<!DOCTYPE html><html lang="zh-CN" data-theme="light"><head><meta charset="UTF-8"><meta http-equiv="X-UA-Compatible" content="IE=edge"><meta name="viewport" content="width=device-width, initial-scale=1.0,viewport-fit=cover"><title>15概念设计 | funtim的博客</title><meta name="author" content="funtim41@gmail.com"><meta name="copyright" content="funtim41@gmail.com"><meta name="format-detection" content="telephone=no"><meta name="theme-color" content="#ffffff"><meta name="description" content="概念设计本章讨论用于在族文档中创建复杂几何图形的Revit API的概念设计功能。通过添加新对象（点和通过这些点的样条曲线）来支持形状制作。可以分割、填充图案和嵌板化生成的曲面，以创建具有持久参数关系的可构建形状。 本节中的页面  点和曲线对象 形状 曲面的几何化 自适应构件 创建.addin清单文件  点和曲线对象参照点是在概念设计环境的XYZ工作空间中指定位置的元素。可以创建参照点来设计和打印">
<meta property="og:type" content="article">
<meta property="og:title" content="15概念设计">
<meta property="og:url" content="https://funtim41.github.io/2024/12/05/Revit%E4%BA%8C%E5%BC%80%E6%8C%87%E5%8D%97/15%E6%A6%82%E5%BF%B5%E8%AE%BE%E8%AE%A1/">
<meta property="og:site_name" content="funtim的博客">
<meta property="og:description" content="概念设计本章讨论用于在族文档中创建复杂几何图形的Revit API的概念设计功能。通过添加新对象（点和通过这些点的样条曲线）来支持形状制作。可以分割、填充图案和嵌板化生成的曲面，以创建具有持久参数关系的可构建形状。 本节中的页面  点和曲线对象 形状 曲面的几何化 自适应构件 创建.addin清单文件  点和曲线对象参照点是在概念设计环境的XYZ工作空间中指定位置的元素。可以创建参照点来设计和打印">
<meta property="og:locale" content="zh_CN">
<meta property="og:image" content="https://funtim41.github.io/images/4stars.png">
<meta property="article:published_time" content="2024-12-05T13:44:10.000Z">
<meta property="article:modified_time" content="2025-01-13T14:20:18.215Z">
<meta property="article:author" content="funtim41@gmail.com">
<meta property="article:tag" content="Revit">
<meta name="twitter:card" content="summary">
<meta name="twitter:image" content="https://funtim41.github.io/images/4stars.png"><link rel="shortcut icon" href="/images/OIP.jfif"><link rel="canonical" href="https://funtim41.github.io/2024/12/05/Revit%E4%BA%8C%E5%BC%80%E6%8C%87%E5%8D%97/15%E6%A6%82%E5%BF%B5%E8%AE%BE%E8%AE%A1/"><link rel="preconnect" href="//cdn.jsdelivr.net"/><link rel="stylesheet" href="/css/index.css"><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free/css/all.min.css"><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/node-snackbar/dist/snackbar.min.css" media="print" onload="this.media='all'"><script>
    (() => {
      
    const saveToLocal = {
      set: (key, value, ttl) => {
        if (!ttl) return
        const expiry = Date.now() + ttl * 86400000
        localStorage.setItem(key, JSON.stringify({ value, expiry }))
      },
      get: key => {
        const itemStr = localStorage.getItem(key)
        if (!itemStr) return undefined
        const { value, expiry } = JSON.parse(itemStr)
        if (Date.now() > expiry) {
          localStorage.removeItem(key)
          return undefined
        }
        return value
      }
    }

    window.btf = {
      saveToLocal,
      getScript: (url, attr = {}) => new Promise((resolve, reject) => {
        const script = document.createElement('script')
        script.src = url
        script.async = true
        Object.entries(attr).forEach(([key, val]) => script.setAttribute(key, val))
        script.onload = script.onreadystatechange = () => {
          if (!script.readyState || /loaded|complete/.test(script.readyState)) resolve()
        }
        script.onerror = reject
        document.head.appendChild(script)
      }),
      getCSS: (url, id) => new Promise((resolve, reject) => {
        const link = document.createElement('link')
        link.rel = 'stylesheet'
        link.href = url
        if (id) link.id = id
        link.onload = link.onreadystatechange = () => {
          if (!link.readyState || /loaded|complete/.test(link.readyState)) resolve()
        }
        link.onerror = reject
        document.head.appendChild(link)
      }),
      addGlobalFn: (key, fn, name = false, parent = window) => {
        if (!false && key.startsWith('pjax')) return
        const globalFn = parent.globalFn || {}
        globalFn[key] = globalFn[key] || {}
        globalFn[key][name || Object.keys(globalFn[key]).length] = fn
        parent.globalFn = globalFn
      }
    }
  
      
      const activateDarkMode = () => {
        document.documentElement.setAttribute('data-theme', 'dark')
        if (document.querySelector('meta[name="theme-color"]') !== null) {
          document.querySelector('meta[name="theme-color"]').setAttribute('content', '#0d0d0d')
        }
      }
      const activateLightMode = () => {
        document.documentElement.setAttribute('data-theme', 'light')
        if (document.querySelector('meta[name="theme-color"]') !== null) {
          document.querySelector('meta[name="theme-color"]').setAttribute('content', '#ffffff')
        }
      }

      btf.activateDarkMode = activateDarkMode
      btf.activateLightMode = activateLightMode

      const theme = saveToLocal.get('theme')
    
          theme === 'dark' ? activateDarkMode() : theme === 'light' ? activateLightMode() : null
        
      
      const asideStatus = saveToLocal.get('aside-status')
      if (asideStatus !== undefined) {
        document.documentElement.classList.toggle('hide-aside', asideStatus === 'hide')
      }
    
      
    const detectApple = () => {
      if (/iPad|iPhone|iPod|Macintosh/.test(navigator.userAgent)) {
        document.documentElement.classList.add('apple')
      }
    }
    detectApple()
  
    })()
  </script><script>const GLOBAL_CONFIG = {
  root: '/',
  algolia: undefined,
  localSearch: {"path":"/search.xml","preload":false,"top_n_per_article":1,"unescape":false,"languages":{"hits_empty":"未找到符合您查询的内容：${query}","hits_stats":"共找到 ${hits} 篇文章"}},
  translate: undefined,
  highlight: {"plugin":"highlight.js","highlightCopy":true,"highlightLang":true,"highlightHeightLimit":false,"highlightFullpage":false,"highlightMacStyle":false},
  copy: {
    success: '复制成功',
    error: '复制失败',
    noSupport: '浏览器不支持'
  },
  relativeDate: {
    homepage: false,
    post: false
  },
  runtime: '',
  dateSuffix: {
    just: '刚刚',
    min: '分钟前',
    hour: '小时前',
    day: '天前',
    month: '个月前'
  },
  copyright: {"limitCount":150,"languages":{"author":"作者: funtim41@gmail.com","link":"链接: ","source":"来源: funtim的博客","info":"著作权归作者所有。商业转载请联系作者获得授权，非商业转载请注明出处。"}},
  lightbox: 'null',
  Snackbar: {"chs_to_cht":"已切换为繁体中文","cht_to_chs":"已切换为简体中文","day_to_night":"已切换为深色模式","night_to_day":"已切换为浅色模式","bgLight":"#49b1f5","bgDark":"#1f1f1f","position":"bottom-left"},
  infinitegrid: {
    js: 'https://cdn.jsdelivr.net/npm/@egjs/infinitegrid/dist/infinitegrid.min.js',
    buttonText: '加载更多'
  },
  isPhotoFigcaption: false,
  islazyload: false,
  isAnchor: true,
  percent: {
    toc: true,
    rightside: true,
  },
  autoDarkmode: false
}</script><script id="config-diff">var GLOBAL_CONFIG_SITE = {
  title: '15概念设计',
  isPost: true,
  isHome: false,
  isHighlightShrink: false,
  isToc: true,
  isShuoshuo: false
}</script><link rel="stylesheet" href="/css/bar.css"><meta name="generator" content="Hexo 7.3.0"></head><body><div id="web_bg" style="background: Color(#995a82);"></div><div id="sidebar"><div id="menu-mask"></div><div id="sidebar-menus"><div class="avatar-img text-center"><img src="/images/4stars.png" onerror="onerror=null;src='/img/friend_404.gif'" alt="avatar"/></div><div class="site-data text-center"><a href="/archives/"><div class="headline">文章</div><div class="length-num">67</div></a><a href="/tags/"><div class="headline">标签</div><div class="length-num">5</div></a><a href="/categories/"><div class="headline">分类</div><div class="length-num">7</div></a></div><div class="menus_items"><div class="menus_item"><a class="site-page" href="/"><i class="fa-fw fas fa-home"></i><span> Home</span></a></div><div class="menus_item"><a class="site-page" href="/archives/"><i class="fa-fw fas fa-archive"></i><span> Timeline</span></a></div><div class="menus_item"><a class="site-page" href="/tags/"><i class="fa-fw fas fa-tags"></i><span> Tags</span></a></div><div class="menus_item"><a class="site-page" href="/categories/"><i class="fa-fw fas fa-folder-open"></i><span> Categories</span></a></div><div class="menus_item"><a class="site-page" href="/Links/"><i class="fa-fw fas fa-link"></i><span> Links</span></a></div><div class="menus_item"><a class="site-page" href="/about/"><i class="fa-fw fas fa-heart"></i><span> About</span></a></div></div></div></div><div class="post" id="body-wrap"><header class="post-bg fixed" id="page-header" style="background-image: url(/images/topback.jpg);"><nav id="nav"><span id="blog-info"><a class="nav-site-title" href="/"><img class="site-icon" src="/images/OIP.jfif" alt="Logo"><span class="site-name">funtim的博客</span></a><a class="nav-page-title" href="/"><span class="site-name">15概念设计</span></a></span><div id="menus"><div id="search-button"><span class="site-page social-icon search"><i class="fas fa-search fa-fw"></i><span> 搜索</span></span></div><div class="menus_items"><div class="menus_item"><a class="site-page" href="/"><i class="fa-fw fas fa-home"></i><span> Home</span></a></div><div class="menus_item"><a class="site-page" href="/archives/"><i class="fa-fw fas fa-archive"></i><span> Timeline</span></a></div><div class="menus_item"><a class="site-page" href="/tags/"><i class="fa-fw fas fa-tags"></i><span> Tags</span></a></div><div class="menus_item"><a class="site-page" href="/categories/"><i class="fa-fw fas fa-folder-open"></i><span> Categories</span></a></div><div class="menus_item"><a class="site-page" href="/Links/"><i class="fa-fw fas fa-link"></i><span> Links</span></a></div><div class="menus_item"><a class="site-page" href="/about/"><i class="fa-fw fas fa-heart"></i><span> About</span></a></div></div><div id="toggle-menu"><span class="site-page"><i class="fas fa-bars fa-fw"></i></span></div></div></nav><div id="post-info"><h1 class="post-title">15概念设计</h1><div id="post-meta"><div class="meta-firstline"><span class="post-meta-date"><i class="far fa-calendar-alt fa-fw post-meta-icon"></i><span class="post-meta-label">发表于</span><time class="post-meta-date-created" datetime="2024-12-05T13:44:10.000Z" title="发表于 2024-12-05 21:44:10">2024-12-05</time><span class="post-meta-separator">|</span><i class="fas fa-history fa-fw post-meta-icon"></i><span class="post-meta-label">更新于</span><time class="post-meta-date-updated" datetime="2025-01-13T14:20:18.215Z" title="更新于 2025-01-13 22:20:18">2025-01-13</time></span><span class="post-meta-categories"><span class="post-meta-separator">|</span><i class="fas fa-inbox fa-fw post-meta-icon"></i><a class="post-meta-categories" href="/categories/Revit%E4%BA%8C%E6%AC%A1%E5%BC%80%E5%8F%91%E4%BA%BA%E5%91%98%E6%8C%87%E5%8D%97/">Revit二次开发人员指南</a></span></div><div class="meta-secondline"><span class="post-meta-separator">|</span><span class="post-meta-pv-cv" id="" data-flag-title=""><i class="far fa-eye fa-fw post-meta-icon"></i><span class="post-meta-label">浏览量:</span><span id="busuanzi_value_page_pv"><i class="fa-solid fa-spinner fa-spin"></i></span></span></div></div></div></header><main class="layout" id="content-inner"><div id="post"><article class="container post-content" id="article-container"><h1 id="概念设计"><a href="#概念设计" class="headerlink" title="概念设计"></a><a target="_blank" rel="noopener" href="https://help.autodesk.com/view/RVT/2018/ENU/?guid=Revit_API_Revit_API_Developers_Guide_Revit_Geometric_Elements_Conceptual_Design_html">概念设计</a></h1><p>本章讨论用于在族文档中创建复杂几何图形的Revit API的概念设计功能。通过添加新对象（点和通过这些点的样条曲线）来支持形状制作。可以分割、填充图案和嵌板化生成的曲面，以创建具有持久参数关系的可构建形状。</p>
<p>本节中的页面</p>
<ul>
<li>点和曲线对象</li>
<li>形状</li>
<li>曲面的几何化</li>
<li>自适应构件</li>
<li>创建.addin清单文件</li>
</ul>
<h2 id="点和曲线对象"><a href="#点和曲线对象" class="headerlink" title="点和曲线对象"></a>点和曲线对象</h2><p>参照点是在概念设计环境的XYZ工作空间中指定位置的元素。可以创建参照点来设计和打印直线、样条曲线和形状。可以将ReferencePoint添加到ReferencePointArray，然后用于创建CurveByPoints，而CurveByPoints又可用于创建形状。</p>
<p>下面的示例演示如何创建CurveByPoints对象。请参见下一节中的“创建放样形状”示例，了解如何从多个CurveByPoints对象创建形状。</p>
<p>代码区域14-1：创建新的CurveByPoints</p>
<figure class="highlight c#"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br><span class="line">23</span><br><span class="line">24</span><br></pre></td><td class="code"><pre><span class="line"><span class="comment">//体量中创建</span></span><br><span class="line">ReferencePointArray rpa = <span class="keyword">new</span> ReferencePointArray();</span><br><span class="line"></span><br><span class="line">XYZ xyz = document.Application.Create.NewXYZ(<span class="number">0</span>, <span class="number">0</span>, <span class="number">0</span>);</span><br><span class="line">ReferencePoint rp = document.FamilyCreate.NewReferencePoint(xyz);</span><br><span class="line">rpa.Append(rp);</span><br><span class="line"></span><br><span class="line">xyz = document.Application.Create.NewXYZ(<span class="number">0</span>, <span class="number">30</span>, <span class="number">10</span>);</span><br><span class="line">rp = document.FamilyCreate.NewReferencePoint(xyz);</span><br><span class="line">rpa.Append(rp);</span><br><span class="line"></span><br><span class="line">xyz = document.Application.Create.NewXYZ(<span class="number">0</span>, <span class="number">60</span>, <span class="number">0</span>);</span><br><span class="line">rp = document.FamilyCreate.NewReferencePoint(xyz);</span><br><span class="line">rpa.Append(rp);</span><br><span class="line"></span><br><span class="line">xyz = document.Application.Create.NewXYZ(<span class="number">0</span>, <span class="number">100</span>, <span class="number">30</span>);</span><br><span class="line">rp = document.FamilyCreate.NewReferencePoint(xyz);</span><br><span class="line">rpa.Append(rp);</span><br><span class="line"></span><br><span class="line">xyz = document.Application.Create.NewXYZ(<span class="number">0</span>, <span class="number">150</span>, <span class="number">0</span>);</span><br><span class="line">rp = document.FamilyCreate.NewReferencePoint(xyz);</span><br><span class="line">rpa.Append(rp);</span><br><span class="line"></span><br><span class="line">CurveByPoints curve = document.FamilyCreate.NewCurveByPoints(rpa);</span><br></pre></td></tr></table></figure>

<p><img src="https://help.autodesk.com/cloudhelp/2018/ENU/Revit-API/images/GUID-91A84A22-3B88-45F4-B7CE-8D75F685A95A-low.png"></p>
<p>图54：CurveByPoints曲线</p>
<p>参照点可以基于XYZ坐标创建，如上例所示，也可以相对于其他几何图元创建，以便当参照几何图元更改时，这些点会移动。这些点使用PointElementReference类的子类创建。这些子类是：</p>
<ul>
<li>PointOnEdge</li>
<li>PointOnEdgeEdgeIntersection</li>
<li>PointOnEdgeFaceIntersection</li>
<li>PointOnFace</li>
<li>PointOnPlane</li>
</ul>
<p>例如，上一个示例中的最后两行代码在CurveByPoints的中间创建了一个参考点。</p>
<p>可以使用模型线或参照线创建形状。模型线在创建过程中由形状“使用”，不再作为单独的图元存在。另一方面，参照线在形状创建后仍然存在，如果移动它们，可能会改变形状。虽然API没有ReferenceLine类，但可以使用ModelCurve.ChangeToReferenceLine（）方法将模型线更改为参考线。</p>
<p>代码区域14-2：使用参照线创建形状</p>
<figure class="highlight c#"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br><span class="line">23</span><br><span class="line">24</span><br><span class="line">25</span><br><span class="line">26</span><br><span class="line">27</span><br><span class="line">28</span><br><span class="line">29</span><br><span class="line">30</span><br><span class="line">31</span><br><span class="line">32</span><br><span class="line">33</span><br><span class="line">34</span><br><span class="line">35</span><br><span class="line">36</span><br><span class="line">37</span><br><span class="line">38</span><br><span class="line">39</span><br><span class="line">40</span><br><span class="line">41</span><br><span class="line">42</span><br><span class="line">43</span><br><span class="line">44</span><br><span class="line">45</span><br><span class="line">46</span><br><span class="line">47</span><br><span class="line">48</span><br><span class="line">49</span><br><span class="line">50</span><br><span class="line">51</span><br><span class="line">52</span><br></pre></td><td class="code"><pre><span class="line"><span class="comment">//demo失败（报错，无效操作）</span></span><br><span class="line"><span class="function"><span class="keyword">private</span> FormArray <span class="title">CreateRevolveForm</span>(<span class="params">Document document</span>)</span></span><br><span class="line">&#123;</span><br><span class="line">    FormArray revolveForms = <span class="literal">null</span>;</span><br><span class="line"></span><br><span class="line">    <span class="comment">// Create one profile</span></span><br><span class="line">    ReferenceArray ref_ar = <span class="keyword">new</span> ReferenceArray();</span><br><span class="line"></span><br><span class="line">    XYZ ptA = <span class="keyword">new</span> XYZ(<span class="number">0</span>, <span class="number">0</span>, <span class="number">10</span>);</span><br><span class="line">    XYZ ptB = <span class="keyword">new</span> XYZ(<span class="number">100</span>, <span class="number">0</span>, <span class="number">10</span>);</span><br><span class="line">    Line line = Line.CreateBound(ptA, ptB);</span><br><span class="line">    ModelCurve modelcurve = MakeLine(document, ptA, ptB);</span><br><span class="line">    ref_ar.Append(modelcurve.GeometryCurve.Reference);</span><br><span class="line"></span><br><span class="line">    ptA = <span class="keyword">new</span> XYZ(<span class="number">100</span>, <span class="number">0</span>, <span class="number">10</span>);</span><br><span class="line">    ptB = <span class="keyword">new</span> XYZ(<span class="number">100</span>, <span class="number">100</span>, <span class="number">10</span>);</span><br><span class="line">    modelcurve = MakeLine(document, ptA, ptB);</span><br><span class="line">    ref_ar.Append(modelcurve.GeometryCurve.Reference);</span><br><span class="line"></span><br><span class="line">    ptA = <span class="keyword">new</span> XYZ(<span class="number">100</span>, <span class="number">100</span>, <span class="number">10</span>);</span><br><span class="line">    ptB = <span class="keyword">new</span> XYZ(<span class="number">0</span>, <span class="number">0</span>, <span class="number">10</span>);</span><br><span class="line">    modelcurve = MakeLine(document, ptA, ptB);</span><br><span class="line">    ref_ar.Append(modelcurve.GeometryCurve.Reference);</span><br><span class="line"></span><br><span class="line">    <span class="comment">// Create axis for revolve form</span></span><br><span class="line">    ptA = <span class="keyword">new</span> XYZ(<span class="number">-5</span>, <span class="number">0</span>, <span class="number">10</span>);</span><br><span class="line">    ptB = <span class="keyword">new</span> XYZ(<span class="number">-5</span>, <span class="number">10</span>, <span class="number">10</span>);</span><br><span class="line">    ModelCurve axis = MakeLine(document, ptA, ptB);</span><br><span class="line"></span><br><span class="line">    <span class="comment">// make axis a Reference Line</span></span><br><span class="line">    axis.ChangeToReferenceLine();</span><br><span class="line"></span><br><span class="line">    <span class="comment">// Typically this operation produces only a single form, </span></span><br><span class="line">    <span class="comment">// but some combinations of arguments will create multiple froms from a single profile.</span></span><br><span class="line">    revolveForms = document.FamilyCreate.NewRevolveForms(<span class="literal">true</span>, ref_ar, axis.GeometryCurve.Reference, <span class="number">0</span>, Math.PI / <span class="number">4</span>);</span><br><span class="line"></span><br><span class="line">    <span class="keyword">return</span> revolveForms;</span><br><span class="line">&#125;</span><br><span class="line"></span><br><span class="line"><span class="function"><span class="keyword">public</span> ModelCurve <span class="title">MakeLine</span>(<span class="params">Document doc, XYZ ptA, XYZ ptB</span>)</span></span><br><span class="line">&#123;</span><br><span class="line">    Autodesk.Revit.ApplicationServices.Application app = doc.Application;</span><br><span class="line">    <span class="comment">// Create plane by the points</span></span><br><span class="line">    Line line = Line.CreateBound(ptA, ptB);</span><br><span class="line">    XYZ norm = ptA.CrossProduct(ptB);</span><br><span class="line">    <span class="keyword">if</span> (norm.IsZeroLength()) norm = XYZ.BasisZ;</span><br><span class="line">    Plane plane = Plane.CreateByNormalAndOrigin(norm, ptB);</span><br><span class="line">    SketchPlane skplane = SketchPlane.Create(doc, plane);</span><br><span class="line">    <span class="comment">// Create line here</span></span><br><span class="line">    ModelCurve modelcurve = doc.FamilyCreate.NewModelCurve(line, skplane);</span><br><span class="line">    <span class="keyword">return</span> modelcurve;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<p><img src="https://help.autodesk.com/cloudhelp/2018/ENU/Revit-API/images/GUID-F5F29826-D2EA-4007-8C3F-8F30975261C4-low.png"></p>
<p>图55：生成的Revolve表单</p>
<h2 id="形状"><a href="#形状" class="headerlink" title="形状"></a>形状</h2><h3 id="创建形状"><a href="#创建形状" class="headerlink" title="创建形状"></a>创建形状</h3><p>与族创建类似，概念设计环境提供了创建新形状的功能。可以创建以下类型的形状：拉伸、旋转、放样、放样融合、放样和曲面形状。体量族不使用族创建中使用的“混合”、“拉伸”、“旋转”、“放样”和“放样融合”类，而是将“形状”类用于所有类型的形状。</p>
<p>拉伸形状是从平面的闭合曲线回路创建的。旋转形状是根据轮廓和与轮廓在同一平面上的直线创建的，轮廓是围绕其旋转形状以创建三维形状的轴。放样形状是从沿沿着平面路径放样的二维轮廓创建的。放样融合是从多个轮廓创建的，每个轮廓都是平面的，沿沿着单个曲线放样。放样形状由位于不同平面上的两个或多个截面轮廓创建。单个曲面形状是从轮廓创建的，类似于拉伸，但不指定高度。</p>
<p>下面的示例创建一个简单的拉伸形状。请注意，由于用于创建形状的ModelCurves不会转换为参照线，因此它们将由生成的形状使用。</p>
<p>代码区域14-3：创建拉伸形状</p>
<figure class="highlight c#"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br><span class="line">23</span><br><span class="line">24</span><br><span class="line">25</span><br><span class="line">26</span><br><span class="line">27</span><br><span class="line">28</span><br><span class="line">29</span><br><span class="line">30</span><br><span class="line">31</span><br><span class="line">32</span><br><span class="line">33</span><br><span class="line">34</span><br><span class="line">35</span><br><span class="line">36</span><br><span class="line">37</span><br><span class="line">38</span><br><span class="line">39</span><br><span class="line">40</span><br><span class="line">41</span><br><span class="line">42</span><br><span class="line">43</span><br><span class="line">44</span><br><span class="line">45</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="keyword">private</span> Form <span class="title">CreateExtrusionForm</span>(<span class="params">Autodesk.Revit.DB.Document document</span>)</span></span><br><span class="line">&#123;</span><br><span class="line">    Form extrusionForm = <span class="literal">null</span>;</span><br><span class="line"></span><br><span class="line">    <span class="comment">// Create one profile</span></span><br><span class="line">    ReferenceArray ref_ar = <span class="keyword">new</span> ReferenceArray();</span><br><span class="line"></span><br><span class="line">    XYZ ptA = <span class="keyword">new</span> XYZ(<span class="number">10</span>, <span class="number">10</span>, <span class="number">0</span>);</span><br><span class="line">    XYZ ptB = <span class="keyword">new</span> XYZ(<span class="number">90</span>, <span class="number">10</span>, <span class="number">0</span>);</span><br><span class="line">    ModelCurve modelcurve = MakeLine(document, ptA, ptB);</span><br><span class="line">    ref_ar.Append(modelcurve.GeometryCurve.Reference);</span><br><span class="line"></span><br><span class="line">    ptA = <span class="keyword">new</span> XYZ(<span class="number">90</span>, <span class="number">10</span>, <span class="number">0</span>);</span><br><span class="line">    ptB = <span class="keyword">new</span> XYZ(<span class="number">10</span>, <span class="number">90</span>, <span class="number">0</span>);</span><br><span class="line">    modelcurve = MakeLine(document, ptA, ptB);</span><br><span class="line">    ref_ar.Append(modelcurve.GeometryCurve.Reference);</span><br><span class="line"></span><br><span class="line">    ptA = <span class="keyword">new</span> XYZ(<span class="number">10</span>, <span class="number">90</span>, <span class="number">0</span>);</span><br><span class="line">    ptB = <span class="keyword">new</span> XYZ(<span class="number">10</span>, <span class="number">10</span>, <span class="number">0</span>);</span><br><span class="line">    modelcurve = MakeLine(document, ptA, ptB);</span><br><span class="line">    ref_ar.Append(modelcurve.GeometryCurve.Reference);</span><br><span class="line"></span><br><span class="line">    <span class="comment">// The extrusion form direction</span></span><br><span class="line">    XYZ direction = <span class="keyword">new</span> XYZ(<span class="number">0</span>, <span class="number">0</span>, <span class="number">50</span>);</span><br><span class="line"></span><br><span class="line">    extrusionForm = document.FamilyCreate.NewExtrusionForm(<span class="literal">true</span>, ref_ar, direction);</span><br><span class="line"></span><br><span class="line">    <span class="built_in">int</span> profileCount = extrusionForm.ProfileCount;</span><br><span class="line"></span><br><span class="line">    <span class="keyword">return</span> extrusionForm;</span><br><span class="line">&#125;</span><br><span class="line"></span><br><span class="line"><span class="function"><span class="keyword">public</span> ModelCurve <span class="title">MakeLine</span>(<span class="params">Document doc, XYZ ptA, XYZ ptB</span>)</span></span><br><span class="line">&#123;</span><br><span class="line">    Autodesk.Revit.ApplicationServices.Application app = doc.Application;</span><br><span class="line">    <span class="comment">// Create plane by the points</span></span><br><span class="line">    Line line = Line.CreateBound(ptA, ptB);</span><br><span class="line">    XYZ norm = ptA.CrossProduct(ptB);</span><br><span class="line">    <span class="keyword">if</span> (norm.IsZeroLength()) norm = XYZ.BasisZ;</span><br><span class="line">    Plane plane = Plane.CreateByNormalAndOrigin(norm, ptB);</span><br><span class="line">    SketchPlane skplane = SketchPlane.Create(doc, plane);</span><br><span class="line">    <span class="comment">// Create line here</span></span><br><span class="line">    ModelCurve modelcurve = doc.FamilyCreate.NewModelCurve(line, skplane);</span><br><span class="line">    <span class="keyword">return</span> modelcurve;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<p><img src="https://help.autodesk.com/cloudhelp/2018/ENU/Revit-API/images/GUID-ACA912B3-A871-4886-8600-A95C293FB2D5-low.png"></p>
<p>图56：所得拉伸形状</p>
<p>下面的示例显示如何使用一系列CurveByPoints对象创建放样形状。</p>
<p>代码区域14-4：创建放样形状</p>
<figure class="highlight c#"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br><span class="line">23</span><br><span class="line">24</span><br><span class="line">25</span><br><span class="line">26</span><br><span class="line">27</span><br><span class="line">28</span><br><span class="line">29</span><br><span class="line">30</span><br><span class="line">31</span><br><span class="line">32</span><br><span class="line">33</span><br><span class="line">34</span><br><span class="line">35</span><br><span class="line">36</span><br><span class="line">37</span><br><span class="line">38</span><br><span class="line">39</span><br><span class="line">40</span><br><span class="line">41</span><br><span class="line">42</span><br><span class="line">43</span><br><span class="line">44</span><br><span class="line">45</span><br><span class="line">46</span><br><span class="line">47</span><br><span class="line">48</span><br><span class="line">49</span><br><span class="line">50</span><br><span class="line">51</span><br><span class="line">52</span><br><span class="line">53</span><br><span class="line">54</span><br><span class="line">55</span><br><span class="line">56</span><br><span class="line">57</span><br><span class="line">58</span><br><span class="line">59</span><br><span class="line">60</span><br><span class="line">61</span><br><span class="line">62</span><br><span class="line">63</span><br><span class="line">64</span><br><span class="line">65</span><br><span class="line">66</span><br><span class="line">67</span><br><span class="line">68</span><br><span class="line">69</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="keyword">private</span> Form <span class="title">CreateLoftForm</span>(<span class="params">Autodesk.Revit.Document document</span>)</span></span><br><span class="line">&#123;</span><br><span class="line">        Form loftForm = <span class="literal">null</span>;</span><br><span class="line"></span><br><span class="line">        ReferencePointArray rpa = <span class="keyword">new</span> ReferencePointArray();</span><br><span class="line">        ReferenceArrayArray ref_ar_ar = <span class="keyword">new</span> ReferenceArrayArray();</span><br><span class="line">        ReferenceArray ref_ar = <span class="keyword">new</span> ReferenceArray();</span><br><span class="line">        ReferencePoint rp = <span class="literal">null</span>;</span><br><span class="line">        XYZ xyz = <span class="literal">null</span>;</span><br><span class="line"></span><br><span class="line">        <span class="comment">// make first profile curve for loft</span></span><br><span class="line">        xyz = document.Application.Create.NewXYZ(<span class="number">0</span>, <span class="number">0</span>, <span class="number">0</span>);</span><br><span class="line">        rp = document.FamilyCreate.NewReferencePoint(xyz);</span><br><span class="line">        rpa.Append(rp);</span><br><span class="line"></span><br><span class="line">        xyz = document.Application.Create.NewXYZ(<span class="number">0</span>, <span class="number">50</span>, <span class="number">10</span>);</span><br><span class="line">        rp = document.FamilyCreate.NewReferencePoint(xyz);</span><br><span class="line">        rpa.Append(rp);</span><br><span class="line"></span><br><span class="line">        xyz = document.Application.Create.NewXYZ(<span class="number">0</span>, <span class="number">100</span>, <span class="number">0</span>);</span><br><span class="line">        rp = document.FamilyCreate.NewReferencePoint(xyz);</span><br><span class="line">        rpa.Append(rp);</span><br><span class="line"></span><br><span class="line">        CurveByPoints cbp = document.FamilyCreate.NewCurveByPoints(rpa);</span><br><span class="line">        ref_ar.Append(cbp.GeometryCurve.Reference);</span><br><span class="line">        ref_ar_ar.Append(ref_ar);</span><br><span class="line">        rpa.Clear();</span><br><span class="line">        ref_ar = <span class="keyword">new</span> ReferenceArray();</span><br><span class="line"></span><br><span class="line">        <span class="comment">// make second profile curve for loft</span></span><br><span class="line">        xyz = document.Application.Create.NewXYZ(<span class="number">50</span>, <span class="number">0</span>, <span class="number">0</span>);</span><br><span class="line">        rp = document.FamilyCreate.NewReferencePoint(xyz);</span><br><span class="line">        rpa.Append(rp);</span><br><span class="line"></span><br><span class="line">        xyz = document.Application.Create.NewXYZ(<span class="number">50</span>, <span class="number">50</span>, <span class="number">30</span>);</span><br><span class="line">        rp = document.FamilyCreate.NewReferencePoint(xyz);</span><br><span class="line">        rpa.Append(rp);</span><br><span class="line"></span><br><span class="line">        xyz = document.Application.Create.NewXYZ(<span class="number">50</span>, <span class="number">100</span>, <span class="number">0</span>);</span><br><span class="line">        rp = document.FamilyCreate.NewReferencePoint(xyz);</span><br><span class="line">        rpa.Append(rp);</span><br><span class="line"></span><br><span class="line">        cbp = document.FamilyCreate.NewCurveByPoints(rpa);</span><br><span class="line">        ref_ar.Append(cbp.GeometryCurve.Reference);</span><br><span class="line">        ref_ar_ar.Append(ref_ar);</span><br><span class="line">        rpa.Clear();</span><br><span class="line">        ref_ar = <span class="keyword">new</span> ReferenceArray();</span><br><span class="line"></span><br><span class="line">        <span class="comment">// make third profile curve for loft</span></span><br><span class="line">        xyz = document.Application.Create.NewXYZ(<span class="number">75</span>, <span class="number">0</span>, <span class="number">0</span>);</span><br><span class="line">        rp = document.FamilyCreate.NewReferencePoint(xyz);</span><br><span class="line">        rpa.Append(rp);</span><br><span class="line"></span><br><span class="line">        xyz = document.Application.Create.NewXYZ(<span class="number">75</span>, <span class="number">50</span>, <span class="number">5</span>);</span><br><span class="line">        rp = document.FamilyCreate.NewReferencePoint(xyz);</span><br><span class="line">        rpa.Append(rp);</span><br><span class="line"></span><br><span class="line">        xyz = document.Application.Create.NewXYZ(<span class="number">75</span>, <span class="number">100</span>, <span class="number">0</span>);</span><br><span class="line">        rp = document.FamilyCreate.NewReferencePoint(xyz);</span><br><span class="line">        rpa.Append(rp);</span><br><span class="line"></span><br><span class="line">        cbp = document.FamilyCreate.NewCurveByPoints(rpa);</span><br><span class="line">        ref_ar.Append(cbp.GeometryCurve.Reference);</span><br><span class="line">        ref_ar_ar.Append(ref_ar);</span><br><span class="line"></span><br><span class="line">        loftForm = document.FamilyCreate.NewLoftForm(<span class="literal">true</span>, ref_ar_ar);</span><br><span class="line"></span><br><span class="line">        <span class="keyword">return</span> loftForm;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<p><img src="https://help.autodesk.com/cloudhelp/2018/ENU/Revit-API/images/GUID-8F7F53FC-51B6-4547-86C4-709C11B72FCA-low.png"></p>
<p>图57：生成的放样形状</p>
<h3 id="形状修改"><a href="#形状修改" class="headerlink" title="形状修改"></a>形状修改</h3><p>一旦创建，可以通过改变形状的子元素（即面、边、曲线或顶点）或整个轮廓来修改形状。修改表单的方法包括：</p>
<ul>
<li>AddEdge</li>
<li>AddProfile</li>
<li>DeleteProfile</li>
<li>DeleteSubElement</li>
<li>MoveProfile </li>
<li>MoveSubElement </li>
<li>RotateProfile</li>
<li>RotateSubElement</li>
<li>ScaleSubElement</li>
</ul>
<p>此外，可以通过添加边或轮廓来修改形状，然后可以使用上面列出的方法进行修改。</p>
<p>下面的示例将给定形状的第一条轮廓曲线移动指定的偏移量。相应的图显示了将此代码应用于上一个示例中的放样形式的结果。</p>
<p>代码区域14-5：移动轮廓</p>
<figure class="highlight c#"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="keyword">public</span> <span class="keyword">void</span> <span class="title">MoveForm</span>(<span class="params">Form form</span>)</span></span><br><span class="line">&#123;</span><br><span class="line">        <span class="built_in">int</span> profileCount = form.ProfileCount;</span><br><span class="line">        <span class="keyword">if</span> (form.ProfileCount &gt; <span class="number">0</span>)</span><br><span class="line">        &#123;</span><br><span class="line">                <span class="built_in">int</span> profileIndex = <span class="number">0</span>;   <span class="comment">// modify the first form only</span></span><br><span class="line">                <span class="keyword">if</span> (form.CanManipulateProfile(profileIndex))</span><br><span class="line">                &#123;</span><br><span class="line">                XYZ offset = <span class="keyword">new</span> XYZ(<span class="number">-25</span>, <span class="number">0</span>, <span class="number">0</span>);</span><br><span class="line">                form.MoveProfile(profileIndex, offset);</span><br><span class="line">                &#125;</span><br><span class="line">        &#125;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<p><img src="https://help.autodesk.com/cloudhelp/2018/ENU/Revit-API/images/GUID-BCA27D2B-71B9-40CE-A94E-2858C22B8A08-low.png"></p>
<p>图58：修改后的放样形式</p>
<p>下一个示例演示如何移动给定形状的单个顶点。相应的图演示了此代码对前面的拉伸形状示例的影响</p>
<p>代码区域14-6：移动子元素</p>
<figure class="highlight c#"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="keyword">public</span> <span class="keyword">void</span> <span class="title">MoveSubElement</span>(<span class="params">Form form</span>)</span></span><br><span class="line">&#123;</span><br><span class="line">        <span class="keyword">if</span> (form.ProfileCount &gt; <span class="number">0</span>)</span><br><span class="line">        &#123;</span><br><span class="line">                <span class="built_in">int</span> profileIndex = <span class="number">0</span>;   <span class="comment">// get first profile</span></span><br><span class="line">                ReferenceArray ra = form.get_CurveLoopReferencesOnProfile(profileIndex, <span class="number">0</span>);</span><br><span class="line">                <span class="keyword">foreach</span> (Reference r <span class="keyword">in</span> ra)</span><br><span class="line">                &#123;</span><br><span class="line">                        ReferenceArray ra2 = form.GetControlPoints(r);</span><br><span class="line">                        <span class="keyword">foreach</span> (Reference r2 <span class="keyword">in</span> ra2)</span><br><span class="line">                        &#123;</span><br><span class="line">                                Point vertex = document.GetElement(r2).GetGeometryObjectFromReference(r2) <span class="keyword">as</span> Point;</span><br><span class="line"></span><br><span class="line">                                XYZ offset = <span class="keyword">new</span> XYZ(<span class="number">0</span>, <span class="number">15</span>, <span class="number">0</span>);</span><br><span class="line">                                form.MoveSubElement(r2, offset);</span><br><span class="line">                                <span class="keyword">break</span>;  <span class="comment">// just move the first point</span></span><br><span class="line">                        &#125;</span><br><span class="line">                &#125;</span><br><span class="line">        &#125;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<p>图59：修改拉伸的形状</p>
<h2 id="表面的几何化"><a href="#表面的几何化" class="headerlink" title="表面的几何化"></a>表面的几何化</h2><h3 id="分割表面"><a href="#分割表面" class="headerlink" title="分割表面"></a>分割表面</h3><p>形状的面可以用UV网格划分。可以使用DividedSurface.GetReferencesWithDividedSurface（）和DividedSurface.GetDividedSurfaceForReference（）方法（如后续示例所示）访问分割曲面的数据，也可以在形状上创建新的分割曲面，如下所示。</p>
<p>代码区域14-7：划分表面</p>
<figure class="highlight c#"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br><span class="line">23</span><br><span class="line">24</span><br><span class="line">25</span><br><span class="line">26</span><br><span class="line">27</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="keyword">public</span> <span class="keyword">void</span> <span class="title">DivideSurface</span>(<span class="params">Document document, Form form</span>)</span></span><br><span class="line">&#123;</span><br><span class="line">    Autodesk.Revit.ApplicationServices.Application application = document.Application;</span><br><span class="line">    Options opt = application.Create.NewGeometryOptions();</span><br><span class="line">    opt.ComputeReferences = <span class="literal">true</span>;</span><br><span class="line"></span><br><span class="line">    Autodesk.Revit.DB.GeometryElement geomElem = form.get_Geometry(opt);</span><br><span class="line">    <span class="keyword">foreach</span> (GeometryObject geomObj <span class="keyword">in</span> geomElem)</span><br><span class="line">    &#123;</span><br><span class="line">        Solid solid = geomObj <span class="keyword">as</span> Solid;</span><br><span class="line">        <span class="keyword">foreach</span> (Face face <span class="keyword">in</span> solid.Faces)</span><br><span class="line">        &#123;</span><br><span class="line">            <span class="keyword">if</span> (face.Reference != <span class="literal">null</span>)</span><br><span class="line">            &#123;</span><br><span class="line">                DividedSurface ds = DividedSurface.Create(document,face.Reference);</span><br><span class="line">                <span class="comment">// create a divided surface with fixed number of U and V grid lines</span></span><br><span class="line">                SpacingRule srU = ds.USpacingRule;</span><br><span class="line">                srU.SetLayoutFixedNumber(<span class="number">16</span>, SpacingRuleJustification.Center, <span class="number">0</span>, <span class="number">0</span>);</span><br><span class="line"></span><br><span class="line">                SpacingRule srV = ds.VSpacingRule;</span><br><span class="line">                srV.SetLayoutFixedNumber(<span class="number">24</span>, SpacingRuleJustification.Center, <span class="number">0</span>, <span class="number">0</span>);</span><br><span class="line"></span><br><span class="line">                <span class="keyword">break</span>;  <span class="comment">// just divide one face of form</span></span><br><span class="line">            &#125;</span><br><span class="line">        &#125;</span><br><span class="line">    &#125;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<p><img src="https://help.autodesk.com/cloudhelp/2018/ENU/Revit-API/images/GUID-68B498E3-3756-47BF-8392-1F12F2F8D4ED-low.png"></p>
<p>图60：由UV网格划分的形状面</p>
<p>通过指定DividedSurface的USpacing和VSpacing属性，可以为U和V网格线定义SpacingRule，方法是指定固定的网格数（如上例所示）、网格之间的固定距离或网格之间的最小或最大间距。每个间距规则都需要其他信息，例如对正和网格旋转。</p>
<p>图案化表面</p>
<p>可以对分割的曲面进行阵列。任何内置平铺填充图案都可以应用于分割表面。平铺图案是指定给DividedSurface的ElementType。平铺图案根据UV栅格布局应用于曲面，因此更改DividedSurface的USpacing和VSpacing属性将影响图案化曲面的显示方式。</p>
<p>下面的示例演示如何使用OctagonRotate图案覆盖分割曲面。相应的图显示了将其应用于上一示例中的分割曲面时的外观。注意这个例子还演示了如何在窗体上获取DividedSurface。</p>
<p>代码区域14-8：图案化表面</p>
<figure class="highlight c#"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="keyword">public</span> <span class="keyword">void</span> <span class="title">TileSurface</span>(<span class="params">Document document, Form form</span>)</span></span><br><span class="line">&#123;</span><br><span class="line">    <span class="comment">// cover surface with OctagonRotate tile pattern</span></span><br><span class="line">    TilePatterns tilePatterns = document.Settings.TilePatterns;</span><br><span class="line">    <span class="keyword">foreach</span> (Reference r <span class="keyword">in</span> DividedSurface.GetReferencesWithDividedSurfaces(form))</span><br><span class="line">    &#123;</span><br><span class="line">        DividedSurface ds = DividedSurface.GetDividedSurfaceForReference(document, r);</span><br><span class="line">        ds.ChangeTypeId(tilePatterns.GetTilePattern(TilePatternsBuiltIn.OctagonRotate).Id);</span><br><span class="line">    &#125;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<p>图61：应用于分割表面的平铺图案</p>
<p>除了将内置的平铺填充图案应用于分割表面之外，还可以使用“基于幕墙嵌板填充图案的.rft”样板创建自己的体量嵌板族。然后，可以使用DividedSurface.ChangeTypeId（）方法将这些嵌板族载入体量族并应用于分割曲面。</p>
<p>“族”的下列属性特定于幕墙嵌板族：</p>
<ul>
<li>IsCurtainPanelFamily</li>
<li>CurtainPanelHorizontalSpacing -分隔网格的水平间距</li>
<li>CurtainPanelVerticalSpacing -分隔网格的垂直间距</li>
<li>CurtainPanelTilePattern -平铺图案的选择</li>
</ul>
<p>下面的示例演示如何编辑体量嵌板族，然后将其应用于概念体量文档中的形状。若要运行此示例，请首先使用“Curtain Panel Pattern Based.rft”样板创建一个新的族文档。</p>
<p>代码区域14-9：编辑幕墙嵌板族</p>
<figure class="highlight c#"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br><span class="line">23</span><br><span class="line">24</span><br><span class="line">25</span><br><span class="line">26</span><br><span class="line">27</span><br><span class="line">28</span><br><span class="line">29</span><br><span class="line">30</span><br><span class="line">31</span><br><span class="line">32</span><br><span class="line">33</span><br><span class="line">34</span><br><span class="line">35</span><br><span class="line">36</span><br><span class="line">37</span><br><span class="line">38</span><br><span class="line">39</span><br><span class="line">40</span><br><span class="line">41</span><br><span class="line">42</span><br><span class="line">43</span><br><span class="line">44</span><br><span class="line">45</span><br><span class="line">46</span><br><span class="line">47</span><br><span class="line">48</span><br><span class="line">49</span><br><span class="line">50</span><br><span class="line">51</span><br><span class="line">52</span><br><span class="line">53</span><br><span class="line">54</span><br><span class="line">55</span><br><span class="line">56</span><br><span class="line">57</span><br><span class="line">58</span><br><span class="line">59</span><br></pre></td><td class="code"><pre><span class="line">Family family = document.OwnerFamily;</span><br><span class="line"><span class="keyword">if</span> (family.IsCurtainPanelFamily == <span class="literal">true</span> &amp;&amp;</span><br><span class="line">    family.CurtainPanelTilePattern == TilePatternsBuiltIn.Rectangle)</span><br><span class="line">&#123;</span><br><span class="line">    <span class="comment">// first change spacing of grids in family document</span></span><br><span class="line">    family.CurtainPanelHorizontalSpacing = <span class="number">20</span>;</span><br><span class="line">    family.CurtainPanelVerticalSpacing = <span class="number">30</span>;</span><br><span class="line"></span><br><span class="line">    <span class="comment">// create new points and lines on grid</span></span><br><span class="line">    Autodesk.Revit.ApplicationServices.Application app = document.Application;</span><br><span class="line">    FilteredElementCollector collector = <span class="keyword">new</span> FilteredElementCollector(document);</span><br><span class="line">    ICollection collection = collector.OfClass(<span class="keyword">typeof</span>(ReferencePoint)).ToElements();</span><br><span class="line">    <span class="built_in">int</span> ctr = <span class="number">0</span>;</span><br><span class="line">    ReferencePoint rp0 = <span class="literal">null</span>, rp1 = <span class="literal">null</span>, rp2 = <span class="literal">null</span>, rp3 = <span class="literal">null</span>;</span><br><span class="line">    <span class="keyword">foreach</span> (Autodesk.Revit.DB.Element e <span class="keyword">in</span> collection)</span><br><span class="line">    &#123;</span><br><span class="line">        ReferencePoint rp = e <span class="keyword">as</span> ReferencePoint;</span><br><span class="line">        <span class="keyword">switch</span> (ctr)</span><br><span class="line">        &#123;</span><br><span class="line">            <span class="keyword">case</span> <span class="number">0</span>:</span><br><span class="line">                rp0 = rp;</span><br><span class="line">                <span class="keyword">break</span>;</span><br><span class="line">            <span class="keyword">case</span> <span class="number">1</span>:</span><br><span class="line">                rp1 = rp;</span><br><span class="line">                <span class="keyword">break</span>;</span><br><span class="line">            <span class="keyword">case</span> <span class="number">2</span>:</span><br><span class="line">                rp2 = rp;</span><br><span class="line">                <span class="keyword">break</span>;</span><br><span class="line">            <span class="keyword">case</span> <span class="number">3</span>:</span><br><span class="line">                rp3 = rp;</span><br><span class="line">                <span class="keyword">break</span>;</span><br><span class="line">        &#125;</span><br><span class="line">        ctr++;</span><br><span class="line">    &#125;</span><br><span class="line"></span><br><span class="line">    ReferencePointArray rpAr = <span class="keyword">new</span> ReferencePointArray();</span><br><span class="line">    rpAr.Append(rp0);</span><br><span class="line">    rpAr.Append(rp2);</span><br><span class="line">    CurveByPoints curve1 = document.FamilyCreate.NewCurveByPoints(rpAr);</span><br><span class="line">    PointLocationOnCurve pointLocationOnCurve25 = <span class="keyword">new</span> PointLocationOnCurve(PointOnCurveMeasurementType.NormalizedCurveParameter, <span class="number">0.25</span>, PointOnCurveMeasureFrom.Beginning);</span><br><span class="line">    PointOnEdge poeA = app.Create.NewPointOnEdge(curve1.GeometryCurve.Reference, pointLocationOnCurve25);</span><br><span class="line">    ReferencePoint rpA = document.FamilyCreate.NewReferencePoint(poeA);</span><br><span class="line">    PointLocationOnCurve pointLocationOnCurve75 = <span class="keyword">new</span> PointLocationOnCurve(PointOnCurveMeasurementType.NormalizedCurveParameter, <span class="number">0.75</span>, PointOnCurveMeasureFrom.Beginning);</span><br><span class="line">    PointOnEdge poeB = app.Create.NewPointOnEdge(curve1.GeometryCurve.Reference, pointLocationOnCurve75);</span><br><span class="line">    ReferencePoint rpB = document.FamilyCreate.NewReferencePoint(poeB);</span><br><span class="line"></span><br><span class="line">    rpAr.Clear();</span><br><span class="line">    rpAr.Append(rp1);</span><br><span class="line">    rpAr.Append(rp3);</span><br><span class="line">    CurveByPoints curve2 = document.FamilyCreate.NewCurveByPoints(rpAr);</span><br><span class="line">    PointOnEdge poeC = app.Create.NewPointOnEdge(curve2.GeometryCurve.Reference, pointLocationOnCurve25);</span><br><span class="line">    ReferencePoint rpC = document.FamilyCreate.NewReferencePoint(poeC);</span><br><span class="line">    PointOnEdge poeD = app.Create.NewPointOnEdge(curve2.GeometryCurve.Reference, pointLocationOnCurve75);</span><br><span class="line">    ReferencePoint rpD = document.FamilyCreate.NewReferencePoint(poeD);</span><br><span class="line">&#125;</span><br><span class="line"><span class="keyword">else</span></span><br><span class="line">&#123;</span><br><span class="line">    <span class="keyword">throw</span> <span class="keyword">new</span> Exception(<span class="string">&quot;Please open a curtain family document before calling this command.&quot;</span>);</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<p><img src="https://help.autodesk.com/cloudhelp/2018/ENU/Revit-API/images/GUID-8EECE3F0-4C1F-4B31-9133-D3D64676E7FE-low.png"></p>
<p>图62：幕墙嵌板族</p>
<p><img src="https://help.autodesk.com/cloudhelp/2018/ENU/Revit-API/images/GUID-263500A5-C732-4E47-B9AA-D878AF9E9729-low.png"></p>
<p>图63：指定给分割表面的幕墙嵌板</p>
<h2 id="自适应构件"><a href="#自适应构件" class="headerlink" title="自适应构件"></a>自适应构件</h2><p>自适应组件旨在处理组件需要灵活地适应许多独特的上下文条件的情况。例如，自适应构件可用于通过排列符合用户定义约束的多个构件生成的重复系统中。</p>
<p>下面的代码显示如何将自适应构件族的实例创建到体量族中，并以数学方式设置每个点的位置。</p>
<p>代码区域：创建自适应构件族的实例</p>
<figure class="highlight c#"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="keyword">private</span> <span class="keyword">void</span> <span class="title">CreateAdaptiveComponentInstance</span>(<span class="params">Document document, FamilySymbol symbol</span>)</span></span><br><span class="line">        &#123;</span><br><span class="line">            <span class="comment">// Create a new instance of an adaptive component family</span></span><br><span class="line">            FamilyInstance instance = AdaptiveComponentInstanceUtils.CreateAdaptiveComponentInstance(document, symbol);</span><br><span class="line"></span><br><span class="line">            <span class="comment">// Get the placement points of this instance</span></span><br><span class="line">            <span class="keyword">var</span> placePointIds = <span class="keyword">new</span> List&lt;ElementId&gt;();</span><br><span class="line">            placePointIds = AdaptiveComponentInstanceUtils.GetInstancePlacementPointElementRefIds(instance).ToList();</span><br><span class="line">            <span class="built_in">double</span> x = <span class="number">0</span>;</span><br><span class="line"></span><br><span class="line">            <span class="comment">// Set the position of each placement point</span></span><br><span class="line">            <span class="keyword">foreach</span> (ElementId id <span class="keyword">in</span> placePointIds)</span><br><span class="line">            &#123;</span><br><span class="line">                ReferencePoint point = document.GetElement(id) <span class="keyword">as</span> ReferencePoint;</span><br><span class="line">                point.Position = <span class="keyword">new</span> Autodesk.Revit.DB.XYZ(<span class="number">10</span>*x, <span class="number">10</span>*Math.Cos(x), <span class="number">0</span>);</span><br><span class="line">                x += Math.PI / <span class="number">6</span>;</span><br><span class="line">            &#125;</span><br><span class="line">        &#125;</span><br></pre></td></tr></table></figure>

<p>若要批处理创建自适应组件，可以使用FamilyInstanceCreationData构造函数的重载，该构造函数接受两个参数-FamilySymbol和要初始化自适应实例的XYZ自适应点列表。结合使用Autodesk. Rev. Creation. ItemFactoryBase. NewFamilyInstances 2（）方法（该方法采用FamilyInstanceCreationData对象列表），可以一次添加多个自适应构件。这可能比逐个放置单个自适应组件更有效。</p>
<h2 id="创建-addin清单文件"><a href="#创建-addin清单文件" class="headerlink" title="创建.addin清单文件"></a>创建.addin清单文件</h2><p>HelloWorld.dll文件出现在项目输出目录中。如果要在Revit中调用应用程序，请创建清单文件以将其注册到Revit中。</p>
<p>创建清单文件</p>
<ol>
<li><p>在记事本中创建一个新的文本文件。</p>
</li>
<li><p>增加以下案文：</p>
<p>代码区域30-10：为外部命令创建.addin清单文件</p>
<figure class="highlight c#"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br></pre></td><td class="code"><pre><span class="line">&lt;?xml version=<span class="string">&quot;1.0&quot;</span> encoding=<span class="string">&quot;utf-8&quot;</span> standalone=<span class="string">&quot;no&quot;</span>?&gt;</span><br><span class="line"></span><br><span class="line"></span><br><span class="line">    HelloWorld</span><br><span class="line">    HelloWorld.HelloWorld</span><br><span class="line">    HelloWorld</span><br><span class="line">    Show Hello World.</span><br><span class="line">    AlwaysVisible</span><br><span class="line">    C:\Samples\HelloWorld\HelloWorld\bin\Debug\HelloWorld.dll</span><br><span class="line">    <span class="number">239B</span>D853<span class="number">-36E4</span><span class="number">-461f</span><span class="number">-9171</span>-C5ACEDA4E723</span><br><span class="line">    ADSK</span><br><span class="line">    Autodesk, Inc, www.autodesk.com</span><br></pre></td></tr></table></figure></li>
</ol>
<p>注意：FullClassName包括在项目属性的“应用程序”选项卡上找到的根命名空间。</p>
<p>将文件保存为HelloWorld.addin并将其放在以下位置：</p>
<ul>
<li>C:\ProgramData\Autodesk\Revit\Addins\2018\</li>
</ul>
<p>有关使用清单文件的更多详细信息，请参阅加载项集成。</p>
<h2 id="注：翻译自Revit-API-Developers-Guide"><a href="#注：翻译自Revit-API-Developers-Guide" class="headerlink" title="注：翻译自Revit API Developers Guide"></a><em><strong>注：</strong></em>翻译自<a target="_blank" rel="noopener" href="https://help.autodesk.com/view/RVT/2018/ENU/?guid=Revit_API_Revit_API_Developers_Guide_html">Revit API Developers Guide</a></h2></article><div class="tag_share"><div class="post-meta__tag-list"><a class="post-meta__tags" href="/tags/Revit/">Revit</a></div><div class="post-share"><div class="social-share" data-image="/images/4stars.png" data-sites="facebook,twitter,wechat,weibo,qq"></div><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/butterfly-extsrc/sharejs/dist/css/share.min.css" media="print" onload="this.media='all'"><script src="https://cdn.jsdelivr.net/npm/butterfly-extsrc/sharejs/dist/js/social-share.min.js" defer></script></div></div><nav class="pagination-post" id="pagination"><a class="pagination-related" href="/2024/12/05/Revit%E4%BA%8C%E5%BC%80%E6%8C%87%E5%8D%97/06%E9%80%89%E6%8B%A9/" title="06选择"><div class="cover" style="background: var(--default-bg-color)"></div><div class="info"><div class="info-1"><div class="info-item-1">上一篇</div><div class="info-item-2">06选择</div></div><div class="info-2"><div class="info-item-1">选择您可以使用UIDo.Selection.GetElementIds()方法从当前活动文档中获取所选对象，该方法返回所选元素的ElementIds集合。此方法返回的集合可以直接与FilteredElementCollector一起使用，以筛选选定的元素。 Selection对象还可以用于使用SetElementIds()方法以编程方式更改当前选择。 Pages in this section 本节中的页面  Changing the Selection 更改选择 User Selection 用户选择 Filtered User Selection 筛选的用户选择  更改选择要修改选定的图元，请执行以下操作：  创建新的ElementId列表。 把ElementIds放进去。 使用新列表调用SetElementIds()。  下面的示例说明了如何通过获取当前选择并仅过滤出墙以设置为新选择来更改选定的元素。 代码区域7-1：更改所选元素 123456789101112131415161718192021222324252627282930313233private void...</div></div></div></a><a class="pagination-related" href="/2024/11/29/Revit%E4%BA%8C%E5%BC%80%E6%8C%87%E5%8D%97/32%E5%8A%A8%E6%80%81%E6%A8%A1%E5%9E%8B%E6%9B%B4%E6%96%B0/" title="32动态模型更新"><div class="cover" style="background: var(--default-bg-color)"></div><div class="info text-right"><div class="info-1"><div class="info-item-1">下一篇</div><div class="info-item-2">32动态模型更新</div></div><div class="info-2"><div class="info-item-1">动态模型更新动态模型更新为Revit API应用程序提供了修改Revit模型的能力，作为对模型中发生的更改（当这些更改即将在事务结束时提交时）的反应。Revit API应用程序可以通过实现IUpdater接口并将其注册到UpdaterRegistry类来创建更新程序。注册包括指定模型中的哪些更改应该触发更新程序。 Pages in this section 本节中的页面  实现IUpdater Execute方法 注册更新程序 Exposure to...</div></div></div></a></nav><div class="relatedPosts"><div class="headline"><i class="fas fa-thumbs-up fa-fw"></i><span>相关推荐</span></div><div class="relatedPosts-list"><a class="pagination-related" href="/2024/12/20/RevitApi%E5%90%88%E9%9B%86/Autodesk.%20Revit.DB%20ElementTransformUtils/" title="Autodesk.Revit.DB ElementTransformUtils"><div class="cover" style="background: var(--default-bg-color)"></div><div class="info text-center"><div class="info-1"><div class="info-item-1"><i class="far fa-calendar-alt fa-fw"></i> 2024-12-20</div><div class="info-item-2">Autodesk.Revit.DB ElementTransformUtils</div></div><div class="info-2"><div class="info-item-1">Autodesk. Revit.DB ElementTransformUtils允许元素转换的实用程序集合（例如移动，旋转，镜像和复制）。 语法1public static class ElementTransformUtils    继承层次结构 System Object Autodesk.Revit.DB ElementTransformUtils   方法CanMirrorElement确定是否可以镜像元素。 CanMirrorElements确定是否可以镜像元素。 CopyElement复制元素并将副本放置在给定转换指示的位置。 CopyElements(Document, ICollection ElementId , XYZ)复制一组元素，并将副本放置在给定指示的位置。 CopyElements(Document, ICollection ElementId , Document, Transform, CopyPasteOptions)将一组元素从源文档复制到目标文档。 CopyElements(View, ICollection ElementId ,...</div></div></div></a><a class="pagination-related" href="/2025/02/20/RevitApi%E5%90%88%E9%9B%86/Autodesk.Revit.DB%20Curve/" title="Autodesk.Revit.DB Curve"><div class="cover" style="background: var(--default-bg-color)"></div><div class="info text-center"><div class="info-1"><div class="info-item-1"><i class="far fa-calendar-alt fa-fw"></i> 2025-02-20</div><div class="info-item-2">Autodesk.Revit.DB Curve</div></div><div class="info-2"><div class="info-item-1">Autodesk.Revit.DB Curve参数曲线。 语法1public class Curve : GeometryObject    附注具体曲线由参数方程定义。如果曲线是有界的，它只在参数化中为一个区间定义。否则就是 为参数的所有值定义。 继承层次结构System Object Autodesk.Revit.DB APIObject Autodesk.Revit.DB GeometryObject Autodesk.Revit.DB Curve Autodesk.Revit.DB Arc Autodesk.Revit.DB CylindricalHelix Autodesk.Revit.DB Ellipse Autodesk.Revit.DB HermiteSpline Autodesk.Revit.DB Line Autodesk.Revit.DB...</div></div></div></a><a class="pagination-related" href="/2025/02/16/RevitApi%E5%90%88%E9%9B%86/Autodesk.Revit.ApplicationServices%20Application/" title="Autodesk.Revit.ApplicationServices Application"><div class="cover" style="background: var(--default-bg-color)"></div><div class="info text-center"><div class="info-1"><div class="info-item-1"><i class="far fa-calendar-alt fa-fw"></i> 2025-02-16</div><div class="info-item-2">Autodesk.Revit.ApplicationServices Application</div></div><div class="info-2"><div class="info-item-1">Autodesk.Revit.ApplicationServices Application代表Autodesk Revit应用程序，提供对文档、选项和其他应用程序范围数据和设置的访问。 语法1public class Application : IDisposable    示例123string versionInfo = application.VersionBuild + &quot;\n&quot;					+ application.VersionName + &quot;\n&quot;					+ application.VersionNumber;  继承层次结构System Object Autodesk.Revit.ApplicationServices Application Autodesk.Revit.DB.Macros ApplicationEntryPoint 方法CopyModel将现有模型复制到新文件。允许覆盖同名文件。 ExtractPartAtomFromFamilyFile从族文件的内容写入PartAtom...</div></div></div></a><a class="pagination-related" href="/2024/11/18/RevitApi%E5%90%88%E9%9B%86/Autodesk.Revit.DB%20CurveArray/" title="Autodesk.Revit.DB CurveArray"><div class="cover" style="background: var(--default-bg-color)"></div><div class="info text-center"><div class="info-1"><div class="info-item-1"><i class="far fa-calendar-alt fa-fw"></i> 2024-11-18</div><div class="info-item-2">Autodesk.Revit.DB CurveArray</div></div><div class="info-2"><div class="info-item-1">Autodesk.Revit.DB CurveArray可以包含曲线的数组。 语法1public class CurveArray : APIObject, IEnumerable  继承层次结构System Object ​	Autodesk.Revit.DB APIObject ​		Autodesk.Revit.DB CurveArray 另见CurveArray Members Autodesk.Revit.DB Namespace 构造函数CurveArray创建CurveArray类的新实例 方法Append将曲线添加到数组的末尾。 Clear从数组中删除每条曲线，使其为空。 ForwardIterator将一个向前移动的迭代器添加到数组中。 GetEnumerator将一个向前移动的迭代器添加到数组中。 Insert将指定的曲线插入数组。 ReverseIterator返回一个向后移动的迭代器到数组。 属性IsEmpty测试数组是否为空。 Item获取或设置数组中指定索引处的曲线。 Size返回数组中的曲线数。 注：翻译自Revit Api docs 2018</div></div></div></a><a class="pagination-related" href="/2024/12/10/RevitApi%E5%90%88%E9%9B%86/Autodesk.Revit.DB%20Opening/" title="Autodesk.Revit.DB Opening"><div class="cover" style="background: var(--default-bg-color)"></div><div class="info text-center"><div class="info-1"><div class="info-item-1"><i class="far fa-calendar-alt fa-fw"></i> 2024-12-10</div><div class="info-item-2">Autodesk.Revit.DB Opening</div></div><div class="info-2"><div class="info-item-1">Autodesk.Revit.DB OpeningAutodesk Revit项目或族文档中的洞口。 语法1public class Opening : Element  附注该对象表示各种不同类型的洞口：  墙中由修订项目中的两个边界点创建的矩形洞口。 由应用于屋顶、楼板、天花板、梁、支撑或柱的一组曲线创建的洞口。 一个垂直的竖井开口延伸到一个或多个水平。 在族文档中的墙或天花板上创建的简单洞口。  根据打开的类型，此类的某些属性将不可用。 这个对象派生自Element基对象，并且支持该对象的所有方法，例如检索该对象的参数的能力。此对象还支持访问结构分析模型，但此功能仅适用于Autodesk Revit Structure。 示例123456789101112131415161718192021222324252627282930313233343536373839404142434445464748495051### private void Getinfo_Opening(Opening opening)&#123;    string message =...</div></div></div></a><a class="pagination-related" href="/2024/10/30/RevitApi%E5%90%88%E9%9B%86/Autodesk.Revit.DB%20Document/" title="Autodesk.Revit.DB Document"><div class="cover" style="background: var(--default-bg-color)"></div><div class="info text-center"><div class="info-1"><div class="info-item-1"><i class="far fa-calendar-alt fa-fw"></i> 2024-10-30</div><div class="info-item-2">Autodesk.Revit.DB Document</div></div><div class="info-2"><div class="info-item-1">Autodesk.Revit.DB Document表示打开的 Autodesk Revit 项目的对象。 语法1public class Document : IDisposable    附注Document 对象表示 Autodesk Revit 项目。Revit 可以打开多个项目，并打开这些项目的多个视图。活动视图或最顶层视图将是活动项目，因此是可从 Application 对象获得的活动文档。 继承层次结构 System Object Autodesk.Revit.DB Document Autodesk.Revit.DB.Macros DocumentEntryPoint  方法AcquireCoordinates 不知道是啥，API没给描述  AutoJoinElements 强制 Revit...</div></div></div></a></div></div><hr class="custom-hr"/><div id="post-comment"><div class="comment-head"><div class="comment-headline"><i class="fas fa-comments fa-fw"></i><span> 评论</span></div></div><div class="comment-wrap"><div><div id="giscus-wrap"></div></div></div></div></div><div class="aside-content" id="aside-content"><div class="card-widget card-info text-center"><div class="avatar-img"><img src="/images/4stars.png" onerror="this.onerror=null;this.src='/img/friend_404.gif'" alt="avatar"/></div><div class="author-info-name">funtim41@gmail.com</div><div class="author-info-description">实践-认识-再实践-再认识</div><div class="site-data"><a href="/archives/"><div class="headline">文章</div><div class="length-num">67</div></a><a href="/tags/"><div class="headline">标签</div><div class="length-num">5</div></a><a href="/categories/"><div class="headline">分类</div><div class="length-num">7</div></a></div><a id="card-info-btn" target="_blank" rel="noopener" href="https://github.com/FunTim41"><i class="fab fa-github"></i><span>Follow Me</span></a><div class="card-info-social-icons"><a class="social-icon" href="https://github.com/FunTim41" target="_blank" title="Github"><i class="fab fa-github" style="color: #FFFFFF;"></i></a></div></div><div class="card-widget card-announcement"><div class="item-headline"><i class="fas fa-bullhorn fa-shake"></i><span>公告</span></div><div class="announcement_content">This is my Blog</div></div><div class="sticky_layout"><div class="card-widget" id="card-toc"><div class="item-headline"><i class="fas fa-stream"></i><span>目录</span><span class="toc-percentage"></span></div><div class="toc-content"><ol class="toc"><li class="toc-item toc-level-1"><a class="toc-link" href="#%E6%A6%82%E5%BF%B5%E8%AE%BE%E8%AE%A1"><span class="toc-number">1.</span> <span class="toc-text">概念设计</span></a><ol class="toc-child"><li class="toc-item toc-level-2"><a class="toc-link" href="#%E7%82%B9%E5%92%8C%E6%9B%B2%E7%BA%BF%E5%AF%B9%E8%B1%A1"><span class="toc-number">1.1.</span> <span class="toc-text">点和曲线对象</span></a></li><li class="toc-item toc-level-2"><a class="toc-link" href="#%E5%BD%A2%E7%8A%B6"><span class="toc-number">1.2.</span> <span class="toc-text">形状</span></a><ol class="toc-child"><li class="toc-item toc-level-3"><a class="toc-link" href="#%E5%88%9B%E5%BB%BA%E5%BD%A2%E7%8A%B6"><span class="toc-number">1.2.1.</span> <span class="toc-text">创建形状</span></a></li><li class="toc-item toc-level-3"><a class="toc-link" href="#%E5%BD%A2%E7%8A%B6%E4%BF%AE%E6%94%B9"><span class="toc-number">1.2.2.</span> <span class="toc-text">形状修改</span></a></li></ol></li><li class="toc-item toc-level-2"><a class="toc-link" href="#%E8%A1%A8%E9%9D%A2%E7%9A%84%E5%87%A0%E4%BD%95%E5%8C%96"><span class="toc-number">1.3.</span> <span class="toc-text">表面的几何化</span></a><ol class="toc-child"><li class="toc-item toc-level-3"><a class="toc-link" href="#%E5%88%86%E5%89%B2%E8%A1%A8%E9%9D%A2"><span class="toc-number">1.3.1.</span> <span class="toc-text">分割表面</span></a></li></ol></li><li class="toc-item toc-level-2"><a class="toc-link" href="#%E8%87%AA%E9%80%82%E5%BA%94%E6%9E%84%E4%BB%B6"><span class="toc-number">1.4.</span> <span class="toc-text">自适应构件</span></a></li><li class="toc-item toc-level-2"><a class="toc-link" href="#%E5%88%9B%E5%BB%BA-addin%E6%B8%85%E5%8D%95%E6%96%87%E4%BB%B6"><span class="toc-number">1.5.</span> <span class="toc-text">创建.addin清单文件</span></a></li><li class="toc-item toc-level-2"><a class="toc-link" href="#%E6%B3%A8%EF%BC%9A%E7%BF%BB%E8%AF%91%E8%87%AARevit-API-Developers-Guide"><span class="toc-number">1.6.</span> <span class="toc-text">注：翻译自Revit API Developers Guide</span></a></li></ol></li></ol></div></div><div class="card-widget card-recent-post"><div class="item-headline"><i class="fas fa-history"></i><span>最新文章</span></div><div class="aside-list"><div class="aside-list-item no-cover"><div class="content"><a class="title" href="/2025/01/08/CAD%E4%BA%8C%E5%BC%80/AddInManager/" title="AddInManager">AddInManager</a><time datetime="2025-03-30T03:43:29.617Z" title="更新于 2025-03-30 11:43:29">2025-03-30</time></div></div><div class="aside-list-item no-cover"><div class="content"><a class="title" href="/2025/03/29/Revit%E4%BA%8C%E5%BC%80%E7%A4%BA%E4%BE%8B/%E5%9C%A8Revit%E4%B8%AD%E6%B1%82%E5%86%85%E8%BD%AE%E5%BB%93%E5%8F%8A%E5%A4%96%E8%BD%AE%E5%BB%93/" title="在Revit中求内轮廓及外轮廓">在Revit中求内轮廓及外轮廓</a><time datetime="2025-03-29T06:04:26.007Z" title="更新于 2025-03-29 14:04:26">2025-03-29</time></div></div><div class="aside-list-item no-cover"><div class="content"><a class="title" href="/2025/02/27/RevitApi%E5%90%88%E9%9B%86/Autodesk.Revit.DB%20XYZ%20/" title="Autodesk.Revit.DB XYZ">Autodesk.Revit.DB XYZ</a><time datetime="2025-02-27T12:48:50.709Z" title="更新于 2025-02-27 20:48:50">2025-02-27</time></div></div><div class="aside-list-item no-cover"><div class="content"><a class="title" href="/2025/02/20/RevitApi%E5%90%88%E9%9B%86/Autodesk.Revit.DB%20Curve/" title="Autodesk.Revit.DB Curve">Autodesk.Revit.DB Curve</a><time datetime="2025-02-27T12:28:18.794Z" title="更新于 2025-02-27 20:28:18">2025-02-27</time></div></div><div class="aside-list-item no-cover"><div class="content"><a class="title" href="/2025/02/20/RevitApi%E5%90%88%E9%9B%86/Autodesk.Revit.DB%20Line/" title="Autodesk.Revit.DB Line">Autodesk.Revit.DB Line</a><time datetime="2025-02-27T12:28:08.332Z" title="更新于 2025-02-27 20:28:08">2025-02-27</time></div></div></div></div></div></div></main><footer id="footer" style="background-image: url(/images/topback.jpg);"><div id="footer-wrap"><div class="copyright">&copy;2024 - 2025 By funtim41@gmail.com</div><div class="framework-info"><span>框架 </span><a target="_blank" rel="noopener" href="https://hexo.io">Hexo</a><span class="footer-separator">|</span><span>主题 </span><a target="_blank" rel="noopener" href="https://github.com/jerryc127/hexo-theme-butterfly">Butterfly</a></div><div class="footer_custom_text">学而不思则罔，思而不学则殆。</div></div></footer></div><div id="rightside"><div id="rightside-config-hide"><button id="readmode" type="button" title="阅读模式"><i class="fas fa-book-open"></i></button><button id="darkmode" type="button" title="日间和夜间模式切换"><i class="fas fa-adjust"></i></button><button id="hide-aside-btn" type="button" title="单栏和双栏切换"><i class="fas fa-arrows-alt-h"></i></button></div><div id="rightside-config-show"><button id="rightside-config" type="button" title="设置"><i class="fas fa-cog fa-spin"></i></button><button class="close" id="mobile-toc-button" type="button" title="目录"><i class="fas fa-list-ul"></i></button><a id="to_comment" href="#post-comment" title="前往评论"><i class="fas fa-comments"></i></a><button id="go-up" type="button" title="回到顶部"><span class="scroll-percent"></span><i class="fas fa-arrow-up"></i></button></div></div><div><script src="/js/utils.js"></script><script src="/js/main.js"></script><script src="https://cdn.jsdelivr.net/npm/node-snackbar/dist/snackbar.min.js"></script><script>(() => {
  const panguFn = () => {
    if (typeof pangu === 'object') pangu.autoSpacingPage()
    else {
      btf.getScript('https://cdn.jsdelivr.net/npm/pangu/dist/browser/pangu.min.js')
        .then(() => {
          pangu.autoSpacingPage()
        })
    }
  }

  const panguInit = () => {
    if (false){
      GLOBAL_CONFIG_SITE.isPost && panguFn()
    } else {
      panguFn()
    }
  }

  btf.addGlobalFn('pjaxComplete', panguInit, 'pangu')
  document.addEventListener('DOMContentLoaded', panguInit)
})()</script><div class="js-pjax"><script>(() => {
  const isShuoshuo = GLOBAL_CONFIG_SITE.isShuoshuo
  const option = null

  const getGiscusTheme = theme => theme === 'dark' ? 'dark' : 'light'

  const createScriptElement = config => {
    const ele = document.createElement('script')
    Object.entries(config).forEach(([key, value]) => {
      ele.setAttribute(key, value)
    })
    return ele
  }

  const loadGiscus = (el = document, key) => {
    const mappingConfig = isShuoshuo
      ? { 'data-mapping': 'specific', 'data-term': key }
      : { 'data-mapping': (option && option['data-mapping']) || 'pathname' }

    const giscusConfig = {
      src: 'https://giscus.app/client.js',
      'data-repo': 'FunTim41/funtim41.github.io',
      'data-repo-id': 'R_kgDONjG8ww',
      'data-category-id': 'DIC_kwDONjG8w84Cllg2',
      'data-theme': getGiscusTheme(document.documentElement.getAttribute('data-theme')),
      'data-reactions-enabled': '1',
      crossorigin: 'anonymous',
      async: true,
      ...option,
      ...mappingConfig
    }

    const scriptElement = createScriptElement(giscusConfig)

    el.querySelector('#giscus-wrap').appendChild(scriptElement)

    if (isShuoshuo) {
      window.shuoshuoComment.destroyGiscus = () => {
        if (el.children.length) {
          el.innerHTML = ''
          el.classList.add('no-comment')
        }
      }
    }
  }

  const changeGiscusTheme = theme => {
    const iframe = document.querySelector('#giscus-wrap iframe')
    if (iframe) {
      const message = {
        giscus: {
          setConfig: {
            theme: getGiscusTheme(theme)
          }
        }
      }
      iframe.contentWindow.postMessage(message, 'https://giscus.app')
    }
  }

  btf.addGlobalFn('themeChange', changeGiscusTheme, 'giscus')

  if (isShuoshuo) {
    'Giscus' === 'Giscus'
      ? window.shuoshuoComment = { loadComment: loadGiscus }
      : window.loadOtherComment = loadGiscus
    return
  }

  if ('Giscus' === 'Giscus' || !false) {
    if (false) btf.loadComment(document.getElementById('giscus-wrap'), loadGiscus)
    else loadGiscus()
  } else {
    window.loadOtherComment = loadGiscus
  }
})()</script></div><script defer="defer" id="fluttering_ribbon" mobile="false" src="https://cdn.jsdelivr.net/npm/butterfly-extsrc/dist/canvas-fluttering-ribbon.min.js"></script><script async data-pjax src="//busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js"></script><div id="local-search"><div class="search-dialog"><nav class="search-nav"><span class="search-dialog-title">搜索</span><span id="loading-status"></span><button class="search-close-button"><i class="fas fa-times"></i></button></nav><div class="text-center" id="loading-database"><i class="fas fa-spinner fa-pulse"></i><span>  数据加载中</span></div><div class="search-wrap"><div id="local-search-input"><div class="local-search-box"><input class="local-search-box--input" placeholder="搜索文章" type="text"/></div></div><hr/><div id="local-search-results"></div><div id="local-search-stats-wrap"></div></div></div><div id="search-mask"></div><script src="/js/search/local-search.js"></script></div></div></body></html>