<!DOCTYPE html><html lang="zh-CN" data-theme="light"><head><meta charset="UTF-8"><meta http-equiv="X-UA-Compatible" content="IE=edge"><meta name="viewport" content="width=device-width, initial-scale=1.0,viewport-fit=cover"><title>36点云 | funtim的博客</title><meta name="author" content="funtim41@gmail.com"><meta name="copyright" content="funtim41@gmail.com"><meta name="format-detection" content="telephone=no"><meta name="theme-color" content="#ffffff"><meta name="description" content="点云Revit API提供了两种处理点云的方法。第一种方法允许您创建新的点云实例，读取和过滤点，选择整体点的子集，以及选择要高亮显示或隔离的点。第二种方法允许您使用自己的点云引擎并处理不支持的文件格式（即.pcg、.rcp或.rcs以外的格式），从而向Revit提供点以供用户查看。  客户端API 创建新的点云实例 读取和过滤点 点集选择 控制点云高亮显示 引擎API 注册点云文件扩展名 向Rev">
<meta property="og:type" content="article">
<meta property="og:title" content="36点云">
<meta property="og:url" content="https://funtim41.github.io/2024/12/30/Revit%E4%BA%8C%E5%BC%80%E6%8C%87%E5%8D%97/36%E7%82%B9%E4%BA%91/">
<meta property="og:site_name" content="funtim的博客">
<meta property="og:description" content="点云Revit API提供了两种处理点云的方法。第一种方法允许您创建新的点云实例，读取和过滤点，选择整体点的子集，以及选择要高亮显示或隔离的点。第二种方法允许您使用自己的点云引擎并处理不支持的文件格式（即.pcg、.rcp或.rcs以外的格式），从而向Revit提供点以供用户查看。  客户端API 创建新的点云实例 读取和过滤点 点集选择 控制点云高亮显示 引擎API 注册点云文件扩展名 向Rev">
<meta property="og:locale" content="zh_CN">
<meta property="og:image" content="https://funtim41.github.io/images/4stars.png">
<meta property="article:published_time" content="2024-12-30T04:17:56.000Z">
<meta property="article:modified_time" content="2025-01-13T14:22:41.894Z">
<meta property="article:author" content="funtim41@gmail.com">
<meta property="article:tag" content="Revit">
<meta name="twitter:card" content="summary">
<meta name="twitter:image" content="https://funtim41.github.io/images/4stars.png"><link rel="shortcut icon" href="/images/OIP.jfif"><link rel="canonical" href="https://funtim41.github.io/2024/12/30/Revit%E4%BA%8C%E5%BC%80%E6%8C%87%E5%8D%97/36%E7%82%B9%E4%BA%91/"><link rel="preconnect" href="//cdn.jsdelivr.net"/><link rel="stylesheet" href="/css/index.css"><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free/css/all.min.css"><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/node-snackbar/dist/snackbar.min.css" media="print" onload="this.media='all'"><script>
    (() => {
      
    const saveToLocal = {
      set: (key, value, ttl) => {
        if (!ttl) return
        const expiry = Date.now() + ttl * 86400000
        localStorage.setItem(key, JSON.stringify({ value, expiry }))
      },
      get: key => {
        const itemStr = localStorage.getItem(key)
        if (!itemStr) return undefined
        const { value, expiry } = JSON.parse(itemStr)
        if (Date.now() > expiry) {
          localStorage.removeItem(key)
          return undefined
        }
        return value
      }
    }

    window.btf = {
      saveToLocal,
      getScript: (url, attr = {}) => new Promise((resolve, reject) => {
        const script = document.createElement('script')
        script.src = url
        script.async = true
        Object.entries(attr).forEach(([key, val]) => script.setAttribute(key, val))
        script.onload = script.onreadystatechange = () => {
          if (!script.readyState || /loaded|complete/.test(script.readyState)) resolve()
        }
        script.onerror = reject
        document.head.appendChild(script)
      }),
      getCSS: (url, id) => new Promise((resolve, reject) => {
        const link = document.createElement('link')
        link.rel = 'stylesheet'
        link.href = url
        if (id) link.id = id
        link.onload = link.onreadystatechange = () => {
          if (!link.readyState || /loaded|complete/.test(link.readyState)) resolve()
        }
        link.onerror = reject
        document.head.appendChild(link)
      }),
      addGlobalFn: (key, fn, name = false, parent = window) => {
        if (!false && key.startsWith('pjax')) return
        const globalFn = parent.globalFn || {}
        globalFn[key] = globalFn[key] || {}
        globalFn[key][name || Object.keys(globalFn[key]).length] = fn
        parent.globalFn = globalFn
      }
    }
  
      
      const activateDarkMode = () => {
        document.documentElement.setAttribute('data-theme', 'dark')
        if (document.querySelector('meta[name="theme-color"]') !== null) {
          document.querySelector('meta[name="theme-color"]').setAttribute('content', '#0d0d0d')
        }
      }
      const activateLightMode = () => {
        document.documentElement.setAttribute('data-theme', 'light')
        if (document.querySelector('meta[name="theme-color"]') !== null) {
          document.querySelector('meta[name="theme-color"]').setAttribute('content', '#ffffff')
        }
      }

      btf.activateDarkMode = activateDarkMode
      btf.activateLightMode = activateLightMode

      const theme = saveToLocal.get('theme')
    
          theme === 'dark' ? activateDarkMode() : theme === 'light' ? activateLightMode() : null
        
      
      const asideStatus = saveToLocal.get('aside-status')
      if (asideStatus !== undefined) {
        document.documentElement.classList.toggle('hide-aside', asideStatus === 'hide')
      }
    
      
    const detectApple = () => {
      if (/iPad|iPhone|iPod|Macintosh/.test(navigator.userAgent)) {
        document.documentElement.classList.add('apple')
      }
    }
    detectApple()
  
    })()
  </script><script>const GLOBAL_CONFIG = {
  root: '/',
  algolia: undefined,
  localSearch: {"path":"/search.xml","preload":false,"top_n_per_article":1,"unescape":false,"languages":{"hits_empty":"未找到符合您查询的内容：${query}","hits_stats":"共找到 ${hits} 篇文章"}},
  translate: undefined,
  highlight: {"plugin":"highlight.js","highlightCopy":true,"highlightLang":true,"highlightHeightLimit":false,"highlightFullpage":false,"highlightMacStyle":false},
  copy: {
    success: '复制成功',
    error: '复制失败',
    noSupport: '浏览器不支持'
  },
  relativeDate: {
    homepage: false,
    post: false
  },
  runtime: '',
  dateSuffix: {
    just: '刚刚',
    min: '分钟前',
    hour: '小时前',
    day: '天前',
    month: '个月前'
  },
  copyright: {"limitCount":150,"languages":{"author":"作者: funtim41@gmail.com","link":"链接: ","source":"来源: funtim的博客","info":"著作权归作者所有。商业转载请联系作者获得授权，非商业转载请注明出处。"}},
  lightbox: 'null',
  Snackbar: {"chs_to_cht":"已切换为繁体中文","cht_to_chs":"已切换为简体中文","day_to_night":"已切换为深色模式","night_to_day":"已切换为浅色模式","bgLight":"#49b1f5","bgDark":"#1f1f1f","position":"bottom-left"},
  infinitegrid: {
    js: 'https://cdn.jsdelivr.net/npm/@egjs/infinitegrid/dist/infinitegrid.min.js',
    buttonText: '加载更多'
  },
  isPhotoFigcaption: false,
  islazyload: false,
  isAnchor: true,
  percent: {
    toc: true,
    rightside: true,
  },
  autoDarkmode: false
}</script><script id="config-diff">var GLOBAL_CONFIG_SITE = {
  title: '36点云',
  isPost: true,
  isHome: false,
  isHighlightShrink: false,
  isToc: true,
  isShuoshuo: false
}</script><link rel="stylesheet" href="/css/bar.css"><meta name="generator" content="Hexo 7.3.0"></head><body><div id="web_bg" style="background: Color(#995a82);"></div><div id="sidebar"><div id="menu-mask"></div><div id="sidebar-menus"><div class="avatar-img text-center"><img src="/images/4stars.png" onerror="onerror=null;src='/img/friend_404.gif'" alt="avatar"/></div><div class="site-data text-center"><a href="/archives/"><div class="headline">文章</div><div class="length-num">58</div></a><a href="/tags/"><div class="headline">标签</div><div class="length-num">5</div></a><a href="/categories/"><div class="headline">分类</div><div class="length-num">7</div></a></div><div class="menus_items"><div class="menus_item"><a class="site-page" href="/"><i class="fa-fw fas fa-home"></i><span> Home</span></a></div><div class="menus_item"><a class="site-page" href="/archives/"><i class="fa-fw fas fa-archive"></i><span> Timeline</span></a></div><div class="menus_item"><a class="site-page" href="/tags/"><i class="fa-fw fas fa-tags"></i><span> Tags</span></a></div><div class="menus_item"><a class="site-page" href="/categories/"><i class="fa-fw fas fa-folder-open"></i><span> Categories</span></a></div><div class="menus_item"><a class="site-page" href="/Links/"><i class="fa-fw fas fa-link"></i><span> Links</span></a></div><div class="menus_item"><a class="site-page" href="/about/"><i class="fa-fw fas fa-heart"></i><span> About</span></a></div></div></div></div><div class="post" id="body-wrap"><header class="post-bg fixed" id="page-header" style="background-image: url(/images/topback.jpg);"><nav id="nav"><span id="blog-info"><a class="nav-site-title" href="/"><img class="site-icon" src="/images/OIP.jfif" alt="Logo"><span class="site-name">funtim的博客</span></a><a class="nav-page-title" href="/"><span class="site-name">36点云</span></a></span><div id="menus"><div id="search-button"><span class="site-page social-icon search"><i class="fas fa-search fa-fw"></i><span> 搜索</span></span></div><div class="menus_items"><div class="menus_item"><a class="site-page" href="/"><i class="fa-fw fas fa-home"></i><span> Home</span></a></div><div class="menus_item"><a class="site-page" href="/archives/"><i class="fa-fw fas fa-archive"></i><span> Timeline</span></a></div><div class="menus_item"><a class="site-page" href="/tags/"><i class="fa-fw fas fa-tags"></i><span> Tags</span></a></div><div class="menus_item"><a class="site-page" href="/categories/"><i class="fa-fw fas fa-folder-open"></i><span> Categories</span></a></div><div class="menus_item"><a class="site-page" href="/Links/"><i class="fa-fw fas fa-link"></i><span> Links</span></a></div><div class="menus_item"><a class="site-page" href="/about/"><i class="fa-fw fas fa-heart"></i><span> About</span></a></div></div><div id="toggle-menu"><span class="site-page"><i class="fas fa-bars fa-fw"></i></span></div></div></nav><div id="post-info"><h1 class="post-title">36点云</h1><div id="post-meta"><div class="meta-firstline"><span class="post-meta-date"><i class="far fa-calendar-alt fa-fw post-meta-icon"></i><span class="post-meta-label">发表于</span><time class="post-meta-date-created" datetime="2024-12-30T04:17:56.000Z" title="发表于 2024-12-30 12:17:56">2024-12-30</time><span class="post-meta-separator">|</span><i class="fas fa-history fa-fw post-meta-icon"></i><span class="post-meta-label">更新于</span><time class="post-meta-date-updated" datetime="2025-01-13T14:22:41.894Z" title="更新于 2025-01-13 22:22:41">2025-01-13</time></span><span class="post-meta-categories"><span class="post-meta-separator">|</span><i class="fas fa-inbox fa-fw post-meta-icon"></i><a class="post-meta-categories" href="/categories/Revit%E4%BA%8C%E6%AC%A1%E5%BC%80%E5%8F%91%E4%BA%BA%E5%91%98%E6%8C%87%E5%8D%97/">Revit二次开发人员指南</a></span></div><div class="meta-secondline"><span class="post-meta-separator">|</span><span class="post-meta-pv-cv" id="" data-flag-title=""><i class="far fa-eye fa-fw post-meta-icon"></i><span class="post-meta-label">浏览量:</span><span id="busuanzi_value_page_pv"><i class="fa-solid fa-spinner fa-spin"></i></span></span></div></div></div></header><main class="layout" id="content-inner"><div id="post"><article class="container post-content" id="article-container"><h1 id="点云"><a href="#点云" class="headerlink" title="点云"></a>点云</h1><p>Revit API提供了两种处理点云的方法。第一种方法允许您创建新的点云实例，读取和过滤点，选择整体点的子集，以及选择要高亮显示或隔离的点。第二种方法允许您使用自己的点云引擎并处理不支持的文件格式（即.pcg、.rcp或.rcs以外的格式），从而向Revit提供点以供用户查看。</p>
<ul>
<li>客户端API</li>
<li>创建新的点云实例</li>
<li>读取和过滤点</li>
<li>点集选择</li>
<li>控制点云高亮显示</li>
<li>引擎API<ul>
<li>注册点云文件扩展名</li>
<li>向Revit提供点以进行渲染</li>
</ul>
</li>
</ul>
<p> 本节中的页面</p>
<ul>
<li>点云客户端</li>
<li>点云引擎</li>
</ul>
<h2 id="点云客户端"><a href="#点云客户端" class="headerlink" title="点云客户端"></a>点云客户端</h2><p>点云客户端API支持在Revit中读取和修改点云实例。</p>
<p>点云实例提供的点来自点云引擎，该引擎可以是Revit中的内置引擎，也可以是作为应用程序加载的第三方引擎。客户端点云API应用程序不需要关心引擎如何存储点并将点提供给Revit的详细信息。相反，客户端API可用于创建点云、操作其属性以及读取找到的与给定过滤器匹配的点。</p>
<p>与点云相关的主要类有：</p>
<ul>
<li><strong>PointCloudType</strong> - 加载到Revit文档中的点云类型。每个PointCloudType映射到单个文件或标识符（取决于控制它的点云引擎的类型）。</li>
<li><strong>PointCloudInstance</strong> - Revit项目中某个位置的点云实例。</li>
<li><strong>PointCloudFilter</strong> - 在提取点时确定感兴趣体积的过滤器。</li>
<li><strong>PointCollection</strong> -从实例和过滤器获得的点的集合。</li>
<li><strong>PointIterator</strong> - PointCollection中的点的迭代器。</li>
<li><strong>CloudPoint</strong> - 单个点云点，表示云坐标中的X、Y、Z位置和颜色。</li>
<li><strong>PointCloudOverrides</strong> -及其相关设置类指定要应用于PointCloudInstance元素或元素内扫描的视图存储的图形覆盖。</li>
</ul>
<p><strong>点云文件路径</strong></p>
<p>处理点云的两个重要路径位置可作为只读数据提供：</p>
<ol>
<li>PointCloudType.GetPath（）-从中加载点的链接源的路径</li>
<li>Application.PointCloudsRootPath -点云文件的根路径，Revit使用该路径计算点云文件的相对路径</li>
</ol>
<p><strong>创建点云</strong></p>
<p>要在Revit文档中创建新的点云，请创建PointCloudType，然后使用它创建PointCloudInstance。静态PointCloudType.Create（）方法需要引擎标识符（因为它是由第三方向Revit注册的），或者点云文件的文件扩展名（如果它是受支持的文件类型）。对于非基于文件的引擎，它还需要文件名或标识字符串。在以下示例中，pcg文件用于在Revit文档中创建点云。</p>
<p>代码区域：从rcs文件创建点云</p>
<figure class="highlight c#"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="keyword">private</span> PointCloudInstance <span class="title">CreatePointCloud</span>(<span class="params">Document doc</span>)</span></span><br><span class="line">&#123;</span><br><span class="line">    PointCloudType type = PointCloudType.Create(doc, <span class="string">&quot;rcs&quot;</span>, <span class="string">&quot;c:\32_cafeteria.rcs&quot;</span>);</span><br><span class="line">    <span class="keyword">return</span> (PointCloudInstance.Create(doc, type.Id, Transform.Identity));</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<p><img src="https://help.autodesk.com/cloudhelp/2018/ENU/Revit-API/images/PointCloudInstance.png"></p>
<p>访问点云中的点有两种方法可以访问点云中的点：1.使用lEnumerable接口直接从PointCollection返回迭代resultingl点2。无论<br>采用哪种方式，从PointCloudlnstance访问点集合的第一步是使用PointCloudlnstance方法。GetPoints（PointCloudFilterfilter，double<br>averageDistance,int numPoints）注意，作为Revit和点云引擎使用的搜索算法的结果，可能不会返回所请求的确切点数。虽然第二种选择涉及到直接处理指针，但在遍历大量的点缓冲区时，可能会有性能上的提升。不过，这个选项只能在c#和c++&#x2F;CLI中实现。下面两个例子展示了如何使用这两种方法中的一种来迭代点云的一部分。</p>
<p>代码区域：通过迭代阅读点云点</p>
<figure class="highlight c#"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="keyword">private</span> <span class="keyword">void</span> <span class="title">GetPointCloudDataByIteration</span>(<span class="params">PointCloudInstance pcInstance, PointCloudFilter pointCloudFilter</span>)</span></span><br><span class="line">&#123;</span><br><span class="line">    <span class="comment">// read points by iteration</span></span><br><span class="line">    <span class="built_in">double</span> averageDistance = <span class="number">0.001</span>;</span><br><span class="line">    PointCollection points = pcInstance.GetPoints(pointCloudFilter, averageDistance, <span class="number">10000</span>); <span class="comment">// Get points.  Number of points is determined by the needs of the client</span></span><br><span class="line">    <span class="keyword">foreach</span> (CloudPoint point <span class="keyword">in</span> points)</span><br><span class="line">    &#123;</span><br><span class="line">        <span class="comment">// Process each point</span></span><br><span class="line">        System.Drawing.Color color = System.Drawing.ColorTranslator.FromWin32(point.Color);</span><br><span class="line">        String pointDescription = String.Format(<span class="string">&quot;(&#123;0&#125;, &#123;1&#125;, &#123;2&#125;, &#123;3&#125;&quot;</span>, point.X, point.Y, point.Z, color.ToString());</span><br><span class="line">    &#125;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<p>代码区域：通过指针阅读点云点</p>
<figure class="highlight c#"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="keyword">public</span> <span class="keyword">unsafe</span> <span class="keyword">void</span> <span class="title">GetPointCloudDataByPointer</span>(<span class="params">PointCloudInstance pcInstance, PointCloudFilter pointCloudFilter</span>)</span></span><br><span class="line">&#123;</span><br><span class="line">    <span class="built_in">double</span> averageDistance = <span class="number">0.001</span>;</span><br><span class="line">    PointCollection points = pcInstance.GetPoints(pointCloudFilter, averageDistance, <span class="number">10000</span>);</span><br><span class="line">    CloudPoint pointBuffer = (CloudPoint)points.GetPointBufferPointer().ToPointer();</span><br><span class="line">    <span class="built_in">int</span> totalCount = points.Count;</span><br><span class="line">    <span class="keyword">for</span> (<span class="built_in">int</span> numberOfPoints = <span class="number">0</span>; numberOfPoints &lt; totalCount; numberOfPoints++)</span><br><span class="line">    &#123;</span><br><span class="line">        CloudPoint point = (pointBuffer + numberOfPoints);</span><br><span class="line">        <span class="comment">// Process each point</span></span><br><span class="line">        System.Drawing.Color color = System.Drawing.ColorTranslator.FromWin32(point.Color);</span><br><span class="line">        String pointDescription = String.Format(<span class="string">&quot;(&#123;0&#125;, &#123;1&#125;, &#123;2&#125;, &#123;3&#125;&quot;</span>, point.X, point.Y, point.Z, color.ToString());</span><br><span class="line">    &#125;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<p><strong>过滤器</strong></p>
<p>过滤器用于限制阅读点时搜索的体积，也用于管理点云的显示。可以基于平面边界的集合创建PointCloudFilter。过滤器将检查点是否位于每个输入平面的“正”侧，如平面法线的正方向所指示的。因此，这种过滤器隐含地定义了一个体积，它是对应于所有平面的正半空间的交集。这个体积不必闭合，但它将始终是凸的。</p>
<p>The display of point clouds can be controlled by assigning a filter to:<br>点云的显示可以通过将过滤器分配给以下对象来控制：</p>
<ul>
<li>PointCloudInstance.SetSelectionFilter（）</li>
</ul>
<p>Display of the filtered points will be based on the value of the property:<br>过滤点的显示将基于特性的值：</p>
<ul>
<li>PointCloudInstance.FilterAction</li>
</ul>
<p>如果设置为“无”，则忽略选择过滤器。如果将其设置为“高亮显示”，则通过过滤器的点将高亮显示。如果将其设置为“隔离”（Isolate），则只有通过过滤器的点可见。</p>
<p>以下示例将基于点云的边界框高亮显示点云中的点子集。</p>
<p>代码区域：通过指针阅读点云点</p>
<figure class="highlight c#"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br><span class="line">23</span><br></pre></td><td class="code"><pre><span class="line"><span class="comment">// Filter will match 1/8 of the overall point cloud</span></span><br><span class="line"><span class="comment">// Use the bounding box (filter coordinates are in the coordinates of the model)</span></span><br><span class="line">BoundingBoxXYZ boundingBox = pointCloudInstance.get_BoundingBox(<span class="literal">null</span>);</span><br><span class="line">List planes = <span class="keyword">new</span> List();</span><br><span class="line">XYZ midpoint = (boundingBox.Min + boundingBox.Max) / <span class="number">2.0</span>;</span><br><span class="line"></span><br><span class="line"><span class="comment">// X boundaries</span></span><br><span class="line">planes.Add(Plane.CreateByNormalAndOrigin(XYZ.BasisX, boundingBox.Min));</span><br><span class="line">planes.Add(Plane.CreateByNormalAndOrigin(-XYZ.BasisX, midpoint));</span><br><span class="line"></span><br><span class="line"><span class="comment">// Y boundaries</span></span><br><span class="line">planes.Add(Plane.CreateByNormalAndOrigin(XYZ.BasisY, boundingBox.Min));</span><br><span class="line">planes.Add(Plane.CreateByNormalAndOrigin(-XYZ.BasisY, midpoint));</span><br><span class="line"></span><br><span class="line"><span class="comment">// Z boundaries</span></span><br><span class="line">planes.Add(Plane.CreateByNormalAndOrigin(XYZ.BasisZ, boundingBox.Min));</span><br><span class="line">planes.Add(Plane.CreateByNormalAndOrigin(-XYZ.BasisZ, midpoint));</span><br><span class="line"></span><br><span class="line"><span class="comment">// Create filter</span></span><br><span class="line">PointCloudFilter filter = PointCloudFilterFactory.CreateMultiPlaneFilter(planes);</span><br><span class="line">pointCloudInstance.FilterAction = SelectionFilterAction.Highlight;</span><br><span class="line"></span><br><span class="line"><span class="keyword">return</span> filter;</span><br></pre></td></tr></table></figure>

<p>这是在小管道点云上运行上述示例时的结果：</p>
<p><img src="https://help.autodesk.com/cloudhelp/2018/ENU/Revit-API/images/PointCloudHighlight.jpg"></p>
<p>图：带有选择过滤器的点云</p>
<p>Selection.PickBox（）方法调用一个通用的双击编辑器，让用户在屏幕上指定一个矩形区域，可以与PointCloudFilter结合使用，方法是使用生成的PickedBox来生成过滤器的平面边界。</p>
<p> <strong>扫描</strong></p>
<p>.rcp文件可以包含多个扫描。方法PointCloudInstance.GetScans（）返回一个扫描名称列表，可用于为PointCloudInstance中的每次扫描单独设置可见性和固定颜色覆盖。PointCloudInstance.ContainsScan（）指示给定扫描名称是否包含在点云实例中，而PointCloudInstance.GetScanOrigin（）将以模型坐标返回给定扫描的原点。</p>
<p>区域</p>
<p>扫描区域特定于Autodesk ReCap™。如果点云是在ReCap中创建的，则它可能具有区域。PointCloudInstance.GetRegions（）返回区域名称列表，可用于为PointCloudInstance中的每个区域单独设置可见性和固定颜色覆盖。</p>
<p>覆盖</p>
<p>可以使用Revit API修改指定给给定视图的点云替代设置。这些设置对应于Revit UI中“可见性&#x2F;图形替换”任务窗格的“点云”选项卡上的设置。覆盖可以应用于整个点云实例，也可以应用于该实例中的特定扫描。覆盖选项包括设置点云实例中扫描的可见性、将其设置为固定颜色或基于高程、法线或强度的颜色梯度。PointCloudInstance.SupportsOverrides属性标识支持覆盖设置的点云（基于.rcp或.rcs文件的点云）。</p>
<p>设置点云的替代时涉及以下类：</p>
<ul>
<li><strong>PointCloudOverrides</strong> - 用于获取或设置PointCloudInstance、其扫描之一或PointCloudInstance内特定区域的PointCloudOverrideSettings。</li>
<li><strong>PointCloudOverrideSettings</strong> - 用于获取或设置可见性、颜色模式和PointCloudColorSettings。</li>
<li><strong>PointCloudColorSettings</strong> - 于将特定颜色模式的特定颜色指定给PointCloudInstance元素或其扫描之一。如果PointCloudColorMode为“Noise”或“Normals”，则不适用。</li>
</ul>
<h2 id="点云引擎"><a href="#点云引擎" class="headerlink" title="点云引擎"></a>点云引擎</h2><p>可以实现自定义点云引擎，以向Revit提供云点。</p>
<p>点云引擎可以基于文件，也可以不基于文件。基于文件的实现要求将每个点云映射到磁盘上的单个文件。Revit将允许用户通过选择扩展名与引擎标识符匹配的点云文件，直接在文档中创建新的点云实例。这些文件在Revit中被视为外部链接，必要时可以从“管理链接”对话框中重新加载和重新映射。</p>
<p>非基于文件的引擎实现可以从任何地方（例如，从数据库、从服务器、或从较大聚合文件的一部分）获得点云。由于没有用户可以选择的文件，因此Revit的用户界面不允许用户创建此类型的点云。相反，引擎提供程序提供了一个使用PointCloudType.Create（）和PointCloudInstance.Create（）的自定义命令，以创建和放置此类型的点云。“管理链接”对话框将显示此类型的点云，但由于没有与点云关联的文件，因此用户无法管理、重新加载或重新映射此类型的点云。</p>
<p>无论实现的类型如何，自定义引擎实现都包括以下内容：</p>
<ul>
<li>通过PointCloudEngineRegistry向Revit注册的IPointCloudEngine实现。</li>
<li>IPointCloudAccess的实现，它将响应来自Revit的有关单个点云属性的查询。</li>
<li>IPointSetIterator的实现，它将在请求时向Revit返回点集。</li>
</ul>
<p>为了将点云的点提供给Revit，必须实现两个ReadPoints（）方法：</p>
<ul>
<li>IPointCloudAccess.ReadPoints（）-这在一次性调用中提供一组点，可以从Revit或API调用。Revit在某些显示活动（包括选择预高亮显示）中使用此选项。API客户端也可以通过PointCloudInstance.GetPoints（）直接调用此方法。</li>
<li>IPointSetIterator.ReadPoints（）-这提供了点的子集，作为云中点的更大迭代的一部分。Revit在点云的正常显示期间使用此方法;将重复请求点的数量，直到获得足够的点或显示中的某些内容发生更改。在任何给定的点集迭代过程中，引擎实现必须跟踪哪些点已返回到Revit。</li>
</ul>
<p>有关注册和实施基于文件和非基于文件的点云引擎的完整示例，请参见Revit API SDK附带的Samples目录下的PointCloudEngine文件夹。</p>
<h2 id="注：翻译自Revit-API-Developers-Guide"><a href="#注：翻译自Revit-API-Developers-Guide" class="headerlink" title="注：翻译自Revit API Developers Guide"></a><em><strong>注：</strong></em>翻译自<a target="_blank" rel="noopener" href="https://help.autodesk.com/view/RVT/2018/ENU/?guid=Revit_API_Revit_API_Developers_Guide_html">Revit API Developers Guide</a></h2></article><div class="tag_share"><div class="post-meta__tag-list"><a class="post-meta__tags" href="/tags/Revit/">Revit</a></div><div class="post-share"><div class="social-share" data-image="/images/4stars.png" data-sites="facebook,twitter,wechat,weibo,qq"></div><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/butterfly-extsrc/sharejs/dist/css/share.min.css" media="print" onload="this.media='all'"><script src="https://cdn.jsdelivr.net/npm/butterfly-extsrc/sharejs/dist/js/social-share.min.js" defer></script></div></div><nav class="pagination-post" id="pagination"><a class="pagination-related" href="/2024/12/30/Revit%E4%BA%8C%E5%BC%80%E6%8C%87%E5%8D%97/37%E5%88%86%E6%9E%90/" title="37分析"><div class="cover" style="background: var(--default-bg-color)"></div><div class="info"><div class="info-1"><div class="info-item-1">上一篇</div><div class="info-item-2">37分析</div></div><div class="info-2"><div class="info-item-1">分析相关信息  绿色建筑工作室API  Pages in this section  本节中的页面  能量数据 分析可视化 概念能量分析 详细的能源分析模型  能量数据EnergyDataSettings对象包含gbXML导出和热负荷和冷负荷计算的设置以及概念能量分析的项目级别设置。 EnergyDataSettings对象是从Element基对象派生的。它在每个项目中都是唯一的，类似于ProjectInformation。虽然EnergyDataSettings是Element类的子类，但从Element继承的大多数成员都返回null或空集，但Name、Id、UniqueId和Parameters除外。 下面的代码示例使用EnergyDataSettings类。调用命令后，结果将显示在TaskDialog中。 代码区域28-7：使用EnergyDataSettings类 1234567891011public void GetInfo_EnergyData(Document document)&#123;        EnergyDataSettings...</div></div></div></a><a class="pagination-related" href="/2024/12/30/Revit%E4%BA%8C%E5%BC%80%E6%8C%87%E5%8D%97/35%E6%80%A7%E8%83%BD%E9%A1%BE%E9%97%AE/" title="35性能顾问"><div class="cover" style="background: var(--default-bg-color)"></div><div class="info text-right"><div class="info-1"><div class="info-item-1">下一篇</div><div class="info-item-2">35性能顾问</div></div><div class="info-2"><div class="info-item-1">性能顾问Revit API的性能顾问功能旨在分析文档，并为用户标记可能导致性能下降的任何元素和&#x2F;或设置。Performance Adviser命令执行一组规则并在标准审阅警告对话框中显示其结果。 性能顾问的API由两个类组成：  PerformanceAdviser -一个应用程序范围的对象，具有双重角色，既可以作为运行的规则注册表，以检测潜在的性能问题，也可以作为执行这些问题的引擎 IPerformanceAdviserRule - 允许您为Performance...</div></div></div></a></nav><div class="relatedPosts"><div class="headline"><i class="fas fa-thumbs-up fa-fw"></i><span>相关推荐</span></div><div class="relatedPosts-list"><a class="pagination-related" href="/2024/11/18/RevitApi%E5%90%88%E9%9B%86/Autodesk.Revit.DB%20CurveArray/" title="Autodesk.Revit.DB CurveArray"><div class="cover" style="background: var(--default-bg-color)"></div><div class="info text-center"><div class="info-1"><div class="info-item-1"><i class="far fa-calendar-alt fa-fw"></i> 2024-11-18</div><div class="info-item-2">Autodesk.Revit.DB CurveArray</div></div><div class="info-2"><div class="info-item-1">Autodesk.Revit.DB CurveArray可以包含曲线的数组。 语法1public class CurveArray : APIObject, IEnumerable  继承层次结构System Object ​	Autodesk.Revit.DB APIObject ​		Autodesk.Revit.DB CurveArray 另见CurveArray Members Autodesk.Revit.DB Namespace 构造函数CurveArray创建CurveArray类的新实例 方法Append将曲线添加到数组的末尾。 Clear从数组中删除每条曲线，使其为空。 ForwardIterator将一个向前移动的迭代器添加到数组中。 GetEnumerator将一个向前移动的迭代器添加到数组中。 Insert将指定的曲线插入数组。 ReverseIterator返回一个向后移动的迭代器到数组。 属性IsEmpty测试数组是否为空。 Item获取或设置数组中指定索引处的曲线。 Size返回数组中的曲线数。 注：翻译自Revit Api docs 2018</div></div></div></a><a class="pagination-related" href="/2024/12/20/RevitApi%E5%90%88%E9%9B%86/Autodesk.%20Revit.DB%20ElementTransformUtils/" title="Autodesk.Revit.DB ElementTransformUtils"><div class="cover" style="background: var(--default-bg-color)"></div><div class="info text-center"><div class="info-1"><div class="info-item-1"><i class="far fa-calendar-alt fa-fw"></i> 2024-12-20</div><div class="info-item-2">Autodesk.Revit.DB ElementTransformUtils</div></div><div class="info-2"><div class="info-item-1">Autodesk. Revit.DB ElementTransformUtils允许元素转换的实用程序集合（例如移动，旋转，镜像和复制）。 语法1public static class ElementTransformUtils    继承层次结构 System Object Autodesk.Revit.DB ElementTransformUtils   方法CanMirrorElement确定是否可以镜像元素。 CanMirrorElements确定是否可以镜像元素。 CopyElement复制元素并将副本放置在给定转换指示的位置。 CopyElements(Document, ICollection ElementId , XYZ)复制一组元素，并将副本放置在给定指示的位置。 CopyElements(Document, ICollection ElementId , Document, Transform, CopyPasteOptions)将一组元素从源文档复制到目标文档。 CopyElements(View, ICollection ElementId ,...</div></div></div></a><a class="pagination-related" href="/2024/10/30/RevitApi%E5%90%88%E9%9B%86/Autodesk.Revit.DB%20Document/" title="Autodesk.Revit.DB Document"><div class="cover" style="background: var(--default-bg-color)"></div><div class="info text-center"><div class="info-1"><div class="info-item-1"><i class="far fa-calendar-alt fa-fw"></i> 2024-10-30</div><div class="info-item-2">Autodesk.Revit.DB Document</div></div><div class="info-2"><div class="info-item-1">Autodesk.Revit.DB Document表示打开的 Autodesk Revit 项目的对象。 语法1public class Document : IDisposable    附注Document 对象表示 Autodesk Revit 项目。Revit 可以打开多个项目，并打开这些项目的多个视图。活动视图或最顶层视图将是活动项目，因此是可从 Application 对象获得的活动文档。 继承层次结构 System Object Autodesk.Revit.DB Document Autodesk.Revit.DB.Macros DocumentEntryPoint  方法AcquireCoordinates 不知道是啥，API没给描述  AutoJoinElements 强制 Revit...</div></div></div></a><a class="pagination-related" href="/2024/12/10/RevitApi%E5%90%88%E9%9B%86/Autodesk.Revit.DB%20Opening/" title="Autodesk.Revit.DB Opening"><div class="cover" style="background: var(--default-bg-color)"></div><div class="info text-center"><div class="info-1"><div class="info-item-1"><i class="far fa-calendar-alt fa-fw"></i> 2024-12-10</div><div class="info-item-2">Autodesk.Revit.DB Opening</div></div><div class="info-2"><div class="info-item-1">Autodesk.Revit.DB OpeningAutodesk Revit项目或族文档中的洞口。 语法1public class Opening : Element  附注该对象表示各种不同类型的洞口：  墙中由修订项目中的两个边界点创建的矩形洞口。 由应用于屋顶、楼板、天花板、梁、支撑或柱的一组曲线创建的洞口。 一个垂直的竖井开口延伸到一个或多个水平。 在族文档中的墙或天花板上创建的简单洞口。  根据打开的类型，此类的某些属性将不可用。 这个对象派生自Element基对象，并且支持该对象的所有方法，例如检索该对象的参数的能力。此对象还支持访问结构分析模型，但此功能仅适用于Autodesk Revit Structure。 示例123456789101112131415161718192021222324252627282930313233343536373839404142434445464748495051### private void Getinfo_Opening(Opening opening)&#123;    string message =...</div></div></div></a><a class="pagination-related" href="/2024/12/10/RevitApi%E5%90%88%E9%9B%86/Autodesk.Revit.DB%20ReferenceIntersector/" title="Autodesk.Revit.DB ReferenceIntersector"><div class="cover" style="background: var(--default-bg-color)"></div><div class="info text-center"><div class="info-1"><div class="info-item-1"><i class="far fa-calendar-alt fa-fw"></i> 2024-12-10</div><div class="info-item-2">Autodesk.Revit.DB ReferenceIntersector</div></div><div class="info-2"><div class="info-item-1">Autodesk.Revit.DB ReferenceIntersector用于查找和返回与从原点和方向创建的射线相交的元素的类。 语法1public class ReferenceIntersector : IDisposable    附注可以构造此类的实例，以返回与由原点和方向创建的射线，或者基于过滤和标志返回元素的子集。 调用者可以选择使用ElementFilter过滤结果，或者通过应用特定的可接受的元素。 调用方还可以指定要返回的对象的类型， 整个元素、几何体对象或其组合。 在所有情况下，要求调用者提供 用于评估的3D视图;输入视图上的视图和可见性设置将确定 返回特定元素（例如，此工具永远不会返回隐藏元素、 和几何图形位于视图剖面框之外的元素）。 该类配置为可以构建单个实例，并用于对多个不同光线进行多次评估。在同一个 ReferenceIntersector 上的调用之间，评估结果不会被保留。 该类还提供了一个选项，用于返回在Revit链接中遇到的图元结果。 当设置 FindReferencesInRevitLinks 标志...</div></div></div></a><a class="pagination-related" href="/2024/12/19/RevitApi%E5%90%88%E9%9B%86/Autodesk.Revit.UI.Selection%20Namespace/" title="Autodesk.Revit.UI.Selection"><div class="cover" style="background: var(--default-bg-color)"></div><div class="info text-center"><div class="info-1"><div class="info-item-1"><i class="far fa-calendar-alt fa-fw"></i> 2024-12-19</div><div class="info-item-2">Autodesk.Revit.UI.Selection</div></div><div class="info-2"><div class="info-item-1">Autodesk.Revit.UI.SelectionClassesPickedBox包含两个 XYZ 点的类，表示屏幕上的选取框。  Properties  Max 最大坐标数（拾取框的右上角）。  Min 最小坐标（拾取框的左下角）。     SelectableInViewFilter一个过滤器，用于传递在给定视图中可选的元素。  Constructors  SelectableInViewFilter  (Document, ElementId) 构造 SelectableInViewFilter 的新实例。  SelectableInViewFilter (Document, ElementId, Boolean) 构造 SelectableInViewFilter 的新实例，并可选择传递所有不可选择的元素。    Methods  PassesFilter(Element) 将筛选器应用于给定元素。  PassesFilter(Document,...</div></div></div></a></div></div><hr class="custom-hr"/><div id="post-comment"><div class="comment-head"><div class="comment-headline"><i class="fas fa-comments fa-fw"></i><span> 评论</span></div></div><div class="comment-wrap"><div><div id="giscus-wrap"></div></div></div></div></div><div class="aside-content" id="aside-content"><div class="card-widget card-info text-center"><div class="avatar-img"><img src="/images/4stars.png" onerror="this.onerror=null;this.src='/img/friend_404.gif'" alt="avatar"/></div><div class="author-info-name">funtim41@gmail.com</div><div class="author-info-description">实践-认识-再实践-再认识</div><div class="site-data"><a href="/archives/"><div class="headline">文章</div><div class="length-num">58</div></a><a href="/tags/"><div class="headline">标签</div><div class="length-num">5</div></a><a href="/categories/"><div class="headline">分类</div><div class="length-num">7</div></a></div><a id="card-info-btn" target="_blank" rel="noopener" href="https://github.com/FunTim41"><i class="fab fa-github"></i><span>Follow Me</span></a><div class="card-info-social-icons"><a class="social-icon" href="https://github.com/FunTim41" target="_blank" title="Github"><i class="fab fa-github" style="color: #FFFFFF;"></i></a></div></div><div class="card-widget card-announcement"><div class="item-headline"><i class="fas fa-bullhorn fa-shake"></i><span>公告</span></div><div class="announcement_content">This is my Blog</div></div><div class="sticky_layout"><div class="card-widget" id="card-toc"><div class="item-headline"><i class="fas fa-stream"></i><span>目录</span><span class="toc-percentage"></span></div><div class="toc-content"><ol class="toc"><li class="toc-item toc-level-1"><a class="toc-link" href="#%E7%82%B9%E4%BA%91"><span class="toc-number">1.</span> <span class="toc-text">点云</span></a><ol class="toc-child"><li class="toc-item toc-level-2"><a class="toc-link" href="#%E7%82%B9%E4%BA%91%E5%AE%A2%E6%88%B7%E7%AB%AF"><span class="toc-number">1.1.</span> <span class="toc-text">点云客户端</span></a></li><li class="toc-item toc-level-2"><a class="toc-link" href="#%E7%82%B9%E4%BA%91%E5%BC%95%E6%93%8E"><span class="toc-number">1.2.</span> <span class="toc-text">点云引擎</span></a></li><li class="toc-item toc-level-2"><a class="toc-link" href="#%E6%B3%A8%EF%BC%9A%E7%BF%BB%E8%AF%91%E8%87%AARevit-API-Developers-Guide"><span class="toc-number">1.3.</span> <span class="toc-text">注：翻译自Revit API Developers Guide</span></a></li></ol></li></ol></div></div><div class="card-widget card-recent-post"><div class="item-headline"><i class="fas fa-history"></i><span>最新文章</span></div><div class="aside-list"><div class="aside-list-item no-cover"><div class="content"><a class="title" href="/2025/01/16/Revit%E4%BA%8C%E5%BC%80%E7%A4%BA%E4%BE%8B/Revit%E4%B8%8EExcel%E4%BA%A4%E4%BA%92/" title="Revit与Excel交互">Revit与Excel交互</a><time datetime="2025-01-16T08:43:45.327Z" title="更新于 2025-01-16 16:43:45">2025-01-16</time></div></div><div class="aside-list-item no-cover"><div class="content"><a class="title" href="/2025/01/14/ObjectARX%EF%BC%9AManaged.NET%E5%BC%80%E5%8F%91%E4%BA%BA%E5%91%98%E6%8C%87%E5%8D%97/03%E5%88%9B%E5%BB%BA%E5%92%8C%E7%BC%96%E8%BE%91AutoCAD%E5%9B%BE%E5%85%83%EF%BC%88.NET%EF%BC%89/" title="03创建和编辑AutoCAD图元（.NET）">03创建和编辑AutoCAD图元（.NET）</a><time datetime="2025-01-14T04:28:05.785Z" title="更新于 2025-01-14 12:28:05">2025-01-14</time></div></div><div class="aside-list-item no-cover"><div class="content"><a class="title" href="/2025/01/13/ObjectARX%EF%BC%9AManaged.NET%E5%BC%80%E5%8F%91%E4%BA%BA%E5%91%98%E6%8C%87%E5%8D%97/02%E6%8E%A7%E5%88%B6AutoCAD%E7%8E%AF%E5%A2%83%EF%BC%88.NET%EF%BC%89/" title="02控制AutoCAD环境（.NET）">02控制AutoCAD环境（.NET）</a><time datetime="2025-01-14T02:31:41.869Z" title="更新于 2025-01-14 10:31:41">2025-01-14</time></div></div><div class="aside-list-item no-cover"><div class="content"><a class="title" href="/2025/01/12/ObjectARX%EF%BC%9AManaged.NET%E5%BC%80%E5%8F%91%E4%BA%BA%E5%91%98%E6%8C%87%E5%8D%97/01AutoCAD.NET%20API%EF%BC%88.NET%EF%BC%89%E7%9A%84%E5%9F%BA%E7%A1%80%E7%9F%A5%E8%AF%86/" title="01AutoCAD .NET API（.NET）的基础知识">01AutoCAD .NET API（.NET）的基础知识</a><time datetime="2025-01-14T02:31:29.466Z" title="更新于 2025-01-14 10:31:29">2025-01-14</time></div></div><div class="aside-list-item no-cover"><div class="content"><a class="title" href="/2024/12/19/RevitApi%E5%90%88%E9%9B%86/Autodesk.Revit.UI.Selection%20Namespace/" title="Autodesk.Revit.UI.Selection">Autodesk.Revit.UI.Selection</a><time datetime="2025-01-13T14:24:17.222Z" title="更新于 2025-01-13 22:24:17">2025-01-13</time></div></div></div></div></div></div></main><footer id="footer" style="background-image: url(/images/topback.jpg);"><div id="footer-wrap"><div class="copyright">&copy;2024 - 2025 By funtim41@gmail.com</div><div class="framework-info"><span>框架 </span><a target="_blank" rel="noopener" href="https://hexo.io">Hexo</a><span class="footer-separator">|</span><span>主题 </span><a target="_blank" rel="noopener" href="https://github.com/jerryc127/hexo-theme-butterfly">Butterfly</a></div><div class="footer_custom_text">学而不思则罔，思而不学则殆。</div></div></footer></div><div id="rightside"><div id="rightside-config-hide"><button id="readmode" type="button" title="阅读模式"><i class="fas fa-book-open"></i></button><button id="darkmode" type="button" title="日间和夜间模式切换"><i class="fas fa-adjust"></i></button><button id="hide-aside-btn" type="button" title="单栏和双栏切换"><i class="fas fa-arrows-alt-h"></i></button></div><div id="rightside-config-show"><button id="rightside-config" type="button" title="设置"><i class="fas fa-cog fa-spin"></i></button><button class="close" id="mobile-toc-button" type="button" title="目录"><i class="fas fa-list-ul"></i></button><a id="to_comment" href="#post-comment" title="前往评论"><i class="fas fa-comments"></i></a><button id="go-up" type="button" title="回到顶部"><span class="scroll-percent"></span><i class="fas fa-arrow-up"></i></button></div></div><div><script src="/js/utils.js"></script><script src="/js/main.js"></script><script src="https://cdn.jsdelivr.net/npm/node-snackbar/dist/snackbar.min.js"></script><script>(() => {
  const panguFn = () => {
    if (typeof pangu === 'object') pangu.autoSpacingPage()
    else {
      btf.getScript('https://cdn.jsdelivr.net/npm/pangu/dist/browser/pangu.min.js')
        .then(() => {
          pangu.autoSpacingPage()
        })
    }
  }

  const panguInit = () => {
    if (false){
      GLOBAL_CONFIG_SITE.isPost && panguFn()
    } else {
      panguFn()
    }
  }

  btf.addGlobalFn('pjaxComplete', panguInit, 'pangu')
  document.addEventListener('DOMContentLoaded', panguInit)
})()</script><div class="js-pjax"><script>(() => {
  const isShuoshuo = GLOBAL_CONFIG_SITE.isShuoshuo
  const option = null

  const getGiscusTheme = theme => theme === 'dark' ? 'dark' : 'light'

  const createScriptElement = config => {
    const ele = document.createElement('script')
    Object.entries(config).forEach(([key, value]) => {
      ele.setAttribute(key, value)
    })
    return ele
  }

  const loadGiscus = (el = document, key) => {
    const mappingConfig = isShuoshuo
      ? { 'data-mapping': 'specific', 'data-term': key }
      : { 'data-mapping': (option && option['data-mapping']) || 'pathname' }

    const giscusConfig = {
      src: 'https://giscus.app/client.js',
      'data-repo': 'FunTim41/funtim41.github.io',
      'data-repo-id': 'R_kgDONjG8ww',
      'data-category-id': 'DIC_kwDONjG8w84Cllg2',
      'data-theme': getGiscusTheme(document.documentElement.getAttribute('data-theme')),
      'data-reactions-enabled': '1',
      crossorigin: 'anonymous',
      async: true,
      ...option,
      ...mappingConfig
    }

    const scriptElement = createScriptElement(giscusConfig)

    el.querySelector('#giscus-wrap').appendChild(scriptElement)

    if (isShuoshuo) {
      window.shuoshuoComment.destroyGiscus = () => {
        if (el.children.length) {
          el.innerHTML = ''
          el.classList.add('no-comment')
        }
      }
    }
  }

  const changeGiscusTheme = theme => {
    const iframe = document.querySelector('#giscus-wrap iframe')
    if (iframe) {
      const message = {
        giscus: {
          setConfig: {
            theme: getGiscusTheme(theme)
          }
        }
      }
      iframe.contentWindow.postMessage(message, 'https://giscus.app')
    }
  }

  btf.addGlobalFn('themeChange', changeGiscusTheme, 'giscus')

  if (isShuoshuo) {
    'Giscus' === 'Giscus'
      ? window.shuoshuoComment = { loadComment: loadGiscus }
      : window.loadOtherComment = loadGiscus
    return
  }

  if ('Giscus' === 'Giscus' || !false) {
    if (false) btf.loadComment(document.getElementById('giscus-wrap'), loadGiscus)
    else loadGiscus()
  } else {
    window.loadOtherComment = loadGiscus
  }
})()</script></div><script defer="defer" id="fluttering_ribbon" mobile="false" src="https://cdn.jsdelivr.net/npm/butterfly-extsrc/dist/canvas-fluttering-ribbon.min.js"></script><script async data-pjax src="//busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js"></script><div id="local-search"><div class="search-dialog"><nav class="search-nav"><span class="search-dialog-title">搜索</span><span id="loading-status"></span><button class="search-close-button"><i class="fas fa-times"></i></button></nav><div class="text-center" id="loading-database"><i class="fas fa-spinner fa-pulse"></i><span>  数据加载中</span></div><div class="search-wrap"><div id="local-search-input"><div class="local-search-box"><input class="local-search-box--input" placeholder="搜索文章" type="text"/></div></div><hr/><div id="local-search-results"></div><div id="local-search-stats-wrap"></div></div></div><div id="search-mask"></div><script src="/js/search/local-search.js"></script></div></div></body></html>