<!DOCTYPE html><html lang="zh-CN" data-theme="light"><head><meta charset="UTF-8"><meta http-equiv="X-UA-Compatible" content="IE=edge"><meta name="viewport" content="width=device-width, initial-scale=1.0,viewport-fit=cover"><title>38地点和位置 | funtim的博客</title><meta name="author" content="funtim41@gmail.com"><meta name="copyright" content="funtim41@gmail.com"><meta name="format-detection" content="telephone=no"><meta name="theme-color" content="#ffffff"><meta name="description" content="地点和位置每个建筑物在世界上都有一个独特的位置，因为纬度和经度是独一无二的。此外，一个建筑物相对于其他建筑物可以有许多位置。Revit Platform API Site命名空间使用某些类来保存Revit项目的地理位置信息。 注意：Revit Platform API不显示“场地”菜单功能。只有“site”命名空间提供与“管理”选项卡上的“项目位置”面板上的“位置”选项对应的功能。 本节中的页面">
<meta property="og:type" content="article">
<meta property="og:title" content="38地点和位置">
<meta property="og:url" content="https://funtim41.github.io/2024/12/30/Revit%E4%BA%8C%E5%BC%80%E6%8C%87%E5%8D%97/38%E5%9C%B0%E7%82%B9%E5%92%8C%E4%BD%8D%E7%BD%AE/">
<meta property="og:site_name" content="funtim的博客">
<meta property="og:description" content="地点和位置每个建筑物在世界上都有一个独特的位置，因为纬度和经度是独一无二的。此外，一个建筑物相对于其他建筑物可以有许多位置。Revit Platform API Site命名空间使用某些类来保存Revit项目的地理位置信息。 注意：Revit Platform API不显示“场地”菜单功能。只有“site”命名空间提供与“管理”选项卡上的“项目位置”面板上的“位置”选项对应的功能。 本节中的页面">
<meta property="og:locale" content="zh_CN">
<meta property="og:image" content="https://funtim41.github.io/images/4stars.png">
<meta property="article:published_time" content="2024-12-30T06:44:29.000Z">
<meta property="article:modified_time" content="2025-01-13T14:22:55.371Z">
<meta property="article:author" content="funtim41@gmail.com">
<meta property="article:tag" content="Revit">
<meta name="twitter:card" content="summary">
<meta name="twitter:image" content="https://funtim41.github.io/images/4stars.png"><link rel="shortcut icon" href="/images/OIP.jfif"><link rel="canonical" href="https://funtim41.github.io/2024/12/30/Revit%E4%BA%8C%E5%BC%80%E6%8C%87%E5%8D%97/38%E5%9C%B0%E7%82%B9%E5%92%8C%E4%BD%8D%E7%BD%AE/"><link rel="preconnect" href="//cdn.jsdelivr.net"/><link rel="stylesheet" href="/css/index.css"><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free/css/all.min.css"><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/node-snackbar/dist/snackbar.min.css" media="print" onload="this.media='all'"><script>
    (() => {
      
    const saveToLocal = {
      set: (key, value, ttl) => {
        if (!ttl) return
        const expiry = Date.now() + ttl * 86400000
        localStorage.setItem(key, JSON.stringify({ value, expiry }))
      },
      get: key => {
        const itemStr = localStorage.getItem(key)
        if (!itemStr) return undefined
        const { value, expiry } = JSON.parse(itemStr)
        if (Date.now() > expiry) {
          localStorage.removeItem(key)
          return undefined
        }
        return value
      }
    }

    window.btf = {
      saveToLocal,
      getScript: (url, attr = {}) => new Promise((resolve, reject) => {
        const script = document.createElement('script')
        script.src = url
        script.async = true
        Object.entries(attr).forEach(([key, val]) => script.setAttribute(key, val))
        script.onload = script.onreadystatechange = () => {
          if (!script.readyState || /loaded|complete/.test(script.readyState)) resolve()
        }
        script.onerror = reject
        document.head.appendChild(script)
      }),
      getCSS: (url, id) => new Promise((resolve, reject) => {
        const link = document.createElement('link')
        link.rel = 'stylesheet'
        link.href = url
        if (id) link.id = id
        link.onload = link.onreadystatechange = () => {
          if (!link.readyState || /loaded|complete/.test(link.readyState)) resolve()
        }
        link.onerror = reject
        document.head.appendChild(link)
      }),
      addGlobalFn: (key, fn, name = false, parent = window) => {
        if (!false && key.startsWith('pjax')) return
        const globalFn = parent.globalFn || {}
        globalFn[key] = globalFn[key] || {}
        globalFn[key][name || Object.keys(globalFn[key]).length] = fn
        parent.globalFn = globalFn
      }
    }
  
      
      const activateDarkMode = () => {
        document.documentElement.setAttribute('data-theme', 'dark')
        if (document.querySelector('meta[name="theme-color"]') !== null) {
          document.querySelector('meta[name="theme-color"]').setAttribute('content', '#0d0d0d')
        }
      }
      const activateLightMode = () => {
        document.documentElement.setAttribute('data-theme', 'light')
        if (document.querySelector('meta[name="theme-color"]') !== null) {
          document.querySelector('meta[name="theme-color"]').setAttribute('content', '#ffffff')
        }
      }

      btf.activateDarkMode = activateDarkMode
      btf.activateLightMode = activateLightMode

      const theme = saveToLocal.get('theme')
    
          theme === 'dark' ? activateDarkMode() : theme === 'light' ? activateLightMode() : null
        
      
      const asideStatus = saveToLocal.get('aside-status')
      if (asideStatus !== undefined) {
        document.documentElement.classList.toggle('hide-aside', asideStatus === 'hide')
      }
    
      
    const detectApple = () => {
      if (/iPad|iPhone|iPod|Macintosh/.test(navigator.userAgent)) {
        document.documentElement.classList.add('apple')
      }
    }
    detectApple()
  
    })()
  </script><script>const GLOBAL_CONFIG = {
  root: '/',
  algolia: undefined,
  localSearch: {"path":"/search.xml","preload":false,"top_n_per_article":1,"unescape":false,"languages":{"hits_empty":"未找到符合您查询的内容：${query}","hits_stats":"共找到 ${hits} 篇文章"}},
  translate: undefined,
  highlight: {"plugin":"highlight.js","highlightCopy":true,"highlightLang":true,"highlightHeightLimit":false,"highlightFullpage":false,"highlightMacStyle":false},
  copy: {
    success: '复制成功',
    error: '复制失败',
    noSupport: '浏览器不支持'
  },
  relativeDate: {
    homepage: false,
    post: false
  },
  runtime: '',
  dateSuffix: {
    just: '刚刚',
    min: '分钟前',
    hour: '小时前',
    day: '天前',
    month: '个月前'
  },
  copyright: {"limitCount":150,"languages":{"author":"作者: funtim41@gmail.com","link":"链接: ","source":"来源: funtim的博客","info":"著作权归作者所有。商业转载请联系作者获得授权，非商业转载请注明出处。"}},
  lightbox: 'null',
  Snackbar: {"chs_to_cht":"已切换为繁体中文","cht_to_chs":"已切换为简体中文","day_to_night":"已切换为深色模式","night_to_day":"已切换为浅色模式","bgLight":"#49b1f5","bgDark":"#1f1f1f","position":"bottom-left"},
  infinitegrid: {
    js: 'https://cdn.jsdelivr.net/npm/@egjs/infinitegrid/dist/infinitegrid.min.js',
    buttonText: '加载更多'
  },
  isPhotoFigcaption: false,
  islazyload: false,
  isAnchor: true,
  percent: {
    toc: true,
    rightside: true,
  },
  autoDarkmode: false
}</script><script id="config-diff">var GLOBAL_CONFIG_SITE = {
  title: '38地点和位置',
  isPost: true,
  isHome: false,
  isHighlightShrink: false,
  isToc: true,
  isShuoshuo: false
}</script><link rel="stylesheet" href="/css/bar.css"><meta name="generator" content="Hexo 7.3.0"></head><body><div id="web_bg" style="background: Color(#995a82);"></div><div id="sidebar"><div id="menu-mask"></div><div id="sidebar-menus"><div class="avatar-img text-center"><img src="/images/4stars.png" onerror="onerror=null;src='/img/friend_404.gif'" alt="avatar"/></div><div class="site-data text-center"><a href="/archives/"><div class="headline">文章</div><div class="length-num">66</div></a><a href="/tags/"><div class="headline">标签</div><div class="length-num">5</div></a><a href="/categories/"><div class="headline">分类</div><div class="length-num">7</div></a></div><div class="menus_items"><div class="menus_item"><a class="site-page" href="/"><i class="fa-fw fas fa-home"></i><span> Home</span></a></div><div class="menus_item"><a class="site-page" href="/archives/"><i class="fa-fw fas fa-archive"></i><span> Timeline</span></a></div><div class="menus_item"><a class="site-page" href="/tags/"><i class="fa-fw fas fa-tags"></i><span> Tags</span></a></div><div class="menus_item"><a class="site-page" href="/categories/"><i class="fa-fw fas fa-folder-open"></i><span> Categories</span></a></div><div class="menus_item"><a class="site-page" href="/Links/"><i class="fa-fw fas fa-link"></i><span> Links</span></a></div><div class="menus_item"><a class="site-page" href="/about/"><i class="fa-fw fas fa-heart"></i><span> About</span></a></div></div></div></div><div class="post" id="body-wrap"><header class="post-bg fixed" id="page-header" style="background-image: url(/images/topback.jpg);"><nav id="nav"><span id="blog-info"><a class="nav-site-title" href="/"><img class="site-icon" src="/images/OIP.jfif" alt="Logo"><span class="site-name">funtim的博客</span></a><a class="nav-page-title" href="/"><span class="site-name">38地点和位置</span></a></span><div id="menus"><div id="search-button"><span class="site-page social-icon search"><i class="fas fa-search fa-fw"></i><span> 搜索</span></span></div><div class="menus_items"><div class="menus_item"><a class="site-page" href="/"><i class="fa-fw fas fa-home"></i><span> Home</span></a></div><div class="menus_item"><a class="site-page" href="/archives/"><i class="fa-fw fas fa-archive"></i><span> Timeline</span></a></div><div class="menus_item"><a class="site-page" href="/tags/"><i class="fa-fw fas fa-tags"></i><span> Tags</span></a></div><div class="menus_item"><a class="site-page" href="/categories/"><i class="fa-fw fas fa-folder-open"></i><span> Categories</span></a></div><div class="menus_item"><a class="site-page" href="/Links/"><i class="fa-fw fas fa-link"></i><span> Links</span></a></div><div class="menus_item"><a class="site-page" href="/about/"><i class="fa-fw fas fa-heart"></i><span> About</span></a></div></div><div id="toggle-menu"><span class="site-page"><i class="fas fa-bars fa-fw"></i></span></div></div></nav><div id="post-info"><h1 class="post-title">38地点和位置</h1><div id="post-meta"><div class="meta-firstline"><span class="post-meta-date"><i class="far fa-calendar-alt fa-fw post-meta-icon"></i><span class="post-meta-label">发表于</span><time class="post-meta-date-created" datetime="2024-12-30T06:44:29.000Z" title="发表于 2024-12-30 14:44:29">2024-12-30</time><span class="post-meta-separator">|</span><i class="fas fa-history fa-fw post-meta-icon"></i><span class="post-meta-label">更新于</span><time class="post-meta-date-updated" datetime="2025-01-13T14:22:55.371Z" title="更新于 2025-01-13 22:22:55">2025-01-13</time></span><span class="post-meta-categories"><span class="post-meta-separator">|</span><i class="fas fa-inbox fa-fw post-meta-icon"></i><a class="post-meta-categories" href="/categories/Revit%E4%BA%8C%E6%AC%A1%E5%BC%80%E5%8F%91%E4%BA%BA%E5%91%98%E6%8C%87%E5%8D%97/">Revit二次开发人员指南</a></span></div><div class="meta-secondline"><span class="post-meta-separator">|</span><span class="post-meta-pv-cv" id="" data-flag-title=""><i class="far fa-eye fa-fw post-meta-icon"></i><span class="post-meta-label">浏览量:</span><span id="busuanzi_value_page_pv"><i class="fa-solid fa-spinner fa-spin"></i></span></span></div></div></div></header><main class="layout" id="content-inner"><div id="post"><article class="container post-content" id="article-container"><h1 id="地点和位置"><a href="#地点和位置" class="headerlink" title="地点和位置"></a>地点和位置</h1><p>每个建筑物在世界上都有一个独特的位置，因为纬度和经度是独一无二的。此外，一个建筑物相对于其他建筑物可以有许多位置。Revit Platform API Site命名空间使用某些类来保存Revit项目的地理位置信息。</p>
<p>注意：Revit Platform API不显示“场地”菜单功能。只有“site”命名空间提供与“管理”选项卡上的“项目位置”面板上的“位置”选项对应的功能。</p>
<p>本节中的页面</p>
<ul>
<li>Place  地点</li>
<li>City  城市</li>
<li>ProjectLocation  项目地点</li>
<li>Project Position  项目位置</li>
</ul>
<h2 id="地点"><a href="#地点" class="headerlink" title="地点"></a>地点</h2><p>在Revit Platform API中，SiteLocation类包含纬度、经度和时区等位置信息。该信息确定项目在世界上的位置。设置纬度或经度时，请注意：</p>
<ol>
<li>Revit将尝试将坐标与它所知道的城市进行匹配，如果找到匹配，将相应地设置名称。</li>
<li>Revit将尝试自动调整时区值，以匹配使用SunAndShadowSettings.CalculateTimeZone（）设置的新经度或纬度值。对于某些边界情况，计算的时区可能不正确，如果需要，可以直接设置TimeZone属性。</li>
</ol>
<p><img src="https://help.autodesk.com/cloudhelp/2018/ENU/Revit-API/images/GUID-F3A532FC-E537-4CD5-A351-48AC48C21092-low.png" alt="img"></p>
<h2 id="城市"><a href="#城市" class="headerlink" title="城市"></a>城市</h2><p>城市是包含世界上已知城市的地理位置信息的对象。它包含经度、纬度和时区信息。城市列表由Application对象中的Cities属性检索。无法将新城市添加到Revit中的现有列表中。Revit Platform API不会显示当前项目所在的城市。</p>
<h2 id="项目地点"><a href="#项目地点" class="headerlink" title="项目地点"></a>项目地点</h2><p>一个项目只有一个场地，那就是在地球上的绝对位置。但是，它可以相对于周围的项目具有不同的位置。根据所使用的坐标和原点，一个项目中可以有多个ProjectLocation对象。</p>
<p>默认情况下，每个Revit项目至少包含一个命名位置Internal。它是活动项目位置。可以使用Document.ActiveProjectLocation属性检索它。使用Document.ProjectLocations属性检索所有现有的ProjectLocation对象。</p>
<h2 id="项目位置"><a href="#项目位置" class="headerlink" title="项目位置"></a>项目位置</h2><p>项目位置是表示地理偏移和旋转的对象。它通常由ProjectLocation对象用来获取和设置地理信息。下图显示了更改ProjectLocation地理旋转和同一点的坐标后的结果。但是，您无法看到直接更改ProjectLocation地理偏移的结果。</p>
<p><img src="https://help.autodesk.com/cloudhelp/2018/ENU/Revit-API/images/GUID-7242FF42-B873-48EC-8D6C-208675848D2D-low.png" alt="img"></p>
<p>图125：点坐标</p>
<p>注意：东表示位置逆时针旋转;西表示位置顺时针旋转。如果“角度”值介于180度和360度之间，则Revit会自动对其进行变换。例如，如果选择“东”并键入200度作为“角度”，则Revit会将其转换为“西160度”。</p>
<p><img src="https://help.autodesk.com/cloudhelp/2018/ENU/Revit-API/images/GUID-C784E377-BFF8-4CCE-B5A8-77310071FCD3-low.png" alt="img"> </p>
<p>图126：地理偏移和旋转示意图</p>
<p>下面的示例代码说明如何检索ProjectLocation对象。</p>
<p>代码区域21-1：检索ProjectLocation对象</p>
<figure class="highlight c#"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br><span class="line">23</span><br><span class="line">24</span><br><span class="line">25</span><br><span class="line">26</span><br><span class="line">27</span><br><span class="line">28</span><br><span class="line">29</span><br><span class="line">30</span><br><span class="line">31</span><br><span class="line">32</span><br><span class="line">33</span><br><span class="line">34</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="keyword">public</span> <span class="keyword">void</span> <span class="title">ShowActiveProjectLocationUsage</span>(<span class="params">Autodesk.Revit.DB.Document document</span>)</span></span><br><span class="line">&#123;</span><br><span class="line">    <span class="comment">// Get the project location handle </span></span><br><span class="line">    ProjectLocation projectLocation = document.ActiveProjectLocation;</span><br><span class="line"></span><br><span class="line">    <span class="comment">// Show the information of current project location</span></span><br><span class="line">    XYZ origin = <span class="keyword">new</span> XYZ(<span class="number">0</span>, <span class="number">0</span>, <span class="number">0</span>);</span><br><span class="line">    ProjectPosition position = projectLocation.GetProjectPosition(origin);</span><br><span class="line">    <span class="keyword">if</span> (<span class="literal">null</span> == position)</span><br><span class="line">    &#123;</span><br><span class="line">            <span class="keyword">throw</span> <span class="keyword">new</span> Exception(<span class="string">&quot;No project position in origin point.&quot;</span>);</span><br><span class="line">    &#125;</span><br><span class="line"></span><br><span class="line">    <span class="comment">// Format the prompt string to show the message.</span></span><br><span class="line">    String prompt = <span class="string">&quot;Current project location information:\n&quot;</span>;</span><br><span class="line">    prompt += <span class="string">&quot;\n\t&quot;</span> + <span class="string">&quot;Origin point position:&quot;</span>;</span><br><span class="line">    prompt += <span class="string">&quot;\n\t\t&quot;</span> + <span class="string">&quot;Angle: &quot;</span> + position.Angle;</span><br><span class="line">    prompt += <span class="string">&quot;\n\t\t&quot;</span> + <span class="string">&quot;East to West offset: &quot;</span> + position.EastWest;</span><br><span class="line">    prompt += <span class="string">&quot;\n\t\t&quot;</span> + <span class="string">&quot;Elevation: &quot;</span> + position.Elevation;</span><br><span class="line">    prompt += <span class="string">&quot;\n\t\t&quot;</span> + <span class="string">&quot;North to South offset: &quot;</span> + position.NorthSouth;</span><br><span class="line"></span><br><span class="line">    <span class="comment">// Angles are in radians when coming from Revit API, so we </span></span><br><span class="line">    <span class="comment">// convert to degrees for display</span></span><br><span class="line">    <span class="keyword">const</span> <span class="built_in">double</span> angleRatio = Math.PI / <span class="number">180</span>;        <span class="comment">// angle conversion factor</span></span><br><span class="line"></span><br><span class="line">    SiteLocation site = projectLocation.GetSiteLocation();</span><br><span class="line">    <span class="built_in">string</span> degreeSymbol = ((<span class="built_in">char</span>)<span class="number">176</span>).ToString();</span><br><span class="line">    prompt += <span class="string">&quot;\n\t&quot;</span> + <span class="string">&quot;Site location:&quot;</span>;</span><br><span class="line">    prompt += <span class="string">&quot;\n\t\t&quot;</span> + <span class="string">&quot;Latitude: &quot;</span> + site.Latitude / angleRatio + degreeSymbol;</span><br><span class="line">    prompt += <span class="string">&quot;\n\t\t&quot;</span> + <span class="string">&quot;Longitude: &quot;</span> + site.Longitude / angleRatio + degreeSymbol;</span><br><span class="line">    prompt += <span class="string">&quot;\n\t\t&quot;</span> + <span class="string">&quot;TimeZone: &quot;</span> + site.TimeZone;</span><br><span class="line"></span><br><span class="line">    TaskDialog.Show(<span class="string">&quot;Revit&quot;</span>, prompt);</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<p>注意：一次只有一个活动项目位置。若要查看更改ProjectLocation地理偏移和旋转后的结果，请在平面视图“特性”窗格中将“方向”特性从“项目北”更改为“正北”</p>
<p><img src="https://help.autodesk.com/cloudhelp/2018/ENU/Revit-API/images/GUID-57E4EC63-4A77-4C7C-91B3-770F3ADDBE6D-low.png"></p>
<p>图128：项目从项目北向正北旋转30度</p>
<p><img src="https://help.autodesk.com/cloudhelp/2018/ENU/Revit-API/images/GUID-57C77B88-C8F7-4207-9A4F-3728182159F3-low.png"></p>
<p>图129：项目位置信息</p>
<p><strong>创建和删除项目位置</strong></p>
<p>通过使用Duplicate（）方法复制现有项目位置来创建新项目位置。下面的代码示例说明如何使用Duplicate（）方法创建新的项目位置。</p>
<p>代码区域21-2：创建项目位置</p>
<figure class="highlight c#"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="keyword">public</span> ProjectLocation <span class="title">DuplicateLocation</span>(<span class="params">Autodesk.Revit.DB.Document document, <span class="built_in">string</span> newName</span>)</span></span><br><span class="line">&#123;</span><br><span class="line">        ProjectLocation currentLocation = document.ActiveProjectLocation;</span><br><span class="line">        ProjectLocationSet locations = document.ProjectLocations;</span><br><span class="line">        <span class="keyword">foreach</span> (ProjectLocation projectLocation <span class="keyword">in</span> locations)</span><br><span class="line">        &#123;</span><br><span class="line">                <span class="keyword">if</span> (projectLocation.Name == newName)</span><br><span class="line">                &#123;</span><br><span class="line">                        <span class="keyword">throw</span> <span class="keyword">new</span> Exception(<span class="string">&quot;The name is same as a project location&#x27;s name, please change one.&quot;</span>);</span><br><span class="line">                &#125;</span><br><span class="line">        &#125;</span><br><span class="line">        <span class="keyword">return</span> currentLocation.Duplicate(newName);</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<p>下面的代码示例阐释如何从当前项目中删除现有项目位置。</p>
<p>代码区域21-3：删除项目位置</p>
<figure class="highlight c#"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br><span class="line">23</span><br><span class="line">24</span><br><span class="line">25</span><br><span class="line">26</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="keyword">public</span> <span class="keyword">void</span> <span class="title">DeleteLocation</span>(<span class="params">Autodesk.Revit.DB.Document document</span>)</span></span><br><span class="line">&#123;</span><br><span class="line">    ProjectLocation currentLocation = document.ActiveProjectLocation;</span><br><span class="line">    <span class="comment">//There must be at least one project location in the project.</span></span><br><span class="line">    ProjectLocationSet locations = document.ProjectLocations;</span><br><span class="line">    <span class="keyword">if</span> (<span class="number">1</span> == locations.Size)</span><br><span class="line">    &#123;</span><br><span class="line">        <span class="keyword">return</span>;</span><br><span class="line">    &#125;</span><br><span class="line"></span><br><span class="line">    <span class="built_in">string</span> name = <span class="string">&quot;location&quot;</span>;</span><br><span class="line">    <span class="keyword">if</span> (name != currentLocation.Name)</span><br><span class="line">    &#123;</span><br><span class="line">        <span class="keyword">foreach</span> (ProjectLocation projectLocation <span class="keyword">in</span> locations)</span><br><span class="line">        &#123;</span><br><span class="line">            <span class="keyword">if</span> (projectLocation.Name == name)</span><br><span class="line">            &#123;</span><br><span class="line">                ICollection&lt;Autodesk.Revit.DB.ElementId&gt; elemSet = document.Delete(projectLocation.Id);</span><br><span class="line">                <span class="keyword">if</span> (elemSet.Count &gt; <span class="number">0</span>)</span><br><span class="line">                &#123;</span><br><span class="line">                    TaskDialog.Show(<span class="string">&quot;Revit&quot;</span>,<span class="string">&quot;Project Location Deleted!&quot;</span>);</span><br><span class="line">                &#125;</span><br><span class="line">            &#125;</span><br><span class="line">        &#125;</span><br><span class="line">    &#125;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<p>注：以下规则适用于删除项目位置：</p>
<ul>
<li>无法删除活动项目位置，因为项目中必须至少有一个项目位置。</li>
<li>如果ProjectLocationSet类实例为只读，则不能删除项目位置。</li>
</ul>
<h2 id="注：翻译自Revit-API-Developers-Guide"><a href="#注：翻译自Revit-API-Developers-Guide" class="headerlink" title="注：翻译自Revit API Developers Guide"></a><em><strong>注：</strong></em>翻译自<a target="_blank" rel="noopener" href="https://help.autodesk.com/view/RVT/2018/ENU/?guid=Revit_API_Revit_API_Developers_Guide_html">Revit API Developers Guide</a></h2></article><div class="tag_share"><div class="post-meta__tag-list"><a class="post-meta__tags" href="/tags/Revit/">Revit</a></div><div class="post-share"><div class="social-share" data-image="/images/4stars.png" data-sites="facebook,twitter,wechat,weibo,qq"></div><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/butterfly-extsrc/sharejs/dist/css/share.min.css" media="print" onload="this.media='all'"><script src="https://cdn.jsdelivr.net/npm/butterfly-extsrc/sharejs/dist/js/social-share.min.js" defer></script></div></div><nav class="pagination-post" id="pagination"><a class="pagination-related" href="/2024/12/30/Revit%E4%BA%8C%E5%BC%80%E6%8C%87%E5%8D%97/39%E5%B7%A5%E4%BD%9C%E5%85%B1%E4%BA%AB/" title="39工作共享"><div class="cover" style="background: var(--default-bg-color)"></div><div class="info"><div class="info-1"><div class="info-item-1">上一篇</div><div class="info-item-2">39工作共享</div></div><div class="info-2"><div class="info-item-1">...</div></div></div></a><a class="pagination-related" href="/2024/12/30/CSharp/%E7%BA%BF%E7%A8%8B/" title="线程"><div class="cover" style="background: var(--default-bg-color)"></div><div class="info text-right"><div class="info-1"><div class="info-item-1">下一篇</div><div class="info-item-2">线程</div></div><div class="info-2"><div class="info-item-1">线程 创建1Thread thread1 = new Thread(Methode);  开始1thread1.Start();  等待完成1thread1.Join();  优先级1thread1.Priority=ThreadPriority.Highest;//优先级和线程调度器时间片都会影响顺序  名字1thread1.Name=&quot;001&quot;;  当前线程优先级1Thread.CurrentThread.Priority=ThreadPriority.Normal;  锁1lock (counterLock) &#123; counter += 1; &#125;  监视器12345678910111213141516//尝试进入临界区if (Monitor.TryEnter(ticketslock, 2000))    	&#123;		try		&#123;           ...</div></div></div></a></nav><div class="relatedPosts"><div class="headline"><i class="fas fa-thumbs-up fa-fw"></i><span>相关推荐</span></div><div class="relatedPosts-list"><a class="pagination-related" href="/2024/12/20/RevitApi%E5%90%88%E9%9B%86/Autodesk.%20Revit.DB%20ElementTransformUtils/" title="Autodesk.Revit.DB ElementTransformUtils"><div class="cover" style="background: var(--default-bg-color)"></div><div class="info text-center"><div class="info-1"><div class="info-item-1"><i class="far fa-calendar-alt fa-fw"></i> 2024-12-20</div><div class="info-item-2">Autodesk.Revit.DB ElementTransformUtils</div></div><div class="info-2"><div class="info-item-1">Autodesk. Revit.DB ElementTransformUtils允许元素转换的实用程序集合（例如移动，旋转，镜像和复制）。 语法1public static class ElementTransformUtils    继承层次结构 System Object Autodesk.Revit.DB ElementTransformUtils   方法CanMirrorElement确定是否可以镜像元素。 CanMirrorElements确定是否可以镜像元素。 CopyElement复制元素并将副本放置在给定转换指示的位置。 CopyElements(Document, ICollection ElementId , XYZ)复制一组元素，并将副本放置在给定指示的位置。 CopyElements(Document, ICollection ElementId , Document, Transform, CopyPasteOptions)将一组元素从源文档复制到目标文档。 CopyElements(View, ICollection ElementId ,...</div></div></div></a><a class="pagination-related" href="/2025/02/16/RevitApi%E5%90%88%E9%9B%86/Autodesk.Revit.ApplicationServices%20Application/" title="Autodesk.Revit.ApplicationServices Application"><div class="cover" style="background: var(--default-bg-color)"></div><div class="info text-center"><div class="info-1"><div class="info-item-1"><i class="far fa-calendar-alt fa-fw"></i> 2025-02-16</div><div class="info-item-2">Autodesk.Revit.ApplicationServices Application</div></div><div class="info-2"><div class="info-item-1">Autodesk.Revit.ApplicationServices Application代表Autodesk Revit应用程序，提供对文档、选项和其他应用程序范围数据和设置的访问。 语法1public class Application : IDisposable    示例123string versionInfo = application.VersionBuild + &quot;\n&quot;					+ application.VersionName + &quot;\n&quot;					+ application.VersionNumber;  继承层次结构System Object Autodesk.Revit.ApplicationServices Application Autodesk.Revit.DB.Macros ApplicationEntryPoint 方法CopyModel将现有模型复制到新文件。允许覆盖同名文件。 ExtractPartAtomFromFamilyFile从族文件的内容写入PartAtom...</div></div></div></a><a class="pagination-related" href="/2024/11/18/RevitApi%E5%90%88%E9%9B%86/Autodesk.Revit.DB%20CurveArray/" title="Autodesk.Revit.DB CurveArray"><div class="cover" style="background: var(--default-bg-color)"></div><div class="info text-center"><div class="info-1"><div class="info-item-1"><i class="far fa-calendar-alt fa-fw"></i> 2024-11-18</div><div class="info-item-2">Autodesk.Revit.DB CurveArray</div></div><div class="info-2"><div class="info-item-1">Autodesk.Revit.DB CurveArray可以包含曲线的数组。 语法1public class CurveArray : APIObject, IEnumerable  继承层次结构System Object ​	Autodesk.Revit.DB APIObject ​		Autodesk.Revit.DB CurveArray 另见CurveArray Members Autodesk.Revit.DB Namespace 构造函数CurveArray创建CurveArray类的新实例 方法Append将曲线添加到数组的末尾。 Clear从数组中删除每条曲线，使其为空。 ForwardIterator将一个向前移动的迭代器添加到数组中。 GetEnumerator将一个向前移动的迭代器添加到数组中。 Insert将指定的曲线插入数组。 ReverseIterator返回一个向后移动的迭代器到数组。 属性IsEmpty测试数组是否为空。 Item获取或设置数组中指定索引处的曲线。 Size返回数组中的曲线数。 注：翻译自Revit Api docs 2018</div></div></div></a><a class="pagination-related" href="/2025/02/20/RevitApi%E5%90%88%E9%9B%86/Autodesk.Revit.DB%20Curve/" title="Autodesk.Revit.DB Curve"><div class="cover" style="background: var(--default-bg-color)"></div><div class="info text-center"><div class="info-1"><div class="info-item-1"><i class="far fa-calendar-alt fa-fw"></i> 2025-02-20</div><div class="info-item-2">Autodesk.Revit.DB Curve</div></div><div class="info-2"><div class="info-item-1">Autodesk.Revit.DB Curve参数曲线。 语法1public class Curve : GeometryObject    附注具体曲线由参数方程定义。如果曲线是有界的，它只在参数化中为一个区间定义。否则就是 为参数的所有值定义。 继承层次结构System Object Autodesk.Revit.DB APIObject Autodesk.Revit.DB GeometryObject Autodesk.Revit.DB Curve Autodesk.Revit.DB Arc Autodesk.Revit.DB CylindricalHelix Autodesk.Revit.DB Ellipse Autodesk.Revit.DB HermiteSpline Autodesk.Revit.DB Line Autodesk.Revit.DB...</div></div></div></a><a class="pagination-related" href="/2025/02/20/RevitApi%E5%90%88%E9%9B%86/Autodesk.Revit.DB%20Line/" title="Autodesk.Revit.DB Line"><div class="cover" style="background: var(--default-bg-color)"></div><div class="info text-center"><div class="info-1"><div class="info-item-1"><i class="far fa-calendar-alt fa-fw"></i> 2025-02-20</div><div class="info-item-2">Autodesk.Revit.DB Line</div></div><div class="info-2"><div class="info-item-1">Autodesk.Revit.DB Line空间中的一条线。 语法1public class Line : Curve  继承层次结构System Object Autodesk.Revit.DB APIObject Autodesk.Revit.DB GeometryObject Autodesk.Revit.DB Curve Autodesk.Revit.DB Line 方法CreateBound创建有界线性曲线的新实例。 CreateUnbound创建无界线性曲线的新实例。 Intersect计算此曲线与指定曲线的交点。 IsInside指示指定的参数值是否在此曲线的边界内。 属性Direction返回直线的方向。 Origin返回直线的原点。 注：翻译自Revit Api docs 2018</div></div></div></a><a class="pagination-related" href="/2024/12/10/RevitApi%E5%90%88%E9%9B%86/Autodesk.Revit.DB%20Opening/" title="Autodesk.Revit.DB Opening"><div class="cover" style="background: var(--default-bg-color)"></div><div class="info text-center"><div class="info-1"><div class="info-item-1"><i class="far fa-calendar-alt fa-fw"></i> 2024-12-10</div><div class="info-item-2">Autodesk.Revit.DB Opening</div></div><div class="info-2"><div class="info-item-1">Autodesk.Revit.DB OpeningAutodesk Revit项目或族文档中的洞口。 语法1public class Opening : Element  附注该对象表示各种不同类型的洞口：  墙中由修订项目中的两个边界点创建的矩形洞口。 由应用于屋顶、楼板、天花板、梁、支撑或柱的一组曲线创建的洞口。 一个垂直的竖井开口延伸到一个或多个水平。 在族文档中的墙或天花板上创建的简单洞口。  根据打开的类型，此类的某些属性将不可用。 这个对象派生自Element基对象，并且支持该对象的所有方法，例如检索该对象的参数的能力。此对象还支持访问结构分析模型，但此功能仅适用于Autodesk Revit Structure。 示例123456789101112131415161718192021222324252627282930313233343536373839404142434445464748495051### private void Getinfo_Opening(Opening opening)&#123;    string message =...</div></div></div></a></div></div><hr class="custom-hr"/><div id="post-comment"><div class="comment-head"><div class="comment-headline"><i class="fas fa-comments fa-fw"></i><span> 评论</span></div></div><div class="comment-wrap"><div><div id="giscus-wrap"></div></div></div></div></div><div class="aside-content" id="aside-content"><div class="card-widget card-info text-center"><div class="avatar-img"><img src="/images/4stars.png" onerror="this.onerror=null;this.src='/img/friend_404.gif'" alt="avatar"/></div><div class="author-info-name">funtim41@gmail.com</div><div class="author-info-description">实践-认识-再实践-再认识</div><div class="site-data"><a href="/archives/"><div class="headline">文章</div><div class="length-num">66</div></a><a href="/tags/"><div class="headline">标签</div><div class="length-num">5</div></a><a href="/categories/"><div class="headline">分类</div><div class="length-num">7</div></a></div><a id="card-info-btn" target="_blank" rel="noopener" href="https://github.com/FunTim41"><i class="fab fa-github"></i><span>Follow Me</span></a><div class="card-info-social-icons"><a class="social-icon" href="https://github.com/FunTim41" target="_blank" title="Github"><i class="fab fa-github" style="color: #FFFFFF;"></i></a></div></div><div class="card-widget card-announcement"><div class="item-headline"><i class="fas fa-bullhorn fa-shake"></i><span>公告</span></div><div class="announcement_content">This is my Blog</div></div><div class="sticky_layout"><div class="card-widget" id="card-toc"><div class="item-headline"><i class="fas fa-stream"></i><span>目录</span><span class="toc-percentage"></span></div><div class="toc-content"><ol class="toc"><li class="toc-item toc-level-1"><a class="toc-link" href="#%E5%9C%B0%E7%82%B9%E5%92%8C%E4%BD%8D%E7%BD%AE"><span class="toc-number">1.</span> <span class="toc-text">地点和位置</span></a><ol class="toc-child"><li class="toc-item toc-level-2"><a class="toc-link" href="#%E5%9C%B0%E7%82%B9"><span class="toc-number">1.1.</span> <span class="toc-text">地点</span></a></li><li class="toc-item toc-level-2"><a class="toc-link" href="#%E5%9F%8E%E5%B8%82"><span class="toc-number">1.2.</span> <span class="toc-text">城市</span></a></li><li class="toc-item toc-level-2"><a class="toc-link" href="#%E9%A1%B9%E7%9B%AE%E5%9C%B0%E7%82%B9"><span class="toc-number">1.3.</span> <span class="toc-text">项目地点</span></a></li><li class="toc-item toc-level-2"><a class="toc-link" href="#%E9%A1%B9%E7%9B%AE%E4%BD%8D%E7%BD%AE"><span class="toc-number">1.4.</span> <span class="toc-text">项目位置</span></a></li><li class="toc-item toc-level-2"><a class="toc-link" href="#%E6%B3%A8%EF%BC%9A%E7%BF%BB%E8%AF%91%E8%87%AARevit-API-Developers-Guide"><span class="toc-number">1.5.</span> <span class="toc-text">注：翻译自Revit API Developers Guide</span></a></li></ol></li></ol></div></div><div class="card-widget card-recent-post"><div class="item-headline"><i class="fas fa-history"></i><span>最新文章</span></div><div class="aside-list"><div class="aside-list-item no-cover"><div class="content"><a class="title" href="/2025/02/27/RevitApi%E5%90%88%E9%9B%86/Autodesk.Revit.DB%20XYZ%20/" title="Autodesk.Revit.DB XYZ">Autodesk.Revit.DB XYZ</a><time datetime="2025-02-27T12:48:50.709Z" title="更新于 2025-02-27 20:48:50">2025-02-27</time></div></div><div class="aside-list-item no-cover"><div class="content"><a class="title" href="/2025/02/20/RevitApi%E5%90%88%E9%9B%86/Autodesk.Revit.DB%20Curve/" title="Autodesk.Revit.DB Curve">Autodesk.Revit.DB Curve</a><time datetime="2025-02-27T12:28:18.794Z" title="更新于 2025-02-27 20:28:18">2025-02-27</time></div></div><div class="aside-list-item no-cover"><div class="content"><a class="title" href="/2025/02/20/RevitApi%E5%90%88%E9%9B%86/Autodesk.Revit.DB%20Line/" title="Autodesk.Revit.DB Line">Autodesk.Revit.DB Line</a><time datetime="2025-02-27T12:28:08.332Z" title="更新于 2025-02-27 20:28:08">2025-02-27</time></div></div><div class="aside-list-item no-cover"><div class="content"><a class="title" href="/2025/02/16/RevitApi%E5%90%88%E9%9B%86/Autodesk.Revit.ApplicationServices%20Application/" title="Autodesk.Revit.ApplicationServices Application">Autodesk.Revit.ApplicationServices Application</a><time datetime="2025-02-27T12:27:54.491Z" title="更新于 2025-02-27 20:27:54">2025-02-27</time></div></div><div class="aside-list-item no-cover"><div class="content"><a class="title" href="/2025/02/17/RevitApi%E5%90%88%E9%9B%86/Autodesk.Revit.UI%20UIApplication/" title="Autodesk.Revit.UI UIApplication">Autodesk.Revit.UI UIApplication</a><time datetime="2025-02-27T12:27:21.126Z" title="更新于 2025-02-27 20:27:21">2025-02-27</time></div></div></div></div></div></div></main><footer id="footer" style="background-image: url(/images/topback.jpg);"><div id="footer-wrap"><div class="copyright">&copy;2024 - 2025 By funtim41@gmail.com</div><div class="framework-info"><span>框架 </span><a target="_blank" rel="noopener" href="https://hexo.io">Hexo</a><span class="footer-separator">|</span><span>主题 </span><a target="_blank" rel="noopener" href="https://github.com/jerryc127/hexo-theme-butterfly">Butterfly</a></div><div class="footer_custom_text">学而不思则罔，思而不学则殆。</div></div></footer></div><div id="rightside"><div id="rightside-config-hide"><button id="readmode" type="button" title="阅读模式"><i class="fas fa-book-open"></i></button><button id="darkmode" type="button" title="日间和夜间模式切换"><i class="fas fa-adjust"></i></button><button id="hide-aside-btn" type="button" title="单栏和双栏切换"><i class="fas fa-arrows-alt-h"></i></button></div><div id="rightside-config-show"><button id="rightside-config" type="button" title="设置"><i class="fas fa-cog fa-spin"></i></button><button class="close" id="mobile-toc-button" type="button" title="目录"><i class="fas fa-list-ul"></i></button><a id="to_comment" href="#post-comment" title="前往评论"><i class="fas fa-comments"></i></a><button id="go-up" type="button" title="回到顶部"><span class="scroll-percent"></span><i class="fas fa-arrow-up"></i></button></div></div><div><script src="/js/utils.js"></script><script src="/js/main.js"></script><script src="https://cdn.jsdelivr.net/npm/node-snackbar/dist/snackbar.min.js"></script><script>(() => {
  const panguFn = () => {
    if (typeof pangu === 'object') pangu.autoSpacingPage()
    else {
      btf.getScript('https://cdn.jsdelivr.net/npm/pangu/dist/browser/pangu.min.js')
        .then(() => {
          pangu.autoSpacingPage()
        })
    }
  }

  const panguInit = () => {
    if (false){
      GLOBAL_CONFIG_SITE.isPost && panguFn()
    } else {
      panguFn()
    }
  }

  btf.addGlobalFn('pjaxComplete', panguInit, 'pangu')
  document.addEventListener('DOMContentLoaded', panguInit)
})()</script><div class="js-pjax"><script>(() => {
  const isShuoshuo = GLOBAL_CONFIG_SITE.isShuoshuo
  const option = null

  const getGiscusTheme = theme => theme === 'dark' ? 'dark' : 'light'

  const createScriptElement = config => {
    const ele = document.createElement('script')
    Object.entries(config).forEach(([key, value]) => {
      ele.setAttribute(key, value)
    })
    return ele
  }

  const loadGiscus = (el = document, key) => {
    const mappingConfig = isShuoshuo
      ? { 'data-mapping': 'specific', 'data-term': key }
      : { 'data-mapping': (option && option['data-mapping']) || 'pathname' }

    const giscusConfig = {
      src: 'https://giscus.app/client.js',
      'data-repo': 'FunTim41/funtim41.github.io',
      'data-repo-id': 'R_kgDONjG8ww',
      'data-category-id': 'DIC_kwDONjG8w84Cllg2',
      'data-theme': getGiscusTheme(document.documentElement.getAttribute('data-theme')),
      'data-reactions-enabled': '1',
      crossorigin: 'anonymous',
      async: true,
      ...option,
      ...mappingConfig
    }

    const scriptElement = createScriptElement(giscusConfig)

    el.querySelector('#giscus-wrap').appendChild(scriptElement)

    if (isShuoshuo) {
      window.shuoshuoComment.destroyGiscus = () => {
        if (el.children.length) {
          el.innerHTML = ''
          el.classList.add('no-comment')
        }
      }
    }
  }

  const changeGiscusTheme = theme => {
    const iframe = document.querySelector('#giscus-wrap iframe')
    if (iframe) {
      const message = {
        giscus: {
          setConfig: {
            theme: getGiscusTheme(theme)
          }
        }
      }
      iframe.contentWindow.postMessage(message, 'https://giscus.app')
    }
  }

  btf.addGlobalFn('themeChange', changeGiscusTheme, 'giscus')

  if (isShuoshuo) {
    'Giscus' === 'Giscus'
      ? window.shuoshuoComment = { loadComment: loadGiscus }
      : window.loadOtherComment = loadGiscus
    return
  }

  if ('Giscus' === 'Giscus' || !false) {
    if (false) btf.loadComment(document.getElementById('giscus-wrap'), loadGiscus)
    else loadGiscus()
  } else {
    window.loadOtherComment = loadGiscus
  }
})()</script></div><script defer="defer" id="fluttering_ribbon" mobile="false" src="https://cdn.jsdelivr.net/npm/butterfly-extsrc/dist/canvas-fluttering-ribbon.min.js"></script><script async data-pjax src="//busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js"></script><div id="local-search"><div class="search-dialog"><nav class="search-nav"><span class="search-dialog-title">搜索</span><span id="loading-status"></span><button class="search-close-button"><i class="fas fa-times"></i></button></nav><div class="text-center" id="loading-database"><i class="fas fa-spinner fa-pulse"></i><span>  数据加载中</span></div><div class="search-wrap"><div id="local-search-input"><div class="local-search-box"><input class="local-search-box--input" placeholder="搜索文章" type="text"/></div></div><hr/><div id="local-search-results"></div><div id="local-search-stats-wrap"></div></div></div><div id="search-mask"></div><script src="/js/search/local-search.js"></script></div></div></body></html>