<!DOCTYPE html><html lang="zh-CN" data-theme="light"><head><meta charset="UTF-8"><meta http-equiv="X-UA-Compatible" content="IE=edge"><meta name="viewport" content="width=device-width, initial-scale=1.0,viewport-fit=cover"><title>19草图 | funtim的博客</title><meta name="author" content="funtim41@gmail.com"><meta name="copyright" content="funtim41@gmail.com"><meta name="format-detection" content="telephone=no"><meta name="theme-color" content="#ffffff"><meta name="description" content="草图要在Revit中创建图元或编辑其轮廓，必须先创建草图对象。需要绘制草图的图元示例包括：  Roofs 屋顶 Floors 地板 Stairs 楼梯 Railings 栏杆  还需要草图来定义其他类型的几何图形，例如：  Extrusions 拉伸 Openings 开口 Regions 区域  在Revit Platform API中，草图函数由二维和三维草图类表示，如下所示：  二维Sket">
<meta property="og:type" content="article">
<meta property="og:title" content="19草图">
<meta property="og:url" content="https://funtim41.github.io/2024/12/15/%E4%BA%8C%E5%BC%80%E6%8C%87%E5%8D%97/19%E8%8D%89%E5%9B%BE/">
<meta property="og:site_name" content="funtim的博客">
<meta property="og:description" content="草图要在Revit中创建图元或编辑其轮廓，必须先创建草图对象。需要绘制草图的图元示例包括：  Roofs 屋顶 Floors 地板 Stairs 楼梯 Railings 栏杆  还需要草图来定义其他类型的几何图形，例如：  Extrusions 拉伸 Openings 开口 Regions 区域  在Revit Platform API中，草图函数由二维和三维草图类表示，如下所示：  二维Sket">
<meta property="og:locale" content="zh_CN">
<meta property="og:image" content="https://funtim41.github.io/images/4stars.png">
<meta property="article:published_time" content="2024-12-15T04:29:34.000Z">
<meta property="article:modified_time" content="2024-12-29T07:31:06.916Z">
<meta property="article:author" content="funtim41@gmail.com">
<meta property="article:tag" content="Revit">
<meta name="twitter:card" content="summary">
<meta name="twitter:image" content="https://funtim41.github.io/images/4stars.png"><link rel="shortcut icon" href="/images/OIP.jfif"><link rel="canonical" href="https://funtim41.github.io/2024/12/15/%E4%BA%8C%E5%BC%80%E6%8C%87%E5%8D%97/19%E8%8D%89%E5%9B%BE/"><link rel="preconnect" href="//cdn.jsdelivr.net"/><link rel="stylesheet" href="/css/index.css"><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free/css/all.min.css"><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/node-snackbar/dist/snackbar.min.css" media="print" onload="this.media='all'"><script>
    (() => {
      
    const saveToLocal = {
      set: (key, value, ttl) => {
        if (!ttl) return
        const expiry = Date.now() + ttl * 86400000
        localStorage.setItem(key, JSON.stringify({ value, expiry }))
      },
      get: key => {
        const itemStr = localStorage.getItem(key)
        if (!itemStr) return undefined
        const { value, expiry } = JSON.parse(itemStr)
        if (Date.now() > expiry) {
          localStorage.removeItem(key)
          return undefined
        }
        return value
      }
    }

    window.btf = {
      saveToLocal,
      getScript: (url, attr = {}) => new Promise((resolve, reject) => {
        const script = document.createElement('script')
        script.src = url
        script.async = true
        Object.entries(attr).forEach(([key, val]) => script.setAttribute(key, val))
        script.onload = script.onreadystatechange = () => {
          if (!script.readyState || /loaded|complete/.test(script.readyState)) resolve()
        }
        script.onerror = reject
        document.head.appendChild(script)
      }),
      getCSS: (url, id) => new Promise((resolve, reject) => {
        const link = document.createElement('link')
        link.rel = 'stylesheet'
        link.href = url
        if (id) link.id = id
        link.onload = link.onreadystatechange = () => {
          if (!link.readyState || /loaded|complete/.test(link.readyState)) resolve()
        }
        link.onerror = reject
        document.head.appendChild(link)
      }),
      addGlobalFn: (key, fn, name = false, parent = window) => {
        if (!false && key.startsWith('pjax')) return
        const globalFn = parent.globalFn || {}
        globalFn[key] = globalFn[key] || {}
        globalFn[key][name || Object.keys(globalFn[key]).length] = fn
        parent.globalFn = globalFn
      }
    }
  
      
      const activateDarkMode = () => {
        document.documentElement.setAttribute('data-theme', 'dark')
        if (document.querySelector('meta[name="theme-color"]') !== null) {
          document.querySelector('meta[name="theme-color"]').setAttribute('content', '#0d0d0d')
        }
      }
      const activateLightMode = () => {
        document.documentElement.setAttribute('data-theme', 'light')
        if (document.querySelector('meta[name="theme-color"]') !== null) {
          document.querySelector('meta[name="theme-color"]').setAttribute('content', '#ffffff')
        }
      }

      btf.activateDarkMode = activateDarkMode
      btf.activateLightMode = activateLightMode

      const theme = saveToLocal.get('theme')
    
          theme === 'dark' ? activateDarkMode() : theme === 'light' ? activateLightMode() : null
        
      
      const asideStatus = saveToLocal.get('aside-status')
      if (asideStatus !== undefined) {
        document.documentElement.classList.toggle('hide-aside', asideStatus === 'hide')
      }
    
      
    const detectApple = () => {
      if (/iPad|iPhone|iPod|Macintosh/.test(navigator.userAgent)) {
        document.documentElement.classList.add('apple')
      }
    }
    detectApple()
  
    })()
  </script><script>const GLOBAL_CONFIG = {
  root: '/',
  algolia: undefined,
  localSearch: {"path":"/search.xml","preload":false,"top_n_per_article":1,"unescape":false,"languages":{"hits_empty":"未找到符合您查询的内容：${query}","hits_stats":"共找到 ${hits} 篇文章"}},
  translate: undefined,
  highlight: {"plugin":"highlight.js","highlightCopy":true,"highlightLang":true,"highlightHeightLimit":false,"highlightFullpage":false,"highlightMacStyle":false},
  copy: {
    success: '复制成功',
    error: '复制失败',
    noSupport: '浏览器不支持'
  },
  relativeDate: {
    homepage: false,
    post: false
  },
  runtime: '',
  dateSuffix: {
    just: '刚刚',
    min: '分钟前',
    hour: '小时前',
    day: '天前',
    month: '个月前'
  },
  copyright: {"limitCount":150,"languages":{"author":"作者: funtim41@gmail.com","link":"链接: ","source":"来源: funtim的博客","info":"著作权归作者所有。商业转载请联系作者获得授权，非商业转载请注明出处。"}},
  lightbox: 'null',
  Snackbar: {"chs_to_cht":"已切换为繁体中文","cht_to_chs":"已切换为简体中文","day_to_night":"已切换为深色模式","night_to_day":"已切换为浅色模式","bgLight":"#49b1f5","bgDark":"#1f1f1f","position":"bottom-left"},
  infinitegrid: {
    js: 'https://cdn.jsdelivr.net/npm/@egjs/infinitegrid/dist/infinitegrid.min.js',
    buttonText: '加载更多'
  },
  isPhotoFigcaption: false,
  islazyload: false,
  isAnchor: true,
  percent: {
    toc: true,
    rightside: true,
  },
  autoDarkmode: false
}</script><script id="config-diff">var GLOBAL_CONFIG_SITE = {
  title: '19草图',
  isPost: true,
  isHome: false,
  isHighlightShrink: false,
  isToc: true,
  isShuoshuo: false
}</script><link rel="stylesheet" href="/css/bar.css"><meta name="generator" content="Hexo 7.3.0"></head><body><div id="web_bg" style="background: Color(#995a82);"></div><div id="sidebar"><div id="menu-mask"></div><div id="sidebar-menus"><div class="avatar-img text-center"><img src="/images/4stars.png" onerror="onerror=null;src='/img/friend_404.gif'" alt="avatar"/></div><div class="site-data text-center"><a href="/archives/"><div class="headline">文章</div><div class="length-num">51</div></a><a href="/tags/"><div class="headline">标签</div><div class="length-num">2</div></a><a href="/categories/"><div class="headline">分类</div><div class="length-num">3</div></a></div><div class="menus_items"><div class="menus_item"><a class="site-page" href="/"><i class="fa-fw fas fa-home"></i><span> Home</span></a></div><div class="menus_item"><a class="site-page" href="/archives/"><i class="fa-fw fas fa-archive"></i><span> Timeline</span></a></div><div class="menus_item"><a class="site-page" href="/tags/"><i class="fa-fw fas fa-tags"></i><span> Tags</span></a></div><div class="menus_item"><a class="site-page" href="/categories/"><i class="fa-fw fas fa-folder-open"></i><span> Categories</span></a></div><div class="menus_item"><a class="site-page" href="/Links/"><i class="fa-fw fas fa-link"></i><span> Links</span></a></div><div class="menus_item"><a class="site-page" href="/about/"><i class="fa-fw fas fa-heart"></i><span> About</span></a></div></div></div></div><div class="post" id="body-wrap"><header class="post-bg fixed" id="page-header" style="background-image: url(/images/topback.jpg);"><nav id="nav"><span id="blog-info"><a class="nav-site-title" href="/"><img class="site-icon" src="/images/OIP.jfif" alt="Logo"><span class="site-name">funtim的博客</span></a><a class="nav-page-title" href="/"><span class="site-name">19草图</span></a></span><div id="menus"><div id="search-button"><span class="site-page social-icon search"><i class="fas fa-search fa-fw"></i><span> 搜索</span></span></div><div class="menus_items"><div class="menus_item"><a class="site-page" href="/"><i class="fa-fw fas fa-home"></i><span> Home</span></a></div><div class="menus_item"><a class="site-page" href="/archives/"><i class="fa-fw fas fa-archive"></i><span> Timeline</span></a></div><div class="menus_item"><a class="site-page" href="/tags/"><i class="fa-fw fas fa-tags"></i><span> Tags</span></a></div><div class="menus_item"><a class="site-page" href="/categories/"><i class="fa-fw fas fa-folder-open"></i><span> Categories</span></a></div><div class="menus_item"><a class="site-page" href="/Links/"><i class="fa-fw fas fa-link"></i><span> Links</span></a></div><div class="menus_item"><a class="site-page" href="/about/"><i class="fa-fw fas fa-heart"></i><span> About</span></a></div></div><div id="toggle-menu"><span class="site-page"><i class="fas fa-bars fa-fw"></i></span></div></div></nav><div id="post-info"><h1 class="post-title">19草图</h1><div id="post-meta"><div class="meta-firstline"><span class="post-meta-date"><i class="far fa-calendar-alt fa-fw post-meta-icon"></i><span class="post-meta-label">发表于</span><time class="post-meta-date-created" datetime="2024-12-15T04:29:34.000Z" title="发表于 2024-12-15 12:29:34">2024-12-15</time><span class="post-meta-separator">|</span><i class="fas fa-history fa-fw post-meta-icon"></i><span class="post-meta-label">更新于</span><time class="post-meta-date-updated" datetime="2024-12-29T07:31:06.916Z" title="更新于 2024-12-29 15:31:06">2024-12-29</time></span><span class="post-meta-categories"><span class="post-meta-separator">|</span><i class="fas fa-inbox fa-fw post-meta-icon"></i><a class="post-meta-categories" href="/categories/Revit%E4%BA%8C%E6%AC%A1%E5%BC%80%E5%8F%91%E4%BA%BA%E5%91%98%E6%8C%87%E5%8D%97/">Revit二次开发人员指南</a></span></div><div class="meta-secondline"><span class="post-meta-separator">|</span><span class="post-meta-pv-cv" id="" data-flag-title=""><i class="far fa-eye fa-fw post-meta-icon"></i><span class="post-meta-label">浏览量:</span><span id="busuanzi_value_page_pv"><i class="fa-solid fa-spinner fa-spin"></i></span></span></div></div></div></header><main class="layout" id="content-inner"><div id="post"><article class="container post-content" id="article-container"><h1 id="草图"><a href="#草图" class="headerlink" title="草图"></a><a target="_blank" rel="noopener" href="https://help.autodesk.com/view/RVT/2018/ENU/?guid=Revit_API_Revit_API_Developers_Guide_Revit_Geometric_Elements_Sketching_html">草图</a></h1><p>要在Revit中创建图元或编辑其轮廓，必须先创建草图对象。需要绘制草图的图元示例包括：</p>
<ul>
<li>Roofs 屋顶</li>
<li>Floors 地板</li>
<li>Stairs 楼梯</li>
<li>Railings 栏杆</li>
</ul>
<p>还需要草图来定义其他类型的几何图形，例如：</p>
<ul>
<li>Extrusions 拉伸</li>
<li>Openings 开口</li>
<li>Regions 区域</li>
</ul>
<p>在Revit Platform API中，草图函数由二维和三维草图类表示，如下所示：</p>
<ul>
<li>二维Sketch：<ul>
<li>SketchPlane 草图平面</li>
<li>Sketch 草图</li>
<li>ModelCurve 模型线</li>
<li>and more</li>
</ul>
</li>
<li>三维Sketch：<ul>
<li>GenericForm 通用形状</li>
<li>Path3D 3D路径</li>
</ul>
</li>
</ul>
<p>除了草图元素外，本章还介绍了ModelCurve。有关元素分类的详细信息，请参阅元素部分中的元素分类。</p>
<p> 本节中的页面</p>
<ul>
<li>2DSketch类</li>
<li>3DSketch</li>
<li>模型线</li>
</ul>
<h2 id="2D-Sketch类"><a href="#2D-Sketch类" class="headerlink" title="2D Sketch类"></a>2D Sketch类</h2><p>Sketch类表示用于创建3D模型的平面中的封闭曲线。关键功能由SketchPlane和CurveLoop属性表示。</p>
<p>编辑Revit文件时，无法通过迭代Document.Elements枚举来检索Sketch对象，因为所有Sketch对象都是瞬态Elements。访问族的三维建模信息时，草图对象对于形成几何图形非常重要。有关更多详细信息，请参见3D草图。</p>
<p>SketchPlane是所有2D草图类（如ModelCurve和Sketch）的基础。SketchPlane也是DetailCurve等2D注释元素的基础。ModelCurve和DetailCurve都具有SketchPlane属性，并且在相应的创建方法中需要SketchPlane。SketchPlane在Revit UI中始终不可见。</p>
<p>每个ModelCurve必须位于一个SketchPlane中。换句话说，无论您在UI中还是通过使用API绘制ModelCurve，都必须存在SketchPlane。因此，在绘制ModelCurve的二维视图中至少存在一个SketchPlane。</p>
<p>二维视图包含CeilingPlan、FloorPlan和Elevation ViewTypes。默认情况下，会自动为所有这些视图创建“草绘平面”（SketchPlane）。与二维视图相关的SketchPlane Name返回视图名称，例如Level 1或North。</p>
<p><img src="https://help.autodesk.com/cloudhelp/2018/ENU/Revit-API/images/GUID-9B03E831-1E6C-4CE2-9149-3F7B309A5B5D-low.png"></p>
<p>图77：拾取平面以标识新的工作平面</p>
<p>指定新工作平面时，可以选择“拾取平面”，如上图所示。拾取平面后，选择特定图元（如墙）上的平面，如下图所示。在这种情况下，SketchPlane.Name属性返回与该元素相关的字符串。例如，在下图中，SketchPlane.Name属性返回与Wall.Name属性相同的“Generic - 8”。</p>
<p><img src="https://help.autodesk.com/cloudhelp/2018/ENU/Revit-API/images/GUID-67D74CA2-D850-422F-A4FF-E762D683DFC9-low.png"></p>
<p> 图78：在墙上拾取一个平面作为工作平面</p>
<p>注意：“草绘平面”与工作平面不同，因为工作平面是可见的并且可以选择。它在当前API中没有特定的类，但由Element类表示。必须基于特定的SketchPlane定义工作平面。工作平面和SketchPlane Category属性都返回null。尽管“草绘平面”始终不可见，但始终存在与工作平面对应的“草绘平面”。工作平面用于在文本和图片中表达SketchPlane。</p>
<p>以下信息适用于SketchPlane成员：</p>
<ul>
<li>ID、UniqueId、Name和Plane属性返回值;</li>
<li>参数属性为空</li>
<li>Location属性返回Location对象</li>
<li>其他属性返回null。</li>
</ul>
<p>Plane包含SketchPlane几何信息。SketchPlane使用Plane设置平面坐标系，如下图所示：</p>
<p><img src="https://help.autodesk.com/cloudhelp/2018/ENU/Revit-API/images/GUID-415773EF-49A7-4158-B9DD-42A218063E81-low.png"></p>
<p>图79：SketchPlane和Plane坐标系</p>
<p>以下代码示例说明如何创建新的SketchPlane：</p>
<p>代码区域17-1：创建新的草绘平面</p>
<figure class="highlight c#"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="keyword">private</span> SketchPlane <span class="title">CreateSketchPlane</span>(<span class="params">UIApplication application</span>)</span></span><br><span class="line">&#123;</span><br><span class="line">    <span class="comment">//try to create a new sketch plane</span></span><br><span class="line">    XYZ newNormal = <span class="keyword">new</span> XYZ(<span class="number">1</span>, <span class="number">1</span>, <span class="number">0</span>);  <span class="comment">// the normal vector</span></span><br><span class="line">    XYZ newOrigin = <span class="keyword">new</span> XYZ(<span class="number">0</span>, <span class="number">0</span>, <span class="number">0</span>);  <span class="comment">// the origin point</span></span><br><span class="line">    <span class="comment">// create geometry plane</span></span><br><span class="line">    Plane geometryPlane = Plane.CreateByNormalAndOrigin(newNormal, newOrigin);</span><br><span class="line"></span><br><span class="line">    <span class="comment">// create sketch plane</span></span><br><span class="line">    SketchPlane sketchPlane = SketchPlane.Create(application.ActiveUIDocument.Document,geometryPlane);</span><br><span class="line"></span><br><span class="line">    <span class="keyword">return</span> sketchPlane;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<h2 id="3D-Sketch"><a href="#3D-Sketch" class="headerlink" title="3D Sketch"></a>3D Sketch</h2><p>三维草图用于编辑族或创建三维对象。在Revit Platform API中，可以使用以下类完成三维草图。</p>
<ul>
<li>Extrusion </li>
<li>Revolution </li>
<li>Blend </li>
<li>Sweep</li>
</ul>
<p>换句话说，有四个操作可以将2D模型转换为3D模型。有关在2D中绘制草图的详细信息，请参见2D草图类。</p>
<p><strong>Extrusion</strong> </p>
<p>Revit使用拉伸定义族的三维几何图形。通过在平面上定义二维草图来创建拉伸;然后Revit在起点和终点之间拉伸草图。</p>
<p>查询“拉伸形状”对象，以查找要在族建模和体量中使用的常规形状。Extrusion类具有以下属性：</p>
<p>表40：拉伸属性</p>
<table>
<thead>
<tr>
<th>**Property **</th>
<th>**Description **</th>
</tr>
</thead>
<tbody><tr>
<td>ExtrusionStart</td>
<td>返回拉伸起点。这是一个双类型。</td>
</tr>
<tr>
<td>ExtrusionEnd</td>
<td>返回拉伸终点。这是一个双类型。</td>
</tr>
<tr>
<td>Sketch</td>
<td>返回拉伸草图。它包含一个草图平面和一些曲线。</td>
</tr>
</tbody></table>
<p><img src="https://help.autodesk.com/cloudhelp/2018/ENU/Revit-API/images/GUID-8F322D1A-5035-4E9E-88F6-2AFAD258E59E-low.png"></p>
<p>图81：拉伸结果</p>
<p><strong>Revolution</strong> </p>
<p>“旋转”命令可创建绕轴旋转的几何图形。可以使用“旋转”命令在家具、圆屋顶或柱上创建门把手或其他把手。</p>
<p>查询“旋转形式”对象，以获得要在族建模和体量中使用的常规形式。Revolution类具有以下属性：</p>
<p>表41：Revolution属性</p>
<table>
<thead>
<tr>
<th>**Property **</th>
<th>**Description **</th>
</tr>
</thead>
<tbody><tr>
<td>Axis</td>
<td>返回轴。它是一个ModelLine对象。</td>
</tr>
<tr>
<td>EndAngle</td>
<td>返回结束角度。这是一个double类型。</td>
</tr>
<tr>
<td>Sketch</td>
<td>返回拉伸草图。它包含一个SketchPlane和一些曲线。</td>
</tr>
</tbody></table>
<p>EndAngle与Revit UI中的相同参数一致。下图说明了Revolution对应参数、草图和结果。</p>
<p><img src="https://help.autodesk.com/cloudhelp/2018/ENU/Revit-API/images/GUID-2CF60823-4258-4838-ADA8-61F52C4B3515-low.png"></p>
<p>图82：对应参数</p>
<p><img src="https://help.autodesk.com/cloudhelp/2018/ENU/Revit-API/images/GUID-10A03254-96BC-4023-99C5-B22AF43A0702-low.png"></p>
<p>图83：旋转草图</p>
<p><img src="https://help.autodesk.com/cloudhelp/2018/ENU/Revit-API/images/GUID-803C819E-E85C-462B-BF33-CC49E9FC3C86-low.png"></p>
<p>图84：旋转结果</p>
<p>Note: 注意事项：</p>
<ul>
<li>无法使用Revit Platform API访问“起始角度”。</li>
<li>如果“结束角度”为正，则“旋转”方向为顺时针。如果为负，则旋转方向为逆时针</li>
</ul>
<h2 id="Blend"><a href="#Blend" class="headerlink" title="Blend"></a>Blend</h2><p>“融合”命令将两个轮廓融合在一起。例如，如果绘制了一个大矩形，并在其上绘制了一个小矩形，则Revit会将这两个形状融合在一起。</p>
<p>查询“融合形式”对象以获得要在族建模和体量中使用的常规形式。Blend类具有以下属性：</p>
<p>表42：Blend属性</p>
<table>
<thead>
<tr>
<th>**Property **</th>
<th>**Description **</th>
</tr>
</thead>
<tbody><tr>
<td>BottomSketch</td>
<td>返回底部草图。它是一个Sketch对象。</td>
</tr>
<tr>
<td>TopSketch</td>
<td>返回顶部草图融合。它是一个Sketch对象。</td>
</tr>
<tr>
<td>FirstEnd</td>
<td>返回第一个端点。这是一个double类型。</td>
</tr>
<tr>
<td>SecondEnd</td>
<td>返回第二个终点。这是一个double类型。</td>
</tr>
</tbody></table>
<p>FirstEnd和SecondEnd属性值与Revit UI中的相同参数一致。下图说明了“融合”对应的参数、草图和结果。</p>
<p><img src="https://help.autodesk.com/cloudhelp/2018/ENU/Revit-API/images/GUID-BF73A304-626D-43C2-9A53-8C396270369F-low.png"></p>
<p>图85：UI中的融合参数</p>
<p><img src="https://help.autodesk.com/cloudhelp/2018/ENU/Revit-API/images/GUID-14B5134B-B412-429C-8CBF-A542C16659C0-low.png"></p>
<p>图86：融合顶部草图和底部草图</p>
<p><img src="https://help.autodesk.com/cloudhelp/2018/ENU/Revit-API/images/GUID-F637CA72-BA0E-4917-B24D-93947FD69E22-low.png"></p>
<p> 图87：融合结果</p>
<h2 id="Sweep"><a href="#Sweep" class="headerlink" title="Sweep"></a>Sweep</h2><p>“放样”命令可沿创建的二维路径或选定的三维路径沿着放样一个轮廓。路径可以是开环或闭环，但必须穿过轮廓平面。</p>
<p>查询“放样形状”对象，以获得用于族建模和体量的常规形状。Sweep类具有以下属性：</p>
<p>表43：Sweep 属性</p>
<table>
<thead>
<tr>
<th><strong>Property</strong></th>
<th>**Description **</th>
</tr>
</thead>
<tbody><tr>
<td>Path3d</td>
<td>返回三维路径草图。它是一个Path3D对象。</td>
</tr>
<tr>
<td>PathSketch</td>
<td>返回平面路径草图。它是一个Sketch对象。</td>
</tr>
<tr>
<td>ProfileSketch</td>
<td>返回轮廓草图。它是一个Sketch对象。</td>
</tr>
<tr>
<td>EnableTrajSegmentation</td>
<td>返回轨迹分段状态。它是一个布尔值。</td>
</tr>
<tr>
<td>MaxSegmentAngle</td>
<td>返回最大线段角度。这是一个double类型。</td>
</tr>
</tbody></table>
<p>创建2D路径与其他形状类似。通过拾取创建的3D曲线来获取3D路径。</p>
<p><img src="https://help.autodesk.com/cloudhelp/2018/ENU/Revit-API/images/GUID-C9B66D17-E7EF-4CE4-B186-E1862B49461D-low.png"></p>
<p>图88：选择Sweep 3D路径</p>
<p>注意：以下信息适用于放样：</p>
<ul>
<li>仅当使用“拾取路径”获取3D路径时，Path3d特性才可用。</li>
<li>无论路径是三维还是二维，PathSketch都可用。<img src="https://help.autodesk.com/cloudhelp/2018/ENU/Revit-API/images/GUID-4E2B269D-16CC-417E-A4BF-EBAD946C73DC-low.png" alt="img"><br>图89：扫描轮廓草图</li>
</ul>
<p>注意：轮廓草图垂直于路径。</p>
<p>分段放样对于创建机械风管弯头非常有用。通过设置两个放样参数并绘制带有圆弧的路径来创建分段放样。</p>
<p><img src="https://help.autodesk.com/cloudhelp/2018/ENU/Revit-API/images/GUID-B63CD7A5-25B1-440A-A31B-AB6FADF08169-low.png"></p>
<p>图90：UI中的相应分段设置</p>
<p>注意：以下信息适用于分段放样：</p>
<ul>
<li>这些参数仅影响路径中的弧。</li>
<li>放样的最小分段数为两个。</li>
<li>通过清除“轨迹分段”（Trajectory Segmentation）复选框，将分段放样更改为非分段放样。EnableTrajSegmentation属性返回false。</li>
<li>如果EnableTrajSegmentation属性为false，则MaxSegmentAngle的值为默认360°。<img src="https://help.autodesk.com/cloudhelp/2018/ENU/Revit-API/images/GUID-2AACA3CE-F284-4412-9887-B84FB87CC6BA-low.png" alt="img"></li>
</ul>
<p>图91：放样结果</p>
<h2 id="模型线"><a href="#模型线" class="headerlink" title="模型线"></a>模型线</h2><p>ModelCurve表示项目中的模型线。它存在于三维空间中，在所有视图中可见。</p>
<p>以下图片说明了四个ModelCurve派生类：<br><img src="https://help.autodesk.com/cloudhelp/2018/ENU/Revit-API/images/GUID-1CE68863-4E07-4852-A896-5ACE5235B7AE-low.png" alt="img"> 图92：ModelLine和ModelArc<br><img src="https://help.autodesk.com/cloudhelp/2018/ENU/Revit-API/images/GUID-E914167B-553C-4B5B-A87E-1AAB487A12B5-low.png" alt="img"> 图93：ModelEllipse和ModelNurbSpline</p>
<p><strong>创建模型线</strong></p>
<p>创建模型曲线的关键是创建曲线所在的几何、曲线和草图平面。根据您输入的Geometry.Curve类型，返回的相应ModelCurve可以向下转换为正确的类型。</p>
<p>以下示例说明如何创建新的模型曲线（ModelLine和ModelArc）：</p>
<p>代码区域17-2：创建新的模型曲线</p>
<figure class="highlight c#"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br><span class="line">23</span><br><span class="line">24</span><br><span class="line">25</span><br><span class="line">26</span><br><span class="line">27</span><br></pre></td><td class="code"><pre><span class="line"><span class="comment">// get handle to application from document</span></span><br><span class="line">Autodesk.Revit.ApplicationServices.Application application = document.Application;</span><br><span class="line"></span><br><span class="line"><span class="comment">// Create a geometry line in Revit application</span></span><br><span class="line">XYZ startPoint = <span class="keyword">new</span> XYZ(<span class="number">0</span>, <span class="number">0</span>, <span class="number">0</span>);</span><br><span class="line">XYZ endPoint = <span class="keyword">new</span> XYZ(<span class="number">10</span>, <span class="number">10</span>, <span class="number">0</span>);</span><br><span class="line">Line geomLine = Line.CreateBound(startPoint, endPoint);</span><br><span class="line"></span><br><span class="line"><span class="comment">// Create a geometry arc in Revit application</span></span><br><span class="line">XYZ end0 = <span class="keyword">new</span> XYZ(<span class="number">1</span>, <span class="number">0</span>, <span class="number">0</span>);</span><br><span class="line">XYZ end1 = <span class="keyword">new</span> XYZ(<span class="number">10</span>, <span class="number">10</span>, <span class="number">10</span>);</span><br><span class="line">XYZ pointOnCurve = <span class="keyword">new</span> XYZ(<span class="number">10</span>, <span class="number">0</span>, <span class="number">0</span>);</span><br><span class="line">Arc geomArc = Arc.Create(end0, end1, pointOnCurve);</span><br><span class="line"></span><br><span class="line"><span class="comment">// Create a geometry plane in Revit application</span></span><br><span class="line">XYZ origin = <span class="keyword">new</span> XYZ(<span class="number">0</span>, <span class="number">0</span>, <span class="number">0</span>);</span><br><span class="line">XYZ normal = <span class="keyword">new</span> XYZ(<span class="number">1</span>, <span class="number">1</span>, <span class="number">0</span>);</span><br><span class="line">Plane geomPlane = Plane.CreateByNormalAndOrigin(normal, origin);</span><br><span class="line"></span><br><span class="line"><span class="comment">// Create a sketch plane in current document</span></span><br><span class="line">SketchPlane sketch = SketchPlane.Create(document, geomPlane);</span><br><span class="line"></span><br><span class="line"><span class="comment">// Create a ModelLine element using the created geometry line and sketch plane</span></span><br><span class="line">ModelLine line = document.Create.NewModelCurve(geomLine, sketch) <span class="keyword">as</span> ModelLine;</span><br><span class="line"></span><br><span class="line"><span class="comment">// Create a ModelArc element using the created geometry arc and sketch plane</span></span><br><span class="line">ModelArc arc = document.Create.NewModelCurve(geomArc, sketch) <span class="keyword">as</span> ModelArc;</span><br></pre></td></tr></table></figure>

<p><strong>Members</strong> </p>
<p>GeometryCurve </p>
<p>GeometryCurve属性用于获取或设置模型曲线的几何曲线。除了ModelHermiteSpline，你可以从四个ModelCurves中得到不同的几何曲线;</p>
<ul>
<li>Line </li>
<li>Arc </li>
<li>Ellipse </li>
<li>Nurbspline</li>
</ul>
<p>下面的代码示例说明如何从ModelCurve获取特定Curve。</p>
<p>代码区域17-3：从ModelCurve获取特定曲线</p>
<figure class="highlight c#"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br></pre></td><td class="code"><pre><span class="line"><span class="comment">//get the geometry modelCurve of the model modelCurve</span></span><br><span class="line">Autodesk.Revit.DB.Curve geoCurve = modelCurve.GeometryCurve;</span><br><span class="line"></span><br><span class="line"><span class="keyword">if</span> (geoCurve <span class="keyword">is</span> Autodesk.Revit.DB.Line)</span><br><span class="line">&#123;</span><br><span class="line">        Line geoLine = geoCurve <span class="keyword">as</span> Line;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<p>GeometryCurve属性返回值是一个常规的Geometry.Curve对象，因此，必须使用As运算符来转换对象类型。</p>
<p>注意：以下信息适用于GeometryCurve：</p>
<ul>
<li>在Revit中，无法创建Hermite曲线，但可以从其他软件（如AutoCAD）导入该曲线。Curve是唯一表示Hermite曲线的几何类。</li>
<li>SetPlaneAndCurve（）方法以及Curve和SketchPlane属性设置器用于不同的情况。<ul>
<li>当新曲线位于同一个SketchPlane中，或者新SketchPlane与旧SketchPlane位于同一个平面上时，请使用Curve或SketchPlane属性设置器。</li>
<li>如果新的Curve不在同一个SketchPlane中，或者新的SketchPlane与旧的SketchPlane不在同一个平面上，则必须使用SetPlaneAndCurve（）同时更改Curve值和SketchPlane值，以避免内部数据不一致。</li>
</ul>
</li>
</ul>
<p>线样式</p>
<p>线型由GraphicsStyle类表示。ModelCurve的所有线条样式都可以从GetLineStyleIds（）方法中获得，该方法返回一组GraphicsStyle元素的ElementIds。</p>
<h2 id="注：翻译自Revit-API-Developers-Guide"><a href="#注：翻译自Revit-API-Developers-Guide" class="headerlink" title="注：翻译自Revit API Developers Guide"></a><em><strong>注：</strong></em>翻译自<a target="_blank" rel="noopener" href="https://help.autodesk.com/view/RVT/2018/ENU/?guid=Revit_API_Revit_API_Developers_Guide_html">Revit API Developers Guide</a></h2></article><div class="tag_share"><div class="post-meta__tag-list"><a class="post-meta__tags" href="/tags/Revit/">Revit</a></div><div class="post-share"><div class="social-share" data-image="/images/4stars.png" data-sites="facebook,twitter,wechat,weibo,qq"></div><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/butterfly-extsrc/sharejs/dist/css/share.min.css" media="print" onload="this.media='all'"><script src="https://cdn.jsdelivr.net/npm/butterfly-extsrc/sharejs/dist/js/social-share.min.js" defer></script></div></div><nav class="pagination-post" id="pagination"><a class="pagination-related" href="/2024/12/19/RevitApi%E5%90%88%E9%9B%86/Autodesk.Revit.UI.Selection%20Namespace/" title="Autodesk.Revit.UI.Selection"><div class="cover" style="background: var(--default-bg-color)"></div><div class="info"><div class="info-1"><div class="info-item-1">上一篇</div><div class="info-item-2">Autodesk.Revit.UI.Selection</div></div><div class="info-2"><div class="info-item-1">Autodesk.Revit.UI.SelectionClassesPickedBox包含两个 XYZ 点的类，表示屏幕上的选取框。  Properties  Max 最大坐标数（拾取框的右上角）。  Min 最小坐标（拾取框的左下角）。     SelectableInViewFilter一个过滤器，用于传递在给定视图中可选的元素。  Constructors  SelectableInViewFilter  (Document, ElementId) 构造 SelectableInViewFilter 的新实例。  SelectableInViewFilter (Document, ElementId, Boolean) 构造 SelectableInViewFilter 的新实例，并可选择传递所有不可选择的元素。    Methods  PassesFilter(Element) 将筛选器应用于给定元素。  PassesFilter(Document,...</div></div></div></a><a class="pagination-related" href="/2024/12/15/%E4%BA%8C%E5%BC%80%E6%8C%87%E5%8D%97/20%E6%9D%90%E6%96%99/" title="20材料"><div class="cover" style="background: var(--default-bg-color)"></div><div class="info text-right"><div class="info-1"><div class="info-item-1">下一篇</div><div class="info-item-2">20材料</div></div><div class="info-2"><div class="info-item-1">材质在Revit Platform API中，材质数据作为图元进行存储和管理。就像在Revit UI中一样，材质可以有多个与之关联的资源，但只能使用API指定热学和结构（在Revit...</div></div></div></a></nav><div class="relatedPosts"><div class="headline"><i class="fas fa-thumbs-up fa-fw"></i><span>相关推荐</span></div><div class="relatedPosts-list"><a class="pagination-related" href="/2024/11/18/RevitApi%E5%90%88%E9%9B%86/Autodesk.RevitAddIns%20Namespace/" title="Autodesk.RevitAddIns Namespace"><div class="cover" style="background: var(--default-bg-color)"></div><div class="info text-center"><div class="info-1"><div class="info-item-1"><i class="far fa-calendar-alt fa-fw"></i> 2024-11-18</div><div class="info-item-2">Autodesk.RevitAddIns Namespace</div></div><div class="info-2"><div class="info-item-1">Autodesk.RevitAddIns Namespace类AddInManifestUtility此静态类提供从 Revit .addin 文件中读取清单内容的访问。   方法  GetRevitAddInBundleManifests  GetRevitAddInManifest  GetRevitAddInManifests     RevitAddInApplication表示 Revit 外部应用程序。  构造器  RevitAddInApplication 创建 external application info 类的新实例。    属性  Name  Application name    继承关系  System.Object  Autodesk.RevitAddIns.RevitAddInItem  Autodesk.RevitAddIns.RevitAddInApplication    RevitAddInCommand表示 Revit 外部命令。  构造器  RevitAddInCommand 创建 Add-In Command info...</div></div></div></a><a class="pagination-related" href="/2024/11/18/RevitApi%E5%90%88%E9%9B%86/Autodesk.Revit.DB%20CurveArray/" title="Autodesk.Revit.DB CurveArray"><div class="cover" style="background: var(--default-bg-color)"></div><div class="info text-center"><div class="info-1"><div class="info-item-1"><i class="far fa-calendar-alt fa-fw"></i> 2024-11-18</div><div class="info-item-2">Autodesk.Revit.DB CurveArray</div></div><div class="info-2"><div class="info-item-1">Autodesk.Revit.DB CurveArray可以包含曲线的数组。 语法1public class CurveArray : APIObject, IEnumerable  继承层次结构System Object ​	Autodesk.Revit.DB APIObject ​		Autodesk.Revit.DB CurveArray 另见CurveArray Members Autodesk.Revit.DB Namespace 构造函数CurveArray创建CurveArray类的新实例 方法Append将曲线添加到数组的末尾。 Clear从数组中删除每条曲线，使其为空。 ForwardIterator将一个向前移动的迭代器添加到数组中。 GetEnumerator将一个向前移动的迭代器添加到数组中。 Insert将指定的曲线插入数组。 ReverseIterator返回一个向后移动的迭代器到数组。 属性IsEmpty测试数组是否为空。 Item获取或设置数组中指定索引处的曲线。 Size返回数组中的曲线数。 注：翻译自Revit Api docs 2018</div></div></div></a><a class="pagination-related" href="/2024/12/10/RevitApi%E5%90%88%E9%9B%86/Autodesk.Revit.DB%20Opening/" title="Autodesk.Revit.DB Opening"><div class="cover" style="background: var(--default-bg-color)"></div><div class="info text-center"><div class="info-1"><div class="info-item-1"><i class="far fa-calendar-alt fa-fw"></i> 2024-12-10</div><div class="info-item-2">Autodesk.Revit.DB Opening</div></div><div class="info-2"><div class="info-item-1">Autodesk.Revit.DB OpeningAutodesk Revit项目或族文档中的洞口。 语法1public class Opening : Element  附注该对象表示各种不同类型的洞口：  墙中由修订项目中的两个边界点创建的矩形洞口。 由应用于屋顶、楼板、天花板、梁、支撑或柱的一组曲线创建的洞口。 一个垂直的竖井开口延伸到一个或多个水平。 在族文档中的墙或天花板上创建的简单洞口。  根据打开的类型，此类的某些属性将不可用。 这个对象派生自Element基对象，并且支持该对象的所有方法，例如检索该对象的参数的能力。此对象还支持访问结构分析模型，但此功能仅适用于Autodesk Revit Structure。 示例123456789101112131415161718192021222324252627282930313233343536373839404142434445464748495051### private void Getinfo_Opening(Opening opening)&#123;    string message =...</div></div></div></a><a class="pagination-related" href="/2024/12/10/RevitApi%E5%90%88%E9%9B%86/Autodesk.Revit.DB%20ReferenceIntersector/" title="Autodesk.Revit.DB ReferenceIntersector"><div class="cover" style="background: var(--default-bg-color)"></div><div class="info text-center"><div class="info-1"><div class="info-item-1"><i class="far fa-calendar-alt fa-fw"></i> 2024-12-10</div><div class="info-item-2">Autodesk.Revit.DB ReferenceIntersector</div></div><div class="info-2"><div class="info-item-1">Autodesk.Revit.DB ReferenceIntersector用于查找和返回与从原点和方向创建的射线相交的元素的类。 语法1public class ReferenceIntersector : IDisposable    附注可以构造此类的实例，以返回与由原点和方向创建的射线，或者基于过滤和标志返回元素的子集。 调用者可以选择使用ElementFilter过滤结果，或者通过应用特定的可接受的元素。 调用方还可以指定要返回的对象的类型， 整个元素、几何体对象或其组合。 在所有情况下，要求调用者提供 用于评估的3D视图;输入视图上的视图和可见性设置将确定 返回特定元素（例如，此工具永远不会返回隐藏元素、 和几何图形位于视图剖面框之外的元素）。 该类配置为可以构建单个实例，并用于对多个不同光线进行多次评估。在同一个 ReferenceIntersector 上的调用之间，评估结果不会被保留。 该类还提供了一个选项，用于返回在Revit链接中遇到的图元结果。 当设置 FindReferencesInRevitLinks 标志...</div></div></div></a><a class="pagination-related" href="/2024/12/19/RevitApi%E5%90%88%E9%9B%86/Autodesk.Revit.UI.Selection%20Namespace/" title="Autodesk.Revit.UI.Selection"><div class="cover" style="background: var(--default-bg-color)"></div><div class="info text-center"><div class="info-1"><div class="info-item-1"><i class="far fa-calendar-alt fa-fw"></i> 2024-12-19</div><div class="info-item-2">Autodesk.Revit.UI.Selection</div></div><div class="info-2"><div class="info-item-1">Autodesk.Revit.UI.SelectionClassesPickedBox包含两个 XYZ 点的类，表示屏幕上的选取框。  Properties  Max 最大坐标数（拾取框的右上角）。  Min 最小坐标（拾取框的左下角）。     SelectableInViewFilter一个过滤器，用于传递在给定视图中可选的元素。  Constructors  SelectableInViewFilter  (Document, ElementId) 构造 SelectableInViewFilter 的新实例。  SelectableInViewFilter (Document, ElementId, Boolean) 构造 SelectableInViewFilter 的新实例，并可选择传递所有不可选择的元素。    Methods  PassesFilter(Element) 将筛选器应用于给定元素。  PassesFilter(Document,...</div></div></div></a><a class="pagination-related" href="/2024/12/20/RevitApi%E5%90%88%E9%9B%86/Autodesk.Revit.DB%20Transform/" title="Autodesk.Revit.DB Transform"><div class="cover" style="background: var(--default-bg-color)"></div><div class="info text-center"><div class="info-1"><div class="info-item-1"><i class="far fa-calendar-alt fa-fw"></i> 2024-12-20</div><div class="info-item-2">Autodesk.Revit.DB Transform</div></div><div class="info-2"><div class="info-item-1">Autodesk.Revit.DB Transform仿射三维空间的一个变换。 语法public class Transform : APIObject示例12345678910111213141516171819202122### public static XYZ TransformPoint(XYZ point, Transform transform)&#123;    double x = point.X;    double y = point.Y;    double z = point.Z;    //transform basis of the old coordinate system in the new coordinate // system    XYZ b0 = transform.get_Basis(0);    XYZ b1 = transform.get_Basis(1);    XYZ b2 = transform.get_Basis(2);    XYZ origin = transform.Origin;       ...</div></div></div></a></div></div><hr class="custom-hr"/><div id="post-comment"><div class="comment-head"><div class="comment-headline"><i class="fas fa-comments fa-fw"></i><span> 评论</span></div></div><div class="comment-wrap"><div><div id="giscus-wrap"></div></div></div></div></div><div class="aside-content" id="aside-content"><div class="card-widget card-info text-center"><div class="avatar-img"><img src="/images/4stars.png" onerror="this.onerror=null;this.src='/img/friend_404.gif'" alt="avatar"/></div><div class="author-info-name">funtim41@gmail.com</div><div class="author-info-description">实践-认识-再实践-再认识</div><div class="site-data"><a href="/archives/"><div class="headline">文章</div><div class="length-num">51</div></a><a href="/tags/"><div class="headline">标签</div><div class="length-num">2</div></a><a href="/categories/"><div class="headline">分类</div><div class="length-num">3</div></a></div><a id="card-info-btn" target="_blank" rel="noopener" href="https://github.com/FunTim41"><i class="fab fa-github"></i><span>Follow Me</span></a><div class="card-info-social-icons"><a class="social-icon" href="https://github.com/FunTim41" target="_blank" title="Github"><i class="fab fa-github" style="color: #FFFFFF;"></i></a></div></div><div class="card-widget card-announcement"><div class="item-headline"><i class="fas fa-bullhorn fa-shake"></i><span>公告</span></div><div class="announcement_content">This is my Blog</div></div><div class="sticky_layout"><div class="card-widget" id="card-toc"><div class="item-headline"><i class="fas fa-stream"></i><span>目录</span><span class="toc-percentage"></span></div><div class="toc-content"><ol class="toc"><li class="toc-item toc-level-1"><a class="toc-link" href="#%E8%8D%89%E5%9B%BE"><span class="toc-number">1.</span> <span class="toc-text">草图</span></a><ol class="toc-child"><li class="toc-item toc-level-2"><a class="toc-link" href="#2D-Sketch%E7%B1%BB"><span class="toc-number">1.1.</span> <span class="toc-text">2D Sketch类</span></a></li><li class="toc-item toc-level-2"><a class="toc-link" href="#3D-Sketch"><span class="toc-number">1.2.</span> <span class="toc-text">3D Sketch</span></a></li><li class="toc-item toc-level-2"><a class="toc-link" href="#Blend"><span class="toc-number">1.3.</span> <span class="toc-text">Blend</span></a></li><li class="toc-item toc-level-2"><a class="toc-link" href="#Sweep"><span class="toc-number">1.4.</span> <span class="toc-text">Sweep</span></a></li><li class="toc-item toc-level-2"><a class="toc-link" href="#%E6%A8%A1%E5%9E%8B%E7%BA%BF"><span class="toc-number">1.5.</span> <span class="toc-text">模型线</span></a></li><li class="toc-item toc-level-2"><a class="toc-link" href="#%E6%B3%A8%EF%BC%9A%E7%BF%BB%E8%AF%91%E8%87%AARevit-API-Developers-Guide"><span class="toc-number">1.6.</span> <span class="toc-text">注：翻译自Revit API Developers Guide</span></a></li></ol></li></ol></div></div><div class="card-widget card-recent-post"><div class="item-headline"><i class="fas fa-history"></i><span>最新文章</span></div><div class="aside-list"><div class="aside-list-item no-cover"><div class="content"><a class="title" href="/2025/01/08/%E5%8D%9A%E5%AE%A2%E9%85%8D%E7%BD%AE/Hexo+Butterfly%E4%BB%A3%E7%A0%81%E5%9D%97%E6%B0%B4%E5%B9%B3%E6%BB%9A%E5%8A%A8%E6%9D%A1/" title="Hexo+Butterfly代码块水平滚动条">Hexo+Butterfly代码块水平滚动条</a><time datetime="2025-01-08T03:43:27.151Z" title="更新于 2025-01-08 11:43:27">2025-01-08</time></div></div><div class="aside-list-item no-cover"><div class="content"><a class="title" href="/2024/11/18/RevitApi%E5%90%88%E9%9B%86/Autodesk.RevitAddIns%20Namespace/" title="Autodesk.RevitAddIns Namespace">Autodesk.RevitAddIns Namespace</a><time datetime="2025-01-05T09:13:27.547Z" title="更新于 2025-01-05 17:13:27">2025-01-05</time></div></div><div class="aside-list-item no-cover"><div class="content"><a class="title" href="/2024/11/18/RevitApi%E5%90%88%E9%9B%86/Autodesk.Revit.DB%20CurveArray/" title="Autodesk.Revit.DB CurveArray">Autodesk.Revit.DB CurveArray</a><time datetime="2025-01-04T02:50:53.238Z" title="更新于 2025-01-04 10:50:53">2025-01-04</time></div></div><div class="aside-list-item no-cover"><div class="content"><a class="title" href="/2024/12/10/RevitApi%E5%90%88%E9%9B%86/Autodesk.Revit.DB%20Opening/" title="Autodesk.Revit.DB Opening">Autodesk.Revit.DB Opening</a><time datetime="2025-01-04T02:47:58.908Z" title="更新于 2025-01-04 10:47:58">2025-01-04</time></div></div><div class="aside-list-item no-cover"><div class="content"><a class="title" href="/2024/12/10/RevitApi%E5%90%88%E9%9B%86/Autodesk.Revit.DB%20ReferenceIntersector/" title="Autodesk.Revit.DB ReferenceIntersector">Autodesk.Revit.DB ReferenceIntersector</a><time datetime="2025-01-04T02:47:17.298Z" title="更新于 2025-01-04 10:47:17">2025-01-04</time></div></div></div></div></div></div></main><footer id="footer" style="background-image: url(/images/topback.jpg);"><div id="footer-wrap"><div class="copyright">&copy;2024 - 2025 By funtim41@gmail.com</div><div class="framework-info"><span>框架 </span><a target="_blank" rel="noopener" href="https://hexo.io">Hexo</a><span class="footer-separator">|</span><span>主题 </span><a target="_blank" rel="noopener" href="https://github.com/jerryc127/hexo-theme-butterfly">Butterfly</a></div><div class="footer_custom_text">学而不思则罔，思而不学则殆。</div></div></footer></div><div id="rightside"><div id="rightside-config-hide"><button id="readmode" type="button" title="阅读模式"><i class="fas fa-book-open"></i></button><button id="darkmode" type="button" title="日间和夜间模式切换"><i class="fas fa-adjust"></i></button><button id="hide-aside-btn" type="button" title="单栏和双栏切换"><i class="fas fa-arrows-alt-h"></i></button></div><div id="rightside-config-show"><button id="rightside-config" type="button" title="设置"><i class="fas fa-cog fa-spin"></i></button><button class="close" id="mobile-toc-button" type="button" title="目录"><i class="fas fa-list-ul"></i></button><a id="to_comment" href="#post-comment" title="前往评论"><i class="fas fa-comments"></i></a><button id="go-up" type="button" title="回到顶部"><span class="scroll-percent"></span><i class="fas fa-arrow-up"></i></button></div></div><div><script src="/js/utils.js"></script><script src="/js/main.js"></script><script src="https://cdn.jsdelivr.net/npm/node-snackbar/dist/snackbar.min.js"></script><script>(() => {
  const panguFn = () => {
    if (typeof pangu === 'object') pangu.autoSpacingPage()
    else {
      btf.getScript('https://cdn.jsdelivr.net/npm/pangu/dist/browser/pangu.min.js')
        .then(() => {
          pangu.autoSpacingPage()
        })
    }
  }

  const panguInit = () => {
    if (false){
      GLOBAL_CONFIG_SITE.isPost && panguFn()
    } else {
      panguFn()
    }
  }

  btf.addGlobalFn('pjaxComplete', panguInit, 'pangu')
  document.addEventListener('DOMContentLoaded', panguInit)
})()</script><div class="js-pjax"><script>(() => {
  const isShuoshuo = GLOBAL_CONFIG_SITE.isShuoshuo
  const option = null

  const getGiscusTheme = theme => theme === 'dark' ? 'dark' : 'light'

  const createScriptElement = config => {
    const ele = document.createElement('script')
    Object.entries(config).forEach(([key, value]) => {
      ele.setAttribute(key, value)
    })
    return ele
  }

  const loadGiscus = (el = document, key) => {
    const mappingConfig = isShuoshuo
      ? { 'data-mapping': 'specific', 'data-term': key }
      : { 'data-mapping': (option && option['data-mapping']) || 'pathname' }

    const giscusConfig = {
      src: 'https://giscus.app/client.js',
      'data-repo': 'FunTim41/funtim41.github.io',
      'data-repo-id': 'R_kgDONjG8ww',
      'data-category-id': 'DIC_kwDONjG8w84Cllg2',
      'data-theme': getGiscusTheme(document.documentElement.getAttribute('data-theme')),
      'data-reactions-enabled': '1',
      crossorigin: 'anonymous',
      async: true,
      ...option,
      ...mappingConfig
    }

    const scriptElement = createScriptElement(giscusConfig)

    el.querySelector('#giscus-wrap').appendChild(scriptElement)

    if (isShuoshuo) {
      window.shuoshuoComment.destroyGiscus = () => {
        if (el.children.length) {
          el.innerHTML = ''
          el.classList.add('no-comment')
        }
      }
    }
  }

  const changeGiscusTheme = theme => {
    const iframe = document.querySelector('#giscus-wrap iframe')
    if (iframe) {
      const message = {
        giscus: {
          setConfig: {
            theme: getGiscusTheme(theme)
          }
        }
      }
      iframe.contentWindow.postMessage(message, 'https://giscus.app')
    }
  }

  btf.addGlobalFn('themeChange', changeGiscusTheme, 'giscus')

  if (isShuoshuo) {
    'Giscus' === 'Giscus'
      ? window.shuoshuoComment = { loadComment: loadGiscus }
      : window.loadOtherComment = loadGiscus
    return
  }

  if ('Giscus' === 'Giscus' || !false) {
    if (false) btf.loadComment(document.getElementById('giscus-wrap'), loadGiscus)
    else loadGiscus()
  } else {
    window.loadOtherComment = loadGiscus
  }
})()</script></div><script defer="defer" id="fluttering_ribbon" mobile="false" src="https://cdn.jsdelivr.net/npm/butterfly-extsrc/dist/canvas-fluttering-ribbon.min.js"></script><script async data-pjax src="//busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js"></script><div id="local-search"><div class="search-dialog"><nav class="search-nav"><span class="search-dialog-title">搜索</span><span id="loading-status"></span><button class="search-close-button"><i class="fas fa-times"></i></button></nav><div class="text-center" id="loading-database"><i class="fas fa-spinner fa-pulse"></i><span>  数据加载中</span></div><div class="search-wrap"><div id="local-search-input"><div class="local-search-box"><input class="local-search-box--input" placeholder="搜索文章" type="text"/></div></div><hr/><div id="local-search-results"></div><div id="local-search-stats-wrap"></div></div></div><div id="search-mask"></div><script src="/js/search/local-search.js"></script></div></div></body></html>