<!DOCTYPE html><html lang="zh-CN" data-theme="light"><head><meta charset="UTF-8"><meta http-equiv="X-UA-Compatible" content="IE=edge"><meta name="viewport" content="width=device-width, initial-scale=1.0,viewport-fit=cover"><title>21楼梯和扶手 | funtim的博客</title><meta name="author" content="funtim41@gmail.com"><meta name="copyright" content="funtim41@gmail.com"><meta name="format-detection" content="telephone=no"><meta name="theme-color" content="#ffffff"><meta name="description" content="楼梯和扶手Autodesk.Revit.DB.Architecture命名空间中的Revit API中的类允许访问楼梯和相关构件（如平台和梯段）。可以使用Revit API创建或修改楼梯。Stairs类表示“由构件”创建的楼梯。不能在API中将通过草图创建的楼梯图元作为楼梯对象进行访问。静态方法Stairs.IsByComponent（）可用于确定ElementId是否表示由构件创建的楼梯。  本">
<meta property="og:type" content="article">
<meta property="og:title" content="21楼梯和扶手">
<meta property="og:url" content="https://funtim41.github.io/2024/12/23/Revit%E4%BA%8C%E5%BC%80%E6%8C%87%E5%8D%97/21%E6%A5%BC%E6%A2%AF%E5%92%8C%E6%89%B6%E6%89%8B/">
<meta property="og:site_name" content="funtim的博客">
<meta property="og:description" content="楼梯和扶手Autodesk.Revit.DB.Architecture命名空间中的Revit API中的类允许访问楼梯和相关构件（如平台和梯段）。可以使用Revit API创建或修改楼梯。Stairs类表示“由构件”创建的楼梯。不能在API中将通过草图创建的楼梯图元作为楼梯对象进行访问。静态方法Stairs.IsByComponent（）可用于确定ElementId是否表示由构件创建的楼梯。  本">
<meta property="og:locale" content="zh_CN">
<meta property="og:image" content="https://funtim41.github.io/images/4stars.png">
<meta property="article:published_time" content="2024-12-23T15:03:31.000Z">
<meta property="article:modified_time" content="2025-01-13T14:21:06.230Z">
<meta property="article:author" content="funtim41@gmail.com">
<meta property="article:tag" content="Revit">
<meta name="twitter:card" content="summary">
<meta name="twitter:image" content="https://funtim41.github.io/images/4stars.png"><link rel="shortcut icon" href="/images/OIP.jfif"><link rel="canonical" href="https://funtim41.github.io/2024/12/23/Revit%E4%BA%8C%E5%BC%80%E6%8C%87%E5%8D%97/21%E6%A5%BC%E6%A2%AF%E5%92%8C%E6%89%B6%E6%89%8B/"><link rel="preconnect" href="//cdn.jsdelivr.net"/><link rel="stylesheet" href="/css/index.css"><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free/css/all.min.css"><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/node-snackbar/dist/snackbar.min.css" media="print" onload="this.media='all'"><script>
    (() => {
      
    const saveToLocal = {
      set: (key, value, ttl) => {
        if (!ttl) return
        const expiry = Date.now() + ttl * 86400000
        localStorage.setItem(key, JSON.stringify({ value, expiry }))
      },
      get: key => {
        const itemStr = localStorage.getItem(key)
        if (!itemStr) return undefined
        const { value, expiry } = JSON.parse(itemStr)
        if (Date.now() > expiry) {
          localStorage.removeItem(key)
          return undefined
        }
        return value
      }
    }

    window.btf = {
      saveToLocal,
      getScript: (url, attr = {}) => new Promise((resolve, reject) => {
        const script = document.createElement('script')
        script.src = url
        script.async = true
        Object.entries(attr).forEach(([key, val]) => script.setAttribute(key, val))
        script.onload = script.onreadystatechange = () => {
          if (!script.readyState || /loaded|complete/.test(script.readyState)) resolve()
        }
        script.onerror = reject
        document.head.appendChild(script)
      }),
      getCSS: (url, id) => new Promise((resolve, reject) => {
        const link = document.createElement('link')
        link.rel = 'stylesheet'
        link.href = url
        if (id) link.id = id
        link.onload = link.onreadystatechange = () => {
          if (!link.readyState || /loaded|complete/.test(link.readyState)) resolve()
        }
        link.onerror = reject
        document.head.appendChild(link)
      }),
      addGlobalFn: (key, fn, name = false, parent = window) => {
        if (!false && key.startsWith('pjax')) return
        const globalFn = parent.globalFn || {}
        globalFn[key] = globalFn[key] || {}
        globalFn[key][name || Object.keys(globalFn[key]).length] = fn
        parent.globalFn = globalFn
      }
    }
  
      
      const activateDarkMode = () => {
        document.documentElement.setAttribute('data-theme', 'dark')
        if (document.querySelector('meta[name="theme-color"]') !== null) {
          document.querySelector('meta[name="theme-color"]').setAttribute('content', '#0d0d0d')
        }
      }
      const activateLightMode = () => {
        document.documentElement.setAttribute('data-theme', 'light')
        if (document.querySelector('meta[name="theme-color"]') !== null) {
          document.querySelector('meta[name="theme-color"]').setAttribute('content', '#ffffff')
        }
      }

      btf.activateDarkMode = activateDarkMode
      btf.activateLightMode = activateLightMode

      const theme = saveToLocal.get('theme')
    
          theme === 'dark' ? activateDarkMode() : theme === 'light' ? activateLightMode() : null
        
      
      const asideStatus = saveToLocal.get('aside-status')
      if (asideStatus !== undefined) {
        document.documentElement.classList.toggle('hide-aside', asideStatus === 'hide')
      }
    
      
    const detectApple = () => {
      if (/iPad|iPhone|iPod|Macintosh/.test(navigator.userAgent)) {
        document.documentElement.classList.add('apple')
      }
    }
    detectApple()
  
    })()
  </script><script>const GLOBAL_CONFIG = {
  root: '/',
  algolia: undefined,
  localSearch: {"path":"/search.xml","preload":false,"top_n_per_article":1,"unescape":false,"languages":{"hits_empty":"未找到符合您查询的内容：${query}","hits_stats":"共找到 ${hits} 篇文章"}},
  translate: undefined,
  highlight: {"plugin":"highlight.js","highlightCopy":true,"highlightLang":true,"highlightHeightLimit":false,"highlightFullpage":false,"highlightMacStyle":false},
  copy: {
    success: '复制成功',
    error: '复制失败',
    noSupport: '浏览器不支持'
  },
  relativeDate: {
    homepage: false,
    post: false
  },
  runtime: '',
  dateSuffix: {
    just: '刚刚',
    min: '分钟前',
    hour: '小时前',
    day: '天前',
    month: '个月前'
  },
  copyright: {"limitCount":150,"languages":{"author":"作者: funtim41@gmail.com","link":"链接: ","source":"来源: funtim的博客","info":"著作权归作者所有。商业转载请联系作者获得授权，非商业转载请注明出处。"}},
  lightbox: 'null',
  Snackbar: {"chs_to_cht":"已切换为繁体中文","cht_to_chs":"已切换为简体中文","day_to_night":"已切换为深色模式","night_to_day":"已切换为浅色模式","bgLight":"#49b1f5","bgDark":"#1f1f1f","position":"bottom-left"},
  infinitegrid: {
    js: 'https://cdn.jsdelivr.net/npm/@egjs/infinitegrid/dist/infinitegrid.min.js',
    buttonText: '加载更多'
  },
  isPhotoFigcaption: false,
  islazyload: false,
  isAnchor: true,
  percent: {
    toc: true,
    rightside: true,
  },
  autoDarkmode: false
}</script><script id="config-diff">var GLOBAL_CONFIG_SITE = {
  title: '21楼梯和扶手',
  isPost: true,
  isHome: false,
  isHighlightShrink: false,
  isToc: true,
  isShuoshuo: false
}</script><link rel="stylesheet" href="/css/bar.css"><meta name="generator" content="Hexo 7.3.0"></head><body><div id="web_bg" style="background: Color(#995a82);"></div><div id="sidebar"><div id="menu-mask"></div><div id="sidebar-menus"><div class="avatar-img text-center"><img src="/images/4stars.png" onerror="onerror=null;src='/img/friend_404.gif'" alt="avatar"/></div><div class="site-data text-center"><a href="/archives/"><div class="headline">文章</div><div class="length-num">60</div></a><a href="/tags/"><div class="headline">标签</div><div class="length-num">5</div></a><a href="/categories/"><div class="headline">分类</div><div class="length-num">7</div></a></div><div class="menus_items"><div class="menus_item"><a class="site-page" href="/"><i class="fa-fw fas fa-home"></i><span> Home</span></a></div><div class="menus_item"><a class="site-page" href="/archives/"><i class="fa-fw fas fa-archive"></i><span> Timeline</span></a></div><div class="menus_item"><a class="site-page" href="/tags/"><i class="fa-fw fas fa-tags"></i><span> Tags</span></a></div><div class="menus_item"><a class="site-page" href="/categories/"><i class="fa-fw fas fa-folder-open"></i><span> Categories</span></a></div><div class="menus_item"><a class="site-page" href="/Links/"><i class="fa-fw fas fa-link"></i><span> Links</span></a></div><div class="menus_item"><a class="site-page" href="/about/"><i class="fa-fw fas fa-heart"></i><span> About</span></a></div></div></div></div><div class="post" id="body-wrap"><header class="post-bg fixed" id="page-header" style="background-image: url(/images/topback.jpg);"><nav id="nav"><span id="blog-info"><a class="nav-site-title" href="/"><img class="site-icon" src="/images/OIP.jfif" alt="Logo"><span class="site-name">funtim的博客</span></a><a class="nav-page-title" href="/"><span class="site-name">21楼梯和扶手</span></a></span><div id="menus"><div id="search-button"><span class="site-page social-icon search"><i class="fas fa-search fa-fw"></i><span> 搜索</span></span></div><div class="menus_items"><div class="menus_item"><a class="site-page" href="/"><i class="fa-fw fas fa-home"></i><span> Home</span></a></div><div class="menus_item"><a class="site-page" href="/archives/"><i class="fa-fw fas fa-archive"></i><span> Timeline</span></a></div><div class="menus_item"><a class="site-page" href="/tags/"><i class="fa-fw fas fa-tags"></i><span> Tags</span></a></div><div class="menus_item"><a class="site-page" href="/categories/"><i class="fa-fw fas fa-folder-open"></i><span> Categories</span></a></div><div class="menus_item"><a class="site-page" href="/Links/"><i class="fa-fw fas fa-link"></i><span> Links</span></a></div><div class="menus_item"><a class="site-page" href="/about/"><i class="fa-fw fas fa-heart"></i><span> About</span></a></div></div><div id="toggle-menu"><span class="site-page"><i class="fas fa-bars fa-fw"></i></span></div></div></nav><div id="post-info"><h1 class="post-title">21楼梯和扶手</h1><div id="post-meta"><div class="meta-firstline"><span class="post-meta-date"><i class="far fa-calendar-alt fa-fw post-meta-icon"></i><span class="post-meta-label">发表于</span><time class="post-meta-date-created" datetime="2024-12-23T15:03:31.000Z" title="发表于 2024-12-23 23:03:31">2024-12-23</time><span class="post-meta-separator">|</span><i class="fas fa-history fa-fw post-meta-icon"></i><span class="post-meta-label">更新于</span><time class="post-meta-date-updated" datetime="2025-01-13T14:21:06.230Z" title="更新于 2025-01-13 22:21:06">2025-01-13</time></span><span class="post-meta-categories"><span class="post-meta-separator">|</span><i class="fas fa-inbox fa-fw post-meta-icon"></i><a class="post-meta-categories" href="/categories/Revit%E4%BA%8C%E6%AC%A1%E5%BC%80%E5%8F%91%E4%BA%BA%E5%91%98%E6%8C%87%E5%8D%97/">Revit二次开发人员指南</a></span></div><div class="meta-secondline"><span class="post-meta-separator">|</span><span class="post-meta-pv-cv" id="" data-flag-title=""><i class="far fa-eye fa-fw post-meta-icon"></i><span class="post-meta-label">浏览量:</span><span id="busuanzi_value_page_pv"><i class="fa-solid fa-spinner fa-spin"></i></span></span></div></div></div></header><main class="layout" id="content-inner"><div id="post"><article class="container post-content" id="article-container"><h1 id="楼梯和扶手"><a href="#楼梯和扶手" class="headerlink" title="楼梯和扶手"></a><a target="_blank" rel="noopener" href="https://help.autodesk.com/view/RVT/2018/ENU/?guid=Revit_API_Revit_API_Developers_Guide_Revit_Geometric_Elements_Stairs_and_Railings_html">楼梯和扶手</a></h1><p>Autodesk.Revit.DB.Architecture命名空间中的Revit API中的类允许访问楼梯和相关构件（如平台和梯段）。可以使用Revit API创建或修改楼梯。Stairs类表示“由构件”创建的楼梯。不能在API中将通过草图创建的楼梯图元作为楼梯对象进行访问。静态方法Stairs.IsByComponent（）可用于确定ElementId是否表示由构件创建的楼梯。</p>
<p> 本节中的页面</p>
<ul>
<li>创建和编辑楼梯</li>
<li>扶手</li>
<li>楼梯注释</li>
<li>楼梯构件</li>
</ul>
<h2 id="创建和编辑楼梯"><a href="#创建和编辑楼梯" class="headerlink" title="创建和编辑楼梯"></a>创建和编辑楼梯</h2><p><strong>StairsEditScope</strong></p>
<p>与Revit文档中其他类型的元素一样，编辑楼梯和楼梯构件需要事务处理。但是，若要创建新构件（如梯段和平台）或创建新楼梯本身，则必须使用Autodesk.Revit.DB.StairsEditScope对象，该对象支持楼梯编辑任务。</p>
<p>StairsEditScope的作用类似于TransactionGroup。启动StairsEditScope后，可以启动事务并编辑楼梯。在StairsEditScope中创建的单个事务不会出现在撤消菜单中。在编辑模式下提交的所有事务将被合并为一个事务，该事务的名称由传递给 StairsEditScope 构造函数的参数指定。</p>
<p>StairsEditScope有两个Start方法。获取现有Stairs对象的ElementId，并为其启动楼梯编辑会话。第二个Start方法采用底部标高和顶部标高的ElementId，并在指定标高中创建具有默认楼梯类型的新空楼梯元素，然后为新楼梯启动楼梯编辑模式。</p>
<p>将梯段和平台添加到楼梯并完成编辑后，请调用 StairsEditScope.Commit() 方法结束楼梯编辑模式。</p>
<p><strong>添加梯段</strong></p>
<ul>
<li>StairsRun类有三个用于为Stairs对象创建新梯段的静态方法：<ul>
<li><strong>CreateSketchedRun</strong> - 通过提供一组边界曲线和踢面曲线来创建草图梯段。</li>
<li><strong>CreateStraightRun</strong> - 创建直线梯段。</li>
<li><strong>CreateSpiralRun</strong> - 通过提供圆心、起始角度和夹角来创建螺旋梯段。</li>
</ul>
</li>
</ul>
<p><strong>添加平台</strong></p>
<p>可以在两个梯段之间添加自动平台或草图平台。静态方法StairsLanding. Canadian AutomaticLanding（）将检查两个楼梯梯段是否满足创建自动平台的限制。静态StairsLanding. random AutomaticLanding（）方法将返回在两个楼梯梯段之间创建的所有平台的Id。</p>
<p>静态StairsLanding. RightSketchedLanding方法通过提供平台的闭合边界曲线，在两个梯段之间创建自定义平台。基本高程的双精度值是CreateSketchedLanding方法的输入参数之一。标高有以下限制：</p>
<ul>
<li>底部高程相对于楼梯的底部高程。</li>
<li>底部高程将自动舍入为踢面高度的倍数。</li>
<li>基础标高应等于或大于踢面高度的一半。</li>
</ul>
<p><strong>例子</strong></p>
<p>下面的示例将创建一个新的Stairs对象、两个梯段（一个为草图梯段，一个为直线梯段）以及它们之间的平台。</p>
<p>代码区域：创建楼梯、楼梯平台和平台</p>
<figure class="highlight c#"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br><span class="line">23</span><br><span class="line">24</span><br><span class="line">25</span><br><span class="line">26</span><br><span class="line">27</span><br><span class="line">28</span><br><span class="line">29</span><br><span class="line">30</span><br><span class="line">31</span><br><span class="line">32</span><br><span class="line">33</span><br><span class="line">34</span><br><span class="line">35</span><br><span class="line">36</span><br><span class="line">37</span><br><span class="line">38</span><br><span class="line">39</span><br><span class="line">40</span><br><span class="line">41</span><br><span class="line">42</span><br><span class="line">43</span><br><span class="line">44</span><br><span class="line">45</span><br><span class="line">46</span><br><span class="line">47</span><br><span class="line">48</span><br><span class="line">49</span><br><span class="line">50</span><br><span class="line">51</span><br><span class="line">52</span><br><span class="line">53</span><br><span class="line">54</span><br><span class="line">55</span><br><span class="line">56</span><br><span class="line">57</span><br><span class="line">58</span><br><span class="line">59</span><br><span class="line">60</span><br><span class="line">61</span><br><span class="line">62</span><br><span class="line">63</span><br><span class="line">64</span><br><span class="line">65</span><br><span class="line">66</span><br><span class="line">67</span><br><span class="line">68</span><br><span class="line">69</span><br><span class="line">70</span><br><span class="line">71</span><br><span class="line">72</span><br><span class="line">73</span><br><span class="line">74</span><br><span class="line">75</span><br><span class="line">76</span><br><span class="line">77</span><br><span class="line">78</span><br><span class="line">79</span><br><span class="line">80</span><br><span class="line">81</span><br><span class="line">82</span><br></pre></td><td class="code"><pre><span class="line"><span class="comment">// FailurePreprocessor class required for StairsEditScope</span></span><br><span class="line"><span class="keyword">class</span> <span class="title">StairsFailurePreprocessor</span> : <span class="title">IFailuresPreprocessor</span></span><br><span class="line">&#123;</span><br><span class="line">    <span class="function"><span class="keyword">public</span> FailureProcessingResult <span class="title">PreprocessFailures</span>(<span class="params">FailuresAccessor failuresAccessor</span>)</span></span><br><span class="line">    &#123;</span><br><span class="line">        <span class="comment">// Use default failure processing</span></span><br><span class="line">        <span class="keyword">return</span> FailureProcessingResult.Continue; </span><br><span class="line">    &#125;</span><br><span class="line">&#125;</span><br><span class="line"></span><br><span class="line"><span class="function"><span class="keyword">private</span> ElementId <span class="title">CreateStairs</span>(<span class="params">Document document, Level levelBottom, Level levelTop</span>)</span></span><br><span class="line">&#123;</span><br><span class="line">    ElementId newStairsId = <span class="literal">null</span>;</span><br><span class="line"></span><br><span class="line">    <span class="keyword">using</span> (StairsEditScope newStairsScope = <span class="keyword">new</span> StairsEditScope(document, <span class="string">&quot;New Stairs&quot;</span>))</span><br><span class="line">    &#123;</span><br><span class="line">        newStairsId = newStairsScope.Start(levelBottom.Id, levelTop.Id);</span><br><span class="line"></span><br><span class="line">        <span class="keyword">using</span> (Transaction stairsTrans = <span class="keyword">new</span> Transaction(document, <span class="string">&quot;Add Runs and Landings to Stairs&quot;</span>))</span><br><span class="line">        &#123;</span><br><span class="line">            stairsTrans.Start();</span><br><span class="line"></span><br><span class="line">            <span class="comment">// Create a sketched run for the stairs</span></span><br><span class="line">            IList bdryCurves = <span class="keyword">new</span> List();</span><br><span class="line">            IList riserCurves = <span class="keyword">new</span> List();</span><br><span class="line">            IList pathCurves = <span class="keyword">new</span> List();</span><br><span class="line">            XYZ pnt1 = <span class="keyword">new</span> XYZ(<span class="number">0</span>, <span class="number">0</span>, <span class="number">0</span>);</span><br><span class="line">            XYZ pnt2 = <span class="keyword">new</span> XYZ(<span class="number">15</span>, <span class="number">0</span>, <span class="number">0</span>);</span><br><span class="line">            XYZ pnt3 = <span class="keyword">new</span> XYZ(<span class="number">0</span>, <span class="number">10</span>, <span class="number">0</span>);</span><br><span class="line">            XYZ pnt4 = <span class="keyword">new</span> XYZ(<span class="number">15</span>, <span class="number">10</span>, <span class="number">0</span>);</span><br><span class="line"></span><br><span class="line">            <span class="comment">// boundaries</span></span><br><span class="line">            bdryCurves.Add(Line.CreateBound(pnt1, pnt2));</span><br><span class="line">            bdryCurves.Add(Line.CreateBound(pnt3, pnt4));</span><br><span class="line"></span><br><span class="line">            <span class="comment">// riser curves</span></span><br><span class="line">            <span class="keyword">const</span> <span class="built_in">int</span> riserNum = <span class="number">20</span>;</span><br><span class="line">            <span class="keyword">for</span> (<span class="built_in">int</span> ii = <span class="number">0</span>; ii &lt;= riserNum; ii++)</span><br><span class="line">            &#123;</span><br><span class="line">                XYZ end0 = (pnt1 + pnt2)  ii / (<span class="built_in">double</span>)riserNum;</span><br><span class="line">                XYZ end1 = (pnt3 + pnt4)  ii / (<span class="built_in">double</span>)riserNum;</span><br><span class="line">                XYZ end2 = <span class="keyword">new</span> XYZ(end1.X, <span class="number">10</span>, <span class="number">0</span>);</span><br><span class="line">                riserCurves.Add(Line.CreateBound(end0, end2));</span><br><span class="line">            &#125;</span><br><span class="line"></span><br><span class="line">            <span class="comment">//stairs path curves</span></span><br><span class="line">            XYZ pathEnd0 = (pnt1 + pnt3) / <span class="number">2.0</span>;</span><br><span class="line">            XYZ pathEnd1 = (pnt2 + pnt4) / <span class="number">2.0</span>;</span><br><span class="line">            pathCurves.Add(Line.CreateBound(pathEnd0, pathEnd1));</span><br><span class="line"></span><br><span class="line">            StairsRun newRun1 = StairsRun.CreateSketchedRun(document, newStairsId, levelBottom.Elevation, bdryCurves, riserCurves, pathCurves);</span><br><span class="line"></span><br><span class="line">            <span class="comment">// Add a straight run</span></span><br><span class="line">            Line locationLine = Line.CreateBound(<span class="keyword">new</span> XYZ(<span class="number">20</span>, <span class="number">-5</span>, newRun1.TopElevation), <span class="keyword">new</span> XYZ(<span class="number">35</span>, <span class="number">-5</span>, newRun1.TopElevation));</span><br><span class="line">            StairsRun newRun2 = StairsRun.CreateStraightRun(document, newStairsId, locationLine, StairsRunJustification.Center);</span><br><span class="line">            newRun2.ActualRunWidth = <span class="number">10</span>;</span><br><span class="line"></span><br><span class="line">            <span class="comment">// Add a landing between the runs</span></span><br><span class="line">            CurveLoop landingLoop = <span class="keyword">new</span> CurveLoop();</span><br><span class="line">            XYZ p1 = <span class="keyword">new</span> XYZ(<span class="number">15</span>, <span class="number">10</span>, <span class="number">0</span>); </span><br><span class="line">            XYZ p2 = <span class="keyword">new</span> XYZ(<span class="number">20</span>, <span class="number">10</span>, <span class="number">0</span>);</span><br><span class="line">            XYZ p3 = <span class="keyword">new</span> XYZ(<span class="number">20</span>, <span class="number">-10</span>, <span class="number">0</span>);</span><br><span class="line">            XYZ p4 = <span class="keyword">new</span> XYZ(<span class="number">15</span>, <span class="number">-10</span>, <span class="number">0</span>);</span><br><span class="line">            Line curve_1 = Line.CreateBound(p1, p2);</span><br><span class="line">            Line curve_2 = Line.CreateBound(p2, p3);</span><br><span class="line">            Line curve_3 = Line.CreateBound(p3, p4);</span><br><span class="line">            Line curve_4 = Line.CreateBound(p4, p1);</span><br><span class="line"></span><br><span class="line">            landingLoop.Append(curve_1);</span><br><span class="line">            landingLoop.Append(curve_2);</span><br><span class="line">            landingLoop.Append(curve_3);</span><br><span class="line">            landingLoop.Append(curve_4);</span><br><span class="line">            StairsLanding newLanding = StairsLanding.CreateSketchedLanding(document, newStairsId, landingLoop, newRun1.TopElevation);</span><br><span class="line"></span><br><span class="line">            stairsTrans.Commit();</span><br><span class="line">        &#125;</span><br><span class="line">        <span class="comment">// A failure preprocessor is to handle possible failures during the edit mode commitment process.</span></span><br><span class="line">        newStairsScope.Commit(<span class="keyword">new</span> StairsFailurePreprocessor());</span><br><span class="line">    &#125;</span><br><span class="line"></span><br><span class="line">    <span class="keyword">return</span> newStairsId;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<p>从上面的例子产生的楼梯：<img src="https://help.autodesk.com/cloudhelp/2018/ENU/Revit-API/images/stairs.jpg" alt="img"></p>
<p><strong>多层楼梯</strong> </p>
<p>MultistoryStairs类允许楼梯跨越多个标高。多层楼梯元素可以包含多个楼梯，这些楼梯的范围由底部标高和顶部标高控制。 此元素将包含一个或多个Stairs元素。楼梯元素是： 复制到由共享相同标高高度的相同楼梯实例组覆盖的每个标高的参考实例， 或未连接到具有相同标高高度的组的单个Stairs实例。 默认情况下，向多层楼梯添加新标高时，新楼梯将添加到组中。对于不同标高的重复楼梯组，实例可以作为Stairs元素的子元素找到。通过修改关联的Stairs实例，可以一起编辑连接组中的楼梯。对于需要特殊设计的特定楼层，可以使用“取消锁定”方法将楼梯从组中分离出来-对取消锁定的楼梯所做的更改不会影响图元中的其他任何实例。稍后可以使用“锁定”方法将楼梯添加回组中，但是对楼梯所做的任何更改都将丢失，因为楼梯的属性将被组规范覆盖。</p>
<p>代码区域：创建多层楼梯</p>
<figure class="highlight c#"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br></pre></td><td class="code"><pre><span class="line"><span class="comment">// create new MultistoryStairs </span></span><br><span class="line">MultistoryStairs multistoryStairs = MultistoryStairs.Create(stairs);</span><br><span class="line"></span><br><span class="line"><span class="comment">// get all levels that can be connected to this multistoryStairs</span></span><br><span class="line">IEnumerable levelIds = <span class="keyword">new</span> FilteredElementCollector(doc).OfClass(<span class="keyword">typeof</span>(Level)).Cast().Where(q =&gt; multistoryStairs.CanConnectLevel(q.Id))</span><br><span class="line">.Select(q =&gt; q.Id);</span><br><span class="line"></span><br><span class="line"><span class="comment">// Connect the levels to the multistoryStairs</span></span><br><span class="line"><span class="comment">// The input to ConnectLevels is a HashSet or SortedSet, so a HashSet is created from the IEnumerable returned by FilteredElementCollector</span></span><br><span class="line">multistoryStairs.ConnectLevels(<span class="keyword">new</span> HashSet(levelIds));</span><br></pre></td></tr></table></figure>

<p>当使用StairsEditScope.Start（ElementId，ElementId）方法创建新楼梯时，它们具有与其关联的默认扶手。但是，Railing.Create（）方法可用于在不带扶手的楼梯的楼梯元素的所有边上创建具有指定扶手类型的新扶手。与需要使用StairsEditScope创建梯段和平台不同，扶手创建不能在打开的楼梯编辑任务中执行。 由于无法为已具有关联扶手的楼梯创建扶手，因此下面的示例在创建新扶手之前删除与楼梯对象关联的现有扶手。</p>
<p>代码区域：创建扶手</p>
<figure class="highlight c#"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="keyword">private</span> <span class="keyword">void</span> <span class="title">CreateRailing</span>(<span class="params">Document document, Stairs stairs</span>)</span></span><br><span class="line">&#123;</span><br><span class="line">    <span class="keyword">using</span> (Transaction trans = <span class="keyword">new</span> Transaction(document, <span class="string">&quot;Create Railings&quot;</span>))</span><br><span class="line">    &#123;</span><br><span class="line">        trans.Start();</span><br><span class="line"></span><br><span class="line">        <span class="comment">// Delete existing railings</span></span><br><span class="line">        ICollection railingIds = stairs.GetAssociatedRailings();</span><br><span class="line">        <span class="keyword">foreach</span> (ElementId railingId <span class="keyword">in</span> railingIds)</span><br><span class="line">        &#123;</span><br><span class="line">            document.Delete(railingId);</span><br><span class="line">        &#125;</span><br><span class="line">        <span class="comment">// Find RailingType</span></span><br><span class="line">        FilteredElementCollector collector = <span class="keyword">new</span> FilteredElementCollector(document);</span><br><span class="line">        ICollection RailingTypeIds = collector.OfClass(<span class="keyword">typeof</span>(RailingType)).ToElementIds();</span><br><span class="line">        Railing.Create(document, stairs.Id, RailingTypeIds.First(), RailingPlacementPosition.Treads);</span><br><span class="line">        trans.Commit();</span><br><span class="line">    &#125;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<h2 id="扶手"><a href="#扶手" class="headerlink" title="扶手"></a>扶手</h2><p>Autodesk.Revit.DB.Architecture.Railing类表示Autodesk Revit项目中的扶手元素。尽管扶手与楼梯关联，但它们也可以与其他主体（如楼板）关联，也可以放置在空间中。扶手可以是连续的或不连续的。如果它们是不连续的，则仅提供有限的访问级别。</p>
<p>可以使用GetAssociatedRailings（）方法从Stairs类中检索与楼梯关联的扶手。只有少数属性和方法专用于栏杆扶手，例如返回顶部栏杆的ElementId的TopRail属性和指示栏杆扶手是否翻转的Flipped属性。Railing.Flip（）方法翻转扶手，而RemoveHost（）方法将删除扶手与其主体之间的关联。</p>
<p>下面的示例检索与Stairs对象关联的所有栏杆扶手，并翻转系统生成的默认栏杆扶手。</p>
<p>代码区域：使用扶手</p>
<figure class="highlight c#"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="keyword">private</span> <span class="keyword">void</span> <span class="title">FlipDefaultRailings</span>(<span class="params">Stairs stairs</span>)</span></span><br><span class="line">&#123;</span><br><span class="line">    ICollection&lt;ElementId&gt; railingIds = stairs.GetAssociatedRailings();</span><br><span class="line">    Transaction trans = <span class="keyword">new</span> Transaction(stairs.Document, <span class="string">&quot;Flip Railings&quot;</span>);</span><br><span class="line">    trans.Start();</span><br><span class="line">    <span class="keyword">foreach</span> (ElementId railingId <span class="keyword">in</span> railingIds)</span><br><span class="line">    &#123;</span><br><span class="line">        Railing railing = stairs.Document.GetElement(railingId) <span class="keyword">as</span> Railing;</span><br><span class="line">        <span class="keyword">if</span> (railing.IsDefault == <span class="literal">true</span>)</span><br><span class="line">        &#123;</span><br><span class="line">            railing.Flip();</span><br><span class="line">        &#125;</span><br><span class="line">    &#125;</span><br><span class="line">    trans.Commit();</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<p>Railing类具有Create方法，该方法可自动在楼梯元素的所有侧面上创建具有指定扶手类型的新扶手。扶手的创建将在“创建和编辑楼梯”部分中进行演示。</p>
<p>RailingType类表示生成扶手时使用的扶手类型。它包含许多关于扶手的属性，例如主扶手和次扶手以及顶部扶手的高度、横向偏移和类型。</p>
<p> 代码区域：RailingType</p>
<figure class="highlight c#"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="keyword">private</span> <span class="keyword">void</span> <span class="title">GetRailingType</span>(<span class="params">Stairs stairs</span>)</span></span><br><span class="line">&#123;</span><br><span class="line">    ICollection&lt;ElementId&gt; railingIds = stairs.GetAssociatedRailings();</span><br><span class="line">    <span class="keyword">foreach</span> (ElementId railingId <span class="keyword">in</span> railingIds)</span><br><span class="line">    &#123;</span><br><span class="line">        Railing railing = stairs.Document.GetElement(railingId) <span class="keyword">as</span> Railing;</span><br><span class="line">        RailingType railingType = stairs.Document.GetElement(railing.GetTypeId()) <span class="keyword">as</span> RailingType;</span><br><span class="line"></span><br><span class="line">        <span class="comment">// Format railing type info for display</span></span><br><span class="line">        <span class="built_in">string</span> info = <span class="string">&quot;Railing Type:  &quot;</span> + railingType.Name;</span><br><span class="line">        info += <span class="string">&quot;\nPrimary Handrail Height:  &quot;</span> + railingType.PrimaryHandrailHeight;</span><br><span class="line">        info += <span class="string">&quot;\nTop Rail Height:  &quot;</span> + railingType.TopRailHeight;</span><br><span class="line"></span><br><span class="line">        TaskDialog.Show(<span class="string">&quot;Revit&quot;</span>, info);</span><br><span class="line">    &#125;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<h2 id="楼梯注释"><a href="#楼梯注释" class="headerlink" title="楼梯注释"></a>楼梯注释</h2><p><strong>楼梯注释</strong></p>
<p>StairsPath类可用于注释楼梯的坡度方向和行走线。静态StairsPath.Create（）方法将在楼梯必须可见的特定平面视图中为具有指定楼梯路径类型的指定楼梯创建新楼梯路径。</p>
<p>在Revit UI中编辑楼梯路径时，StairsPath类具有与“属性”窗口中可用的属性相同的属性，例如设置上下方向文字沿着或是否应显示文字的属性。此外，可以指定上下文字的偏移，也可以指定楼梯路径相对于楼梯中心线的偏移。</p>
<p><img src="https://help.autodesk.com/cloudhelp/2018/CHS/Revit-API/images/GUID-98F7477B-3F67-4E52-BDC3-6B63ECA6B700.jpg" alt="img"></p>
<p>下面的示例在项目中查找StairsPathType和FloorPlan，并使用它们为给定的Stairs创建新的StairsPath。</p>
<p>代码区域：创建楼梯路径</p>
<figure class="highlight c#"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br><span class="line">23</span><br><span class="line">24</span><br><span class="line">25</span><br><span class="line">26</span><br><span class="line">27</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="keyword">private</span> <span class="keyword">void</span> <span class="title">CreateStairsPath</span>(<span class="params">Document document, Stairs stairs</span>)</span></span><br><span class="line">&#123;</span><br><span class="line">    Transaction transNewPath = <span class="keyword">new</span> Transaction(document, <span class="string">&quot;New Stairs Path&quot;</span>);</span><br><span class="line">    transNewPath.Start();</span><br><span class="line">            </span><br><span class="line">    <span class="comment">// Find StairsPathType</span></span><br><span class="line">    FilteredElementCollector collector = <span class="keyword">new</span> FilteredElementCollector(document);</span><br><span class="line">    ICollection&lt;ElementId&gt; stairsPathIds = collector.OfClass(<span class="keyword">typeof</span>(StairsPathType)).ToElementIdsElementId();</span><br><span class="line"></span><br><span class="line">    <span class="comment">// Find a FloorPlan</span></span><br><span class="line">    ElementId planViewId = ElementId.InvalidElementId;</span><br><span class="line">    FilteredElementCollector viewCollector = <span class="keyword">new</span> FilteredElementCollector(document);</span><br><span class="line">    ICollection&lt;ElementId&gt; viewIds = viewCollector.OfClass(<span class="keyword">typeof</span>(View)).ToElementIdsElementId();</span><br><span class="line">    <span class="keyword">foreach</span> (ElementId viewId <span class="keyword">in</span> viewIds)</span><br><span class="line">    &#123;</span><br><span class="line">        View view = document.GetElement(viewId) <span class="keyword">as</span> View;</span><br><span class="line">        <span class="keyword">if</span> (view.ViewType == ViewType.FloorPlan)</span><br><span class="line">        &#123;</span><br><span class="line">            planViewId = view.Id;</span><br><span class="line">            <span class="keyword">break</span>;</span><br><span class="line">        &#125;</span><br><span class="line">    &#125;</span><br><span class="line">            </span><br><span class="line">    LinkElementId stairsLinkId = <span class="keyword">new</span> LinkElementId(stairs.Id);</span><br><span class="line">    StairsPath.Create(stairs.Document, stairsLinkId, stairsPathIds.First(), planViewId);</span><br><span class="line">    transNewPath.Commit();</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<p>StairsPath具有StairsPathType。楼梯路径类型可从两个预定义的系统族中获得：“自动向上&#x2F;向下方向”和“固定向上方向”。可用于这两种类型的属性作为StairsPathType类中的属性提供，例如FullStepArrow和DistanceToCutMark。</p>
<p><img src="https://help.autodesk.com/cloudhelp/2018/CHS/Revit-API/images/GUID-21CCA05E-3A7C-4CA3-AF96-8BBB88F775E7.jpg" alt="img"></p>
<p>CutMarkType类表示Revit UI中的剪切标记类型，它具有表示在UI中编辑剪切标记类型时可用的相同属性的属性，例如CutLineAngle和CutLineExtension。它与StairsType对象相关联，可以使用BuiltInParameter STAIRSTYPE_CUTMARK_TYPE进行检索，如下所示。</p>
<p>代码区域：获取楼梯的CutMarkType</p>
<figure class="highlight c#"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="keyword">private</span> CutMarkType <span class="title">GetCutMark</span>(<span class="params">Stairs stairs</span>)</span></span><br><span class="line">&#123;</span><br><span class="line">    CutMarkType cutMarkType = <span class="literal">null</span>;</span><br><span class="line">    StairsType stairsType = stairs.Document.GetElement(stairs.GetTypeId()) <span class="keyword">as</span> StairsType;</span><br><span class="line">    Parameter paramCutMark = stairsType.get_Parameter(BuiltInParameter.STAIRSTYPE_CUTMARK_TYPE);</span><br><span class="line">    <span class="keyword">if</span> (paramCutMark.StorageType == StorageType.ElementId)  <span class="comment">// should be an element id</span></span><br><span class="line">    &#123;</span><br><span class="line">        ElementId cutMarkId = paramCutMark.AsElementId();</span><br><span class="line">        cutMarkType = stairs.Document.GetElement(cutMarkId) <span class="keyword">as</span> CutMarkType;</span><br><span class="line">    &#125;</span><br><span class="line"></span><br><span class="line">    <span class="keyword">return</span> cutMarkType;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<h2 id="楼梯构件"><a href="#楼梯构件" class="headerlink" title="楼梯构件"></a>楼梯构件</h2><p><strong>楼梯构件</strong></p>
<p>Stairs类表示Revit中的楼梯图元，并包含表示有关踏步、高度、楼层数以及楼梯高度、底部标高和顶部标高的信息的属性。Stairs类的方法可用于获取楼梯平台构件、楼梯梯段构件和楼梯支撑。</p>
<p>下面的示例按构件查找所有楼梯，并将有关每个楼梯的一些信息输出到TaskDialog对话框。请注意，此示例使用带有BuiltInCategory.OST_Stairs的类别过滤器，该过滤器将返回所有楼梯的ElementId，因此在从文档中检索时将每个ElementId转换为Stairs类之前，需要进行测试以查看每个ElementId是否代表Stairs By Component。</p>
<p>代码区域：获取楼梯信息</p>
<figure class="highlight c#"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br><span class="line">23</span><br><span class="line">24</span><br><span class="line">25</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="keyword">private</span> Stairs <span class="title">GetStairInfo</span>(<span class="params">Document document</span>)</span></span><br><span class="line">&#123;</span><br><span class="line">    Stairs stairs = <span class="literal">null</span>;</span><br><span class="line"></span><br><span class="line">    FilteredElementCollector collector = <span class="keyword">new</span> FilteredElementCollector(document);</span><br><span class="line">    ICollection&lt;ElementId&gt; stairsIds = collector.WhereElementIsNotElementType().OfCategory(BuiltInCategory.OST_Stairs).ToElementIdsElementId();</span><br><span class="line">    <span class="keyword">foreach</span> (ElementId stairId <span class="keyword">in</span> stairsIds)</span><br><span class="line">    &#123;</span><br><span class="line">        <span class="keyword">if</span> (Stairs.IsByComponent(document, stairId) == <span class="literal">true</span>)</span><br><span class="line">        &#123;</span><br><span class="line">            stairs = document.GetElement(stairId) <span class="keyword">as</span> Stairs;</span><br><span class="line">                   </span><br><span class="line">            <span class="comment">// Format the information</span></span><br><span class="line">            String info = <span class="string">&quot;\nNumber of stories:  &quot;</span> + stairs.NumberOfStories;</span><br><span class="line">            info += <span class="string">&quot;\nHeight of stairs:  &quot;</span> + stairs.Height;</span><br><span class="line">            info += <span class="string">&quot;\nNumber of treads:  &quot;</span> + stairs.ActualTreadsNumber;</span><br><span class="line">            info += <span class="string">&quot;\nTread depth:  &quot;</span> + stairs.ActualTreadDepth;</span><br><span class="line">            </span><br><span class="line">            <span class="comment">// Show the information to the user.</span></span><br><span class="line">            TaskDialog.Show(<span class="string">&quot;Revit&quot;</span>, info);</span><br><span class="line">        &#125;</span><br><span class="line">    &#125;</span><br><span class="line">  </span><br><span class="line">    <span class="keyword">return</span> stairs;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<p>StairsType类表示Stairs元素的类型。它包含有关楼梯的信息，例如楼梯对象中所有梯段和平台的类型、楼梯左侧、右侧和中间支撑的类型和偏移，以及与楼梯生成相关的许多其他特性，例如楼梯图元上每个踢面的最大高度。下面的示例获取Stairs元素的StairsType，并在TaskDialog中显示有关该元素的一些信息。</p>
<p>代码区域：获取楼梯类型信息</p>
<figure class="highlight c#"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="keyword">private</span> <span class="keyword">void</span> <span class="title">GetStairsType</span>(<span class="params">Stairs stairs</span>)</span></span><br><span class="line">&#123;</span><br><span class="line">    StairsType stairsType = stairs.Document.GetElement(stairs.GetTypeId()) <span class="keyword">as</span> StairsType;</span><br><span class="line"></span><br><span class="line">    <span class="comment">// Format stairs type info for display</span></span><br><span class="line">    <span class="built_in">string</span> info = <span class="string">&quot;Stairs Type:  &quot;</span> + stairsType.Name;</span><br><span class="line">    info += <span class="string">&quot;\nLeft Lateral Offset:  &quot;</span> + stairsType.LeftLateralOffset;</span><br><span class="line">    info += <span class="string">&quot;\nRight Lateral Offset:  &quot;</span> + stairsType.RightLateralOffset;</span><br><span class="line">    info += <span class="string">&quot;\nMax Riser Height:  &quot;</span> + stairsType.MaxRiserHeight;</span><br><span class="line">    info += <span class="string">&quot;\nMin Run Width:  &quot;</span> + stairsType.MinRunWidth;</span><br><span class="line"></span><br><span class="line">    TaskDialog.Show(<span class="string">&quot;Revit&quot;</span>, info);</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<p><strong>梯段</strong></p>
<p>楼梯构件由梯段、平台和支撑组成。这些项中的每一项都可以从Stairs类中检索。梯段在Revit API中由StairsRun类表示。下面的示例获取Stairs对象的每个梯段，并确保它以踢面开始和结束。</p>
<p>代码区域：使用StairsRun</p>
<figure class="highlight c#"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="keyword">private</span> <span class="keyword">void</span> <span class="title">AddStartandEndRisers</span>(<span class="params">Stairs stairs</span>)</span></span><br><span class="line">&#123;</span><br><span class="line">    ICollection&lt;ElementId&gt; runIds = stairs.GetStairsRuns();</span><br><span class="line">            </span><br><span class="line">    <span class="keyword">foreach</span> (ElementId runId <span class="keyword">in</span> runIds)</span><br><span class="line">    &#123;</span><br><span class="line">        StairsRun run = stairs.Document.GetElement(runId) <span class="keyword">as</span> StairsRun;</span><br><span class="line">        <span class="keyword">if</span> (<span class="literal">null</span> != run)</span><br><span class="line">        &#123;</span><br><span class="line">            run.BeginsWithRiser = <span class="literal">true</span>;</span><br><span class="line">            run.EndsWithRiser = <span class="literal">true</span>;</span><br><span class="line">        &#125;</span><br><span class="line">    &#125;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<p>StairsRun类提供对梯段属性的访问，例如StairsRunStyle（直线、斜梯等），BaseElevation、TopElevation和有关高程的属性。StairsRun类中还有一些方法可用于访问梯段承载的支撑，可以是全部支撑，也可以仅是梯段边界左侧或右侧的支撑。GetStairsPath（）方法将返回表示梯段上楼梯路径的曲线，这些曲线将投影到楼梯的底部标高上。GetFootprintBoundary（）方法返回梯段的边界曲线，这些曲线也投影到楼梯的底部标高上。</p>
<p>StairsRun类有三个用于创建新梯段的静态方法。这些将在“创建和编辑楼梯”部分中介绍。</p>
<p>StairsRunType类表示StairsRun的类型。它包含有关梯段踏板和宽度的许多特性以及有关梯段的其他信息。下面的示例获取Stairs元素中第一个梯段的StairsRunType，并显示踢面和踏步厚度沿着以及类型名称。</p>
<p>代码区域：获取StairsRunType信息</p>
<figure class="highlight c#"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="keyword">private</span> <span class="keyword">void</span> <span class="title">GetRunType</span>(<span class="params">Stairs stairs</span>)</span></span><br><span class="line">&#123;</span><br><span class="line">    ICollection&lt;ElementId&gt; runIds = stairs.GetStairsRuns();</span><br><span class="line"></span><br><span class="line">    ElementId firstRunId = runIds.First();</span><br><span class="line"></span><br><span class="line">    StairsRun firstRun = stairs.Document.GetElement(firstRunId) <span class="keyword">as</span> StairsRun;</span><br><span class="line">    <span class="keyword">if</span> (<span class="literal">null</span> != firstRun)</span><br><span class="line">    &#123;</span><br><span class="line">        StairsRunType runType = stairs.Document.GetElement(firstRun.GetTypeId()) <span class="keyword">as</span> StairsRunType;</span><br><span class="line">        <span class="comment">// Format landing type info for display</span></span><br><span class="line">        <span class="built_in">string</span> info = <span class="string">&quot;Stairs Run Type:  &quot;</span> + runType.Name;</span><br><span class="line">        info += <span class="string">&quot;\nRiser Thickness:  &quot;</span> + runType.RiserThickness;</span><br><span class="line">        info += <span class="string">&quot;\nTread Thickness:  &quot;</span> + runType.TreadThickness;</span><br><span class="line"></span><br><span class="line">        TaskDialog.Show(<span class="string">&quot;Revit&quot;</span>, info);</span><br><span class="line">    &#125;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<p><strong>平台</strong></p>
<p>平台由StairsLanding类表示。下面的示例查找Stairs对象的每个平台的厚度。</p>
<p>代码区域：使用楼梯平台</p>
<figure class="highlight c#"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="keyword">private</span> <span class="keyword">void</span> <span class="title">GetStairLandings</span>(<span class="params">Stairs stairs</span>)</span></span><br><span class="line">&#123;</span><br><span class="line">    ICollection&lt;ElementId&gt; landingIds = stairs.GetStairsLandings();</span><br><span class="line">    <span class="built_in">string</span> info = <span class="string">&quot;Number of landings:  &quot;</span> + landingIds.Count;</span><br><span class="line"></span><br><span class="line">    <span class="built_in">int</span> landingIndex = <span class="number">0</span>;</span><br><span class="line">    <span class="keyword">foreach</span> (ElementId landingId <span class="keyword">in</span> landingIds)</span><br><span class="line">    &#123;</span><br><span class="line">        landingIndex++;</span><br><span class="line">        StairsLanding landing = stairs.Document.GetElement(landingId) <span class="keyword">as</span> StairsLanding;</span><br><span class="line">        <span class="keyword">if</span> (<span class="literal">null</span> != landing)</span><br><span class="line">        &#123;</span><br><span class="line">            info += <span class="string">&quot;\nThickness of Landing &quot;</span> + landingIndex + <span class="string">&quot;:  &quot;</span> + landing.Thickness;</span><br><span class="line">        &#125;</span><br><span class="line">    &#125;</span><br><span class="line"></span><br><span class="line">    TaskDialog.Show(<span class="string">&quot;Revit&quot;</span>, info);</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<p>与StairsRun类似，StairsLanding具有GetStairsPath（）方法和GetFootprintBoundary（）方法，前者返回表示平台上投影到楼梯基层的楼梯路径的曲线，后者返回平台的边界曲线，也投影到楼梯基层。同样类似于StairsRun，有一种方法可以获取平台承载的所有支撑。</p>
<p>StairsLanding类有一个在两个梯段之间创建新平台的方法。它将在“创建和编辑楼梯”部分中介绍。</p>
<p>StairsLandingType类表示Revit API中的平台类型。StairsLandingType类只有两个特定于它的属性，即IsMonolithic（如果楼梯平台是整体的，则为真）和Thickness（表示楼梯平台的厚度）。</p>
<p><strong>楼梯连接</strong><br>Both StairsRun and StairsLanding have a GetConnections() method which provides information about connections among stairs components (run to run, or run to landing). The method returns a collection of StairsComponentConnection objects which have properties about each connection, including the connection type (to a landing, the start of a stairs run, or the end of a stairs run) and the Id of the connected stairs component.<br>StairsRun和StairsLanding都具有GetConnections（）方法，该方法提供有关楼梯构件之间连接的信息（梯段到梯段，或梯段到平台）。该方法返回一个StairsStringentConnection对象的集合，这些对象具有关于每个连接的属性，包括连接类型（连接平台、楼梯梯段起点或楼梯梯段终点）和连接的楼梯构件的ID。</p>
<p><strong>支撑</strong></p>
<p>Revit API不显示楼梯支撑类。获取楼梯、楼梯梯段或楼梯平台的支撑时，支撑将为常规Revit图元。下面的示例获取Stairs对象的所有支撑的名称。</p>
<p>代码区域：获取楼梯支撑</p>
<figure class="highlight c#"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="keyword">private</span> <span class="keyword">void</span> <span class="title">GetStairSupports</span>(<span class="params">Stairs stairs</span>)</span></span><br><span class="line">&#123;</span><br><span class="line">    ICollection&lt;ElementId&gt; supportIds = stairs.GetStairsSupports();</span><br><span class="line">    <span class="built_in">string</span> info = <span class="string">&quot;Number of supports:  &quot;</span> + supportIds.Count;</span><br><span class="line"></span><br><span class="line">    <span class="built_in">int</span> supportIndex = <span class="number">0</span>;</span><br><span class="line">    <span class="keyword">foreach</span> (ElementId supportId <span class="keyword">in</span> supportIds)</span><br><span class="line">    &#123;</span><br><span class="line">        supportIndex++;</span><br><span class="line">        Element support = stairs.Document.GetElement(supportId);</span><br><span class="line">        <span class="keyword">if</span> (<span class="literal">null</span> != support)</span><br><span class="line">        &#123;</span><br><span class="line">            info += <span class="string">&quot;\nName of support &quot;</span> + supportIndex + <span class="string">&quot;:  &quot;</span> + support.Name;</span><br><span class="line">        &#125;</span><br><span class="line">    &#125;</span><br><span class="line"></span><br><span class="line">    TaskDialog.Show(<span class="string">&quot;Revit&quot;</span>, info);</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<h2 id="注：翻译自Revit-API-Developers-Guide"><a href="#注：翻译自Revit-API-Developers-Guide" class="headerlink" title="注：翻译自Revit API Developers Guide"></a><em><strong>注：</strong></em>翻译自<a target="_blank" rel="noopener" href="https://help.autodesk.com/view/RVT/2018/ENU/?guid=Revit_API_Revit_API_Developers_Guide_html">Revit API Developers Guide</a></h2></article><div class="tag_share"><div class="post-meta__tag-list"><a class="post-meta__tags" href="/tags/Revit/">Revit</a></div><div class="post-share"><div class="social-share" data-image="/images/4stars.png" data-sites="facebook,twitter,wechat,weibo,qq"></div><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/butterfly-extsrc/sharejs/dist/css/share.min.css" media="print" onload="this.media='all'"><script src="https://cdn.jsdelivr.net/npm/butterfly-extsrc/sharejs/dist/js/social-share.min.js" defer></script></div></div><nav class="pagination-post" id="pagination"><a class="pagination-related" href="/2024/12/23/Revit%E4%BA%8C%E5%BC%80%E6%8C%87%E5%8D%97/22%E6%9B%B2%E9%9D%A2/" title="22曲面"><div class="cover" style="background: var(--default-bg-color)"></div><div class="info"><div class="info-1"><div class="info-item-1">上一篇</div><div class="info-item-2">22曲面</div></div><div class="info-2"><div class="info-item-1">Surfacessurface类表示表面的数学表示。 surface类不是从GeometryObject类派生的，并且不以边或边循环为边界。Revit中的有界曲面由Face类表示。 Surface是更具体的曲面的基类：  Plane   平面 CylindricalSurface   圆柱形表面 ConicalSurface   圆锥面 RuledSurface   规则曲面 RevolvedSurface   旋转曲面 HermiteSurface   Hermite曲面  这些子类包含Create（）方法和只读属性，适用于构造导入几何图形。有关在几何体创建中使用曲面的示例，请参见DirectShape主题。 注：翻译自Revit API Developers Guide</div></div></div></a><a class="pagination-related" href="/2024/12/20/RevitApi%E5%90%88%E9%9B%86/Autodesk.Revit.DB%20Transform/" title="Autodesk.Revit.DB Transform"><div class="cover" style="background: var(--default-bg-color)"></div><div class="info text-right"><div class="info-1"><div class="info-item-1">下一篇</div><div class="info-item-2">Autodesk.Revit.DB Transform</div></div><div class="info-2"><div class="info-item-1">Autodesk.Revit.DB Transform仿射三维空间的一个变换。 语法public class Transform : APIObject示例12345678910111213141516171819202122### public static XYZ TransformPoint(XYZ point, Transform transform)&#123;    double x = point.X;    double y = point.Y;    double z = point.Z;    //transform basis of the old coordinate system in the new coordinate // system    XYZ b0 = transform.get_Basis(0);    XYZ b1 = transform.get_Basis(1);    XYZ b2 = transform.get_Basis(2);    XYZ origin = transform.Origin;       ...</div></div></div></a></nav><div class="relatedPosts"><div class="headline"><i class="fas fa-thumbs-up fa-fw"></i><span>相关推荐</span></div><div class="relatedPosts-list"><a class="pagination-related" href="/2025/01/16/Revit%E4%BA%8C%E5%BC%80%E7%A4%BA%E4%BE%8B/Revit%E4%B8%8EExcel%E4%BA%A4%E4%BA%92/" title="Revit与Excel交互"><div class="cover" style="background: var(--default-bg-color)"></div><div class="info text-center"><div class="info-1"><div class="info-item-1"><i class="far fa-calendar-alt fa-fw"></i> 2025-01-16</div><div class="info-item-2">Revit与Excel交互</div></div><div class="info-2"><div class="info-item-1">  Excel检测更改自动保存，Revit自动读取数据生成元素 </div></div></div></a><a class="pagination-related" href="/2024/12/20/RevitApi%E5%90%88%E9%9B%86/Autodesk.%20Revit.DB%20ElementTransformUtils/" title="Autodesk.Revit.DB ElementTransformUtils"><div class="cover" style="background: var(--default-bg-color)"></div><div class="info text-center"><div class="info-1"><div class="info-item-1"><i class="far fa-calendar-alt fa-fw"></i> 2024-12-20</div><div class="info-item-2">Autodesk.Revit.DB ElementTransformUtils</div></div><div class="info-2"><div class="info-item-1">Autodesk. Revit.DB ElementTransformUtils允许元素转换的实用程序集合（例如移动，旋转，镜像和复制）。 语法1public static class ElementTransformUtils    继承层次结构 System Object Autodesk.Revit.DB ElementTransformUtils   方法CanMirrorElement确定是否可以镜像元素。 CanMirrorElements确定是否可以镜像元素。 CopyElement复制元素并将副本放置在给定转换指示的位置。 CopyElements(Document, ICollection ElementId , XYZ)复制一组元素，并将副本放置在给定指示的位置。 CopyElements(Document, ICollection ElementId , Document, Transform, CopyPasteOptions)将一组元素从源文档复制到目标文档。 CopyElements(View, ICollection ElementId ,...</div></div></div></a><a class="pagination-related" href="/2024/11/18/RevitApi%E5%90%88%E9%9B%86/Autodesk.Revit.DB%20CurveArray/" title="Autodesk.Revit.DB CurveArray"><div class="cover" style="background: var(--default-bg-color)"></div><div class="info text-center"><div class="info-1"><div class="info-item-1"><i class="far fa-calendar-alt fa-fw"></i> 2024-11-18</div><div class="info-item-2">Autodesk.Revit.DB CurveArray</div></div><div class="info-2"><div class="info-item-1">Autodesk.Revit.DB CurveArray可以包含曲线的数组。 语法1public class CurveArray : APIObject, IEnumerable  继承层次结构System Object ​	Autodesk.Revit.DB APIObject ​		Autodesk.Revit.DB CurveArray 另见CurveArray Members Autodesk.Revit.DB Namespace 构造函数CurveArray创建CurveArray类的新实例 方法Append将曲线添加到数组的末尾。 Clear从数组中删除每条曲线，使其为空。 ForwardIterator将一个向前移动的迭代器添加到数组中。 GetEnumerator将一个向前移动的迭代器添加到数组中。 Insert将指定的曲线插入数组。 ReverseIterator返回一个向后移动的迭代器到数组。 属性IsEmpty测试数组是否为空。 Item获取或设置数组中指定索引处的曲线。 Size返回数组中的曲线数。 注：翻译自Revit Api docs 2018</div></div></div></a><a class="pagination-related" href="/2024/12/10/RevitApi%E5%90%88%E9%9B%86/Autodesk.Revit.DB%20Opening/" title="Autodesk.Revit.DB Opening"><div class="cover" style="background: var(--default-bg-color)"></div><div class="info text-center"><div class="info-1"><div class="info-item-1"><i class="far fa-calendar-alt fa-fw"></i> 2024-12-10</div><div class="info-item-2">Autodesk.Revit.DB Opening</div></div><div class="info-2"><div class="info-item-1">Autodesk.Revit.DB OpeningAutodesk Revit项目或族文档中的洞口。 语法1public class Opening : Element  附注该对象表示各种不同类型的洞口：  墙中由修订项目中的两个边界点创建的矩形洞口。 由应用于屋顶、楼板、天花板、梁、支撑或柱的一组曲线创建的洞口。 一个垂直的竖井开口延伸到一个或多个水平。 在族文档中的墙或天花板上创建的简单洞口。  根据打开的类型，此类的某些属性将不可用。 这个对象派生自Element基对象，并且支持该对象的所有方法，例如检索该对象的参数的能力。此对象还支持访问结构分析模型，但此功能仅适用于Autodesk Revit Structure。 示例123456789101112131415161718192021222324252627282930313233343536373839404142434445464748495051### private void Getinfo_Opening(Opening opening)&#123;    string message =...</div></div></div></a><a class="pagination-related" href="/2024/10/30/RevitApi%E5%90%88%E9%9B%86/Autodesk.Revit.DB%20Document/" title="Autodesk.Revit.DB Document"><div class="cover" style="background: var(--default-bg-color)"></div><div class="info text-center"><div class="info-1"><div class="info-item-1"><i class="far fa-calendar-alt fa-fw"></i> 2024-10-30</div><div class="info-item-2">Autodesk.Revit.DB Document</div></div><div class="info-2"><div class="info-item-1">Autodesk.Revit.DB Document表示打开的 Autodesk Revit 项目的对象。 语法1public class Document : IDisposable    附注Document 对象表示 Autodesk Revit 项目。Revit 可以打开多个项目，并打开这些项目的多个视图。活动视图或最顶层视图将是活动项目，因此是可从 Application 对象获得的活动文档。 继承层次结构 System Object Autodesk.Revit.DB Document Autodesk.Revit.DB.Macros DocumentEntryPoint  方法AcquireCoordinates 不知道是啥，API没给描述  AutoJoinElements 强制 Revit...</div></div></div></a><a class="pagination-related" href="/2024/12/19/RevitApi%E5%90%88%E9%9B%86/Autodesk.Revit.UI.Selection%20Namespace/" title="Autodesk.Revit.UI.Selection"><div class="cover" style="background: var(--default-bg-color)"></div><div class="info text-center"><div class="info-1"><div class="info-item-1"><i class="far fa-calendar-alt fa-fw"></i> 2024-12-19</div><div class="info-item-2">Autodesk.Revit.UI.Selection</div></div><div class="info-2"><div class="info-item-1">Autodesk.Revit.UI.SelectionClassesPickedBox包含两个 XYZ 点的类，表示屏幕上的选取框。  Properties  Max 最大坐标数（拾取框的右上角）。  Min 最小坐标（拾取框的左下角）。     SelectableInViewFilter一个过滤器，用于传递在给定视图中可选的元素。  Constructors  SelectableInViewFilter  (Document, ElementId) 构造 SelectableInViewFilter 的新实例。  SelectableInViewFilter (Document, ElementId, Boolean) 构造 SelectableInViewFilter 的新实例，并可选择传递所有不可选择的元素。    Methods  PassesFilter(Element) 将筛选器应用于给定元素。  PassesFilter(Document,...</div></div></div></a></div></div><hr class="custom-hr"/><div id="post-comment"><div class="comment-head"><div class="comment-headline"><i class="fas fa-comments fa-fw"></i><span> 评论</span></div></div><div class="comment-wrap"><div><div id="giscus-wrap"></div></div></div></div></div><div class="aside-content" id="aside-content"><div class="card-widget card-info text-center"><div class="avatar-img"><img src="/images/4stars.png" onerror="this.onerror=null;this.src='/img/friend_404.gif'" alt="avatar"/></div><div class="author-info-name">funtim41@gmail.com</div><div class="author-info-description">实践-认识-再实践-再认识</div><div class="site-data"><a href="/archives/"><div class="headline">文章</div><div class="length-num">60</div></a><a href="/tags/"><div class="headline">标签</div><div class="length-num">5</div></a><a href="/categories/"><div class="headline">分类</div><div class="length-num">7</div></a></div><a id="card-info-btn" target="_blank" rel="noopener" href="https://github.com/FunTim41"><i class="fab fa-github"></i><span>Follow Me</span></a><div class="card-info-social-icons"><a class="social-icon" href="https://github.com/FunTim41" target="_blank" title="Github"><i class="fab fa-github" style="color: #FFFFFF;"></i></a></div></div><div class="card-widget card-announcement"><div class="item-headline"><i class="fas fa-bullhorn fa-shake"></i><span>公告</span></div><div class="announcement_content">This is my Blog</div></div><div class="sticky_layout"><div class="card-widget" id="card-toc"><div class="item-headline"><i class="fas fa-stream"></i><span>目录</span><span class="toc-percentage"></span></div><div class="toc-content"><ol class="toc"><li class="toc-item toc-level-1"><a class="toc-link" href="#%E6%A5%BC%E6%A2%AF%E5%92%8C%E6%89%B6%E6%89%8B"><span class="toc-number">1.</span> <span class="toc-text">楼梯和扶手</span></a><ol class="toc-child"><li class="toc-item toc-level-2"><a class="toc-link" href="#%E5%88%9B%E5%BB%BA%E5%92%8C%E7%BC%96%E8%BE%91%E6%A5%BC%E6%A2%AF"><span class="toc-number">1.1.</span> <span class="toc-text">创建和编辑楼梯</span></a></li><li class="toc-item toc-level-2"><a class="toc-link" href="#%E6%89%B6%E6%89%8B"><span class="toc-number">1.2.</span> <span class="toc-text">扶手</span></a></li><li class="toc-item toc-level-2"><a class="toc-link" href="#%E6%A5%BC%E6%A2%AF%E6%B3%A8%E9%87%8A"><span class="toc-number">1.3.</span> <span class="toc-text">楼梯注释</span></a></li><li class="toc-item toc-level-2"><a class="toc-link" href="#%E6%A5%BC%E6%A2%AF%E6%9E%84%E4%BB%B6"><span class="toc-number">1.4.</span> <span class="toc-text">楼梯构件</span></a></li><li class="toc-item toc-level-2"><a class="toc-link" href="#%E6%B3%A8%EF%BC%9A%E7%BF%BB%E8%AF%91%E8%87%AARevit-API-Developers-Guide"><span class="toc-number">1.5.</span> <span class="toc-text">注：翻译自Revit API Developers Guide</span></a></li></ol></li></ol></div></div><div class="card-widget card-recent-post"><div class="item-headline"><i class="fas fa-history"></i><span>最新文章</span></div><div class="aside-list"><div class="aside-list-item no-cover"><div class="content"><a class="title" href="/2025/02/08/ObjectARX%EF%BC%9AManaged.NET%E5%BC%80%E5%8F%91%E4%BA%BA%E5%91%98%E6%8C%87%E5%8D%97/05%E5%9C%A8%E4%B8%89%E7%BB%B4%E7%A9%BA%E9%97%B4%E4%B8%AD%E5%B7%A5%E4%BD%9C%EF%BC%88.NET%EF%BC%89/" title="05在三维空间中工作（.NET）">05在三维空间中工作（.NET）</a><time datetime="2025-02-08T10:12:14.946Z" title="更新于 2025-02-08 18:12:14">2025-02-08</time></div></div><div class="aside-list-item no-cover"><div class="content"><a class="title" href="/2025/02/07/ObjectARX%EF%BC%9AManaged.NET%E5%BC%80%E5%8F%91%E4%BA%BA%E5%91%98%E6%8C%87%E5%8D%97/04%E5%B0%BA%E5%AF%B8%E6%A0%87%E6%B3%A8%E5%92%8C%E5%85%AC%E5%B7%AE%EF%BC%88.NET%EF%BC%89/" title="04 尺寸标注和公差（.NET）">04 尺寸标注和公差（.NET）</a><time datetime="2025-02-07T07:32:15.924Z" title="更新于 2025-02-07 15:32:15">2025-02-07</time></div></div><div class="aside-list-item no-cover"><div class="content"><a class="title" href="/2025/01/14/ObjectARX%EF%BC%9AManaged.NET%E5%BC%80%E5%8F%91%E4%BA%BA%E5%91%98%E6%8C%87%E5%8D%97/03%E5%88%9B%E5%BB%BA%E5%92%8C%E7%BC%96%E8%BE%91AutoCAD%E5%9B%BE%E5%85%83%EF%BC%88.NET%EF%BC%89/" title="03创建和编辑AutoCAD图元（.NET）">03创建和编辑AutoCAD图元（.NET）</a><time datetime="2025-01-19T03:40:40.285Z" title="更新于 2025-01-19 11:40:40">2025-01-19</time></div></div><div class="aside-list-item no-cover"><div class="content"><a class="title" href="/2025/01/13/ObjectARX%EF%BC%9AManaged.NET%E5%BC%80%E5%8F%91%E4%BA%BA%E5%91%98%E6%8C%87%E5%8D%97/02%E6%8E%A7%E5%88%B6AutoCAD%E7%8E%AF%E5%A2%83%EF%BC%88.NET%EF%BC%89/" title="02控制AutoCAD环境（.NET）">02控制AutoCAD环境（.NET）</a><time datetime="2025-01-17T10:16:52.559Z" title="更新于 2025-01-17 18:16:52">2025-01-17</time></div></div><div class="aside-list-item no-cover"><div class="content"><a class="title" href="/2025/01/12/ObjectARX%EF%BC%9AManaged.NET%E5%BC%80%E5%8F%91%E4%BA%BA%E5%91%98%E6%8C%87%E5%8D%97/01AutoCAD.NET%20API%EF%BC%88.NET%EF%BC%89%E7%9A%84%E5%9F%BA%E7%A1%80%E7%9F%A5%E8%AF%86/" title="01AutoCAD .NET API（.NET）的基础知识">01AutoCAD .NET API（.NET）的基础知识</a><time datetime="2025-01-17T10:16:40.962Z" title="更新于 2025-01-17 18:16:40">2025-01-17</time></div></div></div></div></div></div></main><footer id="footer" style="background-image: url(/images/topback.jpg);"><div id="footer-wrap"><div class="copyright">&copy;2024 - 2025 By funtim41@gmail.com</div><div class="framework-info"><span>框架 </span><a target="_blank" rel="noopener" href="https://hexo.io">Hexo</a><span class="footer-separator">|</span><span>主题 </span><a target="_blank" rel="noopener" href="https://github.com/jerryc127/hexo-theme-butterfly">Butterfly</a></div><div class="footer_custom_text">学而不思则罔，思而不学则殆。</div></div></footer></div><div id="rightside"><div id="rightside-config-hide"><button id="readmode" type="button" title="阅读模式"><i class="fas fa-book-open"></i></button><button id="darkmode" type="button" title="日间和夜间模式切换"><i class="fas fa-adjust"></i></button><button id="hide-aside-btn" type="button" title="单栏和双栏切换"><i class="fas fa-arrows-alt-h"></i></button></div><div id="rightside-config-show"><button id="rightside-config" type="button" title="设置"><i class="fas fa-cog fa-spin"></i></button><button class="close" id="mobile-toc-button" type="button" title="目录"><i class="fas fa-list-ul"></i></button><a id="to_comment" href="#post-comment" title="前往评论"><i class="fas fa-comments"></i></a><button id="go-up" type="button" title="回到顶部"><span class="scroll-percent"></span><i class="fas fa-arrow-up"></i></button></div></div><div><script src="/js/utils.js"></script><script src="/js/main.js"></script><script src="https://cdn.jsdelivr.net/npm/node-snackbar/dist/snackbar.min.js"></script><script>(() => {
  const panguFn = () => {
    if (typeof pangu === 'object') pangu.autoSpacingPage()
    else {
      btf.getScript('https://cdn.jsdelivr.net/npm/pangu/dist/browser/pangu.min.js')
        .then(() => {
          pangu.autoSpacingPage()
        })
    }
  }

  const panguInit = () => {
    if (false){
      GLOBAL_CONFIG_SITE.isPost && panguFn()
    } else {
      panguFn()
    }
  }

  btf.addGlobalFn('pjaxComplete', panguInit, 'pangu')
  document.addEventListener('DOMContentLoaded', panguInit)
})()</script><div class="js-pjax"><script>(() => {
  const isShuoshuo = GLOBAL_CONFIG_SITE.isShuoshuo
  const option = null

  const getGiscusTheme = theme => theme === 'dark' ? 'dark' : 'light'

  const createScriptElement = config => {
    const ele = document.createElement('script')
    Object.entries(config).forEach(([key, value]) => {
      ele.setAttribute(key, value)
    })
    return ele
  }

  const loadGiscus = (el = document, key) => {
    const mappingConfig = isShuoshuo
      ? { 'data-mapping': 'specific', 'data-term': key }
      : { 'data-mapping': (option && option['data-mapping']) || 'pathname' }

    const giscusConfig = {
      src: 'https://giscus.app/client.js',
      'data-repo': 'FunTim41/funtim41.github.io',
      'data-repo-id': 'R_kgDONjG8ww',
      'data-category-id': 'DIC_kwDONjG8w84Cllg2',
      'data-theme': getGiscusTheme(document.documentElement.getAttribute('data-theme')),
      'data-reactions-enabled': '1',
      crossorigin: 'anonymous',
      async: true,
      ...option,
      ...mappingConfig
    }

    const scriptElement = createScriptElement(giscusConfig)

    el.querySelector('#giscus-wrap').appendChild(scriptElement)

    if (isShuoshuo) {
      window.shuoshuoComment.destroyGiscus = () => {
        if (el.children.length) {
          el.innerHTML = ''
          el.classList.add('no-comment')
        }
      }
    }
  }

  const changeGiscusTheme = theme => {
    const iframe = document.querySelector('#giscus-wrap iframe')
    if (iframe) {
      const message = {
        giscus: {
          setConfig: {
            theme: getGiscusTheme(theme)
          }
        }
      }
      iframe.contentWindow.postMessage(message, 'https://giscus.app')
    }
  }

  btf.addGlobalFn('themeChange', changeGiscusTheme, 'giscus')

  if (isShuoshuo) {
    'Giscus' === 'Giscus'
      ? window.shuoshuoComment = { loadComment: loadGiscus }
      : window.loadOtherComment = loadGiscus
    return
  }

  if ('Giscus' === 'Giscus' || !false) {
    if (false) btf.loadComment(document.getElementById('giscus-wrap'), loadGiscus)
    else loadGiscus()
  } else {
    window.loadOtherComment = loadGiscus
  }
})()</script></div><script defer="defer" id="fluttering_ribbon" mobile="false" src="https://cdn.jsdelivr.net/npm/butterfly-extsrc/dist/canvas-fluttering-ribbon.min.js"></script><script async data-pjax src="//busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js"></script><div id="local-search"><div class="search-dialog"><nav class="search-nav"><span class="search-dialog-title">搜索</span><span id="loading-status"></span><button class="search-close-button"><i class="fas fa-times"></i></button></nav><div class="text-center" id="loading-database"><i class="fas fa-spinner fa-pulse"></i><span>  数据加载中</span></div><div class="search-wrap"><div id="local-search-input"><div class="local-search-box"><input class="local-search-box--input" placeholder="搜索文章" type="text"/></div></div><hr/><div id="local-search-results"></div><div id="local-search-stats-wrap"></div></div></div><div id="search-mask"></div><script src="/js/search/local-search.js"></script></div></div></body></html>