<!DOCTYPE html><html lang="zh-CN" data-theme="light"><head><meta charset="UTF-8"><meta http-equiv="X-UA-Compatible" content="IE=edge"><meta name="viewport" content="width=device-width, initial-scale=1.0,viewport-fit=cover"><title>17注释元素 | funtim的博客</title><meta name="author" content="funtim41@gmail.com"><meta name="copyright" content="funtim41@gmail.com"><meta name="format-detection" content="telephone=no"><meta name="theme-color" content="#ffffff"><meta name="description" content="注释元素本节介绍Revit注释元素，例如尺寸标注、文字注释、注释记号、标记和符号。 请注意：  尺寸标注是视图专有的图元，用于显示项目中的尺寸和距离。 为详图创建详图曲线。它们仅在绘制它们的视图中可见。它们通常绘制在模型视图上。 标签是用于标识图形中图元的注释。与标签关联的特性可以显示在明细表中。 AnnotationSymbol在加载到项目中时具有多个引线选项。  有关Revit Element">
<meta property="og:type" content="article">
<meta property="og:title" content="17注释元素">
<meta property="og:url" content="https://funtim41.github.io/2024/12/10/%E4%BA%8C%E5%BC%80%E6%8C%87%E5%8D%97/17%E6%B3%A8%E9%87%8A%E5%85%83%E7%B4%A0/">
<meta property="og:site_name" content="funtim的博客">
<meta property="og:description" content="注释元素本节介绍Revit注释元素，例如尺寸标注、文字注释、注释记号、标记和符号。 请注意：  尺寸标注是视图专有的图元，用于显示项目中的尺寸和距离。 为详图创建详图曲线。它们仅在绘制它们的视图中可见。它们通常绘制在模型视图上。 标签是用于标识图形中图元的注释。与标签关联的特性可以显示在明细表中。 AnnotationSymbol在加载到项目中时具有多个引线选项。  有关Revit Element">
<meta property="og:locale" content="zh_CN">
<meta property="og:image" content="https://funtim41.github.io/images/4stars.png">
<meta property="article:published_time" content="2024-12-10T04:22:47.000Z">
<meta property="article:modified_time" content="2024-12-29T07:31:06.905Z">
<meta property="article:author" content="funtim41@gmail.com">
<meta property="article:tag" content="Revit">
<meta name="twitter:card" content="summary">
<meta name="twitter:image" content="https://funtim41.github.io/images/4stars.png"><link rel="shortcut icon" href="/images/OIP.jfif"><link rel="canonical" href="https://funtim41.github.io/2024/12/10/%E4%BA%8C%E5%BC%80%E6%8C%87%E5%8D%97/17%E6%B3%A8%E9%87%8A%E5%85%83%E7%B4%A0/"><link rel="preconnect" href="//cdn.jsdelivr.net"/><link rel="stylesheet" href="/css/index.css"><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free/css/all.min.css"><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/node-snackbar/dist/snackbar.min.css" media="print" onload="this.media='all'"><script>
    (() => {
      
    const saveToLocal = {
      set: (key, value, ttl) => {
        if (!ttl) return
        const expiry = Date.now() + ttl * 86400000
        localStorage.setItem(key, JSON.stringify({ value, expiry }))
      },
      get: key => {
        const itemStr = localStorage.getItem(key)
        if (!itemStr) return undefined
        const { value, expiry } = JSON.parse(itemStr)
        if (Date.now() > expiry) {
          localStorage.removeItem(key)
          return undefined
        }
        return value
      }
    }

    window.btf = {
      saveToLocal,
      getScript: (url, attr = {}) => new Promise((resolve, reject) => {
        const script = document.createElement('script')
        script.src = url
        script.async = true
        Object.entries(attr).forEach(([key, val]) => script.setAttribute(key, val))
        script.onload = script.onreadystatechange = () => {
          if (!script.readyState || /loaded|complete/.test(script.readyState)) resolve()
        }
        script.onerror = reject
        document.head.appendChild(script)
      }),
      getCSS: (url, id) => new Promise((resolve, reject) => {
        const link = document.createElement('link')
        link.rel = 'stylesheet'
        link.href = url
        if (id) link.id = id
        link.onload = link.onreadystatechange = () => {
          if (!link.readyState || /loaded|complete/.test(link.readyState)) resolve()
        }
        link.onerror = reject
        document.head.appendChild(link)
      }),
      addGlobalFn: (key, fn, name = false, parent = window) => {
        if (!false && key.startsWith('pjax')) return
        const globalFn = parent.globalFn || {}
        globalFn[key] = globalFn[key] || {}
        globalFn[key][name || Object.keys(globalFn[key]).length] = fn
        parent.globalFn = globalFn
      }
    }
  
      
      const activateDarkMode = () => {
        document.documentElement.setAttribute('data-theme', 'dark')
        if (document.querySelector('meta[name="theme-color"]') !== null) {
          document.querySelector('meta[name="theme-color"]').setAttribute('content', '#0d0d0d')
        }
      }
      const activateLightMode = () => {
        document.documentElement.setAttribute('data-theme', 'light')
        if (document.querySelector('meta[name="theme-color"]') !== null) {
          document.querySelector('meta[name="theme-color"]').setAttribute('content', '#ffffff')
        }
      }

      btf.activateDarkMode = activateDarkMode
      btf.activateLightMode = activateLightMode

      const theme = saveToLocal.get('theme')
    
          theme === 'dark' ? activateDarkMode() : theme === 'light' ? activateLightMode() : null
        
      
      const asideStatus = saveToLocal.get('aside-status')
      if (asideStatus !== undefined) {
        document.documentElement.classList.toggle('hide-aside', asideStatus === 'hide')
      }
    
      
    const detectApple = () => {
      if (/iPad|iPhone|iPod|Macintosh/.test(navigator.userAgent)) {
        document.documentElement.classList.add('apple')
      }
    }
    detectApple()
  
    })()
  </script><script>const GLOBAL_CONFIG = {
  root: '/',
  algolia: undefined,
  localSearch: {"path":"/search.xml","preload":false,"top_n_per_article":1,"unescape":false,"languages":{"hits_empty":"未找到符合您查询的内容：${query}","hits_stats":"共找到 ${hits} 篇文章"}},
  translate: undefined,
  highlight: {"plugin":"highlight.js","highlightCopy":true,"highlightLang":true,"highlightHeightLimit":false,"highlightFullpage":false,"highlightMacStyle":false},
  copy: {
    success: '复制成功',
    error: '复制失败',
    noSupport: '浏览器不支持'
  },
  relativeDate: {
    homepage: false,
    post: false
  },
  runtime: '',
  dateSuffix: {
    just: '刚刚',
    min: '分钟前',
    hour: '小时前',
    day: '天前',
    month: '个月前'
  },
  copyright: {"limitCount":150,"languages":{"author":"作者: funtim41@gmail.com","link":"链接: ","source":"来源: funtim的博客","info":"著作权归作者所有。商业转载请联系作者获得授权，非商业转载请注明出处。"}},
  lightbox: 'null',
  Snackbar: {"chs_to_cht":"已切换为繁体中文","cht_to_chs":"已切换为简体中文","day_to_night":"已切换为深色模式","night_to_day":"已切换为浅色模式","bgLight":"#49b1f5","bgDark":"#1f1f1f","position":"bottom-left"},
  infinitegrid: {
    js: 'https://cdn.jsdelivr.net/npm/@egjs/infinitegrid/dist/infinitegrid.min.js',
    buttonText: '加载更多'
  },
  isPhotoFigcaption: false,
  islazyload: false,
  isAnchor: true,
  percent: {
    toc: true,
    rightside: true,
  },
  autoDarkmode: false
}</script><script id="config-diff">var GLOBAL_CONFIG_SITE = {
  title: '17注释元素',
  isPost: true,
  isHome: false,
  isHighlightShrink: false,
  isToc: true,
  isShuoshuo: false
}</script><link rel="stylesheet" href="/css/bar.css"><meta name="generator" content="Hexo 7.3.0"></head><body><div id="web_bg" style="background: Color(#995a82);"></div><div id="sidebar"><div id="menu-mask"></div><div id="sidebar-menus"><div class="avatar-img text-center"><img src="/images/4stars.png" onerror="onerror=null;src='/img/friend_404.gif'" alt="avatar"/></div><div class="site-data text-center"><a href="/archives/"><div class="headline">文章</div><div class="length-num">51</div></a><a href="/tags/"><div class="headline">标签</div><div class="length-num">2</div></a><a href="/categories/"><div class="headline">分类</div><div class="length-num">3</div></a></div><div class="menus_items"><div class="menus_item"><a class="site-page" href="/"><i class="fa-fw fas fa-home"></i><span> Home</span></a></div><div class="menus_item"><a class="site-page" href="/archives/"><i class="fa-fw fas fa-archive"></i><span> Timeline</span></a></div><div class="menus_item"><a class="site-page" href="/tags/"><i class="fa-fw fas fa-tags"></i><span> Tags</span></a></div><div class="menus_item"><a class="site-page" href="/categories/"><i class="fa-fw fas fa-folder-open"></i><span> Categories</span></a></div><div class="menus_item"><a class="site-page" href="/Links/"><i class="fa-fw fas fa-link"></i><span> Links</span></a></div><div class="menus_item"><a class="site-page" href="/about/"><i class="fa-fw fas fa-heart"></i><span> About</span></a></div></div></div></div><div class="post" id="body-wrap"><header class="post-bg fixed" id="page-header" style="background-image: url(/images/topback.jpg);"><nav id="nav"><span id="blog-info"><a class="nav-site-title" href="/"><img class="site-icon" src="/images/OIP.jfif" alt="Logo"><span class="site-name">funtim的博客</span></a><a class="nav-page-title" href="/"><span class="site-name">17注释元素</span></a></span><div id="menus"><div id="search-button"><span class="site-page social-icon search"><i class="fas fa-search fa-fw"></i><span> 搜索</span></span></div><div class="menus_items"><div class="menus_item"><a class="site-page" href="/"><i class="fa-fw fas fa-home"></i><span> Home</span></a></div><div class="menus_item"><a class="site-page" href="/archives/"><i class="fa-fw fas fa-archive"></i><span> Timeline</span></a></div><div class="menus_item"><a class="site-page" href="/tags/"><i class="fa-fw fas fa-tags"></i><span> Tags</span></a></div><div class="menus_item"><a class="site-page" href="/categories/"><i class="fa-fw fas fa-folder-open"></i><span> Categories</span></a></div><div class="menus_item"><a class="site-page" href="/Links/"><i class="fa-fw fas fa-link"></i><span> Links</span></a></div><div class="menus_item"><a class="site-page" href="/about/"><i class="fa-fw fas fa-heart"></i><span> About</span></a></div></div><div id="toggle-menu"><span class="site-page"><i class="fas fa-bars fa-fw"></i></span></div></div></nav><div id="post-info"><h1 class="post-title">17注释元素</h1><div id="post-meta"><div class="meta-firstline"><span class="post-meta-date"><i class="far fa-calendar-alt fa-fw post-meta-icon"></i><span class="post-meta-label">发表于</span><time class="post-meta-date-created" datetime="2024-12-10T04:22:47.000Z" title="发表于 2024-12-10 12:22:47">2024-12-10</time><span class="post-meta-separator">|</span><i class="fas fa-history fa-fw post-meta-icon"></i><span class="post-meta-label">更新于</span><time class="post-meta-date-updated" datetime="2024-12-29T07:31:06.905Z" title="更新于 2024-12-29 15:31:06">2024-12-29</time></span><span class="post-meta-categories"><span class="post-meta-separator">|</span><i class="fas fa-inbox fa-fw post-meta-icon"></i><a class="post-meta-categories" href="/categories/Revit%E4%BA%8C%E6%AC%A1%E5%BC%80%E5%8F%91%E4%BA%BA%E5%91%98%E6%8C%87%E5%8D%97/">Revit二次开发人员指南</a></span></div><div class="meta-secondline"><span class="post-meta-separator">|</span><span class="post-meta-pv-cv" id="" data-flag-title=""><i class="far fa-eye fa-fw post-meta-icon"></i><span class="post-meta-label">浏览量:</span><span id="busuanzi_value_page_pv"><i class="fa-solid fa-spinner fa-spin"></i></span></span></div></div></div></header><main class="layout" id="content-inner"><div id="post"><article class="container post-content" id="article-container"><h1 id="注释元素"><a href="#注释元素" class="headerlink" title="注释元素"></a><a target="_blank" rel="noopener" href="https://help.autodesk.com/view/RVT/2018/ENU/?guid=Revit_API_Revit_API_Developers_Guide_Revit_Geometric_Elements_Annotation_Elements_html">注释元素</a></h1><p>本节介绍Revit注释元素，例如尺寸标注、文字注释、注释记号、标记和符号。</p>
<p>请注意：</p>
<ul>
<li>尺寸标注是视图专有的图元，用于显示项目中的尺寸和距离。</li>
<li>为详图创建详图曲线。它们仅在绘制它们的视图中可见。它们通常绘制在模型视图上。</li>
<li>标签是用于标识图形中图元的注释。与标签关联的特性可以显示在明细表中。</li>
<li>AnnotationSymbol在加载到项目中时具有多个引线选项。</li>
</ul>
<p>有关Revit Element分类的详细信息，请参见元素要点。</p>
<h2 id="尺寸标注和约束"><a href="#尺寸标注和约束" class="headerlink" title="尺寸标注和约束"></a>尺寸标注和约束</h2><p>永久性尺寸标注和尺寸标注相关约束。</p>
<p>Dimension类表示永久性尺寸标注和与尺寸标注相关的约束元素。在UI中编辑元素时创建的临时尺寸标注不可访问。高程点和高程点坐标由SpotDimension类表示。</p>
<p>下面的代码示例在结尾处说明了如何区分永久性尺寸标注和约束元素。</p>
<p>代码区域16-1：区分永久性尺寸标注和约束</p>
<figure class="highlight c#"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br><span class="line">23</span><br><span class="line">24</span><br><span class="line">25</span><br><span class="line">26</span><br><span class="line">27</span><br><span class="line">28</span><br><span class="line">29</span><br><span class="line">30</span><br><span class="line">31</span><br><span class="line">32</span><br><span class="line">33</span><br><span class="line">34</span><br><span class="line">35</span><br><span class="line">36</span><br><span class="line">37</span><br><span class="line">38</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="keyword">public</span> <span class="keyword">void</span> <span class="title">GetInfo_Dimension</span>(<span class="params">Dimension dimension</span>)</span></span><br><span class="line">&#123;</span><br><span class="line">    <span class="built_in">string</span> message = <span class="string">&quot;Dimension : &quot;</span>;</span><br><span class="line">    <span class="comment">// Get Dimension name</span></span><br><span class="line">    message += <span class="string">&quot;\nDimension name is : &quot;</span> + dimension.Name;</span><br><span class="line"></span><br><span class="line">    <span class="comment">// Get Dimension Curve</span></span><br><span class="line">    Autodesk.Revit.DB.Curve curve = dimension.Curve;</span><br><span class="line">    <span class="keyword">if</span> (curve != <span class="literal">null</span> &amp;&amp; curve.IsBound)</span><br><span class="line">    &#123;</span><br><span class="line">        <span class="comment">// Get curve start point</span></span><br><span class="line">        message += <span class="string">&quot;\nCurve start point:(&quot;</span> + curve.GetEndPoint(<span class="number">0</span>).X + <span class="string">&quot;, &quot;</span></span><br><span class="line">                + curve.GetEndPoint(<span class="number">0</span>).Y + <span class="string">&quot;, &quot;</span> + curve.GetEndPoint(<span class="number">0</span>).Z + <span class="string">&quot;)&quot;</span>;</span><br><span class="line">        <span class="comment">// Get curve end point</span></span><br><span class="line">        message += <span class="string">&quot;; Curve end point:(&quot;</span> + curve.GetEndPoint(<span class="number">1</span>).X + <span class="string">&quot;, &quot;</span></span><br><span class="line">                + curve.GetEndPoint(<span class="number">1</span>).Y + <span class="string">&quot;, &quot;</span> + curve.GetEndPoint(<span class="number">1</span>).Z + <span class="string">&quot;)&quot;</span>;</span><br><span class="line">    &#125;</span><br><span class="line"></span><br><span class="line">    <span class="comment">// Get Dimension type name</span></span><br><span class="line">    message += <span class="string">&quot;\nDimension type name is : &quot;</span> + dimension.DimensionType.Name;</span><br><span class="line"></span><br><span class="line">    <span class="comment">// Get Dimension view name</span></span><br><span class="line">    message += <span class="string">&quot;\nDimension view name is : &quot;</span> + dimension.View.Name;</span><br><span class="line"></span><br><span class="line">    <span class="comment">// Get Dimension reference count</span></span><br><span class="line">    message += <span class="string">&quot;\nDimension references count is &quot;</span> + dimension.References.Size;</span><br><span class="line"></span><br><span class="line">    <span class="keyword">if</span> ((<span class="built_in">int</span>)BuiltInCategory.OST_Dimensions == dimension.Category.Id.IntegerValue)</span><br><span class="line">    &#123;</span><br><span class="line">        message += <span class="string">&quot;\nDimension is a permanent dimension.&quot;</span>;</span><br><span class="line">    &#125;</span><br><span class="line">    <span class="keyword">else</span> <span class="keyword">if</span> ((<span class="built_in">int</span>)BuiltInCategory.OST_Constraints == dimension.Category.Id.IntegerValue)</span><br><span class="line">    &#123;</span><br><span class="line">        message += <span class="string">&quot;\nDimension is a constraint element.&quot;</span>;</span><br><span class="line">    &#125;</span><br><span class="line"></span><br><span class="line">    TaskDialog.Show(<span class="string">&quot;Revit&quot;</span>,message);</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<h3 id="尺寸标注"><a href="#尺寸标注" class="headerlink" title="尺寸标注"></a>尺寸标注</h3><p>有五种永久尺寸标注：</p>
<ul>
<li>Linear dimension 线性尺寸标注</li>
<li>Radial dimension 半径尺寸标注</li>
<li>Diameter Dimension 直径尺寸标注</li>
<li>Angular dimension 角度尺寸标注</li>
<li>Arc length dimension 弧长尺寸标注</li>
</ul>
<p><img src="https://help.autodesk.com/cloudhelp/2018/ENU/Revit-API/images/Dims.png"></p>
<p>图66：永久尺寸标注</p>
<p>所有永久性尺寸标注的BuiltInCategory为OST_Dimensions。没有一种使用API区分四个维度的简单方法。</p>
<p>除半径尺寸标注和直径尺寸标注外，每个尺寸标注都有一条尺寸线。尺寸线可从始终未绑定的Dimension.Curve属性中获得。换句话说，尺寸线没有起点或终点。基于上一张图片：</p>
<ul>
<li>将为线性标注返回Line对象。</li>
<li>将为半径标注或角度标注返回弧对象。</li>
<li>径向尺寸标注返回空。</li>
<li>直径尺寸标注返回空。</li>
</ul>
<p><img src="https://help.autodesk.com/cloudhelp/2018/ENU/Revit-API/images/GUID-4C8DCD73-DFD8-4185-A1EA-2C890D176FBF-low.png"></p>
<p>图67：尺寸参考</p>
<p>如上图所示，通过选择几何参照来创建尺寸。几何参照在API中表示为Reference类。以下尺寸参照可从“参照”（References）属性中获得。有关参考的更多信息，请参见几何部分中的几何辅助程序类。</p>
<ul>
<li>半径和直径尺寸标注-返回曲线的一个参考对象</li>
<li>角度和弧长尺寸标注-返回两个参照对象。</li>
<li>线性尺寸标注-返回两个或多个参照对象。在下图中，线性标注有五个Reference对象。</li>
</ul>
<p><img src="https://help.autodesk.com/cloudhelp/2018/ENU/Revit-API/images/GUID-A976B817-2D4B-471B-BF79-27E9262A8A85-low.png"></p>
<p>图68：线性尺寸参考</p>
<p>与其他注释元素一样，尺寸标注也是视图专有的。它们仅显示在添加它们的视图中。Dimension.View属性返回特定的视图。</p>
<h3 id="约束元素"><a href="#约束元素" class="headerlink" title="约束元素"></a>约束元素</h3><p>具有类别约束的标注对象（BuitInCategory.OST_Constraints）表示两种与标注相关的约束：</p>
<ul>
<li>Linear and radial dimension constraints<br>线性和半径尺寸标注约束</li>
<li>Equality constraints 等式约束</li>
</ul>
<p>在下图中，两种锁定约束分别对应于线性标注和半径标注。在应用程序中，它们显示为带有绿色虚线的挂锁。(绿色虚线可从“尺Dimension.Curve”属性中获得。）线性标注约束和半径标注约束都从Dimension.References属性返回两个Reference对象。</p>
<p><img src="https://help.autodesk.com/cloudhelp/2018/ENU/Revit-API/images/GUID-370D4754-3BC7-4A6C-8531-41B7A5B424D9-low.png"></p>
<p>图69：线性和半径尺寸约束</p>
<p>约束图元不是视图专有的，可以显示在不同的视图中。因此，View属性总是返回null。在下图中，上一图中的约束元素在3D视图中也可见。</p>
<p><img src="https://help.autodesk.com/cloudhelp/2018/ENU/Revit-API/images/GUID-8365F25E-7304-413D-BABE-1C495BD8ADAD-low.png"></p>
<p>图70：3D视图中的线性和半径尺寸约束</p>
<p>虽然等分约束基于尺寸标注，但它们也由Dimension类表示。在API中，没有使用类别或类型区分线性标注约束和等式约束的直接方法。相等约束返回三个或更多引用，而线性尺寸约束返回两个或更多引用。</p>
<p><img src="https://help.autodesk.com/cloudhelp/2018/ENU/Revit-API/images/GUID-FB6F70CD-8913-4C3A-A036-2108550BA25C-low.png"></p>
<p>图71：等分约束</p>
<p>注意：并非所有约束元素都由Dimension类表示，但都属于约束（OST_Constraints）类别，如对齐约束。</p>
<h3 id="高程点标注"><a href="#高程点标注" class="headerlink" title="高程点标注"></a>高程点标注</h3><p>高程点坐标和高程点由SpotDimension类表示，并按类别区分。与永久性尺寸标注一样，高程点尺寸标注也是视图专有的。下表列出了每个高程点标注的类型和类别：</p>
<p>表35：点尺寸类型和类别</p>
<table>
<thead>
<tr>
<th><strong>Type 类型</strong></th>
<th><strong>Category 类别</strong></th>
</tr>
</thead>
<tbody><tr>
<td>Spot Coordinates 高程点坐标</td>
<td>OST_SpotCoordinates</td>
</tr>
<tr>
<td>Spot Elevations 高程点</td>
<td>OST_SpotElevations</td>
</tr>
</tbody></table>
<p><img src="https://help.autodesk.com/cloudhelp/2018/ENU/Revit-API/images/GUID-BDB09C60-D4AC-4F6A-8100-6BA2FA165228-low.png"></p>
<p>图72：SpotCoordinates和SpotElevations</p>
<p>可以将SpotDimension Location向下转换为LocationPoint，以便可以从LocationPoint.Point属性中获得点尺寸所指向的点坐标。SpotDimensions没有尺寸曲线，因此其Curve属性始终返回null。SpotDimension References属性返回一个Reference，表示高程点标注引用的点或边。* 若要控制文本和标记显示样式，请修改SpotDimension和SpotExpressionType参数。</p>
<p>对比下表对比了API中不同类型的维度和约束：</p>
<p>表36：Dimension类别对比</p>
<table>
<thead>
<tr>
<th>Dimension or Constraint</th>
<th>Dimension or Constraint</th>
<th>API Class</th>
<th>BuiltInCategory</th>
<th>Curve</th>
<th>Geometry Helper Classes</th>
<th>View</th>
<th>Location</th>
</tr>
</thead>
<tbody><tr>
<td>Permanent Dimension</td>
<td>linear dimension</td>
<td>Dimension</td>
<td>OST_Dimensions</td>
<td>A Line</td>
<td>&#x3D;2</td>
<td>Specific view</td>
<td>null</td>
</tr>
<tr>
<td>Permanent Dimension</td>
<td>radial dimension</td>
<td>Dimension</td>
<td>OST_Dimensions</td>
<td>Null</td>
<td>1</td>
<td>Specific view</td>
<td>null</td>
</tr>
<tr>
<td>Permanent Dimension</td>
<td>diameter dimension</td>
<td>Dimension</td>
<td>OST_Dimensions</td>
<td>Null</td>
<td>1</td>
<td>Specific view</td>
<td>null</td>
</tr>
<tr>
<td>Permanent Dimension</td>
<td>angular dimension</td>
<td>Dimension</td>
<td>OST_Dimensions</td>
<td>An Arc</td>
<td>2</td>
<td>Specific view</td>
<td>null</td>
</tr>
<tr>
<td>Permanent Dimension</td>
<td>arc length dimension</td>
<td>Dimension</td>
<td>OST_Dimensions</td>
<td>An Arc</td>
<td>2</td>
<td>Specific view</td>
<td>null</td>
</tr>
<tr>
<td>Dimension Constraint</td>
<td>linear dimension constraint</td>
<td>Dimension</td>
<td>OST_Constraints</td>
<td>An Arc</td>
<td>2</td>
<td></td>
<td>null</td>
</tr>
<tr>
<td>Dimension Constraint</td>
<td>angular dimension</td>
<td>Dimension</td>
<td>OST_Constraints</td>
<td>An Arc</td>
<td>2</td>
<td></td>
<td>null</td>
</tr>
<tr>
<td>Equality Constraint</td>
<td>Equality Constraint</td>
<td>Dimension</td>
<td>OST_Constraints</td>
<td>A Line</td>
<td>&#x3D;3</td>
<td></td>
<td>null</td>
</tr>
</tbody></table>
<h3 id="创建和删除"><a href="#创建和删除" class="headerlink" title="创建和删除"></a>创建和删除</h3><p>NewDimension（）方法在Creation.Document类中可用。此方法只能创建线性标注。</p>
<p>代码区域16-2：NewDimension（）</p>
<figure class="highlight c#"><table><tr><td class="gutter"><pre><span class="line">1</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="keyword">public</span> Dimension <span class="title">NewDimension</span> (<span class="params">View view, Line line, ReferenceArray references</span>)</span></span><br></pre></td></tr></table></figure>

<figure class="highlight c#"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="keyword">public</span> Dimension <span class="title">NewDimension</span> (<span class="params">View view, Line line, ReferenceArray references, </span></span></span><br><span class="line"><span class="params"><span class="function">DimensionType dimensionType</span>)</span></span><br></pre></td></tr></table></figure>

<p>使用NewDimension（）方法输入参数，可以定义可见的View、尺寸线和References（两个或多个）。但是，没有简单的方法将线性标注类型与其他类型区分开来。很少使用带有ExcisionType参数的重载NewDimension（）方法。 下面的代码演示如何使用NewDimension（）方法复制标注。</p>
<p>代码区域16-3：使用NewDimension（）复制标注</p>
<figure class="highlight c#"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="keyword">public</span> <span class="keyword">void</span> <span class="title">DuplicateDimension</span>(<span class="params">Document document, Dimension dimension</span>)</span></span><br><span class="line">&#123;</span><br><span class="line">        Line line = dimension.Curve <span class="keyword">as</span> Line;</span><br><span class="line">        <span class="keyword">if</span> (<span class="literal">null</span> != line)</span><br><span class="line">        &#123;</span><br><span class="line">                Autodesk.Revit.DB.View view = dimension.View;</span><br><span class="line">                ReferenceArray references = dimension.References;</span><br><span class="line">                Dimension newDimension = document.Create.NewDimension(view, line, references);</span><br><span class="line">        &#125;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<p>尽管只创建了线性标注，但您可以使用Document.Delete（）方法删除由Dimension和SpotDimension表示的所有标注和约束。 </p>
<p>标注文本操作 Dimension和ExpressionSegment类提供了类似的属性和方法，用于查询和调整文本相对于尺寸曲线的位置。 Dimension.Origin返回尺寸曲线中点的XYZ值，而ExpressionSegment.Origin将返回组成线段的直线的中点。 通过调用IsTextPositionAdjustable（）方法确定标注或标注段的文本位置是否可调，该方法将指示是否可以设置文本和引线位置。 使用属性TextPosition和LeaderEndPosition查询或修改文本或引线（标注或标注段）的位置。 通过调用ResetTextPosition（）方法将文本重置为其在尺寸上的默认位置。</p>
<p>注意：TextPosition和LeaderEndPosition不一定适用于所有标注（例如，标注样式为纵坐标时，使用相等约束的高程点标注、多段标注）。如果这些值不适用，它们将返回NULL，并且不允许设置值。</p>
<p>代码区域：重新定位标注文字</p>
<figure class="highlight c#"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br><span class="line">23</span><br><span class="line">24</span><br><span class="line">25</span><br><span class="line">26</span><br><span class="line">27</span><br><span class="line">28</span><br><span class="line">29</span><br><span class="line">30</span><br><span class="line">31</span><br><span class="line">32</span><br><span class="line">33</span><br><span class="line">34</span><br><span class="line">35</span><br><span class="line">36</span><br><span class="line">37</span><br></pre></td><td class="code"><pre><span class="line"><span class="comment">// Moves all of the text in this dimension one unit in the Y direction</span></span><br><span class="line"><span class="function"><span class="keyword">public</span> <span class="built_in">bool</span> <span class="title">DimensionTextReposition</span>(<span class="params">Dimension dimToModify</span>)</span></span><br><span class="line">&#123;</span><br><span class="line">    <span class="built_in">bool</span> modified = <span class="literal">false</span>;</span><br><span class="line">    <span class="keyword">if</span> (dimToModify == <span class="literal">null</span>)</span><br><span class="line">        <span class="keyword">return</span> <span class="literal">false</span>;</span><br><span class="line"></span><br><span class="line">    <span class="comment">// Check to see if we have a non-multisegment dimension and if text position is adjustable</span></span><br><span class="line">    <span class="keyword">if</span> (dimToModify.NumberOfSegments == <span class="number">0</span> &amp;&amp; dimToModify.IsTextPositionAdjustable())</span><br><span class="line">    &#123;</span><br><span class="line">        <span class="comment">// Get the current text XYZ position</span></span><br><span class="line">        XYZ currentTextPosition = dimToModify.TextPosition;</span><br><span class="line">        <span class="comment">// Calculate a new XYZ position by transforming the current text position</span></span><br><span class="line">        XYZ newTextPosition = Transform.CreateTranslation(<span class="keyword">new</span> XYZ(<span class="number">0.0</span>, <span class="number">1.0</span>, <span class="number">0.0</span>)).OfPoint(currentTextPosition);</span><br><span class="line">        <span class="comment">// Set the new text position</span></span><br><span class="line">        dimToModify.TextPosition = newTextPosition;</span><br><span class="line"></span><br><span class="line">        modified = <span class="literal">true</span>;</span><br><span class="line">    &#125;</span><br><span class="line">    <span class="keyword">else</span> <span class="keyword">if</span> (dimToModify.NumberOfSegments &gt; <span class="number">0</span>)</span><br><span class="line">    &#123;</span><br><span class="line">        <span class="keyword">foreach</span> (DimensionSegment currentSegment <span class="keyword">in</span> dimToModify.Segments)</span><br><span class="line">        &#123;</span><br><span class="line">            <span class="keyword">if</span> (currentSegment != <span class="literal">null</span> &amp;&amp; currentSegment.IsTextPositionAdjustable())</span><br><span class="line">            &#123;</span><br><span class="line">                modified = <span class="literal">true</span>;</span><br><span class="line">                <span class="comment">// Get the current text XYZ position</span></span><br><span class="line">                XYZ currentTextPosition = currentSegment.TextPosition;</span><br><span class="line">                <span class="comment">// Calculate a new XYZ position by transforming the current text position</span></span><br><span class="line">                XYZ newTextPosition = Transform.CreateTranslation(<span class="keyword">new</span> XYZ(<span class="number">0</span>, <span class="number">1</span>, <span class="number">0</span>)).OfPoint(currentTextPosition);</span><br><span class="line">                <span class="comment">// Set the new text position for the segment&#x27;s text</span></span><br><span class="line">                currentSegment.TextPosition = newTextPosition;</span><br><span class="line">            &#125;</span><br><span class="line">        &#125;</span><br><span class="line">    &#125;</span><br><span class="line">    <span class="keyword">return</span> modified;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<h2 id="详图线"><a href="#详图线" class="headerlink" title="详图线"></a>详图线</h2><p>详图线是一种重要的详图构件，通常用于详图或绘图视图中。可以在DetailCurve类及其派生类中访问详图曲线。</p>
<p>DetailCurve与其他注释元素一样，是视图专有的。但是，没有DetailCurve.View属性。创建详图曲线时，必须将详图曲线与模型曲线视图进行比较。</p>
<p>代码区域16-4：NewDetailCurve（）和NewModelCurve（）</p>
<figure class="highlight c#"><table><tr><td class="gutter"><pre><span class="line">1</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="keyword">public</span> DetailCurve <span class="title">NewDetailCurve</span> (<span class="params">View, Curve, SketchPlane</span>)</span></span><br></pre></td></tr></table></figure>

<figure class="highlight c#"><table><tr><td class="gutter"><pre><span class="line">1</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="keyword">public</span> ModelCurve <span class="title">NewModelCurve</span> (<span class="params">Curve, SketchPlane</span>)</span></span><br></pre></td></tr></table></figure>

<p>通常，只有二维视图（如平面视图和立面视图）是可接受的，否则将引发异常。</p>
<p>除了与视图相关的功能外，DetailCurve与ModelCurve非常相似。有关ModelCurve属性和用法的详细信息，请参见“草图”部分中的ModelCurve。</p>
<h2 id="标签"><a href="#标签" class="headerlink" title="标签"></a>标签</h2><p>标签是用于标识图形元素的注释。API公开IndependentTag和RoomTag类，以涵盖Revit应用程序中使用的大多数标签。有关RoomTag的更多详细信息，请参阅房间。</p>
<p>注意：IndependentTag类表示Revit中的标签图元和其他特定标记，如注释标签、梁系统标签、电子电路符号等。在Revit内部代码中，特定标记具有从IndependentTag派生的相应类。因此，特定功能不会由API公开，并且无法使用IndependentTag.xml创建。它们可按以下类别加以区分：</p>
<p>表37：标签名称和类别</p>
<table>
<thead>
<tr>
<th><strong>Tag Name 标记名称</strong></th>
<th><strong>BuiltInCategory</strong></th>
</tr>
</thead>
<tbody><tr>
<td>Keynote Tag</td>
<td>OST_KeynoteTags</td>
</tr>
<tr>
<td>Beam System Tag</td>
<td>OST_BeamSystemTags</td>
</tr>
<tr>
<td>Electronic Circuit Tag</td>
<td>OST_ElectricalCircuitTags</td>
</tr>
<tr>
<td>Span Direction Tag</td>
<td>OST_SpanDirectionSymbol</td>
</tr>
<tr>
<td>Path Reinforcement Span Tag</td>
<td>OST_PathReinSpanSymbol</td>
</tr>
<tr>
<td>Rebar System Span Tag</td>
<td>OST_IOSRebarSystemSpanSymbolCtrl</td>
</tr>
</tbody></table>
<p>族库中的每个类别都有一个预先制作的标记。某些标记会随默认的Revit应用程序样板自动加载，而其他标记则会手动加载。如果主体元素是使用“按类别”选项创建的，则IndependentTag对象将根据主体元素返回不同的类别。例如，Wall和Floor IndependentTag分别是OST_WallTags和OST_FloorTags。</p>
<p>如果标记是使用“Multi-Category ”或“Material”样式创建的，则它们的类别分别为OST_MultiCategoryTags和OST_MaterialTags。</p>
<p>请注意IndependentTag.Create只在2D视图或锁定的3D视图中工作，否则将引发异常。下面的代码是创建IndependentTag的示例。当标高视图为活动视图时运行该命令。</p>
<p>注意：您无法直接更改IndependentTag中显示的文本。您需要修改用于在要标记的图元的族类型中填充标记文字的参数。在下面的示例中，该参数为“Type Mark”，但可以在Revit UI的族编辑器中更改此设置。</p>
<p>代码区域16-5：创建IndependentTag</p>
<figure class="highlight c#"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br><span class="line">23</span><br><span class="line">24</span><br><span class="line">25</span><br><span class="line">26</span><br><span class="line">27</span><br><span class="line">28</span><br><span class="line">29</span><br><span class="line">30</span><br><span class="line">31</span><br><span class="line">32</span><br><span class="line">33</span><br><span class="line">34</span><br><span class="line">35</span><br><span class="line">36</span><br><span class="line">37</span><br><span class="line">38</span><br><span class="line">39</span><br><span class="line">40</span><br><span class="line">41</span><br><span class="line">42</span><br><span class="line">43</span><br><span class="line">44</span><br><span class="line">45</span><br><span class="line">46</span><br><span class="line">47</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="keyword">private</span> IndependentTag <span class="title">CreateIndependentTag</span>(<span class="params">Autodesk.Revit.DB.Document document, Reference reference</span>)</span></span><br><span class="line">&#123;</span><br><span class="line">    <span class="comment">// make sure active view is not a 3D view</span></span><br><span class="line">    Autodesk.Revit.DB.View view = document.ActiveView;</span><br><span class="line">    <span class="keyword">if</span> (view <span class="keyword">is</span> View3D)</span><br><span class="line">        <span class="keyword">return</span> <span class="literal">null</span>;</span><br><span class="line"></span><br><span class="line">    <span class="comment">// define tag mode and tag orientation for new tag</span></span><br><span class="line">    TagMode tagMode = TagMode.TM_ADDBY_CATEGORY;</span><br><span class="line">    TagOrientation tagorn = TagOrientation.Horizontal;</span><br><span class="line"></span><br><span class="line">    <span class="comment">// Add the tag to the middle of the wall</span></span><br><span class="line">    Wall wall = document.GetElement(reference) <span class="keyword">as</span> Wall;</span><br><span class="line">    <span class="keyword">if</span> (wall == <span class="literal">null</span>)</span><br><span class="line">        <span class="keyword">return</span> <span class="literal">null</span>;</span><br><span class="line"></span><br><span class="line">    LocationCurve wallLoc = wall.Location <span class="keyword">as</span> LocationCurve;</span><br><span class="line">    XYZ wallStart = wallLoc.Curve.GetEndPoint(<span class="number">0</span>);</span><br><span class="line">    XYZ wallEnd = wallLoc.Curve.GetEndPoint(<span class="number">1</span>);</span><br><span class="line">    XYZ wallMid = wallLoc.Curve.Evaluate(<span class="number">0.5</span>, <span class="literal">true</span>);</span><br><span class="line"></span><br><span class="line">    IndependentTag newTag = IndependentTag.Create(document, view.Id, reference, <span class="literal">true</span>, tagMode, tagorn, wallMid);</span><br><span class="line">    <span class="keyword">if</span> (<span class="literal">null</span> == newTag)</span><br><span class="line">    &#123;</span><br><span class="line">        <span class="keyword">throw</span> <span class="keyword">new</span> Exception(<span class="string">&quot;Create IndependentTag Failed.&quot;</span>);</span><br><span class="line">    &#125;</span><br><span class="line"></span><br><span class="line">    <span class="comment">// newTag.TagText is read-only, so we change the Type Mark type parameter to </span></span><br><span class="line">    <span class="comment">// set the tag text.  The label parameter for the tag family determines</span></span><br><span class="line">    <span class="comment">// what type parameter is used for the tag text.</span></span><br><span class="line"></span><br><span class="line">    WallType type = wall.WallType;</span><br><span class="line"></span><br><span class="line">    Parameter foundParameter = type.LookupParameter(<span class="string">&quot;Type Mark&quot;</span>);</span><br><span class="line">    <span class="built_in">bool</span> result = foundParameter.Set(<span class="string">&quot;Hello&quot;</span>);</span><br><span class="line"></span><br><span class="line">    <span class="comment">// set leader mode free</span></span><br><span class="line">    <span class="comment">// otherwise leader end point move with elbow point</span></span><br><span class="line"></span><br><span class="line">    newTag.LeaderEndCondition = LeaderEndCondition.Free;</span><br><span class="line">    XYZ elbowPnt = wallMid + <span class="keyword">new</span> XYZ(<span class="number">5.0</span>, <span class="number">5.0</span>, <span class="number">0.0</span>);</span><br><span class="line">    newTag.LeaderElbow = elbowPnt;</span><br><span class="line">    XYZ headerPnt = wallMid + <span class="keyword">new</span> XYZ(<span class="number">10.0</span>, <span class="number">10.0</span>, <span class="number">0.0</span>);</span><br><span class="line">    newTag.TagHeadPosition = headerPnt;</span><br><span class="line"></span><br><span class="line">    <span class="keyword">return</span> newTag;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<p><img src="https://help.autodesk.com/cloudhelp/2018/ENU/Revit-API/images/GUID-6FE76534-FEA8-4573-A2D7-747AB527B335-low.png"></p>
<p>图74：使用示例代码创建IndependentTag</p>
<h2 id="文本"><a href="#文本" class="headerlink" title="文本"></a>文本</h2><p>可以从TextNote类访问文本和关联的引线。注意TextNote可以包含纯文本或格式化文本。重载的TextNote.Create（）方法提供了用于创建展开和换行文本注释元素的选项。文本内容区域的宽度可以在创建时指定，但受基于文本及其类型的属性的最小和最大宽度的限制。从TextElement继承的重载方法GetMinimumAllowedWidth（）和GetMaximumAllowedWidth（）返回特定TextNote或给定文档和文本类型ID的约束。</p>
<p>下面的示例在用户指定的点处使用给定的宽度和TextNoteOptions创建一个新的TextNote。</p>
<p>代码区域：创建文本注释</p>
<figure class="highlight c#"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br><span class="line">23</span><br><span class="line">24</span><br><span class="line">25</span><br><span class="line">26</span><br><span class="line">27</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="keyword">public</span> TextNote <span class="title">AddNewTextNote</span>(<span class="params">UIDocument uiDoc</span>)</span></span><br><span class="line">&#123;</span><br><span class="line">    Document doc = uiDoc.Document;</span><br><span class="line">    XYZ textLoc = uiDoc.Selection.PickPoint(<span class="string">&quot;Pick a point for sample text.&quot;</span>);</span><br><span class="line">    ElementId defaultTextTypeId = doc.GetDefaultElementTypeId(ElementTypeGroup.TextNoteType);</span><br><span class="line">    <span class="built_in">double</span> noteWidth = <span class="number">.2</span>;</span><br><span class="line"></span><br><span class="line">    <span class="comment">// make sure note width works for the text type</span></span><br><span class="line">    <span class="built_in">double</span> minWidth = TextNote.GetMinimumAllowedWidth(doc, defaultTextTypeId);</span><br><span class="line">    <span class="built_in">double</span> maxWidth = TextNote.GetMaximumAllowedWidth(doc, defaultTextTypeId);</span><br><span class="line">    <span class="keyword">if</span> (noteWidth &lt; minWidth)</span><br><span class="line">    &#123;</span><br><span class="line">        noteWidth = minWidth;</span><br><span class="line">    &#125;</span><br><span class="line">    <span class="keyword">else</span> <span class="keyword">if</span> (noteWidth &gt; maxWidth)</span><br><span class="line">    &#123;</span><br><span class="line">        noteWidth = maxWidth;</span><br><span class="line">    &#125;</span><br><span class="line"></span><br><span class="line">    TextNoteOptions opts = <span class="keyword">new</span> TextNoteOptions(defaultTextTypeId);</span><br><span class="line">    opts.HorizontalAlignment = HorizontalTextAlignment.Left;</span><br><span class="line">    opts.Rotation = Math.PI / <span class="number">4</span>;</span><br><span class="line"></span><br><span class="line">    TextNote textNote = TextNote.Create(doc, doc.ActiveView.Id, textLoc, noteWidth, <span class="string">&quot;New sample text&quot;</span>, opts);</span><br><span class="line"></span><br><span class="line">    <span class="keyword">return</span> textNote;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<p>无论TextNote具有纯文本还是格式化文本，始终可以从TextNote.Text属性检索未格式化的文本。</p>
<p>格式化文本 当第一次创建时，TextNote将具有纯文本。使用TextNote. GetNotedText（）方法获取TextNote的NotedText对象。类可以用于对文本应用各种格式，如粗体、下划线、上标或全部大写。在使用修改后的TextText调用SetSetNotedText（）之前，TextNote不会更新。 可以使用TextRange全部或部分地格式化已删除文本中的文本。TextRange基于TextedText对象中的文本指定起始索引和长度。当格式化方法（如SetItalicStatus（）或SetAllCapsStatus（））的重载使用TextRange时，将只修改该范围内的字符。TextRange可以使用其构造函数显式定义，也可以使用FormattedText.Find（）方法检索以获取给定搜索字符串的范围。Find（）方法指定搜索的开始索引，以及是否匹配搜索字符串的大小写或是否进行全词搜索。如果在搜索字符串中找不到文本，或者如果给定的起始索引超出了整个文本的长度，则将返回一个空的TextRange。在使用返回的范围设置文本格式之前，请确保该范围不为空，以避免异常。 下面的示例演示如何设置TextNote中的文本格式并将其设置回TextNote。它使用Find（）方法对文本中的特定单词加粗体和下划线。</p>
<p>代码区域：设置TextNote中的文本格式</p>
<figure class="highlight c#"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br><span class="line">23</span><br><span class="line">24</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="keyword">public</span> <span class="keyword">void</span> <span class="title">FormatText</span>(<span class="params">TextNote textNote</span>)</span></span><br><span class="line">&#123;</span><br><span class="line">    <span class="comment">// TextNote created with &quot;New sample text&quot;</span></span><br><span class="line">    FormattedText formatText = textNote.GetFormattedText();</span><br><span class="line"></span><br><span class="line">    <span class="comment">// italicize &quot;New&quot;</span></span><br><span class="line">    TextRange range = <span class="keyword">new</span> TextRange(<span class="number">0</span>, <span class="number">3</span>);</span><br><span class="line">    formatText.SetItalicStatus(range, <span class="literal">true</span>);</span><br><span class="line"></span><br><span class="line">    <span class="comment">// make &quot;sample&quot; bold</span></span><br><span class="line">    range = formatText.Find(<span class="string">&quot;sample&quot;</span>, <span class="number">0</span>, <span class="literal">false</span>, <span class="literal">true</span>);</span><br><span class="line">    <span class="keyword">if</span> (range.Length &gt; <span class="number">0</span>)</span><br><span class="line">        formatText.SetBoldStatus(range, <span class="literal">true</span>);</span><br><span class="line"></span><br><span class="line">    <span class="comment">// make &quot;text&quot; underlined</span></span><br><span class="line">    range = formatText.Find(<span class="string">&quot;text&quot;</span>, <span class="number">0</span>, <span class="literal">false</span>, <span class="literal">true</span>);</span><br><span class="line">    <span class="keyword">if</span> (range.Length &gt; <span class="number">0</span>)</span><br><span class="line">        formatText.SetUnderlineStatus(range, <span class="literal">true</span>);</span><br><span class="line"></span><br><span class="line">    <span class="comment">// make all text uppercase</span></span><br><span class="line">    formatText.SetAllCapsStatus(<span class="literal">true</span>);</span><br><span class="line"></span><br><span class="line">    textNote.SetFormattedText(formatText);</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<p>可以将新文本添加到已添加文本对象中的现有文本中。如果使用了具有TextRange参数的重载，SetPlainText（）方法将替换某些现有文本，否则将替换整个文本。若要插入文本而不替换现有文本，请使用Length为0的TextRange。新文本将插入到TextRange.Start属性指定的索引处。请注意，插入文本时，它可能会选择相邻文本的格式，类似于将未格式化的文本粘贴到Word文档中将导致文本具有插入点的当前格式。如果格式设置已经应用于整个multitedText，如上面示例中的SetAllCapsStatus（true）调用，则该格式设置将应用于插入的任何新文本。 在下面的示例中，通过首先查找当前文本的结尾并将其设置为要添加的范围的开始，新文本将被追加到现有文本的结尾。它还演示了如何创建一个列表（可以是项目符号，编号或字母）。请注意，它还为新文本的范围调用GetAllCapsStatus（），并在状态不是“大写状态.无”（其他选项是“全部”和“混合”）时关闭大写。</p>
<p>代码区域：插入新文本</p>
<figure class="highlight c#"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br><span class="line">23</span><br><span class="line">24</span><br><span class="line">25</span><br><span class="line">26</span><br><span class="line">27</span><br><span class="line">28</span><br><span class="line">29</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="keyword">public</span> <span class="keyword">void</span> <span class="title">AppendText</span>(<span class="params">TextNote textNote</span>)</span></span><br><span class="line">&#123;</span><br><span class="line">    FormattedText formatText = textNote.GetFormattedText();</span><br><span class="line"></span><br><span class="line">    TextRange range = formatText.AsTextRange();</span><br><span class="line"></span><br><span class="line">    range.Start = range.End - <span class="number">1</span>;</span><br><span class="line">    <span class="comment">// set Length to 0 to insert</span></span><br><span class="line">    range.Length = <span class="number">0</span>;</span><br><span class="line">    <span class="built_in">string</span> someNewText = <span class="string">&quot;\rThis is a new paragraph\vThis is a new line without a paragraph break\r&quot;</span>;</span><br><span class="line">    formatText.SetPlainText(range, someNewText);</span><br><span class="line"></span><br><span class="line">    <span class="comment">// get range for entire text</span></span><br><span class="line">    range = formatText.AsTextRange();</span><br><span class="line">    range.Start = range.End - <span class="number">1</span>;</span><br><span class="line">    range.Length = <span class="number">0</span>;</span><br><span class="line">    <span class="built_in">string</span> someListText = <span class="string">&quot;\rBulleted List item 1\rItem 2\vSecond line for Item 2\rThird bullet point&quot;</span>;</span><br><span class="line">    formatText.SetPlainText(range, someListText);</span><br><span class="line">    range.Start++;</span><br><span class="line">    range.Length = someListText.Length;</span><br><span class="line">    formatText.SetListType(range, ListType.Bullet);</span><br><span class="line"></span><br><span class="line">    <span class="keyword">if</span> (formatText.GetAllCapsStatus(range) != FormatStatus.None)</span><br><span class="line">    &#123;</span><br><span class="line">        formatText.SetAllCapsStatus(range, <span class="literal">false</span>);</span><br><span class="line">    &#125;</span><br><span class="line"></span><br><span class="line">    textNote.SetFormattedText(formatText);</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<p>上面的代码显示了如何使用\r创建换行符，使用\v创建不打断段落的垂直制表符。在项目符号列表的文本中，“\v”用于创建两行项目符号。仅在使用“\r”时才插入新项目符号。 </p>
<p>文本编辑器 TextEditorOptions类可用于控制Revit中文本编辑器的外观和功能。这些设置保存在Revit.ini文件中，不与文档绑定。</p>
<p>代码区域：设置文本编辑器选项</p>
<figure class="highlight c#"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="keyword">public</span> <span class="keyword">void</span> <span class="title">SetEditorOptions</span>()</span></span><br><span class="line">&#123;</span><br><span class="line">    TextEditorOptions editorOptions = TextEditorOptions.GetTextEditorOptions();</span><br><span class="line">    editorOptions.ShowBorder = <span class="literal">false</span>;</span><br><span class="line">    editorOptions.ShowOpaqueBackground = <span class="literal">true</span>;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<h3 id="引线"><a href="#引线" class="headerlink" title="引线"></a>引线</h3><p>Revit支持两种引线：直线引线和圆弧引线。可以使用AddLeader（）方法将引线添加到TextNote，并使用TextNoteLeaderType枚举类型指定引线类型：</p>
<p>表39：引线类型</p>
<table>
<thead>
<tr>
<th><strong>Function 功能</strong></th>
<th><strong>Member Name 成员名称</strong></th>
</tr>
</thead>
<tbody><tr>
<td><img src="https://help.autodesk.com/cloudhelp/2018/ENU/Revit-API/images/GUID-0A443B27-ACDB-401E-8486-62165414529F-low.png" alt="img"> -添加右弧引线</td>
<td>TNLT_ARC_R</td>
</tr>
<tr>
<td><img src="https://help.autodesk.com/cloudhelp/2018/ENU/Revit-API/images/GUID-EE3246C4-B4F8-443D-9958-66CE5E62BB12-low.png" alt="img"> -添加左弧引线</td>
<td>TNLT_ARC_L</td>
</tr>
<tr>
<td><img src="https://help.autodesk.com/cloudhelp/2018/ENU/Revit-API/images/GUID-0D7DA193-EC77-4E99-A864-CA1E69BB3A62-low.png" alt="img"> -添加右引线。</td>
<td>TNLT_STRAIGHT_R</td>
</tr>
<tr>
<td><img src="https://help.autodesk.com/cloudhelp/2018/ENU/Revit-API/images/GUID-60BA1957-992C-468D-8459-7A26E418BF57-low.png" alt="img"> -添加左引线。</td>
<td>TNLT_STRAIGHT_L</td>
</tr>
</tbody></table>
<p>注意：直线引线和圆弧引线不能同时添加到文本类型。</p>
<p>TextNote.LeaderCount属性返回引线数，GetLeaders（）方法返回当前附加到文本组件的所有引线。LeaderLeftAttachment和LeaderRightAttachment指示引线在TextNote的相应侧上的附着位置。LeaderAttachment的选项有TopLine、MidPoint和BottomLine。使用RemoveLeaders（）方法从TextNote中删除所有引线。</p>
<h2 id="注释符号"><a href="#注释符号" class="headerlink" title="注释符号"></a>注释符号</h2><p>注释符号是应用于族的符号，用于在项目中唯一标识该族。</p>
<p><img src="https://help.autodesk.com/cloudhelp/2018/ENU/Revit-API/images/GUID-75864163-28D5-496D-9077-98DFECA07E75-low.png"></p>
<p>图76：带有两条引线的注释符号</p>
<h3 id="创建和删除-1"><a href="#创建和删除-1" class="headerlink" title="创建和删除"></a>创建和删除</h3><p>可以使用Creation.Document.NewFamilyInstance（）方法的以下重载创建注释符号：</p>
<p>代码区域16-6：创建新注释符号</p>
<figure class="highlight c#"><table><tr><td class="gutter"><pre><span class="line">1</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="keyword">public</span> FamilyInstance NewFamilyInstance <span class="title">Method</span> (<span class="params">XYZ origin, FamilySymbol symbol, View specView</span>)</span></span><br></pre></td></tr></table></figure>

<p>可以使用Document.Delete（）方法删除注释符号。 </p>
<p>添加和删除Leader 使用addLeader（）和removeLeader（）方法添加和删除引线。</p>
<p>代码区域16-7：使用addLeader（）和removeLeader（）</p>
<figure class="highlight c#"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="keyword">public</span> <span class="keyword">void</span> <span class="title">AddAndRemoveLeaders</span>(<span class="params">AnnotationSymbol symbol</span>)</span></span><br><span class="line">&#123;</span><br><span class="line">    <span class="comment">// check if there are any leaders currently attached, and remove them</span></span><br><span class="line">    IList leaders = symbol.GetLeaders();</span><br><span class="line"></span><br><span class="line">    <span class="keyword">if</span> (leaders != <span class="literal">null</span> &amp;&amp; leaders.Count &gt; <span class="number">0</span>)</span><br><span class="line">    &#123;</span><br><span class="line">        <span class="keyword">for</span> (<span class="built_in">int</span> i = leaders.Count; i &gt; <span class="number">0</span>; i--)</span><br><span class="line">        &#123;</span><br><span class="line">            symbol.removeLeader();</span><br><span class="line">        &#125;</span><br><span class="line">    &#125;</span><br><span class="line"></span><br><span class="line">    <span class="comment">// add one new leader instead</span></span><br><span class="line">    symbol.addLeader();&#125;</span><br></pre></td></tr></table></figure>

<h2 id="注：翻译自Revit-API-Developers-Guide"><a href="#注：翻译自Revit-API-Developers-Guide" class="headerlink" title="注：翻译自Revit API Developers Guide"></a><em><strong>注：</strong></em>翻译自<a target="_blank" rel="noopener" href="https://help.autodesk.com/view/RVT/2018/ENU/?guid=Revit_API_Revit_API_Developers_Guide_html">Revit API Developers Guide</a></h2></article><div class="tag_share"><div class="post-meta__tag-list"><a class="post-meta__tags" href="/tags/Revit/">Revit</a></div><div class="post-share"><div class="social-share" data-image="/images/4stars.png" data-sites="facebook,twitter,wechat,weibo,qq"></div><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/butterfly-extsrc/sharejs/dist/css/share.min.css" media="print" onload="this.media='all'"><script src="https://cdn.jsdelivr.net/npm/butterfly-extsrc/sharejs/dist/js/social-share.min.js" defer></script></div></div><nav class="pagination-post" id="pagination"><a class="pagination-related" href="/2024/12/10/RevitApi%E5%90%88%E9%9B%86/Autodesk.Revit.DB%20ReferenceIntersector/" title="Autodesk.Revit.DB ReferenceIntersector"><div class="cover" style="background: var(--default-bg-color)"></div><div class="info"><div class="info-1"><div class="info-item-1">上一篇</div><div class="info-item-2">Autodesk.Revit.DB ReferenceIntersector</div></div><div class="info-2"><div class="info-item-1">Autodesk.Revit.DB ReferenceIntersector用于查找和返回与从原点和方向创建的射线相交的元素的类。 语法1public class ReferenceIntersector : IDisposable    附注可以构造此类的实例，以返回与由原点和方向创建的射线，或者基于过滤和标志返回元素的子集。 调用者可以选择使用ElementFilter过滤结果，或者通过应用特定的可接受的元素。 调用方还可以指定要返回的对象的类型， 整个元素、几何体对象或其组合。 在所有情况下，要求调用者提供 用于评估的3D视图;输入视图上的视图和可见性设置将确定 返回特定元素（例如，此工具永远不会返回隐藏元素、 和几何图形位于视图剖面框之外的元素）。 该类配置为可以构建单个实例，并用于对多个不同光线进行多次评估。在同一个 ReferenceIntersector 上的调用之间，评估结果不会被保留。 该类还提供了一个选项，用于返回在Revit链接中遇到的图元结果。 当设置 FindReferencesInRevitLinks 标志...</div></div></div></a><a class="pagination-related" href="/2024/12/06/%E4%BA%8C%E5%BC%80%E6%8C%87%E5%8D%97/16%E5%9F%BA%E5%87%86%E5%92%8C%E4%BF%A1%E6%81%AF%E5%85%83%E7%B4%A0/" title="16基准和信息元素"><div class="cover" style="background: var(--default-bg-color)"></div><div class="info text-right"><div class="info-1"><div class="info-item-1">下一篇</div><div class="info-item-2">16基准和信息元素</div></div><div class="info-2"><div class="info-item-1">基准和信息元素本章介绍Revit中的基准元素和信息元素。  基准元素包括标高、轴网和模型线。 信息元素包括阶段、设计选项和EnergyDataSettings。  有关Revit图元分类的详细信息，请参见图元要素。 注：如果您需要更多信息，请参阅相关章节：  有关荷载基础、荷载工况、荷载组合、荷载性质和荷载用途，请参阅结构工程 对于模型曲线，请参阅草图 对于材质和填充图案，请参阅材质 有关能量数据设置，请参阅能量数据  本节中的页面  Levels 标高 Grids 轴网 Phase 阶段 Design Options 设计选项  标高标高是一个有限的水平面，用作以标高为主体的图元（如墙、屋顶、楼板和天花板）的参照。 在Revit Platform API中，Level类派生自DatumPlane类，而DatumPlane类派生自Element类。继承的Name属性用于检索Revit...</div></div></div></a></nav><div class="relatedPosts"><div class="headline"><i class="fas fa-thumbs-up fa-fw"></i><span>相关推荐</span></div><div class="relatedPosts-list"><a class="pagination-related" href="/2024/11/18/RevitApi%E5%90%88%E9%9B%86/Autodesk.RevitAddIns%20Namespace/" title="Autodesk.RevitAddIns Namespace"><div class="cover" style="background: var(--default-bg-color)"></div><div class="info text-center"><div class="info-1"><div class="info-item-1"><i class="far fa-calendar-alt fa-fw"></i> 2024-11-18</div><div class="info-item-2">Autodesk.RevitAddIns Namespace</div></div><div class="info-2"><div class="info-item-1">Autodesk.RevitAddIns Namespace类AddInManifestUtility此静态类提供从 Revit .addin 文件中读取清单内容的访问。   方法  GetRevitAddInBundleManifests  GetRevitAddInManifest  GetRevitAddInManifests     RevitAddInApplication表示 Revit 外部应用程序。  构造器  RevitAddInApplication 创建 external application info 类的新实例。    属性  Name  Application name    继承关系  System.Object  Autodesk.RevitAddIns.RevitAddInItem  Autodesk.RevitAddIns.RevitAddInApplication    RevitAddInCommand表示 Revit 外部命令。  构造器  RevitAddInCommand 创建 Add-In Command info...</div></div></div></a><a class="pagination-related" href="/2024/11/18/RevitApi%E5%90%88%E9%9B%86/Autodesk.Revit.DB%20CurveArray/" title="Autodesk.Revit.DB CurveArray"><div class="cover" style="background: var(--default-bg-color)"></div><div class="info text-center"><div class="info-1"><div class="info-item-1"><i class="far fa-calendar-alt fa-fw"></i> 2024-11-18</div><div class="info-item-2">Autodesk.Revit.DB CurveArray</div></div><div class="info-2"><div class="info-item-1">Autodesk.Revit.DB CurveArray可以包含曲线的数组。 语法1public class CurveArray : APIObject, IEnumerable  继承层次结构System Object ​	Autodesk.Revit.DB APIObject ​		Autodesk.Revit.DB CurveArray 另见CurveArray Members Autodesk.Revit.DB Namespace 构造函数CurveArray创建CurveArray类的新实例 方法Append将曲线添加到数组的末尾。 Clear从数组中删除每条曲线，使其为空。 ForwardIterator将一个向前移动的迭代器添加到数组中。 GetEnumerator将一个向前移动的迭代器添加到数组中。 Insert将指定的曲线插入数组。 ReverseIterator返回一个向后移动的迭代器到数组。 属性IsEmpty测试数组是否为空。 Item获取或设置数组中指定索引处的曲线。 Size返回数组中的曲线数。 注：翻译自Revit Api docs 2018</div></div></div></a><a class="pagination-related" href="/2024/12/10/RevitApi%E5%90%88%E9%9B%86/Autodesk.Revit.DB%20Opening/" title="Autodesk.Revit.DB Opening"><div class="cover" style="background: var(--default-bg-color)"></div><div class="info text-center"><div class="info-1"><div class="info-item-1"><i class="far fa-calendar-alt fa-fw"></i> 2024-12-10</div><div class="info-item-2">Autodesk.Revit.DB Opening</div></div><div class="info-2"><div class="info-item-1">Autodesk.Revit.DB OpeningAutodesk Revit项目或族文档中的洞口。 语法1public class Opening : Element  附注该对象表示各种不同类型的洞口：  墙中由修订项目中的两个边界点创建的矩形洞口。 由应用于屋顶、楼板、天花板、梁、支撑或柱的一组曲线创建的洞口。 一个垂直的竖井开口延伸到一个或多个水平。 在族文档中的墙或天花板上创建的简单洞口。  根据打开的类型，此类的某些属性将不可用。 这个对象派生自Element基对象，并且支持该对象的所有方法，例如检索该对象的参数的能力。此对象还支持访问结构分析模型，但此功能仅适用于Autodesk Revit Structure。 示例123456789101112131415161718192021222324252627282930313233343536373839404142434445464748495051### private void Getinfo_Opening(Opening opening)&#123;    string message =...</div></div></div></a><a class="pagination-related" href="/2024/12/10/RevitApi%E5%90%88%E9%9B%86/Autodesk.Revit.DB%20ReferenceIntersector/" title="Autodesk.Revit.DB ReferenceIntersector"><div class="cover" style="background: var(--default-bg-color)"></div><div class="info text-center"><div class="info-1"><div class="info-item-1"><i class="far fa-calendar-alt fa-fw"></i> 2024-12-10</div><div class="info-item-2">Autodesk.Revit.DB ReferenceIntersector</div></div><div class="info-2"><div class="info-item-1">Autodesk.Revit.DB ReferenceIntersector用于查找和返回与从原点和方向创建的射线相交的元素的类。 语法1public class ReferenceIntersector : IDisposable    附注可以构造此类的实例，以返回与由原点和方向创建的射线，或者基于过滤和标志返回元素的子集。 调用者可以选择使用ElementFilter过滤结果，或者通过应用特定的可接受的元素。 调用方还可以指定要返回的对象的类型， 整个元素、几何体对象或其组合。 在所有情况下，要求调用者提供 用于评估的3D视图;输入视图上的视图和可见性设置将确定 返回特定元素（例如，此工具永远不会返回隐藏元素、 和几何图形位于视图剖面框之外的元素）。 该类配置为可以构建单个实例，并用于对多个不同光线进行多次评估。在同一个 ReferenceIntersector 上的调用之间，评估结果不会被保留。 该类还提供了一个选项，用于返回在Revit链接中遇到的图元结果。 当设置 FindReferencesInRevitLinks 标志...</div></div></div></a><a class="pagination-related" href="/2024/12/19/RevitApi%E5%90%88%E9%9B%86/Autodesk.Revit.UI.Selection%20Namespace/" title="Autodesk.Revit.UI.Selection"><div class="cover" style="background: var(--default-bg-color)"></div><div class="info text-center"><div class="info-1"><div class="info-item-1"><i class="far fa-calendar-alt fa-fw"></i> 2024-12-19</div><div class="info-item-2">Autodesk.Revit.UI.Selection</div></div><div class="info-2"><div class="info-item-1">Autodesk.Revit.UI.SelectionClassesPickedBox包含两个 XYZ 点的类，表示屏幕上的选取框。  Properties  Max 最大坐标数（拾取框的右上角）。  Min 最小坐标（拾取框的左下角）。     SelectableInViewFilter一个过滤器，用于传递在给定视图中可选的元素。  Constructors  SelectableInViewFilter  (Document, ElementId) 构造 SelectableInViewFilter 的新实例。  SelectableInViewFilter (Document, ElementId, Boolean) 构造 SelectableInViewFilter 的新实例，并可选择传递所有不可选择的元素。    Methods  PassesFilter(Element) 将筛选器应用于给定元素。  PassesFilter(Document,...</div></div></div></a><a class="pagination-related" href="/2024/12/20/RevitApi%E5%90%88%E9%9B%86/Autodesk.Revit.DB%20Transform/" title="Autodesk.Revit.DB Transform"><div class="cover" style="background: var(--default-bg-color)"></div><div class="info text-center"><div class="info-1"><div class="info-item-1"><i class="far fa-calendar-alt fa-fw"></i> 2024-12-20</div><div class="info-item-2">Autodesk.Revit.DB Transform</div></div><div class="info-2"><div class="info-item-1">Autodesk.Revit.DB Transform仿射三维空间的一个变换。 语法public class Transform : APIObject示例12345678910111213141516171819202122### public static XYZ TransformPoint(XYZ point, Transform transform)&#123;    double x = point.X;    double y = point.Y;    double z = point.Z;    //transform basis of the old coordinate system in the new coordinate // system    XYZ b0 = transform.get_Basis(0);    XYZ b1 = transform.get_Basis(1);    XYZ b2 = transform.get_Basis(2);    XYZ origin = transform.Origin;       ...</div></div></div></a></div></div><hr class="custom-hr"/><div id="post-comment"><div class="comment-head"><div class="comment-headline"><i class="fas fa-comments fa-fw"></i><span> 评论</span></div></div><div class="comment-wrap"><div><div id="giscus-wrap"></div></div></div></div></div><div class="aside-content" id="aside-content"><div class="card-widget card-info text-center"><div class="avatar-img"><img src="/images/4stars.png" onerror="this.onerror=null;this.src='/img/friend_404.gif'" alt="avatar"/></div><div class="author-info-name">funtim41@gmail.com</div><div class="author-info-description">实践-认识-再实践-再认识</div><div class="site-data"><a href="/archives/"><div class="headline">文章</div><div class="length-num">51</div></a><a href="/tags/"><div class="headline">标签</div><div class="length-num">2</div></a><a href="/categories/"><div class="headline">分类</div><div class="length-num">3</div></a></div><a id="card-info-btn" target="_blank" rel="noopener" href="https://github.com/FunTim41"><i class="fab fa-github"></i><span>Follow Me</span></a><div class="card-info-social-icons"><a class="social-icon" href="https://github.com/FunTim41" target="_blank" title="Github"><i class="fab fa-github" style="color: #FFFFFF;"></i></a></div></div><div class="card-widget card-announcement"><div class="item-headline"><i class="fas fa-bullhorn fa-shake"></i><span>公告</span></div><div class="announcement_content">This is my Blog</div></div><div class="sticky_layout"><div class="card-widget" id="card-toc"><div class="item-headline"><i class="fas fa-stream"></i><span>目录</span><span class="toc-percentage"></span></div><div class="toc-content"><ol class="toc"><li class="toc-item toc-level-1"><a class="toc-link" href="#%E6%B3%A8%E9%87%8A%E5%85%83%E7%B4%A0"><span class="toc-number">1.</span> <span class="toc-text">注释元素</span></a><ol class="toc-child"><li class="toc-item toc-level-2"><a class="toc-link" href="#%E5%B0%BA%E5%AF%B8%E6%A0%87%E6%B3%A8%E5%92%8C%E7%BA%A6%E6%9D%9F"><span class="toc-number">1.1.</span> <span class="toc-text">尺寸标注和约束</span></a><ol class="toc-child"><li class="toc-item toc-level-3"><a class="toc-link" href="#%E5%B0%BA%E5%AF%B8%E6%A0%87%E6%B3%A8"><span class="toc-number">1.1.1.</span> <span class="toc-text">尺寸标注</span></a></li><li class="toc-item toc-level-3"><a class="toc-link" href="#%E7%BA%A6%E6%9D%9F%E5%85%83%E7%B4%A0"><span class="toc-number">1.1.2.</span> <span class="toc-text">约束元素</span></a></li><li class="toc-item toc-level-3"><a class="toc-link" href="#%E9%AB%98%E7%A8%8B%E7%82%B9%E6%A0%87%E6%B3%A8"><span class="toc-number">1.1.3.</span> <span class="toc-text">高程点标注</span></a></li><li class="toc-item toc-level-3"><a class="toc-link" href="#%E5%88%9B%E5%BB%BA%E5%92%8C%E5%88%A0%E9%99%A4"><span class="toc-number">1.1.4.</span> <span class="toc-text">创建和删除</span></a></li></ol></li><li class="toc-item toc-level-2"><a class="toc-link" href="#%E8%AF%A6%E5%9B%BE%E7%BA%BF"><span class="toc-number">1.2.</span> <span class="toc-text">详图线</span></a></li><li class="toc-item toc-level-2"><a class="toc-link" href="#%E6%A0%87%E7%AD%BE"><span class="toc-number">1.3.</span> <span class="toc-text">标签</span></a></li><li class="toc-item toc-level-2"><a class="toc-link" href="#%E6%96%87%E6%9C%AC"><span class="toc-number">1.4.</span> <span class="toc-text">文本</span></a><ol class="toc-child"><li class="toc-item toc-level-3"><a class="toc-link" href="#%E5%BC%95%E7%BA%BF"><span class="toc-number">1.4.1.</span> <span class="toc-text">引线</span></a></li></ol></li><li class="toc-item toc-level-2"><a class="toc-link" href="#%E6%B3%A8%E9%87%8A%E7%AC%A6%E5%8F%B7"><span class="toc-number">1.5.</span> <span class="toc-text">注释符号</span></a><ol class="toc-child"><li class="toc-item toc-level-3"><a class="toc-link" href="#%E5%88%9B%E5%BB%BA%E5%92%8C%E5%88%A0%E9%99%A4-1"><span class="toc-number">1.5.1.</span> <span class="toc-text">创建和删除</span></a></li></ol></li><li class="toc-item toc-level-2"><a class="toc-link" href="#%E6%B3%A8%EF%BC%9A%E7%BF%BB%E8%AF%91%E8%87%AARevit-API-Developers-Guide"><span class="toc-number">1.6.</span> <span class="toc-text">注：翻译自Revit API Developers Guide</span></a></li></ol></li></ol></div></div><div class="card-widget card-recent-post"><div class="item-headline"><i class="fas fa-history"></i><span>最新文章</span></div><div class="aside-list"><div class="aside-list-item no-cover"><div class="content"><a class="title" href="/2025/01/08/%E5%8D%9A%E5%AE%A2%E9%85%8D%E7%BD%AE/Hexo+Butterfly%E4%BB%A3%E7%A0%81%E5%9D%97%E6%B0%B4%E5%B9%B3%E6%BB%9A%E5%8A%A8%E6%9D%A1/" title="Hexo+Butterfly代码块水平滚动条">Hexo+Butterfly代码块水平滚动条</a><time datetime="2025-01-08T04:02:06.594Z" title="更新于 2025-01-08 12:02:06">2025-01-08</time></div></div><div class="aside-list-item no-cover"><div class="content"><a class="title" href="/2024/11/18/RevitApi%E5%90%88%E9%9B%86/Autodesk.RevitAddIns%20Namespace/" title="Autodesk.RevitAddIns Namespace">Autodesk.RevitAddIns Namespace</a><time datetime="2025-01-05T09:13:27.547Z" title="更新于 2025-01-05 17:13:27">2025-01-05</time></div></div><div class="aside-list-item no-cover"><div class="content"><a class="title" href="/2024/11/18/RevitApi%E5%90%88%E9%9B%86/Autodesk.Revit.DB%20CurveArray/" title="Autodesk.Revit.DB CurveArray">Autodesk.Revit.DB CurveArray</a><time datetime="2025-01-04T02:50:53.238Z" title="更新于 2025-01-04 10:50:53">2025-01-04</time></div></div><div class="aside-list-item no-cover"><div class="content"><a class="title" href="/2024/12/10/RevitApi%E5%90%88%E9%9B%86/Autodesk.Revit.DB%20Opening/" title="Autodesk.Revit.DB Opening">Autodesk.Revit.DB Opening</a><time datetime="2025-01-04T02:47:58.908Z" title="更新于 2025-01-04 10:47:58">2025-01-04</time></div></div><div class="aside-list-item no-cover"><div class="content"><a class="title" href="/2024/12/10/RevitApi%E5%90%88%E9%9B%86/Autodesk.Revit.DB%20ReferenceIntersector/" title="Autodesk.Revit.DB ReferenceIntersector">Autodesk.Revit.DB ReferenceIntersector</a><time datetime="2025-01-04T02:47:17.298Z" title="更新于 2025-01-04 10:47:17">2025-01-04</time></div></div></div></div></div></div></main><footer id="footer" style="background-image: url(/images/topback.jpg);"><div id="footer-wrap"><div class="copyright">&copy;2024 - 2025 By funtim41@gmail.com</div><div class="framework-info"><span>框架 </span><a target="_blank" rel="noopener" href="https://hexo.io">Hexo</a><span class="footer-separator">|</span><span>主题 </span><a target="_blank" rel="noopener" href="https://github.com/jerryc127/hexo-theme-butterfly">Butterfly</a></div><div class="footer_custom_text">学而不思则罔，思而不学则殆。</div></div></footer></div><div id="rightside"><div id="rightside-config-hide"><button id="readmode" type="button" title="阅读模式"><i class="fas fa-book-open"></i></button><button id="darkmode" type="button" title="日间和夜间模式切换"><i class="fas fa-adjust"></i></button><button id="hide-aside-btn" type="button" title="单栏和双栏切换"><i class="fas fa-arrows-alt-h"></i></button></div><div id="rightside-config-show"><button id="rightside-config" type="button" title="设置"><i class="fas fa-cog fa-spin"></i></button><button class="close" id="mobile-toc-button" type="button" title="目录"><i class="fas fa-list-ul"></i></button><a id="to_comment" href="#post-comment" title="前往评论"><i class="fas fa-comments"></i></a><button id="go-up" type="button" title="回到顶部"><span class="scroll-percent"></span><i class="fas fa-arrow-up"></i></button></div></div><div><script src="/js/utils.js"></script><script src="/js/main.js"></script><script src="https://cdn.jsdelivr.net/npm/node-snackbar/dist/snackbar.min.js"></script><script>(() => {
  const panguFn = () => {
    if (typeof pangu === 'object') pangu.autoSpacingPage()
    else {
      btf.getScript('https://cdn.jsdelivr.net/npm/pangu/dist/browser/pangu.min.js')
        .then(() => {
          pangu.autoSpacingPage()
        })
    }
  }

  const panguInit = () => {
    if (false){
      GLOBAL_CONFIG_SITE.isPost && panguFn()
    } else {
      panguFn()
    }
  }

  btf.addGlobalFn('pjaxComplete', panguInit, 'pangu')
  document.addEventListener('DOMContentLoaded', panguInit)
})()</script><div class="js-pjax"><script>(() => {
  const isShuoshuo = GLOBAL_CONFIG_SITE.isShuoshuo
  const option = null

  const getGiscusTheme = theme => theme === 'dark' ? 'dark' : 'light'

  const createScriptElement = config => {
    const ele = document.createElement('script')
    Object.entries(config).forEach(([key, value]) => {
      ele.setAttribute(key, value)
    })
    return ele
  }

  const loadGiscus = (el = document, key) => {
    const mappingConfig = isShuoshuo
      ? { 'data-mapping': 'specific', 'data-term': key }
      : { 'data-mapping': (option && option['data-mapping']) || 'pathname' }

    const giscusConfig = {
      src: 'https://giscus.app/client.js',
      'data-repo': 'FunTim41/funtim41.github.io',
      'data-repo-id': 'R_kgDONjG8ww',
      'data-category-id': 'DIC_kwDONjG8w84Cllg2',
      'data-theme': getGiscusTheme(document.documentElement.getAttribute('data-theme')),
      'data-reactions-enabled': '1',
      crossorigin: 'anonymous',
      async: true,
      ...option,
      ...mappingConfig
    }

    const scriptElement = createScriptElement(giscusConfig)

    el.querySelector('#giscus-wrap').appendChild(scriptElement)

    if (isShuoshuo) {
      window.shuoshuoComment.destroyGiscus = () => {
        if (el.children.length) {
          el.innerHTML = ''
          el.classList.add('no-comment')
        }
      }
    }
  }

  const changeGiscusTheme = theme => {
    const iframe = document.querySelector('#giscus-wrap iframe')
    if (iframe) {
      const message = {
        giscus: {
          setConfig: {
            theme: getGiscusTheme(theme)
          }
        }
      }
      iframe.contentWindow.postMessage(message, 'https://giscus.app')
    }
  }

  btf.addGlobalFn('themeChange', changeGiscusTheme, 'giscus')

  if (isShuoshuo) {
    'Giscus' === 'Giscus'
      ? window.shuoshuoComment = { loadComment: loadGiscus }
      : window.loadOtherComment = loadGiscus
    return
  }

  if ('Giscus' === 'Giscus' || !false) {
    if (false) btf.loadComment(document.getElementById('giscus-wrap'), loadGiscus)
    else loadGiscus()
  } else {
    window.loadOtherComment = loadGiscus
  }
})()</script></div><script defer="defer" id="fluttering_ribbon" mobile="false" src="https://cdn.jsdelivr.net/npm/butterfly-extsrc/dist/canvas-fluttering-ribbon.min.js"></script><script async data-pjax src="//busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js"></script><div id="local-search"><div class="search-dialog"><nav class="search-nav"><span class="search-dialog-title">搜索</span><span id="loading-status"></span><button class="search-close-button"><i class="fas fa-times"></i></button></nav><div class="text-center" id="loading-database"><i class="fas fa-spinner fa-pulse"></i><span>  数据加载中</span></div><div class="search-wrap"><div id="local-search-input"><div class="local-search-box"><input class="local-search-box--input" placeholder="搜索文章" type="text"/></div></div><hr/><div id="local-search-results"></div><div id="local-search-stats-wrap"></div></div></div><div id="search-mask"></div><script src="/js/search/local-search.js"></script></div></div></body></html>