<!DOCTYPE html><html lang="zh-CN" data-theme="light"><head><meta charset="UTF-8"><meta http-equiv="X-UA-Compatible" content="IE=edge"><meta name="viewport" content="width=device-width, initial-scale=1.0,viewport-fit=cover"><title>06选择 | funtim的博客</title><meta name="author" content="funtim41@gmail.com"><meta name="copyright" content="funtim41@gmail.com"><meta name="format-detection" content="telephone=no"><meta name="theme-color" content="#ffffff"><meta name="description" content="选择您可以使用UIDo.Selection.GetElementIds()方法从当前活动文档中获取所选对象，该方法返回所选元素的ElementIds集合。此方法返回的集合可以直接与FilteredElementCollector一起使用，以筛选选定的元素。 Selection对象还可以用于使用SetElementIds()方法以编程方式更改当前选择。 Pages in this section 本">
<meta property="og:type" content="article">
<meta property="og:title" content="06选择">
<meta property="og:url" content="https://funtim41.github.io/2024/12/05/Revit%E4%BA%8C%E5%BC%80%E6%8C%87%E5%8D%97/06%E9%80%89%E6%8B%A9/">
<meta property="og:site_name" content="funtim的博客">
<meta property="og:description" content="选择您可以使用UIDo.Selection.GetElementIds()方法从当前活动文档中获取所选对象，该方法返回所选元素的ElementIds集合。此方法返回的集合可以直接与FilteredElementCollector一起使用，以筛选选定的元素。 Selection对象还可以用于使用SetElementIds()方法以编程方式更改当前选择。 Pages in this section 本">
<meta property="og:locale" content="zh_CN">
<meta property="og:image" content="https://funtim41.github.io/images/4stars.png">
<meta property="article:published_time" content="2024-12-05T14:03:30.000Z">
<meta property="article:modified_time" content="2025-01-13T14:19:18.540Z">
<meta property="article:author" content="funtim41@gmail.com">
<meta property="article:tag" content="Revit">
<meta name="twitter:card" content="summary">
<meta name="twitter:image" content="https://funtim41.github.io/images/4stars.png"><link rel="shortcut icon" href="/images/OIP.jfif"><link rel="canonical" href="https://funtim41.github.io/2024/12/05/Revit%E4%BA%8C%E5%BC%80%E6%8C%87%E5%8D%97/06%E9%80%89%E6%8B%A9/"><link rel="preconnect" href="//cdn.jsdelivr.net"/><link rel="stylesheet" href="/css/index.css"><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free/css/all.min.css"><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/node-snackbar/dist/snackbar.min.css" media="print" onload="this.media='all'"><script>
    (() => {
      
    const saveToLocal = {
      set: (key, value, ttl) => {
        if (!ttl) return
        const expiry = Date.now() + ttl * 86400000
        localStorage.setItem(key, JSON.stringify({ value, expiry }))
      },
      get: key => {
        const itemStr = localStorage.getItem(key)
        if (!itemStr) return undefined
        const { value, expiry } = JSON.parse(itemStr)
        if (Date.now() > expiry) {
          localStorage.removeItem(key)
          return undefined
        }
        return value
      }
    }

    window.btf = {
      saveToLocal,
      getScript: (url, attr = {}) => new Promise((resolve, reject) => {
        const script = document.createElement('script')
        script.src = url
        script.async = true
        Object.entries(attr).forEach(([key, val]) => script.setAttribute(key, val))
        script.onload = script.onreadystatechange = () => {
          if (!script.readyState || /loaded|complete/.test(script.readyState)) resolve()
        }
        script.onerror = reject
        document.head.appendChild(script)
      }),
      getCSS: (url, id) => new Promise((resolve, reject) => {
        const link = document.createElement('link')
        link.rel = 'stylesheet'
        link.href = url
        if (id) link.id = id
        link.onload = link.onreadystatechange = () => {
          if (!link.readyState || /loaded|complete/.test(link.readyState)) resolve()
        }
        link.onerror = reject
        document.head.appendChild(link)
      }),
      addGlobalFn: (key, fn, name = false, parent = window) => {
        if (!false && key.startsWith('pjax')) return
        const globalFn = parent.globalFn || {}
        globalFn[key] = globalFn[key] || {}
        globalFn[key][name || Object.keys(globalFn[key]).length] = fn
        parent.globalFn = globalFn
      }
    }
  
      
      const activateDarkMode = () => {
        document.documentElement.setAttribute('data-theme', 'dark')
        if (document.querySelector('meta[name="theme-color"]') !== null) {
          document.querySelector('meta[name="theme-color"]').setAttribute('content', '#0d0d0d')
        }
      }
      const activateLightMode = () => {
        document.documentElement.setAttribute('data-theme', 'light')
        if (document.querySelector('meta[name="theme-color"]') !== null) {
          document.querySelector('meta[name="theme-color"]').setAttribute('content', '#ffffff')
        }
      }

      btf.activateDarkMode = activateDarkMode
      btf.activateLightMode = activateLightMode

      const theme = saveToLocal.get('theme')
    
          theme === 'dark' ? activateDarkMode() : theme === 'light' ? activateLightMode() : null
        
      
      const asideStatus = saveToLocal.get('aside-status')
      if (asideStatus !== undefined) {
        document.documentElement.classList.toggle('hide-aside', asideStatus === 'hide')
      }
    
      
    const detectApple = () => {
      if (/iPad|iPhone|iPod|Macintosh/.test(navigator.userAgent)) {
        document.documentElement.classList.add('apple')
      }
    }
    detectApple()
  
    })()
  </script><script>const GLOBAL_CONFIG = {
  root: '/',
  algolia: undefined,
  localSearch: {"path":"/search.xml","preload":false,"top_n_per_article":1,"unescape":false,"languages":{"hits_empty":"未找到符合您查询的内容：${query}","hits_stats":"共找到 ${hits} 篇文章"}},
  translate: undefined,
  highlight: {"plugin":"highlight.js","highlightCopy":true,"highlightLang":true,"highlightHeightLimit":false,"highlightFullpage":false,"highlightMacStyle":false},
  copy: {
    success: '复制成功',
    error: '复制失败',
    noSupport: '浏览器不支持'
  },
  relativeDate: {
    homepage: false,
    post: false
  },
  runtime: '',
  dateSuffix: {
    just: '刚刚',
    min: '分钟前',
    hour: '小时前',
    day: '天前',
    month: '个月前'
  },
  copyright: {"limitCount":150,"languages":{"author":"作者: funtim41@gmail.com","link":"链接: ","source":"来源: funtim的博客","info":"著作权归作者所有。商业转载请联系作者获得授权，非商业转载请注明出处。"}},
  lightbox: 'null',
  Snackbar: {"chs_to_cht":"已切换为繁体中文","cht_to_chs":"已切换为简体中文","day_to_night":"已切换为深色模式","night_to_day":"已切换为浅色模式","bgLight":"#49b1f5","bgDark":"#1f1f1f","position":"bottom-left"},
  infinitegrid: {
    js: 'https://cdn.jsdelivr.net/npm/@egjs/infinitegrid/dist/infinitegrid.min.js',
    buttonText: '加载更多'
  },
  isPhotoFigcaption: false,
  islazyload: false,
  isAnchor: true,
  percent: {
    toc: true,
    rightside: true,
  },
  autoDarkmode: false
}</script><script id="config-diff">var GLOBAL_CONFIG_SITE = {
  title: '06选择',
  isPost: true,
  isHome: false,
  isHighlightShrink: false,
  isToc: true,
  isShuoshuo: false
}</script><link rel="stylesheet" href="/css/bar.css"><meta name="generator" content="Hexo 7.3.0"></head><body><div id="web_bg" style="background: Color(#995a82);"></div><div id="sidebar"><div id="menu-mask"></div><div id="sidebar-menus"><div class="avatar-img text-center"><img src="/images/4stars.png" onerror="onerror=null;src='/img/friend_404.gif'" alt="avatar"/></div><div class="site-data text-center"><a href="/archives/"><div class="headline">文章</div><div class="length-num">58</div></a><a href="/tags/"><div class="headline">标签</div><div class="length-num">5</div></a><a href="/categories/"><div class="headline">分类</div><div class="length-num">7</div></a></div><div class="menus_items"><div class="menus_item"><a class="site-page" href="/"><i class="fa-fw fas fa-home"></i><span> Home</span></a></div><div class="menus_item"><a class="site-page" href="/archives/"><i class="fa-fw fas fa-archive"></i><span> Timeline</span></a></div><div class="menus_item"><a class="site-page" href="/tags/"><i class="fa-fw fas fa-tags"></i><span> Tags</span></a></div><div class="menus_item"><a class="site-page" href="/categories/"><i class="fa-fw fas fa-folder-open"></i><span> Categories</span></a></div><div class="menus_item"><a class="site-page" href="/Links/"><i class="fa-fw fas fa-link"></i><span> Links</span></a></div><div class="menus_item"><a class="site-page" href="/about/"><i class="fa-fw fas fa-heart"></i><span> About</span></a></div></div></div></div><div class="post" id="body-wrap"><header class="post-bg fixed" id="page-header" style="background-image: url(/images/topback.jpg);"><nav id="nav"><span id="blog-info"><a class="nav-site-title" href="/"><img class="site-icon" src="/images/OIP.jfif" alt="Logo"><span class="site-name">funtim的博客</span></a><a class="nav-page-title" href="/"><span class="site-name">06选择</span></a></span><div id="menus"><div id="search-button"><span class="site-page social-icon search"><i class="fas fa-search fa-fw"></i><span> 搜索</span></span></div><div class="menus_items"><div class="menus_item"><a class="site-page" href="/"><i class="fa-fw fas fa-home"></i><span> Home</span></a></div><div class="menus_item"><a class="site-page" href="/archives/"><i class="fa-fw fas fa-archive"></i><span> Timeline</span></a></div><div class="menus_item"><a class="site-page" href="/tags/"><i class="fa-fw fas fa-tags"></i><span> Tags</span></a></div><div class="menus_item"><a class="site-page" href="/categories/"><i class="fa-fw fas fa-folder-open"></i><span> Categories</span></a></div><div class="menus_item"><a class="site-page" href="/Links/"><i class="fa-fw fas fa-link"></i><span> Links</span></a></div><div class="menus_item"><a class="site-page" href="/about/"><i class="fa-fw fas fa-heart"></i><span> About</span></a></div></div><div id="toggle-menu"><span class="site-page"><i class="fas fa-bars fa-fw"></i></span></div></div></nav><div id="post-info"><h1 class="post-title">06选择</h1><div id="post-meta"><div class="meta-firstline"><span class="post-meta-date"><i class="far fa-calendar-alt fa-fw post-meta-icon"></i><span class="post-meta-label">发表于</span><time class="post-meta-date-created" datetime="2024-12-05T14:03:30.000Z" title="发表于 2024-12-05 22:03:30">2024-12-05</time><span class="post-meta-separator">|</span><i class="fas fa-history fa-fw post-meta-icon"></i><span class="post-meta-label">更新于</span><time class="post-meta-date-updated" datetime="2025-01-13T14:19:18.540Z" title="更新于 2025-01-13 22:19:18">2025-01-13</time></span><span class="post-meta-categories"><span class="post-meta-separator">|</span><i class="fas fa-inbox fa-fw post-meta-icon"></i><a class="post-meta-categories" href="/categories/Revit%E4%BA%8C%E6%AC%A1%E5%BC%80%E5%8F%91%E4%BA%BA%E5%91%98%E6%8C%87%E5%8D%97/">Revit二次开发人员指南</a></span></div><div class="meta-secondline"><span class="post-meta-separator">|</span><span class="post-meta-pv-cv" id="" data-flag-title=""><i class="far fa-eye fa-fw post-meta-icon"></i><span class="post-meta-label">浏览量:</span><span id="busuanzi_value_page_pv"><i class="fa-solid fa-spinner fa-spin"></i></span></span></div></div></div></header><main class="layout" id="content-inner"><div id="post"><article class="container post-content" id="article-container"><h1 id="选择"><a href="#选择" class="headerlink" title="选择"></a><a target="_blank" rel="noopener" href="https://help.autodesk.com/view/RVT/2018/ENU/?guid=Revit_API_Revit_API_Developers_Guide_Basic_Interaction_with_Revit_Elements_Selection_html">选择</a></h1><p>您可以使用UIDo.Selection.GetElementIds()方法从当前活动文档中获取所选对象，该方法返回所选元素的ElementIds集合。此方法返回的集合可以直接与FilteredElementCollector一起使用，以筛选选定的元素。</p>
<p>Selection对象还可以用于使用SetElementIds()方法以编程方式更改当前选择。</p>
<p>Pages in this section 本节中的页面</p>
<ul>
<li>Changing the Selection 更改选择</li>
<li>User Selection 用户选择</li>
<li>Filtered User Selection 筛选的用户选择</li>
</ul>
<h2 id="更改选择"><a href="#更改选择" class="headerlink" title="更改选择"></a>更改选择</h2><p>要修改选定的图元，请执行以下操作：</p>
<ol>
<li>创建新的ElementId列表。</li>
<li>把ElementIds放进去。</li>
<li>使用新列表调用SetElementIds()。</li>
</ol>
<p>下面的示例说明了如何通过获取当前选择并仅过滤出墙以设置为新选择来更改选定的元素。</p>
<p><strong>代码区域7-1：更改所选元素</strong></p>
<figure class="highlight c#"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br><span class="line">23</span><br><span class="line">24</span><br><span class="line">25</span><br><span class="line">26</span><br><span class="line">27</span><br><span class="line">28</span><br><span class="line">29</span><br><span class="line">30</span><br><span class="line">31</span><br><span class="line">32</span><br><span class="line">33</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="keyword">private</span> <span class="keyword">void</span> <span class="title">ChangeSelection</span>(<span class="params">UIDocument uidoc</span>)</span></span><br><span class="line">&#123;</span><br><span class="line">    <span class="comment">// Get selected elements from current document.</span></span><br><span class="line">    ICollection selectedIds = uidoc.Selection.GetElementIds();</span><br><span class="line"></span><br><span class="line">    <span class="comment">// Display current number of selected elements</span></span><br><span class="line">    TaskDialog.Show(<span class="string">&quot;Revit&quot;</span>, <span class="string">&quot;Number of selected elements: &quot;</span> + selectedIds.Count.ToString());</span><br><span class="line"></span><br><span class="line">    <span class="comment">// Go through the selected items and filter out walls only.</span></span><br><span class="line">    ICollection selectedWallIds = <span class="keyword">new</span> List();</span><br><span class="line"></span><br><span class="line">    <span class="keyword">foreach</span> (ElementId id <span class="keyword">in</span> selectedIds)</span><br><span class="line">    &#123;</span><br><span class="line">        Element elements = uidoc.Document.GetElement(id);</span><br><span class="line">        <span class="keyword">if</span> (elements <span class="keyword">is</span> Wall)</span><br><span class="line">        &#123;</span><br><span class="line">            selectedWallIds.Add(id);</span><br><span class="line">        &#125;</span><br><span class="line">    &#125;</span><br><span class="line"></span><br><span class="line">    <span class="comment">// Set the created element set as current select element set.</span></span><br><span class="line">    uidoc.Selection.SetElementIds(selectedWallIds);</span><br><span class="line"></span><br><span class="line">    <span class="comment">// Give the user some information.</span></span><br><span class="line">    <span class="keyword">if</span> (<span class="number">0</span> != selectedWallIds.Count)</span><br><span class="line">    &#123;</span><br><span class="line">        TaskDialog.Show(<span class="string">&quot;Revit&quot;</span>, selectedWallIds.Count.ToString() + <span class="string">&quot; Walls are selected!&quot;</span>);</span><br><span class="line">    &#125;</span><br><span class="line">    <span class="keyword">else</span></span><br><span class="line">    &#123;</span><br><span class="line">        TaskDialog.Show(<span class="string">&quot;Revit&quot;</span>,<span class="string">&quot;No Walls have been selected!&quot;</span>);</span><br><span class="line">    &#125;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<h2 id="用户选择"><a href="#用户选择" class="headerlink" title="用户选择"></a>用户选择</h2><p>Selection类也有一些方法，允许用户选择新对象，甚至是屏幕上的一个点。这允许用户使用光标选择一个或多个元素（或其他对象，如边或面），然后将控制权返回给应用程序。这些函数不会自动将新选区添加到活动选区集合中。</p>
<ul>
<li>PickObject()方法提示用户在Revit模型中选择对象。</li>
<li>PickObjects()方法提示用户在Revit模型中选择多个对象。</li>
<li>PickElementsByRectangle()方法提示用户使用矩形选择多个元素。</li>
<li>PickPoint()方法提示用户在活动草图平面中拾取点。</li>
<li>PickBox()方法调用一个通用的双击编辑器，让用户在屏幕上指定一个矩形区域。</li>
</ul>
<p>调用PickObject()或PickObject时指定要选择的对象类型。可以指定的对象类型有：元素、PointOnElement、边或面。</p>
<p>当应用程序提示用户拾取对象或元素时，StatusbarTip属性在状态栏中显示一条消息。每个Pick函数都有一个重载，该重载具有一个String参数，可以在其中提供自定义状态消息。</p>
<p>代码区域7-2：使用PickObject()和PickElementsByRectangle()添加选定元素</p>
<figure class="highlight c#"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br><span class="line">23</span><br><span class="line">24</span><br></pre></td><td class="code"><pre><span class="line">UIDocument uidoc = <span class="keyword">new</span> UIDocument(document);</span><br><span class="line">Selection choices = uidoc.Selection;</span><br><span class="line"><span class="comment">// Pick one object from Revit.</span></span><br><span class="line">Reference hasPickOne = choices.PickObject(ObjectType.Element);</span><br><span class="line"><span class="keyword">if</span> (hasPickOne != <span class="literal">null</span>)</span><br><span class="line">&#123;</span><br><span class="line">    TaskDialog.Show(<span class="string">&quot;Revit&quot;</span>, <span class="string">&quot;One element selected.&quot;</span>);</span><br><span class="line">&#125;</span><br><span class="line"></span><br><span class="line"><span class="comment">// Use the rectangle picking tool to identify model elements to select.</span></span><br><span class="line">IList pickedElements = uidoc.Selection.PickElementsByRectangle(<span class="string">&quot;Select by rectangle&quot;</span>);</span><br><span class="line"><span class="keyword">if</span> (pickedElements.Count &gt; <span class="number">0</span>)</span><br><span class="line">&#123; </span><br><span class="line">    <span class="comment">// Collect Ids of all picked elements</span></span><br><span class="line">    IList idsToSelect = <span class="keyword">new</span> List(pickedElements.Count);</span><br><span class="line">    <span class="keyword">foreach</span> (Element element <span class="keyword">in</span> pickedElements)</span><br><span class="line">    &#123;</span><br><span class="line">        idsToSelect.Add(element.Id);</span><br><span class="line">    &#125;</span><br><span class="line"></span><br><span class="line">    <span class="comment">// Update the current selection</span></span><br><span class="line">    uidoc.Selection.SetElementIds(idsToSelect);</span><br><span class="line">    TaskDialog.Show(<span class="string">&quot;Revit&quot;</span>, <span class="built_in">string</span>.Format(<span class="string">&quot;&#123;0&#125; elements added to Selection.&quot;</span>, idsToSelect.Count));</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<p>PickPoint()方法有2个重载，其中ObjectSnapTypes参数用于指定用于选择的捕捉类型的类型。可以指定多个，如下一个示例所示。</p>
<p>代码区域7-3：捕捉点</p>
<figure class="highlight c#"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="keyword">public</span> <span class="keyword">void</span> <span class="title">PickPoint</span>(<span class="params">UIDocument uidoc</span>)</span></span><br><span class="line">&#123;</span><br><span class="line"></span><br><span class="line">        ObjectSnapTypes snapTypes = ObjectSnapTypes.Endpoints | ObjectSnapTypes.Intersections;</span><br><span class="line">        XYZ point = uidoc.Selection.PickPoint(snapTypes, <span class="string">&quot;Select an end point or intersection&quot;</span>);</span><br><span class="line"></span><br><span class="line">        <span class="built_in">string</span> strCoords = <span class="string">&quot;Selected point is &quot;</span> + point.ToString();</span><br><span class="line"></span><br><span class="line">        TaskDialog.Show(<span class="string">&quot;Revit&quot;</span>, strCoords);</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<p>PickBox()方法接受一个PickBoxStyle枚举器。这些选项包括“交叉”、“包围”和“方向”，前者是选择完全或部分位于框内的对象时使用的样式，后者是选择完全被框包围的对象时使用的样式，前者是框的样式取决于框的绘制方向。如果从右向左绘制，则使用“交叉”样式;如果以相反方向绘制，则使用“包围”样式。 PickBox()返回一个PickedBox，其中包含选定的Min和Max点。以下示例演示了在点云选择中使用PickBox()。</p>
<p>代码区域：PickBox</p>
<figure class="highlight c#"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br><span class="line">23</span><br><span class="line">24</span><br><span class="line">25</span><br><span class="line">26</span><br><span class="line">27</span><br><span class="line">28</span><br><span class="line">29</span><br><span class="line">30</span><br><span class="line">31</span><br><span class="line">32</span><br><span class="line">33</span><br><span class="line">34</span><br><span class="line">35</span><br><span class="line">36</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="keyword">public</span> <span class="keyword">void</span> <span class="title">PromptForPointCloudSelection</span>(<span class="params">UIDocument uiDoc, PointCloudInstance pcInstance</span>)</span></span><br><span class="line">&#123;</span><br><span class="line">    Autodesk.Revit.ApplicationServices.Application app = uiDoc.Application.Application;</span><br><span class="line">    Selection currentSel = uiDoc.Selection;</span><br><span class="line"></span><br><span class="line">    PickedBox pickedBox = currentSel.PickBox(PickBoxStyle.Enclosing, <span class="string">&quot;Select region of cloud for highlighting&quot;</span>);</span><br><span class="line"></span><br><span class="line">    XYZ min = pickedBox.Min;</span><br><span class="line">    XYZ max = pickedBox.Max;</span><br><span class="line"></span><br><span class="line">    <span class="comment">//Transform points into filter</span></span><br><span class="line">    View view = uiDoc.ActiveView;</span><br><span class="line">    XYZ right = view.RightDirection;</span><br><span class="line">    XYZ up = view.UpDirection;</span><br><span class="line"></span><br><span class="line">    List planes = <span class="keyword">new</span> List();</span><br><span class="line"></span><br><span class="line">    <span class="comment">// X boundaries</span></span><br><span class="line">    <span class="built_in">bool</span> directionCorrect = IsPointAbovePlane(right, min, max);</span><br><span class="line">    planes.Add(Plane.CreateByNormalAndOrigin(right, directionCorrect ? min : max));</span><br><span class="line">    planes.Add(Plane.CreateByNormalAndOrigin(-right, directionCorrect ? max : min));</span><br><span class="line"></span><br><span class="line">    <span class="comment">// Y boundaries</span></span><br><span class="line">    directionCorrect = IsPointAbovePlane(up, min, max);</span><br><span class="line">    planes.Add(Plane.CreateByNormalAndOrigin(up, directionCorrect ? min : max));</span><br><span class="line">    planes.Add(Plane.CreateByNormalAndOrigin(-up, directionCorrect ? max : min));</span><br><span class="line"></span><br><span class="line">    <span class="comment">// Create filter</span></span><br><span class="line">    PointCloudFilter filter = PointCloudFilterFactory.CreateMultiPlaneFilter(planes);</span><br><span class="line">    Transaction t = <span class="keyword">new</span> Transaction(uiDoc.Document, <span class="string">&quot;Highlight&quot;</span>);</span><br><span class="line">    t.Start();</span><br><span class="line">    pcInstance.SetSelectionFilter(filter);</span><br><span class="line">    pcInstance.FilterAction = SelectionFilterAction.Highlight;</span><br><span class="line">    t.Commit();</span><br><span class="line">    uiDoc.RefreshActiveView();</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<h2 id="筛选的用户选择"><a href="#筛选的用户选择" class="headerlink" title="筛选的用户选择"></a>筛选的用户选择</h2><p>PickObject()、PickObjects()和PickElementsByRectangle()都具有将ISelectionFilter作为参数的重载。ISelectionFilter是一个接口，可用于在选择操作期间过滤对象。它有两个可以覆盖的方法：AllowElement()用于指定是否允许选择元素，以及AllowReference()用于指定是否允许选择对一段几何图形的引用。</p>
<p>下面的示例阐释如何使用ISelectionFilter接口将用户的选择限制为“体量”类别中的元素。它不允许选择对几何图元的任何参照。</p>
<p>使用ISelectionFilter限制元素选择</p>
<figure class="highlight c#"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br><span class="line">23</span><br><span class="line">24</span><br><span class="line">25</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="keyword">public</span> <span class="keyword">static</span> IList <span class="title">GetManyRefByRectangle</span>(<span class="params">UIDocument doc</span>)</span></span><br><span class="line">&#123;</span><br><span class="line">        ReferenceArray ra = <span class="keyword">new</span> ReferenceArray();</span><br><span class="line">        ISelectionFilter selFilter = <span class="keyword">new</span> MassSelectionFilter();</span><br><span class="line">        IList eList = doc.Selection.PickElementsByRectangle(selFilter, </span><br><span class="line">                <span class="string">&quot;Select multiple faces&quot;</span>) <span class="keyword">as</span> IList;</span><br><span class="line">        <span class="keyword">return</span> eList;</span><br><span class="line">&#125;</span><br><span class="line"></span><br><span class="line"><span class="keyword">public</span> <span class="keyword">class</span> <span class="title">MassSelectionFilter</span> : <span class="title">ISelectionFilter</span></span><br><span class="line">&#123;</span><br><span class="line">        <span class="function"><span class="keyword">public</span> <span class="built_in">bool</span> <span class="title">AllowElement</span>(<span class="params">Element element</span>)</span></span><br><span class="line">        &#123;</span><br><span class="line">        <span class="keyword">if</span> (element.Category.Name == <span class="string">&quot;Mass&quot;</span>)</span><br><span class="line">        &#123;</span><br><span class="line">                <span class="keyword">return</span> <span class="literal">true</span>;</span><br><span class="line">        &#125;</span><br><span class="line">        <span class="keyword">return</span> <span class="literal">false</span>;</span><br><span class="line">        &#125;</span><br><span class="line"></span><br><span class="line">        <span class="function"><span class="keyword">public</span> <span class="built_in">bool</span> <span class="title">AllowReference</span>(<span class="params">Reference refer, XYZ point</span>)</span></span><br><span class="line">        &#123;</span><br><span class="line">                <span class="keyword">return</span> <span class="literal">false</span>;</span><br><span class="line">        &#125;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<p>下一个示例演示如何使用ISelectionFilter仅允许选择平面。</p>
<p>代码区域7-5：使用ISelectionFilter限制几何选择</p>
<figure class="highlight c#"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br><span class="line">23</span><br><span class="line">24</span><br><span class="line">25</span><br><span class="line">26</span><br><span class="line">27</span><br><span class="line">28</span><br><span class="line">29</span><br><span class="line">30</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="keyword">public</span> <span class="keyword">void</span> <span class="title">SelectPlanarFaces</span>(<span class="params">Autodesk.Revit.DB.Document document</span>)</span></span><br><span class="line">&#123;</span><br><span class="line">        UIDocument uidoc = <span class="keyword">new</span> UIDocument(document);</span><br><span class="line">        ISelectionFilter selFilter = <span class="keyword">new</span> PlanarFacesSelectionFilter(document);</span><br><span class="line">        IList faces = uidoc.Selection.PickObjects(ObjectType.Face, </span><br><span class="line">                selFilter, <span class="string">&quot;Select multiple planar faces&quot;</span>);</span><br><span class="line">&#125;</span><br><span class="line"></span><br><span class="line"><span class="keyword">public</span> <span class="keyword">class</span> <span class="title">PlanarFacesSelectionFilter</span> : <span class="title">ISelectionFilter</span></span><br><span class="line">&#123;</span><br><span class="line">        Document doc = <span class="literal">null</span>;</span><br><span class="line">        <span class="function"><span class="keyword">public</span> <span class="title">PlanarFacesSelectionFilter</span>(<span class="params">Document document</span>)</span></span><br><span class="line">        &#123;</span><br><span class="line">                doc = document;</span><br><span class="line">        &#125;</span><br><span class="line"></span><br><span class="line">        <span class="function"><span class="keyword">public</span> <span class="built_in">bool</span> <span class="title">AllowElement</span>(<span class="params">Element element</span>)</span></span><br><span class="line">        &#123;</span><br><span class="line">                <span class="keyword">return</span> <span class="literal">true</span>;</span><br><span class="line">        &#125;</span><br><span class="line"></span><br><span class="line">        <span class="function"><span class="keyword">public</span> <span class="built_in">bool</span> <span class="title">AllowReference</span>(<span class="params">Reference refer, XYZ point</span>)</span></span><br><span class="line">        &#123;                <span class="keyword">if</span> (doc.GetElement(refer).GetGeometryObjectFromReference(refer) <span class="keyword">is</span> PlanarFace)</span><br><span class="line">                &#123;</span><br><span class="line">                        <span class="comment">// Only return true for planar faces. Non-planar faces will not be selectable </span></span><br><span class="line">                        <span class="keyword">return</span> <span class="literal">true</span>; </span><br><span class="line">                &#125;</span><br><span class="line">                <span class="keyword">return</span> <span class="literal">false</span>;</span><br><span class="line">        &#125;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<p>有关从选定元素中检索元素的更多信息，请参见“入门”部分中的演练：检索选定元素。</p>
<h2 id="注：翻译自Revit-API-Developers-Guide"><a href="#注：翻译自Revit-API-Developers-Guide" class="headerlink" title="注：翻译自Revit API Developers Guide"></a><em><strong>注：</strong></em>翻译自<a target="_blank" rel="noopener" href="https://help.autodesk.com/view/RVT/2018/ENU/?guid=Revit_API_Revit_API_Developers_Guide_html">Revit API Developers Guide</a></h2></article><div class="tag_share"><div class="post-meta__tag-list"><a class="post-meta__tags" href="/tags/Revit/">Revit</a></div><div class="post-share"><div class="social-share" data-image="/images/4stars.png" data-sites="facebook,twitter,wechat,weibo,qq"></div><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/butterfly-extsrc/sharejs/dist/css/share.min.css" media="print" onload="this.media='all'"><script src="https://cdn.jsdelivr.net/npm/butterfly-extsrc/sharejs/dist/js/social-share.min.js" defer></script></div></div><nav class="pagination-post" id="pagination"><a class="pagination-related" href="/2024/12/05/Revit%E4%BA%8C%E5%BC%80%E6%8C%87%E5%8D%97/08%E9%9B%86%E5%90%88/" title="08集合"><div class="cover" style="background: var(--default-bg-color)"></div><div class="info"><div class="info-1"><div class="info-item-1">上一篇</div><div class="info-item-2">08集合</div></div><div class="info-2"><div class="info-item-1">集合大多数Revit Platform API属性和方法在提供对一组相关项的访问时都使用.NET Framework集合类。 在Revit集合类型中实现的IEnumerator和IEnumerator接口在System.Collection命名空间中定义。 Pages in this section 本节中的页面  Interface 接口 Collections and Iterators 集合和迭代器  Interface...</div></div></div></a><a class="pagination-related" href="/2024/12/05/Revit%E4%BA%8C%E5%BC%80%E6%8C%87%E5%8D%97/15%E6%A6%82%E5%BF%B5%E8%AE%BE%E8%AE%A1/" title="15概念设计"><div class="cover" style="background: var(--default-bg-color)"></div><div class="info text-right"><div class="info-1"><div class="info-item-1">下一篇</div><div class="info-item-2">15概念设计</div></div><div class="info-2"><div class="info-item-1">概念设计本章讨论用于在族文档中创建复杂几何图形的Revit API的概念设计功能。通过添加新对象（点和通过这些点的样条曲线）来支持形状制作。可以分割、填充图案和嵌板化生成的曲面，以创建具有持久参数关系的可构建形状。 本节中的页面  点和曲线对象 形状 曲面的几何化 自适应构件 创建.addin清单文件  点和曲线对象参照点是在概念设计环境的XYZ工作空间中指定位置的元素。可以创建参照点来设计和打印直线、样条曲线和形状。可以将ReferencePoint添加到ReferencePointArray，然后用于创建CurveByPoints，而CurveByPoints又可用于创建形状。 下面的示例演示如何创建CurveByPoints对象。请参见下一节中的“创建放样形状”示例，了解如何从多个CurveByPoints对象创建形状。 代码区域14-1：创建新的CurveByPoints 123456789101112131415161718192021222324//体量中创建ReferencePointArray rpa = new...</div></div></div></a></nav><div class="relatedPosts"><div class="headline"><i class="fas fa-thumbs-up fa-fw"></i><span>相关推荐</span></div><div class="relatedPosts-list"><a class="pagination-related" href="/2024/11/18/RevitApi%E5%90%88%E9%9B%86/Autodesk.Revit.DB%20CurveArray/" title="Autodesk.Revit.DB CurveArray"><div class="cover" style="background: var(--default-bg-color)"></div><div class="info text-center"><div class="info-1"><div class="info-item-1"><i class="far fa-calendar-alt fa-fw"></i> 2024-11-18</div><div class="info-item-2">Autodesk.Revit.DB CurveArray</div></div><div class="info-2"><div class="info-item-1">Autodesk.Revit.DB CurveArray可以包含曲线的数组。 语法1public class CurveArray : APIObject, IEnumerable  继承层次结构System Object ​	Autodesk.Revit.DB APIObject ​		Autodesk.Revit.DB CurveArray 另见CurveArray Members Autodesk.Revit.DB Namespace 构造函数CurveArray创建CurveArray类的新实例 方法Append将曲线添加到数组的末尾。 Clear从数组中删除每条曲线，使其为空。 ForwardIterator将一个向前移动的迭代器添加到数组中。 GetEnumerator将一个向前移动的迭代器添加到数组中。 Insert将指定的曲线插入数组。 ReverseIterator返回一个向后移动的迭代器到数组。 属性IsEmpty测试数组是否为空。 Item获取或设置数组中指定索引处的曲线。 Size返回数组中的曲线数。 注：翻译自Revit Api docs 2018</div></div></div></a><a class="pagination-related" href="/2024/12/20/RevitApi%E5%90%88%E9%9B%86/Autodesk.%20Revit.DB%20ElementTransformUtils/" title="Autodesk.Revit.DB ElementTransformUtils"><div class="cover" style="background: var(--default-bg-color)"></div><div class="info text-center"><div class="info-1"><div class="info-item-1"><i class="far fa-calendar-alt fa-fw"></i> 2024-12-20</div><div class="info-item-2">Autodesk.Revit.DB ElementTransformUtils</div></div><div class="info-2"><div class="info-item-1">Autodesk. Revit.DB ElementTransformUtils允许元素转换的实用程序集合（例如移动，旋转，镜像和复制）。 语法1public static class ElementTransformUtils    继承层次结构 System Object Autodesk.Revit.DB ElementTransformUtils   方法CanMirrorElement确定是否可以镜像元素。 CanMirrorElements确定是否可以镜像元素。 CopyElement复制元素并将副本放置在给定转换指示的位置。 CopyElements(Document, ICollection ElementId , XYZ)复制一组元素，并将副本放置在给定指示的位置。 CopyElements(Document, ICollection ElementId , Document, Transform, CopyPasteOptions)将一组元素从源文档复制到目标文档。 CopyElements(View, ICollection ElementId ,...</div></div></div></a><a class="pagination-related" href="/2024/10/30/RevitApi%E5%90%88%E9%9B%86/Autodesk.Revit.DB%20Document/" title="Autodesk.Revit.DB Document"><div class="cover" style="background: var(--default-bg-color)"></div><div class="info text-center"><div class="info-1"><div class="info-item-1"><i class="far fa-calendar-alt fa-fw"></i> 2024-10-30</div><div class="info-item-2">Autodesk.Revit.DB Document</div></div><div class="info-2"><div class="info-item-1">Autodesk.Revit.DB Document表示打开的 Autodesk Revit 项目的对象。 语法1public class Document : IDisposable    附注Document 对象表示 Autodesk Revit 项目。Revit 可以打开多个项目，并打开这些项目的多个视图。活动视图或最顶层视图将是活动项目，因此是可从 Application 对象获得的活动文档。 继承层次结构 System Object Autodesk.Revit.DB Document Autodesk.Revit.DB.Macros DocumentEntryPoint  方法AcquireCoordinates 不知道是啥，API没给描述  AutoJoinElements 强制 Revit...</div></div></div></a><a class="pagination-related" href="/2024/12/10/RevitApi%E5%90%88%E9%9B%86/Autodesk.Revit.DB%20Opening/" title="Autodesk.Revit.DB Opening"><div class="cover" style="background: var(--default-bg-color)"></div><div class="info text-center"><div class="info-1"><div class="info-item-1"><i class="far fa-calendar-alt fa-fw"></i> 2024-12-10</div><div class="info-item-2">Autodesk.Revit.DB Opening</div></div><div class="info-2"><div class="info-item-1">Autodesk.Revit.DB OpeningAutodesk Revit项目或族文档中的洞口。 语法1public class Opening : Element  附注该对象表示各种不同类型的洞口：  墙中由修订项目中的两个边界点创建的矩形洞口。 由应用于屋顶、楼板、天花板、梁、支撑或柱的一组曲线创建的洞口。 一个垂直的竖井开口延伸到一个或多个水平。 在族文档中的墙或天花板上创建的简单洞口。  根据打开的类型，此类的某些属性将不可用。 这个对象派生自Element基对象，并且支持该对象的所有方法，例如检索该对象的参数的能力。此对象还支持访问结构分析模型，但此功能仅适用于Autodesk Revit Structure。 示例123456789101112131415161718192021222324252627282930313233343536373839404142434445464748495051### private void Getinfo_Opening(Opening opening)&#123;    string message =...</div></div></div></a><a class="pagination-related" href="/2024/12/10/RevitApi%E5%90%88%E9%9B%86/Autodesk.Revit.DB%20ReferenceIntersector/" title="Autodesk.Revit.DB ReferenceIntersector"><div class="cover" style="background: var(--default-bg-color)"></div><div class="info text-center"><div class="info-1"><div class="info-item-1"><i class="far fa-calendar-alt fa-fw"></i> 2024-12-10</div><div class="info-item-2">Autodesk.Revit.DB ReferenceIntersector</div></div><div class="info-2"><div class="info-item-1">Autodesk.Revit.DB ReferenceIntersector用于查找和返回与从原点和方向创建的射线相交的元素的类。 语法1public class ReferenceIntersector : IDisposable    附注可以构造此类的实例，以返回与由原点和方向创建的射线，或者基于过滤和标志返回元素的子集。 调用者可以选择使用ElementFilter过滤结果，或者通过应用特定的可接受的元素。 调用方还可以指定要返回的对象的类型， 整个元素、几何体对象或其组合。 在所有情况下，要求调用者提供 用于评估的3D视图;输入视图上的视图和可见性设置将确定 返回特定元素（例如，此工具永远不会返回隐藏元素、 和几何图形位于视图剖面框之外的元素）。 该类配置为可以构建单个实例，并用于对多个不同光线进行多次评估。在同一个 ReferenceIntersector 上的调用之间，评估结果不会被保留。 该类还提供了一个选项，用于返回在Revit链接中遇到的图元结果。 当设置 FindReferencesInRevitLinks 标志...</div></div></div></a><a class="pagination-related" href="/2024/12/19/RevitApi%E5%90%88%E9%9B%86/Autodesk.Revit.UI.Selection%20Namespace/" title="Autodesk.Revit.UI.Selection"><div class="cover" style="background: var(--default-bg-color)"></div><div class="info text-center"><div class="info-1"><div class="info-item-1"><i class="far fa-calendar-alt fa-fw"></i> 2024-12-19</div><div class="info-item-2">Autodesk.Revit.UI.Selection</div></div><div class="info-2"><div class="info-item-1">Autodesk.Revit.UI.SelectionClassesPickedBox包含两个 XYZ 点的类，表示屏幕上的选取框。  Properties  Max 最大坐标数（拾取框的右上角）。  Min 最小坐标（拾取框的左下角）。     SelectableInViewFilter一个过滤器，用于传递在给定视图中可选的元素。  Constructors  SelectableInViewFilter  (Document, ElementId) 构造 SelectableInViewFilter 的新实例。  SelectableInViewFilter (Document, ElementId, Boolean) 构造 SelectableInViewFilter 的新实例，并可选择传递所有不可选择的元素。    Methods  PassesFilter(Element) 将筛选器应用于给定元素。  PassesFilter(Document,...</div></div></div></a></div></div><hr class="custom-hr"/><div id="post-comment"><div class="comment-head"><div class="comment-headline"><i class="fas fa-comments fa-fw"></i><span> 评论</span></div></div><div class="comment-wrap"><div><div id="giscus-wrap"></div></div></div></div></div><div class="aside-content" id="aside-content"><div class="card-widget card-info text-center"><div class="avatar-img"><img src="/images/4stars.png" onerror="this.onerror=null;this.src='/img/friend_404.gif'" alt="avatar"/></div><div class="author-info-name">funtim41@gmail.com</div><div class="author-info-description">实践-认识-再实践-再认识</div><div class="site-data"><a href="/archives/"><div class="headline">文章</div><div class="length-num">58</div></a><a href="/tags/"><div class="headline">标签</div><div class="length-num">5</div></a><a href="/categories/"><div class="headline">分类</div><div class="length-num">7</div></a></div><a id="card-info-btn" target="_blank" rel="noopener" href="https://github.com/FunTim41"><i class="fab fa-github"></i><span>Follow Me</span></a><div class="card-info-social-icons"><a class="social-icon" href="https://github.com/FunTim41" target="_blank" title="Github"><i class="fab fa-github" style="color: #FFFFFF;"></i></a></div></div><div class="card-widget card-announcement"><div class="item-headline"><i class="fas fa-bullhorn fa-shake"></i><span>公告</span></div><div class="announcement_content">This is my Blog</div></div><div class="sticky_layout"><div class="card-widget" id="card-toc"><div class="item-headline"><i class="fas fa-stream"></i><span>目录</span><span class="toc-percentage"></span></div><div class="toc-content"><ol class="toc"><li class="toc-item toc-level-1"><a class="toc-link" href="#%E9%80%89%E6%8B%A9"><span class="toc-number">1.</span> <span class="toc-text">选择</span></a><ol class="toc-child"><li class="toc-item toc-level-2"><a class="toc-link" href="#%E6%9B%B4%E6%94%B9%E9%80%89%E6%8B%A9"><span class="toc-number">1.1.</span> <span class="toc-text">更改选择</span></a></li><li class="toc-item toc-level-2"><a class="toc-link" href="#%E7%94%A8%E6%88%B7%E9%80%89%E6%8B%A9"><span class="toc-number">1.2.</span> <span class="toc-text">用户选择</span></a></li><li class="toc-item toc-level-2"><a class="toc-link" href="#%E7%AD%9B%E9%80%89%E7%9A%84%E7%94%A8%E6%88%B7%E9%80%89%E6%8B%A9"><span class="toc-number">1.3.</span> <span class="toc-text">筛选的用户选择</span></a></li><li class="toc-item toc-level-2"><a class="toc-link" href="#%E6%B3%A8%EF%BC%9A%E7%BF%BB%E8%AF%91%E8%87%AARevit-API-Developers-Guide"><span class="toc-number">1.4.</span> <span class="toc-text">注：翻译自Revit API Developers Guide</span></a></li></ol></li></ol></div></div><div class="card-widget card-recent-post"><div class="item-headline"><i class="fas fa-history"></i><span>最新文章</span></div><div class="aside-list"><div class="aside-list-item no-cover"><div class="content"><a class="title" href="/2025/01/16/Revit%E4%BA%8C%E5%BC%80%E7%A4%BA%E4%BE%8B/Revit%E4%B8%8EExcel%E4%BA%A4%E4%BA%92/" title="Revit与Excel交互">Revit与Excel交互</a><time datetime="2025-01-16T08:43:45.327Z" title="更新于 2025-01-16 16:43:45">2025-01-16</time></div></div><div class="aside-list-item no-cover"><div class="content"><a class="title" href="/2025/01/14/ObjectARX%EF%BC%9AManaged.NET%E5%BC%80%E5%8F%91%E4%BA%BA%E5%91%98%E6%8C%87%E5%8D%97/03%E5%88%9B%E5%BB%BA%E5%92%8C%E7%BC%96%E8%BE%91AutoCAD%E5%9B%BE%E5%85%83%EF%BC%88.NET%EF%BC%89/" title="03创建和编辑AutoCAD图元（.NET）">03创建和编辑AutoCAD图元（.NET）</a><time datetime="2025-01-14T04:28:05.785Z" title="更新于 2025-01-14 12:28:05">2025-01-14</time></div></div><div class="aside-list-item no-cover"><div class="content"><a class="title" href="/2025/01/13/ObjectARX%EF%BC%9AManaged.NET%E5%BC%80%E5%8F%91%E4%BA%BA%E5%91%98%E6%8C%87%E5%8D%97/02%E6%8E%A7%E5%88%B6AutoCAD%E7%8E%AF%E5%A2%83%EF%BC%88.NET%EF%BC%89/" title="02控制AutoCAD环境（.NET）">02控制AutoCAD环境（.NET）</a><time datetime="2025-01-14T02:31:41.869Z" title="更新于 2025-01-14 10:31:41">2025-01-14</time></div></div><div class="aside-list-item no-cover"><div class="content"><a class="title" href="/2025/01/12/ObjectARX%EF%BC%9AManaged.NET%E5%BC%80%E5%8F%91%E4%BA%BA%E5%91%98%E6%8C%87%E5%8D%97/01AutoCAD.NET%20API%EF%BC%88.NET%EF%BC%89%E7%9A%84%E5%9F%BA%E7%A1%80%E7%9F%A5%E8%AF%86/" title="01AutoCAD .NET API（.NET）的基础知识">01AutoCAD .NET API（.NET）的基础知识</a><time datetime="2025-01-14T02:31:29.466Z" title="更新于 2025-01-14 10:31:29">2025-01-14</time></div></div><div class="aside-list-item no-cover"><div class="content"><a class="title" href="/2024/12/19/RevitApi%E5%90%88%E9%9B%86/Autodesk.Revit.UI.Selection%20Namespace/" title="Autodesk.Revit.UI.Selection">Autodesk.Revit.UI.Selection</a><time datetime="2025-01-13T14:24:17.222Z" title="更新于 2025-01-13 22:24:17">2025-01-13</time></div></div></div></div></div></div></main><footer id="footer" style="background-image: url(/images/topback.jpg);"><div id="footer-wrap"><div class="copyright">&copy;2024 - 2025 By funtim41@gmail.com</div><div class="framework-info"><span>框架 </span><a target="_blank" rel="noopener" href="https://hexo.io">Hexo</a><span class="footer-separator">|</span><span>主题 </span><a target="_blank" rel="noopener" href="https://github.com/jerryc127/hexo-theme-butterfly">Butterfly</a></div><div class="footer_custom_text">学而不思则罔，思而不学则殆。</div></div></footer></div><div id="rightside"><div id="rightside-config-hide"><button id="readmode" type="button" title="阅读模式"><i class="fas fa-book-open"></i></button><button id="darkmode" type="button" title="日间和夜间模式切换"><i class="fas fa-adjust"></i></button><button id="hide-aside-btn" type="button" title="单栏和双栏切换"><i class="fas fa-arrows-alt-h"></i></button></div><div id="rightside-config-show"><button id="rightside-config" type="button" title="设置"><i class="fas fa-cog fa-spin"></i></button><button class="close" id="mobile-toc-button" type="button" title="目录"><i class="fas fa-list-ul"></i></button><a id="to_comment" href="#post-comment" title="前往评论"><i class="fas fa-comments"></i></a><button id="go-up" type="button" title="回到顶部"><span class="scroll-percent"></span><i class="fas fa-arrow-up"></i></button></div></div><div><script src="/js/utils.js"></script><script src="/js/main.js"></script><script src="https://cdn.jsdelivr.net/npm/node-snackbar/dist/snackbar.min.js"></script><script>(() => {
  const panguFn = () => {
    if (typeof pangu === 'object') pangu.autoSpacingPage()
    else {
      btf.getScript('https://cdn.jsdelivr.net/npm/pangu/dist/browser/pangu.min.js')
        .then(() => {
          pangu.autoSpacingPage()
        })
    }
  }

  const panguInit = () => {
    if (false){
      GLOBAL_CONFIG_SITE.isPost && panguFn()
    } else {
      panguFn()
    }
  }

  btf.addGlobalFn('pjaxComplete', panguInit, 'pangu')
  document.addEventListener('DOMContentLoaded', panguInit)
})()</script><div class="js-pjax"><script>(() => {
  const isShuoshuo = GLOBAL_CONFIG_SITE.isShuoshuo
  const option = null

  const getGiscusTheme = theme => theme === 'dark' ? 'dark' : 'light'

  const createScriptElement = config => {
    const ele = document.createElement('script')
    Object.entries(config).forEach(([key, value]) => {
      ele.setAttribute(key, value)
    })
    return ele
  }

  const loadGiscus = (el = document, key) => {
    const mappingConfig = isShuoshuo
      ? { 'data-mapping': 'specific', 'data-term': key }
      : { 'data-mapping': (option && option['data-mapping']) || 'pathname' }

    const giscusConfig = {
      src: 'https://giscus.app/client.js',
      'data-repo': 'FunTim41/funtim41.github.io',
      'data-repo-id': 'R_kgDONjG8ww',
      'data-category-id': 'DIC_kwDONjG8w84Cllg2',
      'data-theme': getGiscusTheme(document.documentElement.getAttribute('data-theme')),
      'data-reactions-enabled': '1',
      crossorigin: 'anonymous',
      async: true,
      ...option,
      ...mappingConfig
    }

    const scriptElement = createScriptElement(giscusConfig)

    el.querySelector('#giscus-wrap').appendChild(scriptElement)

    if (isShuoshuo) {
      window.shuoshuoComment.destroyGiscus = () => {
        if (el.children.length) {
          el.innerHTML = ''
          el.classList.add('no-comment')
        }
      }
    }
  }

  const changeGiscusTheme = theme => {
    const iframe = document.querySelector('#giscus-wrap iframe')
    if (iframe) {
      const message = {
        giscus: {
          setConfig: {
            theme: getGiscusTheme(theme)
          }
        }
      }
      iframe.contentWindow.postMessage(message, 'https://giscus.app')
    }
  }

  btf.addGlobalFn('themeChange', changeGiscusTheme, 'giscus')

  if (isShuoshuo) {
    'Giscus' === 'Giscus'
      ? window.shuoshuoComment = { loadComment: loadGiscus }
      : window.loadOtherComment = loadGiscus
    return
  }

  if ('Giscus' === 'Giscus' || !false) {
    if (false) btf.loadComment(document.getElementById('giscus-wrap'), loadGiscus)
    else loadGiscus()
  } else {
    window.loadOtherComment = loadGiscus
  }
})()</script></div><script defer="defer" id="fluttering_ribbon" mobile="false" src="https://cdn.jsdelivr.net/npm/butterfly-extsrc/dist/canvas-fluttering-ribbon.min.js"></script><script async data-pjax src="//busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js"></script><div id="local-search"><div class="search-dialog"><nav class="search-nav"><span class="search-dialog-title">搜索</span><span id="loading-status"></span><button class="search-close-button"><i class="fas fa-times"></i></button></nav><div class="text-center" id="loading-database"><i class="fas fa-spinner fa-pulse"></i><span>  数据加载中</span></div><div class="search-wrap"><div id="local-search-input"><div class="local-search-box"><input class="local-search-box--input" placeholder="搜索文章" type="text"/></div></div><hr/><div id="local-search-results"></div><div id="local-search-stats-wrap"></div></div></div><div id="search-mask"></div><script src="/js/search/local-search.js"></script></div></div></body></html>