<!DOCTYPE html><html lang="zh-CN" data-theme="light"><head><meta charset="UTF-8"><meta http-equiv="X-UA-Compatible" content="IE=edge"><meta name="viewport" content="width=device-width, initial-scale=1.0,viewport-fit=cover"><title>41链接文件 | funtim的博客</title><meta name="author" content="funtim41@gmail.com"><meta name="copyright" content="funtim41@gmail.com"><meta name="format-detection" content="telephone=no"><meta name="theme-color" content="#ffffff"><meta name="description" content="链接文件Revit API可以确定Revit中的哪些图元是对外部文件（“链接文件”）的引用，并可以对Revit加载外部文件的方式进行一些修改。 包含ExternalFileReference的元素是引用基.rvt文件之外的某个文件的元素。示例包括Revit链接、CAD链接、存储注释记号文件位置的图元和渲染贴花。IsExternalFileReference（）返回元素是否表示外部文件。GetExt">
<meta property="og:type" content="article">
<meta property="og:title" content="41链接文件">
<meta property="og:url" content="https://funtim41.github.io/2024/12/30/%E4%BA%8C%E5%BC%80%E6%8C%87%E5%8D%97/41%E9%93%BE%E6%8E%A5%E6%96%87%E4%BB%B6/">
<meta property="og:site_name" content="funtim的博客">
<meta property="og:description" content="链接文件Revit API可以确定Revit中的哪些图元是对外部文件（“链接文件”）的引用，并可以对Revit加载外部文件的方式进行一些修改。 包含ExternalFileReference的元素是引用基.rvt文件之外的某个文件的元素。示例包括Revit链接、CAD链接、存储注释记号文件位置的图元和渲染贴花。IsExternalFileReference（）返回元素是否表示外部文件。GetExt">
<meta property="og:locale" content="zh_CN">
<meta property="og:image" content="https://funtim41.github.io/images/4stars.png">
<meta property="article:published_time" content="2024-12-30T07:52:29.000Z">
<meta property="article:modified_time" content="2024-12-30T08:06:42.788Z">
<meta property="article:author" content="funtim41@gmail.com">
<meta property="article:tag" content="Revit">
<meta name="twitter:card" content="summary">
<meta name="twitter:image" content="https://funtim41.github.io/images/4stars.png"><link rel="shortcut icon" href="/images/OIP.jfif"><link rel="canonical" href="https://funtim41.github.io/2024/12/30/%E4%BA%8C%E5%BC%80%E6%8C%87%E5%8D%97/41%E9%93%BE%E6%8E%A5%E6%96%87%E4%BB%B6/"><link rel="preconnect" href="//cdn.jsdelivr.net"/><link rel="stylesheet" href="/css/index.css"><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free/css/all.min.css"><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/node-snackbar/dist/snackbar.min.css" media="print" onload="this.media='all'"><script>
    (() => {
      
    const saveToLocal = {
      set: (key, value, ttl) => {
        if (!ttl) return
        const expiry = Date.now() + ttl * 86400000
        localStorage.setItem(key, JSON.stringify({ value, expiry }))
      },
      get: key => {
        const itemStr = localStorage.getItem(key)
        if (!itemStr) return undefined
        const { value, expiry } = JSON.parse(itemStr)
        if (Date.now() > expiry) {
          localStorage.removeItem(key)
          return undefined
        }
        return value
      }
    }

    window.btf = {
      saveToLocal,
      getScript: (url, attr = {}) => new Promise((resolve, reject) => {
        const script = document.createElement('script')
        script.src = url
        script.async = true
        Object.entries(attr).forEach(([key, val]) => script.setAttribute(key, val))
        script.onload = script.onreadystatechange = () => {
          if (!script.readyState || /loaded|complete/.test(script.readyState)) resolve()
        }
        script.onerror = reject
        document.head.appendChild(script)
      }),
      getCSS: (url, id) => new Promise((resolve, reject) => {
        const link = document.createElement('link')
        link.rel = 'stylesheet'
        link.href = url
        if (id) link.id = id
        link.onload = link.onreadystatechange = () => {
          if (!link.readyState || /loaded|complete/.test(link.readyState)) resolve()
        }
        link.onerror = reject
        document.head.appendChild(link)
      }),
      addGlobalFn: (key, fn, name = false, parent = window) => {
        if (!false && key.startsWith('pjax')) return
        const globalFn = parent.globalFn || {}
        globalFn[key] = globalFn[key] || {}
        globalFn[key][name || Object.keys(globalFn[key]).length] = fn
        parent.globalFn = globalFn
      }
    }
  
      
      const activateDarkMode = () => {
        document.documentElement.setAttribute('data-theme', 'dark')
        if (document.querySelector('meta[name="theme-color"]') !== null) {
          document.querySelector('meta[name="theme-color"]').setAttribute('content', '#0d0d0d')
        }
      }
      const activateLightMode = () => {
        document.documentElement.setAttribute('data-theme', 'light')
        if (document.querySelector('meta[name="theme-color"]') !== null) {
          document.querySelector('meta[name="theme-color"]').setAttribute('content', '#ffffff')
        }
      }

      btf.activateDarkMode = activateDarkMode
      btf.activateLightMode = activateLightMode

      const theme = saveToLocal.get('theme')
    
          theme === 'dark' ? activateDarkMode() : theme === 'light' ? activateLightMode() : null
        
      
      const asideStatus = saveToLocal.get('aside-status')
      if (asideStatus !== undefined) {
        document.documentElement.classList.toggle('hide-aside', asideStatus === 'hide')
      }
    
      
    const detectApple = () => {
      if (/iPad|iPhone|iPod|Macintosh/.test(navigator.userAgent)) {
        document.documentElement.classList.add('apple')
      }
    }
    detectApple()
  
    })()
  </script><script>const GLOBAL_CONFIG = {
  root: '/',
  algolia: undefined,
  localSearch: {"path":"/search.xml","preload":false,"top_n_per_article":1,"unescape":false,"languages":{"hits_empty":"未找到符合您查询的内容：${query}","hits_stats":"共找到 ${hits} 篇文章"}},
  translate: undefined,
  highlight: {"plugin":"highlight.js","highlightCopy":true,"highlightLang":true,"highlightHeightLimit":false,"highlightFullpage":false,"highlightMacStyle":false},
  copy: {
    success: '复制成功',
    error: '复制失败',
    noSupport: '浏览器不支持'
  },
  relativeDate: {
    homepage: false,
    post: false
  },
  runtime: '',
  dateSuffix: {
    just: '刚刚',
    min: '分钟前',
    hour: '小时前',
    day: '天前',
    month: '个月前'
  },
  copyright: {"limitCount":150,"languages":{"author":"作者: funtim41@gmail.com","link":"链接: ","source":"来源: funtim的博客","info":"著作权归作者所有。商业转载请联系作者获得授权，非商业转载请注明出处。"}},
  lightbox: 'null',
  Snackbar: {"chs_to_cht":"已切换为繁体中文","cht_to_chs":"已切换为简体中文","day_to_night":"已切换为深色模式","night_to_day":"已切换为浅色模式","bgLight":"#49b1f5","bgDark":"#1f1f1f","position":"bottom-left"},
  infinitegrid: {
    js: 'https://cdn.jsdelivr.net/npm/@egjs/infinitegrid/dist/infinitegrid.min.js',
    buttonText: '加载更多'
  },
  isPhotoFigcaption: false,
  islazyload: false,
  isAnchor: true,
  percent: {
    toc: true,
    rightside: true,
  },
  autoDarkmode: false
}</script><script id="config-diff">var GLOBAL_CONFIG_SITE = {
  title: '41链接文件',
  isPost: true,
  isHome: false,
  isHighlightShrink: false,
  isToc: true,
  isShuoshuo: false
}</script><link rel="stylesheet" href="/css/bar.css"><meta name="generator" content="Hexo 7.3.0"></head><body><div id="web_bg" style="background: Color(#995a82);"></div><div id="sidebar"><div id="menu-mask"></div><div id="sidebar-menus"><div class="avatar-img text-center"><img src="/images/4stars.png" onerror="onerror=null;src='/img/friend_404.gif'" alt="avatar"/></div><div class="site-data text-center"><a href="/archives/"><div class="headline">文章</div><div class="length-num">51</div></a><a href="/tags/"><div class="headline">标签</div><div class="length-num">2</div></a><a href="/categories/"><div class="headline">分类</div><div class="length-num">3</div></a></div><div class="menus_items"><div class="menus_item"><a class="site-page" href="/"><i class="fa-fw fas fa-home"></i><span> Home</span></a></div><div class="menus_item"><a class="site-page" href="/archives/"><i class="fa-fw fas fa-archive"></i><span> Timeline</span></a></div><div class="menus_item"><a class="site-page" href="/tags/"><i class="fa-fw fas fa-tags"></i><span> Tags</span></a></div><div class="menus_item"><a class="site-page" href="/categories/"><i class="fa-fw fas fa-folder-open"></i><span> Categories</span></a></div><div class="menus_item"><a class="site-page" href="/Links/"><i class="fa-fw fas fa-link"></i><span> Links</span></a></div><div class="menus_item"><a class="site-page" href="/about/"><i class="fa-fw fas fa-heart"></i><span> About</span></a></div></div></div></div><div class="post" id="body-wrap"><header class="post-bg fixed" id="page-header" style="background-image: url(/images/topback.jpg);"><nav id="nav"><span id="blog-info"><a class="nav-site-title" href="/"><img class="site-icon" src="/images/OIP.jfif" alt="Logo"><span class="site-name">funtim的博客</span></a><a class="nav-page-title" href="/"><span class="site-name">41链接文件</span></a></span><div id="menus"><div id="search-button"><span class="site-page social-icon search"><i class="fas fa-search fa-fw"></i><span> 搜索</span></span></div><div class="menus_items"><div class="menus_item"><a class="site-page" href="/"><i class="fa-fw fas fa-home"></i><span> Home</span></a></div><div class="menus_item"><a class="site-page" href="/archives/"><i class="fa-fw fas fa-archive"></i><span> Timeline</span></a></div><div class="menus_item"><a class="site-page" href="/tags/"><i class="fa-fw fas fa-tags"></i><span> Tags</span></a></div><div class="menus_item"><a class="site-page" href="/categories/"><i class="fa-fw fas fa-folder-open"></i><span> Categories</span></a></div><div class="menus_item"><a class="site-page" href="/Links/"><i class="fa-fw fas fa-link"></i><span> Links</span></a></div><div class="menus_item"><a class="site-page" href="/about/"><i class="fa-fw fas fa-heart"></i><span> About</span></a></div></div><div id="toggle-menu"><span class="site-page"><i class="fas fa-bars fa-fw"></i></span></div></div></nav><div id="post-info"><h1 class="post-title">41链接文件</h1><div id="post-meta"><div class="meta-firstline"><span class="post-meta-date"><i class="far fa-calendar-alt fa-fw post-meta-icon"></i><span class="post-meta-label">发表于</span><time class="post-meta-date-created" datetime="2024-12-30T07:52:29.000Z" title="发表于 2024-12-30 15:52:29">2024-12-30</time><span class="post-meta-separator">|</span><i class="fas fa-history fa-fw post-meta-icon"></i><span class="post-meta-label">更新于</span><time class="post-meta-date-updated" datetime="2024-12-30T08:06:42.788Z" title="更新于 2024-12-30 16:06:42">2024-12-30</time></span><span class="post-meta-categories"><span class="post-meta-separator">|</span><i class="fas fa-inbox fa-fw post-meta-icon"></i><a class="post-meta-categories" href="/categories/Revit%E4%BA%8C%E6%AC%A1%E5%BC%80%E5%8F%91%E4%BA%BA%E5%91%98%E6%8C%87%E5%8D%97/">Revit二次开发人员指南</a></span></div><div class="meta-secondline"><span class="post-meta-separator">|</span><span class="post-meta-pv-cv" id="" data-flag-title=""><i class="far fa-eye fa-fw post-meta-icon"></i><span class="post-meta-label">浏览量:</span><span id="busuanzi_value_page_pv"><i class="fa-solid fa-spinner fa-spin"></i></span></span></div></div></div></header><main class="layout" id="content-inner"><div id="post"><article class="container post-content" id="article-container"><h1 id="链接文件"><a href="#链接文件" class="headerlink" title="链接文件"></a>链接文件</h1><p>Revit API可以确定Revit中的哪些图元是对外部文件（“链接文件”）的引用，并可以对Revit加载外部文件的方式进行一些修改。</p>
<p>包含ExternalFileReference的元素是引用基.rvt文件之外的某个文件的元素。示例包括Revit链接、CAD链接、存储注释记号文件位置的图元和渲染贴花。IsExternalFileReference（）返回元素是否表示外部文件。GetExternalFileReference（）返回给定Element的ExternalFileReference，其中包含与该元素引用的外部文件有关的信息。</p>
<p>以下类与Revit API中的链接文件关联：</p>
<ul>
<li>ExternalFileReference - 非Element类，包含Revit项目引用的单个外部文件的路径和类型信息。</li>
<li>ExternalFileUtils -一个实用程序类，允许用户查找所有外部文件引用，从元素中获取外部文件引用，或者告诉元素是否是外部文件引用。</li>
<li>RevitLinkType -表示链接到Revit项目的Revit文件的图元。</li>
<li>ModelPath - 包含文件（不一定是.rvt文件）路径信息的非元素类。路径可以指向本地或网络驱动器上的某个位置，也可以指向Revit Server位置。</li>
<li>ModelPathUtils -一个实用程序类，它提供了在字符串和ModelPaths之间进行转换的方法。</li>
<li>TransmissionData -一个类，用于存储文档中所有外部文件引用的信息。无需打开文档即可读取Revit项目的TransmissionData。</li>
</ul>
<p><strong>模型路径</strong></p>
<p>ModelPaths是指向另一个文件的路径。它们可以引用Revit模型，也可以引用Revit的任何外部文件引用（如DWG链接）。路径可以是相对路径，也可以是绝对路径，但它们必须包含指示文件类型的扩展名。相对路径通常相对于当前打开的文档。如果当前文档是工作共享的，则路径将被视为相对于中心模型。若要创建ModelPath，请使用派生类FilePath或ServerPath之一。</p>
<p>ModelPathUtils类包含用于将ModelPaths与用户可见的路径字符串相互转换的实用函数，以及用于确定字符串是否为有效的服务器路径的实用函数。</p>
<p>共享坐标使其他链接模型能够知道一个链接文件的位置。</p>
<ul>
<li><p>从指定的链接实例获取项目坐标。这适用于Revit链接（RevitLinkInstance）和DWG链接（ImportInstance）。</p>
</li>
<li><p>将共享坐标发布到指定的ProjectLocation。此方法仅适用于Revit链接。这些只读属性提供有关SiteLocation的地理坐标系的信息。地理坐标系是从AutoCAD或Civil 3D的DWG文件导入的。如果SiteLocation具有地理坐标系信息，则当模型的测量点移动时，SiteLocation的纬度和经度将自动更新。</p>
</li>
<li><p>SiteLocation. GeoCoordinateSystemId-获取与地理坐标系ID对应的字符串，例如SiteLocation的”AMG-50”或”Beijing1954&#x2F;a.GK3d-40”。如果没有为SiteLocation指定坐标系，则该值将为空字符串。</p>
</li>
<li><p>GeoCoordinateSystemDefinition -获取描述地理坐标系的XML字符串。如果没有为SiteLocation指定坐标系，则该值将为空字符串。</p>
</li>
</ul>
<p>本节中的页面</p>
<ul>
<li>Revit 链接</li>
<li>管理外部文件</li>
</ul>
<h2 id="Revit-链接"><a href="#Revit-链接" class="headerlink" title="Revit 链接"></a>Revit 链接</h2><p>Revit文档可以包含指向各种外部文件（包括其他Revit文档）的链接。Revit API中的这些链接类型由RevitLinkType和RevitLinkInstance类表示。RevitLinkType类表示引入到当前文档（“主体”）中的另一个Revit文档（“链接”），而RevitLinkInstance类表示RevitLinkType的实例。</p>
<p><strong>创建新链接</strong></p>
<p>要创建新的Revit链接，请使用静态RevitLinkType.Create（）方法（该方法将创建新的Revit链接类型并加载链接文档）和静态RevitLinkInstance.Create（）方法（将链接的实例放置在模型中）。RevitLinkType.Create（）方法需要一个文档（将作为宿主）、要链接的文件的ModelPath和RevitLinkOptions对象。RevitLinkOptions类表示用于创建和加载Revit链接的选项。选项包括Revit是否存储链接文件和工作集配置的相对路径或绝对路径。WorksetConfiguration类用于指定创建链接时将打开哪些工作集（如果有）。请注意，相对路径或绝对路径决定了Revit存储路径的方式，但传递到Create（）方法中的ModelPath需要完整的路径才能最初查找链接的文档。</p>
<p>下面的示例演示RevitLinkType.Create（）的用法。变量pathName是磁盘上要链接的文件的完整路径。</p>
<p>代码区域：创建新的Revit链接</p>
<figure class="highlight c#"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="keyword">public</span> ElementId <span class="title">CreateRevitLink</span>(<span class="params">Document doc, <span class="built_in">string</span> pathName</span>)</span></span><br><span class="line">&#123;</span><br><span class="line">    FilePath path = <span class="keyword">new</span> FilePath(pathName);</span><br><span class="line">    RevitLinkOptions options = <span class="keyword">new</span> RevitLinkOptions(<span class="literal">false</span>);</span><br><span class="line">    <span class="comment">// Create new revit link storing absolute path to file</span></span><br><span class="line">    LinkLoadResult result = RevitLinkType.Create(doc, path, options);</span><br><span class="line">    <span class="keyword">return</span> (result.ElementId);</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<p>创建RevitLinkType后，可以将实例添加到文档中。在下面的示例中，添加了两个RevitLinkType实例，偏移量为100 ‘。在创建RevitLinkInstance之前，Revit链接将显示在“管理链接”窗口中，但链接文件的图元在任何视图中都不可见。</p>
<p>代码区域：创建新的Revit Link实例</p>
<figure class="highlight c#"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="keyword">public</span> <span class="keyword">void</span> <span class="title">CreateLinkInstances</span>(<span class="params">Document doc, ElementId linkTypeId</span>)</span></span><br><span class="line">&#123;</span><br><span class="line">    <span class="comment">// Create revit link instance at origin</span></span><br><span class="line">    RevitLinkInstance.Create(doc, linkTypeId);</span><br><span class="line">    RevitLinkInstance instance2 = RevitLinkInstance.Create(doc, linkTypeId);</span><br><span class="line">    <span class="comment">// Offset second instance by 100 feet</span></span><br><span class="line">    Location location = instance2.Location;</span><br><span class="line">    location.Move(<span class="keyword">new</span> XYZ(<span class="number">0</span>, <span class="number">-100</span>, <span class="number">0</span>));</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<p>上面的例子使用本地磁盘上的文件。下面是一个更复杂的示例，涉及到Revit服务器上模型的链接。</p>
<p>代码区域：创建指向Revit服务器上模型的新Revit链接</p>
<figure class="highlight c#"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br><span class="line">23</span><br><span class="line">24</span><br><span class="line">25</span><br><span class="line">26</span><br><span class="line">27</span><br><span class="line">28</span><br><span class="line">29</span><br><span class="line">30</span><br><span class="line">31</span><br><span class="line">32</span><br><span class="line">33</span><br><span class="line">34</span><br><span class="line">35</span><br><span class="line">36</span><br><span class="line">37</span><br><span class="line">38</span><br><span class="line">39</span><br><span class="line">40</span><br><span class="line">41</span><br><span class="line">42</span><br><span class="line">43</span><br><span class="line">44</span><br><span class="line">45</span><br><span class="line">46</span><br><span class="line">47</span><br><span class="line">48</span><br><span class="line">49</span><br><span class="line">50</span><br><span class="line">51</span><br><span class="line">52</span><br><span class="line">53</span><br><span class="line">54</span><br><span class="line">55</span><br><span class="line">56</span><br><span class="line">57</span><br><span class="line">58</span><br><span class="line">59</span><br><span class="line">60</span><br><span class="line">61</span><br><span class="line">62</span><br><span class="line">63</span><br><span class="line">64</span><br><span class="line">65</span><br><span class="line">66</span><br><span class="line">67</span><br><span class="line">68</span><br><span class="line">69</span><br><span class="line">70</span><br><span class="line">71</span><br><span class="line">72</span><br><span class="line">73</span><br><span class="line">74</span><br><span class="line">75</span><br><span class="line">76</span><br><span class="line">77</span><br><span class="line">78</span><br><span class="line">79</span><br><span class="line">80</span><br><span class="line">81</span><br><span class="line">82</span><br><span class="line">83</span><br><span class="line">84</span><br><span class="line">85</span><br><span class="line">86</span><br><span class="line">87</span><br><span class="line">88</span><br><span class="line">89</span><br><span class="line">90</span><br><span class="line">91</span><br><span class="line">92</span><br><span class="line">93</span><br><span class="line">94</span><br><span class="line">95</span><br><span class="line">96</span><br><span class="line">97</span><br><span class="line">98</span><br><span class="line">99</span><br><span class="line">100</span><br><span class="line">101</span><br><span class="line">102</span><br><span class="line">103</span><br><span class="line">104</span><br><span class="line">105</span><br><span class="line">106</span><br><span class="line">107</span><br><span class="line">108</span><br><span class="line">109</span><br><span class="line">110</span><br><span class="line">111</span><br><span class="line">112</span><br><span class="line">113</span><br><span class="line">114</span><br><span class="line">115</span><br><span class="line">116</span><br><span class="line">117</span><br><span class="line">118</span><br><span class="line">119</span><br><span class="line">120</span><br><span class="line">121</span><br><span class="line">122</span><br><span class="line">123</span><br><span class="line">124</span><br><span class="line">125</span><br><span class="line">126</span><br><span class="line">127</span><br><span class="line">128</span><br><span class="line">129</span><br><span class="line">130</span><br><span class="line">131</span><br><span class="line">132</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="keyword">public</span> <span class="keyword">static</span> <span class="keyword">void</span> <span class="title">CreateLinkToServerModel</span>(<span class="params">UIApplication uiApp</span>)</span></span><br><span class="line">&#123;</span><br><span class="line">    UIDocument uiDoc = uiApp.ActiveUIDocument;</span><br><span class="line">    Document doc = uiDoc.Document;</span><br><span class="line"></span><br><span class="line">    <span class="comment">// Try to get the server path for the particular model on the server</span></span><br><span class="line">    Application application = uiApp.Application;</span><br><span class="line">    String hostId = application.GetRevitServerNetworkHosts().First();</span><br><span class="line">    String rootFolder = <span class="string">&quot;|&quot;</span>;</span><br><span class="line">    ModelPath serverPath = FindWSAPIModelPathOnServer(application, hostId, rootFolder, <span class="string">&quot;Wall pin model for updaters.rvt&quot;</span>);</span><br><span class="line"></span><br><span class="line">    <span class="keyword">using</span> (Transaction t = <span class="keyword">new</span> Transaction(doc, <span class="string">&quot;Create link&quot;</span>))</span><br><span class="line">    &#123;</span><br><span class="line">        t.Start();</span><br><span class="line">        RevitLinkOptions options = <span class="keyword">new</span> RevitLinkOptions(<span class="literal">false</span>);</span><br><span class="line"></span><br><span class="line">        LinkLoadResult result = RevitLinkType.Create(doc, serverPath, options);</span><br><span class="line"></span><br><span class="line">        RevitLinkInstance.Create(doc, result.ElementId);</span><br><span class="line">        t.Commit();</span><br><span class="line">    &#125;</span><br><span class="line">&#125;</span><br><span class="line"></span><br><span class="line"><span class="function"><span class="keyword">private</span> <span class="keyword">static</span> ModelPath <span class="title">FindWSAPIModelPathOnServer</span>(<span class="params">Application app, <span class="built_in">string</span> hostId, <span class="built_in">string</span> folderName, <span class="built_in">string</span> fileName</span>)</span></span><br><span class="line">&#123;</span><br><span class="line">    <span class="comment">// Connect to host to find list of available models (the &quot;/contents&quot; flag)</span></span><br><span class="line">    XmlDictionaryReader reader = GetResponse(app, hostId, folderName + <span class="string">&quot;/contents&quot;</span>);</span><br><span class="line">    <span class="built_in">bool</span> found = <span class="literal">false</span>;</span><br><span class="line"></span><br><span class="line">    <span class="comment">// Look for the target model name in top level folder</span></span><br><span class="line">    List folders = <span class="keyword">new</span> List();</span><br><span class="line">    <span class="keyword">while</span> (reader.Read())</span><br><span class="line">    &#123;</span><br><span class="line">        <span class="comment">// Save a list of subfolders, if found</span></span><br><span class="line">        <span class="keyword">if</span> (reader.NodeType == XmlNodeType.Element &amp;&amp; reader.Name == <span class="string">&quot;Folders&quot;</span>)</span><br><span class="line">        &#123;</span><br><span class="line">            <span class="keyword">while</span> (reader.Read())</span><br><span class="line">            &#123;</span><br><span class="line">                <span class="keyword">if</span> (reader.NodeType == XmlNodeType.EndElement &amp;&amp; reader.Name == <span class="string">&quot;Folders&quot;</span>)</span><br><span class="line">                    <span class="keyword">break</span>;</span><br><span class="line"></span><br><span class="line">                <span class="keyword">if</span> (reader.NodeType == XmlNodeType.Element &amp;&amp; reader.Name == <span class="string">&quot;Name&quot;</span>)</span><br><span class="line">                &#123;</span><br><span class="line">                    reader.Read();</span><br><span class="line">                    folders.Add(reader.Value);</span><br><span class="line">                &#125;</span><br><span class="line">            &#125;</span><br><span class="line">        &#125;</span><br><span class="line">        <span class="comment">// Check for a matching model at this folder level</span></span><br><span class="line">        <span class="keyword">if</span> (reader.NodeType == XmlNodeType.Element &amp;&amp; reader.Name == <span class="string">&quot;Models&quot;</span>)</span><br><span class="line">        &#123;</span><br><span class="line">            found = FindModelInServerResponseJson(reader, fileName);</span><br><span class="line">            <span class="keyword">if</span> (found)</span><br><span class="line">                <span class="keyword">break</span>;</span><br><span class="line">        &#125;</span><br><span class="line">    &#125;</span><br><span class="line"></span><br><span class="line">    reader.Close();</span><br><span class="line"></span><br><span class="line">    <span class="comment">// Build the model path to match the found model on the server</span></span><br><span class="line">    <span class="keyword">if</span> (found)</span><br><span class="line">    &#123;</span><br><span class="line">        <span class="comment">// Server URLs use &quot;|&quot; for folder separation, Revit API uses &quot;/&quot;</span></span><br><span class="line">        String folderNameFragment = folderName.Replace(<span class="string">&#x27;|&#x27;</span>, <span class="string">&#x27;/&#x27;</span>);</span><br><span class="line"></span><br><span class="line">        <span class="comment">// Add trailing &quot;/&quot; if not present</span></span><br><span class="line">        <span class="keyword">if</span> (!folderNameFragment.EndsWith(<span class="string">&quot;/&quot;</span>))</span><br><span class="line">            folderNameFragment += <span class="string">&quot;/&quot;</span>;</span><br><span class="line"></span><br><span class="line">        <span class="comment">// Build server path</span></span><br><span class="line">        ModelPath modelPath = <span class="keyword">new</span> ServerPath(hostId, folderNameFragment + fileName);</span><br><span class="line">        <span class="keyword">return</span> modelPath;</span><br><span class="line">    &#125;</span><br><span class="line">    <span class="keyword">else</span></span><br><span class="line">    &#123;</span><br><span class="line">        <span class="comment">// Try subfolders</span></span><br><span class="line">        <span class="keyword">foreach</span> (String folder <span class="keyword">in</span> folders)</span><br><span class="line">        &#123;</span><br><span class="line">            ModelPath modelPath = FindWSAPIModelPathOnServer(app, hostId, folder, fileName);</span><br><span class="line">            <span class="keyword">if</span> (modelPath != <span class="literal">null</span>)</span><br><span class="line">                <span class="keyword">return</span> modelPath;</span><br><span class="line">        &#125;</span><br><span class="line">    &#125;</span><br><span class="line"></span><br><span class="line">    <span class="keyword">return</span> <span class="literal">null</span>;</span><br><span class="line">&#125;</span><br><span class="line"></span><br><span class="line"><span class="comment">// This string is different for each RevitServer version</span></span><br><span class="line"><span class="keyword">private</span> <span class="keyword">static</span> <span class="built_in">string</span> s_revitServerVersion = <span class="string">&quot;/RevitServerAdminRESTService2014/AdminRESTService.svc/&quot;</span>;</span><br><span class="line"></span><br><span class="line"><span class="function"><span class="keyword">private</span> <span class="keyword">static</span> XmlDictionaryReader <span class="title">GetResponse</span>(<span class="params">Application app, <span class="built_in">string</span> hostId, <span class="built_in">string</span> info</span>)</span></span><br><span class="line">&#123;</span><br><span class="line">    <span class="comment">// Create request    WebRequest request = WebRequest.Create(&quot;http://&quot; + hostId + s_revitServerVersion + info);</span></span><br><span class="line">    request.Method = <span class="string">&quot;GET&quot;</span>;</span><br><span class="line"></span><br><span class="line">    <span class="comment">// Add the information the request needs</span></span><br><span class="line"></span><br><span class="line">    request.Headers.Add(<span class="string">&quot;User-Name&quot;</span>, app.Username);</span><br><span class="line">    request.Headers.Add(<span class="string">&quot;User-Machine-Name&quot;</span>, app.Username);</span><br><span class="line">    request.Headers.Add(<span class="string">&quot;Operation-GUID&quot;</span>, Guid.NewGuid().ToString());</span><br><span class="line"></span><br><span class="line">    <span class="comment">// Read the response</span></span><br><span class="line">    XmlDictionaryReaderQuotas quotas =</span><br><span class="line">        <span class="keyword">new</span> XmlDictionaryReaderQuotas();</span><br><span class="line">    XmlDictionaryReader jsonReader =</span><br><span class="line">        JsonReaderWriterFactory.CreateJsonReader(request.GetResponse().GetResponseStream(), quotas);</span><br><span class="line"></span><br><span class="line">    <span class="keyword">return</span> jsonReader;</span><br><span class="line">&#125;</span><br><span class="line"></span><br><span class="line"><span class="function"><span class="keyword">private</span> <span class="keyword">static</span> <span class="built_in">bool</span> <span class="title">FindModelInServerResponseJson</span>(<span class="params">XmlDictionaryReader reader, <span class="built_in">string</span> fileName</span>)</span></span><br><span class="line">&#123;</span><br><span class="line">    <span class="comment">// Read through entries in this section</span></span><br><span class="line">    <span class="keyword">while</span> (reader.Read())</span><br><span class="line">    &#123;</span><br><span class="line">        <span class="keyword">if</span> (reader.NodeType == XmlNodeType.EndElement &amp;&amp; reader.Name == <span class="string">&quot;Models&quot;</span>)</span><br><span class="line">            <span class="keyword">break</span>;</span><br><span class="line"></span><br><span class="line">        <span class="keyword">if</span> (reader.NodeType == XmlNodeType.Element &amp;&amp; reader.Name == <span class="string">&quot;Name&quot;</span>)</span><br><span class="line">        &#123;</span><br><span class="line">            reader.Read();</span><br><span class="line">            String modelName = reader.Value;</span><br><span class="line">            <span class="keyword">if</span> (modelName.Equals(fileName))</span><br><span class="line">            &#123;</span><br><span class="line">                <span class="comment">// Match found, stop looping and return</span></span><br><span class="line">                <span class="keyword">return</span> <span class="literal">true</span>;</span><br><span class="line">            &#125;</span><br><span class="line">        &#125;</span><br><span class="line">    &#125;</span><br><span class="line"></span><br><span class="line">    <span class="keyword">return</span> <span class="literal">false</span>;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<p>在下面的示例中，将获取WorksetConfiguration并对其进行修改，以便在创建新链接之前仅打开一个指定的工作集并将其设置回RevitLinkOptions。</p>
<p>代码区域：创建打开一个工作集的链接</p>
<figure class="highlight c#"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br><span class="line">23</span><br><span class="line">24</span><br><span class="line">25</span><br><span class="line">26</span><br><span class="line">27</span><br><span class="line">28</span><br><span class="line">29</span><br><span class="line">30</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="keyword">public</span> <span class="built_in">bool</span> <span class="title">CreateRevitLinkWithOneWorksetOpen</span>(<span class="params">Document doc, <span class="built_in">string</span> pathName, <span class="built_in">string</span> worksetName</span>)</span></span><br><span class="line">&#123;</span><br><span class="line">    FilePath path = <span class="keyword">new</span> FilePath(pathName);</span><br><span class="line">    RevitLinkOptions options = <span class="keyword">new</span> RevitLinkOptions(<span class="literal">true</span>);</span><br><span class="line"></span><br><span class="line">    <span class="comment">// Get info on all the user worksets in the project prior to opening</span></span><br><span class="line">    IList worksets = WorksharingUtils.GetUserWorksetInfo(path);</span><br><span class="line">    IList worksetIds = <span class="keyword">new</span> List();</span><br><span class="line">    <span class="comment">// Find worksetName</span></span><br><span class="line">    <span class="keyword">foreach</span> (WorksetPreview worksetPrev <span class="keyword">in</span> worksets)</span><br><span class="line">    &#123;</span><br><span class="line">        <span class="keyword">if</span> (worksetPrev.Name.CompareTo(worksetName) == <span class="number">0</span>)</span><br><span class="line">        &#123;</span><br><span class="line">            worksetIds.Add(worksetPrev.Id);</span><br><span class="line">            <span class="keyword">break</span>;</span><br><span class="line">        &#125;</span><br><span class="line">    &#125;</span><br><span class="line"></span><br><span class="line">    <span class="comment">// close all worksets but the one specified</span></span><br><span class="line">    WorksetConfiguration worksetConfig = <span class="keyword">new</span> WorksetConfiguration(WorksetConfigurationOption.CloseAllWorksets);</span><br><span class="line">    <span class="keyword">if</span> (worksetIds.Count &gt; <span class="number">0</span>)</span><br><span class="line">    &#123;</span><br><span class="line">        worksetConfig.Open(worksetIds);</span><br><span class="line">    &#125;</span><br><span class="line">    options.SetWorksetConfiguration(worksetConfig);</span><br><span class="line"></span><br><span class="line">    LinkLoadResult result = RevitLinkType.Create(doc, path, options);</span><br><span class="line">    RevitLinkType type = doc.GetElement(result.ElementId) <span class="keyword">as</span> RevitLinkType;</span><br><span class="line">    <span class="keyword">return</span> (result.LoadResult == LinkLoadResultType.LinkLoaded);</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<p>无论是创建还是加载链接，都将返回LinkLoadResult。此类有一个属性来确定链接是否已加载。它还有一个ElementId属性，该属性是创建或加载的链接模型的ID。 RevitLinkInstance.Create（ImportPlacement放置）创建链接的Revit项目的新实例（RevitLinkType）。根据输入放置类型，将按原点到原点或按共享坐标放置图形。 #加载和卸载链接 RevitLinkType有几种与加载链接相关的方法。Load（）、LoadFrom（）和Unload（）允许加载或卸载链接，或者从新位置加载链接。这些方法重新生成文档。文档的撤消历史记录将通过这些方法清除。所有显式启动的事务阶段（例如事务、事务组和子事务）必须在调用这些方法之前完成。 静态方法RevitLinkType.IsLoaded（）将返回链接是否已加载。 #获取链接信息 文档中的每个RevitLinkType都可以有一个或多个关联的RevitLinkType。RevitLinkInstance.GetLinkDocument（）方法返回与Revit链接关联的Document。不能修改此单据，这意味着不能执行需要交易或修改单据在内存中状态的操作（如保存和关闭）。 可以使用从RevitLinkInstance.GetTypeId（）方法获得的ElementId从文档中检索RevitLinkInstance的关联RevitLinkType。链接文件的RevitLinkType有几个与嵌套链接相关的方法和属性。链接到另一个文档的文档本身可能具有链接。如果RevitLinkType是嵌套链接（即，它有其他链接作为父链接），IsNested属性返回true;如果它是顶级链接，IsNested属性返回false。方法GetParentId（）将获取此链接的直接父级的ID，而GetRootId（）将返回此链接最终链接的顶级链接的ID。如果此链接是顶级链接，则这两个方法都将返回invalidElementId。方法GetChildIds（）将返回所有直接链接到此链接的链接的元素ID。 例如，如果C链接到文档B，而B又链接到文档A，则为C链接调用GetParentId（）将返回文档B的ID，为C链接调用GetRootId（）将返回文档A的ID。为文档A调用GetChildIds（）将只返回B的链接的id，因为C不是A下的直接链接。 RevitLinkType还有一个PathType属性，该属性指示外部文件参照的路径是相对于主体文件的位置（或相对于中心模型的位置（如果主体是工作共享的）），还是相对于磁盘或网络上某个位置的绝对路径，或者路径是相对于Revit Server位置。 RevitLinkType的AttachmentType属性指示链接是附件还是覆盖。“附件”链接被认为是其父链接的一部分，如果其父链接到另一个文档中，“附件”链接将被沿着。“覆盖”链接只有在直接打开父链接时才可见。 下面的示例获取文档中的所有RevitLinkList并显示有关它们的一些信息。</p>
<p>代码区域：获取链接信息</p>
<figure class="highlight c#"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="keyword">public</span> <span class="keyword">void</span> <span class="title">GetAllRevitLinkInstances</span>(<span class="params">Document doc</span>)</span></span><br><span class="line">&#123;</span><br><span class="line">    FilteredElementCollector collector = <span class="keyword">new</span> FilteredElementCollector(doc);</span><br><span class="line">    collector.OfClass(<span class="keyword">typeof</span>(RevitLinkInstance));</span><br><span class="line">    StringBuilder linkedDocs = <span class="keyword">new</span> StringBuilder();</span><br><span class="line">    <span class="keyword">foreach</span> (Element elem <span class="keyword">in</span> collector)</span><br><span class="line">    &#123;</span><br><span class="line">        RevitLinkInstance instance = elem <span class="keyword">as</span> RevitLinkInstance;</span><br><span class="line">        Document linkDoc = instance.GetLinkDocument();</span><br><span class="line">        linkedDocs.AppendLine(<span class="string">&quot;FileName: &quot;</span> + Path.GetFileName(linkDoc.PathName));</span><br><span class="line">        RevitLinkType type = doc.GetElement(instance.GetTypeId()) <span class="keyword">as</span> RevitLinkType;</span><br><span class="line">        linkedDocs.AppendLine(<span class="string">&quot;Is Nested: &quot;</span> + type.IsNestedLink.ToString());</span><br><span class="line">    &#125;</span><br><span class="line"></span><br><span class="line">    TaskDialog.Show(<span class="string">&quot;Revit Links in Document&quot;</span>, linkedDocs.ToString());</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<p><strong>链接几何图形</strong></p>
<p><strong>共享坐标</strong></p>
<p>RevitLinkType方法SavePositions（）和HasSaveablePositions（）支持将共享坐标更改保存回链接文档。使用HasSaveablePositions（）确定链接是否具有可以保存的共享定位更改。调用SavePositions（）将共享坐标更改保存回链接文档。SavePositions（）需要ISaveSharedCoordinatesCallback接口的实例，以解决Revit遇到已修改链接时的情况。接口的GetSaveModifiedLinksOption（）方法确定Revit是应保存链接、不保存链接还是完全放弃共享定位。</p>
<p>虽然SavePositions（）不清除文档的撤消历史记录，但它不能撤消，因为它将链接的共享坐标更改保存到磁盘。</p>
<p><strong>几何参照的转换</strong></p>
<p>Reference类具有与链接文件相关的成员，这些成员允许在仅引用链接内容的Reference对象和引用宿主的Reference对象之间进行转换。例如，这允许应用程序查看链接中的几何图形，查找所需的面，并将该面的参照转换为主体中适合用于放置基于面的实例的参照。此外，这些Reference成员还可以在主体中获取引用（例如，从尺寸或族中），并将其转换为链接中的引用，以便在Element.GetGeometryObjectFromReference（）中使用。</p>
<p>Reference.LinkedElementId属性表示此引用所引用的链接文档中顶级元素的ID，或InvalidElementId表示未引用链接RVT文件中元素的引用。Reference.RightLinkReference（）方法使用RevitLinkInstance从Revit链接中的参照创建Reference和Reference.ReferenceInLink（）方法可从宿主文件中的引用创建Revit链接中的引用</p>
<p><strong>拾取链接中的元素</strong></p>
<p>选择方法PickObject（）和PickObjects（）允许选择Revit链接中的对象。若要允许用户选择链接文件中的元素，请对PickObject（）或PickObjects（）的第一个参数使用ObjectType.LinkedElement枚举值。请注意，此选项仅允许选择链接中的元素，而不允许选择宿主文档中的元素。</p>
<p>在下面的示例中，ISelectionFilter用于仅允许在链接文件中选择墙。</p>
<p>代码区域：选择链接文件中的元素</p>
<figure class="highlight c#"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br><span class="line">23</span><br><span class="line">24</span><br><span class="line">25</span><br><span class="line">26</span><br><span class="line">27</span><br><span class="line">28</span><br><span class="line">29</span><br><span class="line">30</span><br><span class="line">31</span><br><span class="line">32</span><br><span class="line">33</span><br><span class="line">34</span><br><span class="line">35</span><br><span class="line">36</span><br><span class="line">37</span><br><span class="line">38</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="keyword">public</span> <span class="keyword">void</span> <span class="title">SelectElementsInLinkedDoc</span>(<span class="params">Autodesk.Revit.DB.Document document</span>)</span></span><br><span class="line">&#123;</span><br><span class="line">    UIDocument uidoc = <span class="keyword">new</span> UIDocument(document);</span><br><span class="line">    Selection choices = uidoc.Selection;</span><br><span class="line">    <span class="comment">// Pick one wall from Revit link</span></span><br><span class="line">    WallInLinkSelectionFilter wallFilter = <span class="keyword">new</span> WallInLinkSelectionFilter();</span><br><span class="line">    Reference elementRef = choices.PickObject(ObjectType.LinkedElement, wallFilter, <span class="string">&quot;Select a wall in a linked document&quot;</span>);</span><br><span class="line">    <span class="keyword">if</span> (elementRef != <span class="literal">null</span>)</span><br><span class="line">    &#123;</span><br><span class="line">        TaskDialog.Show(<span class="string">&quot;Revit&quot;</span>, <span class="string">&quot;Element from link document selected.&quot;</span>);</span><br><span class="line">    &#125;</span><br><span class="line">&#125;</span><br><span class="line"></span><br><span class="line"><span class="comment">// This filter allows selection of only a certain element type in a link instance.</span></span><br><span class="line"><span class="keyword">class</span> <span class="title">WallInLinkSelectionFilter</span> : <span class="title">ISelectionFilter</span></span><br><span class="line">&#123;</span><br><span class="line">    <span class="keyword">private</span> RevitLinkInstance m_currentInstance = <span class="literal">null</span>;</span><br><span class="line"></span><br><span class="line">    <span class="function"><span class="keyword">public</span> <span class="built_in">bool</span> <span class="title">AllowElement</span>(<span class="params">Element e</span>)</span></span><br><span class="line">    &#123;</span><br><span class="line">        <span class="comment">// Accept any link instance, and save the handle for use in AllowReference()</span></span><br><span class="line">        m_currentInstance = e <span class="keyword">as</span> RevitLinkInstance;</span><br><span class="line">        <span class="keyword">return</span> (m_currentInstance != <span class="literal">null</span>);</span><br><span class="line">    &#125;</span><br><span class="line"></span><br><span class="line">    <span class="function"><span class="keyword">public</span> <span class="built_in">bool</span> <span class="title">AllowReference</span>(<span class="params">Reference refer, XYZ point</span>)</span></span><br><span class="line">    &#123;</span><br><span class="line">        <span class="keyword">if</span> (m_currentInstance == <span class="literal">null</span>)</span><br><span class="line">            <span class="keyword">return</span> <span class="literal">false</span>;</span><br><span class="line"></span><br><span class="line">        <span class="comment">// Get the handle to the element in the link</span></span><br><span class="line">        Document linkedDoc = m_currentInstance.GetLinkDocument();</span><br><span class="line">        Element elem = linkedDoc.GetElement(refer.LinkedElementId);</span><br><span class="line"></span><br><span class="line">        <span class="comment">// Accept the selection if the element exists and is of the correct type</span></span><br><span class="line">        <span class="keyword">return</span> elem != <span class="literal">null</span> &amp;&amp; elem <span class="keyword">is</span> Wall;</span><br><span class="line">    &#125;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<h2 id="管理外部文件"><a href="#管理外部文件" class="headerlink" title="管理外部文件"></a>管理外部文件</h2><p><strong>ExternalFileUtils</strong> </p>
<p>顾名思义，这个实用程序类提供有关外部文件引用的信息。ExternalFileUtils.GetAllExternalFileReferences（）方法返回文档中作为外部文件引用的所有元素的ElementId集合。(Note它不会返回嵌套的Revit链接的ID;它只返回顶级参照。）此实用程序类还有另外两个方法，IsExternalFileReference（）和GetExternalFileReference（），它们执行与Element类的类似命名方法相同的功能，但可以在您拥有ElementId而不是首先获取Element时使用。</p>
<p>TransmissionDataTransmissionData存储有关外部文件引用的先前状态和请求状态的信息。这意味着它存储最近打开此TransmissionData文档时的引用的加载状态和路径。它还存储加载状态和路径信息，以便Revit在下次打开文档时执行操作。</p>
<p>因此，可以使用TransmissionData对外部文件参照执行操作，而无需打开整个关联的Revit文档。方法ReadTransmissionData和WriteTransmissionData可用于获取有关外部引用的信息，或更改该信息。例如，使用TransmissionData对象调用WriteTransmissionData，该对象已将所有引用设置为LinkedFileStatus.Unloaded，这将导致下次打开文档时不加载任何引用。</p>
<p>TransmissionData无法添加或删除对外部文件的引用。如果使用与外部文件引用元素不对应的ElementId调用AddExternalFileReference，则文件加载时将忽略该信息。</p>
<p>以下示例读取给定位置的文件的TransmissionData，并将所有Revit链接设置为在下次打开文档时卸载。</p>
<p>代码区域：卸载Revit链接</p>
<figure class="highlight c#"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br><span class="line">23</span><br><span class="line">24</span><br><span class="line">25</span><br><span class="line">26</span><br><span class="line">27</span><br><span class="line">28</span><br><span class="line">29</span><br><span class="line">30</span><br><span class="line">31</span><br><span class="line">32</span><br><span class="line">33</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="keyword">void</span> <span class="title">UnloadRevitLinks</span>(<span class="params">ModelPath location</span>)</span></span><br><span class="line"><span class="function"><span class="comment">/// This method will set all Revit links to be unloaded the next time the document at the given location is opened. </span></span></span><br><span class="line"><span class="function"><span class="comment">/// The TransmissionData for a given document only contains top-level Revit links, not nested links.</span></span></span><br><span class="line"><span class="function"><span class="comment">/// However, nested links will be unloaded if their parent links are unloaded, so this function only needs to look at the document&#x27;s immediate links. </span></span></span><br><span class="line">&#123;</span><br><span class="line">    <span class="comment">// access transmission data in the given Revit file</span></span><br><span class="line">    TransmissionData transData = TransmissionData.ReadTransmissionData(location);</span><br><span class="line">    <span class="keyword">if</span> (transData != <span class="literal">null</span>)</span><br><span class="line">    &#123;</span><br><span class="line">        <span class="comment">// collect all (immediate) external references in the model</span></span><br><span class="line">        ICollection externalReferences = transData.GetAllExternalFileReferenceIds();</span><br><span class="line">        <span class="comment">// find every reference that is a link</span></span><br><span class="line">        <span class="keyword">foreach</span> (ElementId refId <span class="keyword">in</span> externalReferences)</span><br><span class="line">        &#123;</span><br><span class="line">            ExternalFileReference extRef = transData.GetLastSavedReferenceData(refId);</span><br><span class="line">            <span class="keyword">if</span> (extRef.ExternalFileReferenceType == ExternalFileReferenceType.RevitLink)</span><br><span class="line">            &#123;</span><br><span class="line">                <span class="comment">// we do not want to change neither the path nor the path-type</span></span><br><span class="line">                <span class="comment">// we only want the links to be unloaded (shouldLoad = false)</span></span><br><span class="line">                transData.SetDesiredReferenceData(refId, extRef.GetPath(), extRef.PathType, <span class="literal">false</span>);</span><br><span class="line">            &#125;</span><br><span class="line">        &#125;</span><br><span class="line"></span><br><span class="line">        <span class="comment">// make sure the IsTransmitted property is set </span></span><br><span class="line">        transData.IsTransmitted = <span class="literal">true</span>;</span><br><span class="line">        <span class="comment">// modified transmission data must be saved back to the model</span></span><br><span class="line">        TransmissionData.WriteTransmissionData(location, transData);</span><br><span class="line">    &#125;</span><br><span class="line">    <span class="keyword">else</span></span><br><span class="line">    &#123;</span><br><span class="line">        Autodesk.Revit.UI.TaskDialog.Show(<span class="string">&quot;Unload Links&quot;</span>, <span class="string">&quot;The document does not have any transmission data&quot;</span>);</span><br><span class="line">    &#125;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<p>为服务器上的位置构造ModelPath</p>
<p>要读取TransmissionData对象，需要调用静态方法TransmissionData.ReadTransmissionData。它需要一个ModelPath对象。</p>
<p>有两种方法可以构造引用中心文件的ModelPath对象。第一种方法涉及使用ModelPathUtils和基本ModelPath类。其步骤如下：</p>
<ol>
<li><p>编写中心文件的用户可见路径字符串：ModelPathUtils.GetRevitServerPrefix（）+“相对路径”。</p>
<p>注意：“相对路径”中使用的文件夹分隔符是正斜杠（&#x2F;）。正确的分隔符是正斜杠。</p>
</li>
<li><p>通过ModelPathUtils.ConvertUserVisiblePathToModelPath（）方法创建ModelPath对象。传入在上一步中编写的字符串。</p>
</li>
<li><p>通过TransmissionData：：ReadTransmissionData（）方法读取传输数据。传入在上一步中获得的ModelPath。</p>
</li>
</ol>
<p>以下示例演示了此方法，假定中心文件testmodel.rvt存储在Revit Server的根文件夹SHACNG 035 WQRP中。</p>
<p>代码区域：使用ModelPath构造中心文件的路径</p>
<figure class="highlight c#"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br><span class="line">23</span><br><span class="line">24</span><br><span class="line">25</span><br><span class="line">26</span><br></pre></td><td class="code"><pre><span class="line">[<span class="meta">TransactionAttribute(Autodesk.Revit.Attributes.TransactionMode.Manual)</span>]</span><br><span class="line"><span class="keyword">public</span> <span class="keyword">class</span> <span class="title">RevitCommand</span> : <span class="title">IExternalCommand</span></span><br><span class="line">&#123;</span><br><span class="line">  <span class="function"><span class="keyword">public</span> Result <span class="title">Execute</span>(<span class="params">ExternalCommandData commandData,         <span class="keyword">ref</span> <span class="built_in">string</span> messages, ElementSet elements</span>)</span></span><br><span class="line">&#123;</span><br><span class="line">    UIApplication app = commandData.Application;</span><br><span class="line">    Document doc = app.ActiveUIDocument.Document;</span><br><span class="line">    Transaction trans = <span class="keyword">new</span> Transaction(doc, <span class="string">&quot;ExComm&quot;</span>);</span><br><span class="line">    trans.Start();</span><br><span class="line">    <span class="built_in">string</span> visiblePath = ModelPathUtils.GetRevitServerPrefix() + <span class="string">&quot;/testmodel.rvt&quot;</span>;</span><br><span class="line">    ModelPath serverPath = ModelPathUtils.ConvertUserVisiblePathToModelPath(visiblePath);</span><br><span class="line">    TransmissionData transData = TransmissionData.ReadTransmissionData(serverPath);</span><br><span class="line">    <span class="built_in">string</span> mymessage = <span class="literal">null</span>;</span><br><span class="line">    <span class="keyword">if</span> (transData != <span class="literal">null</span>)</span><br><span class="line">    &#123;</span><br><span class="line">         <span class="comment">//access the data in the transData here.</span></span><br><span class="line">    &#125;</span><br><span class="line">    <span class="keyword">else</span></span><br><span class="line">    &#123;</span><br><span class="line">      Autodesk.Revit.UI.TaskDialog.Show(<span class="string">&quot;Unload Links&quot;</span>,</span><br><span class="line">      <span class="string">&quot;The document does not have any transmission data&quot;</span>);</span><br><span class="line">    &#125;</span><br><span class="line">    trans.Commit();</span><br><span class="line">    <span class="keyword">return</span> Result.Succeeded;</span><br><span class="line">  &#125;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<p>构造引用中心文件的ModelPath对象的第二种方法是使用子类ServerPath。如果程序知道本地服务器名称，则可以使用此方法，但不建议使用此方法，因为Revit用户可以从Revit UI更改服务器名称。其步骤如下： 1. 使用ServerPath构造函数创建ServerPath对象。</p>
<figure class="highlight c#"><table><tr><td class="gutter"><pre><span class="line">1</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">new</span> ServerPath(“ServerNameOrServerIp”, “relative path without the initial forward slash”).</span><br></pre></td></tr></table></figure>

<p>注意：第一个参数是服务器名称，而不是ModelPathUtils.GetRevitServerPrefix（）返回的字符串，第二个参数不包括首个正斜杠。请参见下面的示例代码。文件夹分隔符也是一个正斜杠（&#x2F;）。 1. 通过TransmissionData.ReadTransmissionData（）方法读取TransmissionData对象。 下面的代码演示了此方法。</p>
<p>代码区域：使用ServerPath构造中心文件的路径</p>
<figure class="highlight c#"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br><span class="line">23</span><br><span class="line">24</span><br><span class="line">25</span><br><span class="line">26</span><br></pre></td><td class="code"><pre><span class="line">[<span class="meta">TransactionAttribute(Autodesk.Revit.Attributes.TransactionMode.Manual)</span>]</span><br><span class="line"><span class="keyword">public</span> <span class="keyword">class</span> <span class="title">RevitCommand</span> : <span class="title">IExternalCommand</span></span><br><span class="line">&#123;</span><br><span class="line">  <span class="function"><span class="keyword">public</span> Result <span class="title">Execute</span>(<span class="params">ExternalCommandData commandData,</span></span></span><br><span class="line"><span class="params"><span class="function">         <span class="keyword">ref</span> <span class="built_in">string</span> messages, ElementSet elements</span>)</span></span><br><span class="line">  &#123;</span><br><span class="line">    UIApplication app = commandData.Application;</span><br><span class="line">    Document doc = app.ActiveUIDocument.Document;</span><br><span class="line">    Transaction trans = <span class="keyword">new</span> Transaction(doc, <span class="string">&quot;ExComm&quot;</span>);</span><br><span class="line">    trans.Start();</span><br><span class="line">    ServerPath serverPath = <span class="keyword">new</span> ServerPath(<span class="string">&quot;SHACNG035WQRP&quot;</span>, <span class="string">&quot;testmodel.rvt&quot;</span>);</span><br><span class="line">    TransmissionData transData = TransmissionData.ReadTransmissionData(serverPath);</span><br><span class="line">    <span class="built_in">string</span> mymessage = <span class="literal">null</span>;</span><br><span class="line">    <span class="keyword">if</span> (transData != <span class="literal">null</span>)</span><br><span class="line">    &#123;</span><br><span class="line">       <span class="comment">//access the data in the transData here.</span></span><br><span class="line">    &#125;</span><br><span class="line">    <span class="keyword">else</span></span><br><span class="line">    &#123;</span><br><span class="line">      Autodesk.Revit.UI.TaskDialog.Show(<span class="string">&quot;Unload Links&quot;</span>,</span><br><span class="line">         <span class="string">&quot;The document does not have any transmission data&quot;</span>);</span><br><span class="line">    &#125;</span><br><span class="line">    trans.Commit();</span><br><span class="line">    <span class="keyword">return</span> Result.Succeeded;</span><br><span class="line">  &#125;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<h2 id="注：翻译自Revit-API-Developers-Guide"><a href="#注：翻译自Revit-API-Developers-Guide" class="headerlink" title="注：翻译自Revit API Developers Guide"></a><em><strong>注：</strong></em>翻译自<a target="_blank" rel="noopener" href="https://help.autodesk.com/view/RVT/2018/ENU/?guid=Revit_API_Revit_API_Developers_Guide_html">Revit API Developers Guide</a></h2></article><div class="tag_share"><div class="post-meta__tag-list"><a class="post-meta__tags" href="/tags/Revit/">Revit</a></div><div class="post-share"><div class="social-share" data-image="/images/4stars.png" data-sites="facebook,twitter,wechat,weibo,qq"></div><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/butterfly-extsrc/sharejs/dist/css/share.min.css" media="print" onload="this.media='all'"><script src="https://cdn.jsdelivr.net/npm/butterfly-extsrc/sharejs/dist/js/social-share.min.js" defer></script></div></div><nav class="pagination-post" id="pagination"><a class="pagination-related" href="/2024/12/30/%E4%BA%8C%E5%BC%80%E6%8C%87%E5%8D%97/42%E5%AF%BC%E5%87%BA/" title="42导出"><div class="cover" style="background: var(--default-bg-color)"></div><div class="info"><div class="info-1"><div class="info-item-1">上一篇</div><div class="info-item-2">42导出</div></div><div class="info-2"><div class="info-item-1">导出Revit API允许将Revit文档或其中的一部分导出为各种格式，以便与其他软件一起使用。Document类具有重载的Export（）方法，该方法将使用Revit中的内置导出器（如果可用）启动文档的导出。对于更高级的需求，可以使用Revit附加模块自定义某些类型的导出，例如导出到IFC和导出到Navisworks。(Note，Navisworks导出仅作为附加模块导出器提供）。 下表概述了Document.Export（）方法重载。 表：Document.Export（）方法    格式 Export() parameters Comments    gbXML String, String, MassGBXMLExportOptions 从体量模型文档导出gbXML文件   gbXML String, String, GBXMLExportOptions 以Green-Building XML格式导出文档。如果将EnergyDataSettings设置为使用概念模型，则无法使用此函数：请改用上述方法。   IFC String, String,...</div></div></div></a><a class="pagination-related" href="/2024/12/30/%E4%BA%8C%E5%BC%80%E6%8C%87%E5%8D%97/40%E6%96%BD%E5%B7%A5%E5%BB%BA%E6%A8%A1/" title="40施工建模"><div class="cover" style="background: var(--default-bg-color)"></div><div class="info text-right"><div class="info-1"><div class="info-item-1">下一篇</div><div class="info-item-2">40施工建模</div></div><div class="info-2"><div class="info-item-1">施工建模Revit API允许将图元划分为子零件或收集到程序集中，以支持构造建模工作流，这与使用Revit用户界面的方法大致相同。零件和程序集都可以独立地进行明细表、标记、过滤和导出。您也可以将零件分割成更小的零件。创建程序集类型后，可以在项目中放置其他实例并生成独立的程序集视图。 与构造建模相关的主要类有：  AssemblyInstance -这个类结合了多个元素，用于标记、过滤、调度和创建隔离的装配视图。 AssemblyType - 表示构造程序集元素的类型。在项目中创建的每个新的唯一程序集都会自动创建一个相应的AssemblyType。可以从现有AssemblyType将新AssemblyInstance放置到文档中。 PartUtils - 这个实用程序类包含通用的程序集实用程序方法，包括创建程序集、划分程序集和获取程序集信息的能力。 AssemblyViewUtils - 用于创建各种类型的装配视图的实用程序类。  ...</div></div></div></a></nav><div class="relatedPosts"><div class="headline"><i class="fas fa-thumbs-up fa-fw"></i><span>相关推荐</span></div><div class="relatedPosts-list"><a class="pagination-related" href="/2024/11/18/RevitApi%E5%90%88%E9%9B%86/Autodesk.RevitAddIns%20Namespace/" title="Autodesk.RevitAddIns Namespace"><div class="cover" style="background: var(--default-bg-color)"></div><div class="info text-center"><div class="info-1"><div class="info-item-1"><i class="far fa-calendar-alt fa-fw"></i> 2024-11-18</div><div class="info-item-2">Autodesk.RevitAddIns Namespace</div></div><div class="info-2"><div class="info-item-1">Autodesk.RevitAddIns Namespace类AddInManifestUtility此静态类提供从 Revit .addin 文件中读取清单内容的访问。   方法  GetRevitAddInBundleManifests  GetRevitAddInManifest  GetRevitAddInManifests     RevitAddInApplication表示 Revit 外部应用程序。  构造器  RevitAddInApplication 创建 external application info 类的新实例。    属性  Name  Application name    继承关系  System.Object  Autodesk.RevitAddIns.RevitAddInItem  Autodesk.RevitAddIns.RevitAddInApplication    RevitAddInCommand表示 Revit 外部命令。  构造器  RevitAddInCommand 创建 Add-In Command info...</div></div></div></a><a class="pagination-related" href="/2024/11/18/RevitApi%E5%90%88%E9%9B%86/Autodesk.Revit.DB%20CurveArray/" title="Autodesk.Revit.DB CurveArray"><div class="cover" style="background: var(--default-bg-color)"></div><div class="info text-center"><div class="info-1"><div class="info-item-1"><i class="far fa-calendar-alt fa-fw"></i> 2024-11-18</div><div class="info-item-2">Autodesk.Revit.DB CurveArray</div></div><div class="info-2"><div class="info-item-1">Autodesk.Revit.DB CurveArray可以包含曲线的数组。 语法1public class CurveArray : APIObject, IEnumerable  继承层次结构System Object ​	Autodesk.Revit.DB APIObject ​		Autodesk.Revit.DB CurveArray 另见CurveArray Members Autodesk.Revit.DB Namespace 构造函数CurveArray创建CurveArray类的新实例 方法Append将曲线添加到数组的末尾。 Clear从数组中删除每条曲线，使其为空。 ForwardIterator将一个向前移动的迭代器添加到数组中。 GetEnumerator将一个向前移动的迭代器添加到数组中。 Insert将指定的曲线插入数组。 ReverseIterator返回一个向后移动的迭代器到数组。 属性IsEmpty测试数组是否为空。 Item获取或设置数组中指定索引处的曲线。 Size返回数组中的曲线数。 注：翻译自Revit Api docs 2018</div></div></div></a><a class="pagination-related" href="/2024/12/10/RevitApi%E5%90%88%E9%9B%86/Autodesk.Revit.DB%20Opening/" title="Autodesk.Revit.DB Opening"><div class="cover" style="background: var(--default-bg-color)"></div><div class="info text-center"><div class="info-1"><div class="info-item-1"><i class="far fa-calendar-alt fa-fw"></i> 2024-12-10</div><div class="info-item-2">Autodesk.Revit.DB Opening</div></div><div class="info-2"><div class="info-item-1">Autodesk.Revit.DB OpeningAutodesk Revit项目或族文档中的洞口。 语法1public class Opening : Element  附注该对象表示各种不同类型的洞口：  墙中由修订项目中的两个边界点创建的矩形洞口。 由应用于屋顶、楼板、天花板、梁、支撑或柱的一组曲线创建的洞口。 一个垂直的竖井开口延伸到一个或多个水平。 在族文档中的墙或天花板上创建的简单洞口。  根据打开的类型，此类的某些属性将不可用。 这个对象派生自Element基对象，并且支持该对象的所有方法，例如检索该对象的参数的能力。此对象还支持访问结构分析模型，但此功能仅适用于Autodesk Revit Structure。 示例123456789101112131415161718192021222324252627282930313233343536373839404142434445464748495051### private void Getinfo_Opening(Opening opening)&#123;    string message =...</div></div></div></a><a class="pagination-related" href="/2024/12/10/RevitApi%E5%90%88%E9%9B%86/Autodesk.Revit.DB%20ReferenceIntersector/" title="Autodesk.Revit.DB ReferenceIntersector"><div class="cover" style="background: var(--default-bg-color)"></div><div class="info text-center"><div class="info-1"><div class="info-item-1"><i class="far fa-calendar-alt fa-fw"></i> 2024-12-10</div><div class="info-item-2">Autodesk.Revit.DB ReferenceIntersector</div></div><div class="info-2"><div class="info-item-1">Autodesk.Revit.DB ReferenceIntersector用于查找和返回与从原点和方向创建的射线相交的元素的类。 语法1public class ReferenceIntersector : IDisposable    附注可以构造此类的实例，以返回与由原点和方向创建的射线，或者基于过滤和标志返回元素的子集。 调用者可以选择使用ElementFilter过滤结果，或者通过应用特定的可接受的元素。 调用方还可以指定要返回的对象的类型， 整个元素、几何体对象或其组合。 在所有情况下，要求调用者提供 用于评估的3D视图;输入视图上的视图和可见性设置将确定 返回特定元素（例如，此工具永远不会返回隐藏元素、 和几何图形位于视图剖面框之外的元素）。 该类配置为可以构建单个实例，并用于对多个不同光线进行多次评估。在同一个 ReferenceIntersector 上的调用之间，评估结果不会被保留。 该类还提供了一个选项，用于返回在Revit链接中遇到的图元结果。 当设置 FindReferencesInRevitLinks 标志...</div></div></div></a><a class="pagination-related" href="/2024/12/19/RevitApi%E5%90%88%E9%9B%86/Autodesk.Revit.UI.Selection%20Namespace/" title="Autodesk.Revit.UI.Selection"><div class="cover" style="background: var(--default-bg-color)"></div><div class="info text-center"><div class="info-1"><div class="info-item-1"><i class="far fa-calendar-alt fa-fw"></i> 2024-12-19</div><div class="info-item-2">Autodesk.Revit.UI.Selection</div></div><div class="info-2"><div class="info-item-1">Autodesk.Revit.UI.SelectionClassesPickedBox包含两个 XYZ 点的类，表示屏幕上的选取框。  Properties  Max 最大坐标数（拾取框的右上角）。  Min 最小坐标（拾取框的左下角）。     SelectableInViewFilter一个过滤器，用于传递在给定视图中可选的元素。  Constructors  SelectableInViewFilter  (Document, ElementId) 构造 SelectableInViewFilter 的新实例。  SelectableInViewFilter (Document, ElementId, Boolean) 构造 SelectableInViewFilter 的新实例，并可选择传递所有不可选择的元素。    Methods  PassesFilter(Element) 将筛选器应用于给定元素。  PassesFilter(Document,...</div></div></div></a><a class="pagination-related" href="/2024/12/20/RevitApi%E5%90%88%E9%9B%86/Autodesk.Revit.DB%20Transform/" title="Autodesk.Revit.DB Transform"><div class="cover" style="background: var(--default-bg-color)"></div><div class="info text-center"><div class="info-1"><div class="info-item-1"><i class="far fa-calendar-alt fa-fw"></i> 2024-12-20</div><div class="info-item-2">Autodesk.Revit.DB Transform</div></div><div class="info-2"><div class="info-item-1">Autodesk.Revit.DB Transform仿射三维空间的一个变换。 语法public class Transform : APIObject示例12345678910111213141516171819202122### public static XYZ TransformPoint(XYZ point, Transform transform)&#123;    double x = point.X;    double y = point.Y;    double z = point.Z;    //transform basis of the old coordinate system in the new coordinate // system    XYZ b0 = transform.get_Basis(0);    XYZ b1 = transform.get_Basis(1);    XYZ b2 = transform.get_Basis(2);    XYZ origin = transform.Origin;       ...</div></div></div></a></div></div><hr class="custom-hr"/><div id="post-comment"><div class="comment-head"><div class="comment-headline"><i class="fas fa-comments fa-fw"></i><span> 评论</span></div></div><div class="comment-wrap"><div><div id="giscus-wrap"></div></div></div></div></div><div class="aside-content" id="aside-content"><div class="card-widget card-info text-center"><div class="avatar-img"><img src="/images/4stars.png" onerror="this.onerror=null;this.src='/img/friend_404.gif'" alt="avatar"/></div><div class="author-info-name">funtim41@gmail.com</div><div class="author-info-description">实践-认识-再实践-再认识</div><div class="site-data"><a href="/archives/"><div class="headline">文章</div><div class="length-num">51</div></a><a href="/tags/"><div class="headline">标签</div><div class="length-num">2</div></a><a href="/categories/"><div class="headline">分类</div><div class="length-num">3</div></a></div><a id="card-info-btn" target="_blank" rel="noopener" href="https://github.com/FunTim41"><i class="fab fa-github"></i><span>Follow Me</span></a><div class="card-info-social-icons"><a class="social-icon" href="https://github.com/FunTim41" target="_blank" title="Github"><i class="fab fa-github" style="color: #FFFFFF;"></i></a></div></div><div class="card-widget card-announcement"><div class="item-headline"><i class="fas fa-bullhorn fa-shake"></i><span>公告</span></div><div class="announcement_content">This is my Blog</div></div><div class="sticky_layout"><div class="card-widget" id="card-toc"><div class="item-headline"><i class="fas fa-stream"></i><span>目录</span><span class="toc-percentage"></span></div><div class="toc-content"><ol class="toc"><li class="toc-item toc-level-1"><a class="toc-link" href="#%E9%93%BE%E6%8E%A5%E6%96%87%E4%BB%B6"><span class="toc-number">1.</span> <span class="toc-text">链接文件</span></a><ol class="toc-child"><li class="toc-item toc-level-2"><a class="toc-link" href="#Revit-%E9%93%BE%E6%8E%A5"><span class="toc-number">1.1.</span> <span class="toc-text">Revit 链接</span></a></li><li class="toc-item toc-level-2"><a class="toc-link" href="#%E7%AE%A1%E7%90%86%E5%A4%96%E9%83%A8%E6%96%87%E4%BB%B6"><span class="toc-number">1.2.</span> <span class="toc-text">管理外部文件</span></a></li><li class="toc-item toc-level-2"><a class="toc-link" href="#%E6%B3%A8%EF%BC%9A%E7%BF%BB%E8%AF%91%E8%87%AARevit-API-Developers-Guide"><span class="toc-number">1.3.</span> <span class="toc-text">注：翻译自Revit API Developers Guide</span></a></li></ol></li></ol></div></div><div class="card-widget card-recent-post"><div class="item-headline"><i class="fas fa-history"></i><span>最新文章</span></div><div class="aside-list"><div class="aside-list-item no-cover"><div class="content"><a class="title" href="/2025/01/08/%E5%8D%9A%E5%AE%A2%E9%85%8D%E7%BD%AE/Hexo+Butterfly%E4%BB%A3%E7%A0%81%E5%9D%97%E6%B0%B4%E5%B9%B3%E6%BB%9A%E5%8A%A8%E6%9D%A1/" title="Hexo+Butterfly代码块水平滚动条">Hexo+Butterfly代码块水平滚动条</a><time datetime="2025-01-08T03:43:27.151Z" title="更新于 2025-01-08 11:43:27">2025-01-08</time></div></div><div class="aside-list-item no-cover"><div class="content"><a class="title" href="/2024/11/18/RevitApi%E5%90%88%E9%9B%86/Autodesk.RevitAddIns%20Namespace/" title="Autodesk.RevitAddIns Namespace">Autodesk.RevitAddIns Namespace</a><time datetime="2025-01-05T09:13:27.547Z" title="更新于 2025-01-05 17:13:27">2025-01-05</time></div></div><div class="aside-list-item no-cover"><div class="content"><a class="title" href="/2024/11/18/RevitApi%E5%90%88%E9%9B%86/Autodesk.Revit.DB%20CurveArray/" title="Autodesk.Revit.DB CurveArray">Autodesk.Revit.DB CurveArray</a><time datetime="2025-01-04T02:50:53.238Z" title="更新于 2025-01-04 10:50:53">2025-01-04</time></div></div><div class="aside-list-item no-cover"><div class="content"><a class="title" href="/2024/12/10/RevitApi%E5%90%88%E9%9B%86/Autodesk.Revit.DB%20Opening/" title="Autodesk.Revit.DB Opening">Autodesk.Revit.DB Opening</a><time datetime="2025-01-04T02:47:58.908Z" title="更新于 2025-01-04 10:47:58">2025-01-04</time></div></div><div class="aside-list-item no-cover"><div class="content"><a class="title" href="/2024/12/10/RevitApi%E5%90%88%E9%9B%86/Autodesk.Revit.DB%20ReferenceIntersector/" title="Autodesk.Revit.DB ReferenceIntersector">Autodesk.Revit.DB ReferenceIntersector</a><time datetime="2025-01-04T02:47:17.298Z" title="更新于 2025-01-04 10:47:17">2025-01-04</time></div></div></div></div></div></div></main><footer id="footer" style="background-image: url(/images/topback.jpg);"><div id="footer-wrap"><div class="copyright">&copy;2024 - 2025 By funtim41@gmail.com</div><div class="framework-info"><span>框架 </span><a target="_blank" rel="noopener" href="https://hexo.io">Hexo</a><span class="footer-separator">|</span><span>主题 </span><a target="_blank" rel="noopener" href="https://github.com/jerryc127/hexo-theme-butterfly">Butterfly</a></div><div class="footer_custom_text">学而不思则罔，思而不学则殆。</div></div></footer></div><div id="rightside"><div id="rightside-config-hide"><button id="readmode" type="button" title="阅读模式"><i class="fas fa-book-open"></i></button><button id="darkmode" type="button" title="日间和夜间模式切换"><i class="fas fa-adjust"></i></button><button id="hide-aside-btn" type="button" title="单栏和双栏切换"><i class="fas fa-arrows-alt-h"></i></button></div><div id="rightside-config-show"><button id="rightside-config" type="button" title="设置"><i class="fas fa-cog fa-spin"></i></button><button class="close" id="mobile-toc-button" type="button" title="目录"><i class="fas fa-list-ul"></i></button><a id="to_comment" href="#post-comment" title="前往评论"><i class="fas fa-comments"></i></a><button id="go-up" type="button" title="回到顶部"><span class="scroll-percent"></span><i class="fas fa-arrow-up"></i></button></div></div><div><script src="/js/utils.js"></script><script src="/js/main.js"></script><script src="https://cdn.jsdelivr.net/npm/node-snackbar/dist/snackbar.min.js"></script><script>(() => {
  const panguFn = () => {
    if (typeof pangu === 'object') pangu.autoSpacingPage()
    else {
      btf.getScript('https://cdn.jsdelivr.net/npm/pangu/dist/browser/pangu.min.js')
        .then(() => {
          pangu.autoSpacingPage()
        })
    }
  }

  const panguInit = () => {
    if (false){
      GLOBAL_CONFIG_SITE.isPost && panguFn()
    } else {
      panguFn()
    }
  }

  btf.addGlobalFn('pjaxComplete', panguInit, 'pangu')
  document.addEventListener('DOMContentLoaded', panguInit)
})()</script><div class="js-pjax"><script>(() => {
  const isShuoshuo = GLOBAL_CONFIG_SITE.isShuoshuo
  const option = null

  const getGiscusTheme = theme => theme === 'dark' ? 'dark' : 'light'

  const createScriptElement = config => {
    const ele = document.createElement('script')
    Object.entries(config).forEach(([key, value]) => {
      ele.setAttribute(key, value)
    })
    return ele
  }

  const loadGiscus = (el = document, key) => {
    const mappingConfig = isShuoshuo
      ? { 'data-mapping': 'specific', 'data-term': key }
      : { 'data-mapping': (option && option['data-mapping']) || 'pathname' }

    const giscusConfig = {
      src: 'https://giscus.app/client.js',
      'data-repo': 'FunTim41/funtim41.github.io',
      'data-repo-id': 'R_kgDONjG8ww',
      'data-category-id': 'DIC_kwDONjG8w84Cllg2',
      'data-theme': getGiscusTheme(document.documentElement.getAttribute('data-theme')),
      'data-reactions-enabled': '1',
      crossorigin: 'anonymous',
      async: true,
      ...option,
      ...mappingConfig
    }

    const scriptElement = createScriptElement(giscusConfig)

    el.querySelector('#giscus-wrap').appendChild(scriptElement)

    if (isShuoshuo) {
      window.shuoshuoComment.destroyGiscus = () => {
        if (el.children.length) {
          el.innerHTML = ''
          el.classList.add('no-comment')
        }
      }
    }
  }

  const changeGiscusTheme = theme => {
    const iframe = document.querySelector('#giscus-wrap iframe')
    if (iframe) {
      const message = {
        giscus: {
          setConfig: {
            theme: getGiscusTheme(theme)
          }
        }
      }
      iframe.contentWindow.postMessage(message, 'https://giscus.app')
    }
  }

  btf.addGlobalFn('themeChange', changeGiscusTheme, 'giscus')

  if (isShuoshuo) {
    'Giscus' === 'Giscus'
      ? window.shuoshuoComment = { loadComment: loadGiscus }
      : window.loadOtherComment = loadGiscus
    return
  }

  if ('Giscus' === 'Giscus' || !false) {
    if (false) btf.loadComment(document.getElementById('giscus-wrap'), loadGiscus)
    else loadGiscus()
  } else {
    window.loadOtherComment = loadGiscus
  }
})()</script></div><script defer="defer" id="fluttering_ribbon" mobile="false" src="https://cdn.jsdelivr.net/npm/butterfly-extsrc/dist/canvas-fluttering-ribbon.min.js"></script><script async data-pjax src="//busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js"></script><div id="local-search"><div class="search-dialog"><nav class="search-nav"><span class="search-dialog-title">搜索</span><span id="loading-status"></span><button class="search-close-button"><i class="fas fa-times"></i></button></nav><div class="text-center" id="loading-database"><i class="fas fa-spinner fa-pulse"></i><span>  数据加载中</span></div><div class="search-wrap"><div id="local-search-input"><div class="local-search-box"><input class="local-search-box--input" placeholder="搜索文章" type="text"/></div></div><hr/><div id="local-search-results"></div><div id="local-search-stats-wrap"></div></div></div><div id="search-mask"></div><script src="/js/search/local-search.js"></script></div></div></body></html>