<!DOCTYPE html><html lang="zh-CN" data-theme="light"><head><meta charset="UTF-8"><meta http-equiv="X-UA-Compatible" content="IE=edge"><meta name="viewport" content="width=device-width, initial-scale=1.0,viewport-fit=cover"><title>23DirectShape | funtim的博客</title><meta name="author" content="funtim41@gmail.com"><meta name="copyright" content="funtim41@gmail.com"><meta name="format-detection" content="telephone=no"><meta name="theme-color" content="#ffffff"><meta name="description" content="DirectShape此图元类型可以在项目或族文档中存储通过导入操作或计算获得的任意几何图形。 DirectShape元素和相关类支持在Revit文档中存储外部创建的几何形状的功能。几何体可以包括闭合实体或网格。DirectShape主要用于从其他数据格式（如IFC或STEP）导入形状，在这些格式中，没有足够的信息来创建“真实的”Revit图元。 可以为DirectShape对象指定顶级模型类别，">
<meta property="og:type" content="article">
<meta property="og:title" content="23DirectShape">
<meta property="og:url" content="https://funtim41.github.io/2024/12/24/Revit%E4%BA%8C%E5%BC%80%E6%8C%87%E5%8D%97/23DirectShape/">
<meta property="og:site_name" content="funtim的博客">
<meta property="og:description" content="DirectShape此图元类型可以在项目或族文档中存储通过导入操作或计算获得的任意几何图形。 DirectShape元素和相关类支持在Revit文档中存储外部创建的几何形状的功能。几何体可以包括闭合实体或网格。DirectShape主要用于从其他数据格式（如IFC或STEP）导入形状，在这些格式中，没有足够的信息来创建“真实的”Revit图元。 可以为DirectShape对象指定顶级模型类别，">
<meta property="og:locale" content="zh_CN">
<meta property="og:image" content="https://funtim41.github.io/images/4stars.png">
<meta property="article:published_time" content="2024-12-24T01:55:32.000Z">
<meta property="article:modified_time" content="2025-01-13T14:21:19.410Z">
<meta property="article:author" content="funtim41@gmail.com">
<meta property="article:tag" content="Revit">
<meta name="twitter:card" content="summary">
<meta name="twitter:image" content="https://funtim41.github.io/images/4stars.png"><link rel="shortcut icon" href="/images/OIP.jfif"><link rel="canonical" href="https://funtim41.github.io/2024/12/24/Revit%E4%BA%8C%E5%BC%80%E6%8C%87%E5%8D%97/23DirectShape/"><link rel="preconnect" href="//cdn.jsdelivr.net"/><link rel="stylesheet" href="/css/index.css"><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free/css/all.min.css"><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/node-snackbar/dist/snackbar.min.css" media="print" onload="this.media='all'"><script>
    (() => {
      
    const saveToLocal = {
      set: (key, value, ttl) => {
        if (!ttl) return
        const expiry = Date.now() + ttl * 86400000
        localStorage.setItem(key, JSON.stringify({ value, expiry }))
      },
      get: key => {
        const itemStr = localStorage.getItem(key)
        if (!itemStr) return undefined
        const { value, expiry } = JSON.parse(itemStr)
        if (Date.now() > expiry) {
          localStorage.removeItem(key)
          return undefined
        }
        return value
      }
    }

    window.btf = {
      saveToLocal,
      getScript: (url, attr = {}) => new Promise((resolve, reject) => {
        const script = document.createElement('script')
        script.src = url
        script.async = true
        Object.entries(attr).forEach(([key, val]) => script.setAttribute(key, val))
        script.onload = script.onreadystatechange = () => {
          if (!script.readyState || /loaded|complete/.test(script.readyState)) resolve()
        }
        script.onerror = reject
        document.head.appendChild(script)
      }),
      getCSS: (url, id) => new Promise((resolve, reject) => {
        const link = document.createElement('link')
        link.rel = 'stylesheet'
        link.href = url
        if (id) link.id = id
        link.onload = link.onreadystatechange = () => {
          if (!link.readyState || /loaded|complete/.test(link.readyState)) resolve()
        }
        link.onerror = reject
        document.head.appendChild(link)
      }),
      addGlobalFn: (key, fn, name = false, parent = window) => {
        if (!false && key.startsWith('pjax')) return
        const globalFn = parent.globalFn || {}
        globalFn[key] = globalFn[key] || {}
        globalFn[key][name || Object.keys(globalFn[key]).length] = fn
        parent.globalFn = globalFn
      }
    }
  
      
      const activateDarkMode = () => {
        document.documentElement.setAttribute('data-theme', 'dark')
        if (document.querySelector('meta[name="theme-color"]') !== null) {
          document.querySelector('meta[name="theme-color"]').setAttribute('content', '#0d0d0d')
        }
      }
      const activateLightMode = () => {
        document.documentElement.setAttribute('data-theme', 'light')
        if (document.querySelector('meta[name="theme-color"]') !== null) {
          document.querySelector('meta[name="theme-color"]').setAttribute('content', '#ffffff')
        }
      }

      btf.activateDarkMode = activateDarkMode
      btf.activateLightMode = activateLightMode

      const theme = saveToLocal.get('theme')
    
          theme === 'dark' ? activateDarkMode() : theme === 'light' ? activateLightMode() : null
        
      
      const asideStatus = saveToLocal.get('aside-status')
      if (asideStatus !== undefined) {
        document.documentElement.classList.toggle('hide-aside', asideStatus === 'hide')
      }
    
      
    const detectApple = () => {
      if (/iPad|iPhone|iPod|Macintosh/.test(navigator.userAgent)) {
        document.documentElement.classList.add('apple')
      }
    }
    detectApple()
  
    })()
  </script><script>const GLOBAL_CONFIG = {
  root: '/',
  algolia: undefined,
  localSearch: {"path":"/search.xml","preload":false,"top_n_per_article":1,"unescape":false,"languages":{"hits_empty":"未找到符合您查询的内容：${query}","hits_stats":"共找到 ${hits} 篇文章"}},
  translate: undefined,
  highlight: {"plugin":"highlight.js","highlightCopy":true,"highlightLang":true,"highlightHeightLimit":false,"highlightFullpage":false,"highlightMacStyle":false},
  copy: {
    success: '复制成功',
    error: '复制失败',
    noSupport: '浏览器不支持'
  },
  relativeDate: {
    homepage: false,
    post: false
  },
  runtime: '',
  dateSuffix: {
    just: '刚刚',
    min: '分钟前',
    hour: '小时前',
    day: '天前',
    month: '个月前'
  },
  copyright: {"limitCount":150,"languages":{"author":"作者: funtim41@gmail.com","link":"链接: ","source":"来源: funtim的博客","info":"著作权归作者所有。商业转载请联系作者获得授权，非商业转载请注明出处。"}},
  lightbox: 'null',
  Snackbar: {"chs_to_cht":"已切换为繁体中文","cht_to_chs":"已切换为简体中文","day_to_night":"已切换为深色模式","night_to_day":"已切换为浅色模式","bgLight":"#49b1f5","bgDark":"#1f1f1f","position":"bottom-left"},
  infinitegrid: {
    js: 'https://cdn.jsdelivr.net/npm/@egjs/infinitegrid/dist/infinitegrid.min.js',
    buttonText: '加载更多'
  },
  isPhotoFigcaption: false,
  islazyload: false,
  isAnchor: true,
  percent: {
    toc: true,
    rightside: true,
  },
  autoDarkmode: false
}</script><script id="config-diff">var GLOBAL_CONFIG_SITE = {
  title: '23DirectShape',
  isPost: true,
  isHome: false,
  isHighlightShrink: false,
  isToc: true,
  isShuoshuo: false
}</script><link rel="stylesheet" href="/css/bar.css"><meta name="generator" content="Hexo 7.3.0"></head><body><div id="web_bg" style="background: Color(#995a82);"></div><div id="sidebar"><div id="menu-mask"></div><div id="sidebar-menus"><div class="avatar-img text-center"><img src="/images/4stars.png" onerror="onerror=null;src='/img/friend_404.gif'" alt="avatar"/></div><div class="site-data text-center"><a href="/archives/"><div class="headline">文章</div><div class="length-num">67</div></a><a href="/tags/"><div class="headline">标签</div><div class="length-num">5</div></a><a href="/categories/"><div class="headline">分类</div><div class="length-num">7</div></a></div><div class="menus_items"><div class="menus_item"><a class="site-page" href="/"><i class="fa-fw fas fa-home"></i><span> Home</span></a></div><div class="menus_item"><a class="site-page" href="/archives/"><i class="fa-fw fas fa-archive"></i><span> Timeline</span></a></div><div class="menus_item"><a class="site-page" href="/tags/"><i class="fa-fw fas fa-tags"></i><span> Tags</span></a></div><div class="menus_item"><a class="site-page" href="/categories/"><i class="fa-fw fas fa-folder-open"></i><span> Categories</span></a></div><div class="menus_item"><a class="site-page" href="/Links/"><i class="fa-fw fas fa-link"></i><span> Links</span></a></div><div class="menus_item"><a class="site-page" href="/about/"><i class="fa-fw fas fa-heart"></i><span> About</span></a></div></div></div></div><div class="post" id="body-wrap"><header class="post-bg fixed" id="page-header" style="background-image: url(/images/topback.jpg);"><nav id="nav"><span id="blog-info"><a class="nav-site-title" href="/"><img class="site-icon" src="/images/OIP.jfif" alt="Logo"><span class="site-name">funtim的博客</span></a><a class="nav-page-title" href="/"><span class="site-name">23DirectShape</span></a></span><div id="menus"><div id="search-button"><span class="site-page social-icon search"><i class="fas fa-search fa-fw"></i><span> 搜索</span></span></div><div class="menus_items"><div class="menus_item"><a class="site-page" href="/"><i class="fa-fw fas fa-home"></i><span> Home</span></a></div><div class="menus_item"><a class="site-page" href="/archives/"><i class="fa-fw fas fa-archive"></i><span> Timeline</span></a></div><div class="menus_item"><a class="site-page" href="/tags/"><i class="fa-fw fas fa-tags"></i><span> Tags</span></a></div><div class="menus_item"><a class="site-page" href="/categories/"><i class="fa-fw fas fa-folder-open"></i><span> Categories</span></a></div><div class="menus_item"><a class="site-page" href="/Links/"><i class="fa-fw fas fa-link"></i><span> Links</span></a></div><div class="menus_item"><a class="site-page" href="/about/"><i class="fa-fw fas fa-heart"></i><span> About</span></a></div></div><div id="toggle-menu"><span class="site-page"><i class="fas fa-bars fa-fw"></i></span></div></div></nav><div id="post-info"><h1 class="post-title">23DirectShape</h1><div id="post-meta"><div class="meta-firstline"><span class="post-meta-date"><i class="far fa-calendar-alt fa-fw post-meta-icon"></i><span class="post-meta-label">发表于</span><time class="post-meta-date-created" datetime="2024-12-24T01:55:32.000Z" title="发表于 2024-12-24 09:55:32">2024-12-24</time><span class="post-meta-separator">|</span><i class="fas fa-history fa-fw post-meta-icon"></i><span class="post-meta-label">更新于</span><time class="post-meta-date-updated" datetime="2025-01-13T14:21:19.410Z" title="更新于 2025-01-13 22:21:19">2025-01-13</time></span><span class="post-meta-categories"><span class="post-meta-separator">|</span><i class="fas fa-inbox fa-fw post-meta-icon"></i><a class="post-meta-categories" href="/categories/Revit%E4%BA%8C%E6%AC%A1%E5%BC%80%E5%8F%91%E4%BA%BA%E5%91%98%E6%8C%87%E5%8D%97/">Revit二次开发人员指南</a></span></div><div class="meta-secondline"><span class="post-meta-separator">|</span><span class="post-meta-pv-cv" id="" data-flag-title=""><i class="far fa-eye fa-fw post-meta-icon"></i><span class="post-meta-label">浏览量:</span><span id="busuanzi_value_page_pv"><i class="fa-solid fa-spinner fa-spin"></i></span></span></div></div></div></header><main class="layout" id="content-inner"><div id="post"><article class="container post-content" id="article-container"><h1 id="DirectShape"><a href="#DirectShape" class="headerlink" title="DirectShape"></a>DirectShape</h1><p>此图元类型可以在项目或族文档中存储通过导入操作或计算获得的任意几何图形。</p>
<p>DirectShape元素和相关类支持在Revit文档中存储外部创建的几何形状的功能。几何体可以包括闭合实体或网格。DirectShape主要用于从其他数据格式（如IFC或STEP）导入形状，在这些格式中，没有足够的信息来创建“真实的”Revit图元。</p>
<p>可以为DirectShape对象指定顶级模型类别，例如墙类别。子类别不能指定给DirectShape元素。IsValidCategoryId（）方法可以测试类别ID，以确保它是批准与DirectShape和Category一起使用的顶级内置类别。如果类别类型为Model，则会指示CategoryType枚举值。类别将影响该对象在Revit中的显示方式，并将为该对象授予可用参数的集合和某些有限的行为。</p>
<p><strong>DirectShape创建</strong></p>
<p>静态DirectElement（）方法将创建一个新的实例级DirectShape。它需要将DirectShape添加到其中的文档以及适当的内置类别的ID。DirectShape提供ApplicationId和ApplicationDataId字符串参数，这些参数为创建的形状的源提供上下文。</p>
<p>创建DirectShape后，可以使用重载的SetShape（）方法之一来设置该形状。该形状可以直接从ShapeBuilder对象或从GeometryObject列表中设置。如果您无论如何都要使用ShapeBuilder对象为DirectShape构造几何图形，则使用ShapeBuilder输入可能会有轻微的性能优势，因为Revit将绕过对输入几何图形的重复验证。还可以使用不同版本的DirectShape（）方法将其他几何体对象附加到DirectShape。请注意，BulldShape（）不会将传入的几何体与任何已经存在的几何体合并或连接，几何体将独立存储。</p>
<p>DirectMap接受以下几何体类型作为输入：</p>
<ul>
<li>实体（可以是封闭或开放的外壳）</li>
<li>网格</li>
<li>曲线</li>
<li>点</li>
</ul>
<p>此外，还可以指定要在DirectShape的视图特定表示中使用的几何体。该几何图形与DirectShapeTargetViewType的输入一起沿着输入。设置视图专有的形状表达时，它将仅用于该类型的视图中。目前，唯一受支持的视图专有表达用于平面视图。</p>
<p>面的示例演示如何从使用GeometryCreationUtilities类创建的球体创建简单的DirectShape。请注意在创建几何体时使用了参考框架。在使用Frame对象创建几何图形之前，最好先调用静态方法Frame.CanDefineRevitGeometry（），该方法测试提供的Frame对象是否可用于定义Revit曲线或曲面。为了满足要求，框架必须正交，并且其原点应位于Revit设计限制范围内。(When创建几何体时，使用静态XYZ也很有用。IsWithinLengthLimits（），以确保该点在Revit设计限制范围内。）</p>
<p>代码区域：创建DirectShape</p>
<figure class="highlight c#"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br><span class="line">23</span><br><span class="line">24</span><br><span class="line">25</span><br><span class="line">26</span><br><span class="line">27</span><br><span class="line">28</span><br><span class="line">29</span><br><span class="line">30</span><br><span class="line">31</span><br><span class="line">32</span><br><span class="line">33</span><br><span class="line">34</span><br><span class="line">35</span><br></pre></td><td class="code"><pre><span class="line"><span class="comment">// Create a DirectShape Sphere</span></span><br><span class="line"><span class="function"><span class="keyword">public</span> <span class="keyword">void</span> <span class="title">CreateSphereDirectShape</span>(<span class="params">Document doc</span>)</span></span><br><span class="line">&#123;</span><br><span class="line">    List&lt;Curve&gt; profile = <span class="keyword">new</span> List&lt;Curve&gt;();</span><br><span class="line"></span><br><span class="line">    <span class="comment">// first create sphere with 2&#x27; radius</span></span><br><span class="line">    XYZ center = XYZ.Zero;</span><br><span class="line">    <span class="built_in">double</span> radius = <span class="number">2.0</span>;    </span><br><span class="line">    XYZ profile00 = center;</span><br><span class="line">    XYZ profilePlus = center + <span class="keyword">new</span> XYZ(<span class="number">0</span>, radius, <span class="number">0</span>);</span><br><span class="line">    XYZ profileMinus = center - <span class="keyword">new</span> XYZ(<span class="number">0</span>, radius, <span class="number">0</span>);</span><br><span class="line"></span><br><span class="line">    profile.Add(Line.CreateBound(profilePlus, profileMinus));</span><br><span class="line">    profile.Add(Arc.Create(profileMinus, profilePlus, center + <span class="keyword">new</span> XYZ(radius, <span class="number">0</span>, <span class="number">0</span>)));</span><br><span class="line"></span><br><span class="line">    CurveLoop curveLoop = CurveLoop.Create(profile);</span><br><span class="line">    SolidOptions options = <span class="keyword">new</span> SolidOptions(ElementId.InvalidElementId, ElementId.InvalidElementId);</span><br><span class="line"></span><br><span class="line">    Frame frame = <span class="keyword">new</span> Frame(center, XYZ.BasisX, -XYZ.BasisZ, XYZ.BasisY);</span><br><span class="line">    <span class="keyword">if</span> (Frame.CanDefineRevitGeometry(frame) == <span class="literal">true</span>)</span><br><span class="line">    &#123;</span><br><span class="line">        Solid sphere = GeometryCreationUtilities.CreateRevolvedGeometry(frame, <span class="keyword">new</span> CurveLoop[] &#123; curveLoop &#125;, <span class="number">0</span>, <span class="number">2</span> * Math.PI, options);</span><br><span class="line">        <span class="keyword">using</span> (Transaction t = <span class="keyword">new</span> Transaction(doc, <span class="string">&quot;Create sphere direct shape&quot;</span>))</span><br><span class="line">        &#123;</span><br><span class="line">            t.Start();</span><br><span class="line">            <span class="comment">// create direct shape and assign the sphere shape</span></span><br><span class="line">            DirectShape ds = DirectShape.CreateElement(doc, <span class="keyword">new</span> ElementId(BuiltInCategory.OST_GenericModel));</span><br><span class="line"></span><br><span class="line">            ds.ApplicationId = <span class="string">&quot;Application id&quot;</span>;</span><br><span class="line">            ds.ApplicationDataId = <span class="string">&quot;Geometry object id&quot;</span>;</span><br><span class="line">            ds.SetShape(<span class="keyword">new</span> GeometryObject[] &#123; sphere &#125;);</span><br><span class="line">            t.Commit();</span><br><span class="line">        &#125;</span><br><span class="line">    &#125;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<p>DirectShape的几何体也可以使用ShapeBuilder类的子类或从TessellatedShapeBuilder创建。</p>
<p><strong>ShapeBuilder</strong></p>
<p>ViewShapeBuilder和WireframeBuilder可用于创建几何体以存储在DirectShape类中。ViewShapeBuilder类生成并验证视图特定的形状表示。它仅限于平面视图的基于曲线的表达。WireframeBuilder构造由点和曲线组成的3D形状表示。这两种类型的ShapeBuilder都可以通过使用带ShapeBuilder参数的DirectShape.SetShape（）或DirectShape.SetShadShape（）重载应用于DirectShape元素。</p>
<p><strong>TessellatedShapeBuilder</strong></p>
<p>TessellatedShapeBuilder可用于创建实体、壳或多边形网格，这些网格由一组连接的平面小平面包围，通过逐个添加TessellatedFace对象创建。只有在面集处于“open”状态时，才能将面添加到构建中。使用OpenConnectedFaceSet（）方法打开面集。添加所有TessellatedFaces后，调用CloseConnectedFaceSet（）关闭面集。构建器允许多个面集的可能性-在这种情况下，第一个面集应该代表物体的外部“表面”，所有后续面集代表内部空隙。尽管输入数据中存在不一致或遗漏，构建器仍会尝试创建在Revit中有效的几何图形。</p>
<p>定义所有面并关闭面集后，调用Build（）方法从存储的面集构建指定的几何对象。可以在调用Build（）之前设置TessellatedShapeBuilder的Target、Fallback和GraphicsStyleId属性，否则将使用默认选项。Build（）的结果存储在TessellatedShapeBuilder中，可以通过调用GetBuildResult（）进行检索。TessellatedShapeBuilderResult.GetGeometricalObjects（）方法将返回一个GeometryObjects列表，该列表可与相应的DirectShape.SetShape（）或DirectShape. SethdShape（）重载一起使用，如下面的示例所示。</p>
<p>代码区域：使用TessellatedShapeBuilder创建DirectShape</p>
<figure class="highlight c#"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br><span class="line">23</span><br><span class="line">24</span><br><span class="line">25</span><br><span class="line">26</span><br><span class="line">27</span><br><span class="line">28</span><br><span class="line">29</span><br><span class="line">30</span><br><span class="line">31</span><br><span class="line">32</span><br><span class="line">33</span><br><span class="line">34</span><br><span class="line">35</span><br><span class="line">36</span><br><span class="line">37</span><br><span class="line">38</span><br><span class="line">39</span><br><span class="line">40</span><br><span class="line">41</span><br><span class="line">42</span><br><span class="line">43</span><br><span class="line">44</span><br><span class="line">45</span><br><span class="line">46</span><br><span class="line">47</span><br><span class="line">48</span><br><span class="line">49</span><br><span class="line">50</span><br><span class="line">51</span><br><span class="line">52</span><br><span class="line">53</span><br><span class="line">54</span><br><span class="line">55</span><br><span class="line">56</span><br><span class="line">57</span><br><span class="line">58</span><br><span class="line">59</span><br><span class="line">60</span><br><span class="line">61</span><br><span class="line">62</span><br><span class="line">63</span><br><span class="line">64</span><br><span class="line">65</span><br><span class="line">66</span><br><span class="line">67</span><br></pre></td><td class="code"><pre><span class="line"><span class="comment">// Create a pyramid-shaped DirectShape using given material for the faces</span></span><br><span class="line"><span class="function"><span class="keyword">public</span> <span class="keyword">void</span> <span class="title">CreateTessellatedShape</span>(<span class="params">Document doc, ElementId materialId</span>)</span></span><br><span class="line">&#123;</span><br><span class="line">    List&lt;XYZ&gt; loopVertices = <span class="keyword">new</span> List&lt;XYZ&gt;(<span class="number">4</span>);</span><br><span class="line"></span><br><span class="line">    TessellatedShapeBuilder builder = <span class="keyword">new</span> TessellatedShapeBuilder();</span><br><span class="line"></span><br><span class="line">    builder.OpenConnectedFaceSet(<span class="literal">true</span>);</span><br><span class="line">    <span class="comment">// create a pyramid with a square base 4&#x27; x 4&#x27; and 5&#x27; high</span></span><br><span class="line">    <span class="built_in">double</span> length = <span class="number">4.0</span>;</span><br><span class="line">    <span class="built_in">double</span> height = <span class="number">5.0</span>;</span><br><span class="line"></span><br><span class="line">    XYZ basePt1 = XYZ.Zero;</span><br><span class="line">    XYZ basePt2 = <span class="keyword">new</span> XYZ(length, <span class="number">0</span>, <span class="number">0</span>);</span><br><span class="line">    XYZ basePt3 = <span class="keyword">new</span> XYZ(length, length, <span class="number">0</span>);</span><br><span class="line">    XYZ basePt4 = <span class="keyword">new</span> XYZ(<span class="number">0</span>, length, <span class="number">0</span>);</span><br><span class="line">    XYZ apex = <span class="keyword">new</span> XYZ(length / <span class="number">2</span>, length / <span class="number">2</span>, height);</span><br><span class="line"></span><br><span class="line">    loopVertices.Add(basePt1);</span><br><span class="line">    loopVertices.Add(basePt2);</span><br><span class="line">    loopVertices.Add(basePt3);</span><br><span class="line">    loopVertices.Add(basePt4);</span><br><span class="line">    builder.AddFace(<span class="keyword">new</span> TessellatedFace(loopVertices, materialId));</span><br><span class="line"></span><br><span class="line">    loopVertices.Clear();</span><br><span class="line">    loopVertices.Add(basePt1);</span><br><span class="line">    loopVertices.Add(apex);</span><br><span class="line">    loopVertices.Add(basePt2);</span><br><span class="line">    builder.AddFace(<span class="keyword">new</span> TessellatedFace(loopVertices, materialId));</span><br><span class="line"></span><br><span class="line">    loopVertices.Clear();</span><br><span class="line">    loopVertices.Add(basePt2);</span><br><span class="line">    loopVertices.Add(apex);</span><br><span class="line">    loopVertices.Add(basePt3);</span><br><span class="line">    builder.AddFace(<span class="keyword">new</span> TessellatedFace(loopVertices, materialId));</span><br><span class="line"></span><br><span class="line">    loopVertices.Clear();</span><br><span class="line">    loopVertices.Add(basePt3);</span><br><span class="line">    loopVertices.Add(apex);</span><br><span class="line">    loopVertices.Add(basePt4);</span><br><span class="line">    builder.AddFace(<span class="keyword">new</span> TessellatedFace(loopVertices, materialId));</span><br><span class="line"></span><br><span class="line">    loopVertices.Clear();</span><br><span class="line">    loopVertices.Add(basePt4);</span><br><span class="line">    loopVertices.Add(apex);</span><br><span class="line">    loopVertices.Add(basePt1);</span><br><span class="line">    builder.AddFace(<span class="keyword">new</span> TessellatedFace(loopVertices, materialId));</span><br><span class="line"></span><br><span class="line">    builder.CloseConnectedFaceSet();</span><br><span class="line">    builder.Target = TessellatedShapeBuilderTarget.Solid;</span><br><span class="line">    builder.Fallback = TessellatedShapeBuilderFallback.Abort;</span><br><span class="line">    builder.Build();</span><br><span class="line"></span><br><span class="line">    TessellatedShapeBuilderResult result = builder.GetBuildResult();</span><br><span class="line"></span><br><span class="line">    <span class="keyword">using</span> (Transaction t = <span class="keyword">new</span> Transaction(doc, <span class="string">&quot;Create tessellated direct shape&quot;</span>))</span><br><span class="line">    &#123;</span><br><span class="line">        t.Start();</span><br><span class="line">                </span><br><span class="line">        DirectShape ds = DirectShape.CreateElement(doc, <span class="keyword">new</span> ElementId(BuiltInCategory.OST_GenericModel));</span><br><span class="line">        ds.ApplicationId = <span class="string">&quot;Application id&quot;</span>;</span><br><span class="line">        ds.ApplicationDataId = <span class="string">&quot;Geometry object id&quot;</span>;</span><br><span class="line"></span><br><span class="line">        ds.SetShape(result.GetGeometricalObjects());</span><br><span class="line">        t.Commit();</span><br><span class="line">    &#125;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<p>下面的图片是运行上面的示例并指定混凝土材质ID的结果。</p>
<p><img src="https://help.autodesk.com/cloudhelp/2018/CHS/Revit-API/images/GUID-94C65476-5A32-4C89-8561-4AD97C41774D.png" alt="img"></p>
<p><strong>BRepBuilder</strong></p>
<p>BRepBuilder类提供了构造Revit边界表达几何图形（实体、开放壳等）的功能。作为表面、边和边的边界环的输入的结果。如果边界表示的构建成功，则可以在接受几何图形的任何其他Revit工具中直接使用生成的几何图形对象，或者可以直接传递BRepBuilder，以通过DirectShape类的SetShape（）和RoundShape（）方法填充DirectShape。下面是一个使用SetShape（）方法将圆柱体形状分配给新DirectShape对象的示例。</p>
<p>代码区域：使用BRepBuilder创建DirectShape</p>
<figure class="highlight c#"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br><span class="line">23</span><br><span class="line">24</span><br><span class="line">25</span><br><span class="line">26</span><br><span class="line">27</span><br><span class="line">28</span><br><span class="line">29</span><br><span class="line">30</span><br><span class="line">31</span><br><span class="line">32</span><br><span class="line">33</span><br><span class="line">34</span><br><span class="line">35</span><br><span class="line">36</span><br><span class="line">37</span><br><span class="line">38</span><br><span class="line">39</span><br><span class="line">40</span><br><span class="line">41</span><br><span class="line">42</span><br><span class="line">43</span><br><span class="line">44</span><br><span class="line">45</span><br><span class="line">46</span><br><span class="line">47</span><br><span class="line">48</span><br><span class="line">49</span><br><span class="line">50</span><br><span class="line">51</span><br><span class="line">52</span><br><span class="line">53</span><br><span class="line">54</span><br><span class="line">55</span><br><span class="line">56</span><br><span class="line">57</span><br><span class="line">58</span><br><span class="line">59</span><br><span class="line">60</span><br><span class="line">61</span><br><span class="line">62</span><br><span class="line">63</span><br><span class="line">64</span><br><span class="line">65</span><br><span class="line">66</span><br><span class="line">67</span><br><span class="line">68</span><br><span class="line">69</span><br><span class="line">70</span><br><span class="line">71</span><br><span class="line">72</span><br><span class="line">73</span><br><span class="line">74</span><br><span class="line">75</span><br><span class="line">76</span><br><span class="line">77</span><br><span class="line">78</span><br><span class="line">79</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="keyword">private</span> <span class="keyword">void</span> <span class="title">CreateDirectShapeFromCylinder</span>(<span class="params">Document doc</span>)</span></span><br><span class="line">&#123;</span><br><span class="line">    <span class="comment">// Naming convention for faces and edges: we assume that x is to the left and pointing down, y is horizontal and pointing to the right, z is up</span></span><br><span class="line">    BRepBuilder brepBuilder = <span class="keyword">new</span> BRepBuilder(BRepType.Solid);</span><br><span class="line"></span><br><span class="line">    <span class="comment">// The surfaces of the four faces.</span></span><br><span class="line">    Frame basis = <span class="keyword">new</span> Frame(<span class="keyword">new</span> XYZ(<span class="number">50</span>, <span class="number">-100</span>, <span class="number">0</span>), <span class="keyword">new</span> XYZ(<span class="number">0</span>, <span class="number">1</span>, <span class="number">0</span>), <span class="keyword">new</span> XYZ(<span class="number">-1</span>, <span class="number">0</span>, <span class="number">0</span>), <span class="keyword">new</span> XYZ(<span class="number">0</span>, <span class="number">0</span>, <span class="number">1</span>));</span><br><span class="line">    CylindricalSurface cylSurf = CylindricalSurface.Create(basis, <span class="number">50</span>);</span><br><span class="line">    Plane top = Plane.CreateByNormalAndOrigin(<span class="keyword">new</span> XYZ(<span class="number">0</span>, <span class="number">0</span>, <span class="number">1</span>), <span class="keyword">new</span> XYZ(<span class="number">0</span>, <span class="number">0</span>, <span class="number">100</span>));  <span class="comment">// normal points outside the cylinder</span></span><br><span class="line">    Plane bottom = Plane.CreateByNormalAndOrigin(<span class="keyword">new</span> XYZ(<span class="number">0</span>, <span class="number">0</span>, <span class="number">1</span>), <span class="keyword">new</span> XYZ(<span class="number">0</span>, <span class="number">0</span>, <span class="number">0</span>)); <span class="comment">// normal points inside the cylinder</span></span><br><span class="line">                                                                                              </span><br><span class="line">    <span class="comment">// Add the four faces</span></span><br><span class="line">    BRepBuilderGeometryId frontCylFaceId = brepBuilder.AddFace(BRepBuilderSurfaceGeometry.Create(cylSurf, <span class="literal">null</span>), <span class="literal">false</span>);</span><br><span class="line">    BRepBuilderGeometryId backCylFaceId = brepBuilder.AddFace(BRepBuilderSurfaceGeometry.Create(cylSurf, <span class="literal">null</span>), <span class="literal">false</span>);</span><br><span class="line">    BRepBuilderGeometryId topFaceId = brepBuilder.AddFace(BRepBuilderSurfaceGeometry.Create(top, <span class="literal">null</span>), <span class="literal">false</span>);</span><br><span class="line">    BRepBuilderGeometryId bottomFaceId = brepBuilder.AddFace(BRepBuilderSurfaceGeometry.Create(bottom, <span class="literal">null</span>), <span class="literal">true</span>);</span><br><span class="line"></span><br><span class="line">    <span class="comment">// Geometry for the four semi-circular edges and two vertical linear edges</span></span><br><span class="line">    BRepBuilderEdgeGeometry frontEdgeBottom = BRepBuilderEdgeGeometry.Create(Arc.Create(<span class="keyword">new</span> XYZ(<span class="number">0</span>, <span class="number">-100</span>, <span class="number">0</span>), <span class="keyword">new</span> XYZ(<span class="number">100</span>, <span class="number">-100</span>, <span class="number">0</span>), <span class="keyword">new</span> XYZ(<span class="number">50</span>, <span class="number">-50</span>, <span class="number">0</span>)));</span><br><span class="line">    BRepBuilderEdgeGeometry backEdgeBottom = BRepBuilderEdgeGeometry.Create(Arc.Create(<span class="keyword">new</span> XYZ(<span class="number">100</span>, <span class="number">-100</span>, <span class="number">0</span>), <span class="keyword">new</span> XYZ(<span class="number">0</span>, <span class="number">-100</span>, <span class="number">0</span>), <span class="keyword">new</span> XYZ(<span class="number">50</span>, <span class="number">-150</span>, <span class="number">0</span>)));</span><br><span class="line"></span><br><span class="line">    BRepBuilderEdgeGeometry frontEdgeTop = BRepBuilderEdgeGeometry.Create(Arc.Create(<span class="keyword">new</span> XYZ(<span class="number">0</span>, <span class="number">-100</span>, <span class="number">100</span>), <span class="keyword">new</span> XYZ(<span class="number">100</span>, <span class="number">-100</span>, <span class="number">100</span>), <span class="keyword">new</span> XYZ(<span class="number">50</span>, <span class="number">-50</span>, <span class="number">100</span>)));</span><br><span class="line">    BRepBuilderEdgeGeometry backEdgeTop = BRepBuilderEdgeGeometry.Create(Arc.Create(<span class="keyword">new</span> XYZ(<span class="number">0</span>, <span class="number">-100</span>, <span class="number">100</span>), <span class="keyword">new</span> XYZ(<span class="number">100</span>, <span class="number">-100</span>, <span class="number">100</span>), <span class="keyword">new</span> XYZ(<span class="number">50</span>, <span class="number">-150</span>, <span class="number">100</span>)));</span><br><span class="line"></span><br><span class="line">    BRepBuilderEdgeGeometry linearEdgeFront = BRepBuilderEdgeGeometry.Create(<span class="keyword">new</span> XYZ(<span class="number">100</span>, <span class="number">-100</span>, <span class="number">0</span>), <span class="keyword">new</span> XYZ(<span class="number">100</span>, <span class="number">-100</span>, <span class="number">100</span>));</span><br><span class="line">    BRepBuilderEdgeGeometry linearEdgeBack = BRepBuilderEdgeGeometry.Create(<span class="keyword">new</span> XYZ(<span class="number">0</span>, <span class="number">-100</span>, <span class="number">0</span>), <span class="keyword">new</span> XYZ(<span class="number">0</span>, <span class="number">-100</span>, <span class="number">100</span>));</span><br><span class="line"></span><br><span class="line">    <span class="comment">// Add the six edges</span></span><br><span class="line">    BRepBuilderGeometryId frontEdgeBottomId = brepBuilder.AddEdge(frontEdgeBottom);</span><br><span class="line">    BRepBuilderGeometryId frontEdgeTopId = brepBuilder.AddEdge(frontEdgeTop);</span><br><span class="line">    BRepBuilderGeometryId linearEdgeFrontId = brepBuilder.AddEdge(linearEdgeFront);</span><br><span class="line">    BRepBuilderGeometryId linearEdgeBackId = brepBuilder.AddEdge(linearEdgeBack);</span><br><span class="line">    BRepBuilderGeometryId backEdgeBottomId = brepBuilder.AddEdge(backEdgeBottom);</span><br><span class="line">    BRepBuilderGeometryId backEdgeTopId = brepBuilder.AddEdge(backEdgeTop);</span><br><span class="line"></span><br><span class="line">    <span class="comment">// Loops of the four faces</span></span><br><span class="line">    BRepBuilderGeometryId loopId_Top = brepBuilder.AddLoop(topFaceId);</span><br><span class="line">    BRepBuilderGeometryId loopId_Bottom = brepBuilder.AddLoop(bottomFaceId);</span><br><span class="line">    BRepBuilderGeometryId loopId_Front = brepBuilder.AddLoop(frontCylFaceId);</span><br><span class="line">    BRepBuilderGeometryId loopId_Back = brepBuilder.AddLoop(backCylFaceId);</span><br><span class="line"></span><br><span class="line">    <span class="comment">// Add coedges for the loop of the front face</span></span><br><span class="line">    brepBuilder.AddCoEdge(loopId_Front, linearEdgeBackId, <span class="literal">false</span>);</span><br><span class="line">    brepBuilder.AddCoEdge(loopId_Front, frontEdgeTopId, <span class="literal">false</span>);</span><br><span class="line">    brepBuilder.AddCoEdge(loopId_Front, linearEdgeFrontId, <span class="literal">true</span>);</span><br><span class="line">    brepBuilder.AddCoEdge(loopId_Front, frontEdgeBottomId, <span class="literal">true</span>);</span><br><span class="line">    brepBuilder.FinishLoop(loopId_Front);</span><br><span class="line">    brepBuilder.FinishFace(frontCylFaceId);</span><br><span class="line"></span><br><span class="line">    <span class="comment">// Add coedges for the loop of the back face</span></span><br><span class="line">    brepBuilder.AddCoEdge(loopId_Back, linearEdgeBackId, <span class="literal">true</span>);</span><br><span class="line">    brepBuilder.AddCoEdge(loopId_Back, backEdgeBottomId, <span class="literal">true</span>);</span><br><span class="line">    brepBuilder.AddCoEdge(loopId_Back, linearEdgeFrontId, <span class="literal">false</span>);</span><br><span class="line">    brepBuilder.AddCoEdge(loopId_Back, backEdgeTopId, <span class="literal">true</span>);</span><br><span class="line">    brepBuilder.FinishLoop(loopId_Back);</span><br><span class="line">    brepBuilder.FinishFace(backCylFaceId);</span><br><span class="line"></span><br><span class="line">    <span class="comment">// Add coedges for the loop of the top face</span></span><br><span class="line">    brepBuilder.AddCoEdge(loopId_Top, backEdgeTopId, <span class="literal">false</span>);</span><br><span class="line">    brepBuilder.AddCoEdge(loopId_Top, frontEdgeTopId, <span class="literal">true</span>);</span><br><span class="line">    brepBuilder.FinishLoop(loopId_Top);</span><br><span class="line">    brepBuilder.FinishFace(topFaceId);</span><br><span class="line"></span><br><span class="line">    <span class="comment">// Add coedges for the loop of the bottom face</span></span><br><span class="line">    brepBuilder.AddCoEdge(loopId_Bottom, frontEdgeBottomId, <span class="literal">false</span>);</span><br><span class="line">    brepBuilder.AddCoEdge(loopId_Bottom, backEdgeBottomId, <span class="literal">false</span>);</span><br><span class="line">    brepBuilder.FinishLoop(loopId_Bottom);</span><br><span class="line">    brepBuilder.FinishFace(bottomFaceId);</span><br><span class="line"></span><br><span class="line">    brepBuilder.Finish();</span><br><span class="line"></span><br><span class="line">    <span class="keyword">using</span> (Transaction tr = <span class="keyword">new</span> Transaction(doc, <span class="string">&quot;Create a DirectShape&quot;</span>))</span><br><span class="line">    &#123;</span><br><span class="line">        tr.Start();</span><br><span class="line">        DirectShape ds = DirectShape.CreateElement(doc, <span class="keyword">new</span> ElementId(BuiltInCategory.OST_GenericModel));</span><br><span class="line">        ds.SetShape(brepBuilder);</span><br><span class="line">        tr.Commit();</span><br><span class="line">    &#125;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<p><strong>ShapeImporter</strong> </p>
<p>ShapeImporter工具类支持将以外部格式（如SAT和Rhino）存储的几何体转换为可用于设置DirectShape形状的GeometryObjects集合。使用ShapeImporter.Convert（）生成几何体对象（如果可能，还生成关联文档中的相应材料和图形样式）。</p>
<p>代码区域：从SAT文件创建DirectShape</p>
<figure class="highlight c#"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br><span class="line">23</span><br><span class="line">24</span><br><span class="line">25</span><br><span class="line">26</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="keyword">public</span> <span class="keyword">void</span> <span class="title">ReadSATFile</span>(<span class="params">Document revitDoc</span>)</span></span><br><span class="line">&#123;</span><br><span class="line">    <span class="comment">// Allow the user to select a SAT file.</span></span><br><span class="line">    OpenFileDialog ofd = <span class="keyword">new</span> OpenFileDialog();</span><br><span class="line">    ofd.Filter = <span class="string">&quot;SAT Files (*.sat)|*.sat&quot;</span>;</span><br><span class="line"></span><br><span class="line">    <span class="keyword">if</span> (DialogResult.OK == ofd.ShowDialog())</span><br><span class="line">    &#123;</span><br><span class="line">        ShapeImporter shapeImporter = <span class="keyword">new</span> ShapeImporter();</span><br><span class="line">        shapeImporter.InputFormat = ShapeImporterSourceFormat.SAT; </span><br><span class="line">        IList&lt;GeometryObject&gt; shapes = shapeImporter.Convert(revitDoc, ofd.FileName);</span><br><span class="line"></span><br><span class="line">        <span class="keyword">if</span> (shapes.Count != <span class="number">0</span>)</span><br><span class="line">        &#123;</span><br><span class="line">            <span class="keyword">using</span> (Transaction tr = <span class="keyword">new</span> Transaction(revitDoc, <span class="string">&quot;Create a DirectShape&quot;</span>))</span><br><span class="line">            &#123;</span><br><span class="line">                tr.Start();</span><br><span class="line"></span><br><span class="line">                DirectShape dsImportedSat = DirectShape.CreateElement(revitDoc, <span class="keyword">new</span> ElementId(BuiltInCategory.OST_Walls));</span><br><span class="line">                dsImportedSat.SetShape(shapes);</span><br><span class="line"></span><br><span class="line">                tr.Commit();</span><br><span class="line">            &#125;</span><br><span class="line">        &#125;</span><br><span class="line">    &#125;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<p><strong>Options</strong> </p>
<p>DirectShapeOptions类用于控制DirectShape对象的行为。使用DirectShape.SetOptions（）设置DirectShape对象使用的选项。GetOptions（）方法将返回DirectShape对象当前使用的DirectShapeOptions。</p>
<p>默认情况下，DirectShape元素支持元素参照，包括尺寸标注、路线和面主体以及捕捉。可以使用DirectShapeOptions.ReferencingOption属性更改此默认行为。如果将其设置为NotReferenceable，则几何图形不能用于标注、捕捉、对齐或面主体。用户仍然可以选择该元素进行不引用单个几何对象的操作。</p>
<p>如果DirectShape元素属于房间边界计算的适当类别，并且关联的“房间边界”参数设置为true，则DirectShape元素还支持参与房间边界计算的功能。属性DirectShapeOptions.RoomBoundingOption标识DirectShape是否支持“房间边界”参数的选项以允许参与房间边界计算。默认值为NotApplied，但对于适用的DirectController，此值将自动更改为SetByParameter。</p>
<h2 id="注：翻译自Revit-API-Developers-Guide"><a href="#注：翻译自Revit-API-Developers-Guide" class="headerlink" title="注：翻译自Revit API Developers Guide"></a><em><strong>注：</strong></em>翻译自<a target="_blank" rel="noopener" href="https://help.autodesk.com/view/RVT/2018/ENU/?guid=Revit_API_Revit_API_Developers_Guide_html">Revit API Developers Guide</a></h2></article><div class="tag_share"><div class="post-meta__tag-list"><a class="post-meta__tags" href="/tags/Revit/">Revit</a></div><div class="post-share"><div class="social-share" data-image="/images/4stars.png" data-sites="facebook,twitter,wechat,weibo,qq"></div><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/butterfly-extsrc/sharejs/dist/css/share.min.css" media="print" onload="this.media='all'"><script src="https://cdn.jsdelivr.net/npm/butterfly-extsrc/sharejs/dist/js/social-share.min.js" defer></script></div></div><nav class="pagination-post" id="pagination"><a class="pagination-related" href="/2024/12/24/Revit%E4%BA%8C%E5%BC%80%E6%8C%87%E5%8D%97/25%E5%BB%BA%E7%AD%91/" title="25建筑"><div class="cover" style="background: var(--default-bg-color)"></div><div class="info"><div class="info-1"><div class="info-item-1">上一篇</div><div class="info-item-2">25建筑</div></div><div class="info-2"><div class="info-item-1">建筑本章介绍特定于Revit建筑功能的API功能：  与房间相关的功能（Element.Room、RoomTag等）   本节中的主题  Rooms  房间Rooms  以下各节介绍了有关房间类、其参数以及如何在API中使用房间类的信息。 Room类用于表示房间和图元，例如房间明细表和面积平面。下表列出了API中不同房间、面积及其对应标签的属性和创建函数： 表55：房间、面积和标签关系    **Element ** **Class ** **Category ** **Boundary ** **Location ** **Can Create **    Room in Plan View Room OST_Rooms 在封闭区域中有 LocationPoint NewRoom（），NewRoom（Phase）除外   Room in Schedule View Room OST_Rooms Null Null NewRoom(Phase)   Area Room OST_Areas 总是有 LocationPoint No   Room...</div></div></div></a><a class="pagination-related" href="/2024/12/23/Revit%E4%BA%8C%E5%BC%80%E6%8C%87%E5%8D%97/24%E5%AD%90%E5%85%83%E7%B4%A0/" title="24子元素"><div class="cover" style="background: var(--default-bg-color)"></div><div class="info text-right"><div class="info-1"><div class="info-item-1">下一篇</div><div class="info-item-2">24子元素</div></div><div class="info-2"><div class="info-item-1">子元素多个Revit图元现在可以包含称为子图元的细分。子元素提供了一种方法，使元素的各个部分的行为就像它们是真实的元素一样，而不会产生向模型中添加更多完整元素的开销。 许多Revit功能（例如，参数、明细表和标记）都设计用于对图元进行操作。因此，Revit代码需要将对象表示为元素，以便它们参与这些功能。这可能会导致可伸缩性问题，因为每个元素都会增加开销，并且添加许多元素可能会降低模型的性能。 另一种方法是使用子元素。图元可以显示其包含的一组“子图元”，指定其类别和参数等特征，并且某些Revit功能会将这些子图元视为普通图元。例如，子元素可以为主元素提供几何图形，并且可以独立于其父元素进行选择。它可能会有自己的（可设置的）类型以及分配的类别，该类别可以与其父元素不同。 在API中，新的Subelement类用于引用一个Element或给定Element的特定子元素。它通常与对元素或特定子元素的引用直接相关。 注：翻译自Revit API Developers Guide</div></div></div></a></nav><div class="relatedPosts"><div class="headline"><i class="fas fa-thumbs-up fa-fw"></i><span>相关推荐</span></div><div class="relatedPosts-list"><a class="pagination-related" href="/2024/12/20/RevitApi%E5%90%88%E9%9B%86/Autodesk.%20Revit.DB%20ElementTransformUtils/" title="Autodesk.Revit.DB ElementTransformUtils"><div class="cover" style="background: var(--default-bg-color)"></div><div class="info text-center"><div class="info-1"><div class="info-item-1"><i class="far fa-calendar-alt fa-fw"></i> 2024-12-20</div><div class="info-item-2">Autodesk.Revit.DB ElementTransformUtils</div></div><div class="info-2"><div class="info-item-1">Autodesk. Revit.DB ElementTransformUtils允许元素转换的实用程序集合（例如移动，旋转，镜像和复制）。 语法1public static class ElementTransformUtils    继承层次结构 System Object Autodesk.Revit.DB ElementTransformUtils   方法CanMirrorElement确定是否可以镜像元素。 CanMirrorElements确定是否可以镜像元素。 CopyElement复制元素并将副本放置在给定转换指示的位置。 CopyElements(Document, ICollection ElementId , XYZ)复制一组元素，并将副本放置在给定指示的位置。 CopyElements(Document, ICollection ElementId , Document, Transform, CopyPasteOptions)将一组元素从源文档复制到目标文档。 CopyElements(View, ICollection ElementId ,...</div></div></div></a><a class="pagination-related" href="/2025/02/16/RevitApi%E5%90%88%E9%9B%86/Autodesk.Revit.ApplicationServices%20Application/" title="Autodesk.Revit.ApplicationServices Application"><div class="cover" style="background: var(--default-bg-color)"></div><div class="info text-center"><div class="info-1"><div class="info-item-1"><i class="far fa-calendar-alt fa-fw"></i> 2025-02-16</div><div class="info-item-2">Autodesk.Revit.ApplicationServices Application</div></div><div class="info-2"><div class="info-item-1">Autodesk.Revit.ApplicationServices Application代表Autodesk Revit应用程序，提供对文档、选项和其他应用程序范围数据和设置的访问。 语法1public class Application : IDisposable    示例123string versionInfo = application.VersionBuild + &quot;\n&quot;					+ application.VersionName + &quot;\n&quot;					+ application.VersionNumber;  继承层次结构System Object Autodesk.Revit.ApplicationServices Application Autodesk.Revit.DB.Macros ApplicationEntryPoint 方法CopyModel将现有模型复制到新文件。允许覆盖同名文件。 ExtractPartAtomFromFamilyFile从族文件的内容写入PartAtom...</div></div></div></a><a class="pagination-related" href="/2025/02/20/RevitApi%E5%90%88%E9%9B%86/Autodesk.Revit.DB%20Curve/" title="Autodesk.Revit.DB Curve"><div class="cover" style="background: var(--default-bg-color)"></div><div class="info text-center"><div class="info-1"><div class="info-item-1"><i class="far fa-calendar-alt fa-fw"></i> 2025-02-20</div><div class="info-item-2">Autodesk.Revit.DB Curve</div></div><div class="info-2"><div class="info-item-1">Autodesk.Revit.DB Curve参数曲线。 语法1public class Curve : GeometryObject    附注具体曲线由参数方程定义。如果曲线是有界的，它只在参数化中为一个区间定义。否则就是 为参数的所有值定义。 继承层次结构System Object Autodesk.Revit.DB APIObject Autodesk.Revit.DB GeometryObject Autodesk.Revit.DB Curve Autodesk.Revit.DB Arc Autodesk.Revit.DB CylindricalHelix Autodesk.Revit.DB Ellipse Autodesk.Revit.DB HermiteSpline Autodesk.Revit.DB Line Autodesk.Revit.DB...</div></div></div></a><a class="pagination-related" href="/2024/11/18/RevitApi%E5%90%88%E9%9B%86/Autodesk.Revit.DB%20CurveArray/" title="Autodesk.Revit.DB CurveArray"><div class="cover" style="background: var(--default-bg-color)"></div><div class="info text-center"><div class="info-1"><div class="info-item-1"><i class="far fa-calendar-alt fa-fw"></i> 2024-11-18</div><div class="info-item-2">Autodesk.Revit.DB CurveArray</div></div><div class="info-2"><div class="info-item-1">Autodesk.Revit.DB CurveArray可以包含曲线的数组。 语法1public class CurveArray : APIObject, IEnumerable  继承层次结构System Object ​	Autodesk.Revit.DB APIObject ​		Autodesk.Revit.DB CurveArray 另见CurveArray Members Autodesk.Revit.DB Namespace 构造函数CurveArray创建CurveArray类的新实例 方法Append将曲线添加到数组的末尾。 Clear从数组中删除每条曲线，使其为空。 ForwardIterator将一个向前移动的迭代器添加到数组中。 GetEnumerator将一个向前移动的迭代器添加到数组中。 Insert将指定的曲线插入数组。 ReverseIterator返回一个向后移动的迭代器到数组。 属性IsEmpty测试数组是否为空。 Item获取或设置数组中指定索引处的曲线。 Size返回数组中的曲线数。 注：翻译自Revit Api docs 2018</div></div></div></a><a class="pagination-related" href="/2025/02/20/RevitApi%E5%90%88%E9%9B%86/Autodesk.Revit.DB%20Line/" title="Autodesk.Revit.DB Line"><div class="cover" style="background: var(--default-bg-color)"></div><div class="info text-center"><div class="info-1"><div class="info-item-1"><i class="far fa-calendar-alt fa-fw"></i> 2025-02-20</div><div class="info-item-2">Autodesk.Revit.DB Line</div></div><div class="info-2"><div class="info-item-1">Autodesk.Revit.DB Line空间中的一条线。 语法1public class Line : Curve  继承层次结构System Object Autodesk.Revit.DB APIObject Autodesk.Revit.DB GeometryObject Autodesk.Revit.DB Curve Autodesk.Revit.DB Line 方法CreateBound创建有界线性曲线的新实例。 CreateUnbound创建无界线性曲线的新实例。 Intersect计算此曲线与指定曲线的交点。 IsInside指示指定的参数值是否在此曲线的边界内。 属性Direction返回直线的方向。 Origin返回直线的原点。 注：翻译自Revit Api docs 2018</div></div></div></a><a class="pagination-related" href="/2024/12/10/RevitApi%E5%90%88%E9%9B%86/Autodesk.Revit.DB%20Opening/" title="Autodesk.Revit.DB Opening"><div class="cover" style="background: var(--default-bg-color)"></div><div class="info text-center"><div class="info-1"><div class="info-item-1"><i class="far fa-calendar-alt fa-fw"></i> 2024-12-10</div><div class="info-item-2">Autodesk.Revit.DB Opening</div></div><div class="info-2"><div class="info-item-1">Autodesk.Revit.DB OpeningAutodesk Revit项目或族文档中的洞口。 语法1public class Opening : Element  附注该对象表示各种不同类型的洞口：  墙中由修订项目中的两个边界点创建的矩形洞口。 由应用于屋顶、楼板、天花板、梁、支撑或柱的一组曲线创建的洞口。 一个垂直的竖井开口延伸到一个或多个水平。 在族文档中的墙或天花板上创建的简单洞口。  根据打开的类型，此类的某些属性将不可用。 这个对象派生自Element基对象，并且支持该对象的所有方法，例如检索该对象的参数的能力。此对象还支持访问结构分析模型，但此功能仅适用于Autodesk Revit Structure。 示例123456789101112131415161718192021222324252627282930313233343536373839404142434445464748495051### private void Getinfo_Opening(Opening opening)&#123;    string message =...</div></div></div></a></div></div><hr class="custom-hr"/><div id="post-comment"><div class="comment-head"><div class="comment-headline"><i class="fas fa-comments fa-fw"></i><span> 评论</span></div></div><div class="comment-wrap"><div><div id="giscus-wrap"></div></div></div></div></div><div class="aside-content" id="aside-content"><div class="card-widget card-info text-center"><div class="avatar-img"><img src="/images/4stars.png" onerror="this.onerror=null;this.src='/img/friend_404.gif'" alt="avatar"/></div><div class="author-info-name">funtim41@gmail.com</div><div class="author-info-description">实践-认识-再实践-再认识</div><div class="site-data"><a href="/archives/"><div class="headline">文章</div><div class="length-num">67</div></a><a href="/tags/"><div class="headline">标签</div><div class="length-num">5</div></a><a href="/categories/"><div class="headline">分类</div><div class="length-num">7</div></a></div><a id="card-info-btn" target="_blank" rel="noopener" href="https://github.com/FunTim41"><i class="fab fa-github"></i><span>Follow Me</span></a><div class="card-info-social-icons"><a class="social-icon" href="https://github.com/FunTim41" target="_blank" title="Github"><i class="fab fa-github" style="color: #FFFFFF;"></i></a></div></div><div class="card-widget card-announcement"><div class="item-headline"><i class="fas fa-bullhorn fa-shake"></i><span>公告</span></div><div class="announcement_content">This is my Blog</div></div><div class="sticky_layout"><div class="card-widget" id="card-toc"><div class="item-headline"><i class="fas fa-stream"></i><span>目录</span><span class="toc-percentage"></span></div><div class="toc-content"><ol class="toc"><li class="toc-item toc-level-1"><a class="toc-link" href="#DirectShape"><span class="toc-number">1.</span> <span class="toc-text">DirectShape</span></a><ol class="toc-child"><li class="toc-item toc-level-2"><a class="toc-link" href="#%E6%B3%A8%EF%BC%9A%E7%BF%BB%E8%AF%91%E8%87%AARevit-API-Developers-Guide"><span class="toc-number">1.1.</span> <span class="toc-text">注：翻译自Revit API Developers Guide</span></a></li></ol></li></ol></div></div><div class="card-widget card-recent-post"><div class="item-headline"><i class="fas fa-history"></i><span>最新文章</span></div><div class="aside-list"><div class="aside-list-item no-cover"><div class="content"><a class="title" href="/2025/03/29/Revit%E4%BA%8C%E5%BC%80%E7%A4%BA%E4%BE%8B/%E5%9C%A8Revit%E4%B8%AD%E6%B1%82%E5%86%85%E8%BD%AE%E5%BB%93%E5%8F%8A%E5%A4%96%E8%BD%AE%E5%BB%93/" title="在Revit中求内轮廓及外轮廓">在Revit中求内轮廓及外轮廓</a><time datetime="2025-03-29T05:32:21.007Z" title="更新于 2025-03-29 13:32:21">2025-03-29</time></div></div><div class="aside-list-item no-cover"><div class="content"><a class="title" href="/2025/02/27/RevitApi%E5%90%88%E9%9B%86/Autodesk.Revit.DB%20XYZ%20/" title="Autodesk.Revit.DB XYZ">Autodesk.Revit.DB XYZ</a><time datetime="2025-02-27T12:48:50.709Z" title="更新于 2025-02-27 20:48:50">2025-02-27</time></div></div><div class="aside-list-item no-cover"><div class="content"><a class="title" href="/2025/02/20/RevitApi%E5%90%88%E9%9B%86/Autodesk.Revit.DB%20Curve/" title="Autodesk.Revit.DB Curve">Autodesk.Revit.DB Curve</a><time datetime="2025-02-27T12:28:18.794Z" title="更新于 2025-02-27 20:28:18">2025-02-27</time></div></div><div class="aside-list-item no-cover"><div class="content"><a class="title" href="/2025/02/20/RevitApi%E5%90%88%E9%9B%86/Autodesk.Revit.DB%20Line/" title="Autodesk.Revit.DB Line">Autodesk.Revit.DB Line</a><time datetime="2025-02-27T12:28:08.332Z" title="更新于 2025-02-27 20:28:08">2025-02-27</time></div></div><div class="aside-list-item no-cover"><div class="content"><a class="title" href="/2025/02/16/RevitApi%E5%90%88%E9%9B%86/Autodesk.Revit.ApplicationServices%20Application/" title="Autodesk.Revit.ApplicationServices Application">Autodesk.Revit.ApplicationServices Application</a><time datetime="2025-02-27T12:27:54.491Z" title="更新于 2025-02-27 20:27:54">2025-02-27</time></div></div></div></div></div></div></main><footer id="footer" style="background-image: url(/images/topback.jpg);"><div id="footer-wrap"><div class="copyright">&copy;2024 - 2025 By funtim41@gmail.com</div><div class="framework-info"><span>框架 </span><a target="_blank" rel="noopener" href="https://hexo.io">Hexo</a><span class="footer-separator">|</span><span>主题 </span><a target="_blank" rel="noopener" href="https://github.com/jerryc127/hexo-theme-butterfly">Butterfly</a></div><div class="footer_custom_text">学而不思则罔，思而不学则殆。</div></div></footer></div><div id="rightside"><div id="rightside-config-hide"><button id="readmode" type="button" title="阅读模式"><i class="fas fa-book-open"></i></button><button id="darkmode" type="button" title="日间和夜间模式切换"><i class="fas fa-adjust"></i></button><button id="hide-aside-btn" type="button" title="单栏和双栏切换"><i class="fas fa-arrows-alt-h"></i></button></div><div id="rightside-config-show"><button id="rightside-config" type="button" title="设置"><i class="fas fa-cog fa-spin"></i></button><button class="close" id="mobile-toc-button" type="button" title="目录"><i class="fas fa-list-ul"></i></button><a id="to_comment" href="#post-comment" title="前往评论"><i class="fas fa-comments"></i></a><button id="go-up" type="button" title="回到顶部"><span class="scroll-percent"></span><i class="fas fa-arrow-up"></i></button></div></div><div><script src="/js/utils.js"></script><script src="/js/main.js"></script><script src="https://cdn.jsdelivr.net/npm/node-snackbar/dist/snackbar.min.js"></script><script>(() => {
  const panguFn = () => {
    if (typeof pangu === 'object') pangu.autoSpacingPage()
    else {
      btf.getScript('https://cdn.jsdelivr.net/npm/pangu/dist/browser/pangu.min.js')
        .then(() => {
          pangu.autoSpacingPage()
        })
    }
  }

  const panguInit = () => {
    if (false){
      GLOBAL_CONFIG_SITE.isPost && panguFn()
    } else {
      panguFn()
    }
  }

  btf.addGlobalFn('pjaxComplete', panguInit, 'pangu')
  document.addEventListener('DOMContentLoaded', panguInit)
})()</script><div class="js-pjax"><script>(() => {
  const isShuoshuo = GLOBAL_CONFIG_SITE.isShuoshuo
  const option = null

  const getGiscusTheme = theme => theme === 'dark' ? 'dark' : 'light'

  const createScriptElement = config => {
    const ele = document.createElement('script')
    Object.entries(config).forEach(([key, value]) => {
      ele.setAttribute(key, value)
    })
    return ele
  }

  const loadGiscus = (el = document, key) => {
    const mappingConfig = isShuoshuo
      ? { 'data-mapping': 'specific', 'data-term': key }
      : { 'data-mapping': (option && option['data-mapping']) || 'pathname' }

    const giscusConfig = {
      src: 'https://giscus.app/client.js',
      'data-repo': 'FunTim41/funtim41.github.io',
      'data-repo-id': 'R_kgDONjG8ww',
      'data-category-id': 'DIC_kwDONjG8w84Cllg2',
      'data-theme': getGiscusTheme(document.documentElement.getAttribute('data-theme')),
      'data-reactions-enabled': '1',
      crossorigin: 'anonymous',
      async: true,
      ...option,
      ...mappingConfig
    }

    const scriptElement = createScriptElement(giscusConfig)

    el.querySelector('#giscus-wrap').appendChild(scriptElement)

    if (isShuoshuo) {
      window.shuoshuoComment.destroyGiscus = () => {
        if (el.children.length) {
          el.innerHTML = ''
          el.classList.add('no-comment')
        }
      }
    }
  }

  const changeGiscusTheme = theme => {
    const iframe = document.querySelector('#giscus-wrap iframe')
    if (iframe) {
      const message = {
        giscus: {
          setConfig: {
            theme: getGiscusTheme(theme)
          }
        }
      }
      iframe.contentWindow.postMessage(message, 'https://giscus.app')
    }
  }

  btf.addGlobalFn('themeChange', changeGiscusTheme, 'giscus')

  if (isShuoshuo) {
    'Giscus' === 'Giscus'
      ? window.shuoshuoComment = { loadComment: loadGiscus }
      : window.loadOtherComment = loadGiscus
    return
  }

  if ('Giscus' === 'Giscus' || !false) {
    if (false) btf.loadComment(document.getElementById('giscus-wrap'), loadGiscus)
    else loadGiscus()
  } else {
    window.loadOtherComment = loadGiscus
  }
})()</script></div><script defer="defer" id="fluttering_ribbon" mobile="false" src="https://cdn.jsdelivr.net/npm/butterfly-extsrc/dist/canvas-fluttering-ribbon.min.js"></script><script async data-pjax src="//busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js"></script><div id="local-search"><div class="search-dialog"><nav class="search-nav"><span class="search-dialog-title">搜索</span><span id="loading-status"></span><button class="search-close-button"><i class="fas fa-times"></i></button></nav><div class="text-center" id="loading-database"><i class="fas fa-spinner fa-pulse"></i><span>  数据加载中</span></div><div class="search-wrap"><div id="local-search-input"><div class="local-search-box"><input class="local-search-box--input" placeholder="搜索文章" type="text"/></div></div><hr/><div id="local-search-results"></div><div id="local-search-stats-wrap"></div></div></div><div id="search-mask"></div><script src="/js/search/local-search.js"></script></div></div></body></html>