<!DOCTYPE html><html lang="zh-CN" data-theme="light"><head><meta charset="UTF-8"><meta http-equiv="X-UA-Compatible" content="IE=edge"><meta name="viewport" content="width=device-width, initial-scale=1.0,viewport-fit=cover"><title>25建筑 | funtim的博客</title><meta name="author" content="funtim41@gmail.com"><meta name="copyright" content="funtim41@gmail.com"><meta name="format-detection" content="telephone=no"><meta name="theme-color" content="#ffffff"><meta name="description" content="建筑本章介绍特定于Revit建筑功能的API功能：  与房间相关的功能（Element.Room、RoomTag等）   本节中的主题  Rooms  房间Rooms  以下各节介绍了有关房间类、其参数以及如何在API中使用房间类的信息。 Room类用于表示房间和图元，例如房间明细表和面积平面。下表列出了API中不同房间、面积及其对应标签的属性和创建函数： 表55：房间、面积和标签关系    **">
<meta property="og:type" content="article">
<meta property="og:title" content="25建筑">
<meta property="og:url" content="https://funtim41.github.io/2024/12/24/Revit%E4%BA%8C%E5%BC%80%E6%8C%87%E5%8D%97/25%E5%BB%BA%E7%AD%91/">
<meta property="og:site_name" content="funtim的博客">
<meta property="og:description" content="建筑本章介绍特定于Revit建筑功能的API功能：  与房间相关的功能（Element.Room、RoomTag等）   本节中的主题  Rooms  房间Rooms  以下各节介绍了有关房间类、其参数以及如何在API中使用房间类的信息。 Room类用于表示房间和图元，例如房间明细表和面积平面。下表列出了API中不同房间、面积及其对应标签的属性和创建函数： 表55：房间、面积和标签关系    **">
<meta property="og:locale" content="zh_CN">
<meta property="og:image" content="https://funtim41.github.io/images/4stars.png">
<meta property="article:published_time" content="2024-12-24T03:35:32.000Z">
<meta property="article:modified_time" content="2025-01-13T14:21:33.741Z">
<meta property="article:author" content="funtim41@gmail.com">
<meta property="article:tag" content="Revit">
<meta name="twitter:card" content="summary">
<meta name="twitter:image" content="https://funtim41.github.io/images/4stars.png"><link rel="shortcut icon" href="/images/OIP.jfif"><link rel="canonical" href="https://funtim41.github.io/2024/12/24/Revit%E4%BA%8C%E5%BC%80%E6%8C%87%E5%8D%97/25%E5%BB%BA%E7%AD%91/"><link rel="preconnect" href="//cdn.jsdelivr.net"/><link rel="stylesheet" href="/css/index.css"><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free/css/all.min.css"><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/node-snackbar/dist/snackbar.min.css" media="print" onload="this.media='all'"><script>
    (() => {
      
    const saveToLocal = {
      set: (key, value, ttl) => {
        if (!ttl) return
        const expiry = Date.now() + ttl * 86400000
        localStorage.setItem(key, JSON.stringify({ value, expiry }))
      },
      get: key => {
        const itemStr = localStorage.getItem(key)
        if (!itemStr) return undefined
        const { value, expiry } = JSON.parse(itemStr)
        if (Date.now() > expiry) {
          localStorage.removeItem(key)
          return undefined
        }
        return value
      }
    }

    window.btf = {
      saveToLocal,
      getScript: (url, attr = {}) => new Promise((resolve, reject) => {
        const script = document.createElement('script')
        script.src = url
        script.async = true
        Object.entries(attr).forEach(([key, val]) => script.setAttribute(key, val))
        script.onload = script.onreadystatechange = () => {
          if (!script.readyState || /loaded|complete/.test(script.readyState)) resolve()
        }
        script.onerror = reject
        document.head.appendChild(script)
      }),
      getCSS: (url, id) => new Promise((resolve, reject) => {
        const link = document.createElement('link')
        link.rel = 'stylesheet'
        link.href = url
        if (id) link.id = id
        link.onload = link.onreadystatechange = () => {
          if (!link.readyState || /loaded|complete/.test(link.readyState)) resolve()
        }
        link.onerror = reject
        document.head.appendChild(link)
      }),
      addGlobalFn: (key, fn, name = false, parent = window) => {
        if (!false && key.startsWith('pjax')) return
        const globalFn = parent.globalFn || {}
        globalFn[key] = globalFn[key] || {}
        globalFn[key][name || Object.keys(globalFn[key]).length] = fn
        parent.globalFn = globalFn
      }
    }
  
      
      const activateDarkMode = () => {
        document.documentElement.setAttribute('data-theme', 'dark')
        if (document.querySelector('meta[name="theme-color"]') !== null) {
          document.querySelector('meta[name="theme-color"]').setAttribute('content', '#0d0d0d')
        }
      }
      const activateLightMode = () => {
        document.documentElement.setAttribute('data-theme', 'light')
        if (document.querySelector('meta[name="theme-color"]') !== null) {
          document.querySelector('meta[name="theme-color"]').setAttribute('content', '#ffffff')
        }
      }

      btf.activateDarkMode = activateDarkMode
      btf.activateLightMode = activateLightMode

      const theme = saveToLocal.get('theme')
    
          theme === 'dark' ? activateDarkMode() : theme === 'light' ? activateLightMode() : null
        
      
      const asideStatus = saveToLocal.get('aside-status')
      if (asideStatus !== undefined) {
        document.documentElement.classList.toggle('hide-aside', asideStatus === 'hide')
      }
    
      
    const detectApple = () => {
      if (/iPad|iPhone|iPod|Macintosh/.test(navigator.userAgent)) {
        document.documentElement.classList.add('apple')
      }
    }
    detectApple()
  
    })()
  </script><script>const GLOBAL_CONFIG = {
  root: '/',
  algolia: undefined,
  localSearch: {"path":"/search.xml","preload":false,"top_n_per_article":1,"unescape":false,"languages":{"hits_empty":"未找到符合您查询的内容：${query}","hits_stats":"共找到 ${hits} 篇文章"}},
  translate: undefined,
  highlight: {"plugin":"highlight.js","highlightCopy":true,"highlightLang":true,"highlightHeightLimit":false,"highlightFullpage":false,"highlightMacStyle":false},
  copy: {
    success: '复制成功',
    error: '复制失败',
    noSupport: '浏览器不支持'
  },
  relativeDate: {
    homepage: false,
    post: false
  },
  runtime: '',
  dateSuffix: {
    just: '刚刚',
    min: '分钟前',
    hour: '小时前',
    day: '天前',
    month: '个月前'
  },
  copyright: {"limitCount":150,"languages":{"author":"作者: funtim41@gmail.com","link":"链接: ","source":"来源: funtim的博客","info":"著作权归作者所有。商业转载请联系作者获得授权，非商业转载请注明出处。"}},
  lightbox: 'null',
  Snackbar: {"chs_to_cht":"已切换为繁体中文","cht_to_chs":"已切换为简体中文","day_to_night":"已切换为深色模式","night_to_day":"已切换为浅色模式","bgLight":"#49b1f5","bgDark":"#1f1f1f","position":"bottom-left"},
  infinitegrid: {
    js: 'https://cdn.jsdelivr.net/npm/@egjs/infinitegrid/dist/infinitegrid.min.js',
    buttonText: '加载更多'
  },
  isPhotoFigcaption: false,
  islazyload: false,
  isAnchor: true,
  percent: {
    toc: true,
    rightside: true,
  },
  autoDarkmode: false
}</script><script id="config-diff">var GLOBAL_CONFIG_SITE = {
  title: '25建筑',
  isPost: true,
  isHome: false,
  isHighlightShrink: false,
  isToc: true,
  isShuoshuo: false
}</script><link rel="stylesheet" href="/css/bar.css"><meta name="generator" content="Hexo 7.3.0"></head><body><div id="web_bg" style="background: Color(#995a82);"></div><div id="sidebar"><div id="menu-mask"></div><div id="sidebar-menus"><div class="avatar-img text-center"><img src="/images/4stars.png" onerror="onerror=null;src='/img/friend_404.gif'" alt="avatar"/></div><div class="site-data text-center"><a href="/archives/"><div class="headline">文章</div><div class="length-num">58</div></a><a href="/tags/"><div class="headline">标签</div><div class="length-num">5</div></a><a href="/categories/"><div class="headline">分类</div><div class="length-num">7</div></a></div><div class="menus_items"><div class="menus_item"><a class="site-page" href="/"><i class="fa-fw fas fa-home"></i><span> Home</span></a></div><div class="menus_item"><a class="site-page" href="/archives/"><i class="fa-fw fas fa-archive"></i><span> Timeline</span></a></div><div class="menus_item"><a class="site-page" href="/tags/"><i class="fa-fw fas fa-tags"></i><span> Tags</span></a></div><div class="menus_item"><a class="site-page" href="/categories/"><i class="fa-fw fas fa-folder-open"></i><span> Categories</span></a></div><div class="menus_item"><a class="site-page" href="/Links/"><i class="fa-fw fas fa-link"></i><span> Links</span></a></div><div class="menus_item"><a class="site-page" href="/about/"><i class="fa-fw fas fa-heart"></i><span> About</span></a></div></div></div></div><div class="post" id="body-wrap"><header class="post-bg fixed" id="page-header" style="background-image: url(/images/topback.jpg);"><nav id="nav"><span id="blog-info"><a class="nav-site-title" href="/"><img class="site-icon" src="/images/OIP.jfif" alt="Logo"><span class="site-name">funtim的博客</span></a><a class="nav-page-title" href="/"><span class="site-name">25建筑</span></a></span><div id="menus"><div id="search-button"><span class="site-page social-icon search"><i class="fas fa-search fa-fw"></i><span> 搜索</span></span></div><div class="menus_items"><div class="menus_item"><a class="site-page" href="/"><i class="fa-fw fas fa-home"></i><span> Home</span></a></div><div class="menus_item"><a class="site-page" href="/archives/"><i class="fa-fw fas fa-archive"></i><span> Timeline</span></a></div><div class="menus_item"><a class="site-page" href="/tags/"><i class="fa-fw fas fa-tags"></i><span> Tags</span></a></div><div class="menus_item"><a class="site-page" href="/categories/"><i class="fa-fw fas fa-folder-open"></i><span> Categories</span></a></div><div class="menus_item"><a class="site-page" href="/Links/"><i class="fa-fw fas fa-link"></i><span> Links</span></a></div><div class="menus_item"><a class="site-page" href="/about/"><i class="fa-fw fas fa-heart"></i><span> About</span></a></div></div><div id="toggle-menu"><span class="site-page"><i class="fas fa-bars fa-fw"></i></span></div></div></nav><div id="post-info"><h1 class="post-title">25建筑</h1><div id="post-meta"><div class="meta-firstline"><span class="post-meta-date"><i class="far fa-calendar-alt fa-fw post-meta-icon"></i><span class="post-meta-label">发表于</span><time class="post-meta-date-created" datetime="2024-12-24T03:35:32.000Z" title="发表于 2024-12-24 11:35:32">2024-12-24</time><span class="post-meta-separator">|</span><i class="fas fa-history fa-fw post-meta-icon"></i><span class="post-meta-label">更新于</span><time class="post-meta-date-updated" datetime="2025-01-13T14:21:33.741Z" title="更新于 2025-01-13 22:21:33">2025-01-13</time></span><span class="post-meta-categories"><span class="post-meta-separator">|</span><i class="fas fa-inbox fa-fw post-meta-icon"></i><a class="post-meta-categories" href="/categories/Revit%E4%BA%8C%E6%AC%A1%E5%BC%80%E5%8F%91%E4%BA%BA%E5%91%98%E6%8C%87%E5%8D%97/">Revit二次开发人员指南</a></span></div><div class="meta-secondline"><span class="post-meta-separator">|</span><span class="post-meta-pv-cv" id="" data-flag-title=""><i class="far fa-eye fa-fw post-meta-icon"></i><span class="post-meta-label">浏览量:</span><span id="busuanzi_value_page_pv"><i class="fa-solid fa-spinner fa-spin"></i></span></span></div></div></div></header><main class="layout" id="content-inner"><div id="post"><article class="container post-content" id="article-container"><h1 id="建筑"><a href="#建筑" class="headerlink" title="建筑"></a>建筑</h1><p>本章介绍特定于Revit建筑功能的API功能：</p>
<ul>
<li>与房间相关的功能（Element.Room、RoomTag等）</li>
</ul>
<p> 本节中的主题</p>
<ul>
<li>Rooms</li>
</ul>
<h2 id="房间"><a href="#房间" class="headerlink" title="房间"></a>房间</h2><p><strong>Rooms</strong> </p>
<p>以下各节介绍了有关房间类、其参数以及如何在API中使用房间类的信息。</p>
<p>Room类用于表示房间和图元，例如房间明细表和面积平面。下表列出了API中不同房间、面积及其对应标签的属性和创建函数：</p>
<p><strong>表55：房间、面积和标签关系</strong></p>
<table>
<thead>
<tr>
<th>**Element **</th>
<th>**Class **</th>
<th>**Category **</th>
<th>**Boundary **</th>
<th>**Location **</th>
<th>**Can Create **</th>
</tr>
</thead>
<tbody><tr>
<td>Room in Plan View</td>
<td>Room</td>
<td>OST_Rooms</td>
<td>在封闭区域中有</td>
<td>LocationPoint</td>
<td>NewRoom（），NewRoom（Phase）除外</td>
</tr>
<tr>
<td>Room in Schedule View</td>
<td>Room</td>
<td>OST_Rooms</td>
<td>Null</td>
<td>Null</td>
<td>NewRoom(Phase)</td>
</tr>
<tr>
<td>Area</td>
<td>Room</td>
<td>OST_Areas</td>
<td>总是有</td>
<td>LocationPoint</td>
<td>No</td>
</tr>
<tr>
<td>Room Tag</td>
<td>RoomTag</td>
<td>OST_RoomTags</td>
<td></td>
<td>LocationPoint</td>
<td>Creation.Document.NewRoomTag()</td>
</tr>
<tr>
<td>Area Tag</td>
<td>FamilySymbol</td>
<td>OST_AreaTags</td>
<td></td>
<td>LocationPoint</td>
<td>No</td>
</tr>
</tbody></table>
<p>注：房间名称是房间名称和房间号的组合。例如，对于编号为2且名称为“Master Bedroom”的房间，Room.Name将返回“Master Bedroom 2”。使用ROOM_NAME内置参数获取房间名称。</p>
<p>注意：作为注释元素，特定视图可使用RoomTag. View。不要尝试设置RoomTag.Name属性，因为该名称是自动分配的;否则将引发异常。</p>
<p><strong>创建房间</strong></p>
<p>下面的代码演示了在特定楼层的某个点创建房间的最简单方法：</p>
<p>代码区域28-1：创建房间</p>
<figure class="highlight c#"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br></pre></td><td class="code"><pre><span class="line"><span class="function">Room <span class="title">CreateRoom</span>(<span class="params">Autodesk.Revit.DB.Document document, Level level</span>)</span></span><br><span class="line">&#123;</span><br><span class="line">        <span class="comment">// Create a UV structure which determines the room location</span></span><br><span class="line">        UV roomLocation = <span class="keyword">new</span> UV(<span class="number">0</span>, <span class="number">0</span>);</span><br><span class="line"></span><br><span class="line">        <span class="comment">// Create a new room</span></span><br><span class="line">        Room room = document.Create.NewRoom(level, roomLocation);</span><br><span class="line">        <span class="keyword">if</span> (<span class="literal">null</span> == room)</span><br><span class="line">        &#123;</span><br><span class="line">                <span class="keyword">throw</span> <span class="keyword">new</span> Exception(<span class="string">&quot;Create a new room failed.&quot;</span>);</span><br><span class="line">        &#125;</span><br><span class="line"></span><br><span class="line">        <span class="keyword">return</span> room;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<p>可以在房间明细表中创建房间，然后将其插入到平面回路中。</p>
<ul>
<li>Document.NewRoom（Phase）方法用于创建不与任何特定位置关联的新文件室，并将其插入到现有明细表中。在拨打电话之前，确保房间时间表存在或在指定阶段创建房间时间表。</li>
<li>Document.NewRoom（Roomroom，PlanCircuit线路）方法用于从明细表中的房间和PlanCircuit创建房间。<ul>
<li>输入房间必须仅存在于房间明细表中，这意味着它不会显示在任何平面视图中。</li>
<li>调用该方法后，将在PlanCircuit所在的视图中创建具有相同名称和编号的模型房间。</li>
</ul>
</li>
</ul>
<p>有关平面电路的详细信息，请参见平面拓扑。</p>
<p>以下代码说明了整个过程：</p>
<p>代码区域28-2：创建房间并将其插入到平面回路中</p>
<figure class="highlight c#"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br><span class="line">23</span><br><span class="line">24</span><br><span class="line">25</span><br><span class="line">26</span><br><span class="line">27</span><br><span class="line">28</span><br><span class="line">29</span><br><span class="line">30</span><br><span class="line">31</span><br><span class="line">32</span><br><span class="line">33</span><br><span class="line">34</span><br><span class="line">35</span><br><span class="line">36</span><br><span class="line">37</span><br><span class="line">38</span><br><span class="line">39</span><br><span class="line">40</span><br><span class="line">41</span><br><span class="line">42</span><br><span class="line">43</span><br><span class="line">44</span><br><span class="line">45</span><br><span class="line">46</span><br><span class="line">47</span><br><span class="line">48</span><br><span class="line">49</span><br><span class="line">50</span><br><span class="line">51</span><br></pre></td><td class="code"><pre><span class="line"><span class="function">Room <span class="title">InsertNewRoomInPlanCircuit</span>(<span class="params">Autodesk.Revit.DB.Document document, Level level, Phase newConstructionPhase</span>)</span></span><br><span class="line">&#123;</span><br><span class="line">    <span class="comment">// create room using Phase</span></span><br><span class="line">    Room newScheduleRoom = document.Create.NewRoom(newConstructionPhase);</span><br><span class="line">            </span><br><span class="line">    <span class="comment">// set the Room Number and Name</span></span><br><span class="line">    <span class="built_in">string</span> newRoomNumber = <span class="string">&quot;101&quot;</span>;</span><br><span class="line">    <span class="built_in">string</span> newRoomName = <span class="string">&quot;Class Room 1&quot;</span>;</span><br><span class="line">    newScheduleRoom.Name = newRoomName;</span><br><span class="line">    newScheduleRoom.Number = newRoomNumber;</span><br><span class="line"></span><br><span class="line">    <span class="comment">// Get a PlanCircuit</span></span><br><span class="line">    PlanCircuit planCircuit = <span class="literal">null</span>;</span><br><span class="line">    <span class="comment">// first get the plan topology for given level</span></span><br><span class="line">    PlanTopology planTopology = document.get_PlanTopology(level);</span><br><span class="line">            </span><br><span class="line">    <span class="comment">// Iterate circuits in this plan topology</span></span><br><span class="line">    <span class="keyword">foreach</span> (PlanCircuit circuit <span class="keyword">in</span> planTopology.Circuits)</span><br><span class="line">    &#123;</span><br><span class="line">        <span class="comment">// get the first circuit we find</span></span><br><span class="line">        <span class="keyword">if</span> (<span class="literal">null</span> != circuit)</span><br><span class="line">        &#123;</span><br><span class="line">            planCircuit = circuit;</span><br><span class="line">            <span class="keyword">break</span>;</span><br><span class="line">        &#125;</span><br><span class="line">    &#125;</span><br><span class="line">           </span><br><span class="line">    Room newRoom2 = <span class="literal">null</span>;</span><br><span class="line">    <span class="keyword">if</span> (<span class="literal">null</span> != planCircuit)</span><br><span class="line">    &#123;</span><br><span class="line">        <span class="keyword">using</span> (Transaction transaction = <span class="keyword">new</span> Transaction(document, <span class="string">&quot;Create Room&quot;</span>))</span><br><span class="line">        &#123;</span><br><span class="line">            <span class="keyword">if</span> (transaction.Start() == TransactionStatus.Started)</span><br><span class="line">            &#123;</span><br><span class="line">                <span class="comment">// The input room must exist only in the room schedule, </span></span><br><span class="line">                <span class="comment">// meaning that it does not display in any plan view.</span></span><br><span class="line">                newRoom2 = document.Create.NewRoom(newScheduleRoom, planCircuit);</span><br><span class="line">                <span class="comment">// a model room with the same name and number is created in the </span></span><br><span class="line">                <span class="comment">// view where the PlanCircuit is located</span></span><br><span class="line">                <span class="keyword">if</span> (<span class="literal">null</span> != newRoom2)</span><br><span class="line">                &#123;</span><br><span class="line">                    <span class="comment">// Give the user some information</span></span><br><span class="line">                    TaskDialog.Show(<span class="string">&quot;Revit&quot;</span>, <span class="string">&quot;Room placed in Plan Circuit successfully.&quot;</span>);</span><br><span class="line">                &#125;</span><br><span class="line">                transaction.Commit();</span><br><span class="line">            &#125;</span><br><span class="line">        &#125;</span><br><span class="line">    &#125;</span><br><span class="line"></span><br><span class="line">    <span class="keyword">return</span> newRoom2;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<p>创建房间并将其添加到位置后，可以使用Room.Unplace（）方法将其从该位置删除（但在项目中仍然可用）。然后可以将其放置在新的位置。</p>
<h3 id="房间边界"><a href="#房间边界" class="headerlink" title="房间边界"></a>房间边界</h3><p>房间的边界可在房间所在的位置创建封闭区域。</p>
<ul>
<li>边界包括以下要素：<ul>
<li>Walls  </li>
<li>Model lines  </li>
<li>Columns  </li>
<li>Roofs</li>
</ul>
</li>
</ul>
<h4 id="检索房间边界"><a href="#检索房间边界" class="headerlink" title="检索房间边界"></a>检索房间边界</h4><p>房间周围的边界是从基类方法SpatialElement.GetBoundarySegments（）获得的。当房间不在封闭区域中或仅存在于明细表中时，该方法返回null。每个房间可能有几个区域，每个区域都有几个段，因此数据以BoundarySegment列表的形式返回。</p>
<p>下图显示了在Revit UI中选择的房间边界：</p>
<p><img src="https://help.autodesk.com/cloudhelp/2018/CHS/Revit-API/images/GUID-4FEC99FB-5F16-4343-8475-ECFF367CB072.png" alt="img"></p>
<p>图138：房间边界</p>
<p>线段列表的大小取决于封闭区域拓扑。每个BoundarySegment列表都创建一个回路或一条连续的线，其中一个线段连接到下一个线段。下面的图片提供了几个例子。在下面的图片中，所有墙都是“房间边界”，模型线类别为OST_AreaSeparationLines。如果某个图元不是“房间边界”，则将其从图元中排除以形成边界。</p>
<p><img src="https://help.autodesk.com/cloudhelp/2018/CHS/Revit-API/images/GUID-792A1532-E1EE-4186-894F-F593C930B2A6.png" alt="img"></p>
<p><img src="https://help.autodesk.com/cloudhelp/2018/CHS/Revit-API/images/GUID-C259DDE9-9A9E-457F-87C3-3D686A8A9359.png"></p>
<p>下表提供了之前房间的Room.GetBoundarySegments（）.Size结果：</p>
<p><strong>表56：Room.GetBoundarySegments（）.Size</strong></p>
<table>
<thead>
<tr>
<th><strong>Room 房间</strong></th>
<th>**Room.GetBoundarySegments().Size **</th>
</tr>
</thead>
<tbody><tr>
<td>Room 1、2、3</td>
<td>1</td>
</tr>
<tr>
<td>Room 4</td>
<td>2</td>
</tr>
<tr>
<td>Room 5、6</td>
<td>3</td>
</tr>
</tbody></table>
<p>注意：由模型线连接的墙被视为连续的线段。单个模型线将被忽略。</p>
<p>获取IList&lt;IList<BoundarySegment>后，通过迭代列表获取BoundarySegment。</p>
<p><strong>BoundarySegment</strong> </p>
<p>构成区域的线段由BoundarySegment类表示;其ElementId属性返回对应元素的id，条件如下：</p>
<ul>
<li>对于ModelCurve元素，类别必须是BuiltInCategory.OST_AreaSeparationLines，这意味着它表示房间分隔符。</li>
<li>对于墙、柱和屋顶等其他图元，如果图元是房间边界，则“房间边界”参数（BuiltInParameter.WALL_ATTR_ROOM_BOUNDING）必须为真，如下图所示。</li>
</ul>
<p><img src="https://help.autodesk.com/cloudhelp/2018/CHS/Revit-API/images/GUID-FBC69AE1-EF76-4773-AC4A-7CBCC77EE924.png" alt="img"></p>
<p>图141：房间边界属性</p>
<p>WALL_ATTR_ROOM_BOUNDING内置参数通过API设置：</p>
<p>代码区域28-3：设置房间边界</p>
<figure class="highlight c#"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="keyword">public</span> <span class="keyword">void</span> <span class="title">SetRoomBounding</span>(<span class="params">Wall wall</span>)</span></span><br><span class="line">&#123;</span><br><span class="line">        Parameter parameter = wall.get_Parameter(BuiltInParameter.WALL_ATTR_ROOM_BOUNDING);</span><br><span class="line">        parameter.Set(<span class="number">1</span>);   <span class="comment">//set &quot;Room Bounding&quot; to true</span></span><br><span class="line">        parameter.Set(<span class="number">0</span>);   <span class="comment">//set &quot;Room Bounding&quot; to false</span></span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<p>请注意，在下面的图片中，屋顶如何形成房间的BoundarySegment。第一张图片显示立面视图中的Level 3。将在Level 3楼层视图中创建房间。后两张图片显示了房间和房子的3D视图的边界。</p>
<p><img src="https://help.autodesk.com/cloudhelp/2018/CHS/Revit-API/images/GUID-067191A0-12EA-430F-B145-6B8D5D6E596E.png" alt="img"></p>
<p>图142：在标高3视图中创建的房间</p>
<p><img src="https://help.autodesk.com/cloudhelp/2018/CHS/Revit-API/images/GUID-862FFB79-21A7-4F5A-B949-B442529EF50E.png"></p>
<p><strong>图143：</strong>屋顶形成的房间边界</p>
<p>面积边界只能是类别为面积边界（BuiltInCategory.OST_AreaSchemeLines）的ModelCurve，而显示房间的边界可以是墙和其他图元。</p>
<p><img src="https://help.autodesk.com/cloudhelp/2018/CHS/Revit-API/images/GUID-8B918B3C-ED10-486C-912A-9D4A1F8CC4EA.png"></p>
<p>图144：墙端边缘</p>
<p>如果BoundarySegment对应于房间分隔和墙之间的曲线，如上图所示：</p>
<ul>
<li>Element属性返回null</li>
<li>曲线不为空。</li>
</ul>
<p><strong>边界与事务</strong></p>
<p>在使用API创建了一个元素（如墙）之后，如果调用Room.GetBoundarySegments（），墙可以更改房间边界。您必须确保数据已更新。</p>
<p>下图显示了使用Revit Platform API创建墙后房间的变化。</p>
<p><img src="https://help.autodesk.com/cloudhelp/2018/CHS/Revit-API/images/GUID-5410C3CF-324E-4C38-9152-BA29AB5D6CA1.png" alt="img"></p>
<p>图145：添加的墙更改房间边界</p>
<p>要更新房间边界数据，请使用以下代码中的事务机制：</p>
<figure class="highlight c#"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br><span class="line">23</span><br><span class="line">24</span><br><span class="line">25</span><br><span class="line">26</span><br><span class="line">27</span><br><span class="line">28</span><br><span class="line">29</span><br><span class="line">30</span><br><span class="line">31</span><br><span class="line">32</span><br><span class="line">33</span><br><span class="line">34</span><br><span class="line">35</span><br><span class="line">36</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="keyword">public</span> <span class="keyword">void</span> <span class="title">UpdateRoomBoundary</span>(<span class="params">UIApplication application, Room room, Level level</span>)</span></span><br><span class="line">&#123;</span><br><span class="line">    Document document = application.ActiveUIDocument.Document;</span><br><span class="line">            </span><br><span class="line">    <span class="comment">//Get the size before creating a wall</span></span><br><span class="line">    <span class="built_in">int</span> size = room.GetBoundarySegments(<span class="keyword">new</span> SpatialElementBoundaryOptions()).First().Count;</span><br><span class="line">    <span class="built_in">string</span> message = <span class="string">&quot;Room boundary size before wall: &quot;</span> + size;</span><br><span class="line"></span><br><span class="line">    <span class="comment">//Prepare a line</span></span><br><span class="line">    XYZ startPos = <span class="keyword">new</span> XYZ(<span class="number">-10</span>, <span class="number">0</span>, <span class="number">0</span>);</span><br><span class="line">    XYZ endPos = <span class="keyword">new</span> XYZ(<span class="number">10</span>, <span class="number">0</span>, <span class="number">0</span>);</span><br><span class="line">    Line line = Line.CreateBound(startPos, endPos);</span><br><span class="line"></span><br><span class="line">    <span class="comment">//Create a new wall and enclose the creating into a single transaction</span></span><br><span class="line">    <span class="keyword">using</span> (Transaction transaction = <span class="keyword">new</span> Transaction(document, <span class="string">&quot;Create Wall&quot;</span>))</span><br><span class="line">    &#123;</span><br><span class="line">        <span class="keyword">if</span> (transaction.Start() == TransactionStatus.Started)</span><br><span class="line">        &#123;</span><br><span class="line">            Wall wall = Wall.Create(document, line, level.Id, <span class="literal">false</span>);</span><br><span class="line">            <span class="keyword">if</span> (<span class="literal">null</span> != wall)</span><br><span class="line">            &#123;</span><br><span class="line">                <span class="keyword">if</span> (TransactionStatus.Committed == transaction.Commit())</span><br><span class="line">                &#123;</span><br><span class="line">                    <span class="comment">//Get the new size</span></span><br><span class="line">                    size = room.GetBoundarySegments(<span class="keyword">new</span> SpatialElementBoundaryOptions()).First().Count;</span><br><span class="line">                    message += <span class="string">&quot;\nRoom boundary size after wall: &quot;</span> + size;</span><br><span class="line">                    TaskDialog.Show(<span class="string">&quot;Revit&quot;</span>, message);</span><br><span class="line">                &#125;</span><br><span class="line">            &#125;</span><br><span class="line">            <span class="keyword">else</span></span><br><span class="line">            &#123;</span><br><span class="line">                transaction.RollBack();</span><br><span class="line">            &#125;</span><br><span class="line">        &#125;</span><br><span class="line">    &#125;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<p>有关详细信息，请参阅事务。</p>
<p><strong>平面拓扑</strong></p>
<p>房间所在的标高平面具有由墙和房间分隔线等图元构成的拓扑。PlanTopology和PlanCircuit类用于表示标高拓扑。</p>
<ul>
<li>使用Level从Document对象获取PlanTopology对象。在每个平面视图中，每个阶段对应一个PlanTopology。</li>
<li>相同的条件适用于BoundarySegment，但房间分隔符和房间边界参数为true的元素可以是PlanCircuit中的边（边界）。</li>
</ul>
<p><img src="https://help.autodesk.com/cloudhelp/2018/CHS/Revit-API/images/GUID-E0715B88-5A70-4424-8268-E1CAD3D5EEFF.png" alt="img"></p>
<p>图146：房间和平面拓扑图</p>
<p>PlanCircuit.Sideship属性返回线路边编号，而SpatialElement.GetBoundarySegments（）返回IList&lt;IList&lt;Autodesk.Revit.DB.BoundarySegment&gt;，其Count与线路边编号不同。</p>
<ul>
<li>如果墙上有分支，则SpatialElement.GetBoundarySegments（）将底墙识别为两面墙。</li>
<li>PlanCircuit.无论分支的数量如何，Sideball总是将图片中的底墙视为一个。</li>
</ul>
<p><img src="https://help.autodesk.com/cloudhelp/2018/CHS/Revit-API/images/GUID-25504A29-2C29-409B-AFF6-916CD359E8C2.png" alt="img"></p>
<p>图147：比较房间边界与PlanCircuit</p>
<p>表57：房间边界与平面回路的比较</p>
<table>
<thead>
<tr>
<th>**Circuit **</th>
<th><strong>Circuit.SideNum</strong></th>
<th>**IList&lt;IList&lt;Autodesk.Revit.DB.BoundarySegment&gt; .Count for Room **</th>
</tr>
</thead>
<tbody><tr>
<td>Circuit 1</td>
<td>3</td>
<td>3 (Room1)</td>
</tr>
<tr>
<td>Circuit 2</td>
<td>4 +2 &#x3D; 6</td>
<td>4 +3 &#x3D; 7 (Room2)</td>
</tr>
<tr>
<td>Circuit 3</td>
<td>3 +2 &#x3D; 5</td>
<td>3 +3 &#x3D; 6 (Room3)</td>
</tr>
<tr>
<td>Circuit 4</td>
<td>3</td>
<td>3 (Room4)</td>
</tr>
<tr>
<td>Circuit 5</td>
<td>3</td>
<td>3 (Room5)</td>
</tr>
</tbody></table>
<p><strong>房间和族实例</strong></p>
<p>“门”和“窗”是与“房间”相关的特殊族实例。这里只讨论门，因为唯一的区别是窗户没有翻转把手。</p>
<p>以下特性适用于门：</p>
<ul>
<li>门元素可以在没有房间的情况下存在。</li>
<li>在API中（仅在API中），Door元素具有两个附加属性，它们引用门的两个相对侧上的区域：ToRoom和FromRoom</li>
<li>如果区域是房间，则属性的值将是房间元素。</li>
<li>如果区域不是房间，则属性将返回null。两个属性可以同时为null。</li>
<li>门打开的一侧的区域将是ToRoom。另一边的房间将是FromRoom。</li>
<li>每当相应的区域发生变化时，这两个属性都会动态更新。</li>
</ul>
<p>在下面的图片中，五扇门插入到墙中，而不翻转饰面。该表列出了每个门的FromRoom、ToRoom和Room属性。房间属性属于所有族实例。</p>
<p><img src="https://help.autodesk.com/cloudhelp/2018/CHS/Revit-API/images/GUID-B05F86CE-DD91-401E-BD6C-67704F9BE55C.png" alt="img"></p>
<p>Figure 148: Door 1 </p>
<p><img src="https://help.autodesk.com/cloudhelp/2018/CHS/Revit-API/images/GUID-4D623C2A-40AC-44D0-86E5-14D00C649014.png" alt="img"></p>
<p>Figure 149: Door 2 </p>
<p><img src="https://help.autodesk.com/cloudhelp/2018/CHS/Revit-API/images/GUID-97032EDC-973A-4DD0-A314-3796F3E52F1E.png" alt="img"></p>
<p>Figure 150: Door 3 </p>
<p><img src="https://help.autodesk.com/cloudhelp/2018/CHS/Revit-API/images/GUID-25B7F1B6-3F62-4607-A2DC-AA38B4CBE0D1.png" alt="img"></p>
<p>Figure 151: Door 4</p>
<p><img src="https://help.autodesk.com/cloudhelp/2018/CHS/Revit-API/images/GUID-BEB8BE84-3D6F-4E7E-A87D-0FE6C7CB6D3F.png" alt="img"></p>
<p>Figure 152: Door 5 </p>
<p><strong>表58：门属性</strong></p>
<table>
<thead>
<tr>
<th>**Door **</th>
<th><strong>FromRoom</strong></th>
<th><strong>ToRoom</strong></th>
<th><strong>Room 房间</strong></th>
</tr>
</thead>
<tbody><tr>
<td>Door 1</td>
<td>null</td>
<td>null</td>
<td>null</td>
</tr>
<tr>
<td>Door 2</td>
<td>Room 1</td>
<td>null</td>
<td>null</td>
</tr>
<tr>
<td>Door 3</td>
<td>Room 3</td>
<td>Room 2</td>
<td>Room 2</td>
</tr>
<tr>
<td>Door 4</td>
<td>Room 4</td>
<td>null</td>
<td>null</td>
</tr>
<tr>
<td>Door 5</td>
<td>null</td>
<td>Room 6</td>
<td>Room 6</td>
</tr>
</tbody></table>
<p>所有族实例都具有“房间”属性，该属性是实例在上一个项目阶段中所在的房间。窗户和门都面对着一个房间。通过翻转门或窗的朝向或调用FamilyInstance.FlipFromToRoom（）来更改房间。对于其他类型的实例（如梁和柱），“房间”是与实例具有相同边界的房间。</p>
<p>下面的代码演示了如何从族实例中获取Room。需要检查结果是否为null。</p>
<p>代码区域28-5：从族实例获取房间</p>
<figure class="highlight c#"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="keyword">public</span> <span class="keyword">void</span> <span class="title">GetRoomInfo</span>(<span class="params">FamilyInstance familyInstance</span>)</span></span><br><span class="line">&#123;</span><br><span class="line">        Room room = familyInstance.Room;</span><br><span class="line">        room = familyInstance.FromRoom;  <span class="comment">//for door and window family only</span></span><br><span class="line">        room = familyInstance.ToRoom;    <span class="comment">//for door and window family only</span></span><br><span class="line">        <span class="keyword">if</span> (<span class="literal">null</span> != room)</span><br><span class="line">        &#123;</span><br><span class="line">                <span class="comment">//use the room...</span></span><br><span class="line">        &#125;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<p><strong>其他房间属性</strong></p>
<p>Room类还有其他几个属性，可用于获取有关对象的信息。房间具有以下只读尺寸属性：</p>
<ul>
<li>Area  </li>
<li>Perimeter </li>
<li>UnboundedHeight</li>
<li>Volume  </li>
<li>ClosedShell</li>
</ul>
<p>此示例显示选定房间的尺寸标注信息。请注意，必须启用体积计算设置，否则房间体积将返回为0。</p>
<p>代码区域28-6：获取房间的尺寸</p>
<figure class="highlight c#"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="keyword">public</span> <span class="keyword">void</span> <span class="title">GetRoomDimensions</span>(<span class="params">Document doc, Room room</span>)</span></span><br><span class="line">&#123;</span><br><span class="line">    String roominfo = <span class="string">&quot;Room dimensions:\n&quot;</span>;</span><br><span class="line">    <span class="comment">// turn on volume calculations:</span></span><br><span class="line">    <span class="keyword">using</span> (Transaction t = <span class="keyword">new</span> Transaction(doc, <span class="string">&quot;Turn on volume calculation&quot;</span>))</span><br><span class="line">    &#123;</span><br><span class="line">        t.Start();</span><br><span class="line">        AreaVolumeSettings settings = AreaVolumeSettings.GetAreaVolumeSettings(doc);</span><br><span class="line">        settings.ComputeVolumes = <span class="literal">true</span>;</span><br><span class="line">        t.Commit();</span><br><span class="line">    &#125;</span><br><span class="line">            </span><br><span class="line">    roominfo += <span class="string">&quot;Vol: &quot;</span> + room.Volume + <span class="string">&quot;\n&quot;</span>;</span><br><span class="line">    roominfo += <span class="string">&quot;Area: &quot;</span> + room.Area + <span class="string">&quot;\n&quot;</span>;</span><br><span class="line">    roominfo += <span class="string">&quot;Perimeter: &quot;</span> + room.Perimeter + <span class="string">&quot;\n&quot;</span>;</span><br><span class="line">    roominfo += <span class="string">&quot;Unbounded height: &quot;</span> + room.UnboundedHeight + <span class="string">&quot;\n&quot;</span>;</span><br><span class="line">    TaskDialog.Show(<span class="string">&quot;Revit&quot;</span>,roominfo);</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<p>房间（或空间）的ClosedShell属性是由房间开放空间的边界（墙、楼板、天花板、屋顶和边界线）形成的几何图形。如果需要检查模型中的其他物理图元与房间的交点，例如，查看图元的一部分或全部是否位于房间中，则此属性非常有用。有关示例，请参见随Revit SDK提供的RoofsRooms示例应用程序，其中ClosedShell用于检查房间是否垂直无边界。</p>
<p>此外，还可以获取或设置具有以下属性的房间的基准偏移和限制偏移：</p>
<ul>
<li>BaseOffset</li>
<li>LimitOffset</li>
</ul>
<p>可以使用UpperLimit属性获取或设置定义房间上限的标高。</p>
<h2 id="注：翻译自Revit-API-Developers-Guide"><a href="#注：翻译自Revit-API-Developers-Guide" class="headerlink" title="注：翻译自Revit API Developers Guide"></a><em><strong>注：</strong></em>翻译自<a target="_blank" rel="noopener" href="https://help.autodesk.com/view/RVT/2018/ENU/?guid=Revit_API_Revit_API_Developers_Guide_html">Revit API Developers Guide</a></h2></article><div class="tag_share"><div class="post-meta__tag-list"><a class="post-meta__tags" href="/tags/Revit/">Revit</a></div><div class="post-share"><div class="social-share" data-image="/images/4stars.png" data-sites="facebook,twitter,wechat,weibo,qq"></div><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/butterfly-extsrc/sharejs/dist/css/share.min.css" media="print" onload="this.media='all'"><script src="https://cdn.jsdelivr.net/npm/butterfly-extsrc/sharejs/dist/js/social-share.min.js" defer></script></div></div><nav class="pagination-post" id="pagination"><a class="pagination-related" href="/2024/12/24/Revit%E4%BA%8C%E5%BC%80%E6%8C%87%E5%8D%97/26%E7%BB%93%E6%9E%84%E5%B7%A5%E7%A8%8B/" title="26结构工程"><div class="cover" style="background: var(--default-bg-color)"></div><div class="info"><div class="info-1"><div class="info-item-1">上一篇</div><div class="info-item-2">26结构工程</div></div><div class="info-2"><div class="info-item-1">结构工程以下各节介绍了仅与Revit的结构工程功能相关的API功能：  结构模型元素-讨论仅与Revit的结构工程功能相关的特定元素及其属性。  AnalyticalModel -讨论与分析模型相关的类，如AnalyticalModel、RigidLink和AnalyticalModelSupport。  AnalyticalLink -讨论在分析梁和柱之间创建新的分析链接。  荷载-讨论荷载设置和三种荷载。   您的分析链接-为希望将Revit链接到某些Structural Analysis应用程序的API用户提供建议。 本章包含一些高级主题。如果您不熟悉Revit Platform API，请先阅读基本部分，如“入门”、“元素要素”、“参数”等。  本节中的主题 结构模型元素 分析模型在结构工程中，分析模型是结构物理模型的工程描述。 荷载以下部分确定荷载设置并讨论荷载限制指南。 Analysis Link分析链接 Analytical...</div></div></div></a><a class="pagination-related" href="/2024/12/24/Revit%E4%BA%8C%E5%BC%80%E6%8C%87%E5%8D%97/23DirectShape/" title="23DirectShape"><div class="cover" style="background: var(--default-bg-color)"></div><div class="info text-right"><div class="info-1"><div class="info-item-1">下一篇</div><div class="info-item-2">23DirectShape</div></div><div class="info-2"><div class="info-item-1">...</div></div></div></a></nav><div class="relatedPosts"><div class="headline"><i class="fas fa-thumbs-up fa-fw"></i><span>相关推荐</span></div><div class="relatedPosts-list"><a class="pagination-related" href="/2024/11/23/Revit%E4%BA%8C%E5%BC%80%E6%8C%87%E5%8D%97/01%E5%BC%80%E5%A7%8B/" title="01开始"><div class="cover" style="background: var(--default-bg-color)"></div><div class="info text-center"><div class="info-1"><div class="info-item-1"><i class="far fa-calendar-alt fa-fw"></i> 2024-11-23</div><div class="info-item-2">01开始</div></div><div class="info-2"><div class="info-item-1">开始Revit 平台 API 可通过与 Microsoft .NET Framework 4.5.2 或 4.6 兼容的任何语言（如 Visual C# 或 Visual Basic .NET （VB.NET））进行完全访问。Visual C# 和 VB.NET 通常用于开发 Revit 平台 API 应用程序。但是，本手册的重点是使用 Visual C# 开发应用程序。 欢迎使用 Revit Platform API所有基于 Autodesk Revit 的产品都是参数化建筑信息模型 （BIM） 工具。这样的工具可以看作是用于构建 3D 模型的 CAD 程序，而不是一组单独的图纸文件。Autodesk Revit 建模是通过柱、墙、门和窗等真实世界的元素完成的。用户可以创建模型的视图，包括平面图、剖面图和详图索引。所有这些视图都是直接从 3D 物理模型生成的，因此在一个视图中所做的更改将自动传播到所有其他视图。此过程几乎消除了在模型中进行更改时更新多个图纸和细节的需要。 Autodesk Revit API 旨在反映与程序的图形用户界面相同的用户交互范例。因此，了解 API...</div></div></div></a><a class="pagination-related" href="/2024/11/23/Revit%E4%BA%8C%E5%BC%80%E6%8C%87%E5%8D%97/02%E6%8F%92%E4%BB%B6%E9%9B%86%E6%88%90/" title="02插件集成"><div class="cover" style="background: var(--default-bg-color)"></div><div class="info text-center"><div class="info-1"><div class="info-item-1"><i class="far fa-calendar-alt fa-fw"></i> 2024-11-23</div><div class="info-item-2">02插件集成</div></div><div class="info-2"><div class="info-item-1">插件集成开发人员通过创建和实现 External Commands 和 External Applications 来添加功能。Revit 使用 .addin 清单文件标识新命令和应用程序。外部命令显示在 Add-Ins 选项卡上的 External Tools 菜单按钮下。外部应用程序在 Revit 启动时调用，在 Revit 关闭时卸载。 本章重点介绍以下内容：  了解如何使用 External Commands 和 External Applications 添加功能。 如何访问 Revit 事件。 如何自定义 Revit UI。  概述Revit 平台 API 基于 Revit 应用程序功能。Revit 平台 API 由两个类库组成，这两个类库仅在 Revit 运行时工作。 RevitAPI.dll包含用于在数据库级别访问 Revit 的应用程序、文档、图元和参数的方法。它还包含 IExternalDBApplication 和相关接口。 RevitAPIUI.dll包含与 Revit 用户界面的操作和自定义相关的所有 API...</div></div></div></a><a class="pagination-related" href="/2024/11/26/Revit%E4%BA%8C%E5%BC%80%E6%8C%87%E5%8D%97/03%E5%BA%94%E7%94%A8%E5%8F%8A%E6%96%87%E6%A1%A3/" title="03应用及文档"><div class="cover" style="background: var(--default-bg-color)"></div><div class="info text-center"><div class="info-1"><div class="info-item-1"><i class="far fa-calendar-alt fa-fw"></i> 2024-11-26</div><div class="info-item-2">03应用及文档</div></div><div class="info-2"><div class="info-item-1">Application及DocumentRevit 平台 API 中的顶级对象是Application和Document。这些类由 Application、UIApplication、Document 和 UIDocument 类表示。 Application对象是指单个 Revit 任务，提供对文档、选项和其他应用程序范围的数据和设置的访问。 Autodesk.Revit.UI.UIApplication - 提供对应用程序的 UI 级界面的访问，包括将 RibbonPanel 添加到用户界面的功能，以及在用户界面中获取活动文档的功能。 Autodesk.Revit.ApplicationServices.Application - 提供对所有其他应用程序级别属性的访问。 Document是表示建筑模型的单个 Revit 项目文件。Revit 可以打开多个项目，并为一个项目打开多个视图。 Autodesk.Revit.UI.UIDocument - 提供对文档的 UI...</div></div></div></a><a class="pagination-related" href="/2024/11/26/Revit%E4%BA%8C%E5%BC%80%E6%8C%87%E5%8D%97/05%E8%BF%87%E6%BB%A4/" title="05过滤"><div class="cover" style="background: var(--default-bg-color)"></div><div class="info text-center"><div class="info-1"><div class="info-item-1"><i class="far fa-calendar-alt fa-fw"></i> 2024-11-26</div><div class="info-item-2">05过滤</div></div><div class="info-2"><div class="info-item-1">Filtering 过滤Revit API提供了一种过滤和迭代Revit文档中图元的机制。这是获取一组相关元素（如文档中的所有墙或门）的最佳方法。过滤器也可以用来找到一个非常具体的元素集，如所有特定大小的梁。 获取通过指定过滤器的元素的基本步骤如下：  创建新的FilteredElementCollector 对它应用一个或多个过滤器 获取过滤后的元素或元素ID（使用以下几种方法之一）  下面的示例涵盖了在文档中筛选和迭代元素的基本步骤。 代码区域6-1：使用元素过滤获取文档中的所有墙实例 1234567891011121314// Find all Wall instances in the document by using category filterElementCategoryFilter filter = new ElementCategoryFilter(BuiltInCategory.OST_Walls);// Apply the filter to the elements in the active document// Use shortcut...</div></div></div></a><a class="pagination-related" href="/2024/12/05/Revit%E4%BA%8C%E5%BC%80%E6%8C%87%E5%8D%97/06%E9%80%89%E6%8B%A9/" title="06选择"><div class="cover" style="background: var(--default-bg-color)"></div><div class="info text-center"><div class="info-1"><div class="info-item-1"><i class="far fa-calendar-alt fa-fw"></i> 2024-12-05</div><div class="info-item-2">06选择</div></div><div class="info-2"><div class="info-item-1">选择您可以使用UIDo.Selection.GetElementIds()方法从当前活动文档中获取所选对象，该方法返回所选元素的ElementIds集合。此方法返回的集合可以直接与FilteredElementCollector一起使用，以筛选选定的元素。 Selection对象还可以用于使用SetElementIds()方法以编程方式更改当前选择。 Pages in this section 本节中的页面  Changing the Selection 更改选择 User Selection 用户选择 Filtered User Selection 筛选的用户选择  更改选择要修改选定的图元，请执行以下操作：  创建新的ElementId列表。 把ElementIds放进去。 使用新列表调用SetElementIds()。  下面的示例说明了如何通过获取当前选择并仅过滤出墙以设置为新选择来更改选定的元素。 代码区域7-1：更改所选元素 123456789101112131415161718192021222324252627282930313233private void...</div></div></div></a><a class="pagination-related" href="/2024/11/26/Revit%E4%BA%8C%E5%BC%80%E6%8C%87%E5%8D%97/04%E5%85%83%E7%B4%A0%E8%A6%81%E7%82%B9/" title="04元素要点"><div class="cover" style="background: var(--default-bg-color)"></div><div class="info text-center"><div class="info-1"><div class="info-item-1"><i class="far fa-calendar-alt fa-fw"></i> 2024-11-26</div><div class="info-item-2">04元素要点</div></div><div class="info-2"><div class="info-item-1">元素要点元素对应于单个建筑或绘图构件，例如门、墙或尺寸标注。此外，元素可以是门类型、视图或材质定义。 元素分类Revit 图元分为六组：模型、草图、视图、组、注释和信息。每个组都包含相关的元素及其相应的符号。 模型元素模型元素表示建筑项目中存在的物理项。“模型元素”组中的元素可以细分为以下元素： 族实例 - 族实例包含族实例对象。可以将族对象载入到项目中，也可以从族样板创建族对象。有关更多信息，请参阅系列实例。 主体图元 - 主体图元包含系统族对象，这些对象可以包含其他模型图元，例如墙、屋顶、天花板和楼板。有关主体图元的更多信息，请参见墙、楼板、屋顶和洞口。 结构元素-结构图元包含仅用于 Revit 结构特征的图元。有关 Structure Elements 的更多信息，请参见 Structural Engineering。 视图元素视图图元表示在 Revit 中查看其他对象并与其他对象交互的方式。有关更多信息，请参阅视图。 组元素组图元表示辅助图元，例如 Revit...</div></div></div></a></div></div><hr class="custom-hr"/><div id="post-comment"><div class="comment-head"><div class="comment-headline"><i class="fas fa-comments fa-fw"></i><span> 评论</span></div></div><div class="comment-wrap"><div><div id="giscus-wrap"></div></div></div></div></div><div class="aside-content" id="aside-content"><div class="card-widget card-info text-center"><div class="avatar-img"><img src="/images/4stars.png" onerror="this.onerror=null;this.src='/img/friend_404.gif'" alt="avatar"/></div><div class="author-info-name">funtim41@gmail.com</div><div class="author-info-description">实践-认识-再实践-再认识</div><div class="site-data"><a href="/archives/"><div class="headline">文章</div><div class="length-num">58</div></a><a href="/tags/"><div class="headline">标签</div><div class="length-num">5</div></a><a href="/categories/"><div class="headline">分类</div><div class="length-num">7</div></a></div><a id="card-info-btn" target="_blank" rel="noopener" href="https://github.com/FunTim41"><i class="fab fa-github"></i><span>Follow Me</span></a><div class="card-info-social-icons"><a class="social-icon" href="https://github.com/FunTim41" target="_blank" title="Github"><i class="fab fa-github" style="color: #FFFFFF;"></i></a></div></div><div class="card-widget card-announcement"><div class="item-headline"><i class="fas fa-bullhorn fa-shake"></i><span>公告</span></div><div class="announcement_content">This is my Blog</div></div><div class="sticky_layout"><div class="card-widget" id="card-toc"><div class="item-headline"><i class="fas fa-stream"></i><span>目录</span><span class="toc-percentage"></span></div><div class="toc-content"><ol class="toc"><li class="toc-item toc-level-1"><a class="toc-link" href="#%E5%BB%BA%E7%AD%91"><span class="toc-number">1.</span> <span class="toc-text">建筑</span></a><ol class="toc-child"><li class="toc-item toc-level-2"><a class="toc-link" href="#%E6%88%BF%E9%97%B4"><span class="toc-number">1.1.</span> <span class="toc-text">房间</span></a><ol class="toc-child"><li class="toc-item toc-level-3"><a class="toc-link" href="#%E6%88%BF%E9%97%B4%E8%BE%B9%E7%95%8C"><span class="toc-number">1.1.1.</span> <span class="toc-text">房间边界</span></a><ol class="toc-child"><li class="toc-item toc-level-4"><a class="toc-link" href="#%E6%A3%80%E7%B4%A2%E6%88%BF%E9%97%B4%E8%BE%B9%E7%95%8C"><span class="toc-number">1.1.1.1.</span> <span class="toc-text">检索房间边界</span></a></li></ol></li></ol></li><li class="toc-item toc-level-2"><a class="toc-link" href="#%E6%B3%A8%EF%BC%9A%E7%BF%BB%E8%AF%91%E8%87%AARevit-API-Developers-Guide"><span class="toc-number">1.2.</span> <span class="toc-text">注：翻译自Revit API Developers Guide</span></a></li></ol></li></ol></div></div><div class="card-widget card-recent-post"><div class="item-headline"><i class="fas fa-history"></i><span>最新文章</span></div><div class="aside-list"><div class="aside-list-item no-cover"><div class="content"><a class="title" href="/2025/01/16/Revit%E4%BA%8C%E5%BC%80%E7%A4%BA%E4%BE%8B/Revit%E4%B8%8EExcel%E4%BA%A4%E4%BA%92/" title="Revit与Excel交互">Revit与Excel交互</a><time datetime="2025-01-16T08:43:45.327Z" title="更新于 2025-01-16 16:43:45">2025-01-16</time></div></div><div class="aside-list-item no-cover"><div class="content"><a class="title" href="/2025/01/14/ObjectARX%EF%BC%9AManaged.NET%E5%BC%80%E5%8F%91%E4%BA%BA%E5%91%98%E6%8C%87%E5%8D%97/03%E5%88%9B%E5%BB%BA%E5%92%8C%E7%BC%96%E8%BE%91AutoCAD%E5%9B%BE%E5%85%83%EF%BC%88.NET%EF%BC%89/" title="03创建和编辑AutoCAD图元（.NET）">03创建和编辑AutoCAD图元（.NET）</a><time datetime="2025-01-14T04:28:05.785Z" title="更新于 2025-01-14 12:28:05">2025-01-14</time></div></div><div class="aside-list-item no-cover"><div class="content"><a class="title" href="/2025/01/13/ObjectARX%EF%BC%9AManaged.NET%E5%BC%80%E5%8F%91%E4%BA%BA%E5%91%98%E6%8C%87%E5%8D%97/02%E6%8E%A7%E5%88%B6AutoCAD%E7%8E%AF%E5%A2%83%EF%BC%88.NET%EF%BC%89/" title="02控制AutoCAD环境（.NET）">02控制AutoCAD环境（.NET）</a><time datetime="2025-01-14T02:31:41.869Z" title="更新于 2025-01-14 10:31:41">2025-01-14</time></div></div><div class="aside-list-item no-cover"><div class="content"><a class="title" href="/2025/01/12/ObjectARX%EF%BC%9AManaged.NET%E5%BC%80%E5%8F%91%E4%BA%BA%E5%91%98%E6%8C%87%E5%8D%97/01AutoCAD.NET%20API%EF%BC%88.NET%EF%BC%89%E7%9A%84%E5%9F%BA%E7%A1%80%E7%9F%A5%E8%AF%86/" title="01AutoCAD .NET API（.NET）的基础知识">01AutoCAD .NET API（.NET）的基础知识</a><time datetime="2025-01-14T02:31:29.466Z" title="更新于 2025-01-14 10:31:29">2025-01-14</time></div></div><div class="aside-list-item no-cover"><div class="content"><a class="title" href="/2024/12/19/RevitApi%E5%90%88%E9%9B%86/Autodesk.Revit.UI.Selection%20Namespace/" title="Autodesk.Revit.UI.Selection">Autodesk.Revit.UI.Selection</a><time datetime="2025-01-13T14:24:17.222Z" title="更新于 2025-01-13 22:24:17">2025-01-13</time></div></div></div></div></div></div></main><footer id="footer" style="background-image: url(/images/topback.jpg);"><div id="footer-wrap"><div class="copyright">&copy;2024 - 2025 By funtim41@gmail.com</div><div class="framework-info"><span>框架 </span><a target="_blank" rel="noopener" href="https://hexo.io">Hexo</a><span class="footer-separator">|</span><span>主题 </span><a target="_blank" rel="noopener" href="https://github.com/jerryc127/hexo-theme-butterfly">Butterfly</a></div><div class="footer_custom_text">学而不思则罔，思而不学则殆。</div></div></footer></div><div id="rightside"><div id="rightside-config-hide"><button id="readmode" type="button" title="阅读模式"><i class="fas fa-book-open"></i></button><button id="darkmode" type="button" title="日间和夜间模式切换"><i class="fas fa-adjust"></i></button><button id="hide-aside-btn" type="button" title="单栏和双栏切换"><i class="fas fa-arrows-alt-h"></i></button></div><div id="rightside-config-show"><button id="rightside-config" type="button" title="设置"><i class="fas fa-cog fa-spin"></i></button><button class="close" id="mobile-toc-button" type="button" title="目录"><i class="fas fa-list-ul"></i></button><a id="to_comment" href="#post-comment" title="前往评论"><i class="fas fa-comments"></i></a><button id="go-up" type="button" title="回到顶部"><span class="scroll-percent"></span><i class="fas fa-arrow-up"></i></button></div></div><div><script src="/js/utils.js"></script><script src="/js/main.js"></script><script src="https://cdn.jsdelivr.net/npm/node-snackbar/dist/snackbar.min.js"></script><script>(() => {
  const panguFn = () => {
    if (typeof pangu === 'object') pangu.autoSpacingPage()
    else {
      btf.getScript('https://cdn.jsdelivr.net/npm/pangu/dist/browser/pangu.min.js')
        .then(() => {
          pangu.autoSpacingPage()
        })
    }
  }

  const panguInit = () => {
    if (false){
      GLOBAL_CONFIG_SITE.isPost && panguFn()
    } else {
      panguFn()
    }
  }

  btf.addGlobalFn('pjaxComplete', panguInit, 'pangu')
  document.addEventListener('DOMContentLoaded', panguInit)
})()</script><div class="js-pjax"><script>(() => {
  const isShuoshuo = GLOBAL_CONFIG_SITE.isShuoshuo
  const option = null

  const getGiscusTheme = theme => theme === 'dark' ? 'dark' : 'light'

  const createScriptElement = config => {
    const ele = document.createElement('script')
    Object.entries(config).forEach(([key, value]) => {
      ele.setAttribute(key, value)
    })
    return ele
  }

  const loadGiscus = (el = document, key) => {
    const mappingConfig = isShuoshuo
      ? { 'data-mapping': 'specific', 'data-term': key }
      : { 'data-mapping': (option && option['data-mapping']) || 'pathname' }

    const giscusConfig = {
      src: 'https://giscus.app/client.js',
      'data-repo': 'FunTim41/funtim41.github.io',
      'data-repo-id': 'R_kgDONjG8ww',
      'data-category-id': 'DIC_kwDONjG8w84Cllg2',
      'data-theme': getGiscusTheme(document.documentElement.getAttribute('data-theme')),
      'data-reactions-enabled': '1',
      crossorigin: 'anonymous',
      async: true,
      ...option,
      ...mappingConfig
    }

    const scriptElement = createScriptElement(giscusConfig)

    el.querySelector('#giscus-wrap').appendChild(scriptElement)

    if (isShuoshuo) {
      window.shuoshuoComment.destroyGiscus = () => {
        if (el.children.length) {
          el.innerHTML = ''
          el.classList.add('no-comment')
        }
      }
    }
  }

  const changeGiscusTheme = theme => {
    const iframe = document.querySelector('#giscus-wrap iframe')
    if (iframe) {
      const message = {
        giscus: {
          setConfig: {
            theme: getGiscusTheme(theme)
          }
        }
      }
      iframe.contentWindow.postMessage(message, 'https://giscus.app')
    }
  }

  btf.addGlobalFn('themeChange', changeGiscusTheme, 'giscus')

  if (isShuoshuo) {
    'Giscus' === 'Giscus'
      ? window.shuoshuoComment = { loadComment: loadGiscus }
      : window.loadOtherComment = loadGiscus
    return
  }

  if ('Giscus' === 'Giscus' || !false) {
    if (false) btf.loadComment(document.getElementById('giscus-wrap'), loadGiscus)
    else loadGiscus()
  } else {
    window.loadOtherComment = loadGiscus
  }
})()</script></div><script defer="defer" id="fluttering_ribbon" mobile="false" src="https://cdn.jsdelivr.net/npm/butterfly-extsrc/dist/canvas-fluttering-ribbon.min.js"></script><script async data-pjax src="//busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js"></script><div id="local-search"><div class="search-dialog"><nav class="search-nav"><span class="search-dialog-title">搜索</span><span id="loading-status"></span><button class="search-close-button"><i class="fas fa-times"></i></button></nav><div class="text-center" id="loading-database"><i class="fas fa-spinner fa-pulse"></i><span>  数据加载中</span></div><div class="search-wrap"><div id="local-search-input"><div class="local-search-box"><input class="local-search-box--input" placeholder="搜索文章" type="text"/></div></div><hr/><div id="local-search-results"></div><div id="local-search-stats-wrap"></div></div></div><div id="search-mask"></div><script src="/js/search/local-search.js"></script></div></div></body></html>