<!DOCTYPE html><html lang="zh-CN" data-theme="light"><head><meta charset="UTF-8"><meta http-equiv="X-UA-Compatible" content="IE=edge"><meta name="viewport" content="width=device-width, initial-scale=1.0,viewport-fit=cover"><title>20材料 | funtim的博客</title><meta name="author" content="funtim41@gmail.com"><meta name="copyright" content="funtim41@gmail.com"><meta name="format-detection" content="telephone=no"><meta name="theme-color" content="#ffffff"><meta name="description" content="材质在Revit Platform API中，材质数据作为图元进行存储和管理。就像在Revit UI中一样，材质可以有多个与之关联的资源，但只能使用API指定热学和结构（在Revit UI中称为物理）资源。 某些材质特征由材质类本身的属性（例如FillPattern、Color或Render）表示，而其他材质特征则可用作与材质关联的结构资源或热资源的属性。 在本章中，您将学习如何访问Materia">
<meta property="og:type" content="article">
<meta property="og:title" content="20材料">
<meta property="og:url" content="https://funtim41.github.io/2024/12/15/Revit%E4%BA%8C%E5%BC%80%E6%8C%87%E5%8D%97/20%E6%9D%90%E6%96%99/">
<meta property="og:site_name" content="funtim的博客">
<meta property="og:description" content="材质在Revit Platform API中，材质数据作为图元进行存储和管理。就像在Revit UI中一样，材质可以有多个与之关联的资源，但只能使用API指定热学和结构（在Revit UI中称为物理）资源。 某些材质特征由材质类本身的属性（例如FillPattern、Color或Render）表示，而其他材质特征则可用作与材质关联的结构资源或热资源的属性。 在本章中，您将学习如何访问Materia">
<meta property="og:locale" content="zh_CN">
<meta property="og:image" content="https://funtim41.github.io/images/4stars.png">
<meta property="article:published_time" content="2024-12-15T04:26:08.000Z">
<meta property="article:modified_time" content="2025-01-13T14:20:59.310Z">
<meta property="article:author" content="funtim41@gmail.com">
<meta property="article:tag" content="Revit">
<meta name="twitter:card" content="summary">
<meta name="twitter:image" content="https://funtim41.github.io/images/4stars.png"><link rel="shortcut icon" href="/images/OIP.jfif"><link rel="canonical" href="https://funtim41.github.io/2024/12/15/Revit%E4%BA%8C%E5%BC%80%E6%8C%87%E5%8D%97/20%E6%9D%90%E6%96%99/"><link rel="preconnect" href="//cdn.jsdelivr.net"/><link rel="stylesheet" href="/css/index.css"><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free/css/all.min.css"><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/node-snackbar/dist/snackbar.min.css" media="print" onload="this.media='all'"><script>
    (() => {
      
    const saveToLocal = {
      set: (key, value, ttl) => {
        if (!ttl) return
        const expiry = Date.now() + ttl * 86400000
        localStorage.setItem(key, JSON.stringify({ value, expiry }))
      },
      get: key => {
        const itemStr = localStorage.getItem(key)
        if (!itemStr) return undefined
        const { value, expiry } = JSON.parse(itemStr)
        if (Date.now() > expiry) {
          localStorage.removeItem(key)
          return undefined
        }
        return value
      }
    }

    window.btf = {
      saveToLocal,
      getScript: (url, attr = {}) => new Promise((resolve, reject) => {
        const script = document.createElement('script')
        script.src = url
        script.async = true
        Object.entries(attr).forEach(([key, val]) => script.setAttribute(key, val))
        script.onload = script.onreadystatechange = () => {
          if (!script.readyState || /loaded|complete/.test(script.readyState)) resolve()
        }
        script.onerror = reject
        document.head.appendChild(script)
      }),
      getCSS: (url, id) => new Promise((resolve, reject) => {
        const link = document.createElement('link')
        link.rel = 'stylesheet'
        link.href = url
        if (id) link.id = id
        link.onload = link.onreadystatechange = () => {
          if (!link.readyState || /loaded|complete/.test(link.readyState)) resolve()
        }
        link.onerror = reject
        document.head.appendChild(link)
      }),
      addGlobalFn: (key, fn, name = false, parent = window) => {
        if (!false && key.startsWith('pjax')) return
        const globalFn = parent.globalFn || {}
        globalFn[key] = globalFn[key] || {}
        globalFn[key][name || Object.keys(globalFn[key]).length] = fn
        parent.globalFn = globalFn
      }
    }
  
      
      const activateDarkMode = () => {
        document.documentElement.setAttribute('data-theme', 'dark')
        if (document.querySelector('meta[name="theme-color"]') !== null) {
          document.querySelector('meta[name="theme-color"]').setAttribute('content', '#0d0d0d')
        }
      }
      const activateLightMode = () => {
        document.documentElement.setAttribute('data-theme', 'light')
        if (document.querySelector('meta[name="theme-color"]') !== null) {
          document.querySelector('meta[name="theme-color"]').setAttribute('content', '#ffffff')
        }
      }

      btf.activateDarkMode = activateDarkMode
      btf.activateLightMode = activateLightMode

      const theme = saveToLocal.get('theme')
    
          theme === 'dark' ? activateDarkMode() : theme === 'light' ? activateLightMode() : null
        
      
      const asideStatus = saveToLocal.get('aside-status')
      if (asideStatus !== undefined) {
        document.documentElement.classList.toggle('hide-aside', asideStatus === 'hide')
      }
    
      
    const detectApple = () => {
      if (/iPad|iPhone|iPod|Macintosh/.test(navigator.userAgent)) {
        document.documentElement.classList.add('apple')
      }
    }
    detectApple()
  
    })()
  </script><script>const GLOBAL_CONFIG = {
  root: '/',
  algolia: undefined,
  localSearch: {"path":"/search.xml","preload":false,"top_n_per_article":1,"unescape":false,"languages":{"hits_empty":"未找到符合您查询的内容：${query}","hits_stats":"共找到 ${hits} 篇文章"}},
  translate: undefined,
  highlight: {"plugin":"highlight.js","highlightCopy":true,"highlightLang":true,"highlightHeightLimit":false,"highlightFullpage":false,"highlightMacStyle":false},
  copy: {
    success: '复制成功',
    error: '复制失败',
    noSupport: '浏览器不支持'
  },
  relativeDate: {
    homepage: false,
    post: false
  },
  runtime: '',
  dateSuffix: {
    just: '刚刚',
    min: '分钟前',
    hour: '小时前',
    day: '天前',
    month: '个月前'
  },
  copyright: {"limitCount":150,"languages":{"author":"作者: funtim41@gmail.com","link":"链接: ","source":"来源: funtim的博客","info":"著作权归作者所有。商业转载请联系作者获得授权，非商业转载请注明出处。"}},
  lightbox: 'null',
  Snackbar: {"chs_to_cht":"已切换为繁体中文","cht_to_chs":"已切换为简体中文","day_to_night":"已切换为深色模式","night_to_day":"已切换为浅色模式","bgLight":"#49b1f5","bgDark":"#1f1f1f","position":"bottom-left"},
  infinitegrid: {
    js: 'https://cdn.jsdelivr.net/npm/@egjs/infinitegrid/dist/infinitegrid.min.js',
    buttonText: '加载更多'
  },
  isPhotoFigcaption: false,
  islazyload: false,
  isAnchor: true,
  percent: {
    toc: true,
    rightside: true,
  },
  autoDarkmode: false
}</script><script id="config-diff">var GLOBAL_CONFIG_SITE = {
  title: '20材料',
  isPost: true,
  isHome: false,
  isHighlightShrink: false,
  isToc: true,
  isShuoshuo: false
}</script><link rel="stylesheet" href="/css/bar.css"><meta name="generator" content="Hexo 7.3.0"></head><body><div id="web_bg" style="background: Color(#995a82);"></div><div id="sidebar"><div id="menu-mask"></div><div id="sidebar-menus"><div class="avatar-img text-center"><img src="/images/4stars.png" onerror="onerror=null;src='/img/friend_404.gif'" alt="avatar"/></div><div class="site-data text-center"><a href="/archives/"><div class="headline">文章</div><div class="length-num">58</div></a><a href="/tags/"><div class="headline">标签</div><div class="length-num">5</div></a><a href="/categories/"><div class="headline">分类</div><div class="length-num">7</div></a></div><div class="menus_items"><div class="menus_item"><a class="site-page" href="/"><i class="fa-fw fas fa-home"></i><span> Home</span></a></div><div class="menus_item"><a class="site-page" href="/archives/"><i class="fa-fw fas fa-archive"></i><span> Timeline</span></a></div><div class="menus_item"><a class="site-page" href="/tags/"><i class="fa-fw fas fa-tags"></i><span> Tags</span></a></div><div class="menus_item"><a class="site-page" href="/categories/"><i class="fa-fw fas fa-folder-open"></i><span> Categories</span></a></div><div class="menus_item"><a class="site-page" href="/Links/"><i class="fa-fw fas fa-link"></i><span> Links</span></a></div><div class="menus_item"><a class="site-page" href="/about/"><i class="fa-fw fas fa-heart"></i><span> About</span></a></div></div></div></div><div class="post" id="body-wrap"><header class="post-bg fixed" id="page-header" style="background-image: url(/images/topback.jpg);"><nav id="nav"><span id="blog-info"><a class="nav-site-title" href="/"><img class="site-icon" src="/images/OIP.jfif" alt="Logo"><span class="site-name">funtim的博客</span></a><a class="nav-page-title" href="/"><span class="site-name">20材料</span></a></span><div id="menus"><div id="search-button"><span class="site-page social-icon search"><i class="fas fa-search fa-fw"></i><span> 搜索</span></span></div><div class="menus_items"><div class="menus_item"><a class="site-page" href="/"><i class="fa-fw fas fa-home"></i><span> Home</span></a></div><div class="menus_item"><a class="site-page" href="/archives/"><i class="fa-fw fas fa-archive"></i><span> Timeline</span></a></div><div class="menus_item"><a class="site-page" href="/tags/"><i class="fa-fw fas fa-tags"></i><span> Tags</span></a></div><div class="menus_item"><a class="site-page" href="/categories/"><i class="fa-fw fas fa-folder-open"></i><span> Categories</span></a></div><div class="menus_item"><a class="site-page" href="/Links/"><i class="fa-fw fas fa-link"></i><span> Links</span></a></div><div class="menus_item"><a class="site-page" href="/about/"><i class="fa-fw fas fa-heart"></i><span> About</span></a></div></div><div id="toggle-menu"><span class="site-page"><i class="fas fa-bars fa-fw"></i></span></div></div></nav><div id="post-info"><h1 class="post-title">20材料</h1><div id="post-meta"><div class="meta-firstline"><span class="post-meta-date"><i class="far fa-calendar-alt fa-fw post-meta-icon"></i><span class="post-meta-label">发表于</span><time class="post-meta-date-created" datetime="2024-12-15T04:26:08.000Z" title="发表于 2024-12-15 12:26:08">2024-12-15</time><span class="post-meta-separator">|</span><i class="fas fa-history fa-fw post-meta-icon"></i><span class="post-meta-label">更新于</span><time class="post-meta-date-updated" datetime="2025-01-13T14:20:59.310Z" title="更新于 2025-01-13 22:20:59">2025-01-13</time></span><span class="post-meta-categories"><span class="post-meta-separator">|</span><i class="fas fa-inbox fa-fw post-meta-icon"></i><a class="post-meta-categories" href="/categories/Revit%E4%BA%8C%E6%AC%A1%E5%BC%80%E5%8F%91%E4%BA%BA%E5%91%98%E6%8C%87%E5%8D%97/">Revit二次开发人员指南</a></span></div><div class="meta-secondline"><span class="post-meta-separator">|</span><span class="post-meta-pv-cv" id="" data-flag-title=""><i class="far fa-eye fa-fw post-meta-icon"></i><span class="post-meta-label">浏览量:</span><span id="busuanzi_value_page_pv"><i class="fa-solid fa-spinner fa-spin"></i></span></span></div></div></div></header><main class="layout" id="content-inner"><div id="post"><article class="container post-content" id="article-container"><h1 id="材质"><a href="#材质" class="headerlink" title="材质"></a><a target="_blank" rel="noopener" href="https://help.autodesk.com/view/RVT/2018/ENU/?guid=Revit_API_Revit_API_Developers_Guide_Revit_Geometric_Elements_Material_html">材质</a></h1><p>在Revit Platform API中，材质数据作为图元进行存储和管理。就像在Revit UI中一样，材质可以有多个与之关联的资源，但只能使用API指定热学和结构（在Revit UI中称为物理）资源。</p>
<p>某些材质特征由材质类本身的属性（例如FillPattern、Color或Render）表示，而其他材质特征则可用作与材质关联的结构资源或热资源的属性。</p>
<p>在本章中，您将学习如何访问Material元素以及如何管理文档中的Material对象。“元素材质”提供了一个演练，演示如何获取窗材质。</p>
<p>本节中的页面</p>
<ul>
<li>一般材质信息</li>
<li>材质管理</li>
<li>元素材质</li>
<li>材质数量</li>
<li>绘制元素的表面</li>
</ul>
<h2 id="一般材质信息"><a href="#一般材质信息" class="headerlink" title="一般材质信息"></a>一般材质信息</h2><p>在开始演练之前，请通读以下部分以更好地理解Material类。</p>
<p>所有材质对象都可以使用材质类过滤器进行检索。材质对象也可在文档、类别、元素、面等中使用，并在本章的相关部分中进行讨论。无论你在哪里得到一个材质对象，它都被表示为Material类。</p>
<p><strong>属性</strong></p>
<p>材质将具有与渲染外观、结构或其他主要材质类别相关的一个或多个方面。每个方面都由Material类本身的属性或通过其结构或热资产之一表示。StructuralAsset类表示与结构分析相关的材料属性。ThermalAsset类表示与能量分析相关的材料属性。</p>
<p>代码区域19-3：获取材料属性</p>
<figure class="highlight c#"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br><span class="line">23</span><br><span class="line">24</span><br><span class="line">25</span><br><span class="line">26</span><br><span class="line">27</span><br><span class="line">28</span><br><span class="line">29</span><br><span class="line">30</span><br><span class="line">31</span><br><span class="line">32</span><br><span class="line">33</span><br><span class="line">34</span><br><span class="line">35</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="keyword">private</span> <span class="keyword">void</span> <span class="title">ReadMaterialProps</span>(<span class="params">Document document, Material material</span>)</span></span><br><span class="line">&#123;</span><br><span class="line">    ElementId strucAssetId = material.StructuralAssetId;</span><br><span class="line">    <span class="keyword">if</span> (strucAssetId != ElementId.InvalidElementId)</span><br><span class="line">    &#123;</span><br><span class="line">        PropertySetElement pse = document.GetElement(strucAssetId) asPropertySetElement;</span><br><span class="line">        <span class="keyword">if</span> (pse != <span class="literal">null</span>)</span><br><span class="line">        &#123;</span><br><span class="line">            StructuralAsset asset = pse.GetStructuralAsset();</span><br><span class="line"></span><br><span class="line">            <span class="comment">// Check the material behavior and only read if Isotropic</span></span><br><span class="line">            <span class="keyword">if</span> (asset.Behavior == StructuralBehavior.Isotropic)</span><br><span class="line">            &#123;</span><br><span class="line">                <span class="comment">// Get the class of material</span></span><br><span class="line">                StructuralAssetClass assetClass = asset.StructuralAssetClass; <span class="comment">// Get other material properties</span></span><br><span class="line"></span><br><span class="line">                <span class="comment">// Get other material properties</span></span><br><span class="line">                <span class="built_in">double</span> poisson = asset.PoissonRatio.X;</span><br><span class="line">                <span class="built_in">double</span> youngMod = asset.YoungModulus.X;</span><br><span class="line">                <span class="built_in">double</span> thermCoeff = asset.ThermalExpansionCoefficient.X;</span><br><span class="line">                <span class="built_in">double</span> unitweight = asset.Density;</span><br><span class="line">                <span class="built_in">double</span> shearMod = asset.ShearModulus.X;</span><br><span class="line">                <span class="built_in">double</span> dampingRatio = asset.DampingRatio;</span><br><span class="line">                <span class="keyword">if</span> (assetClass == StructuralAssetClass.Metal)</span><br><span class="line">                &#123;</span><br><span class="line">                    <span class="built_in">double</span> dMinStress = asset.MinimumYieldStress;</span><br><span class="line">                &#125;</span><br><span class="line">                elseif (assetClass == StructuralAssetClass.Concrete)</span><br><span class="line">                &#123;</span><br><span class="line">                    <span class="built_in">double</span> dConcComp = asset.ConcreteCompression;</span><br><span class="line">                &#125;</span><br><span class="line">            &#125;</span><br><span class="line">        &#125;</span><br><span class="line">    &#125;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<p><strong>Classification</strong> </p>
<p>与结构分析相关的材料分类（即钢、混凝土、木材）可以从与材料关联的StructuralAsset的StructuralAssetClass属性中获得。</p>
<p>注意：API不提供对混凝土材料的混凝土类型值的访问。</p>
<p>与能量分析相关的材料分类（即固体、液体、气体）可以从与材料关联的ThermalAsset的ThermalMaterialType属性中获得。</p>
<p><strong>其它性质</strong></p>
<p>材质对象属性标识特定类型的材质，包括颜色、填充图案等。</p>
<p>属性和参数</p>
<p>某些“材质”属性只能作为“参数”使用。有一些，如颜色，可作为属性或作为参数使用内置参数MATERIAL_PARAM_COLOR。</p>
<p>渲染信息</p>
<p>渲染数据的集合被组织到称为资源的对象中，这些对象是只读的。您可以从Application.Assets属性获取所有可用的与外观相关的资产。可以通过Material.AppearanceAssetId属性从材质访问外观资源。</p>
<p>下图显示了“资源浏览器”对话框的“外观库”部分，其中显示了某些渲染资源在UI中的显示方式。</p>
<p><img src="https://help.autodesk.com/cloudhelp/2018/ENU/Revit-API/images/AssetBrowser.jpg"></p>
<p>图106：外观库</p>
<p>SDK附带的Materials示例应用程序显示了如何将RenderApperance属性设置为对话框中选定的材质。该对话框将填充Application.Assets中的所有Asset对象。</p>
<p>填充模式</p>
<p>文档中的所有FillPatterns都可以使用FilteredElementCollector过滤类FillPatternElement。FillPatternElement是包含FillPattern的元素，而FillPattern类提供对模式名称和组成模式的FillGrid集的访问。</p>
<p>FillPatterns有两种：Drafting和Model。在UI中，只能将“绘图”填充样式设置为Material.CutPatternId。填充图案类型通过FillPattern.Target属性公开。下面的示例显示如何更改材质FillPattern。</p>
<p>代码区域19-4：设置填充图案</p>
<figure class="highlight c#"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="keyword">public</span> <span class="keyword">void</span> <span class="title">SetFillPattern</span>(<span class="params">Document document, Material material</span>)</span></span><br><span class="line">&#123;</span><br><span class="line">    FilteredElementCollector collector = <span class="keyword">new</span> FilteredElementCollector(document);</span><br><span class="line">    ICollection fillPatternElements = collector.OfClass(<span class="keyword">typeof</span>(FillPatternElement)).ToElementIds();</span><br><span class="line">    <span class="keyword">foreach</span> (ElementId fillPatternId <span class="keyword">in</span> fillPatternElements)</span><br><span class="line">    &#123;</span><br><span class="line">        <span class="comment">// always set successfully</span></span><br><span class="line">        material.CutPatternId = fillPatternId;</span><br><span class="line">        material.SurfacePatternId = fillPatternId;</span><br><span class="line">    &#125;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<h2 id="材质管理"><a href="#材质管理" class="headerlink" title="材质管理"></a>材质管理</h2><p>您可以使用过滤来检索文档中的所有材料。文档中的每个Material对象都由唯一的名称标识。</p>
<p>以下示例说明如何使用材质名称获取材质。</p>
<p>代码区域19-5：按名称获取材质</p>
<figure class="highlight c#"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br></pre></td><td class="code"><pre><span class="line">FilteredElementCollector elementCollector = <span class="keyword">new</span> FilteredElementCollector(document);</span><br><span class="line">elementCollector.WherePasses(<span class="keyword">new</span> ElementClassFilter(<span class="keyword">typeof</span>(Material)));</span><br><span class="line">IList materials = elementCollector.ToElements();</span><br><span class="line"></span><br><span class="line">Material floorMaterial = <span class="literal">null</span>;</span><br><span class="line"><span class="built_in">string</span> floorMaterialName = <span class="string">&quot;Default Floor&quot;</span>;</span><br><span class="line"></span><br><span class="line"><span class="keyword">foreach</span> (Element materialElement <span class="keyword">in</span> materials)</span><br><span class="line">&#123;</span><br><span class="line">    Material material = materialElement <span class="keyword">as</span> Material;</span><br><span class="line">    <span class="keyword">if</span> (floorMaterialName == material.Name)</span><br><span class="line">    &#123;</span><br><span class="line">        floorMaterial = material;</span><br><span class="line">        <span class="keyword">break</span>;</span><br><span class="line">    &#125;</span><br><span class="line">&#125;</span><br><span class="line"><span class="keyword">if</span> (<span class="literal">null</span> != floorMaterial)</span><br><span class="line">&#123;</span><br><span class="line">    TaskDialog.Show(<span class="string">&quot;Revit&quot;</span>,<span class="string">&quot;Material found.&quot;</span>);</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<p>注意：要运行示例代码，请确保文档中存在材质名称。当前文档的所有材质名称都位于“管理”选项卡（“项目设置”面板  Materials）下。</p>
<p>创建材质</p>
<p>有两种方法可以在API中创建新的Material对象。</p>
<ul>
<li>复制现有材质</li>
<li>添加新材质。</li>
</ul>
<p>使用Duplicate（）方法时，返回的Material对象与原始对象的类型相同。</p>
<p>代码区域19-6：复制材料</p>
<figure class="highlight c#"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="keyword">private</span> <span class="built_in">bool</span> <span class="title">DuplicateMaterial</span>(<span class="params">Material material</span>)</span></span><br><span class="line">&#123;</span><br><span class="line">        <span class="built_in">bool</span> duplicated = <span class="literal">false</span>;</span><br><span class="line">        <span class="comment">//try to duplicate a new instance of Material class using duplicate method</span></span><br><span class="line">        <span class="comment">//make sure the name of new material is unique in MaterailSet</span></span><br><span class="line">        <span class="built_in">string</span> newName = <span class="string">&quot;new&quot;</span> + material.Name;</span><br><span class="line">        Material myMaterial = material.Duplicate(newName);</span><br><span class="line">        <span class="keyword">if</span> (<span class="literal">null</span> == myMaterial)</span><br><span class="line">        &#123;</span><br><span class="line">                TaskDialog.Show(<span class="string">&quot;Revit&quot;</span>, <span class="string">&quot;Failed to duplicate a material!&quot;</span>);</span><br><span class="line">        &#125;</span><br><span class="line">        <span class="keyword">else</span></span><br><span class="line">        &#123;</span><br><span class="line">                duplicated = <span class="literal">true</span>;</span><br><span class="line">        &#125;</span><br><span class="line"></span><br><span class="line">        <span class="keyword">return</span> duplicated;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<p>使用静态方法Material.Create（）直接添加新Material。无论如何应用，都必须为材质和属于该材质的任何资产指定唯一的名称。唯一名称是“材质”对象键。</p>
<p>代码区域19-7：添加新材质</p>
<figure class="highlight c#"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br></pre></td><td class="code"><pre><span class="line"><span class="comment">//Create the material</span></span><br><span class="line">ElementId materialId = Material.Create(document, <span class="string">&quot;My Material&quot;</span>);</span><br><span class="line">Material material = document.GetElement(materialId) <span class="keyword">as</span> Material;</span><br><span class="line"></span><br><span class="line"><span class="comment">//Create a new property set that can be used by this material</span></span><br><span class="line">StructuralAsset strucAsset = <span class="keyword">new</span> StructuralAsset(<span class="string">&quot;My Property Set&quot;</span>, StructuralAssetClass.Concrete);</span><br><span class="line">strucAsset.Behavior = StructuralBehavior.Isotropic;</span><br><span class="line">strucAsset.Density = <span class="number">232.0</span>;</span><br><span class="line"></span><br><span class="line"><span class="comment">//Assign the property set to the material.</span></span><br><span class="line">PropertySetElement pse = PropertySetElement.Create(document, strucAsset);</span><br><span class="line">material.SetMaterialAspectByPropertySet(MaterialAspect.Structural, pse.Id);</span><br></pre></td></tr></table></figure>

<p>删除材质</p>
<p>要删除材料，用：</p>
<ul>
<li>Document.Delete()</li>
</ul>
<p>Document.Delete() 是一个泛型方法。有关详细信息，请参见编辑元素。</p>
<h2 id="元素材质"><a href="#元素材质" class="headerlink" title="元素材质"></a>元素材质</h2><p>一个元素可以有多个元素和组件。例如，FamilyInstance具有SubComponents，Wall具有CompoundStructure，其中包含多个CompoundStructureLayers。(有关“子构件”的详细信息，请参阅“族”部分，有关“复合结构”的详细信息，请参阅“墙、楼板、屋顶和洞口”。）</p>
<p>在Revit Platform API中，使用以下准则获取图元的材质：</p>
<ul>
<li>如果元素包含元素，则单独获取材料。</li>
<li>如果图元包含构件，请从参数或以特定方式获取每个构件的材质（请参见墙、楼板、屋顶和洞口中的“材质”部分）。</li>
<li>如果构件的材质返回null，则从相应的Element.Category子类别中获取物料。</li>
</ul>
<p><strong>参数中的材质</strong></p>
<p>如果Element对象有一个参数，其中的参数类型是参数类型.材料，您可以从参数中获取元素材料。例如，结构柱FamilySymbol（类别为BuiltInCategory.OST_StructuralColumns的FamilyInstance）具有“结构材质”参数。使用ElementId获取材质。下面的代码示例阐释如何获取具有一个构件的结构柱Material。</p>
<p>代码区域：从参数获取元素材质</p>
<figure class="highlight c#"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br><span class="line">23</span><br><span class="line">24</span><br><span class="line">25</span><br><span class="line">26</span><br><span class="line">27</span><br><span class="line">28</span><br><span class="line">29</span><br><span class="line">30</span><br><span class="line">31</span><br><span class="line">32</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="keyword">public</span> <span class="keyword">void</span> <span class="title">GetMaterial</span>(<span class="params">Document document, FamilyInstance familyInstance</span>)</span></span><br><span class="line">&#123;</span><br><span class="line">    <span class="keyword">foreach</span> (Parameter parameter <span class="keyword">in</span> familyInstance.Parameters)</span><br><span class="line">    &#123;</span><br><span class="line">        Definition definition = parameter.Definition;</span><br><span class="line">        <span class="comment">// material is stored as element id</span></span><br><span class="line">        <span class="keyword">if</span> (parameter.StorageType == StorageType.ElementId)</span><br><span class="line">        &#123;</span><br><span class="line">            <span class="keyword">if</span> (definition.ParameterGroup == BuiltInParameterGroup.PG_MATERIALS &amp;&amp;</span><br><span class="line">                    definition.ParameterType == ParameterType.Material)</span><br><span class="line">            &#123;</span><br><span class="line">                Autodesk.Revit.DB.Material material = <span class="literal">null</span>;</span><br><span class="line">                Autodesk.Revit.DB.ElementId materialId = parameter.AsElementId();</span><br><span class="line">                <span class="keyword">if</span> (<span class="number">-1</span> == materialId.IntegerValue)</span><br><span class="line">                &#123;</span><br><span class="line">                    <span class="comment">//Invalid ElementId, assume the material is &quot;By Category&quot;</span></span><br><span class="line">                    <span class="keyword">if</span> (<span class="literal">null</span> != familyInstance.Category)</span><br><span class="line">                    &#123;</span><br><span class="line">                        material = familyInstance.Category.Material;</span><br><span class="line">                    &#125;</span><br><span class="line">                &#125;</span><br><span class="line">                <span class="keyword">else</span></span><br><span class="line">                &#123;</span><br><span class="line">                    material = document.GetElement(materialId) <span class="keyword">as</span> Material;</span><br><span class="line">                &#125;</span><br><span class="line"></span><br><span class="line">                TaskDialog.Show(<span class="string">&quot;Revit&quot;</span>,<span class="string">&quot;Element material: &quot;</span> + material.Name);</span><br><span class="line">                <span class="keyword">break</span>;</span><br><span class="line">            &#125;</span><br><span class="line">        &#125;</span><br><span class="line">    &#125;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<p><strong>注意：</strong>如果在UI中将材质属性设置为“按类别”，则材质的ElementId为ElementId.InvalidElementId，并且不能用于检索Material对象，如示例代码中所示。尝试从类别中检索材质，如下一节所述。 其他化合物参数中包含的某些材质特性无法从API访问。例如，在下图中，对于“系统族：栏杆扶手”，“栏杆结构”参数的“栏杆类型”为“栏杆类型.无”。因此，在这种情况下，您无法获得实质性信息。<img src="https://help.autodesk.com/cloudhelp/2018/ENU/Revit-API/images/ByCategory.jpg"></p>
<p>图107：扶手结构属性</p>
<p> Material和FamilyInstance 梁族、柱族和基础族有另一种使用其StructuralMaterialId属性获取其材质的方法。此属性返回一个ElementId，用于标识定义实例的结构分析属性的材质。</p>
<p>代码区域：从族实例获取图元材质</p>
<figure class="highlight c#"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="keyword">public</span> Material <span class="title">GetFamilyInstanceMaterial</span>(<span class="params">Document document, FamilyInstance beam</span>)</span></span><br><span class="line">&#123;</span><br><span class="line">    Material material = document.GetElement(beam.StructuralMaterialId) <span class="keyword">as</span> Material;</span><br><span class="line"></span><br><span class="line">    <span class="keyword">return</span> material;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<p><strong>材质和类别</strong></p>
<p>只有模型图元可以具有材质。</p>
<p>从Revit的“管理”选项卡中，单击“设置” <img src="https://help.autodesk.com/cloudhelp/2018/ENU/Revit-API/images/ac.menuaro.gif" alt="img"> “对象样式”以显示“对象样式”对话框。类别列在“模型对象”（Model Objects)选项卡中的图元具有材质信息。</p>
<p><img src="https://help.autodesk.com/cloudhelp/2018/ENU/Revit-API/images/ModelObjectsMaterial.jpg" alt="img"></p>
<p>图108：材质分类</p>
<p>只有模型元素可以指定“材质”属性。因此，查询与Model元素（例如，Annotations或Imported）以外的元素相对应的类别的Material将始终导致null。有关元素和类别分类的更多详细信息，请参阅元素要素。</p>
<p>如果一个元素有多个组件，则某些类别.子类别对应于这些组件。</p>
<p>在上一个“对象样式”对话框中，“窗类别”和“框架&#x2F;竖梃”子类别以及“玻璃”子类别将映射到windows元素中的构件。在下图中，似乎窗符号Glass材质参数是获取窗玻璃材质的唯一方法。但是，该值为“按类别”，相应的参数返回ElementId. InvalidElementId。</p>
<p>在这种情况下，窗户的Material不为null，它取决于Category OST_WindowsFrameMullionProjection的Material属性，该属性是窗口类别OST_Windows的子类别。如果它也返回null，则窗格的Material由父类别OST_Windows确定。有关更多详细信息，请参阅元素材质。</p>
<p><img src="https://help.autodesk.com/cloudhelp/2018/ENU/Revit-API/images/GUID-4E345BF1-1837-41C7-BF9C-A89A1A76539F-low.png"></p>
<p>图109：窗户材料</p>
<p><strong>复合结构层材料</strong></p>
<p>可以从HostObjAttributes获取CompoundStructureLayer对象。有关详细信息，请参阅墙、地板、天花板、屋顶和洞口。</p>
<p><strong>电子元件材料</strong></p>
<p>下图显示了检索元素材质的工作流：</p>
<p><img src="https://help.autodesk.com/cloudhelp/2018/ENU/Revit-API/images/GUID-64D41480-87CE-454E-8B14-1EFEFEC8BF09-low.png"></p>
<p>图110：获取元素材质工作流</p>
<p>此工作流说明了以下过程：</p>
<ul>
<li>该工作流显示了如何获取属于图元的Material对象（而不是Autodesk.Revit.DB.Structure.StructuralMaterialType枚举类型）。</li>
<li>检索材质时有两种要素分类：<ul>
<li>HostObject with CompoundStructure -从CompoundStructureLayer类MaterialId属性获取Material对象。</li>
<li>其他-从参数中获取材质。</li>
</ul>
</li>
<li>当您获得空Material对象或值为ElementId.InvalidElementId的无效ElementId时，请尝试相应类别中的Material。请注意，FamilyInstance及其FamilySymbol通常具有相同的类别。</li>
<li>对Element对象了解得越多，获取材质就越容易。举例来说：<ul>
<li>如果知道元素是梁，则可以获取实例参数Structural Material</li>
<li>如果知道该元素是一个窗口，则可以将其强制转换为FamilyInstance并获取FamilySymbol。</li>
</ul>
</li>
<li>之后，您可以获得参数，如框架外部材料或框架内部材料，以获得材料对象。如果你得到null，尝试从FamilySymbol类别中获取Material对象。</li>
<li>API中并非所有元素材质都可用。</li>
</ul>
<p><strong>演练：获取窗户材质</strong></p>
<figure class="highlight c#"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br><span class="line">23</span><br><span class="line">24</span><br><span class="line">25</span><br><span class="line">26</span><br><span class="line">27</span><br><span class="line">28</span><br><span class="line">29</span><br><span class="line">30</span><br><span class="line">31</span><br><span class="line">32</span><br><span class="line">33</span><br><span class="line">34</span><br><span class="line">35</span><br><span class="line">36</span><br><span class="line">37</span><br><span class="line">38</span><br><span class="line">39</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="keyword">public</span> <span class="keyword">void</span> <span class="title">GetMaterial</span>(<span class="params">Document document, FamilyInstance window</span>)</span></span><br><span class="line">&#123;</span><br><span class="line">    FamilySymbol windowSymbol = window.Symbol;</span><br><span class="line">    Category category = windowSymbol.Category;</span><br><span class="line">    Autodesk.Revit.DB.Material frameExteriorMaterial = <span class="literal">null</span>;</span><br><span class="line">    Autodesk.Revit.DB.Material frameInteriorMaterial = <span class="literal">null</span>;</span><br><span class="line">    Autodesk.Revit.DB.Material sashMaterial = <span class="literal">null</span>;</span><br><span class="line">    <span class="comment">// Check the parameters first</span></span><br><span class="line">    <span class="keyword">foreach</span> (Parameter parameter <span class="keyword">in</span> windowSymbol.Parameters)</span><br><span class="line">    &#123;</span><br><span class="line">        <span class="keyword">switch</span> (parameter.Definition.Name)</span><br><span class="line">        &#123;</span><br><span class="line">            <span class="keyword">case</span> <span class="string">&quot;Frame Exterior Material&quot;</span>:</span><br><span class="line">                frameExteriorMaterial = document.GetElement(parameter.AsElementId()) <span class="keyword">as</span> Material;</span><br><span class="line">                <span class="keyword">break</span>;</span><br><span class="line">            <span class="keyword">case</span> <span class="string">&quot;Frame Interior Material&quot;</span>:</span><br><span class="line">                frameInteriorMaterial = document.GetElement(parameter.AsElementId()) <span class="keyword">as</span> Material;</span><br><span class="line">                <span class="keyword">break</span>;</span><br><span class="line">            <span class="keyword">case</span> <span class="string">&quot;Sash&quot;</span>:</span><br><span class="line">                sashMaterial = document.GetElement(parameter.AsElementId()) <span class="keyword">as</span> Material;</span><br><span class="line">                <span class="keyword">break</span>;</span><br><span class="line">            <span class="literal">default</span>:</span><br><span class="line">                <span class="keyword">break</span>;</span><br><span class="line">        &#125;</span><br><span class="line">    &#125;</span><br><span class="line">    <span class="comment">// Try category if the material is set by category</span></span><br><span class="line">    <span class="keyword">if</span> (<span class="literal">null</span> == frameExteriorMaterial)</span><br><span class="line">        frameExteriorMaterial = category.Material;</span><br><span class="line">    <span class="keyword">if</span> (<span class="literal">null</span> == frameInteriorMaterial)</span><br><span class="line">        frameInteriorMaterial = category.Material;</span><br><span class="line">    <span class="keyword">if</span> (<span class="literal">null</span> == sashMaterial)</span><br><span class="line">        sashMaterial = category.Material;</span><br><span class="line">    <span class="comment">// Show the result because the category may have a null Material,</span></span><br><span class="line">    <span class="comment">// the Material objects need to be checked.</span></span><br><span class="line">    <span class="built_in">string</span> materialsInfo = <span class="string">&quot;Frame Exterior Material: &quot;</span> + (<span class="literal">null</span> != frameExteriorMaterial ? frameExteriorMaterial.Name : <span class="string">&quot;null&quot;</span>) + <span class="string">&quot;\n&quot;</span>;</span><br><span class="line">    materialsInfo += <span class="string">&quot;Frame Interior Material: &quot;</span> + (<span class="literal">null</span> != frameInteriorMaterial ? frameInteriorMaterial.Name : <span class="string">&quot;null&quot;</span>) + <span class="string">&quot;\n&quot;</span>;</span><br><span class="line">    materialsInfo += <span class="string">&quot;Sash: &quot;</span> + (<span class="literal">null</span> != sashMaterial ? sashMaterial.Name : <span class="string">&quot;null&quot;</span>) + <span class="string">&quot;\n&quot;</span>;</span><br><span class="line">    TaskDialog.Show(<span class="string">&quot;Revit&quot;</span>,materialsInfo);</span><br><span class="line">&#125; </span><br></pre></td></tr></table></figure>

<h2 id="材质数量"><a href="#材质数量" class="headerlink" title="材质数量"></a>材质数量</h2><p>有一些方法可以直接获取Revit为材质提取明细表计算的材质体积和面积：</p>
<ul>
<li>Element.GetMaterialIds() –获取元素中的材料列表</li>
<li>Element.GetMaterialVolume() – 获取元素中特定材料的体积</li>
<li>Element.GetMaterialArea() – 获取元素中特定材质的面积</li>
</ul>
<p>这些方法适用于其中Category. HasMaterialList属性为true的元素类别。实际上，这仅限于使用复合结构的图元（如墙、屋顶、楼板、天花板）、其他一些基本三维图元（如楼梯）以及可以将材质指定给族几何图形的三维族（如窗、门、柱、MEP设备和装置以及常规模型族）。请注意，在这些类别中，对于如何提取材料数量有进一步的限制。例如，幕墙和幕墙屋顶本身不会报告任何材质数量;这些构件使用的材质可以从组成幕墙系统的各个嵌板图元中提取。</p>
<p>请注意，在某些情况下，Revit计算的体积和面积可能是近似值。例如，对于墙内的各个层，模型中可见的体积与材质提取明细表中显示的体积之间可能会出现微小的差异。使用墙饰条工具向墙添加饰条或分隔缝时，或在某些连接条件下，往往会出现这些差异。</p>
<p>SDK示例“MaterialTools”结合了材质数量提取工具和剪切元素（洞口、窗和门）的临时抑制，以提取总材质数量和净材质数量。</p>
<p><img src="https://help.autodesk.com/cloudhelp/2018/ENU/Revit-API/images/material_quantities.png"></p>
<h2 id="绘制元素的表面"><a href="#绘制元素的表面" class="headerlink" title="绘制元素的表面"></a>绘制元素的表面</h2><p>绘制工具功能可通过Revit API使用。可以使用材质绘制墙、楼板和屋顶等图元的面以更改其外观。它不会改变元素的结构。</p>
<p>与绘制元素相关的方法是Document类的一部分。Paint（）将材质应用于元素的指定面。Document.RemovePaint（）将移除应用的材质。此外，IsPainted（）和GetPaintedMaterial（）方法返回有关元素表面的信息。</p>
<p>代码区域：绘制墙面</p>
<figure class="highlight c#"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br></pre></td><td class="code"><pre><span class="line"><span class="comment">// Paint any unpainted faces of a given wall</span></span><br><span class="line"><span class="function"><span class="keyword">public</span> <span class="keyword">void</span> <span class="title">PaintWallFaces</span>(<span class="params">Wall wall, ElementId matId</span>)</span></span><br><span class="line">&#123;</span><br><span class="line">    Document doc = wall.Document;</span><br><span class="line">    GeometryElement geometryElement = wall.get_Geometry(<span class="keyword">new</span> Options());</span><br><span class="line">    <span class="keyword">foreach</span> (GeometryObject geometryObject <span class="keyword">in</span> geometryElement)</span><br><span class="line">    &#123;</span><br><span class="line">        <span class="keyword">if</span> (geometryObject <span class="keyword">is</span> Solid)</span><br><span class="line">        &#123;</span><br><span class="line">            Solid solid = geometryObject <span class="keyword">as</span> Solid;</span><br><span class="line">            <span class="keyword">foreach</span> (Face face <span class="keyword">in</span> solid.Faces)</span><br><span class="line">            &#123;</span><br><span class="line">                <span class="keyword">if</span> (doc.IsPainted(wall.Id, face) == <span class="literal">false</span>)</span><br><span class="line">                &#123;</span><br><span class="line">                    doc.Paint(wall.Id, face, matId);</span><br><span class="line">                &#125;</span><br><span class="line">            &#125;</span><br><span class="line">        &#125;</span><br><span class="line">    &#125;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<h2 id="注：翻译自Revit-API-Developers-Guide"><a href="#注：翻译自Revit-API-Developers-Guide" class="headerlink" title="注：翻译自Revit API Developers Guide"></a><em><strong>注：</strong></em>翻译自<a target="_blank" rel="noopener" href="https://help.autodesk.com/view/RVT/2018/ENU/?guid=Revit_API_Revit_API_Developers_Guide_html">Revit API Developers Guide</a></h2></article><div class="tag_share"><div class="post-meta__tag-list"><a class="post-meta__tags" href="/tags/Revit/">Revit</a></div><div class="post-share"><div class="social-share" data-image="/images/4stars.png" data-sites="facebook,twitter,wechat,weibo,qq"></div><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/butterfly-extsrc/sharejs/dist/css/share.min.css" media="print" onload="this.media='all'"><script src="https://cdn.jsdelivr.net/npm/butterfly-extsrc/sharejs/dist/js/social-share.min.js" defer></script></div></div><nav class="pagination-post" id="pagination"><a class="pagination-related" href="/2024/12/15/Revit%E4%BA%8C%E5%BC%80%E6%8C%87%E5%8D%97/19%E8%8D%89%E5%9B%BE/" title="19草图"><div class="cover" style="background: var(--default-bg-color)"></div><div class="info"><div class="info-1"><div class="info-item-1">上一篇</div><div class="info-item-2">19草图</div></div><div class="info-2"><div class="info-item-1">草图要在Revit中创建图元或编辑其轮廓，必须先创建草图对象。需要绘制草图的图元示例包括：  Roofs 屋顶 Floors 地板 Stairs 楼梯 Railings 栏杆  还需要草图来定义其他类型的几何图形，例如：  Extrusions 拉伸 Openings 开口 Regions 区域  在Revit Platform API中，草图函数由二维和三维草图类表示，如下所示：  二维Sketch： SketchPlane 草图平面 Sketch 草图 ModelCurve 模型线 and more   三维Sketch： GenericForm 通用形状 Path3D 3D路径    除了草图元素外，本章还介绍了ModelCurve。有关元素分类的详细信息，请参阅元素部分中的元素分类。  本节中的页面  2DSketch类 3DSketch 模型线  2D...</div></div></div></a><a class="pagination-related" href="/2024/12/14/Revit%E4%BA%8C%E5%BC%80%E6%8C%87%E5%8D%97/18%E5%87%A0%E4%BD%95/" title="18几何"><div class="cover" style="background: var(--default-bg-color)"></div><div class="info text-right"><div class="info-1"><div class="info-item-1">下一篇</div><div class="info-item-2">18几何</div></div><div class="info-2"><div class="info-item-1">几何Autodesk.Revit.DB 命名空间包含许多与几何和图形相关类型相关的类，用于描述 API 中的图形表示。几何相关的类包括：  GeometryObject class - 包含从几何对象类派生的类。 Geometry Helper Classes - 包含从 APIObject 类派生出的类和值类型 Geometry Utility Classes - 包含创建非元素几何体和查找实体交点的类 Collection Classes - 包括从 IEnumerable 或 IEnumerator...</div></div></div></a></nav><div class="relatedPosts"><div class="headline"><i class="fas fa-thumbs-up fa-fw"></i><span>相关推荐</span></div><div class="relatedPosts-list"><a class="pagination-related" href="/2024/12/20/RevitApi%E5%90%88%E9%9B%86/Autodesk.%20Revit.DB%20ElementTransformUtils/" title="Autodesk.Revit.DB ElementTransformUtils"><div class="cover" style="background: var(--default-bg-color)"></div><div class="info text-center"><div class="info-1"><div class="info-item-1"><i class="far fa-calendar-alt fa-fw"></i> 2024-12-20</div><div class="info-item-2">Autodesk.Revit.DB ElementTransformUtils</div></div><div class="info-2"><div class="info-item-1">Autodesk. Revit.DB ElementTransformUtils允许元素转换的实用程序集合（例如移动，旋转，镜像和复制）。 语法1public static class ElementTransformUtils    继承层次结构 System Object Autodesk.Revit.DB ElementTransformUtils   方法CanMirrorElement确定是否可以镜像元素。 CanMirrorElements确定是否可以镜像元素。 CopyElement复制元素并将副本放置在给定转换指示的位置。 CopyElements(Document, ICollection ElementId , XYZ)复制一组元素，并将副本放置在给定指示的位置。 CopyElements(Document, ICollection ElementId , Document, Transform, CopyPasteOptions)将一组元素从源文档复制到目标文档。 CopyElements(View, ICollection ElementId ,...</div></div></div></a><a class="pagination-related" href="/2024/11/18/RevitApi%E5%90%88%E9%9B%86/Autodesk.Revit.DB%20CurveArray/" title="Autodesk.Revit.DB CurveArray"><div class="cover" style="background: var(--default-bg-color)"></div><div class="info text-center"><div class="info-1"><div class="info-item-1"><i class="far fa-calendar-alt fa-fw"></i> 2024-11-18</div><div class="info-item-2">Autodesk.Revit.DB CurveArray</div></div><div class="info-2"><div class="info-item-1">Autodesk.Revit.DB CurveArray可以包含曲线的数组。 语法1public class CurveArray : APIObject, IEnumerable  继承层次结构System Object ​	Autodesk.Revit.DB APIObject ​		Autodesk.Revit.DB CurveArray 另见CurveArray Members Autodesk.Revit.DB Namespace 构造函数CurveArray创建CurveArray类的新实例 方法Append将曲线添加到数组的末尾。 Clear从数组中删除每条曲线，使其为空。 ForwardIterator将一个向前移动的迭代器添加到数组中。 GetEnumerator将一个向前移动的迭代器添加到数组中。 Insert将指定的曲线插入数组。 ReverseIterator返回一个向后移动的迭代器到数组。 属性IsEmpty测试数组是否为空。 Item获取或设置数组中指定索引处的曲线。 Size返回数组中的曲线数。 注：翻译自Revit Api docs 2018</div></div></div></a><a class="pagination-related" href="/2024/10/30/RevitApi%E5%90%88%E9%9B%86/Autodesk.Revit.DB%20Document/" title="Autodesk.Revit.DB Document"><div class="cover" style="background: var(--default-bg-color)"></div><div class="info text-center"><div class="info-1"><div class="info-item-1"><i class="far fa-calendar-alt fa-fw"></i> 2024-10-30</div><div class="info-item-2">Autodesk.Revit.DB Document</div></div><div class="info-2"><div class="info-item-1">Autodesk.Revit.DB Document表示打开的 Autodesk Revit 项目的对象。 语法1public class Document : IDisposable    附注Document 对象表示 Autodesk Revit 项目。Revit 可以打开多个项目，并打开这些项目的多个视图。活动视图或最顶层视图将是活动项目，因此是可从 Application 对象获得的活动文档。 继承层次结构 System Object Autodesk.Revit.DB Document Autodesk.Revit.DB.Macros DocumentEntryPoint  方法AcquireCoordinates 不知道是啥，API没给描述  AutoJoinElements 强制 Revit...</div></div></div></a><a class="pagination-related" href="/2024/12/10/RevitApi%E5%90%88%E9%9B%86/Autodesk.Revit.DB%20Opening/" title="Autodesk.Revit.DB Opening"><div class="cover" style="background: var(--default-bg-color)"></div><div class="info text-center"><div class="info-1"><div class="info-item-1"><i class="far fa-calendar-alt fa-fw"></i> 2024-12-10</div><div class="info-item-2">Autodesk.Revit.DB Opening</div></div><div class="info-2"><div class="info-item-1">Autodesk.Revit.DB OpeningAutodesk Revit项目或族文档中的洞口。 语法1public class Opening : Element  附注该对象表示各种不同类型的洞口：  墙中由修订项目中的两个边界点创建的矩形洞口。 由应用于屋顶、楼板、天花板、梁、支撑或柱的一组曲线创建的洞口。 一个垂直的竖井开口延伸到一个或多个水平。 在族文档中的墙或天花板上创建的简单洞口。  根据打开的类型，此类的某些属性将不可用。 这个对象派生自Element基对象，并且支持该对象的所有方法，例如检索该对象的参数的能力。此对象还支持访问结构分析模型，但此功能仅适用于Autodesk Revit Structure。 示例123456789101112131415161718192021222324252627282930313233343536373839404142434445464748495051### private void Getinfo_Opening(Opening opening)&#123;    string message =...</div></div></div></a><a class="pagination-related" href="/2024/12/10/RevitApi%E5%90%88%E9%9B%86/Autodesk.Revit.DB%20ReferenceIntersector/" title="Autodesk.Revit.DB ReferenceIntersector"><div class="cover" style="background: var(--default-bg-color)"></div><div class="info text-center"><div class="info-1"><div class="info-item-1"><i class="far fa-calendar-alt fa-fw"></i> 2024-12-10</div><div class="info-item-2">Autodesk.Revit.DB ReferenceIntersector</div></div><div class="info-2"><div class="info-item-1">Autodesk.Revit.DB ReferenceIntersector用于查找和返回与从原点和方向创建的射线相交的元素的类。 语法1public class ReferenceIntersector : IDisposable    附注可以构造此类的实例，以返回与由原点和方向创建的射线，或者基于过滤和标志返回元素的子集。 调用者可以选择使用ElementFilter过滤结果，或者通过应用特定的可接受的元素。 调用方还可以指定要返回的对象的类型， 整个元素、几何体对象或其组合。 在所有情况下，要求调用者提供 用于评估的3D视图;输入视图上的视图和可见性设置将确定 返回特定元素（例如，此工具永远不会返回隐藏元素、 和几何图形位于视图剖面框之外的元素）。 该类配置为可以构建单个实例，并用于对多个不同光线进行多次评估。在同一个 ReferenceIntersector 上的调用之间，评估结果不会被保留。 该类还提供了一个选项，用于返回在Revit链接中遇到的图元结果。 当设置 FindReferencesInRevitLinks 标志...</div></div></div></a><a class="pagination-related" href="/2024/12/20/RevitApi%E5%90%88%E9%9B%86/Autodesk.Revit.DB%20Transform/" title="Autodesk.Revit.DB Transform"><div class="cover" style="background: var(--default-bg-color)"></div><div class="info text-center"><div class="info-1"><div class="info-item-1"><i class="far fa-calendar-alt fa-fw"></i> 2024-12-20</div><div class="info-item-2">Autodesk.Revit.DB Transform</div></div><div class="info-2"><div class="info-item-1">Autodesk.Revit.DB Transform仿射三维空间的一个变换。 语法public class Transform : APIObject示例12345678910111213141516171819202122### public static XYZ TransformPoint(XYZ point, Transform transform)&#123;    double x = point.X;    double y = point.Y;    double z = point.Z;    //transform basis of the old coordinate system in the new coordinate // system    XYZ b0 = transform.get_Basis(0);    XYZ b1 = transform.get_Basis(1);    XYZ b2 = transform.get_Basis(2);    XYZ origin = transform.Origin;       ...</div></div></div></a></div></div><hr class="custom-hr"/><div id="post-comment"><div class="comment-head"><div class="comment-headline"><i class="fas fa-comments fa-fw"></i><span> 评论</span></div></div><div class="comment-wrap"><div><div id="giscus-wrap"></div></div></div></div></div><div class="aside-content" id="aside-content"><div class="card-widget card-info text-center"><div class="avatar-img"><img src="/images/4stars.png" onerror="this.onerror=null;this.src='/img/friend_404.gif'" alt="avatar"/></div><div class="author-info-name">funtim41@gmail.com</div><div class="author-info-description">实践-认识-再实践-再认识</div><div class="site-data"><a href="/archives/"><div class="headline">文章</div><div class="length-num">58</div></a><a href="/tags/"><div class="headline">标签</div><div class="length-num">5</div></a><a href="/categories/"><div class="headline">分类</div><div class="length-num">7</div></a></div><a id="card-info-btn" target="_blank" rel="noopener" href="https://github.com/FunTim41"><i class="fab fa-github"></i><span>Follow Me</span></a><div class="card-info-social-icons"><a class="social-icon" href="https://github.com/FunTim41" target="_blank" title="Github"><i class="fab fa-github" style="color: #FFFFFF;"></i></a></div></div><div class="card-widget card-announcement"><div class="item-headline"><i class="fas fa-bullhorn fa-shake"></i><span>公告</span></div><div class="announcement_content">This is my Blog</div></div><div class="sticky_layout"><div class="card-widget" id="card-toc"><div class="item-headline"><i class="fas fa-stream"></i><span>目录</span><span class="toc-percentage"></span></div><div class="toc-content"><ol class="toc"><li class="toc-item toc-level-1"><a class="toc-link" href="#%E6%9D%90%E8%B4%A8"><span class="toc-number">1.</span> <span class="toc-text">材质</span></a><ol class="toc-child"><li class="toc-item toc-level-2"><a class="toc-link" href="#%E4%B8%80%E8%88%AC%E6%9D%90%E8%B4%A8%E4%BF%A1%E6%81%AF"><span class="toc-number">1.1.</span> <span class="toc-text">一般材质信息</span></a></li><li class="toc-item toc-level-2"><a class="toc-link" href="#%E6%9D%90%E8%B4%A8%E7%AE%A1%E7%90%86"><span class="toc-number">1.2.</span> <span class="toc-text">材质管理</span></a></li><li class="toc-item toc-level-2"><a class="toc-link" href="#%E5%85%83%E7%B4%A0%E6%9D%90%E8%B4%A8"><span class="toc-number">1.3.</span> <span class="toc-text">元素材质</span></a></li><li class="toc-item toc-level-2"><a class="toc-link" href="#%E6%9D%90%E8%B4%A8%E6%95%B0%E9%87%8F"><span class="toc-number">1.4.</span> <span class="toc-text">材质数量</span></a></li><li class="toc-item toc-level-2"><a class="toc-link" href="#%E7%BB%98%E5%88%B6%E5%85%83%E7%B4%A0%E7%9A%84%E8%A1%A8%E9%9D%A2"><span class="toc-number">1.5.</span> <span class="toc-text">绘制元素的表面</span></a></li><li class="toc-item toc-level-2"><a class="toc-link" href="#%E6%B3%A8%EF%BC%9A%E7%BF%BB%E8%AF%91%E8%87%AARevit-API-Developers-Guide"><span class="toc-number">1.6.</span> <span class="toc-text">注：翻译自Revit API Developers Guide</span></a></li></ol></li></ol></div></div><div class="card-widget card-recent-post"><div class="item-headline"><i class="fas fa-history"></i><span>最新文章</span></div><div class="aside-list"><div class="aside-list-item no-cover"><div class="content"><a class="title" href="/2025/01/16/Revit%E4%BA%8C%E5%BC%80%E7%A4%BA%E4%BE%8B/Revit%E4%B8%8EExcel%E4%BA%A4%E4%BA%92/" title="Revit与Excel交互">Revit与Excel交互</a><time datetime="2025-01-16T08:43:45.327Z" title="更新于 2025-01-16 16:43:45">2025-01-16</time></div></div><div class="aside-list-item no-cover"><div class="content"><a class="title" href="/2025/01/14/ObjectARX%EF%BC%9AManaged.NET%E5%BC%80%E5%8F%91%E4%BA%BA%E5%91%98%E6%8C%87%E5%8D%97/03%E5%88%9B%E5%BB%BA%E5%92%8C%E7%BC%96%E8%BE%91AutoCAD%E5%9B%BE%E5%85%83%EF%BC%88.NET%EF%BC%89/" title="03创建和编辑AutoCAD图元（.NET）">03创建和编辑AutoCAD图元（.NET）</a><time datetime="2025-01-14T04:28:05.785Z" title="更新于 2025-01-14 12:28:05">2025-01-14</time></div></div><div class="aside-list-item no-cover"><div class="content"><a class="title" href="/2025/01/13/ObjectARX%EF%BC%9AManaged.NET%E5%BC%80%E5%8F%91%E4%BA%BA%E5%91%98%E6%8C%87%E5%8D%97/02%E6%8E%A7%E5%88%B6AutoCAD%E7%8E%AF%E5%A2%83%EF%BC%88.NET%EF%BC%89/" title="02控制AutoCAD环境（.NET）">02控制AutoCAD环境（.NET）</a><time datetime="2025-01-14T02:31:41.869Z" title="更新于 2025-01-14 10:31:41">2025-01-14</time></div></div><div class="aside-list-item no-cover"><div class="content"><a class="title" href="/2025/01/12/ObjectARX%EF%BC%9AManaged.NET%E5%BC%80%E5%8F%91%E4%BA%BA%E5%91%98%E6%8C%87%E5%8D%97/01AutoCAD.NET%20API%EF%BC%88.NET%EF%BC%89%E7%9A%84%E5%9F%BA%E7%A1%80%E7%9F%A5%E8%AF%86/" title="01AutoCAD .NET API（.NET）的基础知识">01AutoCAD .NET API（.NET）的基础知识</a><time datetime="2025-01-14T02:31:29.466Z" title="更新于 2025-01-14 10:31:29">2025-01-14</time></div></div><div class="aside-list-item no-cover"><div class="content"><a class="title" href="/2024/12/19/RevitApi%E5%90%88%E9%9B%86/Autodesk.Revit.UI.Selection%20Namespace/" title="Autodesk.Revit.UI.Selection">Autodesk.Revit.UI.Selection</a><time datetime="2025-01-13T14:24:17.222Z" title="更新于 2025-01-13 22:24:17">2025-01-13</time></div></div></div></div></div></div></main><footer id="footer" style="background-image: url(/images/topback.jpg);"><div id="footer-wrap"><div class="copyright">&copy;2024 - 2025 By funtim41@gmail.com</div><div class="framework-info"><span>框架 </span><a target="_blank" rel="noopener" href="https://hexo.io">Hexo</a><span class="footer-separator">|</span><span>主题 </span><a target="_blank" rel="noopener" href="https://github.com/jerryc127/hexo-theme-butterfly">Butterfly</a></div><div class="footer_custom_text">学而不思则罔，思而不学则殆。</div></div></footer></div><div id="rightside"><div id="rightside-config-hide"><button id="readmode" type="button" title="阅读模式"><i class="fas fa-book-open"></i></button><button id="darkmode" type="button" title="日间和夜间模式切换"><i class="fas fa-adjust"></i></button><button id="hide-aside-btn" type="button" title="单栏和双栏切换"><i class="fas fa-arrows-alt-h"></i></button></div><div id="rightside-config-show"><button id="rightside-config" type="button" title="设置"><i class="fas fa-cog fa-spin"></i></button><button class="close" id="mobile-toc-button" type="button" title="目录"><i class="fas fa-list-ul"></i></button><a id="to_comment" href="#post-comment" title="前往评论"><i class="fas fa-comments"></i></a><button id="go-up" type="button" title="回到顶部"><span class="scroll-percent"></span><i class="fas fa-arrow-up"></i></button></div></div><div><script src="/js/utils.js"></script><script src="/js/main.js"></script><script src="https://cdn.jsdelivr.net/npm/node-snackbar/dist/snackbar.min.js"></script><script>(() => {
  const panguFn = () => {
    if (typeof pangu === 'object') pangu.autoSpacingPage()
    else {
      btf.getScript('https://cdn.jsdelivr.net/npm/pangu/dist/browser/pangu.min.js')
        .then(() => {
          pangu.autoSpacingPage()
        })
    }
  }

  const panguInit = () => {
    if (false){
      GLOBAL_CONFIG_SITE.isPost && panguFn()
    } else {
      panguFn()
    }
  }

  btf.addGlobalFn('pjaxComplete', panguInit, 'pangu')
  document.addEventListener('DOMContentLoaded', panguInit)
})()</script><div class="js-pjax"><script>(() => {
  const isShuoshuo = GLOBAL_CONFIG_SITE.isShuoshuo
  const option = null

  const getGiscusTheme = theme => theme === 'dark' ? 'dark' : 'light'

  const createScriptElement = config => {
    const ele = document.createElement('script')
    Object.entries(config).forEach(([key, value]) => {
      ele.setAttribute(key, value)
    })
    return ele
  }

  const loadGiscus = (el = document, key) => {
    const mappingConfig = isShuoshuo
      ? { 'data-mapping': 'specific', 'data-term': key }
      : { 'data-mapping': (option && option['data-mapping']) || 'pathname' }

    const giscusConfig = {
      src: 'https://giscus.app/client.js',
      'data-repo': 'FunTim41/funtim41.github.io',
      'data-repo-id': 'R_kgDONjG8ww',
      'data-category-id': 'DIC_kwDONjG8w84Cllg2',
      'data-theme': getGiscusTheme(document.documentElement.getAttribute('data-theme')),
      'data-reactions-enabled': '1',
      crossorigin: 'anonymous',
      async: true,
      ...option,
      ...mappingConfig
    }

    const scriptElement = createScriptElement(giscusConfig)

    el.querySelector('#giscus-wrap').appendChild(scriptElement)

    if (isShuoshuo) {
      window.shuoshuoComment.destroyGiscus = () => {
        if (el.children.length) {
          el.innerHTML = ''
          el.classList.add('no-comment')
        }
      }
    }
  }

  const changeGiscusTheme = theme => {
    const iframe = document.querySelector('#giscus-wrap iframe')
    if (iframe) {
      const message = {
        giscus: {
          setConfig: {
            theme: getGiscusTheme(theme)
          }
        }
      }
      iframe.contentWindow.postMessage(message, 'https://giscus.app')
    }
  }

  btf.addGlobalFn('themeChange', changeGiscusTheme, 'giscus')

  if (isShuoshuo) {
    'Giscus' === 'Giscus'
      ? window.shuoshuoComment = { loadComment: loadGiscus }
      : window.loadOtherComment = loadGiscus
    return
  }

  if ('Giscus' === 'Giscus' || !false) {
    if (false) btf.loadComment(document.getElementById('giscus-wrap'), loadGiscus)
    else loadGiscus()
  } else {
    window.loadOtherComment = loadGiscus
  }
})()</script></div><script defer="defer" id="fluttering_ribbon" mobile="false" src="https://cdn.jsdelivr.net/npm/butterfly-extsrc/dist/canvas-fluttering-ribbon.min.js"></script><script async data-pjax src="//busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js"></script><div id="local-search"><div class="search-dialog"><nav class="search-nav"><span class="search-dialog-title">搜索</span><span id="loading-status"></span><button class="search-close-button"><i class="fas fa-times"></i></button></nav><div class="text-center" id="loading-database"><i class="fas fa-spinner fa-pulse"></i><span>  数据加载中</span></div><div class="search-wrap"><div id="local-search-input"><div class="local-search-box"><input class="local-search-box--input" placeholder="搜索文章" type="text"/></div></div><hr/><div id="local-search-results"></div><div id="local-search-stats-wrap"></div></div></div><div id="search-mask"></div><script src="/js/search/local-search.js"></script></div></div></body></html>