<!DOCTYPE html><html lang="zh-CN" data-theme="light"><head><meta charset="UTF-8"><meta http-equiv="X-UA-Compatible" content="IE=edge"><meta name="viewport" content="width=device-width, initial-scale=1.0,viewport-fit=cover"><title>13族实例 | funtim的博客</title><meta name="author" content="funtim41@gmail.com"><meta name="copyright" content="funtim41@gmail.com"><meta name="format-detection" content="telephone=no"><meta name="theme-color" content="#ffffff"><meta name="description" content="族实例在本节中，您将了解以下内容：  族与族实例的关系 族和族实例特征 如何载入或创建族和族实例特征 族实例与族符号的关系   本节中的页面  Identifying Elements 识别元素 FamilyInstances 族实例 Code Samples 代码示例 FamilySymbol 族符号 Family 族  识别元素在Revit中，判断元素是否为FamilyInstance的最简单">
<meta property="og:type" content="article">
<meta property="og:title" content="13族实例">
<meta property="og:url" content="https://funtim41.github.io/2024/11/23/Revit%E4%BA%8C%E5%BC%80%E6%8C%87%E5%8D%97/13%E6%97%8F%E5%AE%9E%E4%BE%8B/">
<meta property="og:site_name" content="funtim的博客">
<meta property="og:description" content="族实例在本节中，您将了解以下内容：  族与族实例的关系 族和族实例特征 如何载入或创建族和族实例特征 族实例与族符号的关系   本节中的页面  Identifying Elements 识别元素 FamilyInstances 族实例 Code Samples 代码示例 FamilySymbol 族符号 Family 族  识别元素在Revit中，判断元素是否为FamilyInstance的最简单">
<meta property="og:locale" content="zh_CN">
<meta property="og:image" content="https://funtim41.github.io/images/4stars.png">
<meta property="article:published_time" content="2024-11-23T02:28:46.000Z">
<meta property="article:modified_time" content="2025-01-13T14:20:04.185Z">
<meta property="article:author" content="funtim41@gmail.com">
<meta property="article:tag" content="Revit">
<meta name="twitter:card" content="summary">
<meta name="twitter:image" content="https://funtim41.github.io/images/4stars.png"><link rel="shortcut icon" href="/images/OIP.jfif"><link rel="canonical" href="https://funtim41.github.io/2024/11/23/Revit%E4%BA%8C%E5%BC%80%E6%8C%87%E5%8D%97/13%E6%97%8F%E5%AE%9E%E4%BE%8B/"><link rel="preconnect" href="//cdn.jsdelivr.net"/><link rel="stylesheet" href="/css/index.css"><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free/css/all.min.css"><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/node-snackbar/dist/snackbar.min.css" media="print" onload="this.media='all'"><script>
    (() => {
      
    const saveToLocal = {
      set: (key, value, ttl) => {
        if (!ttl) return
        const expiry = Date.now() + ttl * 86400000
        localStorage.setItem(key, JSON.stringify({ value, expiry }))
      },
      get: key => {
        const itemStr = localStorage.getItem(key)
        if (!itemStr) return undefined
        const { value, expiry } = JSON.parse(itemStr)
        if (Date.now() > expiry) {
          localStorage.removeItem(key)
          return undefined
        }
        return value
      }
    }

    window.btf = {
      saveToLocal,
      getScript: (url, attr = {}) => new Promise((resolve, reject) => {
        const script = document.createElement('script')
        script.src = url
        script.async = true
        Object.entries(attr).forEach(([key, val]) => script.setAttribute(key, val))
        script.onload = script.onreadystatechange = () => {
          if (!script.readyState || /loaded|complete/.test(script.readyState)) resolve()
        }
        script.onerror = reject
        document.head.appendChild(script)
      }),
      getCSS: (url, id) => new Promise((resolve, reject) => {
        const link = document.createElement('link')
        link.rel = 'stylesheet'
        link.href = url
        if (id) link.id = id
        link.onload = link.onreadystatechange = () => {
          if (!link.readyState || /loaded|complete/.test(link.readyState)) resolve()
        }
        link.onerror = reject
        document.head.appendChild(link)
      }),
      addGlobalFn: (key, fn, name = false, parent = window) => {
        if (!false && key.startsWith('pjax')) return
        const globalFn = parent.globalFn || {}
        globalFn[key] = globalFn[key] || {}
        globalFn[key][name || Object.keys(globalFn[key]).length] = fn
        parent.globalFn = globalFn
      }
    }
  
      
      const activateDarkMode = () => {
        document.documentElement.setAttribute('data-theme', 'dark')
        if (document.querySelector('meta[name="theme-color"]') !== null) {
          document.querySelector('meta[name="theme-color"]').setAttribute('content', '#0d0d0d')
        }
      }
      const activateLightMode = () => {
        document.documentElement.setAttribute('data-theme', 'light')
        if (document.querySelector('meta[name="theme-color"]') !== null) {
          document.querySelector('meta[name="theme-color"]').setAttribute('content', '#ffffff')
        }
      }

      btf.activateDarkMode = activateDarkMode
      btf.activateLightMode = activateLightMode

      const theme = saveToLocal.get('theme')
    
          theme === 'dark' ? activateDarkMode() : theme === 'light' ? activateLightMode() : null
        
      
      const asideStatus = saveToLocal.get('aside-status')
      if (asideStatus !== undefined) {
        document.documentElement.classList.toggle('hide-aside', asideStatus === 'hide')
      }
    
      
    const detectApple = () => {
      if (/iPad|iPhone|iPod|Macintosh/.test(navigator.userAgent)) {
        document.documentElement.classList.add('apple')
      }
    }
    detectApple()
  
    })()
  </script><script>const GLOBAL_CONFIG = {
  root: '/',
  algolia: undefined,
  localSearch: {"path":"/search.xml","preload":false,"top_n_per_article":1,"unescape":false,"languages":{"hits_empty":"未找到符合您查询的内容：${query}","hits_stats":"共找到 ${hits} 篇文章"}},
  translate: undefined,
  highlight: {"plugin":"highlight.js","highlightCopy":true,"highlightLang":true,"highlightHeightLimit":false,"highlightFullpage":false,"highlightMacStyle":false},
  copy: {
    success: '复制成功',
    error: '复制失败',
    noSupport: '浏览器不支持'
  },
  relativeDate: {
    homepage: false,
    post: false
  },
  runtime: '',
  dateSuffix: {
    just: '刚刚',
    min: '分钟前',
    hour: '小时前',
    day: '天前',
    month: '个月前'
  },
  copyright: {"limitCount":150,"languages":{"author":"作者: funtim41@gmail.com","link":"链接: ","source":"来源: funtim的博客","info":"著作权归作者所有。商业转载请联系作者获得授权，非商业转载请注明出处。"}},
  lightbox: 'null',
  Snackbar: {"chs_to_cht":"已切换为繁体中文","cht_to_chs":"已切换为简体中文","day_to_night":"已切换为深色模式","night_to_day":"已切换为浅色模式","bgLight":"#49b1f5","bgDark":"#1f1f1f","position":"bottom-left"},
  infinitegrid: {
    js: 'https://cdn.jsdelivr.net/npm/@egjs/infinitegrid/dist/infinitegrid.min.js',
    buttonText: '加载更多'
  },
  isPhotoFigcaption: false,
  islazyload: false,
  isAnchor: true,
  percent: {
    toc: true,
    rightside: true,
  },
  autoDarkmode: false
}</script><script id="config-diff">var GLOBAL_CONFIG_SITE = {
  title: '13族实例',
  isPost: true,
  isHome: false,
  isHighlightShrink: false,
  isToc: true,
  isShuoshuo: false
}</script><link rel="stylesheet" href="/css/bar.css"><meta name="generator" content="Hexo 7.3.0"></head><body><div id="web_bg" style="background: Color(#995a82);"></div><div id="sidebar"><div id="menu-mask"></div><div id="sidebar-menus"><div class="avatar-img text-center"><img src="/images/4stars.png" onerror="onerror=null;src='/img/friend_404.gif'" alt="avatar"/></div><div class="site-data text-center"><a href="/archives/"><div class="headline">文章</div><div class="length-num">67</div></a><a href="/tags/"><div class="headline">标签</div><div class="length-num">5</div></a><a href="/categories/"><div class="headline">分类</div><div class="length-num">7</div></a></div><div class="menus_items"><div class="menus_item"><a class="site-page" href="/"><i class="fa-fw fas fa-home"></i><span> Home</span></a></div><div class="menus_item"><a class="site-page" href="/archives/"><i class="fa-fw fas fa-archive"></i><span> Timeline</span></a></div><div class="menus_item"><a class="site-page" href="/tags/"><i class="fa-fw fas fa-tags"></i><span> Tags</span></a></div><div class="menus_item"><a class="site-page" href="/categories/"><i class="fa-fw fas fa-folder-open"></i><span> Categories</span></a></div><div class="menus_item"><a class="site-page" href="/Links/"><i class="fa-fw fas fa-link"></i><span> Links</span></a></div><div class="menus_item"><a class="site-page" href="/about/"><i class="fa-fw fas fa-heart"></i><span> About</span></a></div></div></div></div><div class="post" id="body-wrap"><header class="post-bg fixed" id="page-header" style="background-image: url(/images/topback.jpg);"><nav id="nav"><span id="blog-info"><a class="nav-site-title" href="/"><img class="site-icon" src="/images/OIP.jfif" alt="Logo"><span class="site-name">funtim的博客</span></a><a class="nav-page-title" href="/"><span class="site-name">13族实例</span></a></span><div id="menus"><div id="search-button"><span class="site-page social-icon search"><i class="fas fa-search fa-fw"></i><span> 搜索</span></span></div><div class="menus_items"><div class="menus_item"><a class="site-page" href="/"><i class="fa-fw fas fa-home"></i><span> Home</span></a></div><div class="menus_item"><a class="site-page" href="/archives/"><i class="fa-fw fas fa-archive"></i><span> Timeline</span></a></div><div class="menus_item"><a class="site-page" href="/tags/"><i class="fa-fw fas fa-tags"></i><span> Tags</span></a></div><div class="menus_item"><a class="site-page" href="/categories/"><i class="fa-fw fas fa-folder-open"></i><span> Categories</span></a></div><div class="menus_item"><a class="site-page" href="/Links/"><i class="fa-fw fas fa-link"></i><span> Links</span></a></div><div class="menus_item"><a class="site-page" href="/about/"><i class="fa-fw fas fa-heart"></i><span> About</span></a></div></div><div id="toggle-menu"><span class="site-page"><i class="fas fa-bars fa-fw"></i></span></div></div></nav><div id="post-info"><h1 class="post-title">13族实例</h1><div id="post-meta"><div class="meta-firstline"><span class="post-meta-date"><i class="far fa-calendar-alt fa-fw post-meta-icon"></i><span class="post-meta-label">发表于</span><time class="post-meta-date-created" datetime="2024-11-23T02:28:46.000Z" title="发表于 2024-11-23 10:28:46">2024-11-23</time><span class="post-meta-separator">|</span><i class="fas fa-history fa-fw post-meta-icon"></i><span class="post-meta-label">更新于</span><time class="post-meta-date-updated" datetime="2025-01-13T14:20:04.185Z" title="更新于 2025-01-13 22:20:04">2025-01-13</time></span><span class="post-meta-categories"><span class="post-meta-separator">|</span><i class="fas fa-inbox fa-fw post-meta-icon"></i><a class="post-meta-categories" href="/categories/Revit%E4%BA%8C%E6%AC%A1%E5%BC%80%E5%8F%91%E4%BA%BA%E5%91%98%E6%8C%87%E5%8D%97/">Revit二次开发人员指南</a></span></div><div class="meta-secondline"><span class="post-meta-separator">|</span><span class="post-meta-pv-cv" id="" data-flag-title=""><i class="far fa-eye fa-fw post-meta-icon"></i><span class="post-meta-label">浏览量:</span><span id="busuanzi_value_page_pv"><i class="fa-solid fa-spinner fa-spin"></i></span></span></div></div></div></header><main class="layout" id="content-inner"><div id="post"><article class="container post-content" id="article-container"><h1 id="族实例"><a href="#族实例" class="headerlink" title="族实例"></a><a target="_blank" rel="noopener" href="https://help.autodesk.com/view/RVT/2018/ENU/?guid=Revit_API_Revit_API_Developers_Guide_Revit_Geometric_Elements_Family_Instances_html">族实例</a></h1><p>在本节中，您将了解以下内容：</p>
<ul>
<li>族与族实例的关系</li>
<li>族和族实例特征</li>
<li>如何载入或创建族和族实例特征</li>
<li>族实例与族符号的关系</li>
</ul>
<p> 本节中的页面</p>
<ul>
<li>Identifying Elements 识别元素</li>
<li>FamilyInstances 族实例</li>
<li>Code Samples 代码示例</li>
<li>FamilySymbol 族符号</li>
<li>Family 族</li>
</ul>
<h2 id="识别元素"><a href="#识别元素" class="headerlink" title="识别元素"></a>识别元素</h2><p>在Revit中，判断元素是否为FamilyInstance的最简单方法是使用属性对话框。</p>
<ul>
<li>如果族名称以“系统族”开头，并且禁用了“载入”按钮，则该族属于“系统族”。</li>
</ul>
<p><img src="https://help.autodesk.com/cloudhelp/2018/ENU/Revit-API/images/GUID-96BC987E-5C38-45EF-9621-2D6EF89989B1-low.png"></p>
<p>图41：系统族</p>
<ul>
<li>属于构件族的常规FamilyInstance不以System Family开头。</li>
<li>例如，在下图中，桌子家具的族名为Desk。此外，还启用了“加载”按钮。</li>
</ul>
<p><img src="https://help.autodesk.com/cloudhelp/2018/ENU/Revit-API/images/GUID-67F1CF63-64EF-40E4-BF92-284873CDDB31-low.png"></p>
<p>图42：组件族</p>
<p>有一些例外，例如：体量和内建成员。“族”和“类型”字段为空。</p>
<p><img src="https://help.autodesk.com/cloudhelp/2018/ENU/Revit-API/images/GUID-A2B06CEE-7E4A-494B-8DE8-7131068F182B-low.png"></p>
<p>图43：体量或内建构件示例</p>
<p>Revit Platform API中的族由三个对象表示：</p>
<ul>
<li>Family </li>
<li>FamilySymbol</li>
<li>FamilyInstance</li>
</ul>
<p>每件对象在族结构中都起着重要的作用。</p>
<p>“族”对象表示整个族，例如单平面门。例如，“单面齐平门族”对应于“单面齐平.rfa”文件。Family对象包含多个FamilySymbols，用于获取所有族符号，以便于将实例从一个符号切换到另一个符号。</p>
<p>FamilySymbol对象表示与Revit UI中的“类型”（例如34”×80”）相对应的一组特定族设置。</p>
<p>FamilyInstance对象表示Revit项目中的实际Type（FamilySymbol）实例。例如，在下图中，FamilyInstance是项目中的一扇门。</p>
<ul>
<li>每个FamilyInstance都有一个FamilySymbol。门是一个34”×80”的实例。</li>
<li>每个FamilySymbol都属于一个Family。34”×80”符号属于单齐平系列。</li>
<li>每个族都包含一个或多个族符号。单齐平系列包含34”×80”符号、34”×84”符号、36”×84”等。</li>
</ul>
<p>注意：虽然大多数组件元素都是通过API类FamilySymbol和FamilyInstance公开的，但也有一些是用特定的API类包装的。例如，AnnotationSymbolType包装FamilySymbol，AnnotationSymbol包装FamilyInstance。</p>
<h2 id="族实例-1"><a href="#族实例-1" class="headerlink" title="族实例"></a>族实例</h2><p>FamilyInstance对象包括梁、支撑、柱、家具、体量等。FamilyInstance对象提供了更详细的属性，以便可以更改项目中的族实例类型和外观。</p>
<h3 id="位置相关属性"><a href="#位置相关属性" class="headerlink" title="位置相关属性"></a>位置相关属性</h3><p>与位置相关的属性显示FamilyInstance对象的物理和几何特征，如方向、旋转和位置。</p>
<h4 id="Orientation-朝向"><a href="#Orientation-朝向" class="headerlink" title="Orientation 朝向"></a>Orientation 朝向</h4><p>对于某些FamilyInstance对象，可以更改面方向或手方向。例如，门可以面向房间或墙壁的外部或内部，并且可以将把手放置在左侧或右侧。下表比较了门、窗和桌子族实例。</p>
<p>表29：比较族实例</p>
<table>
<thead>
<tr>
<th><strong>Boolean Property 布尔属性</strong></th>
<th><strong>Door 门</strong></th>
<th>**Window (Fixed: 36”w × 72”h) **</th>
<th><strong>Desk 书桌</strong></th>
</tr>
</thead>
<tbody><tr>
<td>CanFlipFacing</td>
<td>True</td>
<td>True</td>
<td>False</td>
</tr>
<tr>
<td>CanFlipHand</td>
<td>True</td>
<td>False</td>
<td>False</td>
</tr>
</tbody></table>
<p>如果CanFlipFacing或CanFlipHand为true，则可以分别调用flipFacing（）或flipHand（）方法。这些方法可以分别改变面向方向或手方向。否则，这些方法不执行任何操作并返回False。修改方向时，请记住某些类型的窗可以同时修改手方向和面方向，例如带Trim的3x3平开窗族。门有四种不同的朝向和手方向组合。请参见下图中的组合，下表中列出了相应的布尔值。 </p>
<p><img src="https://help.autodesk.com/cloudhelp/2018/ENU/Revit-API/images/GUID-AC8B1DB7-860B-46D3-A0BD-DBF120980580-low.png"></p>
<p>图44：具有不同面方向和手方向的门</p>
<p>表30：相同类型的不同饰面</p>
<table>
<thead>
<tr>
<th><strong>Boolean Property 布尔属性</strong></th>
<th>**Door 1 **</th>
<th>**Door 2 **</th>
<th>**Door 3 **</th>
<th>**Door 4 **</th>
</tr>
</thead>
<tbody><tr>
<td>FacingFlipped</td>
<td>False</td>
<td>True</td>
<td>False</td>
<td>True</td>
</tr>
<tr>
<td>HandFlipped</td>
<td>False</td>
<td>True</td>
<td>True</td>
<td>False</td>
</tr>
</tbody></table>
<h4 id="Orientation-Work-Plane-方位-工作平面"><a href="#Orientation-Work-Plane-方位-工作平面" class="headerlink" title="Orientation - Work Plane 方位-工作平面"></a>Orientation - Work Plane 方位-工作平面</h4><p>也可以更改FamilyInstance的工作平面方向。如果CanFlipWorkPlane为true，则可以设置IsWorkPlaneFlipped属性。尝试为不允许翻转工作平面的FamilyInstance设置此属性将导致异常。</p>
<h4 id="Rotation-Mirrored-旋转-镜像"><a href="#Rotation-Mirrored-旋转-镜像" class="headerlink" title="Rotation - Mirrored 旋转-镜像"></a>Rotation - Mirrored 旋转-镜像</h4><p>镜像属性指示FamilyInstance对象是否已镜像。</p>
<p>表31：门镜像属性</p>
<table>
<thead>
<tr>
<th><strong>Boolean Property 布尔属性</strong></th>
<th>**Door 1 **</th>
<th>**Door 2 **</th>
<th>**Door 3 **</th>
<th>**Door 4 **</th>
</tr>
</thead>
<tbody><tr>
<td>Mirrored</td>
<td>False</td>
<td>False</td>
<td>True</td>
<td>True</td>
</tr>
</tbody></table>
<p>在前面的门示例中，Door 1和Door 2的Mirror属性为False，而Door 3和Door 4的Mirror属性均为True。这是因为在Revit项目中创建门时，默认结果为“门1”或“门2”。要创建类似“门3”或“门4”的门，必须分别翻转“门1”和“门2”的方向。翻转操作类似于镜像变换，这就是为什么“门3”和“门4”镜像属性为True。 有关在Revit中使用Mirror（）方法的详细信息，请参阅“编辑图元”一章。 #### Rotation - CanRotate和rotate（） 族实例布尔CanRotate属性用于测试族实例是否可以旋转180度。这取决于实例所属的族。例如，在下面的图片中，Window 1（Casement 3×3 with Trim：36”×72”）和Door 1（Double-Glass 2：72”×82”）的CanRotate属性为true，而Window 2（Fixed：36“w × 72“h）的CanRotate属性为false。</p>
<p><img src="https://help.autodesk.com/cloudhelp/2018/ENU/Revit-API/images/GUID-8E93FD79-81F8-4B3D-B09F-9C9A4A1A556C-low.png"></p>
<p><strong>图45：旋转后的变化</strong> </p>
<p>如果CanRotate为true，则可以调用族实例rotate（）方法，该方法将族实例翻转180度。否则，该方法不执行任何操作并返回False。上图还显示了执行rotate（）方法后的Window 1和Door 1状态。 回想一下本文档前面的旋转图元部分，可以使用ElementTransformUtils.RotateElement（）和ElementTransformUtils.RotateElements（）将族实例（和其他图元）旋转用户指定的角度。</p>
<p><strong>位置</strong> Location属性确定实例在项目中的物理位置。实例可以具有点位置或线位置。 以下特征适用于位置： </p>
<p><em>点位置是LocationPoint类对象-基础、门或桌子都有点位置</em> </p>
<p>线位置是LocationCurve类对象-梁具有线位置。 * 它们都是Location类的子类。 有关位置的详细信息，请参阅编辑元素。</p>
<p>Host和HostFace Host和HostFace都是FamilyInstance属性。 </p>
<p><strong>Host</strong> FamilyInstance对象有一个返回其宿主元素的Host属性。 某些FamilyInstance对象没有宿主元素，如Tables和其他家具，因此Host属性不返回任何内容，因为没有创建主体元素。但是，其他对象（如门和窗）必须具有宿主图元。在这种情况下，Host属性返回窗或门所在的墙元素。请参见下图。</p>
<p><img src="https://help.autodesk.com/cloudhelp/2018/ENU/Revit-API/images/GUID-837ECA51-19DE-4B19-A304-A5C26F24EBD0-low.png"></p>
<p>图46：以墙为主体的门和窗 </p>
<p><strong>HostFace</strong> HostFace属性获取对族实例的宿主面的参照，或者如果实例放置在工作平面上，则获取对工作平面下面的几何图形面的参照。如果工作平面未参照其他几何图形，或者实例未以面或工作平面为宿主，则此属性将返回空参照。</p>
<p> <strong>子组件和超级组件</strong> FamilyInstance. GetSubmenentIds（）方法返回加载到该族中的族实例的ElementIds。将“Table-Dining Round w Chairs.rfa”的实例放置在项目中时，GetSubmenuentIds（）方法将返回椅子集的ElementIds。 SuperComponent属性返回族实例的父构件。在“Table-Dining Round w Chairs. rfa”中，每个嵌套椅子的族实例超级组件都是“Table-Dining Round w Chairs. rfa”的实例。</p>
<p>代码区域12-1：从FamilyInstance获取子组件和超级组件</p>
<figure class="highlight c#"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="keyword">public</span> <span class="keyword">void</span> <span class="title">GetSubAndSuperComponents</span>(<span class="params">FamilyInstance familyInstance</span>)</span></span><br><span class="line">&#123;</span><br><span class="line">    ICollection subElemSet = familyInstance.GetSubComponentIds();</span><br><span class="line">    <span class="keyword">if</span> (subElemSet != <span class="literal">null</span>)</span><br><span class="line">    &#123;</span><br><span class="line">        <span class="built_in">string</span> subElems = <span class="string">&quot;&quot;</span>;</span><br><span class="line">        <span class="keyword">foreach</span> (Autodesk.Revit.DB.ElementId ee <span class="keyword">in</span> subElemSet)</span><br><span class="line">        &#123;</span><br><span class="line">            FamilyInstance f = familyInstance.Document.GetElement(ee) <span class="keyword">as</span> FamilyInstance;</span><br><span class="line">            subElems = subElems + f.Name + <span class="string">&quot;\n&quot;</span>;</span><br><span class="line">        &#125;</span><br><span class="line">        TaskDialog.Show(<span class="string">&quot;Revit&quot;</span>,<span class="string">&quot;Subcomponent count = &quot;</span> + subElemSet.Count + <span class="string">&quot;\n&quot;</span> + subElems);</span><br><span class="line">    &#125;</span><br><span class="line">    FamilyInstance super = familyInstance.SuperComponent <span class="keyword">as</span> FamilyInstance;</span><br><span class="line">    <span class="keyword">if</span> (super != <span class="literal">null</span>)</span><br><span class="line">    &#123;</span><br><span class="line">        TaskDialog.Show(<span class="string">&quot;Revit&quot;</span>,<span class="string">&quot;SUPER component: &quot;</span> + super.Name);</span><br><span class="line">    &#125;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<h3 id="几何"><a href="#几何" class="headerlink" title="几何"></a>几何</h3><p>有时，FamilyInstance对象的几何图形会通过连接、剪切、顶盖、延伸或其他在Revit中进行的后期处理进行修改。FamilyInstance.HasModifiedGeometry（）方法标识此FamilyInstance的几何图形是否已从自动生成的默认值修改。GetOriginalGeometry（）方法将返回实例的原始几何体，该几何体在可能发生任何修改之前。若要获取实例的当前几何体，请使用从Element类继承的Geometry属性。</p>
<h3 id="空间元素计算点"><a href="#空间元素计算点" class="headerlink" title="空间元素计算点"></a>空间元素计算点</h3><p>FamilyInstance具有多个成员，用于直接从族实例中阅读有关空间计算点的信息。HasSpatialElementCalculationPoint属性标识此实例是否有一个SpatialElementCalculationPoint用作Revit的搜索点，以标识实例是否位于房间或空间内。如果为true，GetSpatialElementCalculationPoint（）方法将返回此实例的计算点的位置作为XYZ点。</p>
<p>HasSpatialElementFromToCalculationPoints属性标识此实例是否具有一对SpatialElementCalculationPoints，它们用作Revit的搜索点，以标识实例是否位于最多两个房间或空间之间。对于连接两个房间或空间（如门或窗）的族实例，这些点确定哪个房间或空间被视为“从”，哪个被视为“到”。当此属性为true时，GetSpatialElementFromToCalculationPoints（）方法将此实例的计算点的位置作为XYZ点的列表返回。</p>
<h3 id="其它属性"><a href="#其它属性" class="headerlink" title="其它属性"></a>其它属性</h3><p>本部分中的属性特定于Revit的建筑和结构工程功能。它们在各自的章节中都有详细介绍。</p>
<h4 id="房间信息"><a href="#房间信息" class="headerlink" title="房间信息"></a>房间信息</h4><p>FamilyInstance属性包括Room、FromRoom和ToRoom。有关房间的详细信息，请参阅建筑。</p>
<h4 id="空间信息"><a href="#空间信息" class="headerlink" title="空间信息"></a>空间信息</h4><p>FamilyInstance有一个Space属性，用于标识MEP中保存实例的空间。</p>
<h4 id="结构分析模型"><a href="#结构分析模型" class="headerlink" title="结构分析模型"></a>结构分析模型</h4><p>GetAnalyticalModel（）方法检索族实例结构分析模型。</p>
<p>有关分析模型的详细信息，请参阅结构工程。</p>
<h3 id="创建FamilyInstance对象"><a href="#创建FamilyInstance对象" class="headerlink" title="创建FamilyInstance对象"></a>创建FamilyInstance对象</h3><p>通常，FamilyInstance对象是使用Autodesk.Revit.Creation.Document的12种重载方法之一NewFamilyInstance（）创建的。选择使用哪个重载不仅取决于实例的类别，还取决于放置的其他特征，例如是否应将其作为主体、相对于参照标高放置或直接放置在特定面上。详细信息包含在下面的表32 -使用NewFamilyInstance（）创建实例的选项中。</p>
<p>某些FamilyInstance对象需要创建多个位置。在这些情况下，使用此对象提供的更详细的创建方法更合适（请参见表33 -使用其他方法创建实例的选项）。如果未创建实例，则会引发异常。在调用该方法之前，必须将使用的类型&#x2F;符号加载到项目中。</p>
<p>检查NewFamilyInstance（）的所有重载以确保输入FamilySymbol处于活动状态（FamilySymbol.IsActive）。如果输入FamilySymbol处于非活动状态，则该方法将抛出ArgumentException。文档中未使用的符号可能会被停用，以节省内存和再生时间。当符号处于非活动状态时，其几何图形为空，无法访问。为了访问文档中未激活的符号的几何图形，应首先通过调用FamilySymbol.Activate（）来激活该符号。</p>
<p>表32 -使用NewFamilyInstance（）创建实例的选项</p>
<table>
<thead>
<tr>
<th align="left">Category 类别</th>
<th align="left">NewFamilyInstance() parameters NewFamilyInstance（）参数</th>
<th align="left">Comments注解</th>
</tr>
</thead>
<tbody><tr>
<td align="left">Air Terminals Boundary Conditions Casework Communication Devices Data Devices Electrical Equipment Electrical Fixtures Entourage Fire Alarm Devices Furniture Furniture Systems Generic Models Lighting Devices Lighting Fixtures Mass Mechanical Equipment Nurse Call Devices Parking Planting Plumbing Fixtures Security Devices Site Specialty Equipment Sprinklers Structural Connections Structural Foundations Structural Stiffeners Telephone Devices</td>
<td align="left">XYZ, FamilySymbol, StructuralType</td>
<td align="left">在任意位置创建实例，而不参照标高或宿主元素。</td>
</tr>
<tr>
<td align="left"></td>
<td align="left">XYZ, FamilySymbol, Element, StructuralType</td>
<td align="left">如果要在墙壁、地板或天花板上承载</td>
</tr>
<tr>
<td align="left"></td>
<td align="left">XYZ, FamilySymbol, XYZ, Element, StructuralType</td>
<td align="left">如果要以墙、楼板或天花板为主体，并且需要以非默认方向，</td>
</tr>
<tr>
<td align="left"></td>
<td align="left">XYZ, FamilySymbol, Element, Level, StructuralType</td>
<td align="left">如果要以墙、楼板或天花板为宿主并与参照标高关联，</td>
</tr>
<tr>
<td align="left"></td>
<td align="left">XYZ, FamilySymbol, Level, StructuralType</td>
<td align="left">如果要将其关联到参考标高</td>
</tr>
<tr>
<td align="left"></td>
<td align="left">Face, XYZ, XYZ, FamilySymbol XYZ，</td>
<td align="left">如果它是基于面的并且需要以非默认方向，</td>
</tr>
<tr>
<td align="left"></td>
<td align="left">Reference, XYZ, XYZ, FamilySymbol</td>
<td align="left">如果它是基于面的，并且需要以非默认方向，则接受对面的引用，而不是对Face</td>
</tr>
<tr>
<td align="left"></td>
<td align="left">Face, Line, FamilySymbol</td>
<td align="left">如果它是基于面和线的</td>
</tr>
<tr>
<td align="left"></td>
<td align="left">Reference, Line, FamilySymbol</td>
<td align="left">如果它是基于面和线的，但接受对面的引用，而不是面</td>
</tr>
<tr>
<td align="left">Columns Structural Columns</td>
<td align="left">XYZ, FamilySymbol, Level, StructuralType</td>
<td align="left">创建柱，使其底部位于参照标高上。柱将延伸到模型中的下一个可用标高，或者如果参照标高之上没有合适的标高，则将延伸默认柱高。</td>
</tr>
<tr>
<td align="left">Doors Windows</td>
<td align="left">XYZ, FamilySymbol, Element, StructuralType</td>
<td align="left">门和窗必须以墙为宿主。如果可以使用默认方向放置它们，请使用此方法。</td>
</tr>
<tr>
<td align="left"></td>
<td align="left">XYZ, FamilySymbol, XYZ, Element, StructuralType</td>
<td align="left">如果创建的实例需要以非默认方向</td>
</tr>
<tr>
<td align="left"></td>
<td align="left">XYZ, FamilySymbol, Element, Level, StructuralType</td>
<td align="left">如果实例需要关联到参照标高</td>
</tr>
<tr>
<td align="left">Structural Framing (Beams, Braces)</td>
<td align="left">Curve, FamilySymbol, Level, StructuralType</td>
<td align="left">根据其曲线创建基于标高的支撑或梁。这是创建梁和支撑的推荐方法</td>
</tr>
<tr>
<td align="left"></td>
<td align="left">XYZ, FamilySymbol, StructuralType</td>
<td align="left">在任意位置创建实例</td>
</tr>
<tr>
<td align="left"></td>
<td align="left">XYZ, FamilySymbol, Element, Level, StructuralType</td>
<td align="left">如果它位于图元（地板等）上，并与参考标高相关联</td>
</tr>
<tr>
<td align="left"></td>
<td align="left">XYZ, FamilySymbol, Level, StructuralType</td>
<td align="left">如果它与参考标高相关联，</td>
</tr>
<tr>
<td align="left"></td>
<td align="left">XYZ, FamilySymbol, Element, StructuralType</td>
<td align="left">如果它位于图元（地板等）上</td>
</tr>
<tr>
<td align="left">Detail Component</td>
<td align="left">Line, FamilySymbol, View</td>
<td align="left">仅限于基于二维族线的详图符号</td>
</tr>
<tr>
<td align="left">Generic Annotations</td>
<td align="left">XYZ, FamilySymbol, View</td>
<td align="left">仅显示为二维族符号</td>
</tr>
</tbody></table>
<p>结构实例在创建后长度为零。通过使用LocationCurve.Curve属性设置其曲线（FamilyInstance.Location为LocationCurve）来扩展它。</p>
<p>通过使用Document.NewFamilyList（）一次创建多个族实例，可以简化代码并提高性能。此方法有一个参数，该参数是描述要创建的族实例的FamilyInstanceCreationData对象的列表。</p>
<p>代码区域12-2：批量创建族实例</p>
<figure class="highlight c#"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br><span class="line">23</span><br><span class="line">24</span><br><span class="line">25</span><br><span class="line">26</span><br><span class="line">27</span><br><span class="line">28</span><br><span class="line">29</span><br><span class="line">30</span><br><span class="line">31</span><br><span class="line">32</span><br><span class="line">33</span><br><span class="line">34</span><br><span class="line">35</span><br><span class="line">36</span><br><span class="line">37</span><br><span class="line">38</span><br><span class="line">39</span><br><span class="line">40</span><br><span class="line">41</span><br><span class="line">42</span><br><span class="line">43</span><br><span class="line">44</span><br><span class="line">45</span><br><span class="line">46</span><br><span class="line">47</span><br><span class="line">48</span><br><span class="line">49</span><br><span class="line">50</span><br><span class="line">51</span><br><span class="line">52</span><br><span class="line">53</span><br></pre></td><td class="code"><pre><span class="line"><span class="function">ICollection <span class="title">BatchCreateColumns</span>(<span class="params">Autodesk.Revit.DB.Document document, Level level</span>)</span></span><br><span class="line">&#123;</span><br><span class="line">        List fiCreationDatas = <span class="keyword">new</span> List();</span><br><span class="line"></span><br><span class="line">        ICollection elementSet = <span class="literal">null</span>;</span><br><span class="line"></span><br><span class="line">        <span class="comment">//Try to get a FamilySymbol</span></span><br><span class="line">        FamilySymbol familySymbol = <span class="literal">null</span>;</span><br><span class="line">        FilteredElementCollector collector = <span class="keyword">new</span> FilteredElementCollector(document);</span><br><span class="line">        ICollection collection = collector.OfClass(<span class="keyword">typeof</span>(FamilySymbol)).ToElements();</span><br><span class="line">        <span class="keyword">foreach</span> (Element e <span class="keyword">in</span> collection)</span><br><span class="line">        &#123;</span><br><span class="line">                familySymbol = e <span class="keyword">as</span> FamilySymbol;</span><br><span class="line">                <span class="keyword">if</span> (<span class="literal">null</span> != familySymbol.Category)</span><br><span class="line">                &#123;</span><br><span class="line">                        <span class="keyword">if</span> (<span class="string">&quot;Structural Columns&quot;</span> == familySymbol.Category.Name)</span><br><span class="line">                        &#123;</span><br><span class="line">                                <span class="keyword">break</span>;</span><br><span class="line">                        &#125;</span><br><span class="line">                &#125;</span><br><span class="line">        &#125;</span><br><span class="line"></span><br><span class="line">        <span class="keyword">if</span> (<span class="literal">null</span> != familySymbol)</span><br><span class="line">        &#123;</span><br><span class="line">                <span class="comment">//Create 10 FamilyInstanceCreationData items for batch creation </span></span><br><span class="line">                <span class="keyword">for</span> (<span class="built_in">int</span> i = <span class="number">1</span>; i &lt; <span class="number">11</span>; i++)</span><br><span class="line">                &#123;</span><br><span class="line">                        XYZ location = <span class="keyword">new</span> XYZ(i * <span class="number">10</span>, <span class="number">100</span>, <span class="number">0</span>);</span><br><span class="line">                        FamilyInstanceCreationData fiCreationData = <span class="keyword">new</span> FamilyInstanceCreationData(location, familySymbol, level, </span><br><span class="line">                                        StructuralType.Column);</span><br><span class="line">                        <span class="keyword">if</span> (<span class="literal">null</span> != fiCreationData)</span><br><span class="line">                        &#123;</span><br><span class="line">                                fiCreationDatas.Add(fiCreationData);</span><br><span class="line">                        &#125;</span><br><span class="line">                &#125;</span><br><span class="line"></span><br><span class="line">                <span class="keyword">if</span> (fiCreationDatas.Count &gt; <span class="number">0</span>)</span><br><span class="line">        &#123;</span><br><span class="line">                        <span class="comment">// Create Columns</span></span><br><span class="line">            elementSet = document.Create.NewFamilyInstances2(fiCreationDatas);</span><br><span class="line">        &#125;</span><br><span class="line">                <span class="keyword">else</span></span><br><span class="line">                &#123;</span><br><span class="line">                <span class="keyword">throw</span> <span class="keyword">new</span> Exception(<span class="string">&quot;Batch creation failed.&quot;</span>);</span><br><span class="line">                &#125;</span><br><span class="line">    &#125;</span><br><span class="line">        <span class="keyword">else</span></span><br><span class="line">        &#123;</span><br><span class="line">                <span class="keyword">throw</span> <span class="keyword">new</span> Exception(<span class="string">&quot;No column types found.&quot;</span>);</span><br><span class="line">        &#125;</span><br><span class="line"></span><br><span class="line">        <span class="keyword">return</span> elementSet;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<p>某些族类型的实例最好通过Autodesk.Revit.Creation.Document.NewFamilyInstance（）以外的方法创建。这些列于下表。</p>
<p>表33 -使用其他方法创建实例的选项</p>
<table>
<thead>
<tr>
<th><strong>Category 类别</strong></th>
<th><strong>Creation method 创建方法</strong></th>
<th><strong>Comments</strong></th>
</tr>
</thead>
<tbody><tr>
<td>Air Terminal Tags Area Load Tags Area Tags Casework Tags Ceiling Tags Communication Device Tags Curtain Panel Tags Data Device Tags Detail Item Tags Door Tags Duct Accessory Tags Duct Fitting Tags Duct Tags Electrical Equipment Tags Electrical Fixture Tags Fire Alarm Device Tags Flex Duct Tags Flex Pipe Tags Floor Tags Furniture System Tags Furniture Tags Generic Model Tags Internal Area Load Tags Internal Line Load Tags Internal Point Load Tags Keynote Tags Lighting Device Tags Lighting Fixture Tags Line Load Tags Mass Floor Tags Mass Tags Mechanical Equipment Tags Nurse Call Device Tags Parking Tags Pipe Accessory Tags Pipe Fitting Tags Pipe Tags Planting Tags Plumbing Fixture Tags Point Load Tags Property Line Segment Tags Property Tags Railing Tags Revision Cloud Tags Roof Tags Room Tags Security Device Tags Site Tags Space Tags Specialty Equipment Tags Spinkler Tags Stair Tags Structural Area Reinforcement Tags Structural Beam System Tags Structural Column Tags Structural Connection Tags Structural Foundation Tags Structural Framing Tags Structural Path Reinforcement Tags Structural Rebar Tags Structural Stiffener Tags Structural Truss Tags Telephone Device Tags Wall Tags Window Tags Wire Tag Zone Tags on Tags Structural Foundation Tags Structural Framing Tags Structural Path Reinforcement Tags Structural Rebar Tags Structural Truss Tags Telephone Device Tags Wall Tags Window Tags Wire Tag Zone</td>
<td>IndependentTag.Create(Document, ElementId, Reference, Boolean, TagMode, TagOrientation, XYZ)</td>
<td>TagMode should be TM_ADDBY_CATEGORY and there should be a related tag loaded when try to create a tag，otherwise exception will be thrown（当尝试创建一个标记时，应该有一个相关的标签载入家庭）</td>
</tr>
<tr>
<td>Material Tags</td>
<td>IndependentTag.Create(Document, ElementId, Reference, Boolean, TagMode, TagOrientation, XYZ)</td>
<td>TagMode应为TM_ADDBY_MATERIAL，并且应加载材质标签族，否则将引发异常</td>
</tr>
<tr>
<td>Multi-Category Tags</td>
<td>IndependentTag.Create(Document, ElementId, Reference, Boolean, TagMode, TagOrientation, XYZ)</td>
<td>TagMode应为TM_ADDBY_MULTICATEGORY，并且应加载多类别标记族，否则将抛出异常</td>
</tr>
<tr>
<td>Title Blocks</td>
<td>ViewSheet.Create(Document, ElementId)</td>
<td>标题栏将添加到新创建的图纸中。</td>
</tr>
</tbody></table>
<p>使用Document.LoadFamily（）或Document.LoadFamilySymbol（）方法加载族和族符号。某些族（如梁）具有多个端点，插入方式与插入单个点实例的方式相同。插入线性族实例后，可以使用Element.Location属性更改其端点。有关详细信息，请参阅代码示例。</p>
<h2 id="代码示例"><a href="#代码示例" class="headerlink" title="代码示例"></a>代码示例</h2><p>用于使用Family Data的代码示例。</p>
<p>有关使用Family Object的详细信息，请查看以下代码示例。请注意，在NewFamilyInstance（）方法中，需要StructuralType参数来指定要创建的族实例的类型。以下是一些示例：</p>
<p>表34：NewFamilyInstance（）方法中StructuralType参数的值</p>
<table>
<thead>
<tr>
<th><strong>Type of Family Instance 族实例的类型</strong></th>
<th><strong>Value of StructuralType StructuralType的值</strong></th>
</tr>
</thead>
<tbody><tr>
<td>Doors, tables, etc. 门、桌子等</td>
<td>NonStructural 非结构</td>
</tr>
<tr>
<td>Beams 梁</td>
<td>Beam 梁</td>
</tr>
<tr>
<td>Braces 支撑</td>
<td>Brace 支撑</td>
</tr>
<tr>
<td>Columns 柱</td>
<td>Column 柱</td>
</tr>
<tr>
<td>Footings 基础</td>
<td>Footing 基础</td>
</tr>
</tbody></table>
<h3 id="创建桌"><a href="#创建桌" class="headerlink" title="创建桌"></a>创建桌</h3><p>以下函数演示了如何将表族加载到Revit项目中，以及如何从该族中的所有符号创建实例。</p>
<p>如果指定的族以前已加载，则LoadFamily（）方法返回false。因此，在以下情况下，在调用此函数之前，不加载族Table-Dining Round w Chairs.rfa。在本例中，默认情况下，桌是在标高1创建的。</p>
<p>代码区域12-3：创建桌</p>
<figure class="highlight c#"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br><span class="line">23</span><br><span class="line">24</span><br><span class="line">25</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="keyword">void</span> <span class="title">CreateTables</span>(<span class="params">Autodesk.Revit.DB.Document document</span>)</span></span><br><span class="line">&#123;</span><br><span class="line"></span><br><span class="line">    String fileName = <span class="string">@&quot;C:\ProgramData\Autodesk\RVT 2014\Libraries\US Imperial\Furniture\Tables\Table-Dining Round w Chairs.rfa&quot;</span>;</span><br><span class="line"></span><br><span class="line">    <span class="comment">// try to load family</span></span><br><span class="line">    Family family = <span class="literal">null</span>;</span><br><span class="line">    <span class="keyword">if</span> (!document.LoadFamily(fileName, <span class="keyword">out</span> family))</span><br><span class="line">    &#123;</span><br><span class="line">        <span class="keyword">throw</span> <span class="keyword">new</span> Exception(<span class="string">&quot;Unable to load &quot;</span> + fileName);</span><br><span class="line">    &#125;</span><br><span class="line"></span><br><span class="line">    <span class="comment">// Loop through table symbols and add a new table for each</span></span><br><span class="line">    ISet familySymbolIds = family.GetFamilySymbolIds();</span><br><span class="line">    <span class="built_in">double</span> x = <span class="number">0.0</span>, y = <span class="number">0.0</span>;</span><br><span class="line">    <span class="keyword">foreach</span> (ElementId id <span class="keyword">in</span> familySymbolIds)</span><br><span class="line">    &#123;</span><br><span class="line">        FamilySymbol symbol = family.Document.GetElement(id) <span class="keyword">as</span> FamilySymbol;</span><br><span class="line">        symbol.Activate();</span><br><span class="line">        XYZ location = <span class="keyword">new</span> XYZ(x, y, <span class="number">10.0</span>);</span><br><span class="line"></span><br><span class="line">        FamilyInstance instance = document.Create.NewFamilyInstance(location, symbol, StructuralType.NonStructural);</span><br><span class="line">        x += <span class="number">10.0</span>;</span><br><span class="line">    &#125;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<p>加载桌族并放置每个FamilySymbol的一个实例的结果：</p>
<p><img src="https://help.autodesk.com/cloudhelp/2018/ENU/Revit-API/images/GUID-5FE17FC0-A248-47AE-A08A-1BBA3156193B-low.png"></p>
<p>图47：在Revit项目中加载族并创建表格 </p>
<h3 id="创建Beam"><a href="#创建Beam" class="headerlink" title="创建Beam"></a>创建Beam</h3><p> 在此示例中，加载的是族符号而不是族，因为加载单个FamilySymbol比加载包含许多FamilySymbol的族要快。</p>
<p>代码区域12-4：创建梁</p>
<figure class="highlight c#"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br><span class="line">23</span><br><span class="line">24</span><br></pre></td><td class="code"><pre><span class="line"><span class="function">FamilyInstance <span class="title">CreateBeam</span>(<span class="params">Autodesk.Revit.DB.Document document, View view</span>)</span></span><br><span class="line">&#123;</span><br><span class="line"></span><br><span class="line">    <span class="comment">// get the given view&#x27;s level for beam creation</span></span><br><span class="line">    Level level = document.GetElement(view.LevelId) <span class="keyword">as</span> Level;</span><br><span class="line"></span><br><span class="line">    <span class="comment">// get a family symbol</span></span><br><span class="line">    FilteredElementCollector collector = <span class="keyword">new</span> FilteredElementCollector(document);</span><br><span class="line">    collector.OfClass(<span class="keyword">typeof</span>(FamilySymbol)).OfCategory(BuiltInCategory.OST_StructuralFraming);</span><br><span class="line"></span><br><span class="line">    FamilySymbol gotSymbol = collector.FirstElement() <span class="keyword">as</span> FamilySymbol;</span><br><span class="line"></span><br><span class="line">    <span class="comment">// create new beam 10&#x27; long starting at origin</span></span><br><span class="line">    XYZ startPoint = <span class="keyword">new</span> XYZ(<span class="number">0</span>, <span class="number">0</span>, <span class="number">0</span>);</span><br><span class="line">    XYZ endPoint = <span class="keyword">new</span> Autodesk.Revit.DB.XYZ(<span class="number">10</span>, <span class="number">0</span>, <span class="number">0</span>);</span><br><span class="line"></span><br><span class="line">    Autodesk.Revit.DB.Curve beamLine = Line.CreateBound(startPoint, endPoint);</span><br><span class="line"></span><br><span class="line">    <span class="comment">// create a new beam</span></span><br><span class="line">    FamilyInstance instance = document.Create.NewFamilyInstance(beamLine, gotSymbol,</span><br><span class="line">                                                                level, StructuralType.Beam);</span><br><span class="line"></span><br><span class="line">    <span class="keyword">return</span> instance;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<h3 id="创建门"><a href="#创建门" class="headerlink" title="创建门"></a>创建门</h3><p>创建一个长约180’的长墙，并在运行此示例之前选择它。宿主对象必须支持插入实例;否则NewFamilyInstance（）方法将失败。如果没有为必须在宿主中创建的实例提供宿主元素，或者无法将实例插入到指定的宿主元素中，则方法NewFamilyInstance（）不执行任何操作。</p>
<p>代码区域12-5：创建门</p>
<figure class="highlight c#"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br><span class="line">23</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="keyword">void</span> <span class="title">CreateDoorsInWall</span>(<span class="params">Autodesk.Revit.DB.Document document, Wall wall</span>)</span></span><br><span class="line">&#123;</span><br><span class="line">    <span class="comment">// get wall&#x27;s level for door creation</span></span><br><span class="line">    Level level = document.GetElement(wall.LevelId) <span class="keyword">as</span> Level;</span><br><span class="line"></span><br><span class="line">    FilteredElementCollector collector = <span class="keyword">new</span> FilteredElementCollector(document);</span><br><span class="line">    ICollection collection = collector.OfClass(<span class="keyword">typeof</span>(FamilySymbol))</span><br><span class="line">                                                .OfCategory(BuiltInCategory.OST_Doors)</span><br><span class="line">                                                .ToElements();</span><br><span class="line">    IEnumerator symbolItor = collection.GetEnumerator();</span><br><span class="line"></span><br><span class="line">    <span class="built_in">double</span> x = <span class="number">0</span>, y = <span class="number">0</span>, z = <span class="number">0</span>;</span><br><span class="line">    <span class="keyword">while</span> (symbolItor.MoveNext())</span><br><span class="line">    &#123;</span><br><span class="line">        FamilySymbol symbol = symbolItor.Current <span class="keyword">as</span> FamilySymbol;</span><br><span class="line">        symbol.Activate();</span><br><span class="line">        XYZ location = <span class="keyword">new</span> XYZ(x, y, z);</span><br><span class="line">        FamilyInstance instance = document.Create.NewFamilyInstance(location, symbol, wall, level, StructuralType.NonStructural);</span><br><span class="line">        x += <span class="number">10</span>;</span><br><span class="line">        y += <span class="number">10</span>;</span><br><span class="line">        z += <span class="number">1.5</span>;</span><br><span class="line">    &#125;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<p>下图显示了在Revit中执行上述代码的结果。请注意，如果指定的位置不在指定的标高上，NewFamilyInstance（）方法将使用位置标高而不是标高。</p>
<p><img src="https://help.autodesk.com/cloudhelp/2018/ENU/Revit-API/images/GUID-3175405A-CD58-4A39-8DC8-696E76652DBB-low.png"></p>
<p>图48：将门插入墙壁</p>
<h3 id="使用参考方向创建族实例"><a href="#使用参考方向创建族实例" class="headerlink" title="使用参考方向创建族实例"></a>使用参考方向创建族实例</h3><p>使用参照方向可在特定方向上插入项目。</p>
<p>代码区域12-6：使用参考方向创建族实例</p>
<figure class="highlight c#"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br><span class="line">23</span><br><span class="line">24</span><br><span class="line">25</span><br><span class="line">26</span><br><span class="line">27</span><br><span class="line">28</span><br><span class="line">29</span><br><span class="line">30</span><br><span class="line">31</span><br><span class="line">32</span><br><span class="line">33</span><br><span class="line">34</span><br><span class="line">35</span><br><span class="line">36</span><br><span class="line">37</span><br><span class="line">38</span><br><span class="line">39</span><br><span class="line">40</span><br><span class="line">41</span><br><span class="line">42</span><br><span class="line">43</span><br><span class="line">44</span><br><span class="line">45</span><br><span class="line">46</span><br><span class="line">47</span><br><span class="line">48</span><br><span class="line">49</span><br><span class="line">50</span><br><span class="line">51</span><br><span class="line">52</span><br><span class="line">53</span><br></pre></td><td class="code"><pre><span class="line"><span class="comment">// Get a floor to place the beds</span></span><br><span class="line">FilteredElementCollector collector = <span class="keyword">new</span> FilteredElementCollector(document);</span><br><span class="line">Floor floor = collector.OfClass(<span class="keyword">typeof</span>(Floor)).FirstElement() <span class="keyword">as</span> Floor;</span><br><span class="line"><span class="keyword">if</span> (floor != <span class="literal">null</span>)</span><br><span class="line">&#123;</span><br><span class="line">    <span class="comment">// Find a Bed-Box family</span></span><br><span class="line">    Family family = <span class="literal">null</span>;</span><br><span class="line">    FilteredElementCollector famCollector = <span class="keyword">new</span> FilteredElementCollector(document);</span><br><span class="line">    famCollector.OfClass(<span class="keyword">typeof</span>(Family));</span><br><span class="line">    ICollection collection = famCollector.ToElements();</span><br><span class="line">    <span class="keyword">foreach</span> (Element element <span class="keyword">in</span> collection)</span><br><span class="line">    &#123;</span><br><span class="line"></span><br><span class="line">        <span class="keyword">if</span> (element.Name.CompareTo(<span class="string">&quot;双人床 - 箱式&quot;</span>) == <span class="number">0</span>)</span><br><span class="line">        &#123;</span><br><span class="line">            family = element <span class="keyword">as</span> Family;</span><br><span class="line">            <span class="keyword">break</span>;</span><br><span class="line">        &#125;</span><br><span class="line">    &#125;</span><br><span class="line"></span><br><span class="line">    <span class="keyword">if</span> (family != <span class="literal">null</span>)</span><br><span class="line">    &#123;</span><br><span class="line">        <span class="comment">// Enumerate the beds in the Bed-Box family</span></span><br><span class="line">        FilteredElementCollector fsCollector = <span class="keyword">new</span> FilteredElementCollector(document);</span><br><span class="line">        ICollection fsCollection = fsCollector.WherePasses(<span class="keyword">new</span> FamilySymbolFilter(family.Id)).ToElements();</span><br><span class="line">        IEnumerator symbolItor = fsCollection.GetEnumerator();</span><br><span class="line"></span><br><span class="line">        <span class="built_in">int</span> x = <span class="number">0</span>, y = <span class="number">0</span>;</span><br><span class="line">        <span class="built_in">int</span> i = <span class="number">0</span>;</span><br><span class="line">        <span class="keyword">while</span> (symbolItor.MoveNext())</span><br><span class="line">        &#123;</span><br><span class="line">            FamilySymbol symbol = symbolItor.Current <span class="keyword">as</span> FamilySymbol;</span><br><span class="line">            symbol.Activate();</span><br><span class="line">            XYZ location = <span class="keyword">new</span> XYZ(x, y, <span class="number">0</span>);</span><br><span class="line">            XYZ direction = <span class="keyword">new</span> XYZ();</span><br><span class="line">            <span class="keyword">switch</span> (i % <span class="number">3</span>)</span><br><span class="line">            &#123;</span><br><span class="line">                <span class="keyword">case</span> <span class="number">0</span>:</span><br><span class="line">                    direction = <span class="keyword">new</span> XYZ(<span class="number">1</span>, <span class="number">1</span>, <span class="number">0</span>);</span><br><span class="line">                    <span class="keyword">break</span>;</span><br><span class="line">                <span class="keyword">case</span> <span class="number">1</span>:</span><br><span class="line">                    direction = <span class="keyword">new</span> XYZ(<span class="number">0</span>, <span class="number">1</span>, <span class="number">1</span>);</span><br><span class="line">                    <span class="keyword">break</span>;</span><br><span class="line">                <span class="keyword">case</span> <span class="number">2</span>:</span><br><span class="line">                    direction = <span class="keyword">new</span> XYZ(<span class="number">1</span>, <span class="number">0</span>, <span class="number">1</span>);</span><br><span class="line">                    <span class="keyword">break</span>;</span><br><span class="line">            &#125;</span><br><span class="line">            FamilyInstance instance = document.Create.NewFamilyInstance(location, symbol, direction, floor, StructuralType.NonStructural);</span><br><span class="line">            x += <span class="number">10</span>;</span><br><span class="line">            i++;</span><br><span class="line">        &#125;</span><br><span class="line">    &#125;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<p>上一个代码的结果显示在下图中：</p>
<p><img src="https://help.autodesk.com/cloudhelp/2018/ENU/Revit-API/images/GUID-86B0A1C3-988D-4C4B-BA8E-3C8C9BDEAAE0-low.png"></p>
<p>图49：使用不同的参照方向创建族实例</p>
<h2 id="族符号"><a href="#族符号" class="headerlink" title="族符号"></a>族符号</h2><p>FamilySymbol类表示族中的单个类型。</p>
<p>每个族可以包含一个或多个族符号。每个FamilyInstance都有一个关联的FamilySymbol，可以从其Symbol属性访问。</p>
<h3 id="热属性"><a href="#热属性" class="headerlink" title="热属性"></a>热属性</h3><p>某些类型的族（门、窗和幕墙嵌板）包含下面窗的“类型属性”窗口中所示的热属性。</p>
<p><img src="https://help.autodesk.com/cloudhelp/2018/ENU/Revit-API/images/FamilyThermalProperties2-76173.jpg"></p>
<p>FamilySymbol的热属性由FamilyThermalProperties类表示，并使用FamilySymbol.GetThermalProperties（）方法检索。可以使用SetThermalProperties（）设置FamilySymbol的FamilyThermalProperties。FamilyThermalProperties类本身的属性是只读的。</p>
<p>计算值的单位如下表所示。</p>
<table>
<thead>
<tr>
<th><strong>Property 属性</strong></th>
<th><strong>Unit 单位</strong></th>
</tr>
</thead>
<tbody><tr>
<td>HeatTransferCoefficient 传热系数</td>
<td>watts per meter-squared kelvin (W&#x2F;(m^2<em>K)</em></td>
</tr>
<tr>
<td>ThermalResistance 热阻</td>
<td>meter-squared kelvin per watt ((m^2K)&#x2F;Watt)</td>
</tr>
</tbody></table>
<p>AnalyticConstructionTypeId属性是构造gbXML类型，并返回与Constructions.xml中constructionType节点的“id”属性对应的值。静态FamilyThermalProperties.Find（）方法将通过Constructions.xml中constructionType节点的“id”属性查找FamilyThermalProperties。</p>
<p> #FamilyType参数 </p>
<p>FamilySymbol的某些参数可以是FamilyType参数。对于这些参数，可以使用Family.GetFamilyTypeParameterValues（）方法获取参数的所有适用值。返回的值是与给定参数的定义所指定的类别相匹配的所有族类型的ElementId。这些元素属于类ElementType或NestedFamilyTypeReference。第二种变体适用于嵌套在族中的类型，因此无法以其他方式访问。NestedFamilyTypeReference元素仅存储有关嵌套FamilyType的基本信息，例如Type的名称、Family的名称和Category。这些元素非常低级，因此被标准元素过滤器绕过，因此获取它们的主要方法是通过Family.GetFamilyTypeParameterValues（）方法。 以下示例演示如何获取FamilySymbol的FamilyType参数的所有族类型参数值。然后将参数的值更改为另一个值。此更改将影响使用加载的FamilySymbol的所有FamilySymbol。</p>
<p>代码区域：获取嵌套的FamilyTypes</p>
<figure class="highlight c#"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br><span class="line">23</span><br><span class="line">24</span><br><span class="line">25</span><br><span class="line">26</span><br><span class="line">27</span><br><span class="line">28</span><br><span class="line">29</span><br><span class="line">30</span><br><span class="line">31</span><br><span class="line">32</span><br><span class="line">33</span><br><span class="line">34</span><br><span class="line">35</span><br><span class="line">36</span><br><span class="line">37</span><br><span class="line">38</span><br><span class="line">39</span><br><span class="line">40</span><br><span class="line">41</span><br><span class="line">42</span><br><span class="line">43</span><br><span class="line">44</span><br><span class="line">45</span><br><span class="line">46</span><br><span class="line">47</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="keyword">public</span> <span class="keyword">void</span> <span class="title">GetNestedFamilyTypes</span>(<span class="params">FamilyInstance instance</span>)</span></span><br><span class="line">&#123;</span><br><span class="line">    <span class="comment">// find one FamilyType parameter and all values applicable to it</span></span><br><span class="line"></span><br><span class="line">    Parameter aTypeParam = <span class="literal">null</span>;</span><br><span class="line">    ISet values = <span class="literal">null</span>;</span><br><span class="line"></span><br><span class="line">    Family family = instance.Symbol.Family;</span><br><span class="line"></span><br><span class="line">    <span class="keyword">foreach</span> (Parameter param <span class="keyword">in</span> instance.Symbol.Parameters)</span><br><span class="line">    &#123;</span><br><span class="line"></span><br><span class="line">        <span class="keyword">if</span> (param.Definition.ParameterType == ParameterType.FamilyType)</span><br><span class="line">        &#123;</span><br><span class="line"></span><br><span class="line">            aTypeParam = param;</span><br><span class="line"></span><br><span class="line">            values = family.GetFamilyTypeParameterValues(param.Id);</span><br><span class="line"></span><br><span class="line">            <span class="keyword">break</span>;</span><br><span class="line">        &#125;</span><br><span class="line">    &#125;</span><br><span class="line"></span><br><span class="line">    <span class="keyword">if</span> (aTypeParam == <span class="literal">null</span>)</span><br><span class="line">    &#123;</span><br><span class="line">        TaskDialog.Show(<span class="string">&quot;Warning&quot;</span>, <span class="string">&quot;The selected family has no FamilyType parameter defined.&quot;</span>);</span><br><span class="line">    &#125;</span><br><span class="line">    <span class="keyword">else</span> <span class="keyword">if</span> (values == <span class="literal">null</span>)</span><br><span class="line">    &#123;</span><br><span class="line">        TaskDialog.Show(<span class="string">&quot;Error&quot;</span>, <span class="string">&quot;A FamilyType parameter does not have any applicable values!?&quot;</span>);</span><br><span class="line">    &#125;</span><br><span class="line">    <span class="keyword">else</span></span><br><span class="line">    &#123;</span><br><span class="line">        ElementId newValue = values.Last();</span><br><span class="line"></span><br><span class="line">        <span class="keyword">if</span> (newValue != aTypeParam.AsElementId())</span><br><span class="line">        &#123;</span><br><span class="line"></span><br><span class="line">            <span class="keyword">using</span> (Transaction trans = <span class="keyword">new</span> Transaction(instance.Document, <span class="string">&quot;Setting parameter value&quot;</span>))</span><br><span class="line">            &#123;</span><br><span class="line">                trans.Start();</span><br><span class="line">                aTypeParam.Set(newValue);</span><br><span class="line">                trans.Commit();</span><br><span class="line">            &#125;</span><br><span class="line">        &#125;</span><br><span class="line">    &#125;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<h2 id="族"><a href="#族" class="headerlink" title="族"></a>族</h2><p>“族”类表示整个Revit族。它包含FamilySymbols使用的FamilySymbols。</p>
<h3 id="载入族"><a href="#载入族" class="headerlink" title="载入族"></a>载入族</h3><p>Document类包含LoadFamily（）和LoadFamilySymbol（）方法。</p>
<ul>
<li>LoadFamily（）将整个族及其所有类型或符号加载到项目中。</li>
<li>LoadFamilySymbol（）仅将指定的族符号从族文件载入到项目中。</li>
</ul>
<p><strong>注意：</strong>要提高应用程序的性能并减少内存使用，请尽可能加载特定的FamilySymbol，而不是整个Family对象。</p>
<ul>
<li>使用Options.Application对象GetLibraryPaths（）方法检索族文件路径。</li>
<li>Options.Application对象是使用Application对象的Options属性检索的。</li>
<li>在LoadFamilySymbol（）中，输入参数Name与FamilySymbol对象Name属性返回的字符串值相同。</li>
</ul>
<p>有关详细信息，请参阅代码示例。</p>
<p>类别</p>
<p>FamilyCategory属性指示族的类别，例如柱、家具、结构框架或窗。</p>
</article><div class="tag_share"><div class="post-meta__tag-list"><a class="post-meta__tags" href="/tags/Revit/">Revit</a></div><div class="post-share"><div class="social-share" data-image="/images/4stars.png" data-sites="facebook,twitter,wechat,weibo,qq"></div><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/butterfly-extsrc/sharejs/dist/css/share.min.css" media="print" onload="this.media='all'"><script src="https://cdn.jsdelivr.net/npm/butterfly-extsrc/sharejs/dist/js/social-share.min.js" defer></script></div></div><nav class="pagination-post" id="pagination"><a class="pagination-related" href="/2024/11/23/Revit%E4%BA%8C%E5%BC%80%E6%8C%87%E5%8D%97/07%E5%8F%82%E6%95%B0/" title="07参数"><div class="cover" style="background: var(--default-bg-color)"></div><div class="info"><div class="info-1"><div class="info-item-1">上一篇</div><div class="info-item-2">07参数</div></div><div class="info-2"><div class="info-item-1">参数Revit提供了一种常规机制，为每个图元提供一组可编辑的参数。 在Revit UI中，某些图元参数在“图元属性”窗口中可见。以下各节介绍如何获取和使用内置参数、共享参数和全局参数。 在Revit Platform...</div></div></div></a><a class="pagination-related" href="/2024/11/21/Revit%E4%BA%8C%E5%BC%80%E6%8C%87%E5%8D%97/12%E5%A2%99%E3%80%81%E6%A5%BC%E6%9D%BF%E3%80%81%E5%A4%A9%E8%8A%B1%E6%9D%BF%E3%80%81%E5%B1%8B%E9%A1%B6%E5%92%8C%E6%B4%9E%E5%8F%A3/" title="12墙、楼板、天花板、屋顶和洞口"><div class="cover" style="background: var(--default-bg-color)"></div><div class="info text-right"><div class="info-1"><div class="info-item-1">下一篇</div><div class="info-item-2">12墙、楼板、天花板、屋顶和洞口</div></div><div class="info-2"><div class="info-item-1">墙、楼板、天花板、屋顶和洞口元素和表示内置位置构造的相应ElementType。 以下部分介绍与内置位置构造（如墙、楼板、天花板、屋顶和洞口）相关的类及其相应的属性。 本节中的页面  墙 楼板、天花板和基础 屋顶 幕墙 其他元素 复合结构 洞口 热属性  墙WallType.Kind枚举表示四种墙：  Stacked 叠层墙 Curtain 幕墙 Basic 基本 Unknown...</div></div></div></a></nav><div class="relatedPosts"><div class="headline"><i class="fas fa-thumbs-up fa-fw"></i><span>相关推荐</span></div><div class="relatedPosts-list"><a class="pagination-related" href="/2024/11/23/Revit%E4%BA%8C%E5%BC%80%E6%8C%87%E5%8D%97/01%E5%BC%80%E5%A7%8B/" title="01开始"><div class="cover" style="background: var(--default-bg-color)"></div><div class="info text-center"><div class="info-1"><div class="info-item-1"><i class="far fa-calendar-alt fa-fw"></i> 2024-11-23</div><div class="info-item-2">01开始</div></div><div class="info-2"><div class="info-item-1">开始Revit 平台 API 可通过与 Microsoft .NET Framework 4.5.2 或 4.6 兼容的任何语言（如 Visual C# 或 Visual Basic .NET （VB.NET））进行完全访问。Visual C# 和 VB.NET 通常用于开发 Revit 平台 API 应用程序。但是，本手册的重点是使用 Visual C# 开发应用程序。 欢迎使用 Revit Platform API所有基于 Autodesk Revit 的产品都是参数化建筑信息模型 （BIM） 工具。这样的工具可以看作是用于构建 3D 模型的 CAD 程序，而不是一组单独的图纸文件。Autodesk Revit 建模是通过柱、墙、门和窗等真实世界的元素完成的。用户可以创建模型的视图，包括平面图、剖面图和详图索引。所有这些视图都是直接从 3D 物理模型生成的，因此在一个视图中所做的更改将自动传播到所有其他视图。此过程几乎消除了在模型中进行更改时更新多个图纸和细节的需要。 Autodesk Revit API 旨在反映与程序的图形用户界面相同的用户交互范例。因此，了解 API...</div></div></div></a><a class="pagination-related" href="/2024/11/26/Revit%E4%BA%8C%E5%BC%80%E6%8C%87%E5%8D%97/03%E5%BA%94%E7%94%A8%E5%8F%8A%E6%96%87%E6%A1%A3/" title="03应用及文档"><div class="cover" style="background: var(--default-bg-color)"></div><div class="info text-center"><div class="info-1"><div class="info-item-1"><i class="far fa-calendar-alt fa-fw"></i> 2024-11-26</div><div class="info-item-2">03应用及文档</div></div><div class="info-2"><div class="info-item-1">Application及DocumentRevit 平台 API 中的顶级对象是Application和Document。这些类由 Application、UIApplication、Document 和 UIDocument 类表示。 Application对象是指单个 Revit 任务，提供对文档、选项和其他应用程序范围的数据和设置的访问。 Autodesk.Revit.UI.UIApplication - 提供对应用程序的 UI 级界面的访问，包括将 RibbonPanel 添加到用户界面的功能，以及在用户界面中获取活动文档的功能。 Autodesk.Revit.ApplicationServices.Application - 提供对所有其他应用程序级别属性的访问。 Document是表示建筑模型的单个 Revit 项目文件。Revit 可以打开多个项目，并为一个项目打开多个视图。 Autodesk.Revit.UI.UIDocument - 提供对文档的 UI...</div></div></div></a><a class="pagination-related" href="/2024/11/26/Revit%E4%BA%8C%E5%BC%80%E6%8C%87%E5%8D%97/05%E8%BF%87%E6%BB%A4/" title="05过滤"><div class="cover" style="background: var(--default-bg-color)"></div><div class="info text-center"><div class="info-1"><div class="info-item-1"><i class="far fa-calendar-alt fa-fw"></i> 2024-11-26</div><div class="info-item-2">05过滤</div></div><div class="info-2"><div class="info-item-1">Filtering 过滤Revit API提供了一种过滤和迭代Revit文档中图元的机制。这是获取一组相关元素（如文档中的所有墙或门）的最佳方法。过滤器也可以用来找到一个非常具体的元素集，如所有特定大小的梁。 获取通过指定过滤器的元素的基本步骤如下：  创建新的FilteredElementCollector 对它应用一个或多个过滤器 获取过滤后的元素或元素ID（使用以下几种方法之一）  下面的示例涵盖了在文档中筛选和迭代元素的基本步骤。 代码区域6-1：使用元素过滤获取文档中的所有墙实例 1234567891011121314// Find all Wall instances in the document by using category filterElementCategoryFilter filter = new ElementCategoryFilter(BuiltInCategory.OST_Walls);// Apply the filter to the elements in the active document// Use shortcut...</div></div></div></a><a class="pagination-related" href="/2024/12/05/Revit%E4%BA%8C%E5%BC%80%E6%8C%87%E5%8D%97/08%E9%9B%86%E5%90%88/" title="08集合"><div class="cover" style="background: var(--default-bg-color)"></div><div class="info text-center"><div class="info-1"><div class="info-item-1"><i class="far fa-calendar-alt fa-fw"></i> 2024-12-05</div><div class="info-item-2">08集合</div></div><div class="info-2"><div class="info-item-1">集合大多数Revit Platform API属性和方法在提供对一组相关项的访问时都使用.NET Framework集合类。 在Revit集合类型中实现的IEnumerator和IEnumerator接口在System.Collection命名空间中定义。 Pages in this section 本节中的页面  Interface 接口 Collections and Iterators 集合和迭代器  Interface...</div></div></div></a><a class="pagination-related" href="/2024/11/23/Revit%E4%BA%8C%E5%BC%80%E6%8C%87%E5%8D%97/02%E6%8F%92%E4%BB%B6%E9%9B%86%E6%88%90/" title="02插件集成"><div class="cover" style="background: var(--default-bg-color)"></div><div class="info text-center"><div class="info-1"><div class="info-item-1"><i class="far fa-calendar-alt fa-fw"></i> 2024-11-23</div><div class="info-item-2">02插件集成</div></div><div class="info-2"><div class="info-item-1">插件集成开发人员通过创建和实现 External Commands 和 External Applications 来添加功能。Revit 使用 .addin 清单文件标识新命令和应用程序。外部命令显示在 Add-Ins 选项卡上的 External Tools 菜单按钮下。外部应用程序在 Revit 启动时调用，在 Revit 关闭时卸载。 本章重点介绍以下内容：  了解如何使用 External Commands 和 External Applications 添加功能。 如何访问 Revit 事件。 如何自定义 Revit UI。  概述Revit 平台 API 基于 Revit 应用程序功能。Revit 平台 API 由两个类库组成，这两个类库仅在 Revit 运行时工作。 RevitAPI.dll包含用于在数据库级别访问 Revit 的应用程序、文档、图元和参数的方法。它还包含 IExternalDBApplication 和相关接口。 RevitAPIUI.dll包含与 Revit 用户界面的操作和自定义相关的所有 API...</div></div></div></a><a class="pagination-related" href="/2024/11/26/Revit%E4%BA%8C%E5%BC%80%E6%8C%87%E5%8D%97/04%E5%85%83%E7%B4%A0%E8%A6%81%E7%82%B9/" title="04元素要点"><div class="cover" style="background: var(--default-bg-color)"></div><div class="info text-center"><div class="info-1"><div class="info-item-1"><i class="far fa-calendar-alt fa-fw"></i> 2024-11-26</div><div class="info-item-2">04元素要点</div></div><div class="info-2"><div class="info-item-1">元素要点元素对应于单个建筑或绘图构件，例如门、墙或尺寸标注。此外，元素可以是门类型、视图或材质定义。 元素分类Revit 图元分为六组：模型、草图、视图、组、注释和信息。每个组都包含相关的元素及其相应的符号。 模型元素模型元素表示建筑项目中存在的物理项。“模型元素”组中的元素可以细分为以下元素： 族实例 - 族实例包含族实例对象。可以将族对象载入到项目中，也可以从族样板创建族对象。有关更多信息，请参阅系列实例。 主体图元 - 主体图元包含系统族对象，这些对象可以包含其他模型图元，例如墙、屋顶、天花板和楼板。有关主体图元的更多信息，请参见墙、楼板、屋顶和洞口。 结构元素-结构图元包含仅用于 Revit 结构特征的图元。有关 Structure Elements 的更多信息，请参见 Structural Engineering。 视图元素视图图元表示在 Revit 中查看其他对象并与其他对象交互的方式。有关更多信息，请参阅视图。 组元素组图元表示辅助图元，例如 Revit...</div></div></div></a></div></div><hr class="custom-hr"/><div id="post-comment"><div class="comment-head"><div class="comment-headline"><i class="fas fa-comments fa-fw"></i><span> 评论</span></div></div><div class="comment-wrap"><div><div id="giscus-wrap"></div></div></div></div></div><div class="aside-content" id="aside-content"><div class="card-widget card-info text-center"><div class="avatar-img"><img src="/images/4stars.png" onerror="this.onerror=null;this.src='/img/friend_404.gif'" alt="avatar"/></div><div class="author-info-name">funtim41@gmail.com</div><div class="author-info-description">实践-认识-再实践-再认识</div><div class="site-data"><a href="/archives/"><div class="headline">文章</div><div class="length-num">67</div></a><a href="/tags/"><div class="headline">标签</div><div class="length-num">5</div></a><a href="/categories/"><div class="headline">分类</div><div class="length-num">7</div></a></div><a id="card-info-btn" target="_blank" rel="noopener" href="https://github.com/FunTim41"><i class="fab fa-github"></i><span>Follow Me</span></a><div class="card-info-social-icons"><a class="social-icon" href="https://github.com/FunTim41" target="_blank" title="Github"><i class="fab fa-github" style="color: #FFFFFF;"></i></a></div></div><div class="card-widget card-announcement"><div class="item-headline"><i class="fas fa-bullhorn fa-shake"></i><span>公告</span></div><div class="announcement_content">This is my Blog</div></div><div class="sticky_layout"><div class="card-widget" id="card-toc"><div class="item-headline"><i class="fas fa-stream"></i><span>目录</span><span class="toc-percentage"></span></div><div class="toc-content"><ol class="toc"><li class="toc-item toc-level-1"><a class="toc-link" href="#%E6%97%8F%E5%AE%9E%E4%BE%8B"><span class="toc-number">1.</span> <span class="toc-text">族实例</span></a><ol class="toc-child"><li class="toc-item toc-level-2"><a class="toc-link" href="#%E8%AF%86%E5%88%AB%E5%85%83%E7%B4%A0"><span class="toc-number">1.1.</span> <span class="toc-text">识别元素</span></a></li><li class="toc-item toc-level-2"><a class="toc-link" href="#%E6%97%8F%E5%AE%9E%E4%BE%8B-1"><span class="toc-number">1.2.</span> <span class="toc-text">族实例</span></a><ol class="toc-child"><li class="toc-item toc-level-3"><a class="toc-link" href="#%E4%BD%8D%E7%BD%AE%E7%9B%B8%E5%85%B3%E5%B1%9E%E6%80%A7"><span class="toc-number">1.2.1.</span> <span class="toc-text">位置相关属性</span></a><ol class="toc-child"><li class="toc-item toc-level-4"><a class="toc-link" href="#Orientation-%E6%9C%9D%E5%90%91"><span class="toc-number">1.2.1.1.</span> <span class="toc-text">Orientation 朝向</span></a></li><li class="toc-item toc-level-4"><a class="toc-link" href="#Orientation-Work-Plane-%E6%96%B9%E4%BD%8D-%E5%B7%A5%E4%BD%9C%E5%B9%B3%E9%9D%A2"><span class="toc-number">1.2.1.2.</span> <span class="toc-text">Orientation - Work Plane 方位-工作平面</span></a></li><li class="toc-item toc-level-4"><a class="toc-link" href="#Rotation-Mirrored-%E6%97%8B%E8%BD%AC-%E9%95%9C%E5%83%8F"><span class="toc-number">1.2.1.3.</span> <span class="toc-text">Rotation - Mirrored 旋转-镜像</span></a></li></ol></li><li class="toc-item toc-level-3"><a class="toc-link" href="#%E5%87%A0%E4%BD%95"><span class="toc-number">1.2.2.</span> <span class="toc-text">几何</span></a></li><li class="toc-item toc-level-3"><a class="toc-link" href="#%E7%A9%BA%E9%97%B4%E5%85%83%E7%B4%A0%E8%AE%A1%E7%AE%97%E7%82%B9"><span class="toc-number">1.2.3.</span> <span class="toc-text">空间元素计算点</span></a></li><li class="toc-item toc-level-3"><a class="toc-link" href="#%E5%85%B6%E5%AE%83%E5%B1%9E%E6%80%A7"><span class="toc-number">1.2.4.</span> <span class="toc-text">其它属性</span></a><ol class="toc-child"><li class="toc-item toc-level-4"><a class="toc-link" href="#%E6%88%BF%E9%97%B4%E4%BF%A1%E6%81%AF"><span class="toc-number">1.2.4.1.</span> <span class="toc-text">房间信息</span></a></li><li class="toc-item toc-level-4"><a class="toc-link" href="#%E7%A9%BA%E9%97%B4%E4%BF%A1%E6%81%AF"><span class="toc-number">1.2.4.2.</span> <span class="toc-text">空间信息</span></a></li><li class="toc-item toc-level-4"><a class="toc-link" href="#%E7%BB%93%E6%9E%84%E5%88%86%E6%9E%90%E6%A8%A1%E5%9E%8B"><span class="toc-number">1.2.4.3.</span> <span class="toc-text">结构分析模型</span></a></li></ol></li><li class="toc-item toc-level-3"><a class="toc-link" href="#%E5%88%9B%E5%BB%BAFamilyInstance%E5%AF%B9%E8%B1%A1"><span class="toc-number">1.2.5.</span> <span class="toc-text">创建FamilyInstance对象</span></a></li></ol></li><li class="toc-item toc-level-2"><a class="toc-link" href="#%E4%BB%A3%E7%A0%81%E7%A4%BA%E4%BE%8B"><span class="toc-number">1.3.</span> <span class="toc-text">代码示例</span></a><ol class="toc-child"><li class="toc-item toc-level-3"><a class="toc-link" href="#%E5%88%9B%E5%BB%BA%E6%A1%8C"><span class="toc-number">1.3.1.</span> <span class="toc-text">创建桌</span></a></li><li class="toc-item toc-level-3"><a class="toc-link" href="#%E5%88%9B%E5%BB%BABeam"><span class="toc-number">1.3.2.</span> <span class="toc-text">创建Beam</span></a></li><li class="toc-item toc-level-3"><a class="toc-link" href="#%E5%88%9B%E5%BB%BA%E9%97%A8"><span class="toc-number">1.3.3.</span> <span class="toc-text">创建门</span></a></li><li class="toc-item toc-level-3"><a class="toc-link" href="#%E4%BD%BF%E7%94%A8%E5%8F%82%E8%80%83%E6%96%B9%E5%90%91%E5%88%9B%E5%BB%BA%E6%97%8F%E5%AE%9E%E4%BE%8B"><span class="toc-number">1.3.4.</span> <span class="toc-text">使用参考方向创建族实例</span></a></li></ol></li><li class="toc-item toc-level-2"><a class="toc-link" href="#%E6%97%8F%E7%AC%A6%E5%8F%B7"><span class="toc-number">1.4.</span> <span class="toc-text">族符号</span></a><ol class="toc-child"><li class="toc-item toc-level-3"><a class="toc-link" href="#%E7%83%AD%E5%B1%9E%E6%80%A7"><span class="toc-number">1.4.1.</span> <span class="toc-text">热属性</span></a></li></ol></li><li class="toc-item toc-level-2"><a class="toc-link" href="#%E6%97%8F"><span class="toc-number">1.5.</span> <span class="toc-text">族</span></a><ol class="toc-child"><li class="toc-item toc-level-3"><a class="toc-link" href="#%E8%BD%BD%E5%85%A5%E6%97%8F"><span class="toc-number">1.5.1.</span> <span class="toc-text">载入族</span></a></li></ol></li></ol></li></ol></div></div><div class="card-widget card-recent-post"><div class="item-headline"><i class="fas fa-history"></i><span>最新文章</span></div><div class="aside-list"><div class="aside-list-item no-cover"><div class="content"><a class="title" href="/2025/03/29/Revit%E4%BA%8C%E5%BC%80%E7%A4%BA%E4%BE%8B/%E5%9C%A8Revit%E4%B8%AD%E6%B1%82%E5%86%85%E8%BD%AE%E5%BB%93%E5%8F%8A%E5%A4%96%E8%BD%AE%E5%BB%93/" title="在Revit中求内轮廓及外轮廓">在Revit中求内轮廓及外轮廓</a><time datetime="2025-03-29T05:38:20.764Z" title="更新于 2025-03-29 13:38:20">2025-03-29</time></div></div><div class="aside-list-item no-cover"><div class="content"><a class="title" href="/2025/02/27/RevitApi%E5%90%88%E9%9B%86/Autodesk.Revit.DB%20XYZ%20/" title="Autodesk.Revit.DB XYZ">Autodesk.Revit.DB XYZ</a><time datetime="2025-02-27T12:48:50.709Z" title="更新于 2025-02-27 20:48:50">2025-02-27</time></div></div><div class="aside-list-item no-cover"><div class="content"><a class="title" href="/2025/02/20/RevitApi%E5%90%88%E9%9B%86/Autodesk.Revit.DB%20Curve/" title="Autodesk.Revit.DB Curve">Autodesk.Revit.DB Curve</a><time datetime="2025-02-27T12:28:18.794Z" title="更新于 2025-02-27 20:28:18">2025-02-27</time></div></div><div class="aside-list-item no-cover"><div class="content"><a class="title" href="/2025/02/20/RevitApi%E5%90%88%E9%9B%86/Autodesk.Revit.DB%20Line/" title="Autodesk.Revit.DB Line">Autodesk.Revit.DB Line</a><time datetime="2025-02-27T12:28:08.332Z" title="更新于 2025-02-27 20:28:08">2025-02-27</time></div></div><div class="aside-list-item no-cover"><div class="content"><a class="title" href="/2025/02/16/RevitApi%E5%90%88%E9%9B%86/Autodesk.Revit.ApplicationServices%20Application/" title="Autodesk.Revit.ApplicationServices Application">Autodesk.Revit.ApplicationServices Application</a><time datetime="2025-02-27T12:27:54.491Z" title="更新于 2025-02-27 20:27:54">2025-02-27</time></div></div></div></div></div></div></main><footer id="footer" style="background-image: url(/images/topback.jpg);"><div id="footer-wrap"><div class="copyright">&copy;2024 - 2025 By funtim41@gmail.com</div><div class="framework-info"><span>框架 </span><a target="_blank" rel="noopener" href="https://hexo.io">Hexo</a><span class="footer-separator">|</span><span>主题 </span><a target="_blank" rel="noopener" href="https://github.com/jerryc127/hexo-theme-butterfly">Butterfly</a></div><div class="footer_custom_text">学而不思则罔，思而不学则殆。</div></div></footer></div><div id="rightside"><div id="rightside-config-hide"><button id="readmode" type="button" title="阅读模式"><i class="fas fa-book-open"></i></button><button id="darkmode" type="button" title="日间和夜间模式切换"><i class="fas fa-adjust"></i></button><button id="hide-aside-btn" type="button" title="单栏和双栏切换"><i class="fas fa-arrows-alt-h"></i></button></div><div id="rightside-config-show"><button id="rightside-config" type="button" title="设置"><i class="fas fa-cog fa-spin"></i></button><button class="close" id="mobile-toc-button" type="button" title="目录"><i class="fas fa-list-ul"></i></button><a id="to_comment" href="#post-comment" title="前往评论"><i class="fas fa-comments"></i></a><button id="go-up" type="button" title="回到顶部"><span class="scroll-percent"></span><i class="fas fa-arrow-up"></i></button></div></div><div><script src="/js/utils.js"></script><script src="/js/main.js"></script><script src="https://cdn.jsdelivr.net/npm/node-snackbar/dist/snackbar.min.js"></script><script>(() => {
  const panguFn = () => {
    if (typeof pangu === 'object') pangu.autoSpacingPage()
    else {
      btf.getScript('https://cdn.jsdelivr.net/npm/pangu/dist/browser/pangu.min.js')
        .then(() => {
          pangu.autoSpacingPage()
        })
    }
  }

  const panguInit = () => {
    if (false){
      GLOBAL_CONFIG_SITE.isPost && panguFn()
    } else {
      panguFn()
    }
  }

  btf.addGlobalFn('pjaxComplete', panguInit, 'pangu')
  document.addEventListener('DOMContentLoaded', panguInit)
})()</script><div class="js-pjax"><script>(() => {
  const isShuoshuo = GLOBAL_CONFIG_SITE.isShuoshuo
  const option = null

  const getGiscusTheme = theme => theme === 'dark' ? 'dark' : 'light'

  const createScriptElement = config => {
    const ele = document.createElement('script')
    Object.entries(config).forEach(([key, value]) => {
      ele.setAttribute(key, value)
    })
    return ele
  }

  const loadGiscus = (el = document, key) => {
    const mappingConfig = isShuoshuo
      ? { 'data-mapping': 'specific', 'data-term': key }
      : { 'data-mapping': (option && option['data-mapping']) || 'pathname' }

    const giscusConfig = {
      src: 'https://giscus.app/client.js',
      'data-repo': 'FunTim41/funtim41.github.io',
      'data-repo-id': 'R_kgDONjG8ww',
      'data-category-id': 'DIC_kwDONjG8w84Cllg2',
      'data-theme': getGiscusTheme(document.documentElement.getAttribute('data-theme')),
      'data-reactions-enabled': '1',
      crossorigin: 'anonymous',
      async: true,
      ...option,
      ...mappingConfig
    }

    const scriptElement = createScriptElement(giscusConfig)

    el.querySelector('#giscus-wrap').appendChild(scriptElement)

    if (isShuoshuo) {
      window.shuoshuoComment.destroyGiscus = () => {
        if (el.children.length) {
          el.innerHTML = ''
          el.classList.add('no-comment')
        }
      }
    }
  }

  const changeGiscusTheme = theme => {
    const iframe = document.querySelector('#giscus-wrap iframe')
    if (iframe) {
      const message = {
        giscus: {
          setConfig: {
            theme: getGiscusTheme(theme)
          }
        }
      }
      iframe.contentWindow.postMessage(message, 'https://giscus.app')
    }
  }

  btf.addGlobalFn('themeChange', changeGiscusTheme, 'giscus')

  if (isShuoshuo) {
    'Giscus' === 'Giscus'
      ? window.shuoshuoComment = { loadComment: loadGiscus }
      : window.loadOtherComment = loadGiscus
    return
  }

  if ('Giscus' === 'Giscus' || !false) {
    if (false) btf.loadComment(document.getElementById('giscus-wrap'), loadGiscus)
    else loadGiscus()
  } else {
    window.loadOtherComment = loadGiscus
  }
})()</script></div><script defer="defer" id="fluttering_ribbon" mobile="false" src="https://cdn.jsdelivr.net/npm/butterfly-extsrc/dist/canvas-fluttering-ribbon.min.js"></script><script async data-pjax src="//busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js"></script><div id="local-search"><div class="search-dialog"><nav class="search-nav"><span class="search-dialog-title">搜索</span><span id="loading-status"></span><button class="search-close-button"><i class="fas fa-times"></i></button></nav><div class="text-center" id="loading-database"><i class="fas fa-spinner fa-pulse"></i><span>  数据加载中</span></div><div class="search-wrap"><div id="local-search-input"><div class="local-search-box"><input class="local-search-box--input" placeholder="搜索文章" type="text"/></div></div><hr/><div id="local-search-results"></div><div id="local-search-stats-wrap"></div></div></div><div id="search-mask"></div><script src="/js/search/local-search.js"></script></div></div></body></html>