<!DOCTYPE html><html lang="zh-CN" data-theme="light"><head><meta charset="UTF-8"><meta http-equiv="X-UA-Compatible" content="IE=edge"><meta name="viewport" content="width=device-width, initial-scale=1.0,viewport-fit=cover"><title>14族文档 | funtim的博客</title><meta name="author" content="funtim41@gmail.com"><meta name="copyright" content="funtim41@gmail.com"><meta name="format-detection" content="telephone=no"><meta name="theme-color" content="#ffffff"><meta name="description" content="族文档本节讨论族以及如何：  创建和修改族文档 访问族类型和参数  本节中的页面  关于族文档 在族中创建图元 族元素的可见性 管理族类型和参数  关于族文档族族对象表示整个Revit族。族文档是表示族的文档(rfa)而不是Revit项目。 使用Revit API的族创建功能，可以创建和编辑族及其类型。当您有来自外部系统的现有数据并希望将其转换为Revit族库时，此功能特别有用。 对系统族编辑的A">
<meta property="og:type" content="article">
<meta property="og:title" content="14族文档">
<meta property="og:url" content="https://funtim41.github.io/2024/11/29/Revit%E4%BA%8C%E5%BC%80%E6%8C%87%E5%8D%97/14%E6%97%8F%E6%96%87%E6%A1%A3/">
<meta property="og:site_name" content="funtim的博客">
<meta property="og:description" content="族文档本节讨论族以及如何：  创建和修改族文档 访问族类型和参数  本节中的页面  关于族文档 在族中创建图元 族元素的可见性 管理族类型和参数  关于族文档族族对象表示整个Revit族。族文档是表示族的文档(rfa)而不是Revit项目。 使用Revit API的族创建功能，可以创建和编辑族及其类型。当您有来自外部系统的现有数据并希望将其转换为Revit族库时，此功能特别有用。 对系统族编辑的A">
<meta property="og:locale" content="zh_CN">
<meta property="og:image" content="https://funtim41.github.io/images/4stars.png">
<meta property="article:published_time" content="2024-11-29T07:34:57.000Z">
<meta property="article:modified_time" content="2025-01-13T14:20:11.477Z">
<meta property="article:author" content="funtim41@gmail.com">
<meta property="article:tag" content="Revit">
<meta name="twitter:card" content="summary">
<meta name="twitter:image" content="https://funtim41.github.io/images/4stars.png"><link rel="shortcut icon" href="/images/OIP.jfif"><link rel="canonical" href="https://funtim41.github.io/2024/11/29/Revit%E4%BA%8C%E5%BC%80%E6%8C%87%E5%8D%97/14%E6%97%8F%E6%96%87%E6%A1%A3/"><link rel="preconnect" href="//cdn.jsdelivr.net"/><link rel="stylesheet" href="/css/index.css"><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free/css/all.min.css"><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/node-snackbar/dist/snackbar.min.css" media="print" onload="this.media='all'"><script>
    (() => {
      
    const saveToLocal = {
      set: (key, value, ttl) => {
        if (!ttl) return
        const expiry = Date.now() + ttl * 86400000
        localStorage.setItem(key, JSON.stringify({ value, expiry }))
      },
      get: key => {
        const itemStr = localStorage.getItem(key)
        if (!itemStr) return undefined
        const { value, expiry } = JSON.parse(itemStr)
        if (Date.now() > expiry) {
          localStorage.removeItem(key)
          return undefined
        }
        return value
      }
    }

    window.btf = {
      saveToLocal,
      getScript: (url, attr = {}) => new Promise((resolve, reject) => {
        const script = document.createElement('script')
        script.src = url
        script.async = true
        Object.entries(attr).forEach(([key, val]) => script.setAttribute(key, val))
        script.onload = script.onreadystatechange = () => {
          if (!script.readyState || /loaded|complete/.test(script.readyState)) resolve()
        }
        script.onerror = reject
        document.head.appendChild(script)
      }),
      getCSS: (url, id) => new Promise((resolve, reject) => {
        const link = document.createElement('link')
        link.rel = 'stylesheet'
        link.href = url
        if (id) link.id = id
        link.onload = link.onreadystatechange = () => {
          if (!link.readyState || /loaded|complete/.test(link.readyState)) resolve()
        }
        link.onerror = reject
        document.head.appendChild(link)
      }),
      addGlobalFn: (key, fn, name = false, parent = window) => {
        if (!false && key.startsWith('pjax')) return
        const globalFn = parent.globalFn || {}
        globalFn[key] = globalFn[key] || {}
        globalFn[key][name || Object.keys(globalFn[key]).length] = fn
        parent.globalFn = globalFn
      }
    }
  
      
      const activateDarkMode = () => {
        document.documentElement.setAttribute('data-theme', 'dark')
        if (document.querySelector('meta[name="theme-color"]') !== null) {
          document.querySelector('meta[name="theme-color"]').setAttribute('content', '#0d0d0d')
        }
      }
      const activateLightMode = () => {
        document.documentElement.setAttribute('data-theme', 'light')
        if (document.querySelector('meta[name="theme-color"]') !== null) {
          document.querySelector('meta[name="theme-color"]').setAttribute('content', '#ffffff')
        }
      }

      btf.activateDarkMode = activateDarkMode
      btf.activateLightMode = activateLightMode

      const theme = saveToLocal.get('theme')
    
          theme === 'dark' ? activateDarkMode() : theme === 'light' ? activateLightMode() : null
        
      
      const asideStatus = saveToLocal.get('aside-status')
      if (asideStatus !== undefined) {
        document.documentElement.classList.toggle('hide-aside', asideStatus === 'hide')
      }
    
      
    const detectApple = () => {
      if (/iPad|iPhone|iPod|Macintosh/.test(navigator.userAgent)) {
        document.documentElement.classList.add('apple')
      }
    }
    detectApple()
  
    })()
  </script><script>const GLOBAL_CONFIG = {
  root: '/',
  algolia: undefined,
  localSearch: {"path":"/search.xml","preload":false,"top_n_per_article":1,"unescape":false,"languages":{"hits_empty":"未找到符合您查询的内容：${query}","hits_stats":"共找到 ${hits} 篇文章"}},
  translate: undefined,
  highlight: {"plugin":"highlight.js","highlightCopy":true,"highlightLang":true,"highlightHeightLimit":false,"highlightFullpage":false,"highlightMacStyle":false},
  copy: {
    success: '复制成功',
    error: '复制失败',
    noSupport: '浏览器不支持'
  },
  relativeDate: {
    homepage: false,
    post: false
  },
  runtime: '',
  dateSuffix: {
    just: '刚刚',
    min: '分钟前',
    hour: '小时前',
    day: '天前',
    month: '个月前'
  },
  copyright: {"limitCount":150,"languages":{"author":"作者: funtim41@gmail.com","link":"链接: ","source":"来源: funtim的博客","info":"著作权归作者所有。商业转载请联系作者获得授权，非商业转载请注明出处。"}},
  lightbox: 'null',
  Snackbar: {"chs_to_cht":"已切换为繁体中文","cht_to_chs":"已切换为简体中文","day_to_night":"已切换为深色模式","night_to_day":"已切换为浅色模式","bgLight":"#49b1f5","bgDark":"#1f1f1f","position":"bottom-left"},
  infinitegrid: {
    js: 'https://cdn.jsdelivr.net/npm/@egjs/infinitegrid/dist/infinitegrid.min.js',
    buttonText: '加载更多'
  },
  isPhotoFigcaption: false,
  islazyload: false,
  isAnchor: true,
  percent: {
    toc: true,
    rightside: true,
  },
  autoDarkmode: false
}</script><script id="config-diff">var GLOBAL_CONFIG_SITE = {
  title: '14族文档',
  isPost: true,
  isHome: false,
  isHighlightShrink: false,
  isToc: true,
  isShuoshuo: false
}</script><link rel="stylesheet" href="/css/bar.css"><meta name="generator" content="Hexo 7.3.0"></head><body><div id="web_bg" style="background: Color(#995a82);"></div><div id="sidebar"><div id="menu-mask"></div><div id="sidebar-menus"><div class="avatar-img text-center"><img src="/images/4stars.png" onerror="onerror=null;src='/img/friend_404.gif'" alt="avatar"/></div><div class="site-data text-center"><a href="/archives/"><div class="headline">文章</div><div class="length-num">58</div></a><a href="/tags/"><div class="headline">标签</div><div class="length-num">5</div></a><a href="/categories/"><div class="headline">分类</div><div class="length-num">7</div></a></div><div class="menus_items"><div class="menus_item"><a class="site-page" href="/"><i class="fa-fw fas fa-home"></i><span> Home</span></a></div><div class="menus_item"><a class="site-page" href="/archives/"><i class="fa-fw fas fa-archive"></i><span> Timeline</span></a></div><div class="menus_item"><a class="site-page" href="/tags/"><i class="fa-fw fas fa-tags"></i><span> Tags</span></a></div><div class="menus_item"><a class="site-page" href="/categories/"><i class="fa-fw fas fa-folder-open"></i><span> Categories</span></a></div><div class="menus_item"><a class="site-page" href="/Links/"><i class="fa-fw fas fa-link"></i><span> Links</span></a></div><div class="menus_item"><a class="site-page" href="/about/"><i class="fa-fw fas fa-heart"></i><span> About</span></a></div></div></div></div><div class="post" id="body-wrap"><header class="post-bg fixed" id="page-header" style="background-image: url(/images/topback.jpg);"><nav id="nav"><span id="blog-info"><a class="nav-site-title" href="/"><img class="site-icon" src="/images/OIP.jfif" alt="Logo"><span class="site-name">funtim的博客</span></a><a class="nav-page-title" href="/"><span class="site-name">14族文档</span></a></span><div id="menus"><div id="search-button"><span class="site-page social-icon search"><i class="fas fa-search fa-fw"></i><span> 搜索</span></span></div><div class="menus_items"><div class="menus_item"><a class="site-page" href="/"><i class="fa-fw fas fa-home"></i><span> Home</span></a></div><div class="menus_item"><a class="site-page" href="/archives/"><i class="fa-fw fas fa-archive"></i><span> Timeline</span></a></div><div class="menus_item"><a class="site-page" href="/tags/"><i class="fa-fw fas fa-tags"></i><span> Tags</span></a></div><div class="menus_item"><a class="site-page" href="/categories/"><i class="fa-fw fas fa-folder-open"></i><span> Categories</span></a></div><div class="menus_item"><a class="site-page" href="/Links/"><i class="fa-fw fas fa-link"></i><span> Links</span></a></div><div class="menus_item"><a class="site-page" href="/about/"><i class="fa-fw fas fa-heart"></i><span> About</span></a></div></div><div id="toggle-menu"><span class="site-page"><i class="fas fa-bars fa-fw"></i></span></div></div></nav><div id="post-info"><h1 class="post-title">14族文档</h1><div id="post-meta"><div class="meta-firstline"><span class="post-meta-date"><i class="far fa-calendar-alt fa-fw post-meta-icon"></i><span class="post-meta-label">发表于</span><time class="post-meta-date-created" datetime="2024-11-29T07:34:57.000Z" title="发表于 2024-11-29 15:34:57">2024-11-29</time><span class="post-meta-separator">|</span><i class="fas fa-history fa-fw post-meta-icon"></i><span class="post-meta-label">更新于</span><time class="post-meta-date-updated" datetime="2025-01-13T14:20:11.477Z" title="更新于 2025-01-13 22:20:11">2025-01-13</time></span><span class="post-meta-categories"><span class="post-meta-separator">|</span><i class="fas fa-inbox fa-fw post-meta-icon"></i><a class="post-meta-categories" href="/categories/Revit%E4%BA%8C%E6%AC%A1%E5%BC%80%E5%8F%91%E4%BA%BA%E5%91%98%E6%8C%87%E5%8D%97/">Revit二次开发人员指南</a></span></div><div class="meta-secondline"><span class="post-meta-separator">|</span><span class="post-meta-pv-cv" id="" data-flag-title=""><i class="far fa-eye fa-fw post-meta-icon"></i><span class="post-meta-label">浏览量:</span><span id="busuanzi_value_page_pv"><i class="fa-solid fa-spinner fa-spin"></i></span></span></div></div></div></header><main class="layout" id="content-inner"><div id="post"><article class="container post-content" id="article-container"><h1 id="族文档"><a href="#族文档" class="headerlink" title="族文档"></a><a target="_blank" rel="noopener" href="https://help.autodesk.com/view/RVT/2018/ENU/?guid=Revit_API_Revit_API_Developers_Guide_Revit_Geometric_Elements_Family_Documents_html">族文档</a></h1><p>本节讨论族以及如何：</p>
<ul>
<li>创建和修改族文档</li>
<li>访问族类型和参数</li>
</ul>
<p>本节中的页面</p>
<ul>
<li>关于族文档</li>
<li>在族中创建图元</li>
<li>族元素的可见性</li>
<li>管理族类型和参数</li>
</ul>
<h2 id="关于族文档"><a href="#关于族文档" class="headerlink" title="关于族文档"></a>关于族文档</h2><h3 id="族"><a href="#族" class="headerlink" title="族"></a>族</h3><p>族对象表示整个Revit族。族文档是表示族的文档(rfa)而不是Revit项目。</p>
<p>使用Revit API的族创建功能，可以创建和编辑族及其类型。当您有来自外部系统的现有数据并希望将其转换为Revit族库时，此功能特别有用。</p>
<p>对系统族编辑的API访问不可用。</p>
<h3 id="类别"><a href="#类别" class="headerlink" title="类别"></a>类别</h3><p>如前一节所述，Family.FamilyCategory属性指示族的类别，如柱、家具、结构框架或窗。</p>
<p>以下代码可用于确定打开的Revit族文档中族的类别。</p>
<figure class="highlight c#"><table><tr><td class="gutter"><pre><span class="line">1</span><br></pre></td><td class="code"><pre><span class="line"><span class="built_in">string</span> categoryName = familyDoc.OwnerFamily.FamilyCategory.Name;</span><br></pre></td></tr></table></figure>

<p>还可以设置FamilyCategory，以允许更改正在编辑的族的类别。</p>
<p> <strong>参数设置</strong> 可以从族文档的OwnerFamily属性访问族参数，如下例所示。</p>
<p>代码区域13-2：打开的Revit族文档的类别</p>
<figure class="highlight c#"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br></pre></td><td class="code"><pre><span class="line"><span class="comment">// get the owner family of the family document.</span></span><br><span class="line">Family family = familyDoc.OwnerFamily; </span><br><span class="line">Parameter param = family.get_Parameter(BuiltInParameter.FAMILY_WORK_PLANE_BASED);</span><br><span class="line"><span class="comment">// this param is a Yes/No parameter in UI, but an integer value in API</span></span><br><span class="line"><span class="comment">// 1 for true and 0 for false</span></span><br><span class="line"><span class="built_in">int</span> isTrue = param.AsInteger(); </span><br><span class="line"><span class="comment">// param.Set(1); // set value to true.</span></span><br></pre></td></tr></table></figure>

<h3 id="创建族文档"><a href="#创建族文档" class="headerlink" title="创建族文档"></a>创建族文档</h3><p>如果文档是族文档（由IsFamilyDocument属性确定），则可以通过Document类修改Revit族文档并访问族类型和参数。若要在处理Project文档时编辑现有族，请使用Document类中提供的EditFamily（）函数，然后在编辑完成后使用LoadFamily（）将族重新加载回所有者文档。要创建新的族文档，请使用Application.NewFamilyDocument（）：</p>
<p>代码区域13-3：创建新的族文档</p>
<figure class="highlight c#"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br></pre></td><td class="code"><pre><span class="line"><span class="comment">// create a new family document using Generic Model.rft template</span></span><br><span class="line"><span class="built_in">string</span> templateFileName = <span class="string">@&quot;C:\Documents and Settings\All Users\Application Data\Autodesk\RST 2011\Imperial Templates\Generic Model.rft&quot;</span>;</span><br><span class="line"></span><br><span class="line">Document familyDocument = application.NewFamilyDocument(templateFileName);</span><br><span class="line"><span class="keyword">if</span> (<span class="literal">null</span> == familyDocument)</span><br><span class="line">&#123;</span><br><span class="line">        <span class="keyword">throw</span> <span class="keyword">new</span> Exception(<span class="string">&quot;Cannot open family document&quot;</span>);</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<h3 id="嵌套族符号"><a href="#嵌套族符号" class="headerlink" title="嵌套族符号"></a>嵌套族符号</h3><p>可以过滤FamilySymbols的族文档，以将所有FamilySymbols加载到族中。在此代码示例中，列出了给定FamilyInstance的族中的所有嵌套FamilySymbol。</p>
<p>代码区域13-4：在族中获取嵌套的族符号</p>
<figure class="highlight c#"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br><span class="line">23</span><br><span class="line">24</span><br><span class="line">25</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="keyword">public</span> <span class="keyword">void</span> <span class="title">GetLoadedSymbols</span>(<span class="params">Autodesk.Revit.DB.Document document, FamilyInstance familyInstance</span>)</span></span><br><span class="line">&#123;</span><br><span class="line">        <span class="keyword">if</span> (<span class="literal">null</span> != familyInstance.Symbol)</span><br><span class="line">        &#123;</span><br><span class="line">                <span class="comment">// Get family associated with this</span></span><br><span class="line">                Family family = familyInstance.Symbol.Family;</span><br><span class="line"></span><br><span class="line">                <span class="comment">// Get Family document for family</span></span><br><span class="line">                Document familyDoc = document.EditFamily(family);</span><br><span class="line">                <span class="keyword">if</span> (<span class="literal">null</span> != familyDoc &amp;&amp; familyDoc.IsFamilyDocument == <span class="literal">true</span>)</span><br><span class="line">                &#123;</span><br><span class="line">                        String loadedFamilies = <span class="string">&quot;FamilySymbols in &quot;</span> + family.Name + <span class="string">&quot;:\n&quot;</span>;</span><br><span class="line">                        FilteredElementCollector collector = <span class="keyword">new</span> FilteredElementCollector(document);</span><br><span class="line">                        ICollection collection = </span><br><span class="line">                                collector.OfClass(<span class="keyword">typeof</span>(FamilySymbol)).ToElements();</span><br><span class="line">                        <span class="keyword">foreach</span> (Element e <span class="keyword">in</span> collection)</span><br><span class="line">                        &#123;</span><br><span class="line">                                FamilySymbol fs = e <span class="keyword">as</span> FamilySymbol;</span><br><span class="line">                                loadedFamilies += <span class="string">&quot;\t&quot;</span> + fs.Name + <span class="string">&quot;\n&quot;</span>;</span><br><span class="line">                        &#125;</span><br><span class="line"></span><br><span class="line">                        TaskDialog.Show(<span class="string">&quot;Revit&quot;</span>,loadedFamilies);</span><br><span class="line">                &#125;</span><br><span class="line">        &#125;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<h2 id="在族中创建元素"><a href="#在族中创建元素" class="headerlink" title="在族中创建元素"></a>在族中创建元素</h2><p>FamilyItemFactory类提供了在族文档中创建图元的功能。可以通过Document.FamilyCreate属性访问它。FamilyItemFactory派生自ItemFactoryBase类，该类是一个实用的用于在Revit项目文档和族文档中创建元素。</p>
<p> 本节中的页面</p>
<ul>
<li>创建表单元素</li>
<li>创建注释</li>
</ul>
<h3 id="创建形状元素"><a href="#创建形状元素" class="headerlink" title="创建形状元素"></a>创建形状元素</h3><p>FamilyItemFactory类提供了在族中创建形状图元的功能，例如拉伸、旋转、放样和融合。有关这些3D草图表格的更多信息，请参见3D草图部分。</p>
<p>下面的示例演示如何创建新的Extrusion元素。它将创建一个简单的矩形截面轮廓，然后将新创建的“拉伸”移动到新位置。</p>
<p>代码区域：创建新拉伸</p>
<figure class="highlight c#"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br><span class="line">23</span><br><span class="line">24</span><br><span class="line">25</span><br><span class="line">26</span><br><span class="line">27</span><br><span class="line">28</span><br><span class="line">29</span><br><span class="line">30</span><br><span class="line">31</span><br><span class="line">32</span><br><span class="line">33</span><br><span class="line">34</span><br><span class="line">35</span><br><span class="line">36</span><br><span class="line">37</span><br><span class="line">38</span><br><span class="line">39</span><br><span class="line">40</span><br><span class="line">41</span><br><span class="line">42</span><br><span class="line">43</span><br><span class="line">44</span><br><span class="line">45</span><br><span class="line">46</span><br><span class="line">47</span><br><span class="line">48</span><br><span class="line">49</span><br><span class="line">50</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="keyword">private</span> Extrusion <span class="title">CreateExtrusion</span>(<span class="params">Autodesk.Revit.DB.Document document, SketchPlane sketchPlane</span>)</span></span><br><span class="line">&#123;</span><br><span class="line">    Extrusion rectExtrusion = <span class="literal">null</span>;</span><br><span class="line"></span><br><span class="line">    <span class="comment">// make sure we have a family document</span></span><br><span class="line">    <span class="keyword">if</span> (<span class="literal">true</span> == document.IsFamilyDocument)</span><br><span class="line">    &#123;</span><br><span class="line">        <span class="comment">// define the profile for the extrusion</span></span><br><span class="line">        CurveArrArray curveArrArray = <span class="keyword">new</span> CurveArrArray();</span><br><span class="line">        CurveArray curveArray1 = <span class="keyword">new</span> CurveArray();</span><br><span class="line">        CurveArray curveArray2 = <span class="keyword">new</span> CurveArray();</span><br><span class="line">        CurveArray curveArray3 = <span class="keyword">new</span> CurveArray();</span><br><span class="line"></span><br><span class="line">        <span class="comment">// create a rectangular profile</span></span><br><span class="line">        XYZ p0 = XYZ.Zero;</span><br><span class="line">        XYZ p1 = <span class="keyword">new</span> XYZ(<span class="number">10</span>, <span class="number">0</span>, <span class="number">0</span>);</span><br><span class="line">        XYZ p2 = <span class="keyword">new</span> XYZ(<span class="number">10</span>, <span class="number">10</span>, <span class="number">0</span>);</span><br><span class="line">        XYZ p3 = <span class="keyword">new</span> XYZ(<span class="number">0</span>, <span class="number">10</span>, <span class="number">0</span>);</span><br><span class="line">        Line line1 = Line.CreateBound(p0, p1);</span><br><span class="line">        Line line2 = Line.CreateBound(p1, p2);</span><br><span class="line">        Line line3 = Line.CreateBound(p2, p3);</span><br><span class="line">        Line line4 = Line.CreateBound(p3, p0);</span><br><span class="line">        curveArray1.Append(line1);</span><br><span class="line">        curveArray1.Append(line2);</span><br><span class="line">        curveArray1.Append(line3);</span><br><span class="line">        curveArray1.Append(line4);</span><br><span class="line"></span><br><span class="line">        curveArrArray.Append(curveArray1);</span><br><span class="line"></span><br><span class="line">        <span class="comment">// create solid rectangular extrusion</span></span><br><span class="line">        rectExtrusion = document.FamilyCreate.NewExtrusion(<span class="literal">true</span>, curveArrArray, sketchPlane, <span class="number">10</span>);</span><br><span class="line"></span><br><span class="line">        <span class="keyword">if</span> (<span class="literal">null</span> != rectExtrusion)</span><br><span class="line">        &#123;</span><br><span class="line">            <span class="comment">// move extrusion to proper place</span></span><br><span class="line">            XYZ transPoint1 = <span class="keyword">new</span> XYZ(<span class="number">-16</span>, <span class="number">0</span>, <span class="number">0</span>);</span><br><span class="line">            ElementTransformUtils.MoveElement(document, rectExtrusion.Id, transPoint1);</span><br><span class="line">        &#125;</span><br><span class="line">        <span class="keyword">else</span></span><br><span class="line">        &#123;</span><br><span class="line">            <span class="keyword">throw</span> <span class="keyword">new</span> Exception(<span class="string">&quot;Create new Extrusion failed.&quot;</span>);</span><br><span class="line">        &#125;</span><br><span class="line">    &#125;</span><br><span class="line">    <span class="keyword">else</span></span><br><span class="line">    &#123;</span><br><span class="line">        <span class="keyword">throw</span> <span class="keyword">new</span> Exception(<span class="string">&quot;Please open a Family document before invoking this command.&quot;</span>);</span><br><span class="line">    &#125;</span><br><span class="line"></span><br><span class="line">    <span class="keyword">return</span> rectExtrusion;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<p>以下示例显示了如何从族文档中的实心卵形轮廓创建新放样。</p>
<p>代码区域：创建新放样</p>
<figure class="highlight c#"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br><span class="line">23</span><br><span class="line">24</span><br><span class="line">25</span><br><span class="line">26</span><br><span class="line">27</span><br><span class="line">28</span><br><span class="line">29</span><br><span class="line">30</span><br><span class="line">31</span><br><span class="line">32</span><br><span class="line">33</span><br><span class="line">34</span><br><span class="line">35</span><br><span class="line">36</span><br><span class="line">37</span><br><span class="line">38</span><br><span class="line">39</span><br><span class="line">40</span><br><span class="line">41</span><br><span class="line">42</span><br><span class="line">43</span><br><span class="line">44</span><br><span class="line">45</span><br><span class="line">46</span><br><span class="line">47</span><br><span class="line">48</span><br><span class="line">49</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="keyword">private</span> Sweep <span class="title">CreateSweep</span>(<span class="params">Autodesk.Revit.DB.Document document, SketchPlane sketchPlane</span>)</span></span><br><span class="line">&#123;</span><br><span class="line">    Sweep sweep = <span class="literal">null</span>;</span><br><span class="line"></span><br><span class="line">    <span class="comment">// make sure we have a family document</span></span><br><span class="line">    <span class="keyword">if</span> (<span class="literal">true</span> == document.IsFamilyDocument)</span><br><span class="line">    &#123;</span><br><span class="line">        <span class="comment">// Define a profile for the sweep</span></span><br><span class="line">        CurveArrArray arrarr = <span class="keyword">new</span> CurveArrArray();</span><br><span class="line">        CurveArray arr = <span class="keyword">new</span> CurveArray();</span><br><span class="line"></span><br><span class="line">        <span class="comment">// Create an ovoid profile</span></span><br><span class="line">        XYZ pnt1 = <span class="keyword">new</span> XYZ(<span class="number">0</span>, <span class="number">0</span>, <span class="number">0</span>);</span><br><span class="line">        XYZ pnt2 = <span class="keyword">new</span> XYZ(<span class="number">2</span>, <span class="number">0</span>, <span class="number">0</span>);</span><br><span class="line">        XYZ pnt3 = <span class="keyword">new</span> XYZ(<span class="number">1</span>, <span class="number">1</span>, <span class="number">0</span>);</span><br><span class="line">        arr.Append(Arc.Create(pnt2, <span class="number">1.0</span>d, <span class="number">0.0</span>d, <span class="number">180.0</span>d, XYZ.BasisX, XYZ.BasisY));</span><br><span class="line">        arr.Append(Arc.Create(pnt1, pnt3, pnt2));</span><br><span class="line">        arrarr.Append(arr);</span><br><span class="line">        SweepProfile profile = document.Application.Create.NewCurveLoopsProfile(arrarr);</span><br><span class="line"></span><br><span class="line">        <span class="comment">// Create a path for the sweep</span></span><br><span class="line">        XYZ pnt4 = <span class="keyword">new</span> XYZ(<span class="number">10</span>, <span class="number">0</span>, <span class="number">0</span>);</span><br><span class="line">        XYZ pnt5 = <span class="keyword">new</span> XYZ(<span class="number">0</span>, <span class="number">10</span>, <span class="number">0</span>);</span><br><span class="line">        Curve curve = Line.CreateBound(pnt4, pnt5);</span><br><span class="line"></span><br><span class="line">        CurveArray curves = <span class="keyword">new</span> CurveArray();</span><br><span class="line">        curves.Append(curve);</span><br><span class="line"></span><br><span class="line">        <span class="comment">// create a solid ovoid sweep</span></span><br><span class="line">        sweep = document.FamilyCreate.NewSweep(<span class="literal">true</span>, curves, sketchPlane, profile, <span class="number">0</span>, ProfilePlaneLocation.Start);</span><br><span class="line"></span><br><span class="line">        <span class="keyword">if</span> (<span class="literal">null</span> != sweep)</span><br><span class="line">        &#123;</span><br><span class="line">            <span class="comment">// move to proper place</span></span><br><span class="line">            XYZ transPoint1 = <span class="keyword">new</span> XYZ(<span class="number">11</span>, <span class="number">0</span>, <span class="number">0</span>);</span><br><span class="line">            ElementTransformUtils.MoveElement(document, sweep.Id, transPoint1);</span><br><span class="line">        &#125;</span><br><span class="line">        <span class="keyword">else</span></span><br><span class="line">        &#123;</span><br><span class="line">            <span class="keyword">throw</span> <span class="keyword">new</span> Exception(<span class="string">&quot;Failed to create a new Sweep.&quot;</span>);</span><br><span class="line">        &#125;</span><br><span class="line">    &#125;</span><br><span class="line">    <span class="keyword">else</span></span><br><span class="line">    &#123;</span><br><span class="line">        <span class="keyword">throw</span> <span class="keyword">new</span> Exception(<span class="string">&quot;Please open a Family document before invoking this command.&quot;</span>);</span><br><span class="line">    &#125;</span><br><span class="line"></span><br><span class="line">    <span class="keyword">return</span> sweep;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<p><img src="https://help.autodesk.com/cloudhelp/2018/ENU/Revit-API/images/GUID-169B9078-7508-4982-B10D-333FF97CA345-low.png"></p>
<p>图50：由上一个示例创建的卵形扫描</p>
<p> FreeFormElement类允许创建从输入实体轮廓创建的非参数化几何体。FreeFormElement可以与其他可组合元素一起参与连接和空切割。元素的平面可以在面法线方向上以交互方式和编程方式偏移。</p>
<p>将子类别转换为形状 在族中创建新形状后，可能需要修改形状的子类别。例如，您可能有一个门族，并且希望创建多个门的子类别，并将不同的子类别指定给族中的不同门类型。 下面的示例演示如何创建新的子类别，为其指定材质，然后将该子类别指定给窗体。</p>
<p>代码区域：指定子类别</p>
<figure class="highlight c#"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="keyword">public</span> <span class="keyword">void</span> <span class="title">AssignSubCategory</span>(<span class="params">Document document, GenericForm extrusion</span>)</span></span><br><span class="line">&#123;</span><br><span class="line">    <span class="comment">// create a new subcategory</span></span><br><span class="line">    Category cat = document.OwnerFamily.FamilyCategory;</span><br><span class="line">    Category subCat = document.Settings.Categories.NewSubcategory(cat, <span class="string">&quot;NewSubCat&quot;</span>);</span><br><span class="line"></span><br><span class="line">    <span class="comment">// create a new material and assign it to the subcategory</span></span><br><span class="line">    ElementId materialId = Material.Create(document, <span class="string">&quot;Wood Material&quot;</span>);</span><br><span class="line">    subCat.Material = document.GetElement(materialId) <span class="keyword">as</span> Material;</span><br><span class="line"></span><br><span class="line">    <span class="comment">// assign the subcategory to the element</span></span><br><span class="line">    extrusion.Subcategory = subCat;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<h3 id="创建注释"><a href="#创建注释" class="headerlink" title="创建注释"></a>创建注释</h3><p>还可以在族中创建新注释（例如尺寸标注和ModelText和TextNote对象）以及曲线注释元素（例如SymbolicCurve、ModelCurve和DetailCurve）。有关注释元素的详细信息，请参见注释元素。</p>
<p>此外，还可以添加新路线，并参照确定路线方向的视图和两个几何图形参照。</p>
<p>以下示例演示如何创建新的弧长标注。</p>
<p>代码区域：创建标注</p>
<figure class="highlight c#"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br><span class="line">23</span><br><span class="line">24</span><br><span class="line">25</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="keyword">public</span> Dimension <span class="title">CreateArcDimension</span>(<span class="params">Document document, SketchPlane sketchPlane</span>)</span></span><br><span class="line">&#123;</span><br><span class="line">    Autodesk.Revit.Creation.Application appCreate = document.Application.Create;</span><br><span class="line">    Line gLine1 = Line.CreateBound(<span class="keyword">new</span> XYZ(<span class="number">0</span>, <span class="number">2</span>, <span class="number">0</span>), <span class="keyword">new</span> XYZ(<span class="number">2</span>, <span class="number">2</span>, <span class="number">0</span>));</span><br><span class="line">    Line gLine2 = Line.CreateBound(<span class="keyword">new</span> XYZ(<span class="number">0</span>, <span class="number">2</span>, <span class="number">0</span>), <span class="keyword">new</span> XYZ(<span class="number">2</span>, <span class="number">4</span>, <span class="number">0</span>));</span><br><span class="line">    Arc arctoDim = Arc.Create(<span class="keyword">new</span> XYZ(<span class="number">1</span>, <span class="number">2</span>, <span class="number">0</span>), <span class="keyword">new</span> XYZ(<span class="number">-1</span>, <span class="number">2</span>, <span class="number">0</span>), <span class="keyword">new</span> XYZ(<span class="number">0</span>, <span class="number">3</span>, <span class="number">0</span>));</span><br><span class="line">    Arc arcofDim = Arc.Create(<span class="keyword">new</span> XYZ(<span class="number">0</span>, <span class="number">3</span>, <span class="number">0</span>), <span class="keyword">new</span> XYZ(<span class="number">1</span>, <span class="number">2</span>, <span class="number">0</span>), <span class="keyword">new</span> XYZ(<span class="number">0.8</span>, <span class="number">2.8</span>, <span class="number">0</span>));</span><br><span class="line"></span><br><span class="line">    Autodesk.Revit.Creation.FamilyItemFactory creationFamily = document.FamilyCreate;</span><br><span class="line">    ModelCurve modelCurve1 = creationFamily.NewModelCurve(gLine1, sketchPlane);</span><br><span class="line">    ModelCurve modelCurve2 = creationFamily.NewModelCurve(gLine2, sketchPlane);</span><br><span class="line">    ModelCurve modelCurve3 = creationFamily.NewModelCurve(arctoDim, sketchPlane);</span><br><span class="line">    <span class="comment">//get their reference</span></span><br><span class="line">    Reference ref1 = modelCurve1.GeometryCurve.Reference;</span><br><span class="line">    Reference ref2 = modelCurve2.GeometryCurve.Reference;</span><br><span class="line">    Reference arcRef = modelCurve3.GeometryCurve.Reference;</span><br><span class="line"></span><br><span class="line">    Dimension newArcDim = creationFamily.NewArcLengthDimension(document.ActiveView, arcofDim, arcRef, ref1, ref2);</span><br><span class="line">    <span class="keyword">if</span> (newArcDim == <span class="literal">null</span>)</span><br><span class="line">    &#123;</span><br><span class="line">        <span class="keyword">throw</span> <span class="keyword">new</span> Exception(<span class="string">&quot;Failed to create new arc length dimension.&quot;</span>);</span><br><span class="line">    &#125;</span><br><span class="line"></span><br><span class="line">    <span class="keyword">return</span> newArcDim;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<p><img src="https://help.autodesk.com/cloudhelp/2018/ENU/Revit-API/images/GUID-813DEE5B-AD67-4892-934A-EF192F72A5BB-low.png"></p>
<p>图51：产生的弧长尺寸</p>
<p>某些类型的尺寸标注可以使用FamilyParameter进行标记。如果尝试获取或设置Label属性，则无法标记的尺寸标注将引发Autodesk.Revit. Revit.InvalidOperationException。在下面的示例中，在两条线之间创建了一个新的线性尺寸标注，并将其标记为“width”。</p>
<p>代码区域：标注尺寸</p>
<figure class="highlight c#"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br><span class="line">23</span><br><span class="line">24</span><br><span class="line">25</span><br><span class="line">26</span><br><span class="line">27</span><br><span class="line">28</span><br><span class="line">29</span><br><span class="line">30</span><br><span class="line">31</span><br><span class="line">32</span><br><span class="line">33</span><br><span class="line">34</span><br><span class="line">35</span><br><span class="line">36</span><br><span class="line">37</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="keyword">public</span> Dimension <span class="title">CreateLinearDimension</span>(<span class="params">Document document</span>)</span></span><br><span class="line">&#123;</span><br><span class="line">    <span class="comment">// first create two lines</span></span><br><span class="line">    XYZ pt1 = <span class="keyword">new</span> XYZ(<span class="number">5</span>, <span class="number">5</span>, <span class="number">0</span>);</span><br><span class="line">    XYZ pt2 = <span class="keyword">new</span> XYZ(<span class="number">5</span>, <span class="number">10</span>, <span class="number">0</span>);</span><br><span class="line">    Line line = Line.CreateBound(pt1, pt2);</span><br><span class="line">    Plane plane = Plane.CreateByNormalAndOrigin(pt1.CrossProduct(pt2), pt2);</span><br><span class="line">    SketchPlane skplane = SketchPlane.Create (document, plane);</span><br><span class="line">    ModelCurve modelcurve1 = document.FamilyCreate.NewModelCurve(line, skplane);</span><br><span class="line"></span><br><span class="line">    pt1 = <span class="keyword">new</span> XYZ(<span class="number">10</span>, <span class="number">5</span>, <span class="number">0</span>);</span><br><span class="line">    pt2 = <span class="keyword">new</span> XYZ(<span class="number">10</span>, <span class="number">10</span>, <span class="number">0</span>);</span><br><span class="line">    line = Line.CreateBound(pt1, pt2);</span><br><span class="line">    plane = Plane.CreateByNormalAndOrigin(pt1.CrossProduct(pt2), pt2);</span><br><span class="line">    skplane = SketchPlane.Create (document, plane);</span><br><span class="line">    ModelCurve modelcurve2 = document.FamilyCreate.NewModelCurve(line, skplane);</span><br><span class="line"></span><br><span class="line">    <span class="comment">// now create a linear dimension between them</span></span><br><span class="line">    ReferenceArray ra = <span class="keyword">new</span> ReferenceArray();</span><br><span class="line">    ra.Append(modelcurve1.GeometryCurve.Reference);</span><br><span class="line">    ra.Append(modelcurve2.GeometryCurve.Reference);</span><br><span class="line"></span><br><span class="line">    pt1 = <span class="keyword">new</span> XYZ(<span class="number">5</span>, <span class="number">10</span>, <span class="number">0</span>);</span><br><span class="line">    pt2 = <span class="keyword">new</span> XYZ(<span class="number">10</span>, <span class="number">10</span>, <span class="number">0</span>);</span><br><span class="line">    line = Line.CreateBound(pt1, pt2);</span><br><span class="line"></span><br><span class="line">    Dimension dim = document.FamilyCreate.NewLinearDimension(document.ActiveView, line, ra);</span><br><span class="line"></span><br><span class="line">    <span class="comment">// create a label for the dimension called &quot;width&quot;</span></span><br><span class="line">    FamilyParameter param = document.FamilyManager.AddParameter(<span class="string">&quot;width&quot;</span>, </span><br><span class="line">        BuiltInParameterGroup.PG_CONSTRAINTS, </span><br><span class="line">        ParameterType.Length, <span class="literal">false</span>);</span><br><span class="line"></span><br><span class="line">    dim.FamilyLabel = param;</span><br><span class="line"></span><br><span class="line">    <span class="keyword">return</span> dim;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<p><img src="https://help.autodesk.com/cloudhelp/2018/ENU/Revit-API/images/GUID-802D577E-3791-4286-A288-0B7858C6459C-low.png"></p>
<p>图52：标记的线性尺寸</p>
<h2 id="族元素的可见性"><a href="#族元素的可见性" class="headerlink" title="族元素的可见性"></a>族元素的可见性</h2><p>FamilyElementVisibility类可用于控制族图元在项目文档中的可见性。例如，如果有门族，则可能只希望门开启方向在放置门的项目文档的平面视图中可见，而在三维视图中不可见。通过设置门开启方向的可见性，您可以控制其可见性。FamilyElementVisibility适用于以下具有SetVisibility（）函数的族图元类：</p>
<ul>
<li>GenericForm</li>
<li>SymbolicCurve</li>
<li>ModelText </li>
<li>CurveByPoints</li>
<li>ModelCurve </li>
<li>ReferencePoint </li>
<li>ImportInstance</li>
</ul>
<p>在下面的示例中，生成的族文档将显示文本“Hello World”，其下有一条线。当族载入到Revit项目文档中并放置实例时，在平面视图中，只有该线可见。在3D视图中，将同时显示线条和文本，除非将“详细程度”设置为“粗”，在这种情况下，线条将消失。</p>
<p>代码区域13-10：设置族图元可见性</p>
<figure class="highlight c#"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br><span class="line">23</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="keyword">public</span> <span class="keyword">void</span> <span class="title">CreateAndSetVisibility</span>(<span class="params">Autodesk.Revit.DB.Document familyDocument, SketchPlane sketchPlane</span>)</span></span><br><span class="line">&#123;</span><br><span class="line">    <span class="comment">// create a new ModelCurve in the family document</span></span><br><span class="line">    XYZ p0 = <span class="keyword">new</span> XYZ(<span class="number">1</span>, <span class="number">1</span>, <span class="number">0</span>);</span><br><span class="line">    XYZ p1 = <span class="keyword">new</span> XYZ(<span class="number">5</span>, <span class="number">1</span>, <span class="number">0</span>);</span><br><span class="line">    Line line1 = Line.CreateBound(p0, p1);</span><br><span class="line"></span><br><span class="line">    ModelCurve modelCurve1 = familyDocument.FamilyCreate.NewModelCurve(line1, sketchPlane);</span><br><span class="line"></span><br><span class="line">    <span class="comment">// create a new ModelText along ModelCurve line</span></span><br><span class="line">    ModelText text = familyDocument.FamilyCreate.NewModelText(<span class="string">&quot;Hello World&quot;</span>, <span class="literal">null</span>, sketchPlane, p0, HorizontalAlign.Center, <span class="number">0.1</span>);</span><br><span class="line"></span><br><span class="line">    <span class="comment">// set visibility for text</span></span><br><span class="line">    FamilyElementVisibility textVisibility = <span class="keyword">new</span> FamilyElementVisibility(FamilyElementVisibilityType.Model);</span><br><span class="line">    textVisibility.IsShownInTopBottom = <span class="literal">false</span>;</span><br><span class="line">    text.SetVisibility(textVisibility);</span><br><span class="line"></span><br><span class="line">    <span class="comment">// set visibility for line</span></span><br><span class="line">    FamilyElementVisibility curveVisibility = <span class="keyword">new</span> FamilyElementVisibility(FamilyElementVisibilityType.Model);</span><br><span class="line">    curveVisibility.IsShownInCoarse = <span class="literal">false</span>;</span><br><span class="line">    modelCurve1.SetVisibility(curveVisibility);</span><br><span class="line"></span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<h2 id="管理族类型和参数"><a href="#管理族类型和参数" class="headerlink" title="管理族类型和参数"></a>管理族类型和参数</h2><p>族文档提供对FamilyManager属性的访问。FamilyManager类提供对族类型和参数的访问。使用此类，可以添加和删除类型、添加和删除族参数和共享参数、设置不同族类型中的参数值以及定义公式来驱动参数值。</p>
<p><strong>在族中获取种类</strong></p>
<p>FamilyManager可用于遍历族中的种类，如下例所示。</p>
<p>代码区域13-11：获取族中的种类</p>
<figure class="highlight c#"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="keyword">public</span> <span class="keyword">void</span> <span class="title">GetFamilyTypesInFamily</span>(<span class="params">Document familyDoc</span>)</span></span><br><span class="line">&#123;</span><br><span class="line">    <span class="keyword">if</span> (familyDoc.IsFamilyDocument)</span><br><span class="line">    &#123;</span><br><span class="line">        FamilyManager familyManager = familyDoc.FamilyManager;</span><br><span class="line"></span><br><span class="line">        <span class="comment">// get types in family</span></span><br><span class="line">        <span class="built_in">string</span> types = <span class="string">&quot;Family Types: &quot;</span>;</span><br><span class="line">        FamilyTypeSet familyTypes = familyManager.Types;</span><br><span class="line">        FamilyTypeSetIterator familyTypesItor = familyTypes.ForwardIterator();</span><br><span class="line">        familyTypesItor.Reset();</span><br><span class="line">        <span class="keyword">while</span> (familyTypesItor.MoveNext())</span><br><span class="line">        &#123;</span><br><span class="line">            FamilyType familyType = familyTypesItor.Current <span class="keyword">as</span> FamilyType;</span><br><span class="line">            types += <span class="string">&quot;\n&quot;</span> + familyType.Name;</span><br><span class="line">        &#125;</span><br><span class="line">        TaskDialog.Show(<span class="string">&quot;Revit&quot;</span>,types);</span><br><span class="line">    &#125;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<p><img src="https://help.autodesk.com/cloudhelp/2018/ENU/Revit-API/images/GUID-60AB2EDC-BC4E-4E08-8922-38ECF4B7F991-low.png"></p>
<p>图53：混凝土矩形柱族中的族种类</p>
<p><strong>编辑族种类</strong></p>
<p>FamilyManager提供了遍历族中现有种类以及添加和修改种类及其参数的功能。</p>
<p>下面的示例演示如何添加新种类（familysymbol），设置其参数，然后将新种类分配给FamilyInstance。种类编辑是通过使用Set（）函数在当前种类上完成的。当前种类可从CurrentType属性获得。CurrentType属性可用于在编辑之前设置当前种类，或使用NewType（）函数创建新种类并将其设置为当前种类以进行编辑。</p>
<p>请注意，一旦创建并修改了新种类，就会使用Document.LoadFamily（）将族重新载入到Revit项目中，以使新种类可用。</p>
<p>代码区域13-12：编辑族类型</p>
<figure class="highlight c#"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br><span class="line">23</span><br><span class="line">24</span><br><span class="line">25</span><br><span class="line">26</span><br><span class="line">27</span><br><span class="line">28</span><br><span class="line">29</span><br><span class="line">30</span><br><span class="line">31</span><br><span class="line">32</span><br><span class="line">33</span><br><span class="line">34</span><br><span class="line">35</span><br><span class="line">36</span><br><span class="line">37</span><br><span class="line">38</span><br><span class="line">39</span><br><span class="line">40</span><br><span class="line">41</span><br><span class="line">42</span><br><span class="line">43</span><br><span class="line">44</span><br><span class="line">45</span><br><span class="line">46</span><br><span class="line">47</span><br><span class="line">48</span><br><span class="line">49</span><br><span class="line">50</span><br><span class="line">51</span><br><span class="line">52</span><br><span class="line">53</span><br><span class="line">54</span><br><span class="line">55</span><br><span class="line">56</span><br><span class="line">57</span><br><span class="line">58</span><br><span class="line">59</span><br><span class="line">60</span><br><span class="line">61</span><br><span class="line">62</span><br><span class="line">63</span><br><span class="line">64</span><br><span class="line">65</span><br><span class="line">66</span><br><span class="line">67</span><br><span class="line">68</span><br><span class="line">69</span><br><span class="line">70</span><br><span class="line">71</span><br><span class="line">72</span><br><span class="line">73</span><br><span class="line">74</span><br><span class="line">75</span><br><span class="line">76</span><br><span class="line">77</span><br><span class="line">78</span><br><span class="line">79</span><br><span class="line">80</span><br><span class="line">81</span><br><span class="line">82</span><br><span class="line">83</span><br><span class="line">84</span><br><span class="line">85</span><br><span class="line">86</span><br><span class="line">87</span><br><span class="line">88</span><br><span class="line">89</span><br><span class="line">90</span><br><span class="line">91</span><br><span class="line">92</span><br><span class="line">93</span><br><span class="line">94</span><br><span class="line">95</span><br><span class="line">96</span><br><span class="line">97</span><br><span class="line">98</span><br><span class="line">99</span><br><span class="line">100</span><br><span class="line">101</span><br><span class="line">102</span><br><span class="line">103</span><br><span class="line">104</span><br><span class="line">105</span><br><span class="line">106</span><br><span class="line">107</span><br><span class="line">108</span><br><span class="line">109</span><br><span class="line">110</span><br><span class="line">111</span><br><span class="line">112</span><br><span class="line">113</span><br><span class="line">114</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="keyword">public</span> <span class="keyword">void</span> <span class="title">EditFamilyTypes</span>(<span class="params">Document document, FamilyInstance familyInstance</span>)</span></span><br><span class="line">&#123;</span><br><span class="line">    <span class="comment">// example works best when familyInstance is a rectangular concrete element</span></span><br><span class="line"></span><br><span class="line">    <span class="keyword">if</span> ((<span class="literal">null</span> == document) || (<span class="literal">null</span> == familyInstance.Symbol))</span><br><span class="line">    &#123;</span><br><span class="line">        <span class="keyword">return</span>;   <span class="comment">// invalid arguments</span></span><br><span class="line">    &#125;</span><br><span class="line"></span><br><span class="line">    <span class="comment">// Get family associated with this</span></span><br><span class="line">    Family family = familyInstance.Symbol.Family;</span><br><span class="line">    <span class="keyword">if</span> (<span class="literal">null</span> == family)</span><br><span class="line">    &#123;</span><br><span class="line">        <span class="keyword">return</span>;    <span class="comment">// could not get the family</span></span><br><span class="line">    &#125;</span><br><span class="line"></span><br><span class="line">    <span class="comment">// Get Family document for family</span></span><br><span class="line">    Document familyDoc = document.EditFamily(family);</span><br><span class="line">    <span class="keyword">if</span> (<span class="literal">null</span> == familyDoc)</span><br><span class="line">    &#123;</span><br><span class="line">        <span class="keyword">return</span>;    <span class="comment">// could not open a family for edit</span></span><br><span class="line">    &#125;</span><br><span class="line"></span><br><span class="line">    FamilyManager familyManager = familyDoc.FamilyManager;</span><br><span class="line">    <span class="keyword">if</span> (<span class="literal">null</span> == familyManager)</span><br><span class="line">    &#123;</span><br><span class="line">        <span class="keyword">return</span>;  <span class="comment">// cuould not get a family manager</span></span><br><span class="line">    &#125;</span><br><span class="line"></span><br><span class="line">    <span class="comment">// Start transaction for the family document</span></span><br><span class="line">    <span class="keyword">using</span> (Transaction newFamilyTypeTransaction = <span class="keyword">new</span> Transaction(familyDoc, <span class="string">&quot;Add Type to Family&quot;</span>))</span><br><span class="line">    &#123;</span><br><span class="line">        <span class="built_in">int</span> changesMade = <span class="number">0</span>;</span><br><span class="line">        newFamilyTypeTransaction.Start();</span><br><span class="line"></span><br><span class="line">        <span class="comment">// add a new type and edit its parameters</span></span><br><span class="line">        FamilyType newFamilyType = familyManager.NewType(<span class="string">&quot;2X2&quot;</span>);</span><br><span class="line"></span><br><span class="line">        <span class="keyword">if</span> (newFamilyType != <span class="literal">null</span>)</span><br><span class="line">        &#123;</span><br><span class="line">            <span class="comment">// look for &#x27;b&#x27; and &#x27;h&#x27; parameters and set them to 2 feet</span></span><br><span class="line">            FamilyParameter familyParam = familyManager.get_Parameter(<span class="string">&quot;宽度&quot;</span>);</span><br><span class="line">            <span class="keyword">if</span> (<span class="literal">null</span> != familyParam)</span><br><span class="line">            &#123;</span><br><span class="line">                familyManager.Set(familyParam, <span class="number">2.0</span>);</span><br><span class="line">                changesMade += <span class="number">1</span>;</span><br><span class="line">            &#125;</span><br><span class="line"></span><br><span class="line">            familyParam = familyManager.get_Parameter(<span class="string">&quot;高度&quot;</span>);</span><br><span class="line">            <span class="keyword">if</span> (<span class="literal">null</span> != familyParam)</span><br><span class="line">            &#123;</span><br><span class="line">                familyManager.Set(familyParam, <span class="number">2.0</span>);</span><br><span class="line">                changesMade += <span class="number">1</span>;</span><br><span class="line">            &#125;</span><br><span class="line">        &#125;</span><br><span class="line"></span><br><span class="line">        <span class="keyword">if</span> (<span class="number">2</span> == changesMade)   <span class="comment">// set both paramaters?</span></span><br><span class="line">        &#123;</span><br><span class="line">            newFamilyTypeTransaction.Commit();</span><br><span class="line">        &#125;</span><br><span class="line">        <span class="keyword">else</span>   <span class="comment">// could not make the change -&gt; should roll back </span></span><br><span class="line">        &#123;</span><br><span class="line">            newFamilyTypeTransaction.RollBack();</span><br><span class="line">        &#125;</span><br><span class="line"></span><br><span class="line">        <span class="comment">// if could not make the change or could not commit it, we return</span></span><br><span class="line">        <span class="keyword">if</span> (newFamilyTypeTransaction.GetStatus() != TransactionStatus.Committed)</span><br><span class="line">        &#123;</span><br><span class="line">            <span class="keyword">return</span>;</span><br><span class="line">        &#125;</span><br><span class="line">    &#125;</span><br><span class="line"></span><br><span class="line">    <span class="comment">// now update the Revit project with Family which has a new type</span></span><br><span class="line">    LoadOpts loadOptions = <span class="keyword">new</span> LoadOpts();</span><br><span class="line"></span><br><span class="line">    <span class="comment">// This overload is necessary for reloading an edited family</span></span><br><span class="line">    <span class="comment">// back into the source document from which it was extracted</span></span><br><span class="line">    family = familyDoc.LoadFamily(document, loadOptions);</span><br><span class="line">    <span class="keyword">if</span> (<span class="literal">null</span> != family)</span><br><span class="line">    &#123;</span><br><span class="line">        <span class="comment">// find the new type and assign it to FamilyInstance</span></span><br><span class="line">        ISet familySymbolIds = family.GetFamilySymbolIds();</span><br><span class="line">        <span class="keyword">foreach</span> (ElementId id <span class="keyword">in</span> familySymbolIds)</span><br><span class="line">        &#123;</span><br><span class="line">            FamilySymbol familySymbol = family.Document.GetElement(id) <span class="keyword">as</span> FamilySymbol;</span><br><span class="line">            <span class="keyword">if</span> ((<span class="literal">null</span> != familySymbol) &amp;&amp; familySymbol.Name == <span class="string">&quot;2X2&quot;</span>)</span><br><span class="line">            &#123;</span><br><span class="line">                <span class="keyword">using</span> (Transaction changeSymbol = <span class="keyword">new</span> Transaction(document, <span class="string">&quot;Change Symbol Assignment&quot;</span>))</span><br><span class="line">                &#123;</span><br><span class="line">                    changeSymbol.Start();</span><br><span class="line">                    familyInstance.Symbol = familySymbol;</span><br><span class="line">                    changeSymbol.Commit();</span><br><span class="line">                &#125;</span><br><span class="line">                <span class="keyword">break</span>;</span><br><span class="line">            &#125;</span><br><span class="line">        &#125;</span><br><span class="line">    &#125;</span><br><span class="line">&#125;</span><br><span class="line"></span><br><span class="line"><span class="keyword">class</span> <span class="title">LoadOpts</span> : <span class="title">IFamilyLoadOptions</span></span><br><span class="line">&#123;</span><br><span class="line">    <span class="function"><span class="keyword">public</span> <span class="built_in">bool</span> <span class="title">OnFamilyFound</span>(<span class="params"><span class="built_in">bool</span> familyInUse, <span class="keyword">out</span> <span class="built_in">bool</span> overwriteParameterValues</span>)</span></span><br><span class="line">    &#123;</span><br><span class="line">        overwriteParameterValues = <span class="literal">true</span>;</span><br><span class="line">        <span class="keyword">return</span> <span class="literal">true</span>;</span><br><span class="line">    &#125;</span><br><span class="line"></span><br><span class="line">    <span class="function"><span class="keyword">public</span> <span class="built_in">bool</span> <span class="title">OnSharedFamilyFound</span>(<span class="params">Family sharedFamily, <span class="built_in">bool</span> familyInUse, <span class="keyword">out</span> FamilySource source, <span class="keyword">out</span> <span class="built_in">bool</span> overwriteParameterValues</span>)</span></span><br><span class="line">    &#123;</span><br><span class="line">        source = FamilySource.Family;</span><br><span class="line">        overwriteParameterValues = <span class="literal">true</span>;</span><br><span class="line">        <span class="keyword">return</span> <span class="literal">true</span>;</span><br><span class="line">    &#125;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<p>FamilyManager类提供对所有族参数的访问。这包括族内置参数、类别内置参数和与族类型关联的共享参数。有两种方法可以获取族参数：</p>
<ul>
<li>Parameters property - 获取族中的所有参数</li>
<li>GetParameters（）-按族中所有参数在Revit UI中出现的顺序获取这些参数使用GetParameters（）方法时，Revit UI顺序首先按组确定，然后按各个参数的顺序确定。</li>
</ul>
<p>可以从给定族的API（不支持重新排序参数的钢筋形状族除外）重新排序（在其组内）族参数。这允许参数以最符合逻辑的顺序呈现给用户。排序仅影响同一参数组中的可见参数。属于不同组的参数将保持分离，并且组的顺序不会受到影响。</p>
<p>对参数重新排序的最简单方法是使用FamilyManager.SortParameters（）方法，该方法接受一个指示所需排序顺序的参数。下面的示例按升序对参数进行排序。</p>
<p>代码区域：对族参数排序</p>
<figure class="highlight c#"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="keyword">private</span> <span class="keyword">void</span> <span class="title">DisplayParametersInAscendingOrder</span>(<span class="params">Document familyDoc</span>)</span></span><br><span class="line">&#123;</span><br><span class="line">    FamilyManager familyManager = familyDoc.FamilyManager;</span><br><span class="line">    familyManager.SortParameters(ParametersOrder.Ascending);</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<p>注意：排序是一次性操作。当添加新参数时，它们不会自动排序。若要对参数的排序方式进行更多控制，请使用FamilyManager.ReorderParameters（）方法，该方法以新顺序接受族参数列表。此列表必须包含GetParameters（）方法返回的所有参数，包括任何不可见的参数，否则将引发异常。</p>
<h2 id="注：翻译自Revit-API-Developers-Guide"><a href="#注：翻译自Revit-API-Developers-Guide" class="headerlink" title="注：翻译自Revit API Developers Guide"></a><em><strong>注：</strong></em>翻译自<a target="_blank" rel="noopener" href="https://help.autodesk.com/view/RVT/2018/ENU/?guid=Revit_API_Revit_API_Developers_Guide_html">Revit API Developers Guide</a></h2></article><div class="tag_share"><div class="post-meta__tag-list"><a class="post-meta__tags" href="/tags/Revit/">Revit</a></div><div class="post-share"><div class="social-share" data-image="/images/4stars.png" data-sites="facebook,twitter,wechat,weibo,qq"></div><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/butterfly-extsrc/sharejs/dist/css/share.min.css" media="print" onload="this.media='all'"><script src="https://cdn.jsdelivr.net/npm/butterfly-extsrc/sharejs/dist/js/social-share.min.js" defer></script></div></div><nav class="pagination-post" id="pagination"><a class="pagination-related" href="/2024/11/29/Revit%E4%BA%8C%E5%BC%80%E6%8C%87%E5%8D%97/28%E5%8F%AF%E6%89%A9%E5%B1%95%E5%82%A8%E5%AD%98/" title="28可扩展储存"><div class="cover" style="background: var(--default-bg-color)"></div><div class="info"><div class="info-1"><div class="info-item-1">上一篇</div><div class="info-item-2">28可扩展储存</div></div><div class="info-2"><div class="info-item-1">在Revit模型中存储数据使用共享参数或可扩展存储在Revit模型中存储数据。 Revit API提供了两种在Revit模型中存储数据的方法。第一种是使用共享参数。通过Revit API，可以通过编程方式访问通过Revit UI提供的相同共享参数功能。如果共享参数被定义为可见，则用户可以在元素的属性窗口中查看这些参数。可以将共享参数指定给许多（但不是所有）类别的图元。有关详细信息，请参阅共享参数。 另一个选项是可扩展存储，它允许您创建自定义数据结构，然后将该数据的实例分配给模型中的元素。用户在Revit UI中永远看不到这些数据，但其他第三方应用程序可以通过Revit...</div></div></div></a><a class="pagination-related" href="/2024/11/26/Revit%E4%BA%8C%E5%BC%80%E6%8C%87%E5%8D%97/05%E8%BF%87%E6%BB%A4/" title="05过滤"><div class="cover" style="background: var(--default-bg-color)"></div><div class="info text-right"><div class="info-1"><div class="info-item-1">下一篇</div><div class="info-item-2">05过滤</div></div><div class="info-2"><div class="info-item-1">Filtering 过滤Revit API提供了一种过滤和迭代Revit文档中图元的机制。这是获取一组相关元素（如文档中的所有墙或门）的最佳方法。过滤器也可以用来找到一个非常具体的元素集，如所有特定大小的梁。 获取通过指定过滤器的元素的基本步骤如下：  创建新的FilteredElementCollector 对它应用一个或多个过滤器 获取过滤后的元素或元素ID（使用以下几种方法之一）  下面的示例涵盖了在文档中筛选和迭代元素的基本步骤。 代码区域6-1：使用元素过滤获取文档中的所有墙实例 1234567891011121314// Find all Wall instances in the document by using category filterElementCategoryFilter filter = new ElementCategoryFilter(BuiltInCategory.OST_Walls);// Apply the filter to the elements in the active document// Use shortcut...</div></div></div></a></nav><div class="relatedPosts"><div class="headline"><i class="fas fa-thumbs-up fa-fw"></i><span>相关推荐</span></div><div class="relatedPosts-list"><a class="pagination-related" href="/2025/01/16/Revit%E4%BA%8C%E5%BC%80%E7%A4%BA%E4%BE%8B/Revit%E4%B8%8EExcel%E4%BA%A4%E4%BA%92/" title="Revit与Excel交互"><div class="cover" style="background: var(--default-bg-color)"></div><div class="info text-center"><div class="info-1"><div class="info-item-1"><i class="far fa-calendar-alt fa-fw"></i> 2025-01-16</div><div class="info-item-2">Revit与Excel交互</div></div><div class="info-2"><div class="info-item-1">  Excel检测更改自动保存，Revit自动读取数据生成元素 </div></div></div></a><a class="pagination-related" href="/2024/12/20/RevitApi%E5%90%88%E9%9B%86/Autodesk.%20Revit.DB%20ElementTransformUtils/" title="Autodesk.Revit.DB ElementTransformUtils"><div class="cover" style="background: var(--default-bg-color)"></div><div class="info text-center"><div class="info-1"><div class="info-item-1"><i class="far fa-calendar-alt fa-fw"></i> 2024-12-20</div><div class="info-item-2">Autodesk.Revit.DB ElementTransformUtils</div></div><div class="info-2"><div class="info-item-1">Autodesk. Revit.DB ElementTransformUtils允许元素转换的实用程序集合（例如移动，旋转，镜像和复制）。 语法1public static class ElementTransformUtils    继承层次结构 System Object Autodesk.Revit.DB ElementTransformUtils   方法CanMirrorElement确定是否可以镜像元素。 CanMirrorElements确定是否可以镜像元素。 CopyElement复制元素并将副本放置在给定转换指示的位置。 CopyElements(Document, ICollection ElementId , XYZ)复制一组元素，并将副本放置在给定指示的位置。 CopyElements(Document, ICollection ElementId , Document, Transform, CopyPasteOptions)将一组元素从源文档复制到目标文档。 CopyElements(View, ICollection ElementId ,...</div></div></div></a><a class="pagination-related" href="/2024/11/18/RevitApi%E5%90%88%E9%9B%86/Autodesk.Revit.DB%20CurveArray/" title="Autodesk.Revit.DB CurveArray"><div class="cover" style="background: var(--default-bg-color)"></div><div class="info text-center"><div class="info-1"><div class="info-item-1"><i class="far fa-calendar-alt fa-fw"></i> 2024-11-18</div><div class="info-item-2">Autodesk.Revit.DB CurveArray</div></div><div class="info-2"><div class="info-item-1">Autodesk.Revit.DB CurveArray可以包含曲线的数组。 语法1public class CurveArray : APIObject, IEnumerable  继承层次结构System Object ​	Autodesk.Revit.DB APIObject ​		Autodesk.Revit.DB CurveArray 另见CurveArray Members Autodesk.Revit.DB Namespace 构造函数CurveArray创建CurveArray类的新实例 方法Append将曲线添加到数组的末尾。 Clear从数组中删除每条曲线，使其为空。 ForwardIterator将一个向前移动的迭代器添加到数组中。 GetEnumerator将一个向前移动的迭代器添加到数组中。 Insert将指定的曲线插入数组。 ReverseIterator返回一个向后移动的迭代器到数组。 属性IsEmpty测试数组是否为空。 Item获取或设置数组中指定索引处的曲线。 Size返回数组中的曲线数。 注：翻译自Revit Api docs 2018</div></div></div></a><a class="pagination-related" href="/2024/10/30/RevitApi%E5%90%88%E9%9B%86/Autodesk.Revit.DB%20Document/" title="Autodesk.Revit.DB Document"><div class="cover" style="background: var(--default-bg-color)"></div><div class="info text-center"><div class="info-1"><div class="info-item-1"><i class="far fa-calendar-alt fa-fw"></i> 2024-10-30</div><div class="info-item-2">Autodesk.Revit.DB Document</div></div><div class="info-2"><div class="info-item-1">Autodesk.Revit.DB Document表示打开的 Autodesk Revit 项目的对象。 语法1public class Document : IDisposable    附注Document 对象表示 Autodesk Revit 项目。Revit 可以打开多个项目，并打开这些项目的多个视图。活动视图或最顶层视图将是活动项目，因此是可从 Application 对象获得的活动文档。 继承层次结构 System Object Autodesk.Revit.DB Document Autodesk.Revit.DB.Macros DocumentEntryPoint  方法AcquireCoordinates 不知道是啥，API没给描述  AutoJoinElements 强制 Revit...</div></div></div></a><a class="pagination-related" href="/2024/12/10/RevitApi%E5%90%88%E9%9B%86/Autodesk.Revit.DB%20Opening/" title="Autodesk.Revit.DB Opening"><div class="cover" style="background: var(--default-bg-color)"></div><div class="info text-center"><div class="info-1"><div class="info-item-1"><i class="far fa-calendar-alt fa-fw"></i> 2024-12-10</div><div class="info-item-2">Autodesk.Revit.DB Opening</div></div><div class="info-2"><div class="info-item-1">Autodesk.Revit.DB OpeningAutodesk Revit项目或族文档中的洞口。 语法1public class Opening : Element  附注该对象表示各种不同类型的洞口：  墙中由修订项目中的两个边界点创建的矩形洞口。 由应用于屋顶、楼板、天花板、梁、支撑或柱的一组曲线创建的洞口。 一个垂直的竖井开口延伸到一个或多个水平。 在族文档中的墙或天花板上创建的简单洞口。  根据打开的类型，此类的某些属性将不可用。 这个对象派生自Element基对象，并且支持该对象的所有方法，例如检索该对象的参数的能力。此对象还支持访问结构分析模型，但此功能仅适用于Autodesk Revit Structure。 示例123456789101112131415161718192021222324252627282930313233343536373839404142434445464748495051### private void Getinfo_Opening(Opening opening)&#123;    string message =...</div></div></div></a><a class="pagination-related" href="/2024/12/19/RevitApi%E5%90%88%E9%9B%86/Autodesk.Revit.UI.Selection%20Namespace/" title="Autodesk.Revit.UI.Selection"><div class="cover" style="background: var(--default-bg-color)"></div><div class="info text-center"><div class="info-1"><div class="info-item-1"><i class="far fa-calendar-alt fa-fw"></i> 2024-12-19</div><div class="info-item-2">Autodesk.Revit.UI.Selection</div></div><div class="info-2"><div class="info-item-1">Autodesk.Revit.UI.SelectionClassesPickedBox包含两个 XYZ 点的类，表示屏幕上的选取框。  Properties  Max 最大坐标数（拾取框的右上角）。  Min 最小坐标（拾取框的左下角）。     SelectableInViewFilter一个过滤器，用于传递在给定视图中可选的元素。  Constructors  SelectableInViewFilter  (Document, ElementId) 构造 SelectableInViewFilter 的新实例。  SelectableInViewFilter (Document, ElementId, Boolean) 构造 SelectableInViewFilter 的新实例，并可选择传递所有不可选择的元素。    Methods  PassesFilter(Element) 将筛选器应用于给定元素。  PassesFilter(Document,...</div></div></div></a></div></div><hr class="custom-hr"/><div id="post-comment"><div class="comment-head"><div class="comment-headline"><i class="fas fa-comments fa-fw"></i><span> 评论</span></div></div><div class="comment-wrap"><div><div id="giscus-wrap"></div></div></div></div></div><div class="aside-content" id="aside-content"><div class="card-widget card-info text-center"><div class="avatar-img"><img src="/images/4stars.png" onerror="this.onerror=null;this.src='/img/friend_404.gif'" alt="avatar"/></div><div class="author-info-name">funtim41@gmail.com</div><div class="author-info-description">实践-认识-再实践-再认识</div><div class="site-data"><a href="/archives/"><div class="headline">文章</div><div class="length-num">58</div></a><a href="/tags/"><div class="headline">标签</div><div class="length-num">5</div></a><a href="/categories/"><div class="headline">分类</div><div class="length-num">7</div></a></div><a id="card-info-btn" target="_blank" rel="noopener" href="https://github.com/FunTim41"><i class="fab fa-github"></i><span>Follow Me</span></a><div class="card-info-social-icons"><a class="social-icon" href="https://github.com/FunTim41" target="_blank" title="Github"><i class="fab fa-github" style="color: #FFFFFF;"></i></a></div></div><div class="card-widget card-announcement"><div class="item-headline"><i class="fas fa-bullhorn fa-shake"></i><span>公告</span></div><div class="announcement_content">This is my Blog</div></div><div class="sticky_layout"><div class="card-widget" id="card-toc"><div class="item-headline"><i class="fas fa-stream"></i><span>目录</span><span class="toc-percentage"></span></div><div class="toc-content"><ol class="toc"><li class="toc-item toc-level-1"><a class="toc-link" href="#%E6%97%8F%E6%96%87%E6%A1%A3"><span class="toc-number">1.</span> <span class="toc-text">族文档</span></a><ol class="toc-child"><li class="toc-item toc-level-2"><a class="toc-link" href="#%E5%85%B3%E4%BA%8E%E6%97%8F%E6%96%87%E6%A1%A3"><span class="toc-number">1.1.</span> <span class="toc-text">关于族文档</span></a><ol class="toc-child"><li class="toc-item toc-level-3"><a class="toc-link" href="#%E6%97%8F"><span class="toc-number">1.1.1.</span> <span class="toc-text">族</span></a></li><li class="toc-item toc-level-3"><a class="toc-link" href="#%E7%B1%BB%E5%88%AB"><span class="toc-number">1.1.2.</span> <span class="toc-text">类别</span></a></li><li class="toc-item toc-level-3"><a class="toc-link" href="#%E5%88%9B%E5%BB%BA%E6%97%8F%E6%96%87%E6%A1%A3"><span class="toc-number">1.1.3.</span> <span class="toc-text">创建族文档</span></a></li><li class="toc-item toc-level-3"><a class="toc-link" href="#%E5%B5%8C%E5%A5%97%E6%97%8F%E7%AC%A6%E5%8F%B7"><span class="toc-number">1.1.4.</span> <span class="toc-text">嵌套族符号</span></a></li></ol></li><li class="toc-item toc-level-2"><a class="toc-link" href="#%E5%9C%A8%E6%97%8F%E4%B8%AD%E5%88%9B%E5%BB%BA%E5%85%83%E7%B4%A0"><span class="toc-number">1.2.</span> <span class="toc-text">在族中创建元素</span></a><ol class="toc-child"><li class="toc-item toc-level-3"><a class="toc-link" href="#%E5%88%9B%E5%BB%BA%E5%BD%A2%E7%8A%B6%E5%85%83%E7%B4%A0"><span class="toc-number">1.2.1.</span> <span class="toc-text">创建形状元素</span></a></li><li class="toc-item toc-level-3"><a class="toc-link" href="#%E5%88%9B%E5%BB%BA%E6%B3%A8%E9%87%8A"><span class="toc-number">1.2.2.</span> <span class="toc-text">创建注释</span></a></li></ol></li><li class="toc-item toc-level-2"><a class="toc-link" href="#%E6%97%8F%E5%85%83%E7%B4%A0%E7%9A%84%E5%8F%AF%E8%A7%81%E6%80%A7"><span class="toc-number">1.3.</span> <span class="toc-text">族元素的可见性</span></a></li><li class="toc-item toc-level-2"><a class="toc-link" href="#%E7%AE%A1%E7%90%86%E6%97%8F%E7%B1%BB%E5%9E%8B%E5%92%8C%E5%8F%82%E6%95%B0"><span class="toc-number">1.4.</span> <span class="toc-text">管理族类型和参数</span></a></li><li class="toc-item toc-level-2"><a class="toc-link" href="#%E6%B3%A8%EF%BC%9A%E7%BF%BB%E8%AF%91%E8%87%AARevit-API-Developers-Guide"><span class="toc-number">1.5.</span> <span class="toc-text">注：翻译自Revit API Developers Guide</span></a></li></ol></li></ol></div></div><div class="card-widget card-recent-post"><div class="item-headline"><i class="fas fa-history"></i><span>最新文章</span></div><div class="aside-list"><div class="aside-list-item no-cover"><div class="content"><a class="title" href="/2025/01/14/ObjectARX%EF%BC%9AManaged.NET%E5%BC%80%E5%8F%91%E4%BA%BA%E5%91%98%E6%8C%87%E5%8D%97/03%E5%88%9B%E5%BB%BA%E5%92%8C%E7%BC%96%E8%BE%91AutoCAD%E5%9B%BE%E5%85%83%EF%BC%88.NET%EF%BC%89/" title="03创建和编辑AutoCAD图元（.NET）">03创建和编辑AutoCAD图元（.NET）</a><time datetime="2025-01-19T03:40:40.285Z" title="更新于 2025-01-19 11:40:40">2025-01-19</time></div></div><div class="aside-list-item no-cover"><div class="content"><a class="title" href="/2025/01/13/ObjectARX%EF%BC%9AManaged.NET%E5%BC%80%E5%8F%91%E4%BA%BA%E5%91%98%E6%8C%87%E5%8D%97/02%E6%8E%A7%E5%88%B6AutoCAD%E7%8E%AF%E5%A2%83%EF%BC%88.NET%EF%BC%89/" title="02控制AutoCAD环境（.NET）">02控制AutoCAD环境（.NET）</a><time datetime="2025-01-17T10:16:52.559Z" title="更新于 2025-01-17 18:16:52">2025-01-17</time></div></div><div class="aside-list-item no-cover"><div class="content"><a class="title" href="/2025/01/12/ObjectARX%EF%BC%9AManaged.NET%E5%BC%80%E5%8F%91%E4%BA%BA%E5%91%98%E6%8C%87%E5%8D%97/01AutoCAD.NET%20API%EF%BC%88.NET%EF%BC%89%E7%9A%84%E5%9F%BA%E7%A1%80%E7%9F%A5%E8%AF%86/" title="01AutoCAD .NET API（.NET）的基础知识">01AutoCAD .NET API（.NET）的基础知识</a><time datetime="2025-01-17T10:16:40.962Z" title="更新于 2025-01-17 18:16:40">2025-01-17</time></div></div><div class="aside-list-item no-cover"><div class="content"><a class="title" href="/2025/01/16/Revit%E4%BA%8C%E5%BC%80%E7%A4%BA%E4%BE%8B/Revit%E4%B8%8EExcel%E4%BA%A4%E4%BA%92/" title="Revit与Excel交互">Revit与Excel交互</a><time datetime="2025-01-16T08:43:45.327Z" title="更新于 2025-01-16 16:43:45">2025-01-16</time></div></div><div class="aside-list-item no-cover"><div class="content"><a class="title" href="/2024/12/19/RevitApi%E5%90%88%E9%9B%86/Autodesk.Revit.UI.Selection%20Namespace/" title="Autodesk.Revit.UI.Selection">Autodesk.Revit.UI.Selection</a><time datetime="2025-01-13T14:24:17.222Z" title="更新于 2025-01-13 22:24:17">2025-01-13</time></div></div></div></div></div></div></main><footer id="footer" style="background-image: url(/images/topback.jpg);"><div id="footer-wrap"><div class="copyright">&copy;2024 - 2025 By funtim41@gmail.com</div><div class="framework-info"><span>框架 </span><a target="_blank" rel="noopener" href="https://hexo.io">Hexo</a><span class="footer-separator">|</span><span>主题 </span><a target="_blank" rel="noopener" href="https://github.com/jerryc127/hexo-theme-butterfly">Butterfly</a></div><div class="footer_custom_text">学而不思则罔，思而不学则殆。</div></div></footer></div><div id="rightside"><div id="rightside-config-hide"><button id="readmode" type="button" title="阅读模式"><i class="fas fa-book-open"></i></button><button id="darkmode" type="button" title="日间和夜间模式切换"><i class="fas fa-adjust"></i></button><button id="hide-aside-btn" type="button" title="单栏和双栏切换"><i class="fas fa-arrows-alt-h"></i></button></div><div id="rightside-config-show"><button id="rightside-config" type="button" title="设置"><i class="fas fa-cog fa-spin"></i></button><button class="close" id="mobile-toc-button" type="button" title="目录"><i class="fas fa-list-ul"></i></button><a id="to_comment" href="#post-comment" title="前往评论"><i class="fas fa-comments"></i></a><button id="go-up" type="button" title="回到顶部"><span class="scroll-percent"></span><i class="fas fa-arrow-up"></i></button></div></div><div><script src="/js/utils.js"></script><script src="/js/main.js"></script><script src="https://cdn.jsdelivr.net/npm/node-snackbar/dist/snackbar.min.js"></script><script>(() => {
  const panguFn = () => {
    if (typeof pangu === 'object') pangu.autoSpacingPage()
    else {
      btf.getScript('https://cdn.jsdelivr.net/npm/pangu/dist/browser/pangu.min.js')
        .then(() => {
          pangu.autoSpacingPage()
        })
    }
  }

  const panguInit = () => {
    if (false){
      GLOBAL_CONFIG_SITE.isPost && panguFn()
    } else {
      panguFn()
    }
  }

  btf.addGlobalFn('pjaxComplete', panguInit, 'pangu')
  document.addEventListener('DOMContentLoaded', panguInit)
})()</script><div class="js-pjax"><script>(() => {
  const isShuoshuo = GLOBAL_CONFIG_SITE.isShuoshuo
  const option = null

  const getGiscusTheme = theme => theme === 'dark' ? 'dark' : 'light'

  const createScriptElement = config => {
    const ele = document.createElement('script')
    Object.entries(config).forEach(([key, value]) => {
      ele.setAttribute(key, value)
    })
    return ele
  }

  const loadGiscus = (el = document, key) => {
    const mappingConfig = isShuoshuo
      ? { 'data-mapping': 'specific', 'data-term': key }
      : { 'data-mapping': (option && option['data-mapping']) || 'pathname' }

    const giscusConfig = {
      src: 'https://giscus.app/client.js',
      'data-repo': 'FunTim41/funtim41.github.io',
      'data-repo-id': 'R_kgDONjG8ww',
      'data-category-id': 'DIC_kwDONjG8w84Cllg2',
      'data-theme': getGiscusTheme(document.documentElement.getAttribute('data-theme')),
      'data-reactions-enabled': '1',
      crossorigin: 'anonymous',
      async: true,
      ...option,
      ...mappingConfig
    }

    const scriptElement = createScriptElement(giscusConfig)

    el.querySelector('#giscus-wrap').appendChild(scriptElement)

    if (isShuoshuo) {
      window.shuoshuoComment.destroyGiscus = () => {
        if (el.children.length) {
          el.innerHTML = ''
          el.classList.add('no-comment')
        }
      }
    }
  }

  const changeGiscusTheme = theme => {
    const iframe = document.querySelector('#giscus-wrap iframe')
    if (iframe) {
      const message = {
        giscus: {
          setConfig: {
            theme: getGiscusTheme(theme)
          }
        }
      }
      iframe.contentWindow.postMessage(message, 'https://giscus.app')
    }
  }

  btf.addGlobalFn('themeChange', changeGiscusTheme, 'giscus')

  if (isShuoshuo) {
    'Giscus' === 'Giscus'
      ? window.shuoshuoComment = { loadComment: loadGiscus }
      : window.loadOtherComment = loadGiscus
    return
  }

  if ('Giscus' === 'Giscus' || !false) {
    if (false) btf.loadComment(document.getElementById('giscus-wrap'), loadGiscus)
    else loadGiscus()
  } else {
    window.loadOtherComment = loadGiscus
  }
})()</script></div><script defer="defer" id="fluttering_ribbon" mobile="false" src="https://cdn.jsdelivr.net/npm/butterfly-extsrc/dist/canvas-fluttering-ribbon.min.js"></script><script async data-pjax src="//busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js"></script><div id="local-search"><div class="search-dialog"><nav class="search-nav"><span class="search-dialog-title">搜索</span><span id="loading-status"></span><button class="search-close-button"><i class="fas fa-times"></i></button></nav><div class="text-center" id="loading-database"><i class="fas fa-spinner fa-pulse"></i><span>  数据加载中</span></div><div class="search-wrap"><div id="local-search-input"><div class="local-search-box"><input class="local-search-box--input" placeholder="搜索文章" type="text"/></div></div><hr/><div id="local-search-results"></div><div id="local-search-stats-wrap"></div></div></div><div id="search-mask"></div><script src="/js/search/local-search.js"></script></div></div></body></html>