<!DOCTYPE html><html lang="zh-CN" data-theme="light"><head><meta charset="UTF-8"><meta http-equiv="X-UA-Compatible" content="IE=edge"><meta name="viewport" content="width=device-width, initial-scale=1.0,viewport-fit=cover"><title>03应用及文档 | funtim的博客</title><meta name="author" content="funtim41@gmail.com"><meta name="copyright" content="funtim41@gmail.com"><meta name="format-detection" content="telephone=no"><meta name="theme-color" content="#ffffff"><meta name="description" content="Application及DocumentRevit 平台 API 中的顶级对象是Application和Document。这些类由 Application、UIApplication、Document 和 UIDocument 类表示。 Application对象是指单个 Revit 任务，提供对文档、选项和其他应用程序范围的数据和设置的访问。 Autodesk.Revit.UI.UIApplic">
<meta property="og:type" content="article">
<meta property="og:title" content="03应用及文档">
<meta property="og:url" content="https://funtim41.github.io/2024/11/26/Revit%E4%BA%8C%E5%BC%80%E6%8C%87%E5%8D%97/03%E5%BA%94%E7%94%A8%E5%8F%8A%E6%96%87%E6%A1%A3/">
<meta property="og:site_name" content="funtim的博客">
<meta property="og:description" content="Application及DocumentRevit 平台 API 中的顶级对象是Application和Document。这些类由 Application、UIApplication、Document 和 UIDocument 类表示。 Application对象是指单个 Revit 任务，提供对文档、选项和其他应用程序范围的数据和设置的访问。 Autodesk.Revit.UI.UIApplic">
<meta property="og:locale" content="zh_CN">
<meta property="og:image" content="https://funtim41.github.io/images/4stars.png">
<meta property="article:published_time" content="2024-11-26T12:11:29.000Z">
<meta property="article:modified_time" content="2025-01-13T14:18:52.714Z">
<meta property="article:author" content="funtim41@gmail.com">
<meta property="article:tag" content="Revit">
<meta name="twitter:card" content="summary">
<meta name="twitter:image" content="https://funtim41.github.io/images/4stars.png"><link rel="shortcut icon" href="/images/OIP.jfif"><link rel="canonical" href="https://funtim41.github.io/2024/11/26/Revit%E4%BA%8C%E5%BC%80%E6%8C%87%E5%8D%97/03%E5%BA%94%E7%94%A8%E5%8F%8A%E6%96%87%E6%A1%A3/"><link rel="preconnect" href="//cdn.jsdelivr.net"/><link rel="stylesheet" href="/css/index.css"><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free/css/all.min.css"><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/node-snackbar/dist/snackbar.min.css" media="print" onload="this.media='all'"><script>
    (() => {
      
    const saveToLocal = {
      set: (key, value, ttl) => {
        if (!ttl) return
        const expiry = Date.now() + ttl * 86400000
        localStorage.setItem(key, JSON.stringify({ value, expiry }))
      },
      get: key => {
        const itemStr = localStorage.getItem(key)
        if (!itemStr) return undefined
        const { value, expiry } = JSON.parse(itemStr)
        if (Date.now() > expiry) {
          localStorage.removeItem(key)
          return undefined
        }
        return value
      }
    }

    window.btf = {
      saveToLocal,
      getScript: (url, attr = {}) => new Promise((resolve, reject) => {
        const script = document.createElement('script')
        script.src = url
        script.async = true
        Object.entries(attr).forEach(([key, val]) => script.setAttribute(key, val))
        script.onload = script.onreadystatechange = () => {
          if (!script.readyState || /loaded|complete/.test(script.readyState)) resolve()
        }
        script.onerror = reject
        document.head.appendChild(script)
      }),
      getCSS: (url, id) => new Promise((resolve, reject) => {
        const link = document.createElement('link')
        link.rel = 'stylesheet'
        link.href = url
        if (id) link.id = id
        link.onload = link.onreadystatechange = () => {
          if (!link.readyState || /loaded|complete/.test(link.readyState)) resolve()
        }
        link.onerror = reject
        document.head.appendChild(link)
      }),
      addGlobalFn: (key, fn, name = false, parent = window) => {
        if (!false && key.startsWith('pjax')) return
        const globalFn = parent.globalFn || {}
        globalFn[key] = globalFn[key] || {}
        globalFn[key][name || Object.keys(globalFn[key]).length] = fn
        parent.globalFn = globalFn
      }
    }
  
      
      const activateDarkMode = () => {
        document.documentElement.setAttribute('data-theme', 'dark')
        if (document.querySelector('meta[name="theme-color"]') !== null) {
          document.querySelector('meta[name="theme-color"]').setAttribute('content', '#0d0d0d')
        }
      }
      const activateLightMode = () => {
        document.documentElement.setAttribute('data-theme', 'light')
        if (document.querySelector('meta[name="theme-color"]') !== null) {
          document.querySelector('meta[name="theme-color"]').setAttribute('content', '#ffffff')
        }
      }

      btf.activateDarkMode = activateDarkMode
      btf.activateLightMode = activateLightMode

      const theme = saveToLocal.get('theme')
    
          theme === 'dark' ? activateDarkMode() : theme === 'light' ? activateLightMode() : null
        
      
      const asideStatus = saveToLocal.get('aside-status')
      if (asideStatus !== undefined) {
        document.documentElement.classList.toggle('hide-aside', asideStatus === 'hide')
      }
    
      
    const detectApple = () => {
      if (/iPad|iPhone|iPod|Macintosh/.test(navigator.userAgent)) {
        document.documentElement.classList.add('apple')
      }
    }
    detectApple()
  
    })()
  </script><script>const GLOBAL_CONFIG = {
  root: '/',
  algolia: undefined,
  localSearch: {"path":"/search.xml","preload":false,"top_n_per_article":1,"unescape":false,"languages":{"hits_empty":"未找到符合您查询的内容：${query}","hits_stats":"共找到 ${hits} 篇文章"}},
  translate: undefined,
  highlight: {"plugin":"highlight.js","highlightCopy":true,"highlightLang":true,"highlightHeightLimit":false,"highlightFullpage":false,"highlightMacStyle":false},
  copy: {
    success: '复制成功',
    error: '复制失败',
    noSupport: '浏览器不支持'
  },
  relativeDate: {
    homepage: false,
    post: false
  },
  runtime: '',
  dateSuffix: {
    just: '刚刚',
    min: '分钟前',
    hour: '小时前',
    day: '天前',
    month: '个月前'
  },
  copyright: {"limitCount":150,"languages":{"author":"作者: funtim41@gmail.com","link":"链接: ","source":"来源: funtim的博客","info":"著作权归作者所有。商业转载请联系作者获得授权，非商业转载请注明出处。"}},
  lightbox: 'null',
  Snackbar: {"chs_to_cht":"已切换为繁体中文","cht_to_chs":"已切换为简体中文","day_to_night":"已切换为深色模式","night_to_day":"已切换为浅色模式","bgLight":"#49b1f5","bgDark":"#1f1f1f","position":"bottom-left"},
  infinitegrid: {
    js: 'https://cdn.jsdelivr.net/npm/@egjs/infinitegrid/dist/infinitegrid.min.js',
    buttonText: '加载更多'
  },
  isPhotoFigcaption: false,
  islazyload: false,
  isAnchor: true,
  percent: {
    toc: true,
    rightside: true,
  },
  autoDarkmode: false
}</script><script id="config-diff">var GLOBAL_CONFIG_SITE = {
  title: '03应用及文档',
  isPost: true,
  isHome: false,
  isHighlightShrink: false,
  isToc: true,
  isShuoshuo: false
}</script><link rel="stylesheet" href="/css/bar.css"><meta name="generator" content="Hexo 7.3.0"></head><body><div id="web_bg" style="background: Color(#995a82);"></div><div id="sidebar"><div id="menu-mask"></div><div id="sidebar-menus"><div class="avatar-img text-center"><img src="/images/4stars.png" onerror="onerror=null;src='/img/friend_404.gif'" alt="avatar"/></div><div class="site-data text-center"><a href="/archives/"><div class="headline">文章</div><div class="length-num">58</div></a><a href="/tags/"><div class="headline">标签</div><div class="length-num">5</div></a><a href="/categories/"><div class="headline">分类</div><div class="length-num">7</div></a></div><div class="menus_items"><div class="menus_item"><a class="site-page" href="/"><i class="fa-fw fas fa-home"></i><span> Home</span></a></div><div class="menus_item"><a class="site-page" href="/archives/"><i class="fa-fw fas fa-archive"></i><span> Timeline</span></a></div><div class="menus_item"><a class="site-page" href="/tags/"><i class="fa-fw fas fa-tags"></i><span> Tags</span></a></div><div class="menus_item"><a class="site-page" href="/categories/"><i class="fa-fw fas fa-folder-open"></i><span> Categories</span></a></div><div class="menus_item"><a class="site-page" href="/Links/"><i class="fa-fw fas fa-link"></i><span> Links</span></a></div><div class="menus_item"><a class="site-page" href="/about/"><i class="fa-fw fas fa-heart"></i><span> About</span></a></div></div></div></div><div class="post" id="body-wrap"><header class="post-bg fixed" id="page-header" style="background-image: url(/images/topback.jpg);"><nav id="nav"><span id="blog-info"><a class="nav-site-title" href="/"><img class="site-icon" src="/images/OIP.jfif" alt="Logo"><span class="site-name">funtim的博客</span></a><a class="nav-page-title" href="/"><span class="site-name">03应用及文档</span></a></span><div id="menus"><div id="search-button"><span class="site-page social-icon search"><i class="fas fa-search fa-fw"></i><span> 搜索</span></span></div><div class="menus_items"><div class="menus_item"><a class="site-page" href="/"><i class="fa-fw fas fa-home"></i><span> Home</span></a></div><div class="menus_item"><a class="site-page" href="/archives/"><i class="fa-fw fas fa-archive"></i><span> Timeline</span></a></div><div class="menus_item"><a class="site-page" href="/tags/"><i class="fa-fw fas fa-tags"></i><span> Tags</span></a></div><div class="menus_item"><a class="site-page" href="/categories/"><i class="fa-fw fas fa-folder-open"></i><span> Categories</span></a></div><div class="menus_item"><a class="site-page" href="/Links/"><i class="fa-fw fas fa-link"></i><span> Links</span></a></div><div class="menus_item"><a class="site-page" href="/about/"><i class="fa-fw fas fa-heart"></i><span> About</span></a></div></div><div id="toggle-menu"><span class="site-page"><i class="fas fa-bars fa-fw"></i></span></div></div></nav><div id="post-info"><h1 class="post-title">03应用及文档</h1><div id="post-meta"><div class="meta-firstline"><span class="post-meta-date"><i class="far fa-calendar-alt fa-fw post-meta-icon"></i><span class="post-meta-label">发表于</span><time class="post-meta-date-created" datetime="2024-11-26T12:11:29.000Z" title="发表于 2024-11-26 20:11:29">2024-11-26</time><span class="post-meta-separator">|</span><i class="fas fa-history fa-fw post-meta-icon"></i><span class="post-meta-label">更新于</span><time class="post-meta-date-updated" datetime="2025-01-13T14:18:52.714Z" title="更新于 2025-01-13 22:18:52">2025-01-13</time></span><span class="post-meta-categories"><span class="post-meta-separator">|</span><i class="fas fa-inbox fa-fw post-meta-icon"></i><a class="post-meta-categories" href="/categories/Revit%E4%BA%8C%E6%AC%A1%E5%BC%80%E5%8F%91%E4%BA%BA%E5%91%98%E6%8C%87%E5%8D%97/">Revit二次开发人员指南</a></span></div><div class="meta-secondline"><span class="post-meta-separator">|</span><span class="post-meta-pv-cv" id="" data-flag-title=""><i class="far fa-eye fa-fw post-meta-icon"></i><span class="post-meta-label">浏览量:</span><span id="busuanzi_value_page_pv"><i class="fa-solid fa-spinner fa-spin"></i></span></span></div></div></div></header><main class="layout" id="content-inner"><div id="post"><article class="container post-content" id="article-container"><h1 id="Application及Document"><a href="#Application及Document" class="headerlink" title="Application及Document"></a><a target="_blank" rel="noopener" href="https://help.autodesk.com/view/RVT/2018/ENU/?guid=Revit_API_Revit_API_Developers_Guide_Introduction_Application_and_Document_html">Application及Document</a></h1><p>Revit 平台 API 中的顶级对象是Application和Document。这些类由 Application、UIApplication、Document 和 UIDocument 类表示。</p>
<p>Application对象是指单个 Revit 任务，提供对文档、选项和其他应用程序范围的数据和设置的访问。</p>
<p>Autodesk.Revit.UI.UIApplication - 提供对应用程序的 UI 级界面的访问，包括将 RibbonPanel 添加到用户界面的功能，以及在用户界面中获取活动文档的功能。</p>
<p>Autodesk.Revit.ApplicationServices.Application - 提供对所有其他应用程序级别属性的访问。</p>
<p>Document是表示建筑模型的单个 Revit 项目文件。Revit 可以打开多个项目，并为一个项目打开多个视图。</p>
<p>Autodesk.Revit.UI.UIDocument - 提供对文档的 UI 级界面的访问，例如选择的内容以及提示用户进行选择和选取点的功能。</p>
<p>Autodesk.Revit.DB.Document - 提供对所有其他文档级别属性的访问。</p>
<p>如果打开了多个文档，则活动文档是其视图在 Revit 任务中处于活动状态的文档。</p>
<p>本章介绍了所有Application和Document，然后重点介绍文件管理、设置和单位。有关 Element 类的更多详细信息，请参阅 Elements Essentials和 编辑元素 ，并参阅 视图 以了解有关视图元素的更多详细信息。</p>
<h2 id="Applicaion功能"><a href="#Applicaion功能" class="headerlink" title="Applicaion功能"></a>Applicaion功能</h2><p>Application和 UIApplication 成员提供对应用程序范围的数据和设置以及 Revit 的活动会话的访问。</p>
<h4 id="Application-应用"><a href="#Application-应用" class="headerlink" title="Application 应用"></a>Application 应用</h4><p>该类表示 Autodesk Revit 应用程序，提供对文档、选项和其他应用程序范围的数据和设置的访问。</p>
<h4 id="应用程序版本信息"><a href="#应用程序版本信息" class="headerlink" title="应用程序版本信息"></a>应用程序版本信息</h4><p>应用程序属性包括 VersionBuild、VersionNumber 和 VersionName。这些属性可用于根据 Revit 的发布和内部版本提供附加模块行为，如如何使用应用程序属性为附加模块强制实施正确的版本所示。</p>
<h4 id="应用程序范围的设置"><a href="#应用程序范围的设置" class="headerlink" title="应用程序范围的设置"></a>应用程序范围的设置</h4><p>Revit 一次使用一个共享参数文件。Application.OpenSharedParameterFile() 方法访问其路径在 SharedParametersFilename 属性中设置的共享参数文件。有关更多详细信息，请参阅共享参数。</p>
<h4 id="库内容"><a href="#库内容" class="headerlink" title="库内容"></a>库内容</h4><p>GetLibraryPaths() 和 SetLibraryPaths() 方法提供对路径信息的访问，用于标识 Revit 搜索内容的位置。</p>
<h4 id="图形显示"><a href="#图形显示" class="headerlink" title="图形显示"></a>图形显示</h4><p>BackgroundColor 属性允许读取和写入此会话中用于模型视图的背景颜色。AllowNavigationDuringRedraw 属性启用或禁用允许在重绘期间进行视图操作的选项。这可用于在重绘模型期间优化性能。</p>
<h4 id="文档管理"><a href="#文档管理" class="headerlink" title="文档管理"></a>文档管理</h4><p>Application 类提供了用于创建以下类型文档的方法：</p>
<ul>
<li>Family document 族文件</li>
<li>Project document 项目文档</li>
<li>Project template 项目模板</li>
</ul>
<p>OpenDocumentFile() 方法可用于打开这些文档类型中的任何一种。所有打开的文档都可以使用 Documents 属性进行检索。<br>有关更多详细信息，请参阅文档和文件管理。</p>
<h4 id="会话信息"><a href="#会话信息" class="headerlink" title="会话信息"></a>会话信息</h4><p>UserName 等属性和GetRevitServerNetworkHosts() 等方法提供对此会话特定信息的只读访问。</p>
<h4 id="登录信息"><a href="#登录信息" class="headerlink" title="登录信息"></a>登录信息</h4><p>静态 IsLoggedIn 属性检查用户是否已从此会话登录到其 Autodesk A360 帐户。如果用户已登录，则 LoginUserId 属性将返回当前登录的用户的用户 ID。（如果用户未登录，则用户 ID 将为空。与上一节中的 UserName 不同，LoginUserId 值不是可识别的值，而是内部 ID。结合 Store Entitlement REST API，Autodesk 应用程序的发布者可以验证当前用户是否已从 Autodesk App Store 购买了其应用程序。有关 Store Entitlement API 的更多信息，请参阅 <a target="_blank" rel="noopener" href="http://www.autodesk.com/developapps%E3%80%82">www.autodesk.com/developapps。</a></p>
<h4 id="共享参数管理"><a href="#共享参数管理" class="headerlink" title="共享参数管理"></a>共享参数管理</h4><h4 id="事件"><a href="#事件" class="headerlink" title="事件"></a>事件</h4><p>Application 类公开 document 和 application 事件，例如 document open 和 save。订阅这些事件会在启用事件时通知应用程序并采取相应的措施。有关更多详细信息，请参阅 Add-In Integration 部分中的事件。</p>
<h4 id="创造"><a href="#创造" class="headerlink" title="创造"></a>创造</h4><p>“Create ”属性返回一个对象工厂，该对象工厂用于在 Revit 平台 API 中创建应用程序范围的实用程序和几何对象。如果要在 Revit Revit application memory （而不是your application’s memory）中创建对象，则使用“Create ”。</p>
<p>失败发布和处理</p>
<p>包含所有已注册的 FailureDefinitions 的 FailureDefinitionRegistry 可从静态 GetFailureDefinitionRegistry () 方法获得。静态方法 RegisterFailuresProcessor() 可用于注册自定义 IFailuresProcessor。有关发布和处理失败的更多信息，请参阅失败发布和处理。</p>
<h4 id="断开连接警告"><a href="#断开连接警告" class="headerlink" title="断开连接警告"></a>断开连接警告</h4><p>以下属性控制是否显示各种类型断开连接的图形警告。</p>
<ul>
<li>ShowGraphicalWarningCableTrayConduitDisconnects</li>
<li>ShowGraphicalWarningDuctDisconnects</li>
<li>ShowGraphicalWarningElectricalDisconnects</li>
<li>ShowGraphicalWarningHangerDisconnects</li>
</ul>
<h4 id="UIApplication"><a href="#UIApplication" class="headerlink" title="UIApplication"></a>UIApplication</h4><p>此类表示 Autodesk Revit 用户界面的活动会话，提供对 UI 自定义方法、事件和活动文档的访问。<br>文档管理</p>
<p>UIApplication 使用 UIActiveDocument 属性提供对活动文档的访问。此外，可以使用重载的 OpenAndActivateDocument() 方法打开 Revit 文档。文档将在默认视图处于活动状态的情况下打开。此方法不能在事务中调用，并且只能在事件期间调用 Revit 中尚未打开活动文档，并且该事件未嵌套在其他事件中。</p>
<h4 id="插件管理"><a href="#插件管理" class="headerlink" title="插件管理"></a>插件管理</h4><p>ActiveAddInId 属性获取当前活动的外部应用程序或外部命令 ID，而 LoadedApplications 属性返回成功加载的外部应用程序的数组。</p>
<h4 id="功能区面板实用程序"><a href="#功能区面板实用程序" class="headerlink" title="功能区面板实用程序"></a>功能区面板实用程序</h4><p>使用 UIApplication 对象将新的功能区面板和控件添加到 Revit。<br>有关更多详细信息，请参阅“加载项集成”部分中的 Ribbon 面板和控件。</p>
<h4 id="范围"><a href="#范围" class="headerlink" title="范围"></a>范围</h4><p>DrawingAreaExtents 属性返回一个矩形，该矩形表示绘图区域的屏幕像素坐标，而 MainWindowExtents 属性返回一个矩形，该矩形表示 Revit 主窗口的屏幕像素坐标</p>
<h4 id="事件-1"><a href="#事件-1" class="headerlink" title="事件"></a>事件</h4><p>UIApplication 类公开与 UI 相关的事件，例如显示对话框时。订阅这些事件会在启用事件时通知应用程序并采取相应的措施。有关更多详细信息，请参阅 Add-In Integration 部分中的事件。</p>
<h3 id="学科控制"><a href="#学科控制" class="headerlink" title="学科控制"></a>学科控制</h3><p>The properties:</p>
<ul>
<li>Application.IsArchitectureEnabled</li>
<li>Application.IsStructureEnabled</li>
<li>Application.IsStructuralAnalysisEnabled</li>
<li>Application.IsMassingEnabled</li>
<li>Application.IsEnergyAnalysisEnabled</li>
<li>Application.IsSystemsEnabled</li>
<li>Application.IsMechanicalEnabled</li>
<li>Application.IsMechanicalAnalysisEnabled</li>
<li>Application.IsElectricalEnabled</li>
<li>Application.IsElectricalAnalysisEnabled</li>
<li>Application.IsPipingEnabled</li>
<li>Application.IsPipingAnalysisEnabled</li>
</ul>
<p>提供对可用学科的 READ 和 MODIFY 访问权限。应用程序可以读取属性以确定何时启用或禁用其 UI 的各个方面。</p>
<p>切换领域状态时，Revit 的 UI 将进行调整，并且将根据需要启用或禁用某些操作和功能。启用分析模式仅在启用相应专业时生效。例如，除非还启用了机械专业，否则启用 Mechanical Analysis 不会生效。</p>
<h3 id="如何使用Application属性为外接程序强制实施正确的版本"><a href="#如何使用Application属性为外接程序强制实施正确的版本" class="headerlink" title="如何使用Application属性为外接程序强制实施正确的版本"></a>如何使用Application属性为外接程序强制实施正确的版本</h3><p>有时，由于存在特定的修复或兼容的 API，您需要仅在存在特定的 Revit Update Release 的情况下运行附加模块。</p>
<p>使用“Application”的属性可以检查 Revit 的特定版本。属性 VersionNumber 将返回表示主版本号的字符串，而 VersionBuild 属性将返回 Autodesk Revit 应用程序的内部内部版本号。</p>
<p>另一个有用的属性是 Application.SubVersionNumber 属性。它返回一个字符串，该字符串表示 Revit 应用程序的主要-次要版本号，例如“2018.0.0”。Autodesk 会针对所有主要和次要更新更新更新此字符串。小版本（如 2018.1.0）可能具有初始客户版本（如 2018.0.0）中未提供的其他 API 和功能。为支持初始版本而编写的加载项可能与订阅更新兼容，但在订阅更新中使用新功能的加载项将与初始版本不兼容。</p>
<p>以下示例代码演示了一种技术，用于确定 Revit 版本是否为初始已知 Revit 版本之后的任何 Update Release。</p>
<p>代码区域：使用 VersionBuild 确定您的外接程序是否兼容</p>
<figure class="highlight c#"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="keyword">public</span> <span class="keyword">void</span> <span class="title">GetVersionInfo</span>(<span class="params">Autodesk.Revit.ApplicationServices.Application app</span>)</span></span><br><span class="line">&#123; </span><br><span class="line">   <span class="comment">// 20110309_2315 is the datecode of the initial release of Revit 2012 </span></span><br><span class="line">   <span class="keyword">if</span> (app.VersionNumber == <span class="string">&quot;2012&quot;</span> &amp;&amp; </span><br><span class="line">       String.Compare(app.VersionBuild, <span class="string">&quot;20110309_2315&quot;</span>) &gt; <span class="number">0</span>)</span><br><span class="line">   &#123;</span><br><span class="line">       TaskDialog.Show(<span class="string">&quot;Supported version&quot;</span>, </span><br><span class="line">                      <span class="string">&quot;This application supported in this version.&quot;</span>);</span><br><span class="line">   &#125;</span><br><span class="line">   <span class="keyword">else</span></span><br><span class="line">   &#123;</span><br><span class="line">       TaskDialog dialog = <span class="keyword">new</span> TaskDialog(<span class="string">&quot;Unsupported version.&quot;</span>);</span><br><span class="line">       dialog.MainIcon = TaskDialogIcon.TaskDialogIconWarning;</span><br><span class="line">       dialog.MainInstruction = <span class="string">&quot;This Revit 2012 application is supported in UR1 and later releases.&quot;</span>;</span><br><span class="line">       dialog.Show();</span><br><span class="line">   &#125;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>



<h2 id="Document功能"><a href="#Document功能" class="headerlink" title="Document功能"></a>Document功能</h2><p>Document存储 Revit 图元、管理数据并更新多个数据视图。Document 类主要提供以下功能。</p>
<p>Document </p>
<p>Document 类表示打开的 Autodesk Revit 项目。</p>
<p>Settings 属性</p>
<p>Settings 属性返回一个对象，该对象提供对 Revit 项目中常规组件的访问。有关更多详细信息，请参阅设置。</p>
<p>地点和位置</p>
<p>每个项目只有一个场地位置，用于标识 Earth 上的物理项目位置。一个工程可以有多个工程位置。每个位置都是站点位置的偏移或旋转。有关更多详细信息，请参阅地点和位置。</p>
<p>视图管理</p>
<p>一个项目文档可以有多个视图。ActiveView 属性返回表示活动视图的 View 对象。您可以过滤项目中的图元以检索其他视图。有关更多详细信息，请参阅 视图。</p>
<p>元素检索</p>
<p>Document 对象将元素存储在项目中。使用 Element 属性按 ElementId 或 UniqueId 检索特定元素。<br>有关更多详细信息，请参阅 Elements Essential。</p>
<p>文件管理</p>
<p>每个 Document 对象都代表一个 Revit 项目文件。Document 提供如下功能：<br>检索文件信息，例如文件路径名和项目标题。<br>提供 Close() 和 Save() 方法来关闭和保存文档。<br>有关更多详细信息，请参阅文档和文件管理。</p>
<p>元素管理</p>
<p>Revit 会保留项目中的所有图元对象。要创建新图元，请使用“Create”属性，该属性返回用于在 Revit 平台 API 中创建新项目图元实例（如 FamilyInstance 或 Group）的对象工厂。<br>Document 类还可用于删除元素。使用 Delete() 方法删除项目中的元素。已删除的元素和任何从属元素不会显示，并且会从文档中删除。对已删除元素的引用无效，并会导致异常。有关更多详细信息，请参阅编辑元素。</p>
<p>事件</p>
<p>某些操作会引发事件，例如当您使用 Save 或 Save As 保存项目时。要在应用程序中捕获事件并做出响应，必须注册事件处理程序。有关更多详细信息，请参阅 事件。</p>
<p>文档状态</p>
<p>多个属性提供有关文档状态的信息：</p>
<ul>
<li>IsModifiable - 当前是否可以修改文档（这意味着文档中有一个活动事务，并且更改不会被其他任何内容暂时阻止）</li>
<li>IsModified - 文档在打开或保存后是否发生更改</li>
<li>IsReadOnly - 如果为 true，则文档当前为只读且无法修改</li>
<li>IsReadOnlyFile - 文档是否以只读模式打开</li>
<li>IsFamilyDocument - 文档是否为家庭文档</li>
<li>IsWorkshared - 是否已在文档中启用工作集</li>
</ul>
<p>其他</p>
<p>Document 还提供其他功能：</p>
<ul>
<li>ParameterBindings 属性 - 参数定义和类别之间的映射。有关更多详细信息，请参阅共享参数。</li>
<li>ReactionsAreUpToDate 属性 - 报告反作用载荷是否发生变化。有关更多详细信息，请参阅负载。</li>
<li>Default Types - 访问族和非族元素的默认类型。有关更多详细信息，请参阅默认类型。</li>
</ul>
<p>UIDocument</p>
<p>UIDocument 类表示在 Revit 用户界面中打开的 Autodesk Revit 项目。</p>
<p>元素检索</p>
<p>使用 UIDocument 中的 Selection 属性检索所选元素。此属性返回一个对象，该对象表示包含所选项目元素的活动选择。它还提供了 UI 交互方法，用于在 Revit 模型中拾取对象。有关更多详细信息，请参阅 Elements Essentials。</p>
<p>元素显示</p>
<p>ShowElements() 方法使用来关注多个元素。</p>
<p>视图管理</p>
<p>通过调用 RefreshActiveView() 方法，可以使用 UIDocument 类来刷新活动文档中的活动视图。ActiveView 属性可用于检索或设置文档的活动视图。更改活动视图有一些限制。它只能在活动文档中使用，该文档不得处于只读状态，也不得位于事务中。此外，在 ViewActivating 或 ViewActivated 事件期间，或任何操作前事件 （如 DocumentSaving、DocumentClosing 或其他类似事件） 期间，不得更改活动视图。</p>
<p>UIDocument.ActiveGraphicalView 属性检索文档的活动图形视图。与 UIDocument.ActiveView 不同，如果用户碰巧在其中一个视图中进行选择，则此属性将永远不会返回辅助视图（如 Project Browser 或 System Browser）。</p>
<p>UIDocument 还可用于获取 Revit 用户界面中所有打开的视图窗口的列表。GetOpenUIViews 方法返回一个 UIViews 列表，其中包含有关 Revit 用户界面中视图窗口的数据。</p>
<h3 id="Default-Types-默认类型"><a href="#Default-Types-默认类型" class="headerlink" title="Default Types 默认类型"></a>Default Types 默认类型</h3><p>Revit 具有不同类别的默认类型。调用相关工具创建此类别的图元时，此默认类型将显示在 Revit 用户界面中。Revit API 通过 Document 类公开族和非族类型的默认类型。</p>
<p>族类型</p>
<table>
<thead>
<tr>
<th align="left">方法</th>
<th align="left">描述</th>
</tr>
</thead>
<tbody><tr>
<td align="left">GetDefaultFamilyTypeId()</td>
<td align="left">获取与给定族类别 ID 关联的默认系列类型 ID。</td>
</tr>
<tr>
<td align="left">SetDefaultFamilyTypeId()</td>
<td align="left">设置与给定族类别 ID 关联的默认族类型 ID。</td>
</tr>
<tr>
<td align="left">IsDefaultFamilyTypeIdValid()</td>
<td align="left">检查族类型 ID 是否有效，可设置为给定族类别 ID 的默认值。</td>
</tr>
</tbody></table>
<p>此外，给定 ElementType，ElementType.IsValidDefaultFamilyType() 标识它是否是给定族类别 ID 的有效默认族类型。 以下示例演示了如何获取结构柱类别的默认族类型 ID。然后，它获取默认类型的族符号并将其分配给给定的柱。</p>
<figure class="highlight c#"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="keyword">private</span> <span class="keyword">void</span> <span class="title">AssignDefaultTypeToColumn</span>(<span class="params">Document document, FamilyInstance column</span>)</span></span><br><span class="line">&#123;</span><br><span class="line">    ElementId defaultTypeId = document.GetDefaultFamilyTypeId(<span class="keyword">new</span> ElementId(BuiltInCategory.OST_StructuralColumns));</span><br><span class="line"></span><br><span class="line">    <span class="keyword">if</span> (defaultTypeId != ElementId.InvalidElementId)</span><br><span class="line">    &#123;</span><br><span class="line">        FamilySymbol defaultType = document.GetElement(defaultTypeId) <span class="keyword">as</span> FamilySymbol;</span><br><span class="line">        <span class="keyword">if</span> (defaultType != <span class="literal">null</span>)</span><br><span class="line">        &#123;</span><br><span class="line">            column.Symbol = defaultType;</span><br><span class="line">        &#125;</span><br><span class="line">    &#125;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<p>下一个示例在首先检查给定门是否为有效的默认族类型 ID 后，为给定门的门类别设置默认类型。</p>
<p>代码区域：设置默认族类型 ID</p>
<figure class="highlight c#"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="keyword">private</span> <span class="keyword">void</span> <span class="title">SetDefaultTypeFromDoor</span>(<span class="params">Document document, FamilyInstance door</span>)</span></span><br><span class="line">&#123;</span><br><span class="line">    ElementId doorCategoryId = <span class="keyword">new</span> ElementId(BuiltInCategory.OST_Doors);</span><br><span class="line"></span><br><span class="line">    <span class="comment">// It is necessary to test the type suitability to be a default family type, for not every type can be set as default. </span></span><br><span class="line">    <span class="comment">// Trying to set a non-qualifying default type will cause an exception</span></span><br><span class="line">    <span class="keyword">if</span> (door.Symbol.IsValidDefaultFamilyType(doorCategoryId))</span><br><span class="line">    &#123;</span><br><span class="line">        document.SetDefaultFamilyTypeId(doorCategoryId, door.Symbol.Id);</span><br><span class="line">    &#125;</span><br><span class="line"></span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<p>非族类型</p>
<p>下表中的文档成员提供对非 Family 元素类型的默认类型的访问。</p>
<table>
<thead>
<tr>
<th align="left">方法</th>
<th align="left">描述</th>
</tr>
</thead>
<tbody><tr>
<td align="left">GetDefaultElementTypeId()</td>
<td align="left">获取给定非 Family 元素类型的默认元素类型 ID。</td>
</tr>
<tr>
<td align="left">SetDefaultElementTypeId()</td>
<td align="left">为给定的非 Family 元素类型设置默认元素类型 ID。</td>
</tr>
<tr>
<td align="left">IsDefaultElementTypeIdValid()</td>
<td align="left">检查元素类型 ID 是否对给定的非 Family 元素类型有效。</td>
</tr>
</tbody></table>
<p>下面的示例检查给定的墙壁是否使用墙壁类型的默认元素类型。</p>
<p>代码区域：获取默认元素类型 ID</p>
<figure class="highlight plaintext"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br></pre></td><td class="code"><pre><span class="line">private bool IsWallUsingDefaultType(Document document, Wall wall)</span><br><span class="line">&#123;</span><br><span class="line">    ElementId defaultElementTypeId = document.GetDefaultElementTypeId(ElementTypeGroup.WallType);</span><br><span class="line">    return (wall.WallType.Id == defaultElementTypeId);</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>



<h2 id="文档和文件管理"><a href="#文档和文件管理" class="headerlink" title="文档和文件管理"></a>文档和文件管理</h2><p>文档和文件管理使创建和查找文档变得容易。</p>
<p>文档检索</p>
<p>Application 类维护所有文档。如前所述，您可以在一个会话中打开多个文档。使用 UIApplication 类属性 ActiveUIDocument 检索活动文档。所有打开的文档（包括活动文档）都使用 Application 类 Documents 属性进行检索。该属性返回一个包含 Revit 任务中所有打开的文档的集。</p>
<p>文档文件信息</p>
<p>Document 类为每个相应的文件提供两个属性，即 PathName 和 Title。</p>
<p>PathName 返回文档的完全限定文件路径。如果项目自创建以来尚未保存，则 PathName 将返回空字符串。</p>
<p>Title 是项目标题，通常从项目文件名派生而来。返回值因您的系统设置而异。</p>
<p>打开文档</p>
<p>Application 类提供了一个重载的方法来打开现有项目文件：</p>
<p>表 3：在 API 中打开文档</p>
<table>
<thead>
<tr>
<th><strong>Method 方法</strong></th>
<th><strong>Event 事件</strong></th>
</tr>
</thead>
<tbody><tr>
<td>Document OpenDocumentFile(string filename )<br /> Document OpenDocumentFile(ModelPath modelPath, OpenOptions openOptions)</td>
<td>DocumentOpened 文档已打开</td>
</tr>
</tbody></table>
<p>指定具有完全限定文件路径的字符串时，Revit 将打开该文件并创建一个 Document 实例。使用此方法可以通过为此方法分配文件通用命名转换 （UNC） 名称，在其他计算机上打开文件。该文件可以是扩展名为 .rvt 的项目文件、扩展名为 .rfa 的族文件或扩展名为 .rte 的样板文件。第二个重载将模型的路径作为 ModelPath 而不是字符串，并且 OpenOptions 参数提供用于打开文件的选项，例如从中心分离打开的文档（如果适用）的功能，以及与工作共享相关的选项。有关打开工作共享文档的更多信息，请参阅打开工作共享文档。这些方法在发生故障时引发特定的记录异常。例外情况分为 4 大类。</p>
<p>表 4：引发的异常类型</p>
<table>
<thead>
<tr>
<th><strong>Type 类型</strong></th>
<th><strong>Example 例</strong></th>
</tr>
</thead>
<tbody><tr>
<td>Disk errors 磁盘错误</td>
<td>文件不存在或版本错误</td>
</tr>
<tr>
<td>Resource errors 资源错误</td>
<td>没有足够的内存或磁盘空间来打开文件</td>
</tr>
<tr>
<td>Central model file errors 中心模型文件错误</td>
<td>文件已锁定或损坏</td>
</tr>
<tr>
<td>Central model&#x2F;server errors 中心模型&#x2F;服务器错误</td>
<td>与服务器发生网络通信错误</td>
</tr>
</tbody></table>
<p>如果文档打开成功，则会引发 DocumentOpened 事件。</p>
<p> 创建文档 </p>
<p>使用下表中的 Application 方法创建新文档。<br>表 5：在 API 中创建文档</p>
<table>
<thead>
<tr>
<th><strong>Method 方法</strong></th>
<th><strong>Event 事件</strong></th>
</tr>
</thead>
<tbody><tr>
<td><code>Document NewProjectDocument(string templateFileName);</code></td>
<td>DocumentCreated</td>
</tr>
<tr>
<td><code>Document NewProjectDocument(UnitSystem unitSystem);</code></td>
<td>DocumentCreated</td>
</tr>
<tr>
<td><code>Document NewFamilyDocument(string templateFileName);</code></td>
<td>DocumentCreated</td>
</tr>
<tr>
<td><code>Document NewProjectTemplateDocument(string templateFilename);</code></td>
<td>DocumentCreated</td>
</tr>
</tbody></table>
<p>对于需要模板文件名作为参数的方法，将基于模板文件返回创建的文档。NewProjectDocument（UnitSystem）将创建一个没有指定模板的新英制或公制项目文档。</p>
<p>保存并关闭文档 Document 类提供了保存或关闭实例的方法。</p>
<p>表 6：在 API 中保存和关闭文档</p>
<table>
<thead>
<tr>
<th><strong>Method 方法</strong></th>
<th><strong>Event 事件</strong></th>
</tr>
</thead>
<tbody><tr>
<td>Save() 保存</td>
<td>DocumentSaved 文档已保存</td>
</tr>
<tr>
<td>SaveAs() 保存为</td>
<td>DocumentSavedAs</td>
</tr>
<tr>
<td>Close() 关闭</td>
<td>DocumentClosed 文档已关闭</td>
</tr>
</tbody></table>
<p>Save() 有 2 个重载，一个没有参数，另一个带有 SaveOptions 参数，可以指定是否强制操作系统从磁盘上的文件中删除所有死数据。如果之前未保存该文件，则必须改为调用 SaveAs()。 </p>
<p>SaveAs() 有 3 个重载。一个重载仅将文件名作为参数，如果存在另一个具有给定文件名的文件，则会引发异常。其他 2 个重载将文件名作为参数（在一种情况下以 ModelPath 的形式）以及第二个 SaveAsOptions 参数，该参数可用于指定是否覆盖现有文件（如果存在）。SaveAsOptions 还可用于指定其他相关选项，例如是否删除磁盘上与文件相关的死数据和工作共享选项。 Save() 和 SaveAs() 在与打开文档时相同的 4 个类别中引发特定的记录异常，如上面的表 4 所示。</p>
<p> Close() 有两个重载。一个参数采用 Boolean 参数，该参数指示是否在关闭文件之前保存文件。第二个重载不带任何参数，如果文档被修改，系统会询问用户是否要在关闭之前保存文件。如果尚未设置文档的路径名，或者保存的目标文件是只读的，则此方法将引发异常。</p>
<p>注： Close() 方法不会影响活动文档或引发 DocumentClosed 事件，因为该文档由外部应用程序使用。您只能对非活动文档调用此方法。UIDocument 类还提供了保存和关闭实例的方法。</p>
<p>表 7：在 API 中保存和关闭 UIDocument</p>
<table>
<thead>
<tr>
<th><strong>Method 方法</strong></th>
<th><strong>Event 事件</strong></th>
</tr>
</thead>
<tbody><tr>
<td>SaveAndClose()</td>
<td>DocumentSaved, DocumentClosed</td>
</tr>
<tr>
<td>SaveAs() 保存为</td>
<td>DocumentSavedAs</td>
</tr>
</tbody></table>
<p>SaveAndClose() 在保存文档后关闭文档。如果尚未设置文档的路径名称，则向 Revit 用户显示“另存为”对话框，以设置其名称和位置。 SaveAs() 方法将文档保存为通过“另存为”对话框从 Revit 用户处获取的文件名和路径。</p>
<p>文档预览</p>
<p> 可以从 Document 获取 DocumentPreviewSettings 类，该类包含与保存给定文档的预览图像相关的设置。</p>
<p>代码区域：文档预览</p>
<figure class="highlight c#"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br><span class="line">23</span><br><span class="line">24</span><br><span class="line">25</span><br><span class="line">26</span><br><span class="line">27</span><br><span class="line">28</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="keyword">public</span> <span class="keyword">void</span> <span class="title">SaveActiveViewWithPreview</span>(<span class="params">UIApplication application</span>)</span></span><br><span class="line">&#123;</span><br><span class="line">    <span class="comment">// Get the handle of current document.</span></span><br><span class="line">    Autodesk.Revit.DB.Document document = application.ActiveUIDocument.Document;</span><br><span class="line"></span><br><span class="line">    <span class="comment">// Get the document&#x27;s preview settings</span></span><br><span class="line">    DocumentPreviewSettings settings = document.GetDocumentPreviewSettings();</span><br><span class="line">    </span><br><span class="line">    <span class="comment">// Find a candidate 3D view</span></span><br><span class="line">    FilteredElementCollector collector = <span class="keyword">new</span> FilteredElementCollector(document);</span><br><span class="line">    collector.OfClass(<span class="keyword">typeof</span>(View3D));</span><br><span class="line">    </span><br><span class="line">    Func&lt;View3D, <span class="built_in">bool</span>&gt; isValidForPreview = v =&gt; settings.IsViewIdValidForPreview(v.Id);</span><br><span class="line">    </span><br><span class="line">    View3D viewForPreview = collector.OfType().First(isValidForPreview);</span><br><span class="line">    </span><br><span class="line">    <span class="comment">// Set the preview settings</span></span><br><span class="line">    <span class="keyword">using</span> (Transaction setTransaction = <span class="keyword">new</span> Transaction(document, <span class="string">&quot;Set preview view id&quot;</span>))</span><br><span class="line">    &#123;</span><br><span class="line">        setTransaction.Start();</span><br><span class="line">        settings.PreviewViewId = viewForPreview.Id;</span><br><span class="line">        setTransaction.Commit();</span><br><span class="line">    &#125;</span><br><span class="line">    </span><br><span class="line">    <span class="comment">// Save the document</span></span><br><span class="line">    document.Save();</span><br><span class="line"></span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<p>荷载族</p>
<p>Document 类使您能够将整个族及其所有符号加载到项目中。由于加载整个族可能需要很长时间和大量内存，因此 Document 类提供了类似的方法 LoadFamilySymbol() 来仅加载指定的符号。有关更多详细信息，请参阅 族。</p>
<h2 id="设置"><a href="#设置" class="headerlink" title="设置"></a>设置</h2><p>下表标识了 Revit Platform UI“管理”选项卡中的命令以及相应的 API。</p>
<p>表 7：API 和 UI 中的设置</p>
<table>
<thead>
<tr>
<th><strong>UI 命令</strong></th>
<th><strong>关联 API</strong></th>
<th><strong>参考</strong></th>
</tr>
</thead>
<tbody><tr>
<td>设置 <img src="https://help.autodesk.com/cloudhelp/2018/ENU/Revit-API/images/ac.menuaro.gif" alt="img"> 项目信息</td>
<td>Document.ProjectInformation</td>
<td>请参阅以下注释</td>
</tr>
<tr>
<td>设置 <img src="https://help.autodesk.com/cloudhelp/2018/ENU/Revit-API/images/ac.menuaro.gif" alt="img"> 项目参数</td>
<td>Document.ParameterBindings (Only for Shared Parameter)</td>
<td>请参阅<a target="_blank" rel="noopener" href="https://help.autodesk.com/view/RVT/2018/ENU/?guid=Shared_Parameters">共享参数</a></td>
</tr>
<tr>
<td>“项目位置”面板</td>
<td>Document.ProjectLocations</td>
<td>查看<a target="_blank" rel="noopener" href="https://help.autodesk.com/view/RVT/2018/ENU/?guid=Place_and_Locations">地点和位置</a></td>
</tr>
<tr>
<td>设置 <img src="https://help.autodesk.com/cloudhelp/2018/ENU/Revit-API/images/ac.menuaro.gif" alt="img"> 其他设置 <img src="https://help.autodesk.com/cloudhelp/2018/ENU/Revit-API/images/ac.menuaro.gif" alt="img"> 填充图案</td>
<td>FilteredElementCollector filtering on class FillPatternElement</td>
<td>请参阅以下注释</td>
</tr>
<tr>
<td>设置 <img src="https://help.autodesk.com/cloudhelp/2018/ENU/Revit-API/images/ac.menuaro.gif" alt="img"> 材质</td>
<td>FilteredElementCollector filtering on class Material</td>
<td>请参阅<a target="_blank" rel="noopener" href="https://help.autodesk.com/view/RVT/2018/ENU/?guid=Material_Management">物料管理</a></td>
</tr>
<tr>
<td>设置 <img src="https://help.autodesk.com/cloudhelp/2018/ENU/Revit-API/images/ac.menuaro.gif" alt="img"> 对象样式</td>
<td>Document.Settings.Categories</td>
<td>请参阅以下注释</td>
</tr>
<tr>
<td>阶段划分 <img src="https://help.autodesk.com/cloudhelp/2018/ENU/Revit-API/images/ac.menuaro.gif" alt="img"> 阶段</td>
<td>Document.Phases</td>
<td>请参阅以下注释</td>
</tr>
<tr>
<td>设置 <img src="https://help.autodesk.com/cloudhelp/2018/ENU/Revit-API/images/ac.menuaro.gif" alt="img"> 结构设置</td>
<td>Loads and related structural settings are available in the API</td>
<td>参见 <a target="_blank" rel="noopener" href="https://help.autodesk.com/view/RVT/2018/ENU/?guid=Structural_Engineering">Structural Engineering</a></td>
</tr>
<tr>
<td>设置 <img src="https://help.autodesk.com/cloudhelp/2018/ENU/Revit-API/images/ac.menuaro.gif" alt="img"> 项目单位</td>
<td>Document.GetUnits()</td>
<td>见<a target="_blank" rel="noopener" href="https://help.autodesk.com/view/RVT/2018/ENU/?guid=Units">单位</a></td>
</tr>
<tr>
<td>面积和体积计算（在房间和面积面板上）</td>
<td>AreaVolumeSettings.GetAreaVolumeSettings()</td>
<td>请参阅以下注释</td>
</tr>
</tbody></table>
<p>注意：项目信息 - API 提供 ProjectInfo 类，该类使用 Document.ProjectInformation 检索，以表示 Revit 项目中的项目信息。下表标识了 Project Information 参数的相应 API。</p>
<p>表 8：项目信息</p>
<table>
<thead>
<tr>
<th><strong>参数</strong></th>
<th><strong>对应 API</strong></th>
<th><strong>内置参数</strong></th>
</tr>
</thead>
<tbody><tr>
<td>Project Issue Date 项目发布日期</td>
<td>ProjectInfo.IssueDate</td>
<td>PROJECT_ISSUE_DATE</td>
</tr>
<tr>
<td>Project Status 项目进展</td>
<td>ProjectInfo.Status</td>
<td>PROJECT_STATUS</td>
</tr>
<tr>
<td>Client Name 客户端名称</td>
<td>ProjectInfo.ClientName</td>
<td>CLIENT_NAME</td>
</tr>
<tr>
<td>Project Address 项目地址</td>
<td>ProjectInfo.Address</td>
<td>PROJECT_ADDRESS</td>
</tr>
<tr>
<td>Project Name 项目名称</td>
<td>ProjectInfo.Name</td>
<td>PROJECT_NAME</td>
</tr>
<tr>
<td>Project Number 项目编号</td>
<td>ProjectInfo.Number</td>
<td>PROJECT_NUMBER</td>
</tr>
</tbody></table>
<p>使用 ProjectInfo 公开的属性来检索和设置所有字符串。这些属性由相应的内置参数实现。您可以直接通过内置参数获取或设置值。有关如何通过内置参数访问这些参数的更多信息，请参阅“Elements Essentials”部分中的参数。获取项目信息的推荐方法是使用 ProjectInfo 属性。</p>
<p>Fill Patterns</p>
<p>使用对类 FillPatternElement 的 FilteredElementCollector 过滤来检索当前文档中的所有填充图案。可以使用静态方法 FillPatternElement.GetFillPattern（Document， ElementId） 或 FillPatternElement.GetFillPatternByName （Document， string） 来检索特定的 FillPattern。</p>
<p>Object Styles</p>
<p>使用 Settings.Categories 检索 Category 对象中除 Line Style 之外的所有信息。有关更多详细信息，请参阅 Elements Essentials和 Material 部分中的 Other Classifications。</p>
<p>Phases</p>
<p>Revit 按阶段维护图元生命周期，阶段是项目生命周期中的不同时间段。文档中的所有阶段都使用 Document.Phases 属性进行检索。该属性返回一个包含 Phase 类实例的数组。但是，Revit API 不会公开 Phase 类中的函数。</p>
<p>Options</p>
<p> “Options”命令用于配置项目全局设置。您可以使用 Application.Options 属性检索 Options.Application 实例。目前，Options.Application 类仅支持访问库路径和共享参数文件。</p>
<p>Area and Volume Calculations</p>
<p>AreaVolumeSettings 类允许您启用或禁用体积计算，以及更改房间边界位置。</p>
<h2 id="单位"><a href="#单位" class="headerlink" title="单位"></a>单位</h2><p>Revit API 中用于处理单位的两个主要类是 Units 和 FormatOptions。Units 类表示文档的默认设置，用于将带有单位的数字格式设置为字符串。它包含每个单位类型的 FormatOptions 对象以及与小数符号和数字分组相关的设置。</p>
<p>Units 类为每个有效的 Unit 类型存储一个 FormatOptions 对象，但并非所有 Unit 类型都可以直接修改。有些 （如 UT_Number 和 UT_SiteAngle）具有固定的定义。其他单位的定义是从其他单位类型自动派生的。例如，UT_SheetLength 派生自 UT_Length UT_ForceScale 派生自 UT_Force。</p>
<p>FormatOptions 类包含一些设置，这些设置控制如何将带有单位的数字格式设置为字符串。它包含通常由最终用户在“格式”对话框中选择并存储在文档中的设置，例如舍入、准确性、显示单位以及是否禁止空格或前导零或尾随零。</p>
<p>FormatOptions 类以两种不同的方式使用。Units 类中的 FormatOptions 对象表示文档的默认设置。在其他位置使用的 FormatOptions 对象表示可以选择性地覆盖默认设置的设置。</p>
<p>UseDefault 属性控制 FormatOptions 对象是表示默认格式还是自定义格式。如果 UseDefault 为 true，则格式设置将根据 Units 类中的默认设置进行，并且对象中的其他设置都没有意义的。如果 UseDefault 为 false，则对象包含替代 Units 类中的默认设置的自定义设置。对于 Units 类中的 FormatOptions 对象，UseDefault 始终为 false。</p>
<p>Revit API 中与单元相关的重要枚举包括：</p>
<ul>
<li>UnitType - 要测量的物理量类型，例如长度或力（UT_Length 或 UT_Force）</li>
<li>DisplayUnitType - 用于将数字格式化为字符串或转换单位（即 DUT_METERS）的单位和显示格式</li>
<li>UnitSymbolType - 以数字的格式化字符串表示形式显示的单位符号，以指示值的单位（即 UST_M）</li>
</ul>
<p>单位换算<br>Revit API 提供了实用程序类，以便于在 Revit 中处理数量。使用 UnitUtils 类，可以轻松地将单位数据与 Revit 的内部单位相互转换。<br>Revit 有七个基本单位，每个基本单位都有自己的内部单位。下表列出了这些内部单位。</p>
<p>表 9：Revit Unit System 中的 7 个基本单元</p>
<table>
<thead>
<tr>
<th><strong>基本单位</strong></th>
<th><strong>Revit 中的单位</strong></th>
<th><strong>单位制</strong></th>
</tr>
</thead>
<tbody><tr>
<td>Length 长度</td>
<td>Feet (ft) 英尺（英尺）</td>
<td>Imperial 英制</td>
</tr>
<tr>
<td>Angle 角度</td>
<td>Radian 弧度</td>
<td>Metric 公制</td>
</tr>
<tr>
<td>Mass 质量</td>
<td>Kilogram (kg) 千克 （kg）</td>
<td>Metric 公制</td>
</tr>
<tr>
<td>Time 时间</td>
<td>Seconds (s) 秒 （s）</td>
<td>Metric 公制</td>
</tr>
<tr>
<td>Electric Current 电流</td>
<td>Ampere (A) 安培 （A）</td>
<td>Metric 公制</td>
</tr>
<tr>
<td>Temperature 温度</td>
<td>Kelvin (K) 开尔文 （K）</td>
<td>Metric 公制</td>
</tr>
<tr>
<td>Luminous Intensity 发光强度</td>
<td>Candela (cd) 坎德拉 （cd）</td>
<td>Metric 公制</td>
</tr>
</tbody></table>
<p>注意：由于 Revit 以英尺为单位存储长度，以公制单位存储其他基本量，因此涉及长度的派生单位将是基于英制和公制的非标准单位。例如，由于力是以“每时间平方的质量长度”来测量的，因此它以 kg-ft &#x2F; s2 为单位存储。以下示例使用 UnitUtils.ConvertFromInternalUnits() 方法获取材料的最小屈服应力（以 kips&#x2F;平方英寸为单位）。</p>
<p>代码区域：从 Revit 的内部单位转换</p>
<figure class="highlight c#"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="built_in">double</span> <span class="title">GetYieldStressInKsi</span>(<span class="params">Material material</span>)</span></span><br><span class="line">&#123;</span><br><span class="line">    <span class="built_in">double</span> dMinYieldStress = <span class="number">0</span>;</span><br><span class="line">    <span class="comment">// Get the structural asset for the material</span></span><br><span class="line">    ElementId strucAssetId = material.StructuralAssetId;</span><br><span class="line">    <span class="keyword">if</span> (strucAssetId != ElementId.InvalidElementId)</span><br><span class="line">    &#123;</span><br><span class="line">        PropertySetElement pse = material.Document.GetElement(strucAssetId) <span class="keyword">as</span> PropertySetElement;</span><br><span class="line">        <span class="keyword">if</span> (pse != <span class="literal">null</span>)</span><br><span class="line">        &#123;</span><br><span class="line">            StructuralAsset asset = pse.GetStructuralAsset();</span><br><span class="line"></span><br><span class="line">            <span class="comment">// Get the min yield stress and convert to ksi</span></span><br><span class="line">            dMinYieldStress = asset.MinimumYieldStress;</span><br><span class="line">            dMinYieldStress = UnitUtils.ConvertFromInternalUnits(dMinYieldStress,</span><br><span class="line">                DisplayUnitType.DUT_KIPS_PER_SQUARE_INCH);</span><br><span class="line">        &#125;</span><br><span class="line">    &#125;    </span><br><span class="line">    <span class="keyword">return</span> dMinYieldStress;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<p>UnitUtils 还可用于将值从一种单位类型转换为另一种单位类型，例如平方英尺到平方米。在以下示例中，以英寸为单位输入的墙的顶部偏移值将转换为英尺，这是设置该值的预期单位。</p>
<p>代码区域：在单位之间转换</p>
<figure class="highlight c#"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="keyword">void</span> <span class="title">SetTopOffset</span>(<span class="params">Wall wall, <span class="built_in">double</span> dOffsetInches</span>)</span></span><br><span class="line">&#123;</span><br><span class="line">    <span class="comment">// convert user-defined offset value to feet from inches prior to setting</span></span><br><span class="line">    <span class="built_in">double</span> dOffsetFeet = UnitUtils.Convert(dOffsetInches,</span><br><span class="line">                                            DisplayUnitType.DUT_DECIMAL_INCHES,</span><br><span class="line">                                            DisplayUnitType.DUT_DECIMAL_FEET);</span><br><span class="line"></span><br><span class="line">    Parameter paramTopOffset = wall.get_Parameter(BuiltInParameter.WALL_TOP_OFFSET);</span><br><span class="line">    paramTopOffset.Set(dOffsetFeet);</span><br><span class="line"></span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<p>单元格式设置和解析</p>
<p>另一个实用程序类 UnitFormatUtils 可以格式化数据或分析格式化单元数据。</p>
<p>重载方法 Format() 可用于根据格式设置选项将值格式化为字符串，如以下示例所示。检索材料密度，然后使用 Format() 方法将该值转换为用户友好的单位值。</p>
<p>代码区域：将值格式化为字符串</p>
<figure class="highlight c#"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br><span class="line">23</span><br><span class="line">24</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="keyword">void</span> <span class="title">DisplayDensityOfMaterial</span>(<span class="params">Material material</span>)</span></span><br><span class="line">&#123;</span><br><span class="line">    <span class="built_in">double</span> density = <span class="number">0</span>;</span><br><span class="line">    <span class="comment">// get structural asset of material in order to get the density</span></span><br><span class="line">    ElementId strucAssetId = material.StructuralAssetId;</span><br><span class="line">    <span class="keyword">if</span> (strucAssetId != ElementId.InvalidElementId)</span><br><span class="line">    &#123;</span><br><span class="line">        PropertySetElement pse = material.Document.GetElement(strucAssetId) <span class="keyword">as</span> PropertySetElement;</span><br><span class="line">        <span class="keyword">if</span> (pse != <span class="literal">null</span>)</span><br><span class="line">        &#123;</span><br><span class="line">            StructuralAsset asset = pse.GetStructuralAsset();</span><br><span class="line"></span><br><span class="line">            density = asset.Density;</span><br><span class="line">            <span class="comment">// convert the density value to a user readable string that includes the units</span></span><br><span class="line">            Units units = material.Document.GetUnits();</span><br><span class="line">            <span class="comment">// false for maxAccuracy means accuracy specified by the FormatOptions should be used</span></span><br><span class="line">            <span class="comment">// false for forEditing since this will be for display only and no formatting modifications are necessary</span></span><br><span class="line">            <span class="built_in">string</span> strDensity = UnitFormatUtils.Format(units, UnitType.UT_UnitWeight, density, <span class="literal">false</span>, <span class="literal">false</span>);</span><br><span class="line">            <span class="built_in">string</span> msg = <span class="built_in">string</span>.Format(<span class="string">&quot;Raw Value: &#123;0&#125;\r\nFormatted Value: &#123;1&#125;&quot;</span>, density, strDensity);</span><br><span class="line">            TaskDialog.Show(<span class="string">&quot;Material Density&quot;</span>, msg);</span><br><span class="line">        &#125;</span><br><span class="line">    &#125;</span><br><span class="line"></span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<p>重载的 UnitFormatUtils.TryParse() 方法使用指定单位类型的 Revit 内部单位（如果可能）将格式化字符串（包括单位）解析为值。以下示例采用用户输入的长度值（假定为数字和长度单位），并尝试将其分析为长度值。出于演示目的，将结果与 TaskDialog 中的输入字符串进行比较。</p>
<p>代码区域：解析字符串</p>
<figure class="highlight c#"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="built_in">double</span> <span class="title">GetLengthInput</span>(<span class="params">Document document, String userInputLength</span>)</span></span><br><span class="line">&#123;</span><br><span class="line">    <span class="built_in">double</span> dParsedLength = <span class="number">0</span>;</span><br><span class="line">    Units units = document.GetUnits();</span><br><span class="line">    <span class="comment">// try to parse a user entered string (i.e. 100 mm, 1&#x27;6&quot;)</span></span><br><span class="line">    <span class="built_in">bool</span> parsed = UnitFormatUtils.TryParse(units, UnitType.UT_Length, userInputLength, <span class="keyword">out</span> dParsedLength);</span><br><span class="line">    <span class="keyword">if</span> (parsed == <span class="literal">true</span>)</span><br><span class="line">    &#123;</span><br><span class="line">        <span class="built_in">string</span> msg = <span class="built_in">string</span>.Format(<span class="string">&quot;User Input: &#123;0&#125;\r\nParsed value: &#123;1&#125;&quot;</span>, userInputLength, dParsedLength);</span><br><span class="line">        TaskDialog.Show(<span class="string">&quot;Parsed Data&quot;</span>, msg);</span><br><span class="line">    &#125;</span><br><span class="line"></span><br><span class="line">    <span class="keyword">return</span> dParsedLength;</span><br><span class="line"></span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<h2 id="注：翻译自Revit-API-Developers-Guide"><a href="#注：翻译自Revit-API-Developers-Guide" class="headerlink" title="注：翻译自Revit API Developers Guide"></a><em><strong>注：</strong></em>翻译自<a target="_blank" rel="noopener" href="https://help.autodesk.com/view/RVT/2018/ENU/?guid=Revit_API_Revit_API_Developers_Guide_html">Revit API Developers Guide</a></h2></article><div class="tag_share"><div class="post-meta__tag-list"><a class="post-meta__tags" href="/tags/Revit/">Revit</a></div><div class="post-share"><div class="social-share" data-image="/images/4stars.png" data-sites="facebook,twitter,wechat,weibo,qq"></div><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/butterfly-extsrc/sharejs/dist/css/share.min.css" media="print" onload="this.media='all'"><script src="https://cdn.jsdelivr.net/npm/butterfly-extsrc/sharejs/dist/js/social-share.min.js" defer></script></div></div><nav class="pagination-post" id="pagination"><a class="pagination-related" href="/2024/11/26/Revit%E4%BA%8C%E5%BC%80%E6%8C%87%E5%8D%97/04%E5%85%83%E7%B4%A0%E8%A6%81%E7%82%B9/" title="04元素要点"><div class="cover" style="background: var(--default-bg-color)"></div><div class="info"><div class="info-1"><div class="info-item-1">上一篇</div><div class="info-item-2">04元素要点</div></div><div class="info-2"><div class="info-item-1">元素要点元素对应于单个建筑或绘图构件，例如门、墙或尺寸标注。此外，元素可以是门类型、视图或材质定义。 元素分类Revit 图元分为六组：模型、草图、视图、组、注释和信息。每个组都包含相关的元素及其相应的符号。 模型元素模型元素表示建筑项目中存在的物理项。“模型元素”组中的元素可以细分为以下元素： 族实例 - 族实例包含族实例对象。可以将族对象载入到项目中，也可以从族样板创建族对象。有关更多信息，请参阅系列实例。 主体图元 - 主体图元包含系统族对象，这些对象可以包含其他模型图元，例如墙、屋顶、天花板和楼板。有关主体图元的更多信息，请参见墙、楼板、屋顶和洞口。 结构元素-结构图元包含仅用于 Revit 结构特征的图元。有关 Structure Elements 的更多信息，请参见 Structural Engineering。 视图元素视图图元表示在 Revit 中查看其他对象并与其他对象交互的方式。有关更多信息，请参阅视图。 组元素组图元表示辅助图元，例如 Revit...</div></div></div></a><a class="pagination-related" href="/2024/11/23/Revit%E4%BA%8C%E5%BC%80%E6%8C%87%E5%8D%97/33%E5%91%BD%E4%BB%A4/" title="33命令"><div class="cover" style="background: var(--default-bg-color)"></div><div class="info text-right"><div class="info-1"><div class="info-item-1">下一篇</div><div class="info-item-2">33命令</div></div><div class="info-2"><div class="info-item-1">命令Revit API 提供对现有 Revit 命令的访问，这些命令位于选项卡、应用程序菜单或右键单击菜单中。使用 API 处理 Revit 命令的主要方法是替换现有命令实现或发布命令。 替代 Revit 命令AddInCommandBinding 类可用于替代 Revit 中的现有命令。它有三个与替换现有命令实现相关的事件。  BeforeExecuted - 此只读事件在关联命令执行之前发生。应用程序可以对此事件做出反应，但不能更改文档或影响命令的调用。 CanExecute - 当关联的命令启动检查以确定是否可以在命令目标上执行命令时出现。 Executed - 当执行关联的命令时，将发生此事件，并且应在此处执行任何覆盖实现。  要创建 commandbinding，请调用 UIApplication.CreateAddInCommandBinding（） 或 UIControlledApplication.CreateAddInCommandBinding（）。这两种方法都需要 RevitCommandId ID 来标识要替换的命令处理程序。RevitCommandId...</div></div></div></a></nav><div class="relatedPosts"><div class="headline"><i class="fas fa-thumbs-up fa-fw"></i><span>相关推荐</span></div><div class="relatedPosts-list"><a class="pagination-related" href="/2024/12/20/RevitApi%E5%90%88%E9%9B%86/Autodesk.%20Revit.DB%20ElementTransformUtils/" title="Autodesk.Revit.DB ElementTransformUtils"><div class="cover" style="background: var(--default-bg-color)"></div><div class="info text-center"><div class="info-1"><div class="info-item-1"><i class="far fa-calendar-alt fa-fw"></i> 2024-12-20</div><div class="info-item-2">Autodesk.Revit.DB ElementTransformUtils</div></div><div class="info-2"><div class="info-item-1">Autodesk. Revit.DB ElementTransformUtils允许元素转换的实用程序集合（例如移动，旋转，镜像和复制）。 语法1public static class ElementTransformUtils    继承层次结构 System Object Autodesk.Revit.DB ElementTransformUtils   方法CanMirrorElement确定是否可以镜像元素。 CanMirrorElements确定是否可以镜像元素。 CopyElement复制元素并将副本放置在给定转换指示的位置。 CopyElements(Document, ICollection ElementId , XYZ)复制一组元素，并将副本放置在给定指示的位置。 CopyElements(Document, ICollection ElementId , Document, Transform, CopyPasteOptions)将一组元素从源文档复制到目标文档。 CopyElements(View, ICollection ElementId ,...</div></div></div></a><a class="pagination-related" href="/2024/11/18/RevitApi%E5%90%88%E9%9B%86/Autodesk.Revit.DB%20CurveArray/" title="Autodesk.Revit.DB CurveArray"><div class="cover" style="background: var(--default-bg-color)"></div><div class="info text-center"><div class="info-1"><div class="info-item-1"><i class="far fa-calendar-alt fa-fw"></i> 2024-11-18</div><div class="info-item-2">Autodesk.Revit.DB CurveArray</div></div><div class="info-2"><div class="info-item-1">Autodesk.Revit.DB CurveArray可以包含曲线的数组。 语法1public class CurveArray : APIObject, IEnumerable  继承层次结构System Object ​	Autodesk.Revit.DB APIObject ​		Autodesk.Revit.DB CurveArray 另见CurveArray Members Autodesk.Revit.DB Namespace 构造函数CurveArray创建CurveArray类的新实例 方法Append将曲线添加到数组的末尾。 Clear从数组中删除每条曲线，使其为空。 ForwardIterator将一个向前移动的迭代器添加到数组中。 GetEnumerator将一个向前移动的迭代器添加到数组中。 Insert将指定的曲线插入数组。 ReverseIterator返回一个向后移动的迭代器到数组。 属性IsEmpty测试数组是否为空。 Item获取或设置数组中指定索引处的曲线。 Size返回数组中的曲线数。 注：翻译自Revit Api docs 2018</div></div></div></a><a class="pagination-related" href="/2024/10/30/RevitApi%E5%90%88%E9%9B%86/Autodesk.Revit.DB%20Document/" title="Autodesk.Revit.DB Document"><div class="cover" style="background: var(--default-bg-color)"></div><div class="info text-center"><div class="info-1"><div class="info-item-1"><i class="far fa-calendar-alt fa-fw"></i> 2024-10-30</div><div class="info-item-2">Autodesk.Revit.DB Document</div></div><div class="info-2"><div class="info-item-1">Autodesk.Revit.DB Document表示打开的 Autodesk Revit 项目的对象。 语法1public class Document : IDisposable    附注Document 对象表示 Autodesk Revit 项目。Revit 可以打开多个项目，并打开这些项目的多个视图。活动视图或最顶层视图将是活动项目，因此是可从 Application 对象获得的活动文档。 继承层次结构 System Object Autodesk.Revit.DB Document Autodesk.Revit.DB.Macros DocumentEntryPoint  方法AcquireCoordinates 不知道是啥，API没给描述  AutoJoinElements 强制 Revit...</div></div></div></a><a class="pagination-related" href="/2024/12/10/RevitApi%E5%90%88%E9%9B%86/Autodesk.Revit.DB%20Opening/" title="Autodesk.Revit.DB Opening"><div class="cover" style="background: var(--default-bg-color)"></div><div class="info text-center"><div class="info-1"><div class="info-item-1"><i class="far fa-calendar-alt fa-fw"></i> 2024-12-10</div><div class="info-item-2">Autodesk.Revit.DB Opening</div></div><div class="info-2"><div class="info-item-1">Autodesk.Revit.DB OpeningAutodesk Revit项目或族文档中的洞口。 语法1public class Opening : Element  附注该对象表示各种不同类型的洞口：  墙中由修订项目中的两个边界点创建的矩形洞口。 由应用于屋顶、楼板、天花板、梁、支撑或柱的一组曲线创建的洞口。 一个垂直的竖井开口延伸到一个或多个水平。 在族文档中的墙或天花板上创建的简单洞口。  根据打开的类型，此类的某些属性将不可用。 这个对象派生自Element基对象，并且支持该对象的所有方法，例如检索该对象的参数的能力。此对象还支持访问结构分析模型，但此功能仅适用于Autodesk Revit Structure。 示例123456789101112131415161718192021222324252627282930313233343536373839404142434445464748495051### private void Getinfo_Opening(Opening opening)&#123;    string message =...</div></div></div></a><a class="pagination-related" href="/2024/12/10/RevitApi%E5%90%88%E9%9B%86/Autodesk.Revit.DB%20ReferenceIntersector/" title="Autodesk.Revit.DB ReferenceIntersector"><div class="cover" style="background: var(--default-bg-color)"></div><div class="info text-center"><div class="info-1"><div class="info-item-1"><i class="far fa-calendar-alt fa-fw"></i> 2024-12-10</div><div class="info-item-2">Autodesk.Revit.DB ReferenceIntersector</div></div><div class="info-2"><div class="info-item-1">Autodesk.Revit.DB ReferenceIntersector用于查找和返回与从原点和方向创建的射线相交的元素的类。 语法1public class ReferenceIntersector : IDisposable    附注可以构造此类的实例，以返回与由原点和方向创建的射线，或者基于过滤和标志返回元素的子集。 调用者可以选择使用ElementFilter过滤结果，或者通过应用特定的可接受的元素。 调用方还可以指定要返回的对象的类型， 整个元素、几何体对象或其组合。 在所有情况下，要求调用者提供 用于评估的3D视图;输入视图上的视图和可见性设置将确定 返回特定元素（例如，此工具永远不会返回隐藏元素、 和几何图形位于视图剖面框之外的元素）。 该类配置为可以构建单个实例，并用于对多个不同光线进行多次评估。在同一个 ReferenceIntersector 上的调用之间，评估结果不会被保留。 该类还提供了一个选项，用于返回在Revit链接中遇到的图元结果。 当设置 FindReferencesInRevitLinks 标志...</div></div></div></a><a class="pagination-related" href="/2024/12/20/RevitApi%E5%90%88%E9%9B%86/Autodesk.Revit.DB%20Transform/" title="Autodesk.Revit.DB Transform"><div class="cover" style="background: var(--default-bg-color)"></div><div class="info text-center"><div class="info-1"><div class="info-item-1"><i class="far fa-calendar-alt fa-fw"></i> 2024-12-20</div><div class="info-item-2">Autodesk.Revit.DB Transform</div></div><div class="info-2"><div class="info-item-1">Autodesk.Revit.DB Transform仿射三维空间的一个变换。 语法public class Transform : APIObject示例12345678910111213141516171819202122### public static XYZ TransformPoint(XYZ point, Transform transform)&#123;    double x = point.X;    double y = point.Y;    double z = point.Z;    //transform basis of the old coordinate system in the new coordinate // system    XYZ b0 = transform.get_Basis(0);    XYZ b1 = transform.get_Basis(1);    XYZ b2 = transform.get_Basis(2);    XYZ origin = transform.Origin;       ...</div></div></div></a></div></div><hr class="custom-hr"/><div id="post-comment"><div class="comment-head"><div class="comment-headline"><i class="fas fa-comments fa-fw"></i><span> 评论</span></div></div><div class="comment-wrap"><div><div id="giscus-wrap"></div></div></div></div></div><div class="aside-content" id="aside-content"><div class="card-widget card-info text-center"><div class="avatar-img"><img src="/images/4stars.png" onerror="this.onerror=null;this.src='/img/friend_404.gif'" alt="avatar"/></div><div class="author-info-name">funtim41@gmail.com</div><div class="author-info-description">实践-认识-再实践-再认识</div><div class="site-data"><a href="/archives/"><div class="headline">文章</div><div class="length-num">58</div></a><a href="/tags/"><div class="headline">标签</div><div class="length-num">5</div></a><a href="/categories/"><div class="headline">分类</div><div class="length-num">7</div></a></div><a id="card-info-btn" target="_blank" rel="noopener" href="https://github.com/FunTim41"><i class="fab fa-github"></i><span>Follow Me</span></a><div class="card-info-social-icons"><a class="social-icon" href="https://github.com/FunTim41" target="_blank" title="Github"><i class="fab fa-github" style="color: #FFFFFF;"></i></a></div></div><div class="card-widget card-announcement"><div class="item-headline"><i class="fas fa-bullhorn fa-shake"></i><span>公告</span></div><div class="announcement_content">This is my Blog</div></div><div class="sticky_layout"><div class="card-widget" id="card-toc"><div class="item-headline"><i class="fas fa-stream"></i><span>目录</span><span class="toc-percentage"></span></div><div class="toc-content"><ol class="toc"><li class="toc-item toc-level-1"><a class="toc-link" href="#Application%E5%8F%8ADocument"><span class="toc-number">1.</span> <span class="toc-text">Application及Document</span></a><ol class="toc-child"><li class="toc-item toc-level-2"><a class="toc-link" href="#Applicaion%E5%8A%9F%E8%83%BD"><span class="toc-number">1.1.</span> <span class="toc-text">Applicaion功能</span></a><ol class="toc-child"><li class="toc-item toc-level-4"><a class="toc-link" href="#Application-%E5%BA%94%E7%94%A8"><span class="toc-number">1.1.0.1.</span> <span class="toc-text">Application 应用</span></a></li><li class="toc-item toc-level-4"><a class="toc-link" href="#%E5%BA%94%E7%94%A8%E7%A8%8B%E5%BA%8F%E7%89%88%E6%9C%AC%E4%BF%A1%E6%81%AF"><span class="toc-number">1.1.0.2.</span> <span class="toc-text">应用程序版本信息</span></a></li><li class="toc-item toc-level-4"><a class="toc-link" href="#%E5%BA%94%E7%94%A8%E7%A8%8B%E5%BA%8F%E8%8C%83%E5%9B%B4%E7%9A%84%E8%AE%BE%E7%BD%AE"><span class="toc-number">1.1.0.3.</span> <span class="toc-text">应用程序范围的设置</span></a></li><li class="toc-item toc-level-4"><a class="toc-link" href="#%E5%BA%93%E5%86%85%E5%AE%B9"><span class="toc-number">1.1.0.4.</span> <span class="toc-text">库内容</span></a></li><li class="toc-item toc-level-4"><a class="toc-link" href="#%E5%9B%BE%E5%BD%A2%E6%98%BE%E7%A4%BA"><span class="toc-number">1.1.0.5.</span> <span class="toc-text">图形显示</span></a></li><li class="toc-item toc-level-4"><a class="toc-link" href="#%E6%96%87%E6%A1%A3%E7%AE%A1%E7%90%86"><span class="toc-number">1.1.0.6.</span> <span class="toc-text">文档管理</span></a></li><li class="toc-item toc-level-4"><a class="toc-link" href="#%E4%BC%9A%E8%AF%9D%E4%BF%A1%E6%81%AF"><span class="toc-number">1.1.0.7.</span> <span class="toc-text">会话信息</span></a></li><li class="toc-item toc-level-4"><a class="toc-link" href="#%E7%99%BB%E5%BD%95%E4%BF%A1%E6%81%AF"><span class="toc-number">1.1.0.8.</span> <span class="toc-text">登录信息</span></a></li><li class="toc-item toc-level-4"><a class="toc-link" href="#%E5%85%B1%E4%BA%AB%E5%8F%82%E6%95%B0%E7%AE%A1%E7%90%86"><span class="toc-number">1.1.0.9.</span> <span class="toc-text">共享参数管理</span></a></li><li class="toc-item toc-level-4"><a class="toc-link" href="#%E4%BA%8B%E4%BB%B6"><span class="toc-number">1.1.0.10.</span> <span class="toc-text">事件</span></a></li><li class="toc-item toc-level-4"><a class="toc-link" href="#%E5%88%9B%E9%80%A0"><span class="toc-number">1.1.0.11.</span> <span class="toc-text">创造</span></a></li><li class="toc-item toc-level-4"><a class="toc-link" href="#%E6%96%AD%E5%BC%80%E8%BF%9E%E6%8E%A5%E8%AD%A6%E5%91%8A"><span class="toc-number">1.1.0.12.</span> <span class="toc-text">断开连接警告</span></a></li><li class="toc-item toc-level-4"><a class="toc-link" href="#UIApplication"><span class="toc-number">1.1.0.13.</span> <span class="toc-text">UIApplication</span></a></li><li class="toc-item toc-level-4"><a class="toc-link" href="#%E6%8F%92%E4%BB%B6%E7%AE%A1%E7%90%86"><span class="toc-number">1.1.0.14.</span> <span class="toc-text">插件管理</span></a></li><li class="toc-item toc-level-4"><a class="toc-link" href="#%E5%8A%9F%E8%83%BD%E5%8C%BA%E9%9D%A2%E6%9D%BF%E5%AE%9E%E7%94%A8%E7%A8%8B%E5%BA%8F"><span class="toc-number">1.1.0.15.</span> <span class="toc-text">功能区面板实用程序</span></a></li><li class="toc-item toc-level-4"><a class="toc-link" href="#%E8%8C%83%E5%9B%B4"><span class="toc-number">1.1.0.16.</span> <span class="toc-text">范围</span></a></li><li class="toc-item toc-level-4"><a class="toc-link" href="#%E4%BA%8B%E4%BB%B6-1"><span class="toc-number">1.1.0.17.</span> <span class="toc-text">事件</span></a></li></ol></li><li class="toc-item toc-level-3"><a class="toc-link" href="#%E5%AD%A6%E7%A7%91%E6%8E%A7%E5%88%B6"><span class="toc-number">1.1.1.</span> <span class="toc-text">学科控制</span></a></li><li class="toc-item toc-level-3"><a class="toc-link" href="#%E5%A6%82%E4%BD%95%E4%BD%BF%E7%94%A8Application%E5%B1%9E%E6%80%A7%E4%B8%BA%E5%A4%96%E6%8E%A5%E7%A8%8B%E5%BA%8F%E5%BC%BA%E5%88%B6%E5%AE%9E%E6%96%BD%E6%AD%A3%E7%A1%AE%E7%9A%84%E7%89%88%E6%9C%AC"><span class="toc-number">1.1.2.</span> <span class="toc-text">如何使用Application属性为外接程序强制实施正确的版本</span></a></li></ol></li><li class="toc-item toc-level-2"><a class="toc-link" href="#Document%E5%8A%9F%E8%83%BD"><span class="toc-number">1.2.</span> <span class="toc-text">Document功能</span></a><ol class="toc-child"><li class="toc-item toc-level-3"><a class="toc-link" href="#Default-Types-%E9%BB%98%E8%AE%A4%E7%B1%BB%E5%9E%8B"><span class="toc-number">1.2.1.</span> <span class="toc-text">Default Types 默认类型</span></a></li></ol></li><li class="toc-item toc-level-2"><a class="toc-link" href="#%E6%96%87%E6%A1%A3%E5%92%8C%E6%96%87%E4%BB%B6%E7%AE%A1%E7%90%86"><span class="toc-number">1.3.</span> <span class="toc-text">文档和文件管理</span></a></li><li class="toc-item toc-level-2"><a class="toc-link" href="#%E8%AE%BE%E7%BD%AE"><span class="toc-number">1.4.</span> <span class="toc-text">设置</span></a></li><li class="toc-item toc-level-2"><a class="toc-link" href="#%E5%8D%95%E4%BD%8D"><span class="toc-number">1.5.</span> <span class="toc-text">单位</span></a></li><li class="toc-item toc-level-2"><a class="toc-link" href="#%E6%B3%A8%EF%BC%9A%E7%BF%BB%E8%AF%91%E8%87%AARevit-API-Developers-Guide"><span class="toc-number">1.6.</span> <span class="toc-text">注：翻译自Revit API Developers Guide</span></a></li></ol></li></ol></div></div><div class="card-widget card-recent-post"><div class="item-headline"><i class="fas fa-history"></i><span>最新文章</span></div><div class="aside-list"><div class="aside-list-item no-cover"><div class="content"><a class="title" href="/2025/01/16/Revit%E4%BA%8C%E5%BC%80%E7%A4%BA%E4%BE%8B/Revit%E4%B8%8EExcel%E4%BA%A4%E4%BA%92/" title="Revit与Excel交互">Revit与Excel交互</a><time datetime="2025-01-16T08:43:45.327Z" title="更新于 2025-01-16 16:43:45">2025-01-16</time></div></div><div class="aside-list-item no-cover"><div class="content"><a class="title" href="/2025/01/14/ObjectARX%EF%BC%9AManaged.NET%E5%BC%80%E5%8F%91%E4%BA%BA%E5%91%98%E6%8C%87%E5%8D%97/03%E5%88%9B%E5%BB%BA%E5%92%8C%E7%BC%96%E8%BE%91AutoCAD%E5%9B%BE%E5%85%83%EF%BC%88.NET%EF%BC%89/" title="03创建和编辑AutoCAD图元（.NET）">03创建和编辑AutoCAD图元（.NET）</a><time datetime="2025-01-14T04:28:05.785Z" title="更新于 2025-01-14 12:28:05">2025-01-14</time></div></div><div class="aside-list-item no-cover"><div class="content"><a class="title" href="/2025/01/13/ObjectARX%EF%BC%9AManaged.NET%E5%BC%80%E5%8F%91%E4%BA%BA%E5%91%98%E6%8C%87%E5%8D%97/02%E6%8E%A7%E5%88%B6AutoCAD%E7%8E%AF%E5%A2%83%EF%BC%88.NET%EF%BC%89/" title="02控制AutoCAD环境（.NET）">02控制AutoCAD环境（.NET）</a><time datetime="2025-01-14T02:31:41.869Z" title="更新于 2025-01-14 10:31:41">2025-01-14</time></div></div><div class="aside-list-item no-cover"><div class="content"><a class="title" href="/2025/01/12/ObjectARX%EF%BC%9AManaged.NET%E5%BC%80%E5%8F%91%E4%BA%BA%E5%91%98%E6%8C%87%E5%8D%97/01AutoCAD.NET%20API%EF%BC%88.NET%EF%BC%89%E7%9A%84%E5%9F%BA%E7%A1%80%E7%9F%A5%E8%AF%86/" title="01AutoCAD .NET API（.NET）的基础知识">01AutoCAD .NET API（.NET）的基础知识</a><time datetime="2025-01-14T02:31:29.466Z" title="更新于 2025-01-14 10:31:29">2025-01-14</time></div></div><div class="aside-list-item no-cover"><div class="content"><a class="title" href="/2024/12/19/RevitApi%E5%90%88%E9%9B%86/Autodesk.Revit.UI.Selection%20Namespace/" title="Autodesk.Revit.UI.Selection">Autodesk.Revit.UI.Selection</a><time datetime="2025-01-13T14:24:17.222Z" title="更新于 2025-01-13 22:24:17">2025-01-13</time></div></div></div></div></div></div></main><footer id="footer" style="background-image: url(/images/topback.jpg);"><div id="footer-wrap"><div class="copyright">&copy;2024 - 2025 By funtim41@gmail.com</div><div class="framework-info"><span>框架 </span><a target="_blank" rel="noopener" href="https://hexo.io">Hexo</a><span class="footer-separator">|</span><span>主题 </span><a target="_blank" rel="noopener" href="https://github.com/jerryc127/hexo-theme-butterfly">Butterfly</a></div><div class="footer_custom_text">学而不思则罔，思而不学则殆。</div></div></footer></div><div id="rightside"><div id="rightside-config-hide"><button id="readmode" type="button" title="阅读模式"><i class="fas fa-book-open"></i></button><button id="darkmode" type="button" title="日间和夜间模式切换"><i class="fas fa-adjust"></i></button><button id="hide-aside-btn" type="button" title="单栏和双栏切换"><i class="fas fa-arrows-alt-h"></i></button></div><div id="rightside-config-show"><button id="rightside-config" type="button" title="设置"><i class="fas fa-cog fa-spin"></i></button><button class="close" id="mobile-toc-button" type="button" title="目录"><i class="fas fa-list-ul"></i></button><a id="to_comment" href="#post-comment" title="前往评论"><i class="fas fa-comments"></i></a><button id="go-up" type="button" title="回到顶部"><span class="scroll-percent"></span><i class="fas fa-arrow-up"></i></button></div></div><div><script src="/js/utils.js"></script><script src="/js/main.js"></script><script src="https://cdn.jsdelivr.net/npm/node-snackbar/dist/snackbar.min.js"></script><script>(() => {
  const panguFn = () => {
    if (typeof pangu === 'object') pangu.autoSpacingPage()
    else {
      btf.getScript('https://cdn.jsdelivr.net/npm/pangu/dist/browser/pangu.min.js')
        .then(() => {
          pangu.autoSpacingPage()
        })
    }
  }

  const panguInit = () => {
    if (false){
      GLOBAL_CONFIG_SITE.isPost && panguFn()
    } else {
      panguFn()
    }
  }

  btf.addGlobalFn('pjaxComplete', panguInit, 'pangu')
  document.addEventListener('DOMContentLoaded', panguInit)
})()</script><div class="js-pjax"><script>(() => {
  const isShuoshuo = GLOBAL_CONFIG_SITE.isShuoshuo
  const option = null

  const getGiscusTheme = theme => theme === 'dark' ? 'dark' : 'light'

  const createScriptElement = config => {
    const ele = document.createElement('script')
    Object.entries(config).forEach(([key, value]) => {
      ele.setAttribute(key, value)
    })
    return ele
  }

  const loadGiscus = (el = document, key) => {
    const mappingConfig = isShuoshuo
      ? { 'data-mapping': 'specific', 'data-term': key }
      : { 'data-mapping': (option && option['data-mapping']) || 'pathname' }

    const giscusConfig = {
      src: 'https://giscus.app/client.js',
      'data-repo': 'FunTim41/funtim41.github.io',
      'data-repo-id': 'R_kgDONjG8ww',
      'data-category-id': 'DIC_kwDONjG8w84Cllg2',
      'data-theme': getGiscusTheme(document.documentElement.getAttribute('data-theme')),
      'data-reactions-enabled': '1',
      crossorigin: 'anonymous',
      async: true,
      ...option,
      ...mappingConfig
    }

    const scriptElement = createScriptElement(giscusConfig)

    el.querySelector('#giscus-wrap').appendChild(scriptElement)

    if (isShuoshuo) {
      window.shuoshuoComment.destroyGiscus = () => {
        if (el.children.length) {
          el.innerHTML = ''
          el.classList.add('no-comment')
        }
      }
    }
  }

  const changeGiscusTheme = theme => {
    const iframe = document.querySelector('#giscus-wrap iframe')
    if (iframe) {
      const message = {
        giscus: {
          setConfig: {
            theme: getGiscusTheme(theme)
          }
        }
      }
      iframe.contentWindow.postMessage(message, 'https://giscus.app')
    }
  }

  btf.addGlobalFn('themeChange', changeGiscusTheme, 'giscus')

  if (isShuoshuo) {
    'Giscus' === 'Giscus'
      ? window.shuoshuoComment = { loadComment: loadGiscus }
      : window.loadOtherComment = loadGiscus
    return
  }

  if ('Giscus' === 'Giscus' || !false) {
    if (false) btf.loadComment(document.getElementById('giscus-wrap'), loadGiscus)
    else loadGiscus()
  } else {
    window.loadOtherComment = loadGiscus
  }
})()</script></div><script defer="defer" id="fluttering_ribbon" mobile="false" src="https://cdn.jsdelivr.net/npm/butterfly-extsrc/dist/canvas-fluttering-ribbon.min.js"></script><script async data-pjax src="//busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js"></script><div id="local-search"><div class="search-dialog"><nav class="search-nav"><span class="search-dialog-title">搜索</span><span id="loading-status"></span><button class="search-close-button"><i class="fas fa-times"></i></button></nav><div class="text-center" id="loading-database"><i class="fas fa-spinner fa-pulse"></i><span>  数据加载中</span></div><div class="search-wrap"><div id="local-search-input"><div class="local-search-box"><input class="local-search-box--input" placeholder="搜索文章" type="text"/></div></div><hr/><div id="local-search-results"></div><div id="local-search-stats-wrap"></div></div></div><div id="search-mask"></div><script src="/js/search/local-search.js"></script></div></div></body></html>